In [1]:
from joblib import Parallel, delayed
from tqdm.notebook import tqdm

import sys
import pickle
import numpy as np
import pandas as pd
import networkx as nx
import scipy
from itertools import combinations

In [2]:
sys.path.insert(0, "src")

from grn import grn

np.random.seed(5)

In [3]:
all_results = []

for network_seed in range(10):
    np.random.seed(network_seed)

    #manually adjust GRN hyperparameters in an attempt to build GRN with more non-additive effects
    G = grn().add_structure(
        n=256,
        k=1,
        alpha=1e-99,
        beta=0.99,       # 1 - 1/r
        gamma=0.01,      # 1/r
        kappa=10,        # --w
        delta_in=100,
        delta_out=100,
    )

    G.simulate_rna(
        s=1e-4,
        dt=1e-2,
        tmax=20000,
        burnin=5000,
        tol=1e-3,
        save=True,
    )

    x_wt = np.zeros(256)
    y_wt = G.rna

    single_ko_expression = np.zeros((G.n, G.n))
    single_ko_logfc = np.zeros((G.n, G.n))
    single_ko_convergence = {}

    for gene in tqdm(range(G.n), desc=f"Network {network_seed}: single-gene KOs"):

        result = G.ko_nodes(
            genes=[gene],
            stats=("new_rna", "logfc", "convergence"),
            s=1e-4,
            dt=1e-2,
            tmax=20000,
            burnin=5000,
            tol=1e-3,
        )

        single_ko_expression[gene, :] = result["new_rna"].flatten()
        single_ko_logfc[gene, :] = result["logfc"].flatten()
        single_ko_convergence[gene] = result["convergence"]

    x_single_ko = np.eye(G.n)
    y_single_ko = single_ko_expression

    pairs = list(combinations(range(G.n), 2))

    def run_double_ko(pair):
        a, b = pair

        result = G.ko_nodes(
            genes=[a, b],
            stats=("new_rna", "logfc", "convergence"),
            s=0,
            dt=1e-2,
            tmax=20000,
            burnin=5000,
            tol=1e-3,
        )

        return (
            np.asarray(result["new_rna"]).flatten(),
            np.asarray(result["logfc"]).flatten(),
            np.asarray(result["convergence"]),
        )


    results = Parallel(
        n_jobs=64,
        pre_dispatch="n_jobs",
        prefer="processes",
        verbose=10,
    )(
        delayed(run_double_ko)(pair)
        for pair in pairs
    )

    double_expression = np.asarray(
        [r[0] for r in results],
        dtype=np.float32
    )

    double_logfc = np.asarray(
        [r[1] for r in results],
        dtype=np.float32
    )

    double_convergence = np.asarray(
        [r[2] for r in results],
        dtype=np.float32
    )


    #now prepare as training data

    pairs = np.array(
        pairs,
        dtype=np.int32
    )

    x_double_ko = np.zeros((pairs.shape[0], G.n))

    #now fill x for doubleKO with 1s

    rows = np.arange(pairs.shape[0])
    x_double_ko[rows, pairs[:, 0]] = 1.0
    x_double_ko[rows, pairs[:, 1]] = 1.0

    y_double_ko = double_expression


    # ============================================================
    # 10 TRAINING RUNS ON THIS GRN
    # ============================================================

    for training_seed in range(10):

        import torch
        from torch import nn

        torch.manual_seed(training_seed)
        device = torch.device("cpu")

        #for more precision
        #torch.backends.cuda.matmul.allow_tf32 = False
        #torch.backends.cudnn.allow_tf32 = False


        #model implementation without dropout
        model = nn.Sequential(
            nn.Linear(256, 512),
            nn.GELU(),
            nn.Linear(512, 512),
            nn.GELU(),
            nn.Linear(512, 256)
        ).to(device)

        linear = nn.Linear(256, 256).to(device)

        #implement AdamW
        import torch.optim as optim

        optimizer = optim.AdamW(
            model.parameters(),
            lr=1e-3,
            weight_decay=1e-2
        )


        #process data, standardise, put them on GPU

        rng = np.random.default_rng(training_seed)

        n_pairs = pairs.shape[0]
        nt, nv = int(0.5 * n_pairs), int(0.1 * n_pairs)

        indices = rng.permutation(n_pairs)
        test_idx = indices[:nt]
        val_idx = indices[nt:nt + nv]
        train_idx = indices[nt + nv:]

        xtr = np.concatenate(
            [x_wt[None, :], x_single_ko, x_double_ko[train_idx]],
            axis=0
        )

        ytr = np.concatenate(
            [y_wt[None, :], y_single_ko, y_double_ko[train_idx]],
            axis=0
        )

        xv = x_double_ko[val_idx]
        yv = y_double_ko[val_idx]

        x_test = x_double_ko[test_idx]
        y_test = y_double_ko[test_idx]

        mean, scale = (
            np.mean(ytr, axis=0),
            np.maximum(ytr.std(axis=0), 1e-6)
        )

        s_ytr = (ytr - mean) / scale

        xtr_t = torch.as_tensor(
            xtr,
            dtype=torch.float32,
            device=device
        )

        s_ytr_t = torch.as_tensor(
            s_ytr,
            dtype=torch.float32,
            device=device
        )

        xv_t = torch.as_tensor(
            xv,
            dtype=torch.float32,
            device=device
        )

        yv_t = torch.as_tensor(
            yv,
            dtype=torch.float32,
            device=device
        )

        x_test_t = torch.as_tensor(
            x_test,
            dtype=torch.float32,
            device=device
        )

        y_test_t = torch.as_tensor(
            y_test,
            dtype=torch.float32,
            device=device
        )

        mean_t = torch.as_tensor(
            mean,
            dtype=torch.float32,
            device=device
        )

        scale_t = torch.as_tensor(
            scale,
            dtype=torch.float32,
            device=device
        )


        import time
        import copy

        max_epochs = 3000
        batch_size = 256
        lr = 1e-3
        patience = 40
        min_lr = 1e-5
        lr_patience = 12

        best, best_epoch, stale, lr_stale = np.inf, 0, 0, 0
        history = []
        started = time.perf_counter()
        best_model_weights = None


        for epoch in range(1, max_epochs + 1):

            model.train()

            permutation = torch.randperm(
                xtr_t.shape[0],
                device=device
            )

            total = torch.zeros((), device=device)

            for start in range(
                0,
                xtr_t.shape[0],
                batch_size
            ):

                ii = permutation[start:(start + batch_size)]

                optimizer.zero_grad(set_to_none=True)

                loss = torch.mean(
                    (model(xtr_t[ii]) - s_ytr_t[ii]) ** 2
                )

                loss.backward()
                optimizer.step()

                total += loss.detach() * len(ii)

            train_loss = float(
                total.item() / xtr_t.shape[0]
            )

            model.eval()

            with torch.inference_mode():
                val_scaled = torch.cat(
                    [
                        model(chunk)
                        for chunk in xv_t.split(1024)
                    ]
                ).cpu().numpy()

            val_pred = (
                val_scaled.astype(np.float32)
                * scale
                + mean
            )

            raw_mse = float(
                np.mean((val_pred - yv) ** 2)
            )

            if (
                not np.isfinite(train_loss)
                or not np.isfinite(raw_mse)
            ):
                raise FloatingPointError(
                    f"Non-finite loss at epoch {epoch}"
                )

            history.append({
                "epoch": epoch,
                "train_scaled_mse": train_loss,
                "val_scaled_mse": float(
                    np.mean(
                        ((val_pred - yv) / scale) ** 2
                    )
                ),
                "val_raw_mse": raw_mse,
                "learning_rate": lr,
                "elapsed_seconds":
                    time.perf_counter() - started
            })

            if raw_mse < best:

                best = raw_mse
                best_epoch = epoch
                stale = 0
                lr_stale = 0

                best_model_weights = copy.deepcopy(
                    model.state_dict()
                )

            else:

                stale += 1
                lr_stale += 1

            if epoch == 1 or epoch % 10 == 0:

                print(
                    f"network {network_seed}, "
                    f"training {training_seed}, "
                    f"epoch {epoch}: "
                    f"train scaled MSE {train_loss:.6g}; "
                    f"val RMSE {raw_mse**.5:.7g}; "
                    f"lr {lr:g}; "
                    f"{time.perf_counter()-started:.0f}s",
                    flush=True
                )

            if (
                lr_stale >= lr_patience
                and lr > min_lr
            ):

                lr = max(
                    min_lr,
                    lr * .5
                )

                for group in optimizer.param_groups:
                    group["lr"] = lr

                lr_stale = 0

            if stale >= patience:
                break


        if best_model_weights is not None:
            model.load_state_dict(
                best_model_weights
            )


        from sklearn.linear_model import LinearRegression

        # 1. Initialize standard Linear Regression (no alpha/penalty)
        linear_model = LinearRegression(
            fit_intercept=True
        )

        # 2. Fit directly on the NumPy arrays
        linear_model.fit(
            xtr.astype(np.float64),
            s_ytr.astype(np.float64)
        )

        # 3. Predict and reverse normalization
        val_scaled = linear_model.predict(
            xv.astype(np.float64)
        )

        val_pred = (
            val_scaled.astype(np.float32)
            * scale
            + mean
        )

        # 4. Calculate RMSE
        raw_mse = float(
            np.mean(
                (val_pred - yv) ** 2
            )
        )

        print(
            f"Standard Linear Baseline Validation RMSE: "
            f"{raw_mse**.5:.7g}"
        )


        # 1. Generate predictions for the Test set
        model.eval()

        with torch.inference_mode():

            mlp_test_scaled = torch.cat(
                [
                    model(chunk)
                    for chunk
                    in x_test_t.split(1024)
                ]
            ).cpu().numpy()

        mlp_pred = (
            mlp_test_scaled.astype(np.float32)
            * scale
            + mean
        )


        # Retrieve linear model predictions
        linear_test_scaled = linear_model.predict(
            x_test.astype(np.float64)
        )

        linear_pred = (
            linear_test_scaled.astype(np.float32)
            * scale
            + mean
        )


        # 2. Reconstruct test pairs and baseline predictions
        test_pairs = pairs[test_idx]

        # The additive baseline is Single A + Single B - WT
        additive = (
            y_single_ko[test_pairs[:, 0]]
            + y_single_ko[test_pairs[:, 1]]
            - y_wt
        )

        y_true = y_test

        true_r = y_true - additive

        add_pair_mse = np.mean(
            true_r ** 2,
            axis=1
        )

        add_mse = float(
            np.mean(add_pair_mse)
        )


        # Helper function for Pearson correlation
        def correlation(a, b):

            a = np.asarray(a).ravel()
            b = np.asarray(b).ravel()

            if (
                np.std(a) < 1e-15
                or np.std(b) < 1e-15
            ):
                return None

            return float(
                np.corrcoef(a, b)[0, 1]
            )


        predictions = {
            "Additive Baseline": additive,
            "Linear Regression": linear_pred,
            "MLP": mlp_pred
        }

        metrics = []
        pair_losses = {}


        # 3. Calculate core metrics
        for name, pred in predictions.items():

            e2 = (pred - y_true) ** 2

            pair_losses[name] = e2.mean(axis=1)

            implied_residual = pred - additive

            mse = float(
                np.mean(e2)
            )

            pearson_corr = correlation(
                implied_residual,
                true_r
            )

            metrics.append({
                "Model": name,
                "MSE": mse,
                "RMSE": mse ** 0.5,
                "MSE Improvement vs Additive (%)":
                    100 * (1 - mse / add_mse),
                "Pearson (Implied vs True Residual)":
                    pearson_corr if pearson_corr else 0.0,
                "Fraction Pairs < Additive MSE":
                    float(
                        np.mean(
                            pair_losses[name]
                            < add_pair_mse
                        )
                    )
            })


        df = pd.DataFrame(
            metrics
        ).set_index("Model")


        # 4. Bootstrap 95% Confidence Intervals
        # for MSE Improvement (2000 resamples)

        rng = np.random.default_rng(9001)

        boot = {
            "Linear Regression": [],
            "MLP": []
        }

        for _ in range(2000):

            ii = rng.integers(
                0,
                len(test_pairs),
                size=len(test_pairs)
            )

            denom = add_pair_mse[ii].mean()

            for name in boot:

                boot[name].append(
                    100 * (
                        1
                        - pair_losses[name][ii].mean()
                        / denom
                    )
                )


        # Calculate and format CIs
        for name in boot:

            ci_lower, ci_upper = np.quantile(
                boot[name],
                [0.025, 0.975]
            )

            df.loc[
                name,
                "MSE Improv. 95% CI"
            ] = (
                f"[{ci_lower:.2f}%, "
                f"{ci_upper:.2f}%]"
            )


        df.loc[
            "Additive Baseline",
            "MSE Improv. 95% CI"
        ] = "-"


        # 5. Calculate Pearson Correlation
        # Improvement (MLP vs Linear)

        mlp_pearson = df.loc[
            "MLP",
            "Pearson (Implied vs True Residual)"
        ]

        lin_pearson = df.loc[
            "Linear Regression",
            "Pearson (Implied vs True Residual)"
        ]


        if lin_pearson != 0:

            pearson_improvement = (
                (mlp_pearson - lin_pearson)
                / abs(lin_pearson)
            ) * 100

            df.loc[
                "MLP",
                "Pearson Improv. vs Linear (%)"
            ] = pearson_improvement


        df.loc[
            "Linear Regression",
            "Pearson Improv. vs Linear (%)"
        ] = 0.0


        # Use np.nan instead of a string
        # to keep the column numerically typed
        df.loc[
            "Additive Baseline",
            "Pearson Improv. vs Linear (%)"
        ] = np.nan


        # ========================================================
        # SAVE RESULTS FROM THIS NETWORK/TRAINING RUN
        # ========================================================

        run_df = df.reset_index()

        run_df.insert(
            0,
            "Training Seed",
            training_seed
        )

        run_df.insert(
            0,
            "Network Seed",
            network_seed
        )

        all_results.append(run_df)


        # Full results accumulated so far
        all_results_df = pd.concat(
            all_results,
            ignore_index=True
        )

        # Save after every training run so that completed
        # runs are not lost if a later run fails.
        all_results_df.to_csv(
            "../grn_training_results.csv",
            index=False
        )


        # Compact one-row-per-run RMSE table
        # MLP vs regression vs additive
        rmse_by_run = all_results_df.pivot(
            index=[
                "Network Seed",
                "Training Seed"
            ],
            columns="Model",
            values="RMSE"
        ).reset_index()

        rmse_by_run.columns.name = None

        rmse_by_run.to_csv(
            "../grn_training_rmse_by_run.csv",
            index=False
        )


        # Format the DataFrame for clean output
        display_cols = [
            "RMSE",
            "MSE Improvement vs Additive (%)",
            "MSE Improv. 95% CI",
            "Pearson (Implied vs True Residual)",
            "Pearson Improv. vs Linear (%)",
            "Fraction Pairs < Additive MSE"
        ]


        print(
            f"\nNetwork seed {network_seed}, "
            f"training seed {training_seed}"
        )

        display(
            df[
                display_cols
            ].round(4).fillna("-")
        )


# ================================================================
# FINAL RESULT TABLES
# ================================================================

# 10 networks x 10 training runs x 3 models = 300 rows
all_results_df = pd.concat(
    all_results,
    ignore_index=True
)

# 100 rows, one for each Network Seed / Training Seed combination
rmse_by_run = all_results_df.pivot(
    index=[
        "Network Seed",
        "Training Seed"
    ],
    columns="Model",
    values="RMSE"
).reset_index()

rmse_by_run.columns.name = None

display(all_results_df)
display(rmse_by_run)

Network 0: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   30.7s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   31.0s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   31.2s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   31.4s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   31.6s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   32.2s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   32.8s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   33.5s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   34.0s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   34.7s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   35.5s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   36.4s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   37.2s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   38.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   38.9s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   39.7s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   40.6s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   41.5s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   42.5s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   43.7s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   44.9s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   46.0s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   47.5s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   48.6s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   50.1s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   51.4s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   52.7s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   54.2s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   55.7s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   57.0s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   58.5s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 11.5min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 12.1min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 14.0min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 14.4min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 14.5min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 14.9min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 15.3min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 15.7min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 16.1min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 17.1min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 17.3min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 17.6min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 17.7min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 17.9min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 18.0min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 18.2min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 18.3min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 18.5min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 18.6min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 18.8min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 18.9min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 19.1min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 19.2min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 19.4min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 19.5min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 19.7min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 19.9min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 20.0min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 20.2min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 20.3min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 20.5min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 20.7min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 20.8min finished

network 0, training 0, epoch 1: train scaled MSE 0.910925; val RMSE 0.1566212; lr 0.001; 1s
network 0, training 0, epoch 10: train scaled MSE 0.512312; val RMSE 0.1233028; lr 0.001; 2s
network 0, training 0, epoch 20: train scaled MSE 0.471266; val RMSE 0.1190871; lr 0.001; 5s
network 0, training 0, epoch 30: train scaled MSE 0.440797; val RMSE 0.1174908; lr 0.001; 7s
network 0, training 0, epoch 40: train scaled MSE 0.412341; val RMSE 0.1158606; lr 0.001; 10s
network 0, training 0, epoch 50: train scaled MSE 0.37279; val RMSE 0.1154633; lr 0.001; 12s
network 0, training 0, epoch 60: train scaled MSE 0.335953; val RMSE 0.1158411; lr 0.0005; 14s
network 0, training 0, epoch 70: train scaled MSE 0.308009; val RMSE 0.1161971; lr 0.0005; 17s
network 0, training 0, epoch 80: train scaled MSE 0.291441; val RMSE 0.1161266; lr 0.00025; 19s
Standard Linear Baseline Validation RMSE: 0.125638

Network seed 0, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1917,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1256,57.0504,"[56.42%, 57.62%]",0.7552,0.0,0.8392
MLP,0.1154,63.7380,"[63.12%, 64.32%]",0.7985,5.7384,0.8937

network 0, training 1, epoch 1: train scaled MSE 0.90285; val RMSE 0.1572696; lr 0.001; 0s
network 0, training 1, epoch 10: train scaled MSE 0.520094; val RMSE 0.1243996; lr 0.001; 2s
network 0, training 1, epoch 20: train scaled MSE 0.468722; val RMSE 0.1193994; lr 0.001; 5s
network 0, training 1, epoch 30: train scaled MSE 0.443484; val RMSE 0.1176323; lr 0.001; 7s
network 0, training 1, epoch 40: train scaled MSE 0.407752; val RMSE 0.1164973; lr 0.001; 9s
network 0, training 1, epoch 50: train scaled MSE 0.371861; val RMSE 0.1163059; lr 0.001; 12s
network 0, training 1, epoch 60: train scaled MSE 0.333813; val RMSE 0.1168671; lr 0.001; 14s
network 0, training 1, epoch 70: train scaled MSE 0.30399; val RMSE 0.1169034; lr 0.0005; 16s
network 0, training 1, epoch 80: train scaled MSE 0.286785; val RMSE 0.1167204; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.1258372

Network seed 0, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1921,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.1261,56.9246,"[56.35%, 57.51%]",0.7543,0.0,0.8412
MLP,0.1158,63.6320,"[63.03%, 64.23%]",0.7978,5.7651,0.9011

network 0, training 2, epoch 1: train scaled MSE 0.908498; val RMSE 0.1563896; lr 0.001; 0s
network 0, training 2, epoch 10: train scaled MSE 0.5341; val RMSE 0.1251598; lr 0.001; 2s
network 0, training 2, epoch 20: train scaled MSE 0.489569; val RMSE 0.1202165; lr 0.001; 4s
network 0, training 2, epoch 30: train scaled MSE 0.445436; val RMSE 0.1164402; lr 0.001; 7s
network 0, training 2, epoch 40: train scaled MSE 0.40764; val RMSE 0.1147314; lr 0.001; 9s
network 0, training 2, epoch 50: train scaled MSE 0.369082; val RMSE 0.1153642; lr 0.001; 11s
network 0, training 2, epoch 60: train scaled MSE 0.365261; val RMSE 0.1160778; lr 0.001; 14s
network 0, training 2, epoch 70: train scaled MSE 0.30416; val RMSE 0.1159341; lr 0.0005; 16s
network 0, training 2, epoch 80: train scaled MSE 0.286145; val RMSE 0.1156527; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.1249805

Network seed 0, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1911,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1252,57.0664,"[56.48%, 57.66%]",0.7553,0.0,0.8370
MLP,0.1150,63.7696,"[63.14%, 64.37%]",0.7991,5.7997,0.8977

network 0, training 3, epoch 1: train scaled MSE 0.908791; val RMSE 0.1556525; lr 0.001; 0s
network 0, training 3, epoch 10: train scaled MSE 0.51755; val RMSE 0.1228262; lr 0.001; 2s
network 0, training 3, epoch 20: train scaled MSE 0.478935; val RMSE 0.1185919; lr 0.001; 4s
network 0, training 3, epoch 30: train scaled MSE 0.430763; val RMSE 0.1152665; lr 0.001; 7s
network 0, training 3, epoch 40: train scaled MSE 0.394971; val RMSE 0.1148955; lr 0.001; 9s
network 0, training 3, epoch 50: train scaled MSE 0.351598; val RMSE 0.1147242; lr 0.001; 11s
network 0, training 3, epoch 60: train scaled MSE 0.310573; val RMSE 0.1147955; lr 0.0005; 13s
network 0, training 3, epoch 70: train scaled MSE 0.292246; val RMSE 0.1149455; lr 0.00025; 15s
network 0, training 3, epoch 80: train scaled MSE 0.283061; val RMSE 0.1151264; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.124755

Network seed 0, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1920,0.0000,-,0.000,-,0.0000
Linear Regression,0.1254,57.3354,"[56.71%, 57.91%]",0.757,0.0,0.8382
MLP,0.1157,63.6603,"[63.02%, 64.28%]",0.798,5.4085,0.9000

network 0, training 4, epoch 1: train scaled MSE 0.911527; val RMSE 0.1573465; lr 0.001; 0s
network 0, training 4, epoch 10: train scaled MSE 0.509893; val RMSE 0.1236149; lr 0.001; 2s
network 0, training 4, epoch 20: train scaled MSE 0.464589; val RMSE 0.1191256; lr 0.001; 5s
network 0, training 4, epoch 30: train scaled MSE 0.429529; val RMSE 0.1164612; lr 0.001; 7s
network 0, training 4, epoch 40: train scaled MSE 0.393397; val RMSE 0.1155743; lr 0.001; 9s
network 0, training 4, epoch 50: train scaled MSE 0.350219; val RMSE 0.115419; lr 0.001; 11s
network 0, training 4, epoch 60: train scaled MSE 0.310707; val RMSE 0.1158322; lr 0.0005; 13s
network 0, training 4, epoch 70: train scaled MSE 0.287146; val RMSE 0.1159681; lr 0.00025; 16s
network 0, training 4, epoch 80: train scaled MSE 0.27431; val RMSE 0.1162177; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.1256415

Network seed 0, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1925,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1263,56.9411,"[56.37%, 57.54%]",0.7544,0.0,0.8483
MLP,0.1161,63.6046,"[63.00%, 64.23%]",0.7979,5.7734,0.8991

network 0, training 5, epoch 1: train scaled MSE 0.909276; val RMSE 0.1575789; lr 0.001; 0s
network 0, training 5, epoch 10: train scaled MSE 0.5172; val RMSE 0.1250323; lr 0.001; 2s
network 0, training 5, epoch 20: train scaled MSE 0.474967; val RMSE 0.1202454; lr 0.001; 4s
network 0, training 5, epoch 30: train scaled MSE 0.439081; val RMSE 0.1174711; lr 0.001; 7s
network 0, training 5, epoch 40: train scaled MSE 0.407684; val RMSE 0.1168957; lr 0.001; 9s
network 0, training 5, epoch 50: train scaled MSE 0.402942; val RMSE 0.1160888; lr 0.001; 11s
network 0, training 5, epoch 60: train scaled MSE 0.345905; val RMSE 0.1164596; lr 0.001; 14s
network 0, training 5, epoch 70: train scaled MSE 0.317173; val RMSE 0.115929; lr 0.0005; 16s
network 0, training 5, epoch 80: train scaled MSE 0.29832; val RMSE 0.116175; lr 0.0005; 18s
network 0, training 5, epoch 90: train scaled MSE 0.287021; val RMSE 0.1164246; lr 0.00025; 20s
network 0, training 5, epoch 100: train scaled MSE 0.279828; val RMSE 0.1164587; lr 0.000125; 23s
network 0, training 5, epoch 110: train scaled MSE 0.274986; val RMSE 0.1164478; lr 6.25e-05; 25s
Standard Linear Baseline Validation RMSE: 0.1258845

Network seed 0, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1928,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1264,57.0641,"[56.46%, 57.64%]",0.7552,0.0,0.8403
MLP,0.1156,64.0531,"[63.40%, 64.66%]",0.8006,6.0131,0.9017

network 0, training 6, epoch 1: train scaled MSE 0.912162; val RMSE 0.1578977; lr 0.001; 0s
network 0, training 6, epoch 10: train scaled MSE 0.515561; val RMSE 0.1244875; lr 0.001; 2s
network 0, training 6, epoch 20: train scaled MSE 0.471731; val RMSE 0.1203601; lr 0.001; 5s
network 0, training 6, epoch 30: train scaled MSE 0.438552; val RMSE 0.1166404; lr 0.001; 7s
network 0, training 6, epoch 40: train scaled MSE 0.404532; val RMSE 0.1164775; lr 0.001; 9s
network 0, training 6, epoch 50: train scaled MSE 0.362772; val RMSE 0.1154856; lr 0.001; 11s
network 0, training 6, epoch 60: train scaled MSE 0.328587; val RMSE 0.1152922; lr 0.001; 14s
network 0, training 6, epoch 70: train scaled MSE 0.293533; val RMSE 0.1155884; lr 0.0005; 16s
network 0, training 6, epoch 80: train scaled MSE 0.271692; val RMSE 0.1160324; lr 0.00025; 18s
network 0, training 6, epoch 90: train scaled MSE 0.266582; val RMSE 0.1169155; lr 0.00025; 20s
Standard Linear Baseline Validation RMSE: 0.1257289

Network seed 0, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1921,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1260,57.0120,"[56.46%, 57.57%]",0.7549,0.0,0.8430
MLP,0.1163,63.3323,"[62.75%, 63.94%]",0.7962,5.4773,0.8947

network 0, training 7, epoch 1: train scaled MSE 0.910404; val RMSE 0.1569034; lr 0.001; 0s
network 0, training 7, epoch 10: train scaled MSE 0.515839; val RMSE 0.1222311; lr 0.001; 2s
network 0, training 7, epoch 20: train scaled MSE 0.471096; val RMSE 0.1178135; lr 0.001; 4s
network 0, training 7, epoch 30: train scaled MSE 0.440537; val RMSE 0.1169708; lr 0.001; 7s
network 0, training 7, epoch 40: train scaled MSE 0.407844; val RMSE 0.1148158; lr 0.001; 9s
network 0, training 7, epoch 50: train scaled MSE 0.382086; val RMSE 0.1152941; lr 0.001; 11s
network 0, training 7, epoch 60: train scaled MSE 0.340899; val RMSE 0.1147018; lr 0.0005; 13s
network 0, training 7, epoch 70: train scaled MSE 0.31819; val RMSE 0.1143988; lr 0.00025; 15s
network 0, training 7, epoch 80: train scaled MSE 0.306603; val RMSE 0.1144467; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.1241201

Network seed 0, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1914,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1250,57.3192,"[56.73%, 57.89%]",0.7569,0.0,0.8398
MLP,0.1156,63.5149,"[62.89%, 64.14%]",0.7972,5.3215,0.8946

network 0, training 8, epoch 1: train scaled MSE 0.906933; val RMSE 0.1579758; lr 0.001; 0s
network 0, training 8, epoch 10: train scaled MSE 0.514593; val RMSE 0.1252072; lr 0.001; 2s
network 0, training 8, epoch 20: train scaled MSE 0.468002; val RMSE 0.121234; lr 0.001; 4s
network 0, training 8, epoch 30: train scaled MSE 0.437637; val RMSE 0.1187643; lr 0.001; 7s
network 0, training 8, epoch 40: train scaled MSE 0.420955; val RMSE 0.1195402; lr 0.001; 9s
network 0, training 8, epoch 50: train scaled MSE 0.356148; val RMSE 0.1176288; lr 0.0005; 11s
network 0, training 8, epoch 60: train scaled MSE 0.337845; val RMSE 0.1178539; lr 0.0005; 13s
network 0, training 8, epoch 70: train scaled MSE 0.317572; val RMSE 0.1175495; lr 0.00025; 15s
network 0, training 8, epoch 80: train scaled MSE 0.30752; val RMSE 0.117968; lr 0.000125; 18s
network 0, training 8, epoch 90: train scaled MSE 0.302811; val RMSE 0.1179191; lr 0.000125; 20s
Standard Linear Baseline Validation RMSE: 0.1267968

Network seed 0, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1912,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1251,57.1400,"[56.50%, 57.74%]",0.7557,0.0,0.8365
MLP,0.1150,63.7989,"[63.13%, 64.48%]",0.7993,5.7708,0.9010

network 0, training 9, epoch 1: train scaled MSE 0.908953; val RMSE 0.1576649; lr 0.001; 0s
network 0, training 9, epoch 10: train scaled MSE 0.505367; val RMSE 0.1236303; lr 0.001; 2s
network 0, training 9, epoch 20: train scaled MSE 0.466927; val RMSE 0.1190689; lr 0.001; 4s
network 0, training 9, epoch 30: train scaled MSE 0.439291; val RMSE 0.1171997; lr 0.001; 7s
network 0, training 9, epoch 40: train scaled MSE 0.398192; val RMSE 0.1161115; lr 0.001; 9s
network 0, training 9, epoch 50: train scaled MSE 0.358904; val RMSE 0.116162; lr 0.001; 11s
network 0, training 9, epoch 60: train scaled MSE 0.321625; val RMSE 0.115968; lr 0.0005; 13s
network 0, training 9, epoch 70: train scaled MSE 0.299573; val RMSE 0.1158509; lr 0.00025; 15s
network 0, training 9, epoch 80: train scaled MSE 0.29447; val RMSE 0.1164765; lr 0.00025; 17s
Standard Linear Baseline Validation RMSE: 0.1265314

Network seed 0, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1910,0.0000,-,0.0000,-,0.0000
Linear Regression,0.1255,56.7932,"[56.18%, 57.37%]",0.7535,0.0,0.8365
MLP,0.1155,63.4425,"[62.80%, 64.06%]",0.7969,5.76,0.8942

Network 1: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   48.5s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   48.8s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   49.0s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   49.4s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   49.6s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   49.8s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   50.3s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   50.8s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   51.3s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   51.9s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   52.4s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   52.8s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   53.4s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   54.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   54.9s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   55.7s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   56.5s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   57.3s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   58.1s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   59.0s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   59.9s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 11.5min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 11.8min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 12.1min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 12.9min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 13.4min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 13.9min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 14.0min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 14.3min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 14.5min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 15.1min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 15.3min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 15.5min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 15.7min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 16.1min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 16.5min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 16.9min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 17.2min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 17.3min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 17.6min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 17.7min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 17.8min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 18.0min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 18.1min finished

network 1, training 0, epoch 1: train scaled MSE 0.895342; val RMSE 0.1227822; lr 0.001; 0s
network 1, training 0, epoch 10: train scaled MSE 0.407149; val RMSE 0.07430154; lr 0.001; 2s
network 1, training 0, epoch 20: train scaled MSE 0.355164; val RMSE 0.06811807; lr 0.001; 5s
network 1, training 0, epoch 30: train scaled MSE 0.311065; val RMSE 0.06587881; lr 0.001; 7s
network 1, training 0, epoch 40: train scaled MSE 0.263764; val RMSE 0.06566542; lr 0.001; 9s
network 1, training 0, epoch 50: train scaled MSE 0.223771; val RMSE 0.06600496; lr 0.001; 11s
network 1, training 0, epoch 60: train scaled MSE 0.20311; val RMSE 0.06639482; lr 0.0005; 13s
network 1, training 0, epoch 70: train scaled MSE 0.172469; val RMSE 0.06600726; lr 0.00025; 15s
network 1, training 0, epoch 80: train scaled MSE 0.165151; val RMSE 0.06631604; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.07837768

Network seed 1, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0924,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0796,25.6914,"[24.61%, 26.68%]",0.5070,0.0,0.2020
MLP,0.0665,48.1955,"[47.07%, 49.33%]",0.6958,37.2455,0.2183

network 1, training 1, epoch 1: train scaled MSE 0.895313; val RMSE 0.1245898; lr 0.001; 0s
network 1, training 1, epoch 10: train scaled MSE 0.402585; val RMSE 0.07381727; lr 0.001; 2s
network 1, training 1, epoch 20: train scaled MSE 0.345417; val RMSE 0.06749397; lr 0.001; 4s
network 1, training 1, epoch 30: train scaled MSE 0.301341; val RMSE 0.06655529; lr 0.001; 7s
network 1, training 1, epoch 40: train scaled MSE 0.250333; val RMSE 0.06763823; lr 0.001; 9s
network 1, training 1, epoch 50: train scaled MSE 0.21035; val RMSE 0.06626712; lr 0.001; 11s
network 1, training 1, epoch 60: train scaled MSE 0.187295; val RMSE 0.06602253; lr 0.0005; 13s
network 1, training 1, epoch 70: train scaled MSE 0.175129; val RMSE 0.06656352; lr 0.0005; 16s
network 1, training 1, epoch 80: train scaled MSE 0.165951; val RMSE 0.06628393; lr 0.00025; 18s
network 1, training 1, epoch 90: train scaled MSE 0.16072; val RMSE 0.06636019; lr 0.000125; 20s
Standard Linear Baseline Validation RMSE: 0.07848012

Network seed 1, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0915,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0791,25.3003,"[24.22%, 26.39%]",0.5043,0.0,0.1985
MLP,0.0668,46.7129,"[45.42%, 48.07%]",0.6878,36.3911,0.2366

network 1, training 2, epoch 1: train scaled MSE 0.898621; val RMSE 0.1235728; lr 0.001; 0s
network 1, training 2, epoch 10: train scaled MSE 0.410664; val RMSE 0.07507032; lr 0.001; 2s
network 1, training 2, epoch 20: train scaled MSE 0.366679; val RMSE 0.0684779; lr 0.001; 5s
network 1, training 2, epoch 30: train scaled MSE 0.346572; val RMSE 0.06661119; lr 0.001; 7s
network 1, training 2, epoch 40: train scaled MSE 0.292618; val RMSE 0.06524775; lr 0.001; 9s
network 1, training 2, epoch 50: train scaled MSE 0.251251; val RMSE 0.06522244; lr 0.001; 11s
network 1, training 2, epoch 60: train scaled MSE 0.214339; val RMSE 0.06493608; lr 0.0005; 14s
network 1, training 2, epoch 70: train scaled MSE 0.194988; val RMSE 0.065318; lr 0.00025; 16s
network 1, training 2, epoch 80: train scaled MSE 0.183051; val RMSE 0.06521771; lr 0.000125; 18s
network 1, training 2, epoch 90: train scaled MSE 0.178812; val RMSE 0.06535576; lr 0.000125; 20s
Standard Linear Baseline Validation RMSE: 0.07822591

Network seed 1, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0923,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0795,25.8740,"[24.83%, 26.86%]",0.5089,0.0,0.2001
MLP,0.0669,47.5028,"[46.31%, 48.61%]",0.6906,35.702,0.2209

network 1, training 3, epoch 1: train scaled MSE 0.900156; val RMSE 0.1215338; lr 0.001; 0s
network 1, training 3, epoch 10: train scaled MSE 0.401113; val RMSE 0.07136721; lr 0.001; 2s
network 1, training 3, epoch 20: train scaled MSE 0.347267; val RMSE 0.06615441; lr 0.001; 4s
network 1, training 3, epoch 30: train scaled MSE 0.301851; val RMSE 0.06554702; lr 0.001; 6s
network 1, training 3, epoch 40: train scaled MSE 0.253119; val RMSE 0.064911; lr 0.001; 9s
network 1, training 3, epoch 50: train scaled MSE 0.228404; val RMSE 0.06575901; lr 0.0005; 11s
network 1, training 3, epoch 60: train scaled MSE 0.19716; val RMSE 0.06526512; lr 0.00025; 13s
network 1, training 3, epoch 70: train scaled MSE 0.191932; val RMSE 0.06653601; lr 0.000125; 16s
network 1, training 3, epoch 80: train scaled MSE 0.184161; val RMSE 0.06554075; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.07733569

Network seed 1, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0909,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0783,25.6482,"[24.47%, 26.68%]",0.5076,0.0,0.1930
MLP,0.0650,48.8093,"[47.54%, 49.96%]",0.7016,38.2054,0.2183

network 1, training 4, epoch 1: train scaled MSE 0.893635; val RMSE 0.122199; lr 0.001; 0s
network 1, training 4, epoch 10: train scaled MSE 0.401929; val RMSE 0.07426213; lr 0.001; 2s
network 1, training 4, epoch 20: train scaled MSE 0.352381; val RMSE 0.06820116; lr 0.001; 4s
network 1, training 4, epoch 30: train scaled MSE 0.316588; val RMSE 0.06710123; lr 0.001; 7s
network 1, training 4, epoch 40: train scaled MSE 0.274603; val RMSE 0.06672461; lr 0.001; 9s
network 1, training 4, epoch 50: train scaled MSE 0.238792; val RMSE 0.0663977; lr 0.0005; 11s
network 1, training 4, epoch 60: train scaled MSE 0.218921; val RMSE 0.06671231; lr 0.00025; 13s
network 1, training 4, epoch 70: train scaled MSE 0.207564; val RMSE 0.06675221; lr 0.00025; 16s
Standard Linear Baseline Validation RMSE: 0.07847066

Network seed 1, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0921,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0791,26.1171,"[25.10%, 27.08%]",0.5112,0.0,0.2020
MLP,0.0662,48.2549,"[47.07%, 49.41%]",0.6957,36.1034,0.2187

network 1, training 5, epoch 1: train scaled MSE 0.897705; val RMSE 0.1225535; lr 0.001; 0s
network 1, training 5, epoch 10: train scaled MSE 0.403018; val RMSE 0.07555834; lr 0.001; 2s
network 1, training 5, epoch 20: train scaled MSE 0.349447; val RMSE 0.06956518; lr 0.001; 4s
network 1, training 5, epoch 30: train scaled MSE 0.302077; val RMSE 0.06808382; lr 0.001; 7s
network 1, training 5, epoch 40: train scaled MSE 0.272753; val RMSE 0.06874014; lr 0.001; 9s
network 1, training 5, epoch 50: train scaled MSE 0.234638; val RMSE 0.0689041; lr 0.001; 11s
network 1, training 5, epoch 60: train scaled MSE 0.207997; val RMSE 0.06843985; lr 0.0005; 14s
network 1, training 5, epoch 70: train scaled MSE 0.190018; val RMSE 0.06836369; lr 0.00025; 16s
network 1, training 5, epoch 80: train scaled MSE 0.181209; val RMSE 0.06843084; lr 0.000125; 18s
network 1, training 5, epoch 90: train scaled MSE 0.176651; val RMSE 0.06853649; lr 0.000125; 20s
Standard Linear Baseline Validation RMSE: 0.08095688

Network seed 1, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0908,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0784,25.4513,"[24.35%, 26.50%]",0.5051,0.0,0.1991
MLP,0.0659,47.3992,"[46.26%, 48.51%]",0.6907,36.7552,0.2223

network 1, training 6, epoch 1: train scaled MSE 0.899672; val RMSE 0.1211689; lr 0.001; 0s
network 1, training 6, epoch 10: train scaled MSE 0.412731; val RMSE 0.07484503; lr 0.001; 2s
network 1, training 6, epoch 20: train scaled MSE 0.364402; val RMSE 0.06915646; lr 0.001; 4s
network 1, training 6, epoch 30: train scaled MSE 0.338279; val RMSE 0.06734474; lr 0.001; 7s
network 1, training 6, epoch 40: train scaled MSE 0.293427; val RMSE 0.06575448; lr 0.001; 9s
network 1, training 6, epoch 50: train scaled MSE 0.24051; val RMSE 0.06624928; lr 0.001; 11s
network 1, training 6, epoch 60: train scaled MSE 0.209513; val RMSE 0.06594792; lr 0.001; 13s
network 1, training 6, epoch 70: train scaled MSE 0.183271; val RMSE 0.06580777; lr 0.0005; 15s
network 1, training 6, epoch 80: train scaled MSE 0.17104; val RMSE 0.06575061; lr 0.00025; 17s
Standard Linear Baseline Validation RMSE: 0.07839245

Network seed 1, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0921,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0790,26.4550,"[25.46%, 27.47%]",0.5144,0.0,0.2032
MLP,0.0667,47.5145,"[46.39%, 48.62%]",0.6907,34.2723,0.2216

network 1, training 7, epoch 1: train scaled MSE 0.900039; val RMSE 0.1232228; lr 0.001; 0s
network 1, training 7, epoch 10: train scaled MSE 0.408779; val RMSE 0.0725916; lr 0.001; 2s
network 1, training 7, epoch 20: train scaled MSE 0.360607; val RMSE 0.06753987; lr 0.001; 4s
network 1, training 7, epoch 30: train scaled MSE 0.322439; val RMSE 0.06570725; lr 0.001; 6s
network 1, training 7, epoch 40: train scaled MSE 0.272847; val RMSE 0.0645331; lr 0.001; 8s
network 1, training 7, epoch 50: train scaled MSE 0.230138; val RMSE 0.06475275; lr 0.001; 11s
network 1, training 7, epoch 60: train scaled MSE 0.193006; val RMSE 0.06418015; lr 0.0005; 13s
network 1, training 7, epoch 70: train scaled MSE 0.175467; val RMSE 0.06455957; lr 0.0005; 15s
network 1, training 7, epoch 80: train scaled MSE 0.165055; val RMSE 0.06446231; lr 0.00025; 17s
network 1, training 7, epoch 90: train scaled MSE 0.158203; val RMSE 0.06445561; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.07749607

Network seed 1, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0906,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0784,25.1974,"[24.04%, 26.28%]",0.5039,0.0,0.1947
MLP,0.0654,47.8568,"[46.66%, 48.96%]",0.6945,37.824,0.2131

network 1, training 8, epoch 1: train scaled MSE 0.894786; val RMSE 0.1205401; lr 0.001; 0s
network 1, training 8, epoch 10: train scaled MSE 0.401146; val RMSE 0.07350349; lr 0.001; 2s
network 1, training 8, epoch 20: train scaled MSE 0.348279; val RMSE 0.06771223; lr 0.001; 4s
network 1, training 8, epoch 30: train scaled MSE 0.302877; val RMSE 0.06680212; lr 0.001; 6s
network 1, training 8, epoch 40: train scaled MSE 0.268734; val RMSE 0.06662063; lr 0.001; 8s
network 1, training 8, epoch 50: train scaled MSE 0.214489; val RMSE 0.06595017; lr 0.0005; 11s
network 1, training 8, epoch 60: train scaled MSE 0.192661; val RMSE 0.06651626; lr 0.0005; 13s
network 1, training 8, epoch 70: train scaled MSE 0.17915; val RMSE 0.0666545; lr 0.00025; 15s
Standard Linear Baseline Validation RMSE: 0.07774332

Network seed 1, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0928,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0796,26.4398,"[25.38%, 27.46%]",0.5142,0.0,0.2042
MLP,0.0671,47.7381,"[46.51%, 48.89%]",0.6929,34.746,0.2216

network 1, training 9, epoch 1: train scaled MSE 0.898425; val RMSE 0.1219609; lr 0.001; 0s
network 1, training 9, epoch 10: train scaled MSE 0.406293; val RMSE 0.07484798; lr 0.001; 2s
network 1, training 9, epoch 20: train scaled MSE 0.347866; val RMSE 0.07263512; lr 0.001; 4s
network 1, training 9, epoch 30: train scaled MSE 0.30951; val RMSE 0.0672117; lr 0.001; 6s
network 1, training 9, epoch 40: train scaled MSE 0.262409; val RMSE 0.06712675; lr 0.001; 9s
network 1, training 9, epoch 50: train scaled MSE 0.215375; val RMSE 0.06920852; lr 0.001; 11s
network 1, training 9, epoch 60: train scaled MSE 0.188928; val RMSE 0.06740849; lr 0.0005; 13s
network 1, training 9, epoch 70: train scaled MSE 0.172577; val RMSE 0.06763283; lr 0.00025; 15s
network 1, training 9, epoch 80: train scaled MSE 0.16359; val RMSE 0.06761786; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.07948764

Network seed 1, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0915,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0791,25.2122,"[24.09%, 26.24%]",0.5032,0.0,0.2001
MLP,0.0664,47.3381,"[46.19%, 48.49%]",0.6902,37.1568,0.2149

Network 2: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   22.7s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   23.5s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   23.7s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   23.8s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   24.1s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   24.5s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   25.1s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   26.5s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   27.3s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   28.7s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   29.2s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   30.2s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   31.0s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   31.6s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   32.3s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   33.3s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   34.2s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   35.3s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   36.3s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   37.4s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   39.5s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   40.6s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   41.9s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   43.2s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   44.4s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   45.8s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   47.1s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   48.4s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   49.9s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   51.3s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   52.8s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   54.2s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   55.6s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   56.9s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   58.5s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 11.5min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 11.8min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 12.9min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 15.5min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 15.8min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 16.9min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 17.1min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 17.3min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 17.6min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 17.7min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 17.8min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 18.0min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 18.1min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 18.3min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 18.4min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 18.6min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 18.7min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 18.8min finished

network 2, training 0, epoch 1: train scaled MSE 0.898268; val RMSE 0.1093796; lr 0.001; 0s
network 2, training 0, epoch 10: train scaled MSE 0.423757; val RMSE 0.06874966; lr 0.001; 2s
network 2, training 0, epoch 20: train scaled MSE 0.379505; val RMSE 0.06358091; lr 0.001; 4s
network 2, training 0, epoch 30: train scaled MSE 0.339858; val RMSE 0.06314616; lr 0.001; 7s
network 2, training 0, epoch 40: train scaled MSE 0.299102; val RMSE 0.06132529; lr 0.001; 9s
network 2, training 0, epoch 50: train scaled MSE 0.249759; val RMSE 0.06154814; lr 0.001; 11s
network 2, training 0, epoch 60: train scaled MSE 0.214534; val RMSE 0.06158859; lr 0.0005; 13s
network 2, training 0, epoch 70: train scaled MSE 0.183801; val RMSE 0.06099866; lr 0.0005; 15s
network 2, training 0, epoch 80: train scaled MSE 0.172636; val RMSE 0.06114037; lr 0.00025; 17s
Standard Linear Baseline Validation RMSE: 0.06757554

Network seed 2, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0757,0.0000,-,0.0000,-,0.000
Linear Regression,0.0674,20.6904,"[19.48%, 21.85%]",0.4555,0.0,0.159
MLP,0.0600,37.0824,"[35.38%, 38.68%]",0.6145,34.8984,0.148

network 2, training 1, epoch 1: train scaled MSE 0.902061; val RMSE 0.109072; lr 0.001; 0s
network 2, training 1, epoch 10: train scaled MSE 0.411897; val RMSE 0.06569069; lr 0.001; 2s
network 2, training 1, epoch 20: train scaled MSE 0.368786; val RMSE 0.06077525; lr 0.001; 4s
network 2, training 1, epoch 30: train scaled MSE 0.318459; val RMSE 0.05976139; lr 0.001; 6s
network 2, training 1, epoch 40: train scaled MSE 0.270891; val RMSE 0.05990872; lr 0.001; 8s
network 2, training 1, epoch 50: train scaled MSE 0.281644; val RMSE 0.06113693; lr 0.001; 11s
network 2, training 1, epoch 60: train scaled MSE 0.203513; val RMSE 0.05968418; lr 0.0005; 13s
network 2, training 1, epoch 70: train scaled MSE 0.185895; val RMSE 0.05983143; lr 0.0005; 15s
network 2, training 1, epoch 80: train scaled MSE 0.174865; val RMSE 0.05970099; lr 0.00025; 17s
network 2, training 1, epoch 90: train scaled MSE 0.170453; val RMSE 0.05990386; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.06559741

Network seed 2, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0756,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0673,20.8011,"[19.62%, 21.98%]",0.4573,0.0,0.1597
MLP,0.0607,35.5889,"[33.75%, 37.46%]",0.6085,33.0674,0.1508

network 2, training 2, epoch 1: train scaled MSE 0.903555; val RMSE 0.1077622; lr 0.001; 0s
network 2, training 2, epoch 10: train scaled MSE 0.421857; val RMSE 0.06658757; lr 0.001; 2s
network 2, training 2, epoch 20: train scaled MSE 0.378219; val RMSE 0.06133654; lr 0.001; 4s
network 2, training 2, epoch 30: train scaled MSE 0.347148; val RMSE 0.05936252; lr 0.001; 6s
network 2, training 2, epoch 40: train scaled MSE 0.296975; val RMSE 0.0587704; lr 0.001; 8s
network 2, training 2, epoch 50: train scaled MSE 0.254201; val RMSE 0.05876; lr 0.001; 10s
network 2, training 2, epoch 60: train scaled MSE 0.22477; val RMSE 0.05875294; lr 0.0005; 12s
network 2, training 2, epoch 70: train scaled MSE 0.208107; val RMSE 0.05881234; lr 0.00025; 14s
network 2, training 2, epoch 80: train scaled MSE 0.197104; val RMSE 0.05881396; lr 0.000125; 16s
network 2, training 2, epoch 90: train scaled MSE 0.191543; val RMSE 0.05885948; lr 6.25e-05; 19s
Standard Linear Baseline Validation RMSE: 0.06702025

Network seed 2, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0747,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0666,20.5901,"[19.27%, 21.84%]",0.4557,0.0,0.1580
MLP,0.0590,37.5347,"[35.98%, 39.10%]",0.6202,36.0892,0.1516

network 2, training 3, epoch 1: train scaled MSE 0.897443; val RMSE 0.107194; lr 0.001; 0s
network 2, training 3, epoch 10: train scaled MSE 0.409272; val RMSE 0.06657388; lr 0.001; 2s
network 2, training 3, epoch 20: train scaled MSE 0.367182; val RMSE 0.06114864; lr 0.001; 4s
network 2, training 3, epoch 30: train scaled MSE 0.324979; val RMSE 0.06003191; lr 0.001; 6s
network 2, training 3, epoch 40: train scaled MSE 0.271491; val RMSE 0.05942248; lr 0.001; 8s
network 2, training 3, epoch 50: train scaled MSE 0.25737; val RMSE 0.06088087; lr 0.001; 10s
network 2, training 3, epoch 60: train scaled MSE 0.198001; val RMSE 0.05937105; lr 0.0005; 12s
network 2, training 3, epoch 70: train scaled MSE 0.181573; val RMSE 0.05952504; lr 0.00025; 15s
network 2, training 3, epoch 80: train scaled MSE 0.174889; val RMSE 0.0596224; lr 0.000125; 17s
network 2, training 3, epoch 90: train scaled MSE 0.169502; val RMSE 0.05968955; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.06629743

Network seed 2, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0769,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0683,21.1513,"[19.95%, 22.29%]",0.4601,0.0,0.1600
MLP,0.0603,38.4837,"[36.91%, 40.10%]",0.6268,36.2255,0.1483

network 2, training 4, epoch 1: train scaled MSE 0.905816; val RMSE 0.1075956; lr 0.001; 0s
network 2, training 4, epoch 10: train scaled MSE 0.41273; val RMSE 0.06479039; lr 0.001; 2s
network 2, training 4, epoch 20: train scaled MSE 0.36939; val RMSE 0.06130141; lr 0.001; 4s
network 2, training 4, epoch 30: train scaled MSE 0.33404; val RMSE 0.06087873; lr 0.001; 6s
network 2, training 4, epoch 40: train scaled MSE 0.278554; val RMSE 0.05944082; lr 0.001; 8s
network 2, training 4, epoch 50: train scaled MSE 0.22969; val RMSE 0.06721382; lr 0.001; 10s
network 2, training 4, epoch 60: train scaled MSE 0.19854; val RMSE 0.05962062; lr 0.0005; 12s
network 2, training 4, epoch 70: train scaled MSE 0.183169; val RMSE 0.05966756; lr 0.00025; 15s
network 2, training 4, epoch 80: train scaled MSE 0.175472; val RMSE 0.05974877; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.06584689

Network seed 2, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0754,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0674,20.1032,"[18.80%, 21.33%]",0.4511,0.0,0.1605
MLP,0.0602,36.2747,"[34.63%, 37.85%]",0.6082,34.8251,0.1476

network 2, training 5, epoch 1: train scaled MSE 0.895912; val RMSE 0.1104594; lr 0.001; 0s
network 2, training 5, epoch 10: train scaled MSE 0.396249; val RMSE 0.06640774; lr 0.001; 2s
network 2, training 5, epoch 20: train scaled MSE 0.35266; val RMSE 0.06223101; lr 0.001; 4s
network 2, training 5, epoch 30: train scaled MSE 0.310663; val RMSE 0.06042134; lr 0.001; 6s
network 2, training 5, epoch 40: train scaled MSE 0.265864; val RMSE 0.06033828; lr 0.001; 8s
network 2, training 5, epoch 50: train scaled MSE 0.222827; val RMSE 0.06001338; lr 0.0005; 10s
network 2, training 5, epoch 60: train scaled MSE 0.202077; val RMSE 0.06045079; lr 0.00025; 12s
network 2, training 5, epoch 70: train scaled MSE 0.194787; val RMSE 0.06125001; lr 0.00025; 14s
network 2, training 5, epoch 80: train scaled MSE 0.184561; val RMSE 0.06063884; lr 0.000125; 16s
Standard Linear Baseline Validation RMSE: 0.06750494

Network seed 2, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0775,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0688,21.1881,"[20.06%, 22.29%]",0.4603,0.0,0.1651
MLP,0.0610,38.1277,"[36.53%, 39.73%]",0.6222,35.1637,0.1558

network 2, training 6, epoch 1: train scaled MSE 0.900953; val RMSE 0.107535; lr 0.001; 0s
network 2, training 6, epoch 10: train scaled MSE 0.410346; val RMSE 0.06563584; lr 0.001; 2s
network 2, training 6, epoch 20: train scaled MSE 0.370157; val RMSE 0.06041309; lr 0.001; 4s
network 2, training 6, epoch 30: train scaled MSE 0.3292; val RMSE 0.05863579; lr 0.001; 6s
network 2, training 6, epoch 40: train scaled MSE 0.281814; val RMSE 0.05838566; lr 0.001; 8s
network 2, training 6, epoch 50: train scaled MSE 0.228574; val RMSE 0.05831723; lr 0.001; 11s
network 2, training 6, epoch 60: train scaled MSE 0.189002; val RMSE 0.05871531; lr 0.0005; 13s
network 2, training 6, epoch 70: train scaled MSE 0.167913; val RMSE 0.05859095; lr 0.00025; 15s
network 2, training 6, epoch 80: train scaled MSE 0.158444; val RMSE 0.05877514; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.06502526

Network seed 2, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0761,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0679,20.3989,"[19.12%, 21.59%]",0.4528,0.0,0.1605
MLP,0.0604,36.9645,"[35.26%, 38.50%]",0.6128,35.3239,0.1518

network 2, training 7, epoch 1: train scaled MSE 0.903412; val RMSE 0.1091061; lr 0.001; 0s
network 2, training 7, epoch 10: train scaled MSE 0.420414; val RMSE 0.0673548; lr 0.001; 2s
network 2, training 7, epoch 20: train scaled MSE 0.385327; val RMSE 0.06243982; lr 0.001; 4s
network 2, training 7, epoch 30: train scaled MSE 0.340394; val RMSE 0.06083211; lr 0.001; 7s
network 2, training 7, epoch 40: train scaled MSE 0.293249; val RMSE 0.06095816; lr 0.001; 9s
network 2, training 7, epoch 50: train scaled MSE 0.242515; val RMSE 0.06077132; lr 0.001; 11s
network 2, training 7, epoch 60: train scaled MSE 0.20851; val RMSE 0.06101462; lr 0.0005; 13s
network 2, training 7, epoch 70: train scaled MSE 0.183444; val RMSE 0.06053052; lr 0.00025; 15s
network 2, training 7, epoch 80: train scaled MSE 0.173795; val RMSE 0.06090467; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.06731261

Network seed 2, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0758,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0675,20.6744,"[19.44%, 21.83%]",0.4557,0.0,0.1635
MLP,0.0601,37.1874,"[35.64%, 38.65%]",0.6137,34.6612,0.1505

network 2, training 8, epoch 1: train scaled MSE 0.897777; val RMSE 0.1069372; lr 0.001; 0s
network 2, training 8, epoch 10: train scaled MSE 0.405637; val RMSE 0.06592109; lr 0.001; 2s
network 2, training 8, epoch 20: train scaled MSE 0.371369; val RMSE 0.06279622; lr 0.001; 4s
network 2, training 8, epoch 30: train scaled MSE 0.331166; val RMSE 0.06028886; lr 0.001; 6s
network 2, training 8, epoch 40: train scaled MSE 0.287792; val RMSE 0.05914232; lr 0.001; 8s
network 2, training 8, epoch 50: train scaled MSE 0.241965; val RMSE 0.05952298; lr 0.001; 10s
network 2, training 8, epoch 60: train scaled MSE 0.211979; val RMSE 0.05920477; lr 0.0005; 13s
network 2, training 8, epoch 70: train scaled MSE 0.190856; val RMSE 0.05934766; lr 0.00025; 15s
network 2, training 8, epoch 80: train scaled MSE 0.18071; val RMSE 0.05945894; lr 0.000125; 17s
network 2, training 8, epoch 90: train scaled MSE 0.176202; val RMSE 0.05950797; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.06666694

Network seed 2, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0774,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0688,21.0855,"[19.97%, 22.11%]",0.4592,0.0,0.1692
MLP,0.0613,37.2848,"[35.65%, 38.76%]",0.6158,34.0975,0.1561

network 2, training 9, epoch 1: train scaled MSE 0.9; val RMSE 0.1077678; lr 0.001; 0s
network 2, training 9, epoch 10: train scaled MSE 0.415043; val RMSE 0.06716092; lr 0.001; 2s
network 2, training 9, epoch 20: train scaled MSE 0.374525; val RMSE 0.06245466; lr 0.001; 4s
network 2, training 9, epoch 30: train scaled MSE 0.329648; val RMSE 0.06087538; lr 0.001; 6s
network 2, training 9, epoch 40: train scaled MSE 0.273134; val RMSE 0.06102275; lr 0.001; 8s
network 2, training 9, epoch 50: train scaled MSE 0.224993; val RMSE 0.06064641; lr 0.0005; 10s
network 2, training 9, epoch 60: train scaled MSE 0.203777; val RMSE 0.06064145; lr 0.0005; 13s
network 2, training 9, epoch 70: train scaled MSE 0.189857; val RMSE 0.06051558; lr 0.00025; 15s
Standard Linear Baseline Validation RMSE: 0.0668322

Network seed 2, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0744,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0665,20.1003,"[18.73%, 21.37%]",0.4516,0.0,0.1521
MLP,0.0595,35.9513,"[34.35%, 37.56%]",0.6045,33.8577,0.1459

Network 3: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   24.8s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   25.9s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   26.2s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   26.4s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   26.6s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   27.1s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   27.5s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   28.1s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   28.6s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   29.3s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   30.0s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   30.5s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   31.1s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   31.7s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   32.3s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   33.0s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   33.9s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   34.6s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   35.5s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   36.4s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   37.2s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   38.6s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   39.8s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   41.0s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   41.9s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   43.0s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   44.2s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   45.2s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   46.5s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   47.6s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   48.7s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   49.8s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   51.0s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   52.3s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   53.7s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   55.3s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   56.7s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   58.2s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   59.8s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 11.5min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 11.8min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 12.1min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 12.9min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 13.4min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 13.9min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 14.3min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 14.4min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 14.9min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 15.1min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 15.5min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 15.7min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 16.1min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 16.5min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 16.9min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 17.0min finished

network 3, training 0, epoch 1: train scaled MSE 0.899168; val RMSE 0.1332409; lr 0.001; 0s
network 3, training 0, epoch 10: train scaled MSE 0.406717; val RMSE 0.0880774; lr 0.001; 2s
network 3, training 0, epoch 20: train scaled MSE 0.364882; val RMSE 0.08067916; lr 0.001; 4s
network 3, training 0, epoch 30: train scaled MSE 0.323315; val RMSE 0.0792566; lr 0.001; 6s
network 3, training 0, epoch 40: train scaled MSE 0.283112; val RMSE 0.07878146; lr 0.001; 8s
network 3, training 0, epoch 50: train scaled MSE 0.237631; val RMSE 0.07912852; lr 0.001; 10s
network 3, training 0, epoch 60: train scaled MSE 0.20056; val RMSE 0.07879645; lr 0.0005; 13s
network 3, training 0, epoch 70: train scaled MSE 0.18107; val RMSE 0.07899988; lr 0.00025; 15s
network 3, training 0, epoch 80: train scaled MSE 0.171984; val RMSE 0.07915228; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.0942733

Network seed 3, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1077,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0914,27.9498,"[26.88%, 29.06%]",0.5292,0.0,0.2052
MLP,0.0756,50.6717,"[49.54%, 51.80%]",0.7132,34.775,0.2140

network 3, training 1, epoch 1: train scaled MSE 0.895815; val RMSE 0.1297461; lr 0.001; 0s
network 3, training 1, epoch 10: train scaled MSE 0.411713; val RMSE 0.081663; lr 0.001; 2s
network 3, training 1, epoch 20: train scaled MSE 0.356108; val RMSE 0.07493526; lr 0.001; 4s
network 3, training 1, epoch 30: train scaled MSE 0.32037; val RMSE 0.07377349; lr 0.001; 6s
network 3, training 1, epoch 40: train scaled MSE 0.27365; val RMSE 0.07336961; lr 0.001; 8s
network 3, training 1, epoch 50: train scaled MSE 0.226902; val RMSE 0.07384564; lr 0.0005; 10s
network 3, training 1, epoch 60: train scaled MSE 0.208621; val RMSE 0.07357288; lr 0.0005; 12s
network 3, training 1, epoch 70: train scaled MSE 0.194994; val RMSE 0.07337122; lr 0.00025; 14s
network 3, training 1, epoch 80: train scaled MSE 0.189102; val RMSE 0.07351995; lr 0.000125; 16s
Standard Linear Baseline Validation RMSE: 0.08927318

Network seed 3, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1082,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0916,28.3090,"[27.21%, 29.34%]",0.5326,0.0,0.2048
MLP,0.0753,51.5481,"[50.34%, 52.68%]",0.7196,35.1156,0.2197

network 3, training 2, epoch 1: train scaled MSE 0.894857; val RMSE 0.13127; lr 0.001; 0s
network 3, training 2, epoch 10: train scaled MSE 0.400254; val RMSE 0.08322057; lr 0.001; 2s
network 3, training 2, epoch 20: train scaled MSE 0.358577; val RMSE 0.07816832; lr 0.001; 4s
network 3, training 2, epoch 30: train scaled MSE 0.327237; val RMSE 0.07766421; lr 0.001; 6s
network 3, training 2, epoch 40: train scaled MSE 0.290422; val RMSE 0.0767567; lr 0.001; 8s
network 3, training 2, epoch 50: train scaled MSE 0.25822; val RMSE 0.07573002; lr 0.001; 11s
network 3, training 2, epoch 60: train scaled MSE 0.227004; val RMSE 0.07586705; lr 0.0005; 13s
network 3, training 2, epoch 70: train scaled MSE 0.208866; val RMSE 0.07593433; lr 0.00025; 15s
network 3, training 2, epoch 80: train scaled MSE 0.198447; val RMSE 0.07611208; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.09158293

Network seed 3, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1089,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0922,28.2361,"[27.24%, 29.21%]",0.5315,0.0,0.2074
MLP,0.0755,51.9520,"[50.85%, 53.01%]",0.7211,35.6789,0.2176

network 3, training 3, epoch 1: train scaled MSE 0.89249; val RMSE 0.1309348; lr 0.001; 0s
network 3, training 3, epoch 10: train scaled MSE 0.402999; val RMSE 0.08314976; lr 0.001; 2s
network 3, training 3, epoch 20: train scaled MSE 0.351372; val RMSE 0.07750248; lr 0.001; 4s
network 3, training 3, epoch 30: train scaled MSE 0.33914; val RMSE 0.07611323; lr 0.001; 6s
network 3, training 3, epoch 40: train scaled MSE 0.270356; val RMSE 0.07541913; lr 0.001; 9s
network 3, training 3, epoch 50: train scaled MSE 0.23537; val RMSE 0.07591576; lr 0.001; 11s
network 3, training 3, epoch 60: train scaled MSE 0.207908; val RMSE 0.07573027; lr 0.0005; 13s
network 3, training 3, epoch 70: train scaled MSE 0.191265; val RMSE 0.07586056; lr 0.00025; 15s
network 3, training 3, epoch 80: train scaled MSE 0.183134; val RMSE 0.07572787; lr 0.000125; 17s
network 3, training 3, epoch 90: train scaled MSE 0.178449; val RMSE 0.07581303; lr 6.25e-05; 19s
Standard Linear Baseline Validation RMSE: 0.09176139

Network seed 3, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1091,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0922,28.6573,"[27.69%, 29.61%]",0.5352,0.0,0.2101
MLP,0.0755,52.1527,"[51.01%, 53.27%]",0.7234,35.1495,0.2212

network 3, training 4, epoch 1: train scaled MSE 0.890592; val RMSE 0.1309692; lr 0.001; 0s
network 3, training 4, epoch 10: train scaled MSE 0.408354; val RMSE 0.08336949; lr 0.001; 2s
network 3, training 4, epoch 20: train scaled MSE 0.357403; val RMSE 0.07742019; lr 0.001; 4s
network 3, training 4, epoch 30: train scaled MSE 0.32405; val RMSE 0.07621132; lr 0.001; 6s
network 3, training 4, epoch 40: train scaled MSE 0.282276; val RMSE 0.07540069; lr 0.001; 8s
network 3, training 4, epoch 50: train scaled MSE 0.246614; val RMSE 0.07452614; lr 0.0005; 10s
network 3, training 4, epoch 60: train scaled MSE 0.226175; val RMSE 0.07469036; lr 0.0005; 12s
network 3, training 4, epoch 70: train scaled MSE 0.211491; val RMSE 0.0748745; lr 0.00025; 14s
network 3, training 4, epoch 80: train scaled MSE 0.203328; val RMSE 0.07492695; lr 0.000125; 17s
network 3, training 4, epoch 90: train scaled MSE 0.19868; val RMSE 0.07492887; lr 6.25e-05; 19s
Standard Linear Baseline Validation RMSE: 0.09026555

Network seed 3, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1094,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0923,28.9148,"[27.88%, 29.95%]",0.5378,0.0,0.2077
MLP,0.0756,52.3084,"[51.24%, 53.39%]",0.7242,34.6695,0.2208

network 3, training 5, epoch 1: train scaled MSE 0.894857; val RMSE 0.1315515; lr 0.001; 0s
network 3, training 5, epoch 10: train scaled MSE 0.422005; val RMSE 0.08440069; lr 0.001; 2s
network 3, training 5, epoch 20: train scaled MSE 0.373294; val RMSE 0.07821399; lr 0.001; 4s
network 3, training 5, epoch 30: train scaled MSE 0.339697; val RMSE 0.07705937; lr 0.001; 6s
network 3, training 5, epoch 40: train scaled MSE 0.30877; val RMSE 0.07673725; lr 0.001; 8s
network 3, training 5, epoch 50: train scaled MSE 0.271497; val RMSE 0.07511684; lr 0.0005; 10s
network 3, training 5, epoch 60: train scaled MSE 0.25687; val RMSE 0.07545031; lr 0.0005; 13s
network 3, training 5, epoch 70: train scaled MSE 0.236118; val RMSE 0.07511855; lr 0.00025; 15s
network 3, training 5, epoch 80: train scaled MSE 0.226313; val RMSE 0.07492461; lr 0.00025; 17s
network 3, training 5, epoch 90: train scaled MSE 0.220256; val RMSE 0.07501578; lr 0.000125; 19s
network 3, training 5, epoch 100: train scaled MSE 0.21568; val RMSE 0.07495847; lr 6.25e-05; 21s
network 3, training 5, epoch 110: train scaled MSE 0.213262; val RMSE 0.07494511; lr 3.125e-05; 23s
network 3, training 5, epoch 120: train scaled MSE 0.211837; val RMSE 0.07496689; lr 1.5625e-05; 25s
Standard Linear Baseline Validation RMSE: 0.0909721

Network seed 3, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1077,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0913,28.2179,"[27.11%, 29.22%]",0.5319,0.0,0.2039
MLP,0.0751,51.4012,"[50.20%, 52.52%]",0.7185,35.0797,0.2203

network 3, training 6, epoch 1: train scaled MSE 0.895415; val RMSE 0.13019; lr 0.001; 0s
network 3, training 6, epoch 10: train scaled MSE 0.421472; val RMSE 0.08421972; lr 0.001; 2s
network 3, training 6, epoch 20: train scaled MSE 0.372571; val RMSE 0.07771282; lr 0.001; 4s
network 3, training 6, epoch 30: train scaled MSE 0.342035; val RMSE 0.07660757; lr 0.001; 6s
network 3, training 6, epoch 40: train scaled MSE 0.306709; val RMSE 0.07553282; lr 0.001; 9s
network 3, training 6, epoch 50: train scaled MSE 0.248381; val RMSE 0.07563387; lr 0.001; 11s
network 3, training 6, epoch 60: train scaled MSE 0.211644; val RMSE 0.07587147; lr 0.0005; 13s
network 3, training 6, epoch 70: train scaled MSE 0.193402; val RMSE 0.07607742; lr 0.00025; 15s
network 3, training 6, epoch 80: train scaled MSE 0.181783; val RMSE 0.07587619; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.09103456

Network seed 3, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1080,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0916,28.0354,"[27.00%, 29.07%]",0.5300,0.0,0.2058
MLP,0.0754,51.3279,"[50.18%, 52.37%]",0.7174,35.3551,0.2180

network 3, training 7, epoch 1: train scaled MSE 0.894134; val RMSE 0.1292463; lr 0.001; 0s
network 3, training 7, epoch 10: train scaled MSE 0.414494; val RMSE 0.08413772; lr 0.001; 2s
network 3, training 7, epoch 20: train scaled MSE 0.376573; val RMSE 0.07963775; lr 0.001; 4s
network 3, training 7, epoch 30: train scaled MSE 0.340398; val RMSE 0.07719693; lr 0.001; 6s
network 3, training 7, epoch 40: train scaled MSE 0.293099; val RMSE 0.0761632; lr 0.001; 8s
network 3, training 7, epoch 50: train scaled MSE 0.258054; val RMSE 0.07612268; lr 0.001; 10s
network 3, training 7, epoch 60: train scaled MSE 0.217966; val RMSE 0.07608497; lr 0.001; 13s
network 3, training 7, epoch 70: train scaled MSE 0.187547; val RMSE 0.07581074; lr 0.0005; 15s
network 3, training 7, epoch 80: train scaled MSE 0.171087; val RMSE 0.07586666; lr 0.00025; 17s
network 3, training 7, epoch 90: train scaled MSE 0.163954; val RMSE 0.0762243; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.09152361

Network seed 3, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1087,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0918,28.6180,"[27.57%, 29.58%]",0.5350,0.0,0.2070
MLP,0.0757,51.5362,"[50.41%, 52.66%]",0.7191,34.407,0.2172

network 3, training 8, epoch 1: train scaled MSE 0.904448; val RMSE 0.1342812; lr 0.001; 0s
network 3, training 8, epoch 10: train scaled MSE 0.409123; val RMSE 0.08243268; lr 0.001; 2s
network 3, training 8, epoch 20: train scaled MSE 0.36134; val RMSE 0.07768368; lr 0.001; 4s
network 3, training 8, epoch 30: train scaled MSE 0.352041; val RMSE 0.07735564; lr 0.001; 6s
network 3, training 8, epoch 40: train scaled MSE 0.292222; val RMSE 0.07620022; lr 0.001; 9s
network 3, training 8, epoch 50: train scaled MSE 0.244744; val RMSE 0.07569037; lr 0.001; 11s
network 3, training 8, epoch 60: train scaled MSE 0.212216; val RMSE 0.07540816; lr 0.0005; 13s
network 3, training 8, epoch 70: train scaled MSE 0.196873; val RMSE 0.0758707; lr 0.00025; 15s
network 3, training 8, epoch 80: train scaled MSE 0.184948; val RMSE 0.075794; lr 0.00025; 17s
Standard Linear Baseline Validation RMSE: 0.0914556

Network seed 3, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1088,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0919,28.5874,"[27.60%, 29.54%]",0.5347,0.0,0.2064
MLP,0.0760,51.2572,"[50.17%, 52.32%]",0.7172,34.1338,0.2210

network 3, training 9, epoch 1: train scaled MSE 0.888243; val RMSE 0.1283245; lr 0.001; 0s
network 3, training 9, epoch 10: train scaled MSE 0.412783; val RMSE 0.08625119; lr 0.001; 2s
network 3, training 9, epoch 20: train scaled MSE 0.364943; val RMSE 0.07954762; lr 0.001; 4s
network 3, training 9, epoch 30: train scaled MSE 0.332441; val RMSE 0.07716617; lr 0.001; 6s
network 3, training 9, epoch 40: train scaled MSE 0.29941; val RMSE 0.07748604; lr 0.001; 8s
network 3, training 9, epoch 50: train scaled MSE 0.269528; val RMSE 0.07762821; lr 0.001; 10s
network 3, training 9, epoch 60: train scaled MSE 0.228037; val RMSE 0.07650328; lr 0.0005; 12s
network 3, training 9, epoch 70: train scaled MSE 0.208818; val RMSE 0.07674396; lr 0.0005; 14s
network 3, training 9, epoch 80: train scaled MSE 0.19976; val RMSE 0.07681812; lr 0.00025; 17s
Standard Linear Baseline Validation RMSE: 0.09279852

Network seed 3, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1078,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0913,28.1806,"[27.15%, 29.17%]",0.5313,0.0,0.2052
MLP,0.0748,51.8590,"[50.72%, 52.92%]",0.7213,35.7673,0.2157

Network 4: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   21.0s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   21.5s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   21.7s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   21.9s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   22.0s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   22.6s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   23.3s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   23.8s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   24.5s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   25.1s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   25.8s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   26.5s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   27.3s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   28.8s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   29.6s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   30.3s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   31.3s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   32.1s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   33.1s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   34.1s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   35.1s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   36.2s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   37.3s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   39.5s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   40.8s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   42.1s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   43.4s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   44.7s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   46.2s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   47.6s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   48.9s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   50.2s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   51.6s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   53.1s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   54.6s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   56.3s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   57.8s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   59.5s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 11.8min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 12.1min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 13.4min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 13.9min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 14.3min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 14.4min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 15.1min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 15.3min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 15.5min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 15.7min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 16.1min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 17.1min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 17.2min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 17.5min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 17.7min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 17.8min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 17.9min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 18.1min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 18.2min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 18.4min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 18.5min finished

network 4, training 0, epoch 1: train scaled MSE 0.895868; val RMSE 0.1156054; lr 0.001; 0s
network 4, training 0, epoch 10: train scaled MSE 0.411408; val RMSE 0.08127365; lr 0.001; 2s
network 4, training 0, epoch 20: train scaled MSE 0.373621; val RMSE 0.07757171; lr 0.001; 5s
network 4, training 0, epoch 30: train scaled MSE 0.335224; val RMSE 0.07497409; lr 0.001; 7s
network 4, training 0, epoch 40: train scaled MSE 0.305695; val RMSE 0.07439244; lr 0.001; 9s
network 4, training 0, epoch 50: train scaled MSE 0.266762; val RMSE 0.07392817; lr 0.001; 12s
network 4, training 0, epoch 60: train scaled MSE 0.233042; val RMSE 0.07424342; lr 0.001; 14s
network 4, training 0, epoch 70: train scaled MSE 0.209608; val RMSE 0.07410754; lr 0.0005; 16s
network 4, training 0, epoch 80: train scaled MSE 0.196293; val RMSE 0.07425943; lr 0.00025; 19s
network 4, training 0, epoch 90: train scaled MSE 0.188185; val RMSE 0.07428995; lr 0.000125; 21s
network 4, training 0, epoch 100: train scaled MSE 0.185131; val RMSE 0.07448927; lr 0.000125; 23s
Standard Linear Baseline Validation RMSE: 0.08127213

Network seed 4, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1344,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0851,59.8867,"[59.18%, 60.54%]",0.7738,0.0,0.8737
MLP,0.0772,66.9680,"[66.23%, 67.69%]",0.8190,5.8335,0.9206

network 4, training 1, epoch 1: train scaled MSE 0.899097; val RMSE 0.1159909; lr 0.001; 0s
network 4, training 1, epoch 10: train scaled MSE 0.422782; val RMSE 0.08425801; lr 0.001; 2s
network 4, training 1, epoch 20: train scaled MSE 0.37547; val RMSE 0.07991706; lr 0.001; 4s
network 4, training 1, epoch 30: train scaled MSE 0.336482; val RMSE 0.0778994; lr 0.001; 7s
network 4, training 1, epoch 40: train scaled MSE 0.294591; val RMSE 0.0770982; lr 0.001; 9s
network 4, training 1, epoch 50: train scaled MSE 0.265596; val RMSE 0.07676007; lr 0.001; 11s
network 4, training 1, epoch 60: train scaled MSE 0.237789; val RMSE 0.0771206; lr 0.001; 13s
network 4, training 1, epoch 70: train scaled MSE 0.218201; val RMSE 0.07667392; lr 0.0005; 15s
network 4, training 1, epoch 80: train scaled MSE 0.205916; val RMSE 0.07698317; lr 0.0005; 17s
network 4, training 1, epoch 90: train scaled MSE 0.194678; val RMSE 0.07693239; lr 0.00025; 20s
network 4, training 1, epoch 100: train scaled MSE 0.188888; val RMSE 0.0770206; lr 0.000125; 22s
network 4, training 1, epoch 110: train scaled MSE 0.185269; val RMSE 0.07707982; lr 6.25e-05; 24s
Standard Linear Baseline Validation RMSE: 0.08421857

Network seed 4, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1323,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0829,60.7399,"[60.07%, 61.39%]",0.7794,0.0,0.8714
MLP,0.0746,68.2206,"[67.50%, 68.87%]",0.8266,6.0453,0.9190

network 4, training 2, epoch 1: train scaled MSE 0.896242; val RMSE 0.1167132; lr 0.001; 0s
network 4, training 2, epoch 10: train scaled MSE 0.441272; val RMSE 0.08553199; lr 0.001; 2s
network 4, training 2, epoch 20: train scaled MSE 0.386355; val RMSE 0.08006622; lr 0.001; 4s
network 4, training 2, epoch 30: train scaled MSE 0.349258; val RMSE 0.07745392; lr 0.001; 6s
network 4, training 2, epoch 40: train scaled MSE 0.312871; val RMSE 0.07595147; lr 0.001; 8s
network 4, training 2, epoch 50: train scaled MSE 0.271938; val RMSE 0.07581552; lr 0.001; 11s
network 4, training 2, epoch 60: train scaled MSE 0.235834; val RMSE 0.07568319; lr 0.001; 13s
network 4, training 2, epoch 70: train scaled MSE 0.214869; val RMSE 0.07644643; lr 0.001; 15s
network 4, training 2, epoch 80: train scaled MSE 0.189342; val RMSE 0.07603505; lr 0.0005; 17s
network 4, training 2, epoch 90: train scaled MSE 0.178538; val RMSE 0.0759529; lr 0.00025; 19s
Standard Linear Baseline Validation RMSE: 0.08377782

Network seed 4, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1328,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0834,60.5415,"[59.87%, 61.20%]",0.7782,0.0,0.8731
MLP,0.0758,67.3899,"[66.64%, 68.07%]",0.8223,5.6712,0.9172

network 4, training 3, epoch 1: train scaled MSE 0.898628; val RMSE 0.1143068; lr 0.001; 0s
network 4, training 3, epoch 10: train scaled MSE 0.40529; val RMSE 0.08134779; lr 0.001; 2s
network 4, training 3, epoch 20: train scaled MSE 0.369589; val RMSE 0.07787371; lr 0.001; 4s
network 4, training 3, epoch 30: train scaled MSE 0.32907; val RMSE 0.07590119; lr 0.001; 6s
network 4, training 3, epoch 40: train scaled MSE 0.287497; val RMSE 0.07510439; lr 0.001; 9s
network 4, training 3, epoch 50: train scaled MSE 0.251843; val RMSE 0.07499693; lr 0.001; 11s
network 4, training 3, epoch 60: train scaled MSE 0.213127; val RMSE 0.07474317; lr 0.0005; 13s
network 4, training 3, epoch 70: train scaled MSE 0.199227; val RMSE 0.07478512; lr 0.0005; 16s
network 4, training 3, epoch 80: train scaled MSE 0.186294; val RMSE 0.07483188; lr 0.00025; 18s
network 4, training 3, epoch 90: train scaled MSE 0.180707; val RMSE 0.07507174; lr 0.000125; 20s
network 4, training 3, epoch 100: train scaled MSE 0.176732; val RMSE 0.07493542; lr 6.25e-05; 22s
Standard Linear Baseline Validation RMSE: 0.08218546

Network seed 4, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1333,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0843,60.0505,"[59.38%, 60.73%]",0.7749,0.0,0.8748
MLP,0.0765,67.0327,"[66.29%, 67.76%]",0.8195,5.7544,0.9189

network 4, training 4, epoch 1: train scaled MSE 0.901279; val RMSE 0.1153608; lr 0.001; 0s
network 4, training 4, epoch 10: train scaled MSE 0.418101; val RMSE 0.08287422; lr 0.001; 2s
network 4, training 4, epoch 20: train scaled MSE 0.376626; val RMSE 0.07894661; lr 0.001; 4s
network 4, training 4, epoch 30: train scaled MSE 0.340375; val RMSE 0.07661997; lr 0.001; 7s
network 4, training 4, epoch 40: train scaled MSE 0.30081; val RMSE 0.07599656; lr 0.001; 9s
network 4, training 4, epoch 50: train scaled MSE 0.265884; val RMSE 0.07535445; lr 0.001; 11s
network 4, training 4, epoch 60: train scaled MSE 0.232213; val RMSE 0.07507547; lr 0.001; 13s
network 4, training 4, epoch 70: train scaled MSE 0.213131; val RMSE 0.07604032; lr 0.001; 15s
network 4, training 4, epoch 80: train scaled MSE 0.182207; val RMSE 0.07549735; lr 0.0005; 17s
network 4, training 4, epoch 90: train scaled MSE 0.169293; val RMSE 0.07560378; lr 0.00025; 20s
network 4, training 4, epoch 100: train scaled MSE 0.162503; val RMSE 0.07565528; lr 0.000125; 22s
Standard Linear Baseline Validation RMSE: 0.08289508

Network seed 4, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1330,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0835,60.6387,"[59.94%, 61.28%]",0.7787,0.0,0.8699
MLP,0.0756,67.6757,"[66.97%, 68.35%]",0.8233,5.7217,0.9170

network 4, training 5, epoch 1: train scaled MSE 0.899379; val RMSE 0.1150774; lr 0.001; 0s
network 4, training 5, epoch 10: train scaled MSE 0.398614; val RMSE 0.08259483; lr 0.001; 2s
network 4, training 5, epoch 20: train scaled MSE 0.358654; val RMSE 0.07921057; lr 0.001; 4s
network 4, training 5, epoch 30: train scaled MSE 0.325423; val RMSE 0.07627295; lr 0.001; 7s
network 4, training 5, epoch 40: train scaled MSE 0.301035; val RMSE 0.07572903; lr 0.001; 9s
network 4, training 5, epoch 50: train scaled MSE 0.275455; val RMSE 0.07671336; lr 0.001; 11s
network 4, training 5, epoch 60: train scaled MSE 0.227215; val RMSE 0.07517684; lr 0.0005; 14s
network 4, training 5, epoch 70: train scaled MSE 0.209755; val RMSE 0.07524762; lr 0.0005; 16s
network 4, training 5, epoch 80: train scaled MSE 0.199674; val RMSE 0.07520201; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.08303378

Network seed 4, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1338,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0850,59.6731,"[58.96%, 60.36%]",0.7725,0.0,0.8722
MLP,0.0774,66.5198,"[65.78%, 67.19%]",0.8158,5.6017,0.9216

network 4, training 6, epoch 1: train scaled MSE 0.90012; val RMSE 0.1165004; lr 0.001; 0s
network 4, training 6, epoch 10: train scaled MSE 0.430922; val RMSE 0.08491733; lr 0.001; 2s
network 4, training 6, epoch 20: train scaled MSE 0.371647; val RMSE 0.07940847; lr 0.001; 4s
network 4, training 6, epoch 30: train scaled MSE 0.335292; val RMSE 0.07663494; lr 0.001; 7s
network 4, training 6, epoch 40: train scaled MSE 0.301643; val RMSE 0.07561261; lr 0.001; 9s
network 4, training 6, epoch 50: train scaled MSE 0.272448; val RMSE 0.07535412; lr 0.001; 11s
network 4, training 6, epoch 60: train scaled MSE 0.239115; val RMSE 0.07574972; lr 0.001; 13s
network 4, training 6, epoch 70: train scaled MSE 0.217066; val RMSE 0.07545562; lr 0.0005; 15s
network 4, training 6, epoch 80: train scaled MSE 0.202059; val RMSE 0.07542595; lr 0.00025; 17s
network 4, training 6, epoch 90: train scaled MSE 0.195527; val RMSE 0.07567017; lr 0.000125; 20s
Standard Linear Baseline Validation RMSE: 0.08358018

Network seed 4, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1342,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0847,60.1667,"[59.49%, 60.87%]",0.7757,0.0,0.8761
MLP,0.0764,67.6226,"[66.96%, 68.30%]",0.8223,6.0182,0.9275

network 4, training 7, epoch 1: train scaled MSE 0.896394; val RMSE 0.1183063; lr 0.001; 0s
network 4, training 7, epoch 10: train scaled MSE 0.412206; val RMSE 0.08628083; lr 0.001; 2s
network 4, training 7, epoch 20: train scaled MSE 0.370183; val RMSE 0.08179842; lr 0.001; 5s
network 4, training 7, epoch 30: train scaled MSE 0.340796; val RMSE 0.07926192; lr 0.001; 7s
network 4, training 7, epoch 40: train scaled MSE 0.310264; val RMSE 0.07813224; lr 0.001; 9s
network 4, training 7, epoch 50: train scaled MSE 0.275008; val RMSE 0.07716821; lr 0.001; 11s
network 4, training 7, epoch 60: train scaled MSE 0.241572; val RMSE 0.07780632; lr 0.001; 13s
network 4, training 7, epoch 70: train scaled MSE 0.223332; val RMSE 0.07772609; lr 0.0005; 16s
network 4, training 7, epoch 80: train scaled MSE 0.204437; val RMSE 0.07762608; lr 0.00025; 18s
network 4, training 7, epoch 90: train scaled MSE 0.198263; val RMSE 0.07764472; lr 0.000125; 20s
Standard Linear Baseline Validation RMSE: 0.08634581

Network seed 4, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1325,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0830,60.8046,"[60.14%, 61.48%]",0.7798,0.0,0.8710
MLP,0.0746,68.3478,"[67.67%, 69.02%]",0.8268,6.0349,0.9268

network 4, training 8, epoch 1: train scaled MSE 0.900167; val RMSE 0.1183799; lr 0.001; 0s
network 4, training 8, epoch 10: train scaled MSE 0.419179; val RMSE 0.08848655; lr 0.001; 2s
network 4, training 8, epoch 20: train scaled MSE 0.368452; val RMSE 0.08293717; lr 0.001; 5s
network 4, training 8, epoch 30: train scaled MSE 0.360065; val RMSE 0.08096612; lr 0.001; 7s
network 4, training 8, epoch 40: train scaled MSE 0.295373; val RMSE 0.07930876; lr 0.001; 9s
network 4, training 8, epoch 50: train scaled MSE 0.261057; val RMSE 0.07953522; lr 0.001; 12s
network 4, training 8, epoch 60: train scaled MSE 0.236173; val RMSE 0.07874096; lr 0.0005; 14s
network 4, training 8, epoch 70: train scaled MSE 0.220499; val RMSE 0.07880626; lr 0.0005; 17s
network 4, training 8, epoch 80: train scaled MSE 0.209299; val RMSE 0.07877939; lr 0.00025; 19s
network 4, training 8, epoch 90: train scaled MSE 0.201421; val RMSE 0.07872148; lr 0.00025; 21s
network 4, training 8, epoch 100: train scaled MSE 0.195141; val RMSE 0.07874828; lr 0.000125; 23s
network 4, training 8, epoch 110: train scaled MSE 0.191272; val RMSE 0.07873366; lr 6.25e-05; 26s
network 4, training 8, epoch 120: train scaled MSE 0.189252; val RMSE 0.0787358; lr 3.125e-05; 28s
Standard Linear Baseline Validation RMSE: 0.08785265

Network seed 4, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1327,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0835,60.4522,"[59.81%, 61.16%]",0.7775,0.0,0.8723
MLP,0.0755,67.6190,"[66.92%, 68.31%]",0.8232,5.8726,0.9178

network 4, training 9, epoch 1: train scaled MSE 0.898573; val RMSE 0.114698; lr 0.001; 0s
network 4, training 9, epoch 10: train scaled MSE 0.421145; val RMSE 0.08633268; lr 0.001; 2s
network 4, training 9, epoch 20: train scaled MSE 0.370978; val RMSE 0.0808499; lr 0.001; 4s
network 4, training 9, epoch 30: train scaled MSE 0.338123; val RMSE 0.07845803; lr 0.001; 6s
network 4, training 9, epoch 40: train scaled MSE 0.298954; val RMSE 0.07764265; lr 0.001; 9s
network 4, training 9, epoch 50: train scaled MSE 0.263797; val RMSE 0.07683417; lr 0.001; 11s
network 4, training 9, epoch 60: train scaled MSE 0.231535; val RMSE 0.07686656; lr 0.0005; 13s
network 4, training 9, epoch 70: train scaled MSE 0.212172; val RMSE 0.07690683; lr 0.00025; 15s
network 4, training 9, epoch 80: train scaled MSE 0.205704; val RMSE 0.07723576; lr 0.00025; 17s
Standard Linear Baseline Validation RMSE: 0.0851516

Network seed 4, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1337,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0841,60.3852,"[59.69%, 61.03%]",0.7771,0.0,0.8782
MLP,0.0764,67.3238,"[66.64%, 67.99%]",0.8208,5.634,0.9181

Network 5: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   22.2s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   22.4s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   22.5s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   22.8s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   23.0s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   23.6s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   24.1s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   24.8s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   25.4s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   26.0s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   26.6s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   27.2s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   27.8s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   28.4s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   29.4s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   30.0s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   30.8s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   31.5s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   32.2s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   33.0s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   33.8s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   34.9s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   35.5s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   36.5s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   37.4s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   39.5s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   40.9s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   42.1s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   43.3s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   44.7s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   46.1s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   47.5s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   48.9s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   50.3s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   52.2s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   53.6s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   54.9s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   56.3s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   57.9s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   59.1s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 11.8min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 13.4min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 13.9min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 14.3min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 14.4min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 14.5min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 14.9min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 15.3min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 15.7min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 15.8min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 16.1min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 16.5min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 17.1min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 17.2min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 17.5min finished

network 5, training 0, epoch 1: train scaled MSE 0.899846; val RMSE 0.1172542; lr 0.001; 0s
network 5, training 0, epoch 10: train scaled MSE 0.419839; val RMSE 0.07619569; lr 0.001; 2s
network 5, training 0, epoch 20: train scaled MSE 0.360989; val RMSE 0.06787644; lr 0.001; 5s

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 18.4min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 18.5min finished

network 6, training 0, epoch 1: train scaled MSE 0.900333; val RMSE 0.1115898; lr 0.001; 0s
network 6, training 0, epoch 10: train scaled MSE 0.461449; val RMSE 0.07786035; lr 0.001; 2s
network 6, training 0, epoch 20: train scaled MSE 0.408031; val RMSE 0.07137357; lr 0.001; 5s
network 6, training 0, epoch 30: train scaled MSE 0.370852; val RMSE 0.06686966; lr 0.001; 7s
network 6, training 0, epoch 40: train scaled MSE 0.31986; val RMSE 0.0644213; lr 0.001; 10s
network 6, training 0, epoch 50: train scaled MSE 0.273138; val RMSE 0.06446536; lr 0.001; 12s
network 6, training 0, epoch 60: train scaled MSE 0.240552; val RMSE 0.06492343; lr 0.001; 14s
network 6, training 0, epoch 70: train scaled MSE 0.19386; val RMSE 0.06464295; lr 0.0005; 17s
network 6, training 0, epoch 80: train scaled MSE 0.17983; val RMSE 0.0649335; lr 0.0005; 19s
network 6, training 0, epoch 90: train scaled MSE 0.170872; val RMSE 0.06485688; lr 0.00025; 21s
Standard Linear Baseline Validation RMSE: 0.07850654

Network seed 6, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0998,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0799,35.8866,"[35.17%, 36.61%]",0.5988,0.0,0.7206
MLP,0.0656,56.8193,"[55.93%, 57.70%]",0.7548,26.0552,0.9350

network 6, training 1, epoch 1: train scaled MSE 0.898393; val RMSE 0.1143062; lr 0.001; 0s
network 6, training 1, epoch 10: train scaled MSE 0.448206; val RMSE 0.07983935; lr 0.001; 2s
network 6, training 1, epoch 20: train scaled MSE 0.394431; val RMSE 0.07411394; lr 0.001; 5s
network 6, training 1, epoch 30: train scaled MSE 0.343234; val RMSE 0.06940572; lr 0.001; 7s
network 6, training 1, epoch 40: train scaled MSE 0.300404; val RMSE 0.06857526; lr 0.001; 9s
network 6, training 1, epoch 50: train scaled MSE 0.267552; val RMSE 0.06801193; lr 0.001; 11s
network 6, training 1, epoch 60: train scaled MSE 0.227621; val RMSE 0.06779613; lr 0.001; 14s
network 6, training 1, epoch 70: train scaled MSE 0.195187; val RMSE 0.06846462; lr 0.001; 16s
network 6, training 1, epoch 80: train scaled MSE 0.171243; val RMSE 0.06776634; lr 0.0005; 18s
network 6, training 1, epoch 90: train scaled MSE 0.162584; val RMSE 0.06773854; lr 0.00025; 20s
network 6, training 1, epoch 100: train scaled MSE 0.152176; val RMSE 0.06783983; lr 0.000125; 23s
Standard Linear Baseline Validation RMSE: 0.08229899

Network seed 6, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0990,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0795,35.5108,"[34.77%, 36.25%]",0.5962,0.0,0.7221
MLP,0.0655,56.1679,"[55.25%, 57.14%]",0.7513,26.0292,0.9333

network 6, training 2, epoch 1: train scaled MSE 0.897602; val RMSE 0.1138078; lr 0.001; 0s
network 6, training 2, epoch 10: train scaled MSE 0.455818; val RMSE 0.07734428; lr 0.001; 2s
network 6, training 2, epoch 20: train scaled MSE 0.39471; val RMSE 0.06969876; lr 0.001; 5s
network 6, training 2, epoch 30: train scaled MSE 0.351176; val RMSE 0.06621984; lr 0.001; 7s
network 6, training 2, epoch 40: train scaled MSE 0.32681; val RMSE 0.06520764; lr 0.001; 10s
network 6, training 2, epoch 50: train scaled MSE 0.265523; val RMSE 0.06487195; lr 0.001; 12s
network 6, training 2, epoch 60: train scaled MSE 0.224308; val RMSE 0.06513678; lr 0.001; 14s
network 6, training 2, epoch 70: train scaled MSE 0.196883; val RMSE 0.06522739; lr 0.0005; 17s
network 6, training 2, epoch 80: train scaled MSE 0.183133; val RMSE 0.06518817; lr 0.00025; 19s
Standard Linear Baseline Validation RMSE: 0.08027169

Network seed 6, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0998,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0799,35.9256,"[35.20%, 36.65%]",0.5992,0.0,0.7169
MLP,0.0656,56.8737,"[55.94%, 57.79%]",0.7551,26.0141,0.9409

network 6, training 3, epoch 1: train scaled MSE 0.899025; val RMSE 0.1155577; lr 0.001; 0s
network 6, training 3, epoch 10: train scaled MSE 0.432923; val RMSE 0.07868344; lr 0.001; 2s
network 6, training 3, epoch 20: train scaled MSE 0.379132; val RMSE 0.0708214; lr 0.001; 5s
network 6, training 3, epoch 30: train scaled MSE 0.328883; val RMSE 0.06818792; lr 0.001; 7s
network 6, training 3, epoch 40: train scaled MSE 0.28228; val RMSE 0.0677518; lr 0.001; 9s
network 6, training 3, epoch 50: train scaled MSE 0.248395; val RMSE 0.06825237; lr 0.001; 12s
network 6, training 3, epoch 60: train scaled MSE 0.210638; val RMSE 0.06778231; lr 0.0005; 14s
network 6, training 3, epoch 70: train scaled MSE 0.196203; val RMSE 0.06772487; lr 0.00025; 16s
network 6, training 3, epoch 80: train scaled MSE 0.187168; val RMSE 0.06783929; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.08257632

Network seed 6, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0995,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0797,35.8567,"[35.14%, 36.58%]",0.5986,0.0,0.7189
MLP,0.0646,57.8414,"[56.95%, 58.73%]",0.7615,27.2177,0.9345

network 6, training 4, epoch 1: train scaled MSE 0.89709; val RMSE 0.1140144; lr 0.001; 0s
network 6, training 4, epoch 10: train scaled MSE 0.441008; val RMSE 0.07719103; lr 0.001; 2s
network 6, training 4, epoch 20: train scaled MSE 0.391647; val RMSE 0.07020163; lr 0.001; 4s
network 6, training 4, epoch 30: train scaled MSE 0.34559; val RMSE 0.06920582; lr 0.001; 7s
network 6, training 4, epoch 40: train scaled MSE 0.299263; val RMSE 0.06480132; lr 0.001; 9s
network 6, training 4, epoch 50: train scaled MSE 0.251486; val RMSE 0.06597123; lr 0.001; 11s
network 6, training 4, epoch 60: train scaled MSE 0.210708; val RMSE 0.06508581; lr 0.0005; 13s
network 6, training 4, epoch 70: train scaled MSE 0.19768; val RMSE 0.06615331; lr 0.00025; 15s
network 6, training 4, epoch 80: train scaled MSE 0.186543; val RMSE 0.06555443; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.07984846

Network seed 6, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1001,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0799,36.1497,"[35.47%, 36.84%]",0.6009,0.0,0.7345
MLP,0.0661,56.3622,"[55.48%, 57.20%]",0.7518,25.1118,0.9316

network 6, training 5, epoch 1: train scaled MSE 0.895454; val RMSE 0.1141298; lr 0.001; 0s
network 6, training 5, epoch 10: train scaled MSE 0.436509; val RMSE 0.07821477; lr 0.001; 2s
network 6, training 5, epoch 20: train scaled MSE 0.386739; val RMSE 0.07156883; lr 0.001; 5s
network 6, training 5, epoch 30: train scaled MSE 0.324463; val RMSE 0.06862502; lr 0.001; 7s
network 6, training 5, epoch 40: train scaled MSE 0.28721; val RMSE 0.06737843; lr 0.001; 9s
network 6, training 5, epoch 50: train scaled MSE 0.228658; val RMSE 0.06739871; lr 0.001; 12s
network 6, training 5, epoch 60: train scaled MSE 0.196534; val RMSE 0.06815262; lr 0.001; 14s
network 6, training 5, epoch 70: train scaled MSE 0.175084; val RMSE 0.06784657; lr 0.0005; 16s
network 6, training 5, epoch 80: train scaled MSE 0.163244; val RMSE 0.06789544; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.08165456

Network seed 6, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1003,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0804,35.7638,"[35.09%, 36.47%]",0.5977,0.0,0.7151
MLP,0.0660,56.7581,"[55.89%, 57.71%]",0.7546,26.2635,0.9383

network 6, training 6, epoch 1: train scaled MSE 0.894207; val RMSE 0.1129475; lr 0.001; 0s
network 6, training 6, epoch 10: train scaled MSE 0.44317; val RMSE 0.07824301; lr 0.001; 2s
network 6, training 6, epoch 20: train scaled MSE 0.393768; val RMSE 0.07108504; lr 0.001; 4s
network 6, training 6, epoch 30: train scaled MSE 0.339714; val RMSE 0.06711195; lr 0.001; 7s
network 6, training 6, epoch 40: train scaled MSE 0.289405; val RMSE 0.06690042; lr 0.001; 9s
network 6, training 6, epoch 50: train scaled MSE 0.241798; val RMSE 0.06707498; lr 0.001; 11s
network 6, training 6, epoch 60: train scaled MSE 0.199049; val RMSE 0.06679872; lr 0.0005; 14s
network 6, training 6, epoch 70: train scaled MSE 0.182964; val RMSE 0.06718978; lr 0.0005; 16s
network 6, training 6, epoch 80: train scaled MSE 0.170418; val RMSE 0.06729595; lr 0.00025; 18s
network 6, training 6, epoch 90: train scaled MSE 0.16388; val RMSE 0.06729293; lr 0.000125; 21s
Standard Linear Baseline Validation RMSE: 0.08078057

Network seed 6, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0999,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0802,35.5161,"[34.77%, 36.23%]",0.5959,0.0,0.7207
MLP,0.0658,56.5986,"[55.64%, 57.55%]",0.7544,26.5986,0.9410

network 6, training 7, epoch 1: train scaled MSE 0.898058; val RMSE 0.1133465; lr 0.001; 0s
network 6, training 7, epoch 10: train scaled MSE 0.434805; val RMSE 0.07644301; lr 0.001; 2s
network 6, training 7, epoch 20: train scaled MSE 0.381949; val RMSE 0.06953637; lr 0.001; 5s
network 6, training 7, epoch 30: train scaled MSE 0.33969; val RMSE 0.06782285; lr 0.001; 7s
network 6, training 7, epoch 40: train scaled MSE 0.288335; val RMSE 0.06792338; lr 0.001; 9s
network 6, training 7, epoch 50: train scaled MSE 0.231809; val RMSE 0.06727089; lr 0.001; 11s
network 6, training 7, epoch 60: train scaled MSE 0.207035; val RMSE 0.06701932; lr 0.0005; 14s
network 6, training 7, epoch 70: train scaled MSE 0.190164; val RMSE 0.0671968; lr 0.00025; 16s
Standard Linear Baseline Validation RMSE: 0.08135895

Network seed 6, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0989,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0796,35.2728,"[34.51%, 35.98%]",0.5941,0.0,0.7096
MLP,0.0650,56.8886,"[56.00%, 57.80%]",0.7549,27.0562,0.9229

network 6, training 8, epoch 1: train scaled MSE 0.899687; val RMSE 0.1130062; lr 0.001; 0s
network 6, training 8, epoch 10: train scaled MSE 0.445963; val RMSE 0.07734809; lr 0.001; 2s
network 6, training 8, epoch 20: train scaled MSE 0.393629; val RMSE 0.07001035; lr 0.001; 5s
network 6, training 8, epoch 30: train scaled MSE 0.360641; val RMSE 0.06672526; lr 0.001; 7s
network 6, training 8, epoch 40: train scaled MSE 0.309503; val RMSE 0.0649267; lr 0.001; 9s
network 6, training 8, epoch 50: train scaled MSE 0.264563; val RMSE 0.06617128; lr 0.001; 12s
network 6, training 8, epoch 60: train scaled MSE 0.226094; val RMSE 0.06550927; lr 0.001; 14s
network 6, training 8, epoch 70: train scaled MSE 0.198392; val RMSE 0.06513221; lr 0.0005; 16s
network 6, training 8, epoch 80: train scaled MSE 0.186071; val RMSE 0.06520604; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.07981256

Network seed 6, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1011,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0811,35.6648,"[34.99%, 36.32%]",0.5969,0.0,0.7264
MLP,0.0667,56.5187,"[55.64%, 57.34%]",0.7524,26.0532,0.9422

network 6, training 9, epoch 1: train scaled MSE 0.894119; val RMSE 0.1106598; lr 0.001; 0s
network 6, training 9, epoch 10: train scaled MSE 0.432137; val RMSE 0.07442109; lr 0.001; 2s
network 6, training 9, epoch 20: train scaled MSE 0.379787; val RMSE 0.06636947; lr 0.001; 5s
network 6, training 9, epoch 30: train scaled MSE 0.332038; val RMSE 0.06397467; lr 0.001; 7s
network 6, training 9, epoch 40: train scaled MSE 0.282634; val RMSE 0.06550794; lr 0.001; 9s
network 6, training 9, epoch 50: train scaled MSE 0.233628; val RMSE 0.0634116; lr 0.0005; 11s
network 6, training 9, epoch 60: train scaled MSE 0.214599; val RMSE 0.06303449; lr 0.0005; 14s
network 6, training 9, epoch 70: train scaled MSE 0.200999; val RMSE 0.0629716; lr 0.00025; 16s
network 6, training 9, epoch 80: train scaled MSE 0.194426; val RMSE 0.06320506; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.07747297

Network seed 6, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.1004,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0806,35.6072,"[34.87%, 36.31%]",0.5965,0.0,0.7180
MLP,0.0659,56.9140,"[55.97%, 57.83%]",0.7560,26.7435,0.9332

Network 7: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   20.6s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   20.8s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   20.9s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   21.1s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   21.4s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   21.9s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   22.4s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   23.0s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   23.6s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   24.6s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   25.0s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   26.4s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   27.1s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   28.2s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   29.0s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   29.8s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   31.6s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   32.7s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   33.7s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   34.6s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   35.7s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   36.9s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   38.1s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   39.4s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   40.6s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   42.0s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   43.3s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   44.4s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   45.5s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   46.9s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   48.2s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   49.5s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   50.8s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   52.1s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   53.5s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   55.1s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   56.6s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   57.9s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   59.9s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 11.5min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 11.8min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 12.5min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 12.9min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 14.0min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 14.3min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 14.5min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 15.1min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 15.5min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 15.8min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 17.1min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 17.2min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 17.5min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 17.6min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 17.8min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 17.9min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 18.1min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 18.2min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 18.3min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 18.4min finished

network 7, training 0, epoch 1: train scaled MSE 0.904826; val RMSE 0.1230565; lr 0.001; 0s
network 7, training 0, epoch 10: train scaled MSE 0.451693; val RMSE 0.07529383; lr 0.001; 2s
network 7, training 0, epoch 20: train scaled MSE 0.394735; val RMSE 0.07031746; lr 0.001; 4s
network 7, training 0, epoch 30: train scaled MSE 0.356977; val RMSE 0.06819919; lr 0.001; 6s
network 7, training 0, epoch 40: train scaled MSE 0.31359; val RMSE 0.06986589; lr 0.001; 8s
network 7, training 0, epoch 50: train scaled MSE 0.253449; val RMSE 0.068796; lr 0.0005; 10s
network 7, training 0, epoch 60: train scaled MSE 0.230628; val RMSE 0.06876065; lr 0.0005; 12s
network 7, training 0, epoch 70: train scaled MSE 0.216444; val RMSE 0.06898157; lr 0.00025; 15s
Standard Linear Baseline Validation RMSE: 0.07951438

Network seed 7, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0929,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0796,26.5084,"[25.46%, 27.52%]",0.5150,0.0,0.2059
MLP,0.0675,47.1777,"[45.98%, 48.39%]",0.6889,33.7606,0.2161

network 7, training 1, epoch 1: train scaled MSE 0.90869; val RMSE 0.1236244; lr 0.001; 0s
network 7, training 1, epoch 10: train scaled MSE 0.453231; val RMSE 0.07518431; lr 0.001; 2s
network 7, training 1, epoch 20: train scaled MSE 0.405232; val RMSE 0.06968534; lr 0.001; 5s
network 7, training 1, epoch 30: train scaled MSE 0.367731; val RMSE 0.06766608; lr 0.001; 7s
network 7, training 1, epoch 40: train scaled MSE 0.314538; val RMSE 0.0676769; lr 0.001; 9s
network 7, training 1, epoch 50: train scaled MSE 0.264227; val RMSE 0.06799338; lr 0.001; 11s
network 7, training 1, epoch 60: train scaled MSE 0.222642; val RMSE 0.06762672; lr 0.0005; 14s
network 7, training 1, epoch 70: train scaled MSE 0.202611; val RMSE 0.06799948; lr 0.00025; 16s
network 7, training 1, epoch 80: train scaled MSE 0.197994; val RMSE 0.06831226; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.07941805

Network seed 7, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0927,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0796,26.1618,"[25.18%, 27.20%]",0.5120,0.0,0.2051
MLP,0.0670,47.7987,"[46.68%, 48.99%]",0.6932,35.378,0.2123

network 7, training 2, epoch 1: train scaled MSE 0.905244; val RMSE 0.1218197; lr 0.001; 0s
network 7, training 2, epoch 10: train scaled MSE 0.455132; val RMSE 0.07690827; lr 0.001; 2s
network 7, training 2, epoch 20: train scaled MSE 0.399917; val RMSE 0.07059536; lr 0.001; 4s
network 7, training 2, epoch 30: train scaled MSE 0.351214; val RMSE 0.06872993; lr 0.001; 7s
network 7, training 2, epoch 40: train scaled MSE 0.300009; val RMSE 0.0677236; lr 0.001; 9s
network 7, training 2, epoch 50: train scaled MSE 0.26325; val RMSE 0.06828121; lr 0.001; 11s
network 7, training 2, epoch 60: train scaled MSE 0.234717; val RMSE 0.06785314; lr 0.0005; 13s
network 7, training 2, epoch 70: train scaled MSE 0.220035; val RMSE 0.06759281; lr 0.00025; 15s
Standard Linear Baseline Validation RMSE: 0.08038226

Network seed 7, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0936,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0802,26.6977,"[25.69%, 27.70%]",0.5167,0.0,0.2088
MLP,0.0680,47.2026,"[46.02%, 48.38%]",0.6886,33.2688,0.2150

network 7, training 3, epoch 1: train scaled MSE 0.905371; val RMSE 0.1240233; lr 0.001; 0s
network 7, training 3, epoch 10: train scaled MSE 0.452581; val RMSE 0.07898005; lr 0.001; 2s
network 7, training 3, epoch 20: train scaled MSE 0.396085; val RMSE 0.07216064; lr 0.001; 4s
network 7, training 3, epoch 30: train scaled MSE 0.347962; val RMSE 0.07189785; lr 0.001; 7s
network 7, training 3, epoch 40: train scaled MSE 0.28136; val RMSE 0.07029255; lr 0.001; 9s
network 7, training 3, epoch 50: train scaled MSE 0.23724; val RMSE 0.07131292; lr 0.001; 11s
network 7, training 3, epoch 60: train scaled MSE 0.206365; val RMSE 0.07131984; lr 0.0005; 13s
network 7, training 3, epoch 70: train scaled MSE 0.194403; val RMSE 0.07173018; lr 0.00025; 15s
network 7, training 3, epoch 80: train scaled MSE 0.18296; val RMSE 0.07161793; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.08364019

Network seed 7, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0920,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0793,25.6192,"[24.49%, 26.76%]",0.5075,0.0,0.2042
MLP,0.0672,46.6350,"[45.46%, 47.82%]",0.6847,34.9057,0.2110

network 7, training 4, epoch 1: train scaled MSE 0.908957; val RMSE 0.1223607; lr 0.001; 0s
network 7, training 4, epoch 10: train scaled MSE 0.458205; val RMSE 0.07639568; lr 0.001; 2s
network 7, training 4, epoch 20: train scaled MSE 0.408607; val RMSE 0.07075409; lr 0.001; 4s
network 7, training 4, epoch 30: train scaled MSE 0.353208; val RMSE 0.06778952; lr 0.001; 7s
network 7, training 4, epoch 40: train scaled MSE 0.299846; val RMSE 0.0688302; lr 0.001; 9s
network 7, training 4, epoch 50: train scaled MSE 0.258516; val RMSE 0.06744095; lr 0.001; 11s
network 7, training 4, epoch 60: train scaled MSE 0.226036; val RMSE 0.06734903; lr 0.0005; 13s
network 7, training 4, epoch 70: train scaled MSE 0.208941; val RMSE 0.0674821; lr 0.00025; 16s
network 7, training 4, epoch 80: train scaled MSE 0.199175; val RMSE 0.0674015; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.07949768

Network seed 7, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0938,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0808,25.7976,"[24.64%, 26.86%]",0.5085,0.0,0.2051
MLP,0.0684,46.8676,"[45.62%, 48.06%]",0.6862,34.936,0.2143

network 7, training 5, epoch 1: train scaled MSE 0.900285; val RMSE 0.1217499; lr 0.001; 0s
network 7, training 5, epoch 10: train scaled MSE 0.455649; val RMSE 0.07634102; lr 0.001; 2s
network 7, training 5, epoch 20: train scaled MSE 0.391265; val RMSE 0.07070059; lr 0.001; 4s
network 7, training 5, epoch 30: train scaled MSE 0.348298; val RMSE 0.06920433; lr 0.001; 7s
network 7, training 5, epoch 40: train scaled MSE 0.294207; val RMSE 0.06924175; lr 0.001; 9s
network 7, training 5, epoch 50: train scaled MSE 0.250648; val RMSE 0.07188198; lr 0.0005; 11s
network 7, training 5, epoch 60: train scaled MSE 0.227697; val RMSE 0.06958267; lr 0.00025; 13s
network 7, training 5, epoch 70: train scaled MSE 0.217522; val RMSE 0.06995151; lr 0.000125; 16s
Standard Linear Baseline Validation RMSE: 0.08096966

Network seed 7, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0934,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0802,26.2557,"[25.22%, 27.30%]",0.5126,0.0,0.2040
MLP,0.0673,48.0403,"[46.86%, 49.19%]",0.6944,35.4548,0.2143

network 7, training 6, epoch 1: train scaled MSE 0.908181; val RMSE 0.1211189; lr 0.001; 0s
network 7, training 6, epoch 10: train scaled MSE 0.46722; val RMSE 0.07885814; lr 0.001; 2s
network 7, training 6, epoch 20: train scaled MSE 0.413144; val RMSE 0.0714352; lr 0.001; 4s
network 7, training 6, epoch 30: train scaled MSE 0.366347; val RMSE 0.06938885; lr 0.001; 6s
network 7, training 6, epoch 40: train scaled MSE 0.326838; val RMSE 0.06744965; lr 0.001; 8s
network 7, training 6, epoch 50: train scaled MSE 0.285935; val RMSE 0.0670639; lr 0.001; 10s
network 7, training 6, epoch 60: train scaled MSE 0.248309; val RMSE 0.06846531; lr 0.001; 12s
network 7, training 6, epoch 70: train scaled MSE 0.219797; val RMSE 0.06755726; lr 0.0005; 14s
network 7, training 6, epoch 80: train scaled MSE 0.203452; val RMSE 0.06761301; lr 0.00025; 16s
network 7, training 6, epoch 90: train scaled MSE 0.194855; val RMSE 0.06770417; lr 0.000125; 18s
Standard Linear Baseline Validation RMSE: 0.07959704

Network seed 7, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0935,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0806,25.7526,"[24.67%, 26.85%]",0.5081,0.0,0.2074
MLP,0.0680,47.0729,"[45.83%, 48.25%]",0.6882,35.4368,0.2174

network 7, training 7, epoch 1: train scaled MSE 0.906661; val RMSE 0.1218608; lr 0.001; 0s
network 7, training 7, epoch 10: train scaled MSE 0.452057; val RMSE 0.07615429; lr 0.001; 2s
network 7, training 7, epoch 20: train scaled MSE 0.399724; val RMSE 0.07069751; lr 0.001; 4s
network 7, training 7, epoch 30: train scaled MSE 0.344324; val RMSE 0.07053743; lr 0.001; 7s
network 7, training 7, epoch 40: train scaled MSE 0.288709; val RMSE 0.06766146; lr 0.001; 9s
network 7, training 7, epoch 50: train scaled MSE 0.24574; val RMSE 0.06877235; lr 0.001; 11s
network 7, training 7, epoch 60: train scaled MSE 0.221026; val RMSE 0.06806303; lr 0.0005; 13s
network 7, training 7, epoch 70: train scaled MSE 0.205646; val RMSE 0.06793514; lr 0.00025; 15s
Standard Linear Baseline Validation RMSE: 0.08099725

Network seed 7, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0919,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0793,25.5598,"[24.33%, 26.68%]",0.5074,0.0,0.2028
MLP,0.0672,46.4402,"[45.18%, 47.61%]",0.6848,34.9649,0.2090

network 7, training 8, epoch 1: train scaled MSE 0.904448; val RMSE 0.1209762; lr 0.001; 0s
network 7, training 8, epoch 10: train scaled MSE 0.450605; val RMSE 0.07542639; lr 0.001; 2s
network 7, training 8, epoch 20: train scaled MSE 0.395871; val RMSE 0.07006291; lr 0.001; 4s
network 7, training 8, epoch 30: train scaled MSE 0.340645; val RMSE 0.06834967; lr 0.001; 6s
network 7, training 8, epoch 40: train scaled MSE 0.285191; val RMSE 0.06821612; lr 0.001; 8s
network 7, training 8, epoch 50: train scaled MSE 0.238781; val RMSE 0.06917414; lr 0.001; 10s
network 7, training 8, epoch 60: train scaled MSE 0.214687; val RMSE 0.06828592; lr 0.0005; 12s
network 7, training 8, epoch 70: train scaled MSE 0.202448; val RMSE 0.0684736; lr 0.00025; 14s
Standard Linear Baseline Validation RMSE: 0.07998834

Network seed 7, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0928,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0799,25.8109,"[24.68%, 26.89%]",0.5088,0.0,0.2067
MLP,0.0674,47.2159,"[46.05%, 48.38%]",0.6905,35.7224,0.2146

network 7, training 9, epoch 1: train scaled MSE 0.908668; val RMSE 0.1193903; lr 0.001; 0s
network 7, training 9, epoch 10: train scaled MSE 0.459696; val RMSE 0.07527173; lr 0.001; 2s
network 7, training 9, epoch 20: train scaled MSE 0.407938; val RMSE 0.06990096; lr 0.001; 4s
network 7, training 9, epoch 30: train scaled MSE 0.363605; val RMSE 0.0678378; lr 0.001; 7s
network 7, training 9, epoch 40: train scaled MSE 0.314196; val RMSE 0.0670358; lr 0.001; 9s
network 7, training 9, epoch 50: train scaled MSE 0.266454; val RMSE 0.06737095; lr 0.001; 11s
network 7, training 9, epoch 60: train scaled MSE 0.230109; val RMSE 0.0671487; lr 0.0005; 13s
network 7, training 9, epoch 70: train scaled MSE 0.209075; val RMSE 0.06720431; lr 0.00025; 15s
network 7, training 9, epoch 80: train scaled MSE 0.199002; val RMSE 0.06734585; lr 0.000125; 17s
network 7, training 9, epoch 90: train scaled MSE 0.194742; val RMSE 0.06753985; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.0792012

Network seed 7, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0929,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0798,26.0767,"[25.01%, 27.09%]",0.5112,0.0,0.2051
MLP,0.0679,46.5886,"[45.38%, 47.85%]",0.6861,34.2055,0.2159

Network 8: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   23.6s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   25.2s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   25.9s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   26.0s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   26.4s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   27.0s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   27.7s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   28.3s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   29.1s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   29.8s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   31.4s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   32.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   32.5s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   33.3s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   33.9s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   34.8s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   35.5s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   36.4s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   37.4s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   39.4s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   40.8s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   41.8s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   43.1s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   44.3s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   45.7s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   46.7s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   48.4s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   49.9s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   51.4s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   52.7s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   54.3s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   56.0s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   57.3s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   58.6s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  5.3min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.9min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  7.4min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  9.5min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  9.7min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed: 10.2min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 11.5min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 12.1min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 12.9min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 13.3min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 13.4min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 13.7min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 13.9min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 14.0min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 14.4min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 14.5min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 14.9min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 15.1min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 15.3min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 15.5min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 15.8min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 16.6min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 17.1min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 17.3min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 17.6min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 17.7min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 17.8min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 18.0min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 18.1min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 18.3min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 18.4min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 18.6min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 18.7min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 18.9min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 19.0min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 19.1min finished

network 8, training 0, epoch 1: train scaled MSE 0.899384; val RMSE 0.1167179; lr 0.001; 0s
network 8, training 0, epoch 10: train scaled MSE 0.463426; val RMSE 0.07248636; lr 0.001; 2s
network 8, training 0, epoch 20: train scaled MSE 0.405119; val RMSE 0.06587932; lr 0.001; 5s
network 8, training 0, epoch 30: train scaled MSE 0.35717; val RMSE 0.06270098; lr 0.001; 7s
network 8, training 0, epoch 40: train scaled MSE 0.316858; val RMSE 0.0621688; lr 0.001; 10s
network 8, training 0, epoch 50: train scaled MSE 0.264699; val RMSE 0.06211845; lr 0.001; 12s
network 8, training 0, epoch 60: train scaled MSE 0.263271; val RMSE 0.06236483; lr 0.0005; 14s
network 8, training 0, epoch 70: train scaled MSE 0.212886; val RMSE 0.06196438; lr 0.00025; 17s
network 8, training 0, epoch 80: train scaled MSE 0.203694; val RMSE 0.06220365; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.07787621

Network seed 8, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0963,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0810,29.2737,"[28.03%, 30.44%]",0.5414,0.0,0.2045
MLP,0.0659,53.0977,"[51.80%, 54.29%]",0.7308,34.9971,0.2140

network 8, training 1, epoch 1: train scaled MSE 0.902755; val RMSE 0.1180065; lr 0.001; 0s
network 8, training 1, epoch 10: train scaled MSE 0.449113; val RMSE 0.0725361; lr 0.001; 2s
network 8, training 1, epoch 20: train scaled MSE 0.3995; val RMSE 0.06648628; lr 0.001; 5s
network 8, training 1, epoch 30: train scaled MSE 0.353809; val RMSE 0.06541834; lr 0.001; 7s
network 8, training 1, epoch 40: train scaled MSE 0.288393; val RMSE 0.06442204; lr 0.001; 9s
network 8, training 1, epoch 50: train scaled MSE 0.263062; val RMSE 0.06575432; lr 0.0005; 11s
network 8, training 1, epoch 60: train scaled MSE 0.233717; val RMSE 0.0644235; lr 0.00025; 13s
network 8, training 1, epoch 70: train scaled MSE 0.224667; val RMSE 0.06451558; lr 0.000125; 15s
Standard Linear Baseline Validation RMSE: 0.07884771

Network seed 8, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0959,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0809,28.7809,"[27.43%, 29.98%]",0.5373,0.0,0.2053
MLP,0.0664,52.0982,"[50.71%, 53.28%]",0.7221,34.3803,0.2150

network 8, training 2, epoch 1: train scaled MSE 0.89615; val RMSE 0.1208014; lr 0.001; 0s
network 8, training 2, epoch 10: train scaled MSE 0.461357; val RMSE 0.07711393; lr 0.001; 2s
network 8, training 2, epoch 20: train scaled MSE 0.409092; val RMSE 0.06960668; lr 0.001; 4s
network 8, training 2, epoch 30: train scaled MSE 0.384086; val RMSE 0.06815652; lr 0.001; 6s
network 8, training 2, epoch 40: train scaled MSE 0.323007; val RMSE 0.06672958; lr 0.001; 8s
network 8, training 2, epoch 50: train scaled MSE 0.273449; val RMSE 0.06700798; lr 0.001; 11s
network 8, training 2, epoch 60: train scaled MSE 0.237752; val RMSE 0.06706107; lr 0.0005; 13s
network 8, training 2, epoch 70: train scaled MSE 0.219446; val RMSE 0.06745053; lr 0.00025; 15s
network 8, training 2, epoch 80: train scaled MSE 0.209586; val RMSE 0.0675766; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.08262754

Network seed 8, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0957,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0811,28.3239,"[27.02%, 29.61%]",0.5334,0.0,0.2039
MLP,0.0665,51.8161,"[50.57%, 53.06%]",0.7207,35.103,0.2143

network 8, training 3, epoch 1: train scaled MSE 0.899985; val RMSE 0.1188693; lr 0.001; 0s
network 8, training 3, epoch 10: train scaled MSE 0.468385; val RMSE 0.07374745; lr 0.001; 2s
network 8, training 3, epoch 20: train scaled MSE 0.401697; val RMSE 0.06559224; lr 0.001; 4s
network 8, training 3, epoch 30: train scaled MSE 0.347004; val RMSE 0.06597459; lr 0.001; 6s
network 8, training 3, epoch 40: train scaled MSE 0.292472; val RMSE 0.06343569; lr 0.001; 8s
network 8, training 3, epoch 50: train scaled MSE 0.250266; val RMSE 0.06400414; lr 0.001; 11s
network 8, training 3, epoch 60: train scaled MSE 0.205227; val RMSE 0.06399491; lr 0.0005; 13s
network 8, training 3, epoch 70: train scaled MSE 0.187305; val RMSE 0.06395616; lr 0.00025; 15s
network 8, training 3, epoch 80: train scaled MSE 0.178024; val RMSE 0.06406597; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.07886655

Network seed 8, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0962,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0810,29.1240,"[27.97%, 30.25%]",0.5400,0.0,0.2013
MLP,0.0661,52.8119,"[51.55%, 54.04%]",0.7277,34.7574,0.2136

network 8, training 4, epoch 1: train scaled MSE 0.9007; val RMSE 0.1192776; lr 0.001; 0s
network 8, training 4, epoch 10: train scaled MSE 0.455462; val RMSE 0.07348416; lr 0.001; 2s
network 8, training 4, epoch 20: train scaled MSE 0.42094; val RMSE 0.06813568; lr 0.001; 5s
network 8, training 4, epoch 30: train scaled MSE 0.363285; val RMSE 0.06610081; lr 0.001; 7s
network 8, training 4, epoch 40: train scaled MSE 0.311359; val RMSE 0.06561894; lr 0.001; 9s
network 8, training 4, epoch 50: train scaled MSE 0.259823; val RMSE 0.06581258; lr 0.001; 11s
network 8, training 4, epoch 60: train scaled MSE 0.230391; val RMSE 0.06598464; lr 0.0005; 13s
network 8, training 4, epoch 70: train scaled MSE 0.215332; val RMSE 0.06598385; lr 0.00025; 15s
network 8, training 4, epoch 80: train scaled MSE 0.200578; val RMSE 0.06561392; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.08045376

Network seed 8, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0963,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0809,29.3678,"[28.14%, 30.50%]",0.5420,0.0,0.2015
MLP,0.0666,52.2122,"[50.95%, 53.47%]",0.7234,33.4886,0.2096

network 8, training 5, epoch 1: train scaled MSE 0.897155; val RMSE 0.1206778; lr 0.001; 0s
network 8, training 5, epoch 10: train scaled MSE 0.454587; val RMSE 0.07546709; lr 0.001; 2s
network 8, training 5, epoch 20: train scaled MSE 0.394524; val RMSE 0.07006936; lr 0.001; 4s
network 8, training 5, epoch 30: train scaled MSE 0.339878; val RMSE 0.06981124; lr 0.001; 7s
network 8, training 5, epoch 40: train scaled MSE 0.302409; val RMSE 0.06946485; lr 0.001; 9s
network 8, training 5, epoch 50: train scaled MSE 0.255853; val RMSE 0.07029167; lr 0.001; 11s
network 8, training 5, epoch 60: train scaled MSE 0.22039; val RMSE 0.06891595; lr 0.0005; 13s
network 8, training 5, epoch 70: train scaled MSE 0.20306; val RMSE 0.06891464; lr 0.00025; 15s
network 8, training 5, epoch 80: train scaled MSE 0.19466; val RMSE 0.06900232; lr 0.00025; 17s
network 8, training 5, epoch 90: train scaled MSE 0.190106; val RMSE 0.06932078; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.081639

Network seed 8, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0949,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0801,28.7338,"[27.39%, 29.93%]",0.5372,0.0,0.1998
MLP,0.0655,52.4278,"[51.11%, 53.66%]",0.7265,35.2429,0.2126

network 8, training 6, epoch 1: train scaled MSE 0.898764; val RMSE 0.1195963; lr 0.001; 0s
network 8, training 6, epoch 10: train scaled MSE 0.46117; val RMSE 0.07564599; lr 0.001; 2s
network 8, training 6, epoch 20: train scaled MSE 0.402036; val RMSE 0.06835314; lr 0.001; 5s
network 8, training 6, epoch 30: train scaled MSE 0.370864; val RMSE 0.06731583; lr 0.001; 7s
network 8, training 6, epoch 40: train scaled MSE 0.29773; val RMSE 0.06605126; lr 0.001; 10s
network 8, training 6, epoch 50: train scaled MSE 0.244028; val RMSE 0.06627543; lr 0.001; 12s
network 8, training 6, epoch 60: train scaled MSE 0.253327; val RMSE 0.06665735; lr 0.0005; 14s
network 8, training 6, epoch 70: train scaled MSE 0.201934; val RMSE 0.0662653; lr 0.00025; 17s
network 8, training 6, epoch 80: train scaled MSE 0.193996; val RMSE 0.06624624; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.07972051

Network seed 8, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0957,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0809,28.4721,"[27.23%, 29.70%]",0.5343,0.0,0.2055
MLP,0.0665,51.7271,"[50.47%, 52.95%]",0.7209,34.9231,0.2138

network 8, training 7, epoch 1: train scaled MSE 0.900972; val RMSE 0.1168127; lr 0.001; 0s
network 8, training 7, epoch 10: train scaled MSE 0.449082; val RMSE 0.0726168; lr 0.001; 2s
network 8, training 7, epoch 20: train scaled MSE 0.396649; val RMSE 0.06616799; lr 0.001; 4s
network 8, training 7, epoch 30: train scaled MSE 0.35594; val RMSE 0.06504767; lr 0.001; 6s
network 8, training 7, epoch 40: train scaled MSE 0.30461; val RMSE 0.06480635; lr 0.001; 9s
network 8, training 7, epoch 50: train scaled MSE 0.262468; val RMSE 0.06415353; lr 0.0005; 11s
network 8, training 7, epoch 60: train scaled MSE 0.237791; val RMSE 0.06462044; lr 0.0005; 13s
network 8, training 7, epoch 70: train scaled MSE 0.233222; val RMSE 0.06626929; lr 0.00025; 15s
network 8, training 7, epoch 80: train scaled MSE 0.215265; val RMSE 0.06466243; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.07858981

Network seed 8, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0963,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0808,29.5142,"[28.31%, 30.72%]",0.5433,0.0,0.2054
MLP,0.0656,53.6614,"[52.43%, 54.88%]",0.7337,35.031,0.2250

network 8, training 8, epoch 1: train scaled MSE 0.892835; val RMSE 0.1204529; lr 0.001; 0s
network 8, training 8, epoch 10: train scaled MSE 0.45276; val RMSE 0.07872444; lr 0.001; 2s
network 8, training 8, epoch 20: train scaled MSE 0.392909; val RMSE 0.07168144; lr 0.001; 5s
network 8, training 8, epoch 30: train scaled MSE 0.34922; val RMSE 0.06986754; lr 0.001; 7s
network 8, training 8, epoch 40: train scaled MSE 0.287755; val RMSE 0.06992677; lr 0.001; 9s
network 8, training 8, epoch 50: train scaled MSE 0.233058; val RMSE 0.07014654; lr 0.001; 11s
network 8, training 8, epoch 60: train scaled MSE 0.201575; val RMSE 0.07029238; lr 0.0005; 14s
network 8, training 8, epoch 70: train scaled MSE 0.187203; val RMSE 0.07035547; lr 0.00025; 16s
Standard Linear Baseline Validation RMSE: 0.08479915

Network seed 8, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0950,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0801,28.9456,"[27.77%, 30.15%]",0.5383,0.0,0.2019
MLP,0.0661,51.6209,"[50.34%, 52.94%]",0.7198,33.7268,0.2154

network 8, training 9, epoch 1: train scaled MSE 0.898042; val RMSE 0.1193905; lr 0.001; 0s
network 8, training 9, epoch 10: train scaled MSE 0.457021; val RMSE 0.07578608; lr 0.001; 2s
network 8, training 9, epoch 20: train scaled MSE 0.394507; val RMSE 0.06909462; lr 0.001; 5s
network 8, training 9, epoch 30: train scaled MSE 0.349872; val RMSE 0.06777829; lr 0.001; 7s
network 8, training 9, epoch 40: train scaled MSE 0.295631; val RMSE 0.06761312; lr 0.001; 9s
network 8, training 9, epoch 50: train scaled MSE 0.24808; val RMSE 0.0681572; lr 0.001; 12s
network 8, training 9, epoch 60: train scaled MSE 0.212269; val RMSE 0.06773404; lr 0.0005; 14s
network 8, training 9, epoch 70: train scaled MSE 0.193289; val RMSE 0.06746672; lr 0.00025; 16s
network 8, training 9, epoch 80: train scaled MSE 0.185632; val RMSE 0.06767791; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.08193301

Network seed 8, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0955,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0807,28.5655,"[27.23%, 29.81%]",0.5358,0.0,0.2017
MLP,0.0664,51.6798,"[50.33%, 52.94%]",0.7210,34.5527,0.2100

Network 9: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
/home/jovyan/my-conda-envs/grn_env/lib/python3.11/site-packages/joblib/externals/loky/process_executor.py:787: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:    0.7s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:    1.2s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:    1.6s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:    2.1s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:    2.6s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:    2.9s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:    3.6s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:    4.3s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:    4.9s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:    5.5s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:    6.2s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:    6.9s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:    7.6s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:    8.4s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:    9.1s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:    9.8s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   10.5s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   11.4s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   12.3s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   13.2s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   14.1s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   15.1s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   16.2s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   17.1s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   18.2s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   19.3s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   20.4s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   21.5s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   22.6s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   24.0s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   25.3s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   26.7s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   29.4s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   30.7s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   32.5s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   33.9s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   35.5s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   36.9s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   39.8s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   41.5s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   43.1s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   44.7s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   46.3s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   48.7s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   50.8s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   52.6s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   54.4s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   56.2s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   58.6s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  5.2min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  5.4min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  5.5min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  5.6min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  5.7min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  5.8min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  6.0min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  6.1min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  6.2min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  6.3min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  6.4min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  6.5min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  6.6min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  6.7min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  6.8min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  6.9min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  7.0min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  7.1min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  7.2min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  7.3min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  7.5min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  7.6min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  7.7min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  7.8min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  7.9min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  8.0min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  8.1min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  8.2min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  8.3min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  8.4min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  8.5min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  8.6min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  8.7min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  8.8min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  8.9min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  9.0min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  9.1min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  9.2min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  9.3min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  9.4min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  9.6min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  9.8min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  9.9min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed: 10.0min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed: 10.1min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed: 10.3min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed: 10.4min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed: 10.5min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed: 10.6min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed: 10.7min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed: 10.8min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed: 10.9min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed: 11.0min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed: 11.1min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed: 11.2min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed: 11.3min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed: 11.4min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed: 11.6min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed: 11.7min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed: 11.9min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed: 12.0min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed: 12.1min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed: 12.2min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed: 12.3min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed: 12.4min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed: 12.6min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed: 12.7min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed: 12.8min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed: 12.9min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed: 13.0min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed: 13.1min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed: 13.2min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed: 13.4min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed: 13.5min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed: 13.6min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed: 13.8min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed: 14.0min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed: 14.1min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed: 14.2min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed: 14.3min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed: 14.4min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed: 14.5min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed: 14.6min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed: 14.7min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed: 14.8min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed: 15.0min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed: 15.1min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed: 15.2min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed: 15.3min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed: 15.4min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed: 15.6min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed: 15.7min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed: 15.8min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed: 15.9min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed: 16.0min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed: 16.2min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed: 16.3min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed: 16.4min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed: 16.5min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed: 16.7min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed: 16.8min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed: 16.9min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed: 17.0min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed: 17.2min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed: 17.3min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed: 17.4min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed: 17.5min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed: 17.7min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed: 17.8min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed: 17.9min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed: 18.0min finished

network 9, training 0, epoch 1: train scaled MSE 0.889997; val RMSE 0.1087774; lr 0.001; 0s
network 9, training 0, epoch 10: train scaled MSE 0.416189; val RMSE 0.06870552; lr 0.001; 2s
network 9, training 0, epoch 20: train scaled MSE 0.366124; val RMSE 0.06166883; lr 0.001; 4s
network 9, training 0, epoch 30: train scaled MSE 0.323293; val RMSE 0.05908627; lr 0.001; 6s
network 9, training 0, epoch 40: train scaled MSE 0.289275; val RMSE 0.05807895; lr 0.001; 9s
network 9, training 0, epoch 50: train scaled MSE 0.240748; val RMSE 0.05814308; lr 0.001; 11s
network 9, training 0, epoch 60: train scaled MSE 0.196915; val RMSE 0.05828869; lr 0.0005; 13s
network 9, training 0, epoch 70: train scaled MSE 0.178054; val RMSE 0.05838244; lr 0.00025; 15s
network 9, training 0, epoch 80: train scaled MSE 0.168059; val RMSE 0.0584662; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.06932988

Network seed 9, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0777,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0685,22.2796,"[21.01%, 23.40%]",0.4722,0.0,0.1498
MLP,0.0570,46.0984,"[44.56%, 47.55%]",0.6806,44.142,0.1549

network 9, training 1, epoch 1: train scaled MSE 0.894613; val RMSE 0.109352; lr 0.001; 0s
network 9, training 1, epoch 10: train scaled MSE 0.382752; val RMSE 0.0631114; lr 0.001; 2s
network 9, training 1, epoch 20: train scaled MSE 0.330761; val RMSE 0.05744982; lr 0.001; 4s
network 9, training 1, epoch 30: train scaled MSE 0.28675; val RMSE 0.05597428; lr 0.001; 6s
network 9, training 1, epoch 40: train scaled MSE 0.24623; val RMSE 0.05598703; lr 0.001; 8s
network 9, training 1, epoch 50: train scaled MSE 0.212542; val RMSE 0.05620028; lr 0.0005; 10s
network 9, training 1, epoch 60: train scaled MSE 0.191157; val RMSE 0.05593181; lr 0.0005; 12s
network 9, training 1, epoch 70: train scaled MSE 0.179977; val RMSE 0.0559032; lr 0.00025; 14s
network 9, training 1, epoch 80: train scaled MSE 0.173533; val RMSE 0.05600915; lr 0.000125; 16s
Standard Linear Baseline Validation RMSE: 0.067718

Network seed 9, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0784,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0692,22.0319,"[20.78%, 23.15%]",0.4695,0.0,0.1492
MLP,0.0572,46.7798,"[45.24%, 48.19%]",0.6871,46.3304,0.1525

network 9, training 2, epoch 1: train scaled MSE 0.891786; val RMSE 0.1095543; lr 0.001; 0s
network 9, training 2, epoch 10: train scaled MSE 0.398928; val RMSE 0.06467545; lr 0.001; 2s
network 9, training 2, epoch 20: train scaled MSE 0.348485; val RMSE 0.05855603; lr 0.001; 4s
network 9, training 2, epoch 30: train scaled MSE 0.306047; val RMSE 0.0577383; lr 0.001; 6s
network 9, training 2, epoch 40: train scaled MSE 0.261146; val RMSE 0.05643658; lr 0.001; 8s
network 9, training 2, epoch 50: train scaled MSE 0.21425; val RMSE 0.05650398; lr 0.001; 10s
network 9, training 2, epoch 60: train scaled MSE 0.180286; val RMSE 0.05675967; lr 0.0005; 13s
network 9, training 2, epoch 70: train scaled MSE 0.164592; val RMSE 0.05671709; lr 0.00025; 15s
network 9, training 2, epoch 80: train scaled MSE 0.155468; val RMSE 0.05674286; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.06912393

Network seed 9, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0775,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0686,21.6766,"[20.42%, 22.89%]",0.4670,0.0,0.1487
MLP,0.0565,46.8562,"[45.31%, 48.34%]",0.6877,47.2548,0.1517

network 9, training 3, epoch 1: train scaled MSE 0.889988; val RMSE 0.1078532; lr 0.001; 0s
network 9, training 3, epoch 10: train scaled MSE 0.393996; val RMSE 0.06436624; lr 0.001; 2s
network 9, training 3, epoch 20: train scaled MSE 0.347389; val RMSE 0.05932621; lr 0.001; 4s
network 9, training 3, epoch 30: train scaled MSE 0.316265; val RMSE 0.05796642; lr 0.001; 6s
network 9, training 3, epoch 40: train scaled MSE 0.274358; val RMSE 0.05766657; lr 0.001; 8s
network 9, training 3, epoch 50: train scaled MSE 0.23398; val RMSE 0.05781423; lr 0.001; 10s
network 9, training 3, epoch 60: train scaled MSE 0.193854; val RMSE 0.05696231; lr 0.0005; 13s
network 9, training 3, epoch 70: train scaled MSE 0.175418; val RMSE 0.05732736; lr 0.0005; 15s
network 9, training 3, epoch 80: train scaled MSE 0.164744; val RMSE 0.05730125; lr 0.00025; 17s
network 9, training 3, epoch 90: train scaled MSE 0.158751; val RMSE 0.05729238; lr 0.000125; 19s
Standard Linear Baseline Validation RMSE: 0.06914869

Network seed 9, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0774,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0685,21.7760,"[20.66%, 22.87%]",0.4670,0.0,0.1477
MLP,0.0574,45.0174,"[43.49%, 46.54%]",0.6749,44.5202,0.1547

network 9, training 4, epoch 1: train scaled MSE 0.893238; val RMSE 0.1096323; lr 0.001; 0s
network 9, training 4, epoch 10: train scaled MSE 0.398035; val RMSE 0.06480713; lr 0.001; 2s
network 9, training 4, epoch 20: train scaled MSE 0.34519; val RMSE 0.05852453; lr 0.001; 4s
network 9, training 4, epoch 30: train scaled MSE 0.299355; val RMSE 0.05721968; lr 0.001; 6s
network 9, training 4, epoch 40: train scaled MSE 0.247572; val RMSE 0.05633492; lr 0.001; 8s
network 9, training 4, epoch 50: train scaled MSE 0.193703; val RMSE 0.05622219; lr 0.0005; 10s
network 9, training 4, epoch 60: train scaled MSE 0.173727; val RMSE 0.05671052; lr 0.0005; 13s
network 9, training 4, epoch 70: train scaled MSE 0.16006; val RMSE 0.05699016; lr 0.00025; 15s
network 9, training 4, epoch 80: train scaled MSE 0.153839; val RMSE 0.05692931; lr 0.000125; 17s
network 9, training 4, epoch 90: train scaled MSE 0.149976; val RMSE 0.05699601; lr 6.25e-05; 19s
Standard Linear Baseline Validation RMSE: 0.06894375

Network seed 9, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0768,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0681,21.3375,"[20.08%, 22.46%]",0.4638,0.0,0.1464
MLP,0.0567,45.4578,"[43.86%, 46.99%]",0.6803,46.6878,0.1517

network 9, training 5, epoch 1: train scaled MSE 0.892666; val RMSE 0.110816; lr 0.001; 0s
network 9, training 5, epoch 10: train scaled MSE 0.395365; val RMSE 0.06529916; lr 0.001; 2s
network 9, training 5, epoch 20: train scaled MSE 0.353924; val RMSE 0.06039729; lr 0.001; 4s
network 9, training 5, epoch 30: train scaled MSE 0.323417; val RMSE 0.05889431; lr 0.001; 6s
network 9, training 5, epoch 40: train scaled MSE 0.305656; val RMSE 0.05946582; lr 0.001; 9s
network 9, training 5, epoch 50: train scaled MSE 0.247813; val RMSE 0.05751273; lr 0.0005; 11s
network 9, training 5, epoch 60: train scaled MSE 0.231885; val RMSE 0.05777569; lr 0.0005; 13s
network 9, training 5, epoch 70: train scaled MSE 0.216854; val RMSE 0.05756656; lr 0.00025; 15s
network 9, training 5, epoch 80: train scaled MSE 0.208351; val RMSE 0.05762772; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.06912984

Network seed 9, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0781,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0692,21.5352,"[20.36%, 22.62%]",0.4646,0.0,0.1491
MLP,0.0572,46.4192,"[45.04%, 47.85%]",0.6821,46.805,0.1559

network 9, training 6, epoch 1: train scaled MSE 0.891322; val RMSE 0.1086391; lr 0.001; 0s
network 9, training 6, epoch 10: train scaled MSE 0.397569; val RMSE 0.06777514; lr 0.001; 2s
network 9, training 6, epoch 20: train scaled MSE 0.347062; val RMSE 0.0619092; lr 0.001; 4s
network 9, training 6, epoch 30: train scaled MSE 0.30706; val RMSE 0.05964345; lr 0.001; 7s
network 9, training 6, epoch 40: train scaled MSE 0.277126; val RMSE 0.06116231; lr 0.001; 9s
network 9, training 6, epoch 50: train scaled MSE 0.221236; val RMSE 0.05961942; lr 0.001; 11s
network 9, training 6, epoch 60: train scaled MSE 0.211355; val RMSE 0.05971969; lr 0.0005; 13s
network 9, training 6, epoch 70: train scaled MSE 0.17646; val RMSE 0.05929681; lr 0.00025; 15s
network 9, training 6, epoch 80: train scaled MSE 0.169897; val RMSE 0.05942817; lr 0.000125; 17s
network 9, training 6, epoch 90: train scaled MSE 0.164491; val RMSE 0.05941007; lr 6.25e-05; 19s
Standard Linear Baseline Validation RMSE: 0.07053103

Network seed 9, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0781,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0691,21.8526,"[20.67%, 22.98%]",0.4680,0.0,0.1488
MLP,0.0579,45.0302,"[43.48%, 46.61%]",0.6733,43.859,0.1531

network 9, training 7, epoch 1: train scaled MSE 0.899187; val RMSE 0.1076597; lr 0.001; 0s
network 9, training 7, epoch 10: train scaled MSE 0.397662; val RMSE 0.06003836; lr 0.001; 2s
network 9, training 7, epoch 20: train scaled MSE 0.341974; val RMSE 0.05517015; lr 0.001; 4s
network 9, training 7, epoch 30: train scaled MSE 0.303756; val RMSE 0.05377441; lr 0.001; 6s
network 9, training 7, epoch 40: train scaled MSE 0.258969; val RMSE 0.05447824; lr 0.001; 9s
network 9, training 7, epoch 50: train scaled MSE 0.219196; val RMSE 0.0536088; lr 0.0005; 11s
network 9, training 7, epoch 60: train scaled MSE 0.198672; val RMSE 0.05368147; lr 0.00025; 13s
network 9, training 7, epoch 70: train scaled MSE 0.187218; val RMSE 0.05387193; lr 0.000125; 15s
Standard Linear Baseline Validation RMSE: 0.06498225

Network seed 9, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0785,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0690,22.6487,"[21.50%, 23.76%]",0.4763,0.0,0.1511
MLP,0.0570,47.1709,"[45.78%, 48.50%]",0.6875,44.3609,0.1498

network 9, training 8, epoch 1: train scaled MSE 0.890194; val RMSE 0.1073024; lr 0.001; 0s
network 9, training 8, epoch 10: train scaled MSE 0.387652; val RMSE 0.06357174; lr 0.001; 2s
network 9, training 8, epoch 20: train scaled MSE 0.339294; val RMSE 0.05892639; lr 0.001; 4s
network 9, training 8, epoch 30: train scaled MSE 0.299275; val RMSE 0.05749395; lr 0.001; 7s
network 9, training 8, epoch 40: train scaled MSE 0.260471; val RMSE 0.05638669; lr 0.001; 9s
network 9, training 8, epoch 50: train scaled MSE 0.218671; val RMSE 0.0567108; lr 0.001; 11s
network 9, training 8, epoch 60: train scaled MSE 0.184115; val RMSE 0.05662076; lr 0.0005; 13s
network 9, training 8, epoch 70: train scaled MSE 0.16485; val RMSE 0.05678844; lr 0.00025; 16s
network 9, training 8, epoch 80: train scaled MSE 0.161015; val RMSE 0.05734676; lr 0.00025; 18s
Standard Linear Baseline Validation RMSE: 0.06893168

Network seed 9, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0781,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0690,22.0510,"[20.83%, 23.23%]",0.4699,0.0,0.1496
MLP,0.0576,45.7395,"[44.28%, 47.16%]",0.6784,44.3895,0.1552

network 9, training 9, epoch 1: train scaled MSE 0.89434; val RMSE 0.1065846; lr 0.001; 0s
network 9, training 9, epoch 10: train scaled MSE 0.395855; val RMSE 0.06225665; lr 0.001; 2s
network 9, training 9, epoch 20: train scaled MSE 0.34325; val RMSE 0.05710493; lr 0.001; 4s
network 9, training 9, epoch 30: train scaled MSE 0.29681; val RMSE 0.05631768; lr 0.001; 7s
network 9, training 9, epoch 40: train scaled MSE 0.245424; val RMSE 0.05601776; lr 0.001; 9s
network 9, training 9, epoch 50: train scaled MSE 0.194675; val RMSE 0.05716714; lr 0.001; 11s
network 9, training 9, epoch 60: train scaled MSE 0.167186; val RMSE 0.05647214; lr 0.0005; 13s
network 9, training 9, epoch 70: train scaled MSE 0.152903; val RMSE 0.0566687; lr 0.00025; 15s
network 9, training 9, epoch 80: train scaled MSE 0.144435; val RMSE 0.05681306; lr 0.000125; 17s
Standard Linear Baseline Validation RMSE: 0.06720096

Network seed 9, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0782,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0692,21.7867,"[20.51%, 22.95%]",0.4683,0.0,0.1507
MLP,0.0577,45.5312,"[44.04%, 47.08%]",0.6803,45.2637,0.1530

,Network Seed,Training Seed,Model,MSE,RMSE,MSE Improvement vs Additive (%),Pearson (Implied vs True Residual),Fraction Pairs < Additive MSE,MSE Improv. 95% CI,Pearson Improv. vs Linear (%)
0,0,0,Additive Baseline,0.036751,0.191705,0.000000e+00,0.000000,0.000000,-,NaN
1,0,0,Linear Regression,0.015784,0.125636,5.705039e+01,0.755163,0.839216,"[56.42%, 57.62%]",0.000000
2,0,0,MLP,0.013327,0.115441,6.373804e+01,0.798497,0.893689,"[63.12%, 64.32%]",5.738364
3,0,1,Additive Baseline,0.036887,0.192061,-2.220446e-14,0.000000,0.000000,-,NaN
4,0,1,Linear Regression,0.015889,0.126053,5.692465e+01,0.754277,0.841176,"[56.35%, 57.51%]",0.000000
...,...,...,...,...,...,...,...,...,...,...
295,9,8,Linear Regression,0.004759,0.068983,2.205101e+01,0.469852,0.149632,"[20.83%, 23.23%]",0.000000
296,9,8,MLP,0.003312,0.057554,4.573945e+01,0.678416,0.155208,"[44.28%, 47.16%]",44.389512
297,9,9,Additive Baseline,0.006120,0.078231,0.000000e+00,0.000000,0.000000,-,NaN
298,9,9,Linear Regression,0.004787,0.069186,2.178672e+01,0.468300,0.150674,"[20.51%, 22.95%]",0.000000
299,9,9,MLP,0.003334,0.057737,4.553123e+01,0.680270,0.153002,"[44.04%, 47.08%]",45.263728

,Network Seed,Training Seed,Additive Baseline,Linear Regression,MLP
0,0,0,0.191705,0.125636,0.115441
1,0,1,0.192061,0.126053,0.115824
2,0,2,0.191055,0.125186,0.114999
3,0,3,0.191998,0.125410,0.115741
4,0,4,0.192487,0.126309,0.116125
...,...,...,...,...,...
95,9,5,0.078094,0.069176,0.057164
96,9,6,0.078148,0.069083,0.057940
97,9,7,0.078477,0.069020,0.057040
98,9,8,0.078133,0.068983,0.057554
99,9,9,0.078231,0.069186,0.057737

In [4]:
mlp_ci_table = (
    all_results_df
    .query("Model == 'MLP'")
    .pivot(
        index="Training Seed",
        columns="Network Seed",
        values="MSE Improv. 95% CI"
    )
)

display(mlp_ci_table)

Network Seed,0,1,2,3,4,5,6,7,8,9
Training Seed,,,,,,,,,,
0,"[63.12%, 64.32%]","[47.07%, 49.33%]","[35.38%, 38.68%]","[49.54%, 51.80%]","[66.23%, 67.69%]","[50.98%, 53.95%]","[55.93%, 57.70%]","[45.98%, 48.39%]","[51.80%, 54.29%]","[44.56%, 47.55%]"
1,"[63.03%, 64.23%]","[45.42%, 48.07%]","[33.75%, 37.46%]","[50.34%, 52.68%]","[67.50%, 68.87%]","[51.98%, 54.92%]","[55.25%, 57.14%]","[46.68%, 48.99%]","[50.71%, 53.28%]","[45.24%, 48.19%]"
2,"[63.14%, 64.37%]","[46.31%, 48.61%]","[35.98%, 39.10%]","[50.85%, 53.01%]","[66.64%, 68.07%]","[50.15%, 53.08%]","[55.94%, 57.79%]","[46.02%, 48.38%]","[50.57%, 53.06%]","[45.31%, 48.34%]"
3,"[63.02%, 64.28%]","[47.54%, 49.96%]","[36.91%, 40.10%]","[51.01%, 53.27%]","[66.29%, 67.76%]","[49.29%, 52.24%]","[56.95%, 58.73%]","[45.46%, 47.82%]","[51.55%, 54.04%]","[43.49%, 46.54%]"
4,"[63.00%, 64.23%]","[47.07%, 49.41%]","[34.63%, 37.85%]","[51.24%, 53.39%]","[66.97%, 68.35%]","[50.94%, 53.90%]","[55.48%, 57.20%]","[45.62%, 48.06%]","[50.95%, 53.47%]","[43.86%, 46.99%]"
5,"[63.40%, 64.66%]","[46.26%, 48.51%]","[36.53%, 39.73%]","[50.20%, 52.52%]","[65.78%, 67.19%]","[50.77%, 53.59%]","[55.89%, 57.71%]","[46.86%, 49.19%]","[51.11%, 53.66%]","[45.04%, 47.85%]"
6,"[62.75%, 63.94%]","[46.39%, 48.62%]","[35.26%, 38.50%]","[50.18%, 52.37%]","[66.96%, 68.30%]","[50.46%, 53.36%]","[55.64%, 57.55%]","[45.83%, 48.25%]","[50.47%, 52.95%]","[43.48%, 46.61%]"
7,"[62.89%, 64.14%]","[46.66%, 48.96%]","[35.64%, 38.65%]","[50.41%, 52.66%]","[67.67%, 69.02%]","[50.64%, 53.61%]","[56.00%, 57.80%]","[45.18%, 47.61%]","[52.43%, 54.88%]","[45.78%, 48.50%]"
8,"[63.13%, 64.48%]","[46.51%, 48.89%]","[35.65%, 38.76%]","[50.17%, 52.32%]","[66.92%, 68.31%]","[50.78%, 53.63%]","[55.64%, 57.34%]","[46.05%, 48.38%]","[50.34%, 52.94%]","[44.28%, 47.16%]"
9,"[62.80%, 64.06%]","[46.19%, 48.49%]","[34.35%, 37.56%]","[50.72%, 52.92%]","[66.64%, 67.99%]","[50.85%, 53.85%]","[55.97%, 57.83%]","[45.38%, 47.85%]","[50.33%, 52.94%]","[44.04%, 47.08%]"

In [5]:
mlp_ci_table = (
    all_results_df
    .query("Model == 'MLP'")
    .pivot(
        index="Training Seed",
        columns="Network Seed",
        values="MSE Improvement vs Additive (%)"
    )
)

display(mlp_ci_table)

Network Seed,0,1,2,3,4,5,6,7,8,9
Training Seed,,,,,,,,,,
0,63.738039,48.195486,37.082449,50.671678,66.968011,52.505548,56.819271,47.177657,53.097677,46.098384
1,63.631960,46.712883,35.588884,51.548126,68.220579,53.472290,56.167880,47.798686,52.098199,46.779816
2,63.769560,47.502772,37.534678,51.951997,67.389886,51.676579,56.873694,47.202643,51.816142,46.856235
3,63.660335,48.809291,38.483727,52.152739,67.032673,50.763833,57.841400,46.635037,52.811882,45.017426
4,63.604561,48.254931,36.274671,52.308364,67.675746,52.414467,56.362183,46.867639,52.212202,45.457825
5,64.053065,47.399246,38.127699,51.401235,66.519778,52.177714,56.758096,48.040317,52.427761,46.419189
6,63.332327,47.514500,36.964514,51.327862,67.622612,51.942774,56.598601,47.072933,51.727057,45.030242
7,63.514853,47.856760,37.187371,51.536179,68.347829,52.173576,56.888611,46.440247,53.661398,47.170889
8,63.798886,47.738070,37.284791,51.257240,67.619033,52.231691,56.518703,47.215903,51.620881,45.739450
9,63.442520,47.338105,35.951293,51.858978,67.323768,52.362704,56.913959,46.588613,51.679804,45.531228