In [1]:
from joblib import Parallel, delayed
from tqdm.notebook import tqdm

import sys
import pickle
import numpy as np
import pandas as pd
import networkx as nx
import scipy
from itertools import combinations

In [2]:
sys.path.insert(0, "src")

from grn import grn

np.random.seed(5)

In [3]:
all_results = []

for network_seed in range(10):
    np.random.seed(network_seed)

    #manually adjust GRN hyperparameters in an attempt to build GRN with more non-additive effects
    G = grn().add_structure(
        n=256,
        k=1,
        alpha=1e-99,
        beta=0.75,       # 1 - 1/r
        gamma=0.25,      # 1/r
        kappa=10,        # --w
        delta_in=100,
        delta_out=1,
    )

    G.simulate_rna(
        s=1e-4,
        dt=1e-2,
        tmax=20000,
        burnin=5000,
        tol=1e-3,
        save=True,
    )

    x_wt = np.zeros(256)
    y_wt = G.rna

    single_ko_expression = np.zeros((G.n, G.n))
    single_ko_logfc = np.zeros((G.n, G.n))
    single_ko_convergence = {}

    for gene in tqdm(range(G.n), desc=f"Network {network_seed}: single-gene KOs"):

        result = G.ko_nodes(
            genes=[gene],
            stats=("new_rna", "logfc", "convergence"),
            s=1e-4,
            dt=1e-2,
            tmax=20000,
            burnin=5000,
            tol=1e-3,
        )

        single_ko_expression[gene, :] = result["new_rna"].flatten()
        single_ko_logfc[gene, :] = result["logfc"].flatten()
        single_ko_convergence[gene] = result["convergence"]

    x_single_ko = np.eye(G.n)
    y_single_ko = single_ko_expression

    pairs = list(combinations(range(G.n), 2))

    def run_double_ko(pair):
        a, b = pair

        result = G.ko_nodes(
            genes=[a, b],
            stats=("new_rna", "logfc", "convergence"),
            s=0,
            dt=1e-2,
            tmax=20000,
            burnin=5000,
            tol=1e-3,
        )

        return (
            np.asarray(result["new_rna"]).flatten(),
            np.asarray(result["logfc"]).flatten(),
            np.asarray(result["convergence"]),
        )


    results = Parallel(
        n_jobs=64,
        pre_dispatch="n_jobs",
        prefer="processes",
        verbose=10,
    )(
        delayed(run_double_ko)(pair)
        for pair in pairs
    )

    double_expression = np.asarray(
        [r[0] for r in results],
        dtype=np.float32
    )

    double_logfc = np.asarray(
        [r[1] for r in results],
        dtype=np.float32
    )

    double_convergence = np.asarray(
        [r[2] for r in results],
        dtype=np.float32
    )


    #now prepare as training data

    pairs = np.array(
        pairs,
        dtype=np.int32
    )

    x_double_ko = np.zeros((pairs.shape[0], G.n))

    #now fill x for doubleKO with 1s

    rows = np.arange(pairs.shape[0])
    x_double_ko[rows, pairs[:, 0]] = 1.0
    x_double_ko[rows, pairs[:, 1]] = 1.0

    y_double_ko = double_expression


    # ============================================================
    # 10 TRAINING RUNS ON THIS GRN
    # ============================================================

    for training_seed in range(10):

        import torch
        from torch import nn

        torch.manual_seed(training_seed)
        device = torch.device("cpu")

        #for more precision
        #torch.backends.cuda.matmul.allow_tf32 = False
        #torch.backends.cudnn.allow_tf32 = False


        #model implementation without dropout
        model = nn.Sequential(
            nn.Linear(256, 512),
            nn.GELU(),
            nn.Linear(512, 512),
            nn.GELU(),
            nn.Linear(512, 256)
        ).to(device)

        linear = nn.Linear(256, 256).to(device)

        #implement AdamW
        import torch.optim as optim

        optimizer = optim.AdamW(
            model.parameters(),
            lr=1e-3,
            weight_decay=1e-2
        )


        #process data, standardise, put them on GPU

        rng = np.random.default_rng(training_seed)

        n_pairs = pairs.shape[0]
        nt, nv = int(0.5 * n_pairs), int(0.1 * n_pairs)

        indices = rng.permutation(n_pairs)
        test_idx = indices[:nt]
        val_idx = indices[nt:nt + nv]
        train_idx = indices[nt + nv:]

        xtr = np.concatenate(
            [x_wt[None, :], x_single_ko, x_double_ko[train_idx]],
            axis=0
        )

        ytr = np.concatenate(
            [y_wt[None, :], y_single_ko, y_double_ko[train_idx]],
            axis=0
        )

        xv = x_double_ko[val_idx]
        yv = y_double_ko[val_idx]

        x_test = x_double_ko[test_idx]
        y_test = y_double_ko[test_idx]

        mean, scale = (
            np.mean(ytr, axis=0),
            np.maximum(ytr.std(axis=0), 1e-6)
        )

        s_ytr = (ytr - mean) / scale

        xtr_t = torch.as_tensor(
            xtr,
            dtype=torch.float32,
            device=device
        )

        s_ytr_t = torch.as_tensor(
            s_ytr,
            dtype=torch.float32,
            device=device
        )

        xv_t = torch.as_tensor(
            xv,
            dtype=torch.float32,
            device=device
        )

        yv_t = torch.as_tensor(
            yv,
            dtype=torch.float32,
            device=device
        )

        x_test_t = torch.as_tensor(
            x_test,
            dtype=torch.float32,
            device=device
        )

        y_test_t = torch.as_tensor(
            y_test,
            dtype=torch.float32,
            device=device
        )

        mean_t = torch.as_tensor(
            mean,
            dtype=torch.float32,
            device=device
        )

        scale_t = torch.as_tensor(
            scale,
            dtype=torch.float32,
            device=device
        )


        import time
        import copy

        max_epochs = 3000
        batch_size = 256
        lr = 1e-3
        patience = 40
        min_lr = 1e-5
        lr_patience = 12

        best, best_epoch, stale, lr_stale = np.inf, 0, 0, 0
        history = []
        started = time.perf_counter()
        best_model_weights = None


        for epoch in range(1, max_epochs + 1):

            model.train()

            permutation = torch.randperm(
                xtr_t.shape[0],
                device=device
            )

            total = torch.zeros((), device=device)

            for start in range(
                0,
                xtr_t.shape[0],
                batch_size
            ):

                ii = permutation[start:(start + batch_size)]

                optimizer.zero_grad(set_to_none=True)

                loss = torch.mean(
                    (model(xtr_t[ii]) - s_ytr_t[ii]) ** 2
                )

                loss.backward()
                optimizer.step()

                total += loss.detach() * len(ii)

            train_loss = float(
                total.item() / xtr_t.shape[0]
            )

            model.eval()

            with torch.inference_mode():
                val_scaled = torch.cat(
                    [
                        model(chunk)
                        for chunk in xv_t.split(1024)
                    ]
                ).cpu().numpy()

            val_pred = (
                val_scaled.astype(np.float32)
                * scale
                + mean
            )

            raw_mse = float(
                np.mean((val_pred - yv) ** 2)
            )

            if (
                not np.isfinite(train_loss)
                or not np.isfinite(raw_mse)
            ):
                raise FloatingPointError(
                    f"Non-finite loss at epoch {epoch}"
                )

            history.append({
                "epoch": epoch,
                "train_scaled_mse": train_loss,
                "val_scaled_mse": float(
                    np.mean(
                        ((val_pred - yv) / scale) ** 2
                    )
                ),
                "val_raw_mse": raw_mse,
                "learning_rate": lr,
                "elapsed_seconds":
                    time.perf_counter() - started
            })

            if raw_mse < best:

                best = raw_mse
                best_epoch = epoch
                stale = 0
                lr_stale = 0

                best_model_weights = copy.deepcopy(
                    model.state_dict()
                )

            else:

                stale += 1
                lr_stale += 1

            if epoch == 1 or epoch % 10 == 0:

                print(
                    f"network {network_seed}, "
                    f"training {training_seed}, "
                    f"epoch {epoch}: "
                    f"train scaled MSE {train_loss:.6g}; "
                    f"val RMSE {raw_mse**.5:.7g}; "
                    f"lr {lr:g}; "
                    f"{time.perf_counter()-started:.0f}s",
                    flush=True
                )

            if (
                lr_stale >= lr_patience
                and lr > min_lr
            ):

                lr = max(
                    min_lr,
                    lr * .5
                )

                for group in optimizer.param_groups:
                    group["lr"] = lr

                lr_stale = 0

            if stale >= patience:
                break


        if best_model_weights is not None:
            model.load_state_dict(
                best_model_weights
            )


        from sklearn.linear_model import LinearRegression

        # 1. Initialize standard Linear Regression (no alpha/penalty)
        linear_model = LinearRegression(
            fit_intercept=True
        )

        # 2. Fit directly on the NumPy arrays
        linear_model.fit(
            xtr.astype(np.float64),
            s_ytr.astype(np.float64)
        )

        # 3. Predict and reverse normalization
        val_scaled = linear_model.predict(
            xv.astype(np.float64)
        )

        val_pred = (
            val_scaled.astype(np.float32)
            * scale
            + mean
        )

        # 4. Calculate RMSE
        raw_mse = float(
            np.mean(
                (val_pred - yv) ** 2
            )
        )

        print(
            f"Standard Linear Baseline Validation RMSE: "
            f"{raw_mse**.5:.7g}"
        )


        # 1. Generate predictions for the Test set
        model.eval()

        with torch.inference_mode():

            mlp_test_scaled = torch.cat(
                [
                    model(chunk)
                    for chunk
                    in x_test_t.split(1024)
                ]
            ).cpu().numpy()

        mlp_pred = (
            mlp_test_scaled.astype(np.float32)
            * scale
            + mean
        )


        # Retrieve linear model predictions
        linear_test_scaled = linear_model.predict(
            x_test.astype(np.float64)
        )

        linear_pred = (
            linear_test_scaled.astype(np.float32)
            * scale
            + mean
        )


        # 2. Reconstruct test pairs and baseline predictions
        test_pairs = pairs[test_idx]

        # The additive baseline is Single A + Single B - WT
        additive = (
            y_single_ko[test_pairs[:, 0]]
            + y_single_ko[test_pairs[:, 1]]
            - y_wt
        )

        y_true = y_test

        true_r = y_true - additive

        add_pair_mse = np.mean(
            true_r ** 2,
            axis=1
        )

        add_mse = float(
            np.mean(add_pair_mse)
        )


        # Helper function for Pearson correlation
        def correlation(a, b):

            a = np.asarray(a).ravel()
            b = np.asarray(b).ravel()

            if (
                np.std(a) < 1e-15
                or np.std(b) < 1e-15
            ):
                return None

            return float(
                np.corrcoef(a, b)[0, 1]
            )


        predictions = {
            "Additive Baseline": additive,
            "Linear Regression": linear_pred,
            "MLP": mlp_pred
        }

        metrics = []
        pair_losses = {}


        # 3. Calculate core metrics
        for name, pred in predictions.items():

            e2 = (pred - y_true) ** 2

            pair_losses[name] = e2.mean(axis=1)

            implied_residual = pred - additive

            mse = float(
                np.mean(e2)
            )

            pearson_corr = correlation(
                implied_residual,
                true_r
            )

            metrics.append({
                "Model": name,
                "MSE": mse,
                "RMSE": mse ** 0.5,
                "MSE Improvement vs Additive (%)":
                    100 * (1 - mse / add_mse),
                "Pearson (Implied vs True Residual)":
                    pearson_corr if pearson_corr else 0.0,
                "Fraction Pairs < Additive MSE":
                    float(
                        np.mean(
                            pair_losses[name]
                            < add_pair_mse
                        )
                    )
            })


        df = pd.DataFrame(
            metrics
        ).set_index("Model")


        # 4. Bootstrap 95% Confidence Intervals
        # for MSE Improvement (2000 resamples)

        rng = np.random.default_rng(9001)

        boot = {
            "Linear Regression": [],
            "MLP": []
        }

        for _ in range(2000):

            ii = rng.integers(
                0,
                len(test_pairs),
                size=len(test_pairs)
            )

            denom = add_pair_mse[ii].mean()

            for name in boot:

                boot[name].append(
                    100 * (
                        1
                        - pair_losses[name][ii].mean()
                        / denom
                    )
                )


        # Calculate and format CIs
        for name in boot:

            ci_lower, ci_upper = np.quantile(
                boot[name],
                [0.025, 0.975]
            )

            df.loc[
                name,
                "MSE Improv. 95% CI"
            ] = (
                f"[{ci_lower:.2f}%, "
                f"{ci_upper:.2f}%]"
            )


        df.loc[
            "Additive Baseline",
            "MSE Improv. 95% CI"
        ] = "-"


        # 5. Calculate Pearson Correlation
        # Improvement (MLP vs Linear)

        mlp_pearson = df.loc[
            "MLP",
            "Pearson (Implied vs True Residual)"
        ]

        lin_pearson = df.loc[
            "Linear Regression",
            "Pearson (Implied vs True Residual)"
        ]


        if lin_pearson != 0:

            pearson_improvement = (
                (mlp_pearson - lin_pearson)
                / abs(lin_pearson)
            ) * 100

            df.loc[
                "MLP",
                "Pearson Improv. vs Linear (%)"
            ] = pearson_improvement


        df.loc[
            "Linear Regression",
            "Pearson Improv. vs Linear (%)"
        ] = 0.0


        # Use np.nan instead of a string
        # to keep the column numerically typed
        df.loc[
            "Additive Baseline",
            "Pearson Improv. vs Linear (%)"
        ] = np.nan


        # ========================================================
        # SAVE RESULTS FROM THIS NETWORK/TRAINING RUN
        # ========================================================

        run_df = df.reset_index()

        run_df.insert(
            0,
            "Training Seed",
            training_seed
        )

        run_df.insert(
            0,
            "Network Seed",
            network_seed
        )

        all_results.append(run_df)


        # Full results accumulated so far
        all_results_df = pd.concat(
            all_results,
            ignore_index=True
        )

        # Save after every training run so that completed
        # runs are not lost if a later run fails.
        all_results_df.to_csv(
            "../grn_training_results.csv",
            index=False
        )


        # Compact one-row-per-run RMSE table
        # MLP vs regression vs additive
        rmse_by_run = all_results_df.pivot(
            index=[
                "Network Seed",
                "Training Seed"
            ],
            columns="Model",
            values="RMSE"
        ).reset_index()

        rmse_by_run.columns.name = None

        rmse_by_run.to_csv(
            "../grn_training_rmse_by_run.csv",
            index=False
        )


        # Format the DataFrame for clean output
        display_cols = [
            "RMSE",
            "MSE Improvement vs Additive (%)",
            "MSE Improv. 95% CI",
            "Pearson (Implied vs True Residual)",
            "Pearson Improv. vs Linear (%)",
            "Fraction Pairs < Additive MSE"
        ]


        print(
            f"\nNetwork seed {network_seed}, "
            f"training seed {training_seed}"
        )

        display(
            df[
                display_cols
            ].round(4).fillna("-")
        )


# ================================================================
# FINAL RESULT TABLES
# ================================================================

# 10 networks x 10 training runs x 3 models = 300 rows
all_results_df = pd.concat(
    all_results,
    ignore_index=True
)

# 100 rows, one for each Network Seed / Training Seed combination
rmse_by_run = all_results_df.pivot(
    index=[
        "Network Seed",
        "Training Seed"
    ],
    columns="Model",
    values="RMSE"
).reset_index()

rmse_by_run.columns.name = None

display(all_results_df)
display(rmse_by_run)

Network 0: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   37.8s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   38.0s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   38.1s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   38.2s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   38.5s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   38.6s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   38.9s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   39.1s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   39.2s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   39.4s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   39.6s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   39.8s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   40.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   40.3s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   40.4s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   40.7s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   41.1s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   41.2s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   41.5s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   41.9s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   42.1s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   42.4s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   42.6s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   43.0s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   43.3s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   43.6s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   43.9s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   44.3s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   44.7s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   45.0s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   45.4s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   45.8s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   46.2s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   46.7s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   47.0s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   47.5s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   47.9s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   48.4s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   48.9s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   49.4s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   49.9s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   50.4s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   50.9s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   51.4s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   51.9s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   52.5s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   53.0s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   53.5s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   54.1s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   54.6s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   55.2s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   55.9s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   56.4s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   57.1s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   57.8s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   58.5s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   59.2s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   59.8s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  5.1min finished

network 0, training 0, epoch 1: train scaled MSE 0.82848; val RMSE 0.01920971; lr 0.001; 1s
network 0, training 0, epoch 10: train scaled MSE 0.0427469; val RMSE 0.003601856; lr 0.001; 3s
network 0, training 0, epoch 20: train scaled MSE 0.0261598; val RMSE 0.002339018; lr 0.001; 5s
network 0, training 0, epoch 30: train scaled MSE 0.0290917; val RMSE 0.002720074; lr 0.001; 7s
network 0, training 0, epoch 40: train scaled MSE 0.00812519; val RMSE 0.002214951; lr 0.001; 9s
network 0, training 0, epoch 50: train scaled MSE 0.00508276; val RMSE 0.002078251; lr 0.001; 11s
network 0, training 0, epoch 60: train scaled MSE 0.00828798; val RMSE 0.002134715; lr 0.001; 13s
network 0, training 0, epoch 70: train scaled MSE 0.00350614; val RMSE 0.001922647; lr 0.001; 15s
network 0, training 0, epoch 80: train scaled MSE 0.00307815; val RMSE 0.001939174; lr 0.001; 17s
network 0, training 0, epoch 90: train scaled MSE 0.00194486; val RMSE 0.001834042; lr 0.0005; 19s
network 0, training 0, epoch 100: train scaled MSE 0.00178477; val RMSE 0.001797164; lr 0.0005; 21s
network 0, training 0, epoch 110: train scaled MSE 0.00558486; val RMSE 0.001937571; lr 0.0005; 23s
network 0, training 0, epoch 120: train scaled MSE 0.00139049; val RMSE 0.001780232; lr 0.00025; 25s
network 0, training 0, epoch 130: train scaled MSE 0.00134532; val RMSE 0.00178007; lr 0.00025; 27s
network 0, training 0, epoch 140: train scaled MSE 0.001219; val RMSE 0.001769859; lr 0.00025; 29s
network 0, training 0, epoch 150: train scaled MSE 0.00116837; val RMSE 0.001760735; lr 0.00025; 31s
network 0, training 0, epoch 160: train scaled MSE 0.0012418; val RMSE 0.001765129; lr 0.00025; 33s
network 0, training 0, epoch 170: train scaled MSE 0.000984821; val RMSE 0.001744677; lr 0.000125; 35s
network 0, training 0, epoch 180: train scaled MSE 0.000947853; val RMSE 0.001738755; lr 0.000125; 37s
network 0, training 0, epoch 190: train scaled MSE 0.000941452; val RMSE 0.001737888; lr 0.000125; 39s
network 0, training 0, epoch 200: train scaled MSE 0.000873731; val RMSE 0.001729956; lr 6.25e-05; 41s
network 0, training 0, epoch 210: train scaled MSE 0.000928485; val RMSE 0.001734508; lr 6.25e-05; 43s
network 0, training 0, epoch 220: train scaled MSE 0.00114411; val RMSE 0.001732662; lr 6.25e-05; 45s
network 0, training 0, epoch 230: train scaled MSE 0.000829547; val RMSE 0.001725011; lr 6.25e-05; 47s
network 0, training 0, epoch 240: train scaled MSE 0.00081602; val RMSE 0.001725097; lr 6.25e-05; 49s
network 0, training 0, epoch 250: train scaled MSE 0.000932041; val RMSE 0.001739461; lr 6.25e-05; 51s
network 0, training 0, epoch 260: train scaled MSE 0.000776076; val RMSE 0.001720086; lr 3.125e-05; 53s
network 0, training 0, epoch 270: train scaled MSE 0.000789791; val RMSE 0.001720966; lr 3.125e-05; 55s
network 0, training 0, epoch 280: train scaled MSE 0.000759865; val RMSE 0.001717941; lr 3.125e-05; 57s
network 0, training 0, epoch 290: train scaled MSE 0.000755322; val RMSE 0.001726337; lr 3.125e-05; 59s
network 0, training 0, epoch 300: train scaled MSE 0.000747733; val RMSE 0.001716792; lr 1.5625e-05; 61s
network 0, training 0, epoch 310: train scaled MSE 0.000738626; val RMSE 0.001715802; lr 1.5625e-05; 63s
network 0, training 0, epoch 320: train scaled MSE 0.000842931; val RMSE 0.001720724; lr 1.5625e-05; 65s
network 0, training 0, epoch 330: train scaled MSE 0.000729216; val RMSE 0.001714635; lr 1.5625e-05; 68s
network 0, training 0, epoch 340: train scaled MSE 0.000732342; val RMSE 0.001714036; lr 1.5625e-05; 70s
network 0, training 0, epoch 350: train scaled MSE 0.000760176; val RMSE 0.001716973; lr 1.5625e-05; 72s
network 0, training 0, epoch 360: train scaled MSE 0.000772199; val RMSE 0.001716416; lr 1e-05; 74s
network 0, training 0, epoch 370: train scaled MSE 0.000741621; val RMSE 0.001714379; lr 1e-05; 76s
network 0, training 0, epoch 380: train scaled MSE 0.000714448; val RMSE 0.001712691; lr 1e-05; 78s
network 0, training 0, epoch 390: train scaled MSE 0.000740561; val RMSE 0.00171404; lr 1e-05; 80s
network 0, training 0, epoch 400: train scaled MSE 0.000709238; val RMSE 0.001711992; lr 1e-05; 82s
network 0, training 0, epoch 410: train scaled MSE 0.000718308; val RMSE 0.00171205; lr 1e-05; 84s
network 0, training 0, epoch 420: train scaled MSE 0.000704465; val RMSE 0.001711569; lr 1e-05; 86s
network 0, training 0, epoch 430: train scaled MSE 0.000702032; val RMSE 0.001710872; lr 1e-05; 88s
network 0, training 0, epoch 440: train scaled MSE 0.000700008; val RMSE 0.00171078; lr 1e-05; 90s
network 0, training 0, epoch 450: train scaled MSE 0.000700428; val RMSE 0.001710263; lr 1e-05; 93s
network 0, training 0, epoch 460: train scaled MSE 0.000695387; val RMSE 0.001710403; lr 1e-05; 95s
network 0, training 0, epoch 470: train scaled MSE 0.000692714; val RMSE 0.001710856; lr 1e-05; 97s
network 0, training 0, epoch 480: train scaled MSE 0.000690666; val RMSE 0.001710894; lr 1e-05; 99s
network 0, training 0, epoch 490: train scaled MSE 0.000688198; val RMSE 0.001709784; lr 1e-05; 101s
network 0, training 0, epoch 500: train scaled MSE 0.000687309; val RMSE 0.001709302; lr 1e-05; 104s
network 0, training 0, epoch 510: train scaled MSE 0.000682695; val RMSE 0.001708934; lr 1e-05; 106s
network 0, training 0, epoch 520: train scaled MSE 0.000679546; val RMSE 0.001707667; lr 1e-05; 108s
network 0, training 0, epoch 530: train scaled MSE 0.000676862; val RMSE 0.00170844; lr 1e-05; 110s
network 0, training 0, epoch 540: train scaled MSE 0.000675032; val RMSE 0.0017086; lr 1e-05; 112s
network 0, training 0, epoch 550: train scaled MSE 0.000671712; val RMSE 0.001707681; lr 1e-05; 114s
network 0, training 0, epoch 560: train scaled MSE 0.000673084; val RMSE 0.001708775; lr 1e-05; 116s
network 0, training 0, epoch 570: train scaled MSE 0.000668179; val RMSE 0.001708207; lr 1e-05; 118s
network 0, training 0, epoch 580: train scaled MSE 0.000665388; val RMSE 0.001707132; lr 1e-05; 120s
network 0, training 0, epoch 590: train scaled MSE 0.000663391; val RMSE 0.001708309; lr 1e-05; 123s
network 0, training 0, epoch 600: train scaled MSE 0.00066071; val RMSE 0.001706728; lr 1e-05; 125s
network 0, training 0, epoch 610: train scaled MSE 0.000658292; val RMSE 0.001707075; lr 1e-05; 127s
network 0, training 0, epoch 620: train scaled MSE 0.000655997; val RMSE 0.001705863; lr 1e-05; 129s
network 0, training 0, epoch 630: train scaled MSE 0.00065393; val RMSE 0.001705781; lr 1e-05; 131s
network 0, training 0, epoch 640: train scaled MSE 0.000694617; val RMSE 0.001708178; lr 1e-05; 134s
network 0, training 0, epoch 650: train scaled MSE 0.000651785; val RMSE 0.00170526; lr 1e-05; 136s
network 0, training 0, epoch 660: train scaled MSE 0.000650271; val RMSE 0.001704863; lr 1e-05; 138s
network 0, training 0, epoch 670: train scaled MSE 0.00066572; val RMSE 0.001704336; lr 1e-05; 140s
network 0, training 0, epoch 680: train scaled MSE 0.000644532; val RMSE 0.001704191; lr 1e-05; 142s
network 0, training 0, epoch 690: train scaled MSE 0.000642729; val RMSE 0.001704507; lr 1e-05; 144s
network 0, training 0, epoch 700: train scaled MSE 0.000642352; val RMSE 0.001704074; lr 1e-05; 146s
network 0, training 0, epoch 710: train scaled MSE 0.000639166; val RMSE 0.001703362; lr 1e-05; 148s
network 0, training 0, epoch 720: train scaled MSE 0.000638495; val RMSE 0.001704773; lr 1e-05; 150s
network 0, training 0, epoch 730: train scaled MSE 0.000636383; val RMSE 0.001703564; lr 1e-05; 152s
network 0, training 0, epoch 740: train scaled MSE 0.000634214; val RMSE 0.001703087; lr 1e-05; 154s
network 0, training 0, epoch 750: train scaled MSE 0.000632439; val RMSE 0.001703532; lr 1e-05; 156s
network 0, training 0, epoch 760: train scaled MSE 0.000633057; val RMSE 0.001703037; lr 1e-05; 157s
network 0, training 0, epoch 770: train scaled MSE 0.000627844; val RMSE 0.00170216; lr 1e-05; 159s
network 0, training 0, epoch 780: train scaled MSE 0.000626665; val RMSE 0.001702473; lr 1e-05; 161s
network 0, training 0, epoch 790: train scaled MSE 0.000624318; val RMSE 0.001702549; lr 1e-05; 163s
network 0, training 0, epoch 800: train scaled MSE 0.000622559; val RMSE 0.001701076; lr 1e-05; 165s
network 0, training 0, epoch 810: train scaled MSE 0.000621188; val RMSE 0.001701897; lr 1e-05; 167s
network 0, training 0, epoch 820: train scaled MSE 0.000618415; val RMSE 0.001701025; lr 1e-05; 169s
network 0, training 0, epoch 830: train scaled MSE 0.000617642; val RMSE 0.001702428; lr 1e-05; 171s
network 0, training 0, epoch 840: train scaled MSE 0.000614958; val RMSE 0.001700453; lr 1e-05; 173s
network 0, training 0, epoch 850: train scaled MSE 0.000612453; val RMSE 0.001701032; lr 1e-05; 175s
network 0, training 0, epoch 860: train scaled MSE 0.000610271; val RMSE 0.001700446; lr 1e-05; 177s
network 0, training 0, epoch 870: train scaled MSE 0.000607879; val RMSE 0.001699793; lr 1e-05; 179s
network 0, training 0, epoch 880: train scaled MSE 0.000606855; val RMSE 0.001699656; lr 1e-05; 181s
network 0, training 0, epoch 890: train scaled MSE 0.000603433; val RMSE 0.001699364; lr 1e-05; 183s
network 0, training 0, epoch 900: train scaled MSE 0.000602479; val RMSE 0.001699494; lr 1e-05; 185s
network 0, training 0, epoch 910: train scaled MSE 0.000612759; val RMSE 0.001699868; lr 1e-05; 187s
network 0, training 0, epoch 920: train scaled MSE 0.000597745; val RMSE 0.001698564; lr 1e-05; 189s
network 0, training 0, epoch 930: train scaled MSE 0.000595017; val RMSE 0.0016997; lr 1e-05; 191s
network 0, training 0, epoch 940: train scaled MSE 0.000594266; val RMSE 0.001699038; lr 1e-05; 193s
network 0, training 0, epoch 950: train scaled MSE 0.000601987; val RMSE 0.001699627; lr 1e-05; 195s
network 0, training 0, epoch 960: train scaled MSE 0.000589214; val RMSE 0.001698024; lr 1e-05; 197s
network 0, training 0, epoch 970: train scaled MSE 0.000590608; val RMSE 0.001697767; lr 1e-05; 199s
network 0, training 0, epoch 980: train scaled MSE 0.000586535; val RMSE 0.0016974; lr 1e-05; 201s
network 0, training 0, epoch 990: train scaled MSE 0.000583817; val RMSE 0.001697055; lr 1e-05; 203s
network 0, training 0, epoch 1000: train scaled MSE 0.000582508; val RMSE 0.001697045; lr 1e-05; 205s
network 0, training 0, epoch 1010: train scaled MSE 0.000580993; val RMSE 0.001696976; lr 1e-05; 207s
network 0, training 0, epoch 1020: train scaled MSE 0.00057894; val RMSE 0.001696601; lr 1e-05; 209s
network 0, training 0, epoch 1030: train scaled MSE 0.000577239; val RMSE 0.001696392; lr 1e-05; 211s
network 0, training 0, epoch 1040: train scaled MSE 0.000575699; val RMSE 0.001696191; lr 1e-05; 213s
network 0, training 0, epoch 1050: train scaled MSE 0.000573107; val RMSE 0.00169674; lr 1e-05; 215s
network 0, training 0, epoch 1060: train scaled MSE 0.000571511; val RMSE 0.001695413; lr 1e-05; 217s
Standard Linear Baseline Validation RMSE: 0.001704017

Network seed 0, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0022,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0022,-2.7916,"[-9.41%, 0.60%]",0.0741,0.0,0.1165
MLP,0.0023,-8.2798,"[-24.85%, 3.28%]",0.1900,156.4282,0.0121

network 0, training 1, epoch 1: train scaled MSE 0.824262; val RMSE 0.01895431; lr 0.001; 0s
network 0, training 1, epoch 10: train scaled MSE 0.0222366; val RMSE 0.004400522; lr 0.001; 2s
network 0, training 1, epoch 20: train scaled MSE 0.00751253; val RMSE 0.003602203; lr 0.001; 4s
network 0, training 1, epoch 30: train scaled MSE 0.00539413; val RMSE 0.003129729; lr 0.001; 6s
network 0, training 1, epoch 40: train scaled MSE 0.00446851; val RMSE 0.003126967; lr 0.001; 9s
network 0, training 1, epoch 50: train scaled MSE 0.00505875; val RMSE 0.003062358; lr 0.001; 11s
network 0, training 1, epoch 60: train scaled MSE 0.00351823; val RMSE 0.002994588; lr 0.0005; 13s
network 0, training 1, epoch 70: train scaled MSE 0.00314423; val RMSE 0.002970315; lr 0.0005; 15s
network 0, training 1, epoch 80: train scaled MSE 0.00308342; val RMSE 0.003116925; lr 0.0005; 17s
network 0, training 1, epoch 90: train scaled MSE 0.00271094; val RMSE 0.002925393; lr 0.0005; 19s
network 0, training 1, epoch 100: train scaled MSE 0.00250013; val RMSE 0.002909162; lr 0.0005; 21s
network 0, training 1, epoch 110: train scaled MSE 0.00234165; val RMSE 0.002895168; lr 0.0005; 23s
network 0, training 1, epoch 120: train scaled MSE 0.0020086; val RMSE 0.00288925; lr 0.0005; 25s
network 0, training 1, epoch 130: train scaled MSE 0.00185594; val RMSE 0.002856774; lr 0.0005; 27s
network 0, training 1, epoch 140: train scaled MSE 0.00161549; val RMSE 0.002917896; lr 0.0005; 29s
network 0, training 1, epoch 150: train scaled MSE 0.00144119; val RMSE 0.002896845; lr 0.0005; 31s
network 0, training 1, epoch 160: train scaled MSE 0.00133271; val RMSE 0.002884856; lr 0.0005; 33s
network 0, training 1, epoch 170: train scaled MSE 0.00115276; val RMSE 0.002832875; lr 0.00025; 35s
network 0, training 1, epoch 180: train scaled MSE 0.00106061; val RMSE 0.002826525; lr 0.00025; 37s
network 0, training 1, epoch 190: train scaled MSE 0.0010029; val RMSE 0.00300498; lr 0.00025; 39s
network 0, training 1, epoch 200: train scaled MSE 0.000934116; val RMSE 0.002833615; lr 0.000125; 41s
network 0, training 1, epoch 210: train scaled MSE 0.000927388; val RMSE 0.002828142; lr 6.25e-05; 43s
network 0, training 1, epoch 220: train scaled MSE 0.000886293; val RMSE 0.00282669; lr 6.25e-05; 45s
network 0, training 1, epoch 230: train scaled MSE 0.000869279; val RMSE 0.002827472; lr 6.25e-05; 47s
network 0, training 1, epoch 240: train scaled MSE 0.000851314; val RMSE 0.002826859; lr 6.25e-05; 49s
network 0, training 1, epoch 250: train scaled MSE 0.00083325; val RMSE 0.002824975; lr 3.125e-05; 51s
network 0, training 1, epoch 260: train scaled MSE 0.000812203; val RMSE 0.002825099; lr 1.5625e-05; 53s
network 0, training 1, epoch 270: train scaled MSE 0.000808074; val RMSE 0.002824105; lr 1.5625e-05; 55s
network 0, training 1, epoch 280: train scaled MSE 0.000801251; val RMSE 0.002824014; lr 1e-05; 57s
network 0, training 1, epoch 290: train scaled MSE 0.000796741; val RMSE 0.002824425; lr 1e-05; 59s
network 0, training 1, epoch 300: train scaled MSE 0.000795485; val RMSE 0.002824123; lr 1e-05; 61s
network 0, training 1, epoch 310: train scaled MSE 0.000794162; val RMSE 0.002824661; lr 1e-05; 63s
network 0, training 1, epoch 320: train scaled MSE 0.000789831; val RMSE 0.002825083; lr 1e-05; 65s
network 0, training 1, epoch 330: train scaled MSE 0.000784769; val RMSE 0.002824017; lr 1e-05; 68s
network 0, training 1, epoch 340: train scaled MSE 0.000786139; val RMSE 0.002824168; lr 1e-05; 69s
network 0, training 1, epoch 350: train scaled MSE 0.000780463; val RMSE 0.002823614; lr 1e-05; 71s
network 0, training 1, epoch 360: train scaled MSE 0.000777996; val RMSE 0.002823421; lr 1e-05; 74s
network 0, training 1, epoch 370: train scaled MSE 0.000775383; val RMSE 0.002823108; lr 1e-05; 76s
network 0, training 1, epoch 380: train scaled MSE 0.000769779; val RMSE 0.002823077; lr 1e-05; 78s
network 0, training 1, epoch 390: train scaled MSE 0.000766544; val RMSE 0.002822861; lr 1e-05; 80s
network 0, training 1, epoch 400: train scaled MSE 0.000776827; val RMSE 0.002822686; lr 1e-05; 82s
network 0, training 1, epoch 410: train scaled MSE 0.000760269; val RMSE 0.002822765; lr 1e-05; 84s
network 0, training 1, epoch 420: train scaled MSE 0.000760002; val RMSE 0.002823648; lr 1e-05; 86s
network 0, training 1, epoch 430: train scaled MSE 0.000754877; val RMSE 0.002822936; lr 1e-05; 88s
Standard Linear Baseline Validation RMSE: 0.002808234

Network seed 0, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0031,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0031,0.4577,"[-0.60%, 0.74%]",0.0687,0.0,0.2556
MLP,0.0029,13.4672,"[-23.36%, 23.99%]",0.3717,441.355,0.0061

network 0, training 2, epoch 1: train scaled MSE 0.82573; val RMSE 0.01923994; lr 0.001; 0s
network 0, training 2, epoch 10: train scaled MSE 0.0314113; val RMSE 0.004228488; lr 0.001; 2s
network 0, training 2, epoch 20: train scaled MSE 0.0120447; val RMSE 0.00263862; lr 0.001; 4s
network 0, training 2, epoch 30: train scaled MSE 0.00879173; val RMSE 0.002579567; lr 0.001; 6s
network 0, training 2, epoch 40: train scaled MSE 0.00666489; val RMSE 0.002013543; lr 0.001; 8s
network 0, training 2, epoch 50: train scaled MSE 0.00542472; val RMSE 0.001936753; lr 0.001; 10s
network 0, training 2, epoch 60: train scaled MSE 0.00435384; val RMSE 0.001862249; lr 0.001; 12s
network 0, training 2, epoch 70: train scaled MSE 0.00320886; val RMSE 0.001777184; lr 0.001; 14s
network 0, training 2, epoch 80: train scaled MSE 0.00264958; val RMSE 0.001787514; lr 0.001; 16s
network 0, training 2, epoch 90: train scaled MSE 0.00173391; val RMSE 0.001660189; lr 0.0005; 18s
network 0, training 2, epoch 100: train scaled MSE 0.00171921; val RMSE 0.001673788; lr 0.0005; 20s
network 0, training 2, epoch 110: train scaled MSE 0.00177393; val RMSE 0.001656587; lr 0.0005; 22s
network 0, training 2, epoch 120: train scaled MSE 0.00118145; val RMSE 0.001625058; lr 0.00025; 24s
network 0, training 2, epoch 130: train scaled MSE 0.00113009; val RMSE 0.001628615; lr 0.00025; 26s
network 0, training 2, epoch 140: train scaled MSE 0.00104469; val RMSE 0.001614879; lr 0.000125; 28s
network 0, training 2, epoch 150: train scaled MSE 0.000992186; val RMSE 0.001612499; lr 0.000125; 30s
network 0, training 2, epoch 160: train scaled MSE 0.000975447; val RMSE 0.001606993; lr 0.000125; 32s
network 0, training 2, epoch 170: train scaled MSE 0.000920804; val RMSE 0.001607475; lr 0.000125; 34s
network 0, training 2, epoch 180: train scaled MSE 0.000885904; val RMSE 0.001600956; lr 0.000125; 36s
network 0, training 2, epoch 190: train scaled MSE 0.000852002; val RMSE 0.001596827; lr 0.000125; 38s
network 0, training 2, epoch 200: train scaled MSE 0.000825025; val RMSE 0.001594662; lr 0.000125; 41s
network 0, training 2, epoch 210: train scaled MSE 0.000789236; val RMSE 0.001590357; lr 0.000125; 43s
network 0, training 2, epoch 220: train scaled MSE 0.000781852; val RMSE 0.001588815; lr 0.000125; 45s
network 0, training 2, epoch 230: train scaled MSE 0.00072384; val RMSE 0.001598037; lr 0.000125; 47s
network 0, training 2, epoch 240: train scaled MSE 0.00069469; val RMSE 0.001582196; lr 0.000125; 49s
network 0, training 2, epoch 250: train scaled MSE 0.000768971; val RMSE 0.001584686; lr 0.000125; 51s
network 0, training 2, epoch 260: train scaled MSE 0.000651147; val RMSE 0.001574347; lr 0.000125; 53s
network 0, training 2, epoch 270: train scaled MSE 0.000609977; val RMSE 0.001568172; lr 6.25e-05; 55s
network 0, training 2, epoch 280: train scaled MSE 0.000598502; val RMSE 0.001594166; lr 6.25e-05; 57s
network 0, training 2, epoch 290: train scaled MSE 0.000588207; val RMSE 0.001568294; lr 6.25e-05; 59s
network 0, training 2, epoch 300: train scaled MSE 0.000577791; val RMSE 0.001566766; lr 3.125e-05; 61s
network 0, training 2, epoch 310: train scaled MSE 0.000572001; val RMSE 0.001562545; lr 3.125e-05; 62s
network 0, training 2, epoch 320: train scaled MSE 0.000563328; val RMSE 0.001561135; lr 3.125e-05; 64s
network 0, training 2, epoch 330: train scaled MSE 0.000565203; val RMSE 0.001561125; lr 3.125e-05; 66s
network 0, training 2, epoch 340: train scaled MSE 0.000559626; val RMSE 0.001560274; lr 1.5625e-05; 68s
network 0, training 2, epoch 350: train scaled MSE 0.000550287; val RMSE 0.001560117; lr 1.5625e-05; 70s
network 0, training 2, epoch 360: train scaled MSE 0.000582755; val RMSE 0.001562005; lr 1.5625e-05; 72s
network 0, training 2, epoch 370: train scaled MSE 0.000552876; val RMSE 0.001558988; lr 1e-05; 74s
network 0, training 2, epoch 380: train scaled MSE 0.00054215; val RMSE 0.001558065; lr 1e-05; 76s
network 0, training 2, epoch 390: train scaled MSE 0.00054095; val RMSE 0.001558158; lr 1e-05; 78s
network 0, training 2, epoch 400: train scaled MSE 0.000541786; val RMSE 0.001558183; lr 1e-05; 80s
network 0, training 2, epoch 410: train scaled MSE 0.000538162; val RMSE 0.001557581; lr 1e-05; 82s
network 0, training 2, epoch 420: train scaled MSE 0.000537619; val RMSE 0.001557426; lr 1e-05; 84s
network 0, training 2, epoch 430: train scaled MSE 0.000535092; val RMSE 0.001557308; lr 1e-05; 86s
network 0, training 2, epoch 440: train scaled MSE 0.00053406; val RMSE 0.001556777; lr 1e-05; 88s
network 0, training 2, epoch 450: train scaled MSE 0.000533569; val RMSE 0.001556576; lr 1e-05; 90s
network 0, training 2, epoch 460: train scaled MSE 0.000530373; val RMSE 0.001556217; lr 1e-05; 92s
network 0, training 2, epoch 470: train scaled MSE 0.000540703; val RMSE 0.001557252; lr 1e-05; 94s
network 0, training 2, epoch 480: train scaled MSE 0.000527068; val RMSE 0.001555668; lr 1e-05; 96s
network 0, training 2, epoch 490: train scaled MSE 0.000525477; val RMSE 0.001555607; lr 1e-05; 98s
network 0, training 2, epoch 500: train scaled MSE 0.000523313; val RMSE 0.001555659; lr 1e-05; 100s
network 0, training 2, epoch 510: train scaled MSE 0.000535172; val RMSE 0.00155722; lr 1e-05; 102s
network 0, training 2, epoch 520: train scaled MSE 0.000521169; val RMSE 0.001555031; lr 1e-05; 104s
network 0, training 2, epoch 530: train scaled MSE 0.000518947; val RMSE 0.001554383; lr 1e-05; 106s
network 0, training 2, epoch 540: train scaled MSE 0.000517055; val RMSE 0.001554582; lr 1e-05; 108s
network 0, training 2, epoch 550: train scaled MSE 0.00051492; val RMSE 0.001553868; lr 1e-05; 110s
network 0, training 2, epoch 560: train scaled MSE 0.000515688; val RMSE 0.001554557; lr 1e-05; 112s
network 0, training 2, epoch 570: train scaled MSE 0.000513915; val RMSE 0.001553864; lr 1e-05; 114s
network 0, training 2, epoch 580: train scaled MSE 0.000510108; val RMSE 0.001553201; lr 1e-05; 116s
network 0, training 2, epoch 590: train scaled MSE 0.000509743; val RMSE 0.001553374; lr 1e-05; 118s
network 0, training 2, epoch 600: train scaled MSE 0.00051178; val RMSE 0.001553389; lr 1e-05; 120s
network 0, training 2, epoch 610: train scaled MSE 0.000505789; val RMSE 0.001552976; lr 1e-05; 122s
network 0, training 2, epoch 620: train scaled MSE 0.000505928; val RMSE 0.001552395; lr 1e-05; 124s
network 0, training 2, epoch 630: train scaled MSE 0.00050285; val RMSE 0.001551947; lr 1e-05; 126s
network 0, training 2, epoch 640: train scaled MSE 0.000501813; val RMSE 0.001551628; lr 1e-05; 128s
network 0, training 2, epoch 650: train scaled MSE 0.000500036; val RMSE 0.001551702; lr 1e-05; 130s
network 0, training 2, epoch 660: train scaled MSE 0.000504656; val RMSE 0.001552765; lr 1e-05; 132s
network 0, training 2, epoch 670: train scaled MSE 0.000497376; val RMSE 0.001551158; lr 1e-05; 134s
network 0, training 2, epoch 680: train scaled MSE 0.000496161; val RMSE 0.001550974; lr 1e-05; 136s
network 0, training 2, epoch 690: train scaled MSE 0.000494892; val RMSE 0.001551467; lr 1e-05; 138s
network 0, training 2, epoch 700: train scaled MSE 0.00050745; val RMSE 0.001552487; lr 1e-05; 140s
network 0, training 2, epoch 710: train scaled MSE 0.000492286; val RMSE 0.001550595; lr 1e-05; 142s
network 0, training 2, epoch 720: train scaled MSE 0.000490572; val RMSE 0.001550526; lr 1e-05; 144s
network 0, training 2, epoch 730: train scaled MSE 0.000491741; val RMSE 0.001550039; lr 1e-05; 146s
network 0, training 2, epoch 740: train scaled MSE 0.000488003; val RMSE 0.001550199; lr 1e-05; 148s
network 0, training 2, epoch 750: train scaled MSE 0.00048673; val RMSE 0.00155028; lr 1e-05; 150s
network 0, training 2, epoch 760: train scaled MSE 0.000484816; val RMSE 0.001549788; lr 1e-05; 152s
network 0, training 2, epoch 770: train scaled MSE 0.000531459; val RMSE 0.001554062; lr 1e-05; 154s
network 0, training 2, epoch 780: train scaled MSE 0.000486062; val RMSE 0.001550556; lr 1e-05; 156s
network 0, training 2, epoch 790: train scaled MSE 0.000481733; val RMSE 0.00154995; lr 1e-05; 158s
network 0, training 2, epoch 800: train scaled MSE 0.000482533; val RMSE 0.001550371; lr 1e-05; 160s
Standard Linear Baseline Validation RMSE: 0.00154434

Network seed 0, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.003,0.0000,-,0.0000,-,0.0000
Linear Regression,0.003,0.4906,"[-2.91%, 1.30%]",0.0800,0.0,0.1818
MLP,0.003,0.6848,"[-14.63%, 9.26%]",0.1852,131.6247,0.0256

network 0, training 3, epoch 1: train scaled MSE 0.821971; val RMSE 0.01923975; lr 0.001; 0s
network 0, training 3, epoch 10: train scaled MSE 0.0384456; val RMSE 0.004542803; lr 0.001; 2s
network 0, training 3, epoch 20: train scaled MSE 0.0243042; val RMSE 0.004823463; lr 0.001; 4s
network 0, training 3, epoch 30: train scaled MSE 0.0187861; val RMSE 0.003455436; lr 0.001; 6s
network 0, training 3, epoch 40: train scaled MSE 0.0128363; val RMSE 0.003480713; lr 0.001; 8s
network 0, training 3, epoch 50: train scaled MSE 0.00593779; val RMSE 0.003470469; lr 0.0005; 10s
network 0, training 3, epoch 60: train scaled MSE 0.00402388; val RMSE 0.0034711; lr 0.0005; 12s
network 0, training 3, epoch 70: train scaled MSE 0.00321888; val RMSE 0.003419834; lr 0.00025; 14s
Standard Linear Baseline Validation RMSE: 0.003511381

Network seed 0, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0022,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0023,-2.0984,"[-7.27%, 0.60%]",0.0585,0.0,0.1395
MLP,0.0027,-46.1889,"[-84.41%, -27.44%]",-0.0156,-126.6554,0.0029

network 0, training 4, epoch 1: train scaled MSE 0.854745; val RMSE 0.01868001; lr 0.001; 0s
network 0, training 4, epoch 10: train scaled MSE 0.0306504; val RMSE 0.003919899; lr 0.001; 2s
network 0, training 4, epoch 20: train scaled MSE 0.0303612; val RMSE 0.003213143; lr 0.001; 4s
network 0, training 4, epoch 30: train scaled MSE 0.0101792; val RMSE 0.002104164; lr 0.001; 6s
network 0, training 4, epoch 40: train scaled MSE 0.00586581; val RMSE 0.001753792; lr 0.001; 8s
network 0, training 4, epoch 50: train scaled MSE 0.00435642; val RMSE 0.002313372; lr 0.001; 10s
network 0, training 4, epoch 60: train scaled MSE 0.00327069; val RMSE 0.00169686; lr 0.001; 13s
network 0, training 4, epoch 70: train scaled MSE 0.00275375; val RMSE 0.001563354; lr 0.001; 15s
network 0, training 4, epoch 80: train scaled MSE 0.00221738; val RMSE 0.001558607; lr 0.001; 17s
network 0, training 4, epoch 90: train scaled MSE 0.00212253; val RMSE 0.001469915; lr 0.0005; 19s
network 0, training 4, epoch 100: train scaled MSE 0.00144392; val RMSE 0.001443455; lr 0.0005; 21s
network 0, training 4, epoch 110: train scaled MSE 0.00134635; val RMSE 0.001446657; lr 0.0005; 23s
network 0, training 4, epoch 120: train scaled MSE 0.00124038; val RMSE 0.001419513; lr 0.00025; 25s
network 0, training 4, epoch 130: train scaled MSE 0.0010249; val RMSE 0.001403747; lr 0.000125; 28s
network 0, training 4, epoch 140: train scaled MSE 0.00112826; val RMSE 0.00140894; lr 0.000125; 30s
network 0, training 4, epoch 150: train scaled MSE 0.00112974; val RMSE 0.001412785; lr 0.000125; 32s
network 0, training 4, epoch 160: train scaled MSE 0.000983092; val RMSE 0.001398619; lr 6.25e-05; 34s
network 0, training 4, epoch 170: train scaled MSE 0.00120643; val RMSE 0.001422875; lr 6.25e-05; 36s
network 0, training 4, epoch 180: train scaled MSE 0.000883396; val RMSE 0.00139053; lr 3.125e-05; 38s
network 0, training 4, epoch 190: train scaled MSE 0.000873709; val RMSE 0.00139255; lr 3.125e-05; 40s
network 0, training 4, epoch 200: train scaled MSE 0.000885737; val RMSE 0.001389208; lr 3.125e-05; 42s
network 0, training 4, epoch 210: train scaled MSE 0.000854032; val RMSE 0.001387285; lr 3.125e-05; 44s
network 0, training 4, epoch 220: train scaled MSE 0.000864774; val RMSE 0.001388269; lr 3.125e-05; 47s
network 0, training 4, epoch 230: train scaled MSE 0.000839663; val RMSE 0.00138834; lr 1.5625e-05; 49s
network 0, training 4, epoch 240: train scaled MSE 0.000827822; val RMSE 0.001385174; lr 1.5625e-05; 51s
network 0, training 4, epoch 250: train scaled MSE 0.000823274; val RMSE 0.001383851; lr 1.5625e-05; 53s
network 0, training 4, epoch 260: train scaled MSE 0.000822498; val RMSE 0.001383099; lr 1.5625e-05; 55s
network 0, training 4, epoch 270: train scaled MSE 0.000817049; val RMSE 0.001381492; lr 1e-05; 57s
network 0, training 4, epoch 280: train scaled MSE 0.00080812; val RMSE 0.00138122; lr 1e-05; 59s
network 0, training 4, epoch 290: train scaled MSE 0.000805531; val RMSE 0.001381173; lr 1e-05; 62s
network 0, training 4, epoch 300: train scaled MSE 0.000802153; val RMSE 0.001380827; lr 1e-05; 64s
network 0, training 4, epoch 310: train scaled MSE 0.000814498; val RMSE 0.001381872; lr 1e-05; 66s
network 0, training 4, epoch 320: train scaled MSE 0.000795951; val RMSE 0.001380873; lr 1e-05; 68s
network 0, training 4, epoch 330: train scaled MSE 0.000793974; val RMSE 0.001379938; lr 1e-05; 70s
network 0, training 4, epoch 340: train scaled MSE 0.000790811; val RMSE 0.001379653; lr 1e-05; 72s
network 0, training 4, epoch 350: train scaled MSE 0.000791676; val RMSE 0.001379955; lr 1e-05; 74s
network 0, training 4, epoch 360: train scaled MSE 0.000785937; val RMSE 0.001378913; lr 1e-05; 77s
network 0, training 4, epoch 370: train scaled MSE 0.000793504; val RMSE 0.001378871; lr 1e-05; 79s
network 0, training 4, epoch 380: train scaled MSE 0.000783776; val RMSE 0.001378297; lr 1e-05; 81s
network 0, training 4, epoch 390: train scaled MSE 0.00077848; val RMSE 0.001378472; lr 1e-05; 83s
network 0, training 4, epoch 400: train scaled MSE 0.000774197; val RMSE 0.001377451; lr 1e-05; 85s
network 0, training 4, epoch 410: train scaled MSE 0.000771715; val RMSE 0.001376448; lr 1e-05; 88s
network 0, training 4, epoch 420: train scaled MSE 0.000769065; val RMSE 0.00137577; lr 1e-05; 90s
network 0, training 4, epoch 430: train scaled MSE 0.000766732; val RMSE 0.001375829; lr 1e-05; 92s
network 0, training 4, epoch 440: train scaled MSE 0.000763562; val RMSE 0.001375631; lr 1e-05; 94s
network 0, training 4, epoch 450: train scaled MSE 0.000762101; val RMSE 0.001375778; lr 1e-05; 96s
network 0, training 4, epoch 460: train scaled MSE 0.000757804; val RMSE 0.001374961; lr 1e-05; 98s
network 0, training 4, epoch 470: train scaled MSE 0.000755266; val RMSE 0.001374561; lr 1e-05; 100s
network 0, training 4, epoch 480: train scaled MSE 0.000763132; val RMSE 0.001375306; lr 1e-05; 102s
network 0, training 4, epoch 490: train scaled MSE 0.000749714; val RMSE 0.001373708; lr 1e-05; 105s
network 0, training 4, epoch 500: train scaled MSE 0.000746974; val RMSE 0.001373446; lr 1e-05; 107s
network 0, training 4, epoch 510: train scaled MSE 0.000747451; val RMSE 0.001373675; lr 1e-05; 109s
network 0, training 4, epoch 520: train scaled MSE 0.000741709; val RMSE 0.001372285; lr 1e-05; 111s
network 0, training 4, epoch 530: train scaled MSE 0.000739949; val RMSE 0.001372483; lr 1e-05; 113s
network 0, training 4, epoch 540: train scaled MSE 0.000740736; val RMSE 0.001373659; lr 1e-05; 115s
network 0, training 4, epoch 550: train scaled MSE 0.00073763; val RMSE 0.00137272; lr 1e-05; 118s
network 0, training 4, epoch 560: train scaled MSE 0.000734955; val RMSE 0.001372313; lr 1e-05; 120s
network 0, training 4, epoch 570: train scaled MSE 0.000731568; val RMSE 0.001371924; lr 1e-05; 122s
network 0, training 4, epoch 580: train scaled MSE 0.000728606; val RMSE 0.001371576; lr 1e-05; 124s
network 0, training 4, epoch 590: train scaled MSE 0.000732691; val RMSE 0.001371115; lr 1e-05; 126s
network 0, training 4, epoch 600: train scaled MSE 0.000725651; val RMSE 0.001371216; lr 1e-05; 128s
network 0, training 4, epoch 610: train scaled MSE 0.000722407; val RMSE 0.001370726; lr 1e-05; 130s
network 0, training 4, epoch 620: train scaled MSE 0.000719158; val RMSE 0.001370023; lr 1e-05; 132s
network 0, training 4, epoch 630: train scaled MSE 0.00071746; val RMSE 0.001369808; lr 1e-05; 134s
network 0, training 4, epoch 640: train scaled MSE 0.00071745; val RMSE 0.001369778; lr 1e-05; 136s
network 0, training 4, epoch 650: train scaled MSE 0.000714707; val RMSE 0.001370112; lr 1e-05; 138s
network 0, training 4, epoch 660: train scaled MSE 0.000718651; val RMSE 0.001370185; lr 1e-05; 139s
network 0, training 4, epoch 670: train scaled MSE 0.00070891; val RMSE 0.001368659; lr 1e-05; 141s
network 0, training 4, epoch 680: train scaled MSE 0.0007067; val RMSE 0.001368448; lr 1e-05; 143s
network 0, training 4, epoch 690: train scaled MSE 0.000703895; val RMSE 0.001368208; lr 1e-05; 145s
network 0, training 4, epoch 700: train scaled MSE 0.000702474; val RMSE 0.001367761; lr 1e-05; 147s
network 0, training 4, epoch 710: train scaled MSE 0.000699451; val RMSE 0.00136699; lr 1e-05; 149s
network 0, training 4, epoch 720: train scaled MSE 0.00069934; val RMSE 0.001367151; lr 1e-05; 151s
network 0, training 4, epoch 730: train scaled MSE 0.00069762; val RMSE 0.001367565; lr 1e-05; 153s
network 0, training 4, epoch 740: train scaled MSE 0.000693323; val RMSE 0.001366358; lr 1e-05; 155s
network 0, training 4, epoch 750: train scaled MSE 0.000690172; val RMSE 0.001365757; lr 1e-05; 157s
network 0, training 4, epoch 760: train scaled MSE 0.000714444; val RMSE 0.0013668; lr 1e-05; 159s
network 0, training 4, epoch 770: train scaled MSE 0.00068475; val RMSE 0.001365293; lr 1e-05; 161s
network 0, training 4, epoch 780: train scaled MSE 0.000691402; val RMSE 0.001365292; lr 1e-05; 163s
network 0, training 4, epoch 790: train scaled MSE 0.000694839; val RMSE 0.001365778; lr 1e-05; 165s
network 0, training 4, epoch 800: train scaled MSE 0.00068292; val RMSE 0.00136484; lr 1e-05; 168s
network 0, training 4, epoch 810: train scaled MSE 0.000678126; val RMSE 0.001364161; lr 1e-05; 170s
network 0, training 4, epoch 820: train scaled MSE 0.000711605; val RMSE 0.001364895; lr 1e-05; 172s
network 0, training 4, epoch 830: train scaled MSE 0.000673925; val RMSE 0.001363889; lr 1e-05; 174s
network 0, training 4, epoch 840: train scaled MSE 0.000701268; val RMSE 0.001370573; lr 1e-05; 176s
network 0, training 4, epoch 850: train scaled MSE 0.000672665; val RMSE 0.001364103; lr 1e-05; 178s
network 0, training 4, epoch 860: train scaled MSE 0.000668944; val RMSE 0.001363162; lr 1e-05; 180s
network 0, training 4, epoch 870: train scaled MSE 0.00066688; val RMSE 0.001362603; lr 1e-05; 182s
network 0, training 4, epoch 880: train scaled MSE 0.000664738; val RMSE 0.001362433; lr 1e-05; 184s
network 0, training 4, epoch 890: train scaled MSE 0.000664631; val RMSE 0.00136284; lr 1e-05; 186s
network 0, training 4, epoch 900: train scaled MSE 0.000671656; val RMSE 0.001362055; lr 1e-05; 188s
network 0, training 4, epoch 910: train scaled MSE 0.000660582; val RMSE 0.001361591; lr 1e-05; 190s
network 0, training 4, epoch 920: train scaled MSE 0.000658501; val RMSE 0.001361299; lr 1e-05; 192s
network 0, training 4, epoch 930: train scaled MSE 0.000657864; val RMSE 0.001362195; lr 1e-05; 194s
network 0, training 4, epoch 940: train scaled MSE 0.000655661; val RMSE 0.001360846; lr 1e-05; 196s
network 0, training 4, epoch 950: train scaled MSE 0.000653314; val RMSE 0.001360759; lr 1e-05; 198s
network 0, training 4, epoch 960: train scaled MSE 0.000651837; val RMSE 0.001360663; lr 1e-05; 200s
network 0, training 4, epoch 970: train scaled MSE 0.000650731; val RMSE 0.001360372; lr 1e-05; 202s
network 0, training 4, epoch 980: train scaled MSE 0.00064842; val RMSE 0.001359894; lr 1e-05; 204s
network 0, training 4, epoch 990: train scaled MSE 0.000645973; val RMSE 0.001359533; lr 1e-05; 206s
network 0, training 4, epoch 1000: train scaled MSE 0.000643568; val RMSE 0.001359069; lr 1e-05; 209s
network 0, training 4, epoch 1010: train scaled MSE 0.000642528; val RMSE 0.001359279; lr 1e-05; 211s
network 0, training 4, epoch 1020: train scaled MSE 0.000643797; val RMSE 0.001359597; lr 1e-05; 213s
network 0, training 4, epoch 1030: train scaled MSE 0.000644928; val RMSE 0.00135914; lr 1e-05; 215s
network 0, training 4, epoch 1040: train scaled MSE 0.000639618; val RMSE 0.001358824; lr 1e-05; 217s
network 0, training 4, epoch 1050: train scaled MSE 0.000638183; val RMSE 0.001359519; lr 1e-05; 219s
network 0, training 4, epoch 1060: train scaled MSE 0.000636363; val RMSE 0.00135815; lr 1e-05; 221s
network 0, training 4, epoch 1070: train scaled MSE 0.000632045; val RMSE 0.001357898; lr 1e-05; 223s
network 0, training 4, epoch 1080: train scaled MSE 0.000630978; val RMSE 0.001358614; lr 1e-05; 226s
network 0, training 4, epoch 1090: train scaled MSE 0.000628001; val RMSE 0.001359092; lr 1e-05; 228s
network 0, training 4, epoch 1100: train scaled MSE 0.000626413; val RMSE 0.001357225; lr 1e-05; 230s
network 0, training 4, epoch 1110: train scaled MSE 0.000625878; val RMSE 0.001357265; lr 1e-05; 232s
network 0, training 4, epoch 1120: train scaled MSE 0.000623121; val RMSE 0.001356818; lr 1e-05; 234s
network 0, training 4, epoch 1130: train scaled MSE 0.00067207; val RMSE 0.001362307; lr 1e-05; 236s
network 0, training 4, epoch 1140: train scaled MSE 0.000620883; val RMSE 0.001356681; lr 1e-05; 238s
network 0, training 4, epoch 1150: train scaled MSE 0.000618236; val RMSE 0.001356352; lr 1e-05; 240s
network 0, training 4, epoch 1160: train scaled MSE 0.000616591; val RMSE 0.00135648; lr 1e-05; 242s
network 0, training 4, epoch 1170: train scaled MSE 0.000614975; val RMSE 0.001357038; lr 1e-05; 244s
network 0, training 4, epoch 1180: train scaled MSE 0.000612944; val RMSE 0.001355913; lr 1e-05; 247s
network 0, training 4, epoch 1190: train scaled MSE 0.000612771; val RMSE 0.001355665; lr 1e-05; 249s
network 0, training 4, epoch 1200: train scaled MSE 0.000612154; val RMSE 0.00135549; lr 1e-05; 251s
network 0, training 4, epoch 1210: train scaled MSE 0.000608879; val RMSE 0.001355546; lr 1e-05; 253s
network 0, training 4, epoch 1220: train scaled MSE 0.000605192; val RMSE 0.001355052; lr 1e-05; 255s
network 0, training 4, epoch 1230: train scaled MSE 0.000603728; val RMSE 0.001355011; lr 1e-05; 257s
network 0, training 4, epoch 1240: train scaled MSE 0.000602766; val RMSE 0.001353799; lr 1e-05; 259s
network 0, training 4, epoch 1250: train scaled MSE 0.000604027; val RMSE 0.001354303; lr 1e-05; 261s
network 0, training 4, epoch 1260: train scaled MSE 0.000605628; val RMSE 0.001355346; lr 1e-05; 264s
network 0, training 4, epoch 1270: train scaled MSE 0.000597469; val RMSE 0.001354513; lr 1e-05; 266s
network 0, training 4, epoch 1280: train scaled MSE 0.000594163; val RMSE 0.001353429; lr 1e-05; 268s
network 0, training 4, epoch 1290: train scaled MSE 0.000591683; val RMSE 0.001353103; lr 1e-05; 270s
network 0, training 4, epoch 1300: train scaled MSE 0.000594588; val RMSE 0.001353228; lr 1e-05; 272s
network 0, training 4, epoch 1310: train scaled MSE 0.000588616; val RMSE 0.001352742; lr 1e-05; 274s
network 0, training 4, epoch 1320: train scaled MSE 0.000587538; val RMSE 0.001352357; lr 1e-05; 276s
network 0, training 4, epoch 1330: train scaled MSE 0.000585349; val RMSE 0.001351901; lr 1e-05; 278s
network 0, training 4, epoch 1340: train scaled MSE 0.00058322; val RMSE 0.001351912; lr 1e-05; 280s
network 0, training 4, epoch 1350: train scaled MSE 0.000585528; val RMSE 0.001352094; lr 1e-05; 282s
network 0, training 4, epoch 1360: train scaled MSE 0.000583761; val RMSE 0.001353376; lr 1e-05; 284s
network 0, training 4, epoch 1370: train scaled MSE 0.000578388; val RMSE 0.001351545; lr 1e-05; 286s
network 0, training 4, epoch 1380: train scaled MSE 0.00057691; val RMSE 0.001351327; lr 1e-05; 288s
network 0, training 4, epoch 1390: train scaled MSE 0.000578411; val RMSE 0.001351192; lr 1e-05; 291s
network 0, training 4, epoch 1400: train scaled MSE 0.000579177; val RMSE 0.001351287; lr 1e-05; 293s
network 0, training 4, epoch 1410: train scaled MSE 0.000572807; val RMSE 0.001351542; lr 1e-05; 295s
network 0, training 4, epoch 1420: train scaled MSE 0.000570167; val RMSE 0.001350589; lr 1e-05; 297s
network 0, training 4, epoch 1430: train scaled MSE 0.000569501; val RMSE 0.001350861; lr 1e-05; 299s
network 0, training 4, epoch 1440: train scaled MSE 0.000568863; val RMSE 0.00135076; lr 1e-05; 301s
network 0, training 4, epoch 1450: train scaled MSE 0.000565099; val RMSE 0.001349878; lr 1e-05; 303s
network 0, training 4, epoch 1460: train scaled MSE 0.000564385; val RMSE 0.001349687; lr 1e-05; 305s
network 0, training 4, epoch 1470: train scaled MSE 0.000564975; val RMSE 0.001349618; lr 1e-05; 307s
network 0, training 4, epoch 1480: train scaled MSE 0.000560573; val RMSE 0.001349279; lr 1e-05; 309s
network 0, training 4, epoch 1490: train scaled MSE 0.000559691; val RMSE 0.001349344; lr 1e-05; 311s
network 0, training 4, epoch 1500: train scaled MSE 0.000557769; val RMSE 0.001348764; lr 1e-05; 313s
network 0, training 4, epoch 1510: train scaled MSE 0.000571066; val RMSE 0.001351619; lr 1e-05; 316s
network 0, training 4, epoch 1520: train scaled MSE 0.000554821; val RMSE 0.001348276; lr 1e-05; 318s
network 0, training 4, epoch 1530: train scaled MSE 0.000552654; val RMSE 0.001348317; lr 1e-05; 320s
network 0, training 4, epoch 1540: train scaled MSE 0.000551573; val RMSE 0.001347978; lr 1e-05; 322s
network 0, training 4, epoch 1550: train scaled MSE 0.000551083; val RMSE 0.001348224; lr 1e-05; 324s
network 0, training 4, epoch 1560: train scaled MSE 0.000548582; val RMSE 0.001347918; lr 1e-05; 326s
network 0, training 4, epoch 1570: train scaled MSE 0.000549072; val RMSE 0.001347959; lr 1e-05; 329s
network 0, training 4, epoch 1580: train scaled MSE 0.000547238; val RMSE 0.001347168; lr 1e-05; 331s
network 0, training 4, epoch 1590: train scaled MSE 0.000543567; val RMSE 0.001348517; lr 1e-05; 333s
network 0, training 4, epoch 1600: train scaled MSE 0.000542348; val RMSE 0.001346912; lr 1e-05; 335s
network 0, training 4, epoch 1610: train scaled MSE 0.000541112; val RMSE 0.00134696; lr 1e-05; 337s
network 0, training 4, epoch 1620: train scaled MSE 0.000539363; val RMSE 0.001346699; lr 1e-05; 339s
network 0, training 4, epoch 1630: train scaled MSE 0.000545838; val RMSE 0.001347265; lr 1e-05; 341s
network 0, training 4, epoch 1640: train scaled MSE 0.000536906; val RMSE 0.001346097; lr 1e-05; 343s
network 0, training 4, epoch 1650: train scaled MSE 0.000535449; val RMSE 0.00134596; lr 1e-05; 345s
network 0, training 4, epoch 1660: train scaled MSE 0.000533946; val RMSE 0.001345259; lr 1e-05; 347s
network 0, training 4, epoch 1670: train scaled MSE 0.000533316; val RMSE 0.00134517; lr 1e-05; 349s
network 0, training 4, epoch 1680: train scaled MSE 0.000531295; val RMSE 0.001346313; lr 1e-05; 351s
network 0, training 4, epoch 1690: train scaled MSE 0.000530285; val RMSE 0.001345949; lr 1e-05; 353s
network 0, training 4, epoch 1700: train scaled MSE 0.000530342; val RMSE 0.001346972; lr 1e-05; 355s
network 0, training 4, epoch 1710: train scaled MSE 0.000528161; val RMSE 0.001346034; lr 1e-05; 357s
network 0, training 4, epoch 1720: train scaled MSE 0.000526069; val RMSE 0.001345177; lr 1e-05; 359s
network 0, training 4, epoch 1730: train scaled MSE 0.000526951; val RMSE 0.001345166; lr 1e-05; 361s
network 0, training 4, epoch 1740: train scaled MSE 0.00052403; val RMSE 0.0013447; lr 1e-05; 363s
network 0, training 4, epoch 1750: train scaled MSE 0.000523535; val RMSE 0.00134535; lr 1e-05; 365s
network 0, training 4, epoch 1760: train scaled MSE 0.000528579; val RMSE 0.001345486; lr 1e-05; 367s
network 0, training 4, epoch 1770: train scaled MSE 0.000520379; val RMSE 0.001344392; lr 1e-05; 369s
network 0, training 4, epoch 1780: train scaled MSE 0.000520105; val RMSE 0.001344205; lr 1e-05; 371s
network 0, training 4, epoch 1790: train scaled MSE 0.000524849; val RMSE 0.00134426; lr 1e-05; 372s
network 0, training 4, epoch 1800: train scaled MSE 0.00051693; val RMSE 0.001343638; lr 1e-05; 374s
network 0, training 4, epoch 1810: train scaled MSE 0.00051571; val RMSE 0.001343425; lr 1e-05; 376s
network 0, training 4, epoch 1820: train scaled MSE 0.000518578; val RMSE 0.00134541; lr 1e-05; 378s
network 0, training 4, epoch 1830: train scaled MSE 0.000513793; val RMSE 0.001343154; lr 1e-05; 380s
network 0, training 4, epoch 1840: train scaled MSE 0.000512435; val RMSE 0.00134363; lr 1e-05; 382s
network 0, training 4, epoch 1850: train scaled MSE 0.000510423; val RMSE 0.001342753; lr 1e-05; 384s
network 0, training 4, epoch 1860: train scaled MSE 0.000512208; val RMSE 0.001342561; lr 1e-05; 386s
network 0, training 4, epoch 1870: train scaled MSE 0.000510383; val RMSE 0.001342902; lr 1e-05; 388s
network 0, training 4, epoch 1880: train scaled MSE 0.000506413; val RMSE 0.001342008; lr 1e-05; 390s
network 0, training 4, epoch 1890: train scaled MSE 0.000506973; val RMSE 0.001342484; lr 1e-05; 392s
network 0, training 4, epoch 1900: train scaled MSE 0.000504352; val RMSE 0.001341646; lr 1e-05; 394s
network 0, training 4, epoch 1910: train scaled MSE 0.000503321; val RMSE 0.001343265; lr 1e-05; 396s
network 0, training 4, epoch 1920: train scaled MSE 0.000504231; val RMSE 0.001341347; lr 1e-05; 398s
network 0, training 4, epoch 1930: train scaled MSE 0.00050071; val RMSE 0.001342233; lr 1e-05; 400s
network 0, training 4, epoch 1940: train scaled MSE 0.000499781; val RMSE 0.001341172; lr 1e-05; 402s
network 0, training 4, epoch 1950: train scaled MSE 0.000498205; val RMSE 0.001341208; lr 1e-05; 404s
network 0, training 4, epoch 1960: train scaled MSE 0.000496933; val RMSE 0.001340435; lr 1e-05; 406s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0029,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0029,0.2284,"[-6.69%, 1.76%]",0.0857,0.0,0.1257
MLP,0.0028,5.7576,"[-14.36%, 26.40%]",0.2956,245.0627,0.1389

network 0, training 5, epoch 1: train scaled MSE 0.829136; val RMSE 0.01823763; lr 0.001; 0s
network 0, training 5, epoch 10: train scaled MSE 0.0512022; val RMSE 0.004124205; lr 0.001; 2s
network 0, training 5, epoch 20: train scaled MSE 0.0285338; val RMSE 0.002401214; lr 0.001; 4s
network 0, training 5, epoch 30: train scaled MSE 0.0146085; val RMSE 0.002129286; lr 0.001; 7s
network 0, training 5, epoch 40: train scaled MSE 0.00793165; val RMSE 0.002883796; lr 0.001; 9s
network 0, training 5, epoch 50: train scaled MSE 0.00634698; val RMSE 0.00202207; lr 0.001; 11s
network 0, training 5, epoch 60: train scaled MSE 0.00482238; val RMSE 0.001805; lr 0.001; 13s
network 0, training 5, epoch 70: train scaled MSE 0.00360013; val RMSE 0.001834805; lr 0.001; 15s
network 0, training 5, epoch 80: train scaled MSE 0.00287332; val RMSE 0.001803971; lr 0.001; 17s
network 0, training 5, epoch 90: train scaled MSE 0.00400797; val RMSE 0.001922388; lr 0.001; 19s
network 0, training 5, epoch 100: train scaled MSE 0.00234172; val RMSE 0.001670292; lr 0.0005; 21s
network 0, training 5, epoch 110: train scaled MSE 0.00187596; val RMSE 0.00162638; lr 0.0005; 24s
network 0, training 5, epoch 120: train scaled MSE 0.00169406; val RMSE 0.001633022; lr 0.0005; 26s
network 0, training 5, epoch 130: train scaled MSE 0.00161795; val RMSE 0.001632882; lr 0.0005; 28s
network 0, training 5, epoch 140: train scaled MSE 0.00126943; val RMSE 0.0015728; lr 0.00025; 30s
network 0, training 5, epoch 150: train scaled MSE 0.00122032; val RMSE 0.001572044; lr 0.00025; 32s
network 0, training 5, epoch 160: train scaled MSE 0.00114495; val RMSE 0.001563312; lr 0.00025; 34s
network 0, training 5, epoch 170: train scaled MSE 0.00109282; val RMSE 0.001584279; lr 0.00025; 36s
network 0, training 5, epoch 180: train scaled MSE 0.00104466; val RMSE 0.001545611; lr 0.00025; 38s
network 0, training 5, epoch 190: train scaled MSE 0.00108545; val RMSE 0.001539282; lr 0.00025; 40s
network 0, training 5, epoch 200: train scaled MSE 0.000918755; val RMSE 0.001533504; lr 0.00025; 42s
network 0, training 5, epoch 210: train scaled MSE 0.000839587; val RMSE 0.001522069; lr 0.000125; 44s
network 0, training 5, epoch 220: train scaled MSE 0.000832149; val RMSE 0.001521289; lr 0.000125; 46s
network 0, training 5, epoch 230: train scaled MSE 0.000806139; val RMSE 0.001519823; lr 0.000125; 48s
network 0, training 5, epoch 240: train scaled MSE 0.000778595; val RMSE 0.001518994; lr 0.000125; 51s
network 0, training 5, epoch 250: train scaled MSE 0.000779812; val RMSE 0.001522347; lr 0.000125; 53s
network 0, training 5, epoch 260: train scaled MSE 0.000753698; val RMSE 0.001517501; lr 0.000125; 55s
network 0, training 5, epoch 270: train scaled MSE 0.000698048; val RMSE 0.001513121; lr 6.25e-05; 57s
network 0, training 5, epoch 280: train scaled MSE 0.000687737; val RMSE 0.001508522; lr 6.25e-05; 59s
network 0, training 5, epoch 290: train scaled MSE 0.000677042; val RMSE 0.001522454; lr 6.25e-05; 61s
network 0, training 5, epoch 300: train scaled MSE 0.000668082; val RMSE 0.001504895; lr 6.25e-05; 63s
network 0, training 5, epoch 310: train scaled MSE 0.000654681; val RMSE 0.001504916; lr 6.25e-05; 65s
network 0, training 5, epoch 320: train scaled MSE 0.000738547; val RMSE 0.001507804; lr 6.25e-05; 67s
network 0, training 5, epoch 330: train scaled MSE 0.000668612; val RMSE 0.001510446; lr 6.25e-05; 69s
network 0, training 5, epoch 340: train scaled MSE 0.000624125; val RMSE 0.001500411; lr 6.25e-05; 71s
network 0, training 5, epoch 350: train scaled MSE 0.00061177; val RMSE 0.001501649; lr 6.25e-05; 73s
network 0, training 5, epoch 360: train scaled MSE 0.000604454; val RMSE 0.001498262; lr 6.25e-05; 75s
network 0, training 5, epoch 370: train scaled MSE 0.0005831; val RMSE 0.001495248; lr 3.125e-05; 77s
network 0, training 5, epoch 380: train scaled MSE 0.000577029; val RMSE 0.001495851; lr 3.125e-05; 79s
network 0, training 5, epoch 390: train scaled MSE 0.000569206; val RMSE 0.001494045; lr 1.5625e-05; 81s
network 0, training 5, epoch 400: train scaled MSE 0.000581327; val RMSE 0.001493336; lr 1.5625e-05; 83s
network 0, training 5, epoch 410: train scaled MSE 0.000563384; val RMSE 0.00149271; lr 1e-05; 85s
network 0, training 5, epoch 420: train scaled MSE 0.000561189; val RMSE 0.001492432; lr 1e-05; 87s
network 0, training 5, epoch 430: train scaled MSE 0.000559439; val RMSE 0.001492363; lr 1e-05; 89s
network 0, training 5, epoch 440: train scaled MSE 0.000557577; val RMSE 0.001491551; lr 1e-05; 91s
network 0, training 5, epoch 450: train scaled MSE 0.00055798; val RMSE 0.001491524; lr 1e-05; 93s
network 0, training 5, epoch 460: train scaled MSE 0.000554618; val RMSE 0.001491636; lr 1e-05; 95s
network 0, training 5, epoch 470: train scaled MSE 0.000552275; val RMSE 0.001490328; lr 1e-05; 97s
network 0, training 5, epoch 480: train scaled MSE 0.000550403; val RMSE 0.001490402; lr 1e-05; 99s
network 0, training 5, epoch 490: train scaled MSE 0.000548086; val RMSE 0.001489677; lr 1e-05; 101s
network 0, training 5, epoch 500: train scaled MSE 0.000546132; val RMSE 0.001489792; lr 1e-05; 103s
network 0, training 5, epoch 510: train scaled MSE 0.000544207; val RMSE 0.001491433; lr 1e-05; 105s
network 0, training 5, epoch 520: train scaled MSE 0.000544425; val RMSE 0.0014898; lr 1e-05; 107s
network 0, training 5, epoch 530: train scaled MSE 0.000541285; val RMSE 0.001489545; lr 1e-05; 109s
network 0, training 5, epoch 540: train scaled MSE 0.000540474; val RMSE 0.001490047; lr 1e-05; 111s
network 0, training 5, epoch 550: train scaled MSE 0.000536537; val RMSE 0.001489152; lr 1e-05; 113s
network 0, training 5, epoch 560: train scaled MSE 0.000543637; val RMSE 0.001489558; lr 1e-05; 115s
network 0, training 5, epoch 570: train scaled MSE 0.000534566; val RMSE 0.001488449; lr 1e-05; 117s
network 0, training 5, epoch 580: train scaled MSE 0.000533395; val RMSE 0.001488733; lr 1e-05; 119s
network 0, training 5, epoch 590: train scaled MSE 0.000529626; val RMSE 0.001488215; lr 1e-05; 121s
network 0, training 5, epoch 600: train scaled MSE 0.00052834; val RMSE 0.001487358; lr 1e-05; 124s
network 0, training 5, epoch 610: train scaled MSE 0.000526317; val RMSE 0.001487837; lr 1e-05; 126s
network 0, training 5, epoch 620: train scaled MSE 0.000530096; val RMSE 0.001488031; lr 1e-05; 128s
network 0, training 5, epoch 630: train scaled MSE 0.000535316; val RMSE 0.001488579; lr 1e-05; 130s
network 0, training 5, epoch 640: train scaled MSE 0.000520912; val RMSE 0.001487217; lr 1e-05; 132s
network 0, training 5, epoch 650: train scaled MSE 0.000522598; val RMSE 0.001487071; lr 1e-05; 134s
network 0, training 5, epoch 660: train scaled MSE 0.000517787; val RMSE 0.001485905; lr 1e-05; 136s
network 0, training 5, epoch 670: train scaled MSE 0.000516344; val RMSE 0.001487193; lr 1e-05; 138s
network 0, training 5, epoch 680: train scaled MSE 0.000531129; val RMSE 0.001489274; lr 1e-05; 140s
network 0, training 5, epoch 690: train scaled MSE 0.000513887; val RMSE 0.001485954; lr 1e-05; 142s
network 0, training 5, epoch 700: train scaled MSE 0.000511574; val RMSE 0.001485289; lr 1e-05; 144s
network 0, training 5, epoch 710: train scaled MSE 0.000510434; val RMSE 0.001485995; lr 1e-05; 146s
network 0, training 5, epoch 720: train scaled MSE 0.000510599; val RMSE 0.001485788; lr 1e-05; 148s
network 0, training 5, epoch 730: train scaled MSE 0.000510393; val RMSE 0.001485627; lr 1e-05; 150s
network 0, training 5, epoch 740: train scaled MSE 0.000515577; val RMSE 0.001485676; lr 1e-05; 152s
network 0, training 5, epoch 750: train scaled MSE 0.0005061; val RMSE 0.00148509; lr 1e-05; 154s
network 0, training 5, epoch 760: train scaled MSE 0.00050812; val RMSE 0.001485522; lr 1e-05; 156s
network 0, training 5, epoch 770: train scaled MSE 0.000503217; val RMSE 0.001485532; lr 1e-05; 158s
network 0, training 5, epoch 780: train scaled MSE 0.000536352; val RMSE 0.00149114; lr 1e-05; 160s
network 0, training 5, epoch 790: train scaled MSE 0.000502824; val RMSE 0.00148403; lr 1e-05; 162s
network 0, training 5, epoch 800: train scaled MSE 0.000498278; val RMSE 0.001483908; lr 1e-05; 164s
network 0, training 5, epoch 810: train scaled MSE 0.000497044; val RMSE 0.001485023; lr 1e-05; 166s
network 0, training 5, epoch 820: train scaled MSE 0.000495478; val RMSE 0.001484042; lr 1e-05; 168s
network 0, training 5, epoch 830: train scaled MSE 0.000494075; val RMSE 0.00148335; lr 1e-05; 170s
network 0, training 5, epoch 840: train scaled MSE 0.000492075; val RMSE 0.001483554; lr 1e-05; 172s
network 0, training 5, epoch 850: train scaled MSE 0.000518755; val RMSE 0.001487182; lr 1e-05; 174s
network 0, training 5, epoch 860: train scaled MSE 0.000493929; val RMSE 0.001484187; lr 1e-05; 176s
network 0, training 5, epoch 870: train scaled MSE 0.000487574; val RMSE 0.001483516; lr 1e-05; 178s
network 0, training 5, epoch 880: train scaled MSE 0.00048653; val RMSE 0.001482818; lr 1e-05; 180s
network 0, training 5, epoch 890: train scaled MSE 0.000488362; val RMSE 0.001483511; lr 1e-05; 182s
network 0, training 5, epoch 900: train scaled MSE 0.000484153; val RMSE 0.001484068; lr 1e-05; 184s
network 0, training 5, epoch 910: train scaled MSE 0.000482612; val RMSE 0.001482569; lr 1e-05; 186s
network 0, training 5, epoch 920: train scaled MSE 0.000484676; val RMSE 0.001482691; lr 1e-05; 188s
network 0, training 5, epoch 930: train scaled MSE 0.000480571; val RMSE 0.001482743; lr 1e-05; 190s
network 0, training 5, epoch 940: train scaled MSE 0.000490003; val RMSE 0.001483369; lr 1e-05; 192s
network 0, training 5, epoch 950: train scaled MSE 0.00047765; val RMSE 0.001482; lr 1e-05; 194s
network 0, training 5, epoch 960: train scaled MSE 0.000477164; val RMSE 0.001482245; lr 1e-05; 196s
network 0, training 5, epoch 970: train scaled MSE 0.00048347; val RMSE 0.001483897; lr 1e-05; 198s
network 0, training 5, epoch 980: train scaled MSE 0.00047234; val RMSE 0.001481656; lr 1e-05; 200s
network 0, training 5, epoch 990: train scaled MSE 0.000484536; val RMSE 0.001481906; lr 1e-05; 202s
network 0, training 5, epoch 1000: train scaled MSE 0.000469713; val RMSE 0.001481249; lr 1e-05; 204s
network 0, training 5, epoch 1010: train scaled MSE 0.000468774; val RMSE 0.00148196; lr 1e-05; 206s
network 0, training 5, epoch 1020: train scaled MSE 0.000467226; val RMSE 0.001482127; lr 1e-05; 208s
network 0, training 5, epoch 1030: train scaled MSE 0.00046554; val RMSE 0.001481235; lr 1e-05; 210s
network 0, training 5, epoch 1040: train scaled MSE 0.000464219; val RMSE 0.001481223; lr 1e-05; 212s
network 0, training 5, epoch 1050: train scaled MSE 0.000464544; val RMSE 0.001481018; lr 1e-05; 214s
network 0, training 5, epoch 1060: train scaled MSE 0.000485789; val RMSE 0.00148265; lr 1e-05; 216s
network 0, training 5, epoch 1070: train scaled MSE 0.000460867; val RMSE 0.001480995; lr 1e-05; 218s
network 0, training 5, epoch 1080: train scaled MSE 0.000462979; val RMSE 0.001482254; lr 1e-05; 220s
network 0, training 5, epoch 1090: train scaled MSE 0.000461806; val RMSE 0.001482047; lr 1e-05; 222s
Standard Linear Baseline Validation RMSE: 0.001432839

Network seed 0, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0019,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0019,-8.1143,"[-19.41%, -2.25%]",0.0633,0.0,0.0686
MLP,0.0020,-21.5489,"[-57.69%, 0.82%]",0.1313,107.4355,0.0469

network 0, training 6, epoch 1: train scaled MSE 0.857484; val RMSE 0.01954433; lr 0.001; 0s
network 0, training 6, epoch 10: train scaled MSE 0.0439191; val RMSE 0.004194617; lr 0.001; 2s
network 0, training 6, epoch 20: train scaled MSE 0.0291945; val RMSE 0.003217187; lr 0.001; 4s
network 0, training 6, epoch 30: train scaled MSE 0.0229217; val RMSE 0.003667638; lr 0.001; 6s
network 0, training 6, epoch 40: train scaled MSE 0.0121765; val RMSE 0.003722695; lr 0.001; 8s
network 0, training 6, epoch 50: train scaled MSE 0.00600614; val RMSE 0.002919842; lr 0.001; 10s
network 0, training 6, epoch 60: train scaled MSE 0.00461391; val RMSE 0.00271875; lr 0.001; 12s
network 0, training 6, epoch 70: train scaled MSE 0.00503746; val RMSE 0.002728931; lr 0.001; 14s
network 0, training 6, epoch 80: train scaled MSE 0.00268673; val RMSE 0.002525288; lr 0.0005; 16s
network 0, training 6, epoch 90: train scaled MSE 0.00281742; val RMSE 0.002522682; lr 0.0005; 18s
network 0, training 6, epoch 100: train scaled MSE 0.00219097; val RMSE 0.002500814; lr 0.00025; 20s
network 0, training 6, epoch 110: train scaled MSE 0.00214326; val RMSE 0.002491779; lr 0.00025; 22s
network 0, training 6, epoch 120: train scaled MSE 0.00194797; val RMSE 0.002478297; lr 0.00025; 24s
network 0, training 6, epoch 130: train scaled MSE 0.00191777; val RMSE 0.002468332; lr 0.00025; 26s
network 0, training 6, epoch 140: train scaled MSE 0.00170714; val RMSE 0.002457929; lr 0.00025; 28s
network 0, training 6, epoch 150: train scaled MSE 0.00162679; val RMSE 0.002474748; lr 0.00025; 30s
network 0, training 6, epoch 160: train scaled MSE 0.00141765; val RMSE 0.00245475; lr 0.000125; 33s
network 0, training 6, epoch 170: train scaled MSE 0.00135254; val RMSE 0.002430166; lr 0.000125; 35s
network 0, training 6, epoch 180: train scaled MSE 0.00129689; val RMSE 0.002425671; lr 0.000125; 36s
network 0, training 6, epoch 190: train scaled MSE 0.00124739; val RMSE 0.002421131; lr 0.000125; 38s
network 0, training 6, epoch 200: train scaled MSE 0.00120617; val RMSE 0.002428855; lr 0.000125; 40s
network 0, training 6, epoch 210: train scaled MSE 0.00111515; val RMSE 0.002416045; lr 6.25e-05; 42s
network 0, training 6, epoch 220: train scaled MSE 0.00112304; val RMSE 0.002420903; lr 6.25e-05; 45s
network 0, training 6, epoch 230: train scaled MSE 0.00107399; val RMSE 0.002411596; lr 3.125e-05; 47s
network 0, training 6, epoch 240: train scaled MSE 0.00104397; val RMSE 0.002414385; lr 3.125e-05; 49s
network 0, training 6, epoch 250: train scaled MSE 0.00102895; val RMSE 0.002409567; lr 3.125e-05; 51s
network 0, training 6, epoch 260: train scaled MSE 0.00101775; val RMSE 0.002409664; lr 3.125e-05; 53s
network 0, training 6, epoch 270: train scaled MSE 0.000998546; val RMSE 0.002410255; lr 1.5625e-05; 55s
network 0, training 6, epoch 280: train scaled MSE 0.000987845; val RMSE 0.002409209; lr 1e-05; 56s
network 0, training 6, epoch 290: train scaled MSE 0.000980729; val RMSE 0.00240913; lr 1e-05; 58s
network 0, training 6, epoch 300: train scaled MSE 0.000976262; val RMSE 0.002408713; lr 1e-05; 60s
network 0, training 6, epoch 310: train scaled MSE 0.000970868; val RMSE 0.002408494; lr 1e-05; 62s
network 0, training 6, epoch 320: train scaled MSE 0.000966401; val RMSE 0.002408284; lr 1e-05; 65s
network 0, training 6, epoch 330: train scaled MSE 0.000961023; val RMSE 0.002408595; lr 1e-05; 67s
network 0, training 6, epoch 340: train scaled MSE 0.000957887; val RMSE 0.002408305; lr 1e-05; 69s
network 0, training 6, epoch 350: train scaled MSE 0.000951362; val RMSE 0.002408133; lr 1e-05; 71s
network 0, training 6, epoch 360: train scaled MSE 0.000945219; val RMSE 0.002407507; lr 1e-05; 73s
network 0, training 6, epoch 370: train scaled MSE 0.000939794; val RMSE 0.002407294; lr 1e-05; 75s
network 0, training 6, epoch 380: train scaled MSE 0.000942329; val RMSE 0.00240827; lr 1e-05; 77s
network 0, training 6, epoch 390: train scaled MSE 0.000932804; val RMSE 0.002407253; lr 1e-05; 79s
network 0, training 6, epoch 400: train scaled MSE 0.000926776; val RMSE 0.002406467; lr 1e-05; 81s
network 0, training 6, epoch 410: train scaled MSE 0.000921834; val RMSE 0.00240619; lr 1e-05; 83s
network 0, training 6, epoch 420: train scaled MSE 0.000974092; val RMSE 0.002413962; lr 1e-05; 85s
network 0, training 6, epoch 430: train scaled MSE 0.000914065; val RMSE 0.002407216; lr 1e-05; 86s
network 0, training 6, epoch 440: train scaled MSE 0.000911967; val RMSE 0.00240705; lr 1e-05; 88s
network 0, training 6, epoch 450: train scaled MSE 0.000904936; val RMSE 0.002406628; lr 1e-05; 90s
Standard Linear Baseline Validation RMSE: 0.00259309

Network seed 0, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0022,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0022,-3.4941,"[-12.48%, 0.51%]",0.0743,0.0,0.1328
MLP,0.0022,-8.5340,"[-22.65%, 0.01%]",0.1784,140.1829,0.0064

network 0, training 7, epoch 1: train scaled MSE 0.823425; val RMSE 0.01967693; lr 0.001; 0s
network 0, training 7, epoch 10: train scaled MSE 0.0271185; val RMSE 0.004369047; lr 0.001; 2s
network 0, training 7, epoch 20: train scaled MSE 0.0122081; val RMSE 0.00343094; lr 0.001; 4s
network 0, training 7, epoch 30: train scaled MSE 0.0113773; val RMSE 0.00330391; lr 0.001; 6s
network 0, training 7, epoch 40: train scaled MSE 0.00773554; val RMSE 0.00311832; lr 0.001; 8s
network 0, training 7, epoch 50: train scaled MSE 0.00505969; val RMSE 0.003038911; lr 0.0005; 10s
network 0, training 7, epoch 60: train scaled MSE 0.00418832; val RMSE 0.003008017; lr 0.00025; 12s
network 0, training 7, epoch 70: train scaled MSE 0.00555857; val RMSE 0.003017303; lr 0.00025; 14s
network 0, training 7, epoch 80: train scaled MSE 0.00374789; val RMSE 0.00301725; lr 0.00025; 16s
network 0, training 7, epoch 90: train scaled MSE 0.00332956; val RMSE 0.00302122; lr 0.000125; 18s
network 0, training 7, epoch 100: train scaled MSE 0.00317355; val RMSE 0.003024; lr 0.000125; 20s
network 0, training 7, epoch 110: train scaled MSE 0.00304964; val RMSE 0.003017879; lr 6.25e-05; 22s
network 0, training 7, epoch 120: train scaled MSE 0.00296416; val RMSE 0.00301032; lr 3.125e-05; 24s
network 0, training 7, epoch 130: train scaled MSE 0.00289694; val RMSE 0.00301029; lr 1.5625e-05; 26s
Standard Linear Baseline Validation RMSE: 0.002935623

Network seed 0, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0029,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0028,0.4021,"[-3.33%, 1.25%]",0.0746,0.0,0.2091
MLP,0.0028,5.6291,"[-29.59%, 20.40%]",0.2685,259.7914,0.0056

network 0, training 8, epoch 1: train scaled MSE 0.843479; val RMSE 0.01941152; lr 0.001; 0s
network 0, training 8, epoch 10: train scaled MSE 0.0262222; val RMSE 0.003148945; lr 0.001; 2s
network 0, training 8, epoch 20: train scaled MSE 0.013858; val RMSE 0.002325613; lr 0.001; 4s
network 0, training 8, epoch 30: train scaled MSE 0.00871028; val RMSE 0.002260057; lr 0.001; 6s
network 0, training 8, epoch 40: train scaled MSE 0.00981378; val RMSE 0.002047406; lr 0.001; 8s
network 0, training 8, epoch 50: train scaled MSE 0.00389706; val RMSE 0.001767033; lr 0.001; 10s
network 0, training 8, epoch 60: train scaled MSE 0.00353833; val RMSE 0.001695431; lr 0.001; 12s
network 0, training 8, epoch 70: train scaled MSE 0.00277568; val RMSE 0.001681102; lr 0.001; 14s
network 0, training 8, epoch 80: train scaled MSE 0.0023878; val RMSE 0.001988687; lr 0.001; 16s
network 0, training 8, epoch 90: train scaled MSE 0.0020073; val RMSE 0.00235953; lr 0.001; 18s
network 0, training 8, epoch 100: train scaled MSE 0.00194932; val RMSE 0.001586975; lr 0.0005; 20s
network 0, training 8, epoch 110: train scaled MSE 0.00151023; val RMSE 0.001576028; lr 0.0005; 22s
network 0, training 8, epoch 120: train scaled MSE 0.00124858; val RMSE 0.00173129; lr 0.0005; 24s
network 0, training 8, epoch 130: train scaled MSE 0.00111021; val RMSE 0.001546913; lr 0.0005; 26s
network 0, training 8, epoch 140: train scaled MSE 0.00106356; val RMSE 0.001548338; lr 0.0005; 28s
network 0, training 8, epoch 150: train scaled MSE 0.00116669; val RMSE 0.001680581; lr 0.0005; 30s
network 0, training 8, epoch 160: train scaled MSE 0.000840307; val RMSE 0.001522793; lr 0.0005; 32s
network 0, training 8, epoch 170: train scaled MSE 0.000759472; val RMSE 0.00152152; lr 0.00025; 34s
network 0, training 8, epoch 180: train scaled MSE 0.000690205; val RMSE 0.001486689; lr 0.00025; 36s
network 0, training 8, epoch 190: train scaled MSE 0.000637525; val RMSE 0.001485956; lr 0.00025; 38s
network 0, training 8, epoch 200: train scaled MSE 0.000638183; val RMSE 0.001488127; lr 0.00025; 40s
network 0, training 8, epoch 210: train scaled MSE 0.000611332; val RMSE 0.001483165; lr 0.00025; 42s
network 0, training 8, epoch 220: train scaled MSE 0.000554893; val RMSE 0.001509638; lr 0.000125; 44s
network 0, training 8, epoch 230: train scaled MSE 0.000508439; val RMSE 0.001482393; lr 0.000125; 46s
network 0, training 8, epoch 240: train scaled MSE 0.000494373; val RMSE 0.001479014; lr 6.25e-05; 48s
network 0, training 8, epoch 250: train scaled MSE 0.000478711; val RMSE 0.001480428; lr 6.25e-05; 50s
network 0, training 8, epoch 260: train scaled MSE 0.000470677; val RMSE 0.001482736; lr 6.25e-05; 52s
network 0, training 8, epoch 270: train scaled MSE 0.000494186; val RMSE 0.001475869; lr 6.25e-05; 54s
network 0, training 8, epoch 280: train scaled MSE 0.000480028; val RMSE 0.00147381; lr 6.25e-05; 56s
network 0, training 8, epoch 290: train scaled MSE 0.000445985; val RMSE 0.001480914; lr 6.25e-05; 58s
network 0, training 8, epoch 300: train scaled MSE 0.000446201; val RMSE 0.001471272; lr 6.25e-05; 60s
network 0, training 8, epoch 310: train scaled MSE 0.000433274; val RMSE 0.001466263; lr 6.25e-05; 62s
network 0, training 8, epoch 320: train scaled MSE 0.000429223; val RMSE 0.00146616; lr 6.25e-05; 64s
network 0, training 8, epoch 330: train scaled MSE 0.000415353; val RMSE 0.001467891; lr 6.25e-05; 66s
network 0, training 8, epoch 340: train scaled MSE 0.000470646; val RMSE 0.001469678; lr 6.25e-05; 68s
network 0, training 8, epoch 350: train scaled MSE 0.000403791; val RMSE 0.001461719; lr 6.25e-05; 70s
network 0, training 8, epoch 360: train scaled MSE 0.000453266; val RMSE 0.001465811; lr 6.25e-05; 72s
network 0, training 8, epoch 370: train scaled MSE 0.000377492; val RMSE 0.001459108; lr 3.125e-05; 74s
network 0, training 8, epoch 380: train scaled MSE 0.000374455; val RMSE 0.001459921; lr 3.125e-05; 76s
network 0, training 8, epoch 390: train scaled MSE 0.000372926; val RMSE 0.001458963; lr 3.125e-05; 78s
network 0, training 8, epoch 400: train scaled MSE 0.000368387; val RMSE 0.001457083; lr 3.125e-05; 80s
network 0, training 8, epoch 410: train scaled MSE 0.000365451; val RMSE 0.001460613; lr 3.125e-05; 82s
network 0, training 8, epoch 420: train scaled MSE 0.00036233; val RMSE 0.001456368; lr 3.125e-05; 84s
network 0, training 8, epoch 430: train scaled MSE 0.000355628; val RMSE 0.001457455; lr 1.5625e-05; 86s
network 0, training 8, epoch 440: train scaled MSE 0.00035195; val RMSE 0.001455702; lr 1e-05; 88s
network 0, training 8, epoch 450: train scaled MSE 0.00035419; val RMSE 0.001455665; lr 1e-05; 90s
network 0, training 8, epoch 460: train scaled MSE 0.000350072; val RMSE 0.001456023; lr 1e-05; 93s
network 0, training 8, epoch 470: train scaled MSE 0.000349328; val RMSE 0.001456402; lr 1e-05; 95s
network 0, training 8, epoch 480: train scaled MSE 0.00034828; val RMSE 0.001455748; lr 1e-05; 97s
Standard Linear Baseline Validation RMSE: 0.001381029

Network seed 0, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0030,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0030,0.7996,"[-2.42%, 1.86%]",0.0965,0.0,0.1808
MLP,0.0027,18.9087,"[-11.19%, 32.98%]",0.4355,351.4068,0.1171

network 0, training 9, epoch 1: train scaled MSE 0.852524; val RMSE 0.01955941; lr 0.001; 0s
network 0, training 9, epoch 10: train scaled MSE 0.0526644; val RMSE 0.004425615; lr 0.001; 2s
network 0, training 9, epoch 20: train scaled MSE 0.0255954; val RMSE 0.00375379; lr 0.001; 4s
network 0, training 9, epoch 30: train scaled MSE 0.0195013; val RMSE 0.002985368; lr 0.001; 6s
network 0, training 9, epoch 40: train scaled MSE 0.00919689; val RMSE 0.003010118; lr 0.001; 8s
network 0, training 9, epoch 50: train scaled MSE 0.00516359; val RMSE 0.002991381; lr 0.001; 10s
network 0, training 9, epoch 60: train scaled MSE 0.0043521; val RMSE 0.002749561; lr 0.001; 12s
network 0, training 9, epoch 70: train scaled MSE 0.00377163; val RMSE 0.002751491; lr 0.001; 14s
network 0, training 9, epoch 80: train scaled MSE 0.00540222; val RMSE 0.002814489; lr 0.001; 16s
network 0, training 9, epoch 90: train scaled MSE 0.00232029; val RMSE 0.002677252; lr 0.0005; 18s
network 0, training 9, epoch 100: train scaled MSE 0.00208048; val RMSE 0.002646172; lr 0.0005; 20s
network 0, training 9, epoch 110: train scaled MSE 0.00191098; val RMSE 0.002638265; lr 0.0005; 22s
network 0, training 9, epoch 120: train scaled MSE 0.00168262; val RMSE 0.002624543; lr 0.00025; 24s
network 0, training 9, epoch 130: train scaled MSE 0.00189596; val RMSE 0.002644893; lr 0.00025; 26s
network 0, training 9, epoch 140: train scaled MSE 0.00142809; val RMSE 0.002619345; lr 0.00025; 28s
network 0, training 9, epoch 150: train scaled MSE 0.00134775; val RMSE 0.002608937; lr 0.000125; 30s
network 0, training 9, epoch 160: train scaled MSE 0.00130876; val RMSE 0.00260662; lr 0.000125; 32s
network 0, training 9, epoch 170: train scaled MSE 0.00126256; val RMSE 0.002603888; lr 0.000125; 34s
network 0, training 9, epoch 180: train scaled MSE 0.00122604; val RMSE 0.002630559; lr 0.000125; 36s
network 0, training 9, epoch 190: train scaled MSE 0.00118931; val RMSE 0.002606668; lr 0.000125; 38s
network 0, training 9, epoch 200: train scaled MSE 0.00113555; val RMSE 0.002600119; lr 0.000125; 39s
network 0, training 9, epoch 210: train scaled MSE 0.00110075; val RMSE 0.002601178; lr 0.000125; 41s
network 0, training 9, epoch 220: train scaled MSE 0.00189405; val RMSE 0.002608968; lr 0.000125; 43s
network 0, training 9, epoch 230: train scaled MSE 0.000992831; val RMSE 0.002600615; lr 6.25e-05; 45s
network 0, training 9, epoch 240: train scaled MSE 0.0009753; val RMSE 0.002597103; lr 6.25e-05; 47s
network 0, training 9, epoch 250: train scaled MSE 0.000960469; val RMSE 0.002597791; lr 6.25e-05; 49s
network 0, training 9, epoch 260: train scaled MSE 0.000932788; val RMSE 0.002603842; lr 6.25e-05; 51s
network 0, training 9, epoch 270: train scaled MSE 0.00091568; val RMSE 0.002596938; lr 6.25e-05; 53s
network 0, training 9, epoch 280: train scaled MSE 0.000892746; val RMSE 0.002593825; lr 6.25e-05; 55s
network 0, training 9, epoch 290: train scaled MSE 0.000861328; val RMSE 0.00259193; lr 3.125e-05; 57s
network 0, training 9, epoch 300: train scaled MSE 0.000861182; val RMSE 0.00259619; lr 3.125e-05; 59s
network 0, training 9, epoch 310: train scaled MSE 0.000838596; val RMSE 0.002593342; lr 1.5625e-05; 61s
network 0, training 9, epoch 320: train scaled MSE 0.000832365; val RMSE 0.002592197; lr 1e-05; 63s
network 0, training 9, epoch 330: train scaled MSE 0.000825472; val RMSE 0.002592329; lr 1e-05; 64s
Standard Linear Baseline Validation RMSE: 0.002584832

Network seed 0, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0025,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0025,-0.5280,"[-5.27%, 1.55%]",0.0764,0.0,0.1401
MLP,0.0024,1.7633,"[-15.06%, 12.40%]",0.2480,224.4573,0.0070

Network 1: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   17.9s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   18.0s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   18.1s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   18.2s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   18.4s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   18.6s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   18.7s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   18.8s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   18.9s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   19.2s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   19.3s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   19.5s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   19.8s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   20.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   20.2s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   20.4s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   20.7s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   20.9s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   21.2s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   21.4s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   21.6s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   21.9s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   22.2s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   22.5s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   22.7s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   23.1s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   23.4s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   23.7s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   24.0s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   24.4s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   24.7s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   25.0s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   25.3s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   26.1s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   26.5s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   26.8s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   27.2s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   27.5s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   27.9s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   28.4s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   28.8s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   29.2s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   29.6s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   30.0s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   31.0s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   31.5s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   32.1s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   32.6s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   33.0s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   33.5s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   34.0s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   34.6s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   35.1s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   35.6s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   36.2s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   36.8s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   37.3s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   37.9s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   38.5s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   39.2s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   39.8s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   40.3s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   40.8s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   41.4s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   42.0s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   42.7s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   43.2s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   43.9s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   44.6s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   45.2s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   45.9s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   46.6s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   47.3s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   48.0s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   48.7s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   49.5s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   50.3s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   51.1s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   51.8s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   52.6s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   53.3s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   54.2s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:   54.9s
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:   55.7s
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:   56.6s
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:   57.3s
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:   58.1s
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:   58.9s
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:   59.7s
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.7min finished

network 1, training 0, epoch 1: train scaled MSE 0.819415; val RMSE 0.02760191; lr 0.001; 0s
network 1, training 0, epoch 10: train scaled MSE 0.049405; val RMSE 0.006175021; lr 0.001; 2s
network 1, training 0, epoch 20: train scaled MSE 0.0322659; val RMSE 0.004540659; lr 0.001; 4s
network 1, training 0, epoch 30: train scaled MSE 0.0250941; val RMSE 0.004555118; lr 0.001; 6s
network 1, training 0, epoch 40: train scaled MSE 0.0138547; val RMSE 0.004190061; lr 0.001; 8s
network 1, training 0, epoch 50: train scaled MSE 0.00815971; val RMSE 0.004241218; lr 0.001; 10s
network 1, training 0, epoch 60: train scaled MSE 0.0061784; val RMSE 0.004266496; lr 0.001; 12s
network 1, training 0, epoch 70: train scaled MSE 0.00382853; val RMSE 0.004708351; lr 0.001; 14s
network 1, training 0, epoch 80: train scaled MSE 0.00435317; val RMSE 0.004044532; lr 0.0005; 16s
network 1, training 0, epoch 90: train scaled MSE 0.0021279; val RMSE 0.004022444; lr 0.0005; 18s
network 1, training 0, epoch 100: train scaled MSE 0.00176218; val RMSE 0.00400122; lr 0.0005; 20s
network 1, training 0, epoch 110: train scaled MSE 0.00294783; val RMSE 0.004169233; lr 0.0005; 22s
network 1, training 0, epoch 120: train scaled MSE 0.00134217; val RMSE 0.003975911; lr 0.00025; 24s
network 1, training 0, epoch 130: train scaled MSE 0.00126013; val RMSE 0.003975256; lr 0.00025; 26s
network 1, training 0, epoch 140: train scaled MSE 0.001186; val RMSE 0.003982446; lr 0.00025; 28s
network 1, training 0, epoch 150: train scaled MSE 0.0013337; val RMSE 0.00398423; lr 0.00025; 30s
network 1, training 0, epoch 160: train scaled MSE 0.00104863; val RMSE 0.003970992; lr 0.00025; 32s
network 1, training 0, epoch 170: train scaled MSE 0.00100229; val RMSE 0.003946229; lr 0.000125; 34s
network 1, training 0, epoch 180: train scaled MSE 0.000917691; val RMSE 0.003955649; lr 0.000125; 36s
network 1, training 0, epoch 190: train scaled MSE 0.000881288; val RMSE 0.003952447; lr 6.25e-05; 38s
network 1, training 0, epoch 200: train scaled MSE 0.000865474; val RMSE 0.003955422; lr 3.125e-05; 40s
network 1, training 0, epoch 210: train scaled MSE 0.00085846; val RMSE 0.003956774; lr 1.5625e-05; 42s
Standard Linear Baseline Validation RMSE: 0.003270661

Network seed 1, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0039,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0039,-0.5499,"[-3.32%, 0.93%]",0.0894,0.0,0.0127
MLP,0.0043,-25.0802,"[-43.83%, -9.31%]",0.1652,84.6924,0.0044

network 1, training 1, epoch 1: train scaled MSE 0.830901; val RMSE 0.02832599; lr 0.001; 0s
network 1, training 1, epoch 10: train scaled MSE 0.0367369; val RMSE 0.006794709; lr 0.001; 2s
network 1, training 1, epoch 20: train scaled MSE 0.0185402; val RMSE 0.005460924; lr 0.001; 4s
network 1, training 1, epoch 30: train scaled MSE 0.0112334; val RMSE 0.005108613; lr 0.001; 6s
network 1, training 1, epoch 40: train scaled MSE 0.00802795; val RMSE 0.005005046; lr 0.001; 8s
network 1, training 1, epoch 50: train scaled MSE 0.00878964; val RMSE 0.005311524; lr 0.001; 10s
network 1, training 1, epoch 60: train scaled MSE 0.00527577; val RMSE 0.005136307; lr 0.0005; 12s
network 1, training 1, epoch 70: train scaled MSE 0.00444263; val RMSE 0.00508675; lr 0.00025; 14s
network 1, training 1, epoch 80: train scaled MSE 0.00405427; val RMSE 0.005054261; lr 0.000125; 16s
Standard Linear Baseline Validation RMSE: 0.005131192

Network seed 1, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0042,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0042,-0.2669,"[-1.90%, 0.75%]",0.0726,0.0,0.0151
MLP,0.0047,-25.7435,"[-45.20%, -9.71%]",0.0818,12.6069,0.0046

network 1, training 2, epoch 1: train scaled MSE 0.8498; val RMSE 0.02838453; lr 0.001; 0s
network 1, training 2, epoch 10: train scaled MSE 0.032373; val RMSE 0.005834817; lr 0.001; 2s
network 1, training 2, epoch 20: train scaled MSE 0.0186834; val RMSE 0.003441095; lr 0.001; 4s
network 1, training 2, epoch 30: train scaled MSE 0.0141333; val RMSE 0.003703697; lr 0.001; 6s
network 1, training 2, epoch 40: train scaled MSE 0.00997936; val RMSE 0.003280944; lr 0.001; 8s
network 1, training 2, epoch 50: train scaled MSE 0.0064628; val RMSE 0.003080044; lr 0.001; 10s
network 1, training 2, epoch 60: train scaled MSE 0.00422081; val RMSE 0.003060857; lr 0.001; 12s
network 1, training 2, epoch 70: train scaled MSE 0.00307453; val RMSE 0.002824875; lr 0.001; 14s
network 1, training 2, epoch 80: train scaled MSE 0.0022682; val RMSE 0.002758874; lr 0.001; 17s
network 1, training 2, epoch 90: train scaled MSE 0.00192582; val RMSE 0.002807422; lr 0.001; 19s
network 1, training 2, epoch 100: train scaled MSE 0.00146341; val RMSE 0.00290899; lr 0.001; 21s
network 1, training 2, epoch 110: train scaled MSE 0.00209098; val RMSE 0.002749876; lr 0.001; 23s
network 1, training 2, epoch 120: train scaled MSE 0.000834388; val RMSE 0.002658338; lr 0.0005; 25s
network 1, training 2, epoch 130: train scaled MSE 0.000761723; val RMSE 0.002652002; lr 0.0005; 27s
network 1, training 2, epoch 140: train scaled MSE 0.000750381; val RMSE 0.002650576; lr 0.0005; 29s
network 1, training 2, epoch 150: train scaled MSE 0.000615998; val RMSE 0.002631025; lr 0.00025; 31s
network 1, training 2, epoch 160: train scaled MSE 0.00055298; val RMSE 0.002623378; lr 0.000125; 33s
network 1, training 2, epoch 170: train scaled MSE 0.000536593; val RMSE 0.002625368; lr 0.000125; 35s
network 1, training 2, epoch 180: train scaled MSE 0.000511978; val RMSE 0.002623126; lr 6.25e-05; 37s
network 1, training 2, epoch 190: train scaled MSE 0.000501892; val RMSE 0.002625676; lr 6.25e-05; 39s
network 1, training 2, epoch 200: train scaled MSE 0.000486325; val RMSE 0.002618407; lr 3.125e-05; 41s
network 1, training 2, epoch 210: train scaled MSE 0.000480451; val RMSE 0.002618877; lr 3.125e-05; 43s
network 1, training 2, epoch 220: train scaled MSE 0.000474479; val RMSE 0.002618641; lr 3.125e-05; 45s
network 1, training 2, epoch 230: train scaled MSE 0.000472178; val RMSE 0.002620672; lr 3.125e-05; 47s
network 1, training 2, epoch 240: train scaled MSE 0.000463849; val RMSE 0.002618426; lr 1.5625e-05; 49s
network 1, training 2, epoch 250: train scaled MSE 0.000457486; val RMSE 0.002617362; lr 1e-05; 51s
network 1, training 2, epoch 260: train scaled MSE 0.000452528; val RMSE 0.002617165; lr 1e-05; 53s
network 1, training 2, epoch 270: train scaled MSE 0.000450436; val RMSE 0.002616763; lr 1e-05; 55s
network 1, training 2, epoch 280: train scaled MSE 0.000448441; val RMSE 0.002616384; lr 1e-05; 57s
network 1, training 2, epoch 290: train scaled MSE 0.000446937; val RMSE 0.002616776; lr 1e-05; 59s
network 1, training 2, epoch 300: train scaled MSE 0.00044468; val RMSE 0.002616804; lr 1e-05; 61s
network 1, training 2, epoch 310: train scaled MSE 0.000442916; val RMSE 0.002616897; lr 1e-05; 63s
network 1, training 2, epoch 320: train scaled MSE 0.000441071; val RMSE 0.002615948; lr 1e-05; 65s
network 1, training 2, epoch 330: train scaled MSE 0.000439791; val RMSE 0.002616482; lr 1e-05; 67s
network 1, training 2, epoch 340: train scaled MSE 0.00043953; val RMSE 0.00261687; lr 1e-05; 69s
network 1, training 2, epoch 350: train scaled MSE 0.000436055; val RMSE 0.002615772; lr 1e-05; 71s
network 1, training 2, epoch 360: train scaled MSE 0.00043393; val RMSE 0.002616034; lr 1e-05; 73s
network 1, training 2, epoch 370: train scaled MSE 0.000437228; val RMSE 0.002615664; lr 1e-05; 75s
network 1, training 2, epoch 380: train scaled MSE 0.000430986; val RMSE 0.002615757; lr 1e-05; 77s
network 1, training 2, epoch 390: train scaled MSE 0.000428485; val RMSE 0.002615342; lr 1e-05; 79s
network 1, training 2, epoch 400: train scaled MSE 0.000434781; val RMSE 0.002616532; lr 1e-05; 80s
network 1, training 2, epoch 410: train scaled MSE 0.000427773; val RMSE 0.002615032; lr 1e-05; 82s
network 1, training 2, epoch 420: train scaled MSE 0.000424238; val RMSE 0.002614952; lr 1e-05; 84s
network 1, training 2, epoch 430: train scaled MSE 0.00042398; val RMSE 0.002615066; lr 1e-05; 86s
network 1, training 2, epoch 440: train scaled MSE 0.000421208; val RMSE 0.002614871; lr 1e-05; 88s
network 1, training 2, epoch 450: train scaled MSE 0.000419483; val RMSE 0.002614598; lr 1e-05; 90s
network 1, training 2, epoch 460: train scaled MSE 0.000417642; val RMSE 0.002614994; lr 1e-05; 92s
network 1, training 2, epoch 470: train scaled MSE 0.000423834; val RMSE 0.002615446; lr 1e-05; 94s
network 1, training 2, epoch 480: train scaled MSE 0.000414141; val RMSE 0.00261437; lr 1e-05; 96s
network 1, training 2, epoch 490: train scaled MSE 0.000412183; val RMSE 0.002614138; lr 1e-05; 98s
network 1, training 2, epoch 500: train scaled MSE 0.000410982; val RMSE 0.002613552; lr 1e-05; 100s
network 1, training 2, epoch 510: train scaled MSE 0.000408653; val RMSE 0.002613667; lr 1e-05; 102s
network 1, training 2, epoch 520: train scaled MSE 0.000406719; val RMSE 0.00261353; lr 1e-05; 104s
network 1, training 2, epoch 530: train scaled MSE 0.000404902; val RMSE 0.002614047; lr 1e-05; 106s
network 1, training 2, epoch 540: train scaled MSE 0.000403128; val RMSE 0.002614045; lr 1e-05; 108s
network 1, training 2, epoch 550: train scaled MSE 0.000402184; val RMSE 0.002613784; lr 1e-05; 110s
network 1, training 2, epoch 560: train scaled MSE 0.000399589; val RMSE 0.002614033; lr 1e-05; 112s
network 1, training 2, epoch 570: train scaled MSE 0.00039746; val RMSE 0.00261346; lr 1e-05; 114s
network 1, training 2, epoch 580: train scaled MSE 0.000396375; val RMSE 0.002613807; lr 1e-05; 116s
network 1, training 2, epoch 590: train scaled MSE 0.00039675; val RMSE 0.002613935; lr 1e-05; 118s
network 1, training 2, epoch 600: train scaled MSE 0.000392448; val RMSE 0.002613732; lr 1e-05; 120s
network 1, training 2, epoch 610: train scaled MSE 0.000390894; val RMSE 0.002613452; lr 1e-05; 122s
network 1, training 2, epoch 620: train scaled MSE 0.000389655; val RMSE 0.00261294; lr 1e-05; 124s
network 1, training 2, epoch 630: train scaled MSE 0.00038753; val RMSE 0.00261315; lr 1e-05; 125s
network 1, training 2, epoch 640: train scaled MSE 0.000386133; val RMSE 0.002612897; lr 1e-05; 127s
network 1, training 2, epoch 650: train scaled MSE 0.000385012; val RMSE 0.002613751; lr 1e-05; 129s
network 1, training 2, epoch 660: train scaled MSE 0.000384021; val RMSE 0.002613777; lr 1e-05; 131s
Standard Linear Baseline Validation RMSE: 0.002602298

Network seed 1, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0044,-1.7442,"[-4.23%, -0.42%]",0.0610,0.0,0.0126
MLP,0.0044,-3.9299,"[-14.96%, 4.80%]",0.2407,294.7059,0.0071

network 1, training 3, epoch 1: train scaled MSE 0.843643; val RMSE 0.02659597; lr 0.001; 0s
network 1, training 3, epoch 10: train scaled MSE 0.0278131; val RMSE 0.005795207; lr 0.001; 2s
network 1, training 3, epoch 20: train scaled MSE 0.0173204; val RMSE 0.004335033; lr 0.001; 4s
network 1, training 3, epoch 30: train scaled MSE 0.010339; val RMSE 0.003778562; lr 0.001; 6s
network 1, training 3, epoch 40: train scaled MSE 0.0069577; val RMSE 0.003664895; lr 0.001; 8s
network 1, training 3, epoch 50: train scaled MSE 0.00485143; val RMSE 0.003643706; lr 0.001; 10s
network 1, training 3, epoch 60: train scaled MSE 0.0033631; val RMSE 0.003660295; lr 0.001; 12s
network 1, training 3, epoch 70: train scaled MSE 0.00342754; val RMSE 0.003620442; lr 0.0005; 14s
network 1, training 3, epoch 80: train scaled MSE 0.00178884; val RMSE 0.003577946; lr 0.00025; 16s
network 1, training 3, epoch 90: train scaled MSE 0.00307278; val RMSE 0.003589516; lr 0.00025; 18s
network 1, training 3, epoch 100: train scaled MSE 0.00139176; val RMSE 0.003569861; lr 0.000125; 20s
network 1, training 3, epoch 110: train scaled MSE 0.0013065; val RMSE 0.003565762; lr 0.000125; 22s
network 1, training 3, epoch 120: train scaled MSE 0.0012162; val RMSE 0.003563577; lr 0.000125; 24s
network 1, training 3, epoch 130: train scaled MSE 0.00114587; val RMSE 0.003558282; lr 0.000125; 26s
network 1, training 3, epoch 140: train scaled MSE 0.00106863; val RMSE 0.00355885; lr 0.000125; 28s
network 1, training 3, epoch 150: train scaled MSE 0.000997303; val RMSE 0.003546541; lr 0.000125; 30s
network 1, training 3, epoch 160: train scaled MSE 0.000924751; val RMSE 0.003542937; lr 0.000125; 32s
network 1, training 3, epoch 170: train scaled MSE 0.000879058; val RMSE 0.003538453; lr 0.000125; 34s
network 1, training 3, epoch 180: train scaled MSE 0.000809819; val RMSE 0.003544049; lr 0.000125; 36s
network 1, training 3, epoch 190: train scaled MSE 0.000760876; val RMSE 0.003531947; lr 6.25e-05; 38s
network 1, training 3, epoch 200: train scaled MSE 0.00073487; val RMSE 0.003533274; lr 6.25e-05; 40s
network 1, training 3, epoch 210: train scaled MSE 0.000709744; val RMSE 0.003527939; lr 3.125e-05; 42s
network 1, training 3, epoch 220: train scaled MSE 0.00069312; val RMSE 0.003526371; lr 3.125e-05; 44s
network 1, training 3, epoch 230: train scaled MSE 0.000687503; val RMSE 0.00352533; lr 3.125e-05; 46s
network 1, training 3, epoch 240: train scaled MSE 0.000679314; val RMSE 0.003524273; lr 3.125e-05; 48s
network 1, training 3, epoch 250: train scaled MSE 0.000667736; val RMSE 0.003523164; lr 3.125e-05; 50s
network 1, training 3, epoch 260: train scaled MSE 0.000653803; val RMSE 0.00352361; lr 3.125e-05; 52s
network 1, training 3, epoch 270: train scaled MSE 0.000645375; val RMSE 0.003520784; lr 3.125e-05; 54s
network 1, training 3, epoch 280: train scaled MSE 0.000656159; val RMSE 0.003522181; lr 3.125e-05; 56s
network 1, training 3, epoch 290: train scaled MSE 0.000625447; val RMSE 0.003518783; lr 3.125e-05; 58s
network 1, training 3, epoch 300: train scaled MSE 0.000617699; val RMSE 0.003519331; lr 3.125e-05; 60s
network 1, training 3, epoch 310: train scaled MSE 0.000612841; val RMSE 0.003521833; lr 3.125e-05; 62s
network 1, training 3, epoch 320: train scaled MSE 0.000595977; val RMSE 0.003516653; lr 1.5625e-05; 64s
network 1, training 3, epoch 330: train scaled MSE 0.000593022; val RMSE 0.003514949; lr 1.5625e-05; 66s
network 1, training 3, epoch 340: train scaled MSE 0.000587052; val RMSE 0.003516274; lr 1.5625e-05; 68s
network 1, training 3, epoch 350: train scaled MSE 0.000588402; val RMSE 0.003515497; lr 1e-05; 70s
network 1, training 3, epoch 360: train scaled MSE 0.000579461; val RMSE 0.003515292; lr 1e-05; 72s
network 1, training 3, epoch 370: train scaled MSE 0.000576204; val RMSE 0.00351431; lr 1e-05; 74s
network 1, training 3, epoch 380: train scaled MSE 0.000573511; val RMSE 0.00351395; lr 1e-05; 76s
network 1, training 3, epoch 390: train scaled MSE 0.000570703; val RMSE 0.003513835; lr 1e-05; 78s
network 1, training 3, epoch 400: train scaled MSE 0.000567221; val RMSE 0.003513163; lr 1e-05; 80s
network 1, training 3, epoch 410: train scaled MSE 0.00056639; val RMSE 0.003512889; lr 1e-05; 82s
network 1, training 3, epoch 420: train scaled MSE 0.000560922; val RMSE 0.003512183; lr 1e-05; 84s
network 1, training 3, epoch 430: train scaled MSE 0.000557674; val RMSE 0.003511962; lr 1e-05; 86s
network 1, training 3, epoch 440: train scaled MSE 0.000557023; val RMSE 0.003512124; lr 1e-05; 88s
network 1, training 3, epoch 450: train scaled MSE 0.000551728; val RMSE 0.003511578; lr 1e-05; 89s
network 1, training 3, epoch 460: train scaled MSE 0.000548824; val RMSE 0.003511484; lr 1e-05; 91s
network 1, training 3, epoch 470: train scaled MSE 0.00054597; val RMSE 0.00350997; lr 1e-05; 93s
network 1, training 3, epoch 480: train scaled MSE 0.00054602; val RMSE 0.003511763; lr 1e-05; 95s
network 1, training 3, epoch 490: train scaled MSE 0.000540426; val RMSE 0.003509023; lr 1e-05; 97s
network 1, training 3, epoch 500: train scaled MSE 0.000536979; val RMSE 0.003510214; lr 1e-05; 99s
network 1, training 3, epoch 510: train scaled MSE 0.000533943; val RMSE 0.003509439; lr 1e-05; 101s
network 1, training 3, epoch 520: train scaled MSE 0.000531271; val RMSE 0.003509646; lr 1e-05; 104s
network 1, training 3, epoch 530: train scaled MSE 0.000528131; val RMSE 0.003507786; lr 1e-05; 106s
network 1, training 3, epoch 540: train scaled MSE 0.000526309; val RMSE 0.003509218; lr 1e-05; 108s
network 1, training 3, epoch 550: train scaled MSE 0.000525148; val RMSE 0.003508587; lr 1e-05; 109s
network 1, training 3, epoch 560: train scaled MSE 0.000520472; val RMSE 0.003508045; lr 1e-05; 111s
network 1, training 3, epoch 570: train scaled MSE 0.00051705; val RMSE 0.003507681; lr 1e-05; 113s
Standard Linear Baseline Validation RMSE: 0.003469373

Network seed 1, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0044,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0044,-0.0514,"[-1.76%, 1.15%]",0.0817,0.0,0.0138
MLP,0.0044,-0.2146,"[-15.31%, 11.93%]",0.2803,242.9468,0.0069

network 1, training 4, epoch 1: train scaled MSE 0.82757; val RMSE 0.02875587; lr 0.001; 0s
network 1, training 4, epoch 10: train scaled MSE 0.0408263; val RMSE 0.005679432; lr 0.001; 2s
network 1, training 4, epoch 20: train scaled MSE 0.0252973; val RMSE 0.004120925; lr 0.001; 4s
network 1, training 4, epoch 30: train scaled MSE 0.0150928; val RMSE 0.004242871; lr 0.001; 6s
network 1, training 4, epoch 40: train scaled MSE 0.00882501; val RMSE 0.003917656; lr 0.001; 8s
network 1, training 4, epoch 50: train scaled MSE 0.00533888; val RMSE 0.003775082; lr 0.001; 10s
network 1, training 4, epoch 60: train scaled MSE 0.00973605; val RMSE 0.004124626; lr 0.001; 12s
network 1, training 4, epoch 70: train scaled MSE 0.00327543; val RMSE 0.003746043; lr 0.001; 14s
network 1, training 4, epoch 80: train scaled MSE 0.00441366; val RMSE 0.003625733; lr 0.001; 16s
network 1, training 4, epoch 90: train scaled MSE 0.00188796; val RMSE 0.003543845; lr 0.0005; 18s
network 1, training 4, epoch 100: train scaled MSE 0.00175235; val RMSE 0.003482733; lr 0.0005; 19s
network 1, training 4, epoch 110: train scaled MSE 0.0014596; val RMSE 0.003469362; lr 0.00025; 21s
network 1, training 4, epoch 120: train scaled MSE 0.00136104; val RMSE 0.003454921; lr 0.00025; 23s
network 1, training 4, epoch 130: train scaled MSE 0.001274; val RMSE 0.003486291; lr 0.00025; 25s
network 1, training 4, epoch 140: train scaled MSE 0.00117803; val RMSE 0.003441789; lr 0.000125; 27s
network 1, training 4, epoch 150: train scaled MSE 0.00109605; val RMSE 0.003441708; lr 0.000125; 29s
network 1, training 4, epoch 160: train scaled MSE 0.00103599; val RMSE 0.003441496; lr 0.000125; 31s
network 1, training 4, epoch 170: train scaled MSE 0.000979415; val RMSE 0.003433145; lr 6.25e-05; 33s
network 1, training 4, epoch 180: train scaled MSE 0.000957014; val RMSE 0.003433539; lr 6.25e-05; 35s
network 1, training 4, epoch 190: train scaled MSE 0.00093419; val RMSE 0.003429473; lr 6.25e-05; 37s
network 1, training 4, epoch 200: train scaled MSE 0.000919864; val RMSE 0.003427025; lr 6.25e-05; 39s
network 1, training 4, epoch 210: train scaled MSE 0.000875663; val RMSE 0.00342893; lr 3.125e-05; 41s
network 1, training 4, epoch 220: train scaled MSE 0.000861595; val RMSE 0.003425517; lr 1.5625e-05; 43s
network 1, training 4, epoch 230: train scaled MSE 0.000856937; val RMSE 0.003426769; lr 1.5625e-05; 45s
Standard Linear Baseline Validation RMSE: 0.003491404

Network seed 1, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,0.0859,"[-1.69%, 1.15%]",0.0843,0.0,0.0152
MLP,0.0046,-12.1051,"[-29.63%, 3.21%]",0.1979,134.6219,0.0067

network 1, training 5, epoch 1: train scaled MSE 0.821014; val RMSE 0.02755958; lr 0.001; 0s
network 1, training 5, epoch 10: train scaled MSE 0.0426192; val RMSE 0.006824705; lr 0.001; 2s
network 1, training 5, epoch 20: train scaled MSE 0.0284705; val RMSE 0.005499061; lr 0.001; 4s
network 1, training 5, epoch 30: train scaled MSE 0.0172877; val RMSE 0.005684276; lr 0.001; 6s
network 1, training 5, epoch 40: train scaled MSE 0.0186461; val RMSE 0.009800671; lr 0.001; 8s
network 1, training 5, epoch 50: train scaled MSE 0.00851516; val RMSE 0.004771993; lr 0.001; 10s
network 1, training 5, epoch 60: train scaled MSE 0.0056441; val RMSE 0.004736063; lr 0.0005; 12s
network 1, training 5, epoch 70: train scaled MSE 0.00466315; val RMSE 0.004749016; lr 0.0005; 14s
network 1, training 5, epoch 80: train scaled MSE 0.00382735; val RMSE 0.004731694; lr 0.00025; 16s
network 1, training 5, epoch 90: train scaled MSE 0.00343401; val RMSE 0.004717291; lr 0.00025; 19s
network 1, training 5, epoch 100: train scaled MSE 0.00321792; val RMSE 0.004744822; lr 0.00025; 21s
network 1, training 5, epoch 110: train scaled MSE 0.00277948; val RMSE 0.004702498; lr 0.000125; 23s
network 1, training 5, epoch 120: train scaled MSE 0.00261994; val RMSE 0.004699208; lr 0.000125; 25s
network 1, training 5, epoch 130: train scaled MSE 0.00246846; val RMSE 0.004689927; lr 6.25e-05; 28s
network 1, training 5, epoch 140: train scaled MSE 0.00242605; val RMSE 0.004687739; lr 6.25e-05; 30s
network 1, training 5, epoch 150: train scaled MSE 0.00233556; val RMSE 0.004689979; lr 6.25e-05; 32s
network 1, training 5, epoch 160: train scaled MSE 0.00225708; val RMSE 0.00468395; lr 3.125e-05; 34s
network 1, training 5, epoch 170: train scaled MSE 0.00221635; val RMSE 0.004685683; lr 3.125e-05; 36s
network 1, training 5, epoch 180: train scaled MSE 0.00218097; val RMSE 0.004683884; lr 1.5625e-05; 38s
network 1, training 5, epoch 190: train scaled MSE 0.00216271; val RMSE 0.004683027; lr 1.5625e-05; 40s
network 1, training 5, epoch 200: train scaled MSE 0.00213642; val RMSE 0.004680659; lr 1.5625e-05; 42s
network 1, training 5, epoch 210: train scaled MSE 0.00211357; val RMSE 0.004681113; lr 1.5625e-05; 45s
network 1, training 5, epoch 220: train scaled MSE 0.00209756; val RMSE 0.004678126; lr 1.5625e-05; 47s
network 1, training 5, epoch 230: train scaled MSE 0.00206835; val RMSE 0.004679328; lr 1.5625e-05; 49s
network 1, training 5, epoch 240: train scaled MSE 0.0020399; val RMSE 0.004677279; lr 1.5625e-05; 51s
network 1, training 5, epoch 250: train scaled MSE 0.00201434; val RMSE 0.004674958; lr 1.5625e-05; 53s
network 1, training 5, epoch 260: train scaled MSE 0.00199676; val RMSE 0.004673621; lr 1.5625e-05; 55s
network 1, training 5, epoch 270: train scaled MSE 0.00196436; val RMSE 0.004673316; lr 1.5625e-05; 57s
network 1, training 5, epoch 280: train scaled MSE 0.00194055; val RMSE 0.00467339; lr 1e-05; 59s
network 1, training 5, epoch 290: train scaled MSE 0.00192601; val RMSE 0.004673155; lr 1e-05; 61s
Standard Linear Baseline Validation RMSE: 0.004788209

Network seed 1, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0036,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0036,-2.5136,"[-7.54%, 0.02%]",0.0749,0.0,0.0116
MLP,0.0038,-11.1536,"[-28.90%, 3.57%]",0.2269,202.9351,0.0055

network 1, training 6, epoch 1: train scaled MSE 0.828828; val RMSE 0.02842526; lr 0.001; 0s
network 1, training 6, epoch 10: train scaled MSE 0.0332659; val RMSE 0.006229933; lr 0.001; 2s
network 1, training 6, epoch 20: train scaled MSE 0.0196681; val RMSE 0.004807868; lr 0.001; 4s
network 1, training 6, epoch 30: train scaled MSE 0.0149549; val RMSE 0.004868545; lr 0.001; 7s
network 1, training 6, epoch 40: train scaled MSE 0.00927911; val RMSE 0.004809854; lr 0.0005; 9s
network 1, training 6, epoch 50: train scaled MSE 0.00705208; val RMSE 0.004551957; lr 0.0005; 11s
network 1, training 6, epoch 60: train scaled MSE 0.00488714; val RMSE 0.004460396; lr 0.0005; 13s
network 1, training 6, epoch 70: train scaled MSE 0.00366317; val RMSE 0.004456122; lr 0.0005; 15s
network 1, training 6, epoch 80: train scaled MSE 0.00288919; val RMSE 0.004485183; lr 0.0005; 17s
network 1, training 6, epoch 90: train scaled MSE 0.00217438; val RMSE 0.004471787; lr 0.00025; 19s
network 1, training 6, epoch 100: train scaled MSE 0.00189398; val RMSE 0.004471349; lr 0.000125; 21s
network 1, training 6, epoch 110: train scaled MSE 0.00178937; val RMSE 0.004470176; lr 0.000125; 24s
Standard Linear Baseline Validation RMSE: 0.003917709

Network seed 1, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,-0.1847,"[-1.81%, 0.86%]",0.0793,0.0,0.0142
MLP,0.0044,-4.3235,"[-23.08%, 13.60%]",0.2781,250.5856,0.0045

network 1, training 7, epoch 1: train scaled MSE 0.847408; val RMSE 0.02886289; lr 0.001; 0s
network 1, training 7, epoch 10: train scaled MSE 0.0325054; val RMSE 0.005090898; lr 0.001; 2s
network 1, training 7, epoch 20: train scaled MSE 0.0178329; val RMSE 0.003924761; lr 0.001; 4s
network 1, training 7, epoch 30: train scaled MSE 0.0133857; val RMSE 0.003582897; lr 0.001; 6s
network 1, training 7, epoch 40: train scaled MSE 0.00808455; val RMSE 0.003285606; lr 0.001; 8s
network 1, training 7, epoch 50: train scaled MSE 0.00534955; val RMSE 0.003374909; lr 0.001; 11s
network 1, training 7, epoch 60: train scaled MSE 0.00393201; val RMSE 0.003224222; lr 0.001; 13s
network 1, training 7, epoch 70: train scaled MSE 0.00296844; val RMSE 0.003085921; lr 0.0005; 15s
network 1, training 7, epoch 80: train scaled MSE 0.00210418; val RMSE 0.003053085; lr 0.00025; 17s
network 1, training 7, epoch 90: train scaled MSE 0.0018652; val RMSE 0.003066622; lr 0.00025; 19s
network 1, training 7, epoch 100: train scaled MSE 0.00161235; val RMSE 0.003066653; lr 0.000125; 21s
network 1, training 7, epoch 110: train scaled MSE 0.00150085; val RMSE 0.003054637; lr 6.25e-05; 23s
network 1, training 7, epoch 120: train scaled MSE 0.00144471; val RMSE 0.003054602; lr 6.25e-05; 25s
Standard Linear Baseline Validation RMSE: 0.003158606

Network seed 1, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0042,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0042,0.0003,"[-2.56%, 1.50%]",0.0953,0.0,0.0119
MLP,0.0041,7.4952,"[-15.65%, 28.78%]",0.3872,306.3273,0.0062

network 1, training 8, epoch 1: train scaled MSE 0.830546; val RMSE 0.02823645; lr 0.001; 0s
network 1, training 8, epoch 10: train scaled MSE 0.0344165; val RMSE 0.005585005; lr 0.001; 2s
network 1, training 8, epoch 20: train scaled MSE 0.0225534; val RMSE 0.003767842; lr 0.001; 4s
network 1, training 8, epoch 30: train scaled MSE 0.0168346; val RMSE 0.003529622; lr 0.001; 6s
network 1, training 8, epoch 40: train scaled MSE 0.0101271; val RMSE 0.003810495; lr 0.001; 9s
network 1, training 8, epoch 50: train scaled MSE 0.00612503; val RMSE 0.003459536; lr 0.001; 11s
network 1, training 8, epoch 60: train scaled MSE 0.00451281; val RMSE 0.00328968; lr 0.001; 13s
network 1, training 8, epoch 70: train scaled MSE 0.00302026; val RMSE 0.003147247; lr 0.0005; 15s
network 1, training 8, epoch 80: train scaled MSE 0.00249248; val RMSE 0.003136304; lr 0.00025; 17s
network 1, training 8, epoch 90: train scaled MSE 0.00226004; val RMSE 0.003113172; lr 0.00025; 19s
network 1, training 8, epoch 100: train scaled MSE 0.00203519; val RMSE 0.003098297; lr 0.000125; 21s
network 1, training 8, epoch 110: train scaled MSE 0.00191662; val RMSE 0.003102735; lr 0.000125; 23s
network 1, training 8, epoch 120: train scaled MSE 0.00180831; val RMSE 0.003095751; lr 6.25e-05; 25s
network 1, training 8, epoch 130: train scaled MSE 0.00175339; val RMSE 0.00309752; lr 6.25e-05; 27s
network 1, training 8, epoch 140: train scaled MSE 0.00170597; val RMSE 0.003096527; lr 3.125e-05; 29s
network 1, training 8, epoch 150: train scaled MSE 0.00168135; val RMSE 0.003094901; lr 1.5625e-05; 31s
network 1, training 8, epoch 160: train scaled MSE 0.00166311; val RMSE 0.003094849; lr 1.5625e-05; 33s
network 1, training 8, epoch 170: train scaled MSE 0.0016473; val RMSE 0.003094607; lr 1.5625e-05; 36s
network 1, training 8, epoch 180: train scaled MSE 0.00163072; val RMSE 0.003095572; lr 1.5625e-05; 38s
network 1, training 8, epoch 190: train scaled MSE 0.001614; val RMSE 0.003095704; lr 1e-05; 40s
network 1, training 8, epoch 200: train scaled MSE 0.00160327; val RMSE 0.003095614; lr 1e-05; 42s
Standard Linear Baseline Validation RMSE: 0.00293941

Network seed 1, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,0.5018,"[-1.53%, 1.50%]",0.1005,0.0,0.0142
MLP,0.0041,6.5488,"[-11.62%, 23.04%]",0.3616,259.82,0.0063

network 1, training 9, epoch 1: train scaled MSE 0.827974; val RMSE 0.02825719; lr 0.001; 0s
network 1, training 9, epoch 10: train scaled MSE 0.0451336; val RMSE 0.005835231; lr 0.001; 2s
network 1, training 9, epoch 20: train scaled MSE 0.0194458; val RMSE 0.004297538; lr 0.001; 4s
network 1, training 9, epoch 30: train scaled MSE 0.0127764; val RMSE 0.00416647; lr 0.001; 6s
network 1, training 9, epoch 40: train scaled MSE 0.00995599; val RMSE 0.004028344; lr 0.001; 8s
network 1, training 9, epoch 50: train scaled MSE 0.00714169; val RMSE 0.003942844; lr 0.001; 10s
network 1, training 9, epoch 60: train scaled MSE 0.00420744; val RMSE 0.003830234; lr 0.001; 12s
network 1, training 9, epoch 70: train scaled MSE 0.00288071; val RMSE 0.003934422; lr 0.001; 14s
network 1, training 9, epoch 80: train scaled MSE 0.00192358; val RMSE 0.003744364; lr 0.0005; 16s
network 1, training 9, epoch 90: train scaled MSE 0.00160919; val RMSE 0.003743864; lr 0.00025; 18s
network 1, training 9, epoch 100: train scaled MSE 0.00140225; val RMSE 0.00374568; lr 0.00025; 20s
network 1, training 9, epoch 110: train scaled MSE 0.00134004; val RMSE 0.003730756; lr 0.00025; 22s
network 1, training 9, epoch 120: train scaled MSE 0.00119092; val RMSE 0.003721339; lr 0.000125; 23s
network 1, training 9, epoch 130: train scaled MSE 0.00114932; val RMSE 0.003728904; lr 0.000125; 25s
network 1, training 9, epoch 140: train scaled MSE 0.00108372; val RMSE 0.003723007; lr 6.25e-05; 27s
network 1, training 9, epoch 150: train scaled MSE 0.00105585; val RMSE 0.003722896; lr 3.125e-05; 29s
network 1, training 9, epoch 160: train scaled MSE 0.00103521; val RMSE 0.003720746; lr 1.5625e-05; 31s
network 1, training 9, epoch 170: train scaled MSE 0.00102609; val RMSE 0.00372119; lr 1.5625e-05; 33s
network 1, training 9, epoch 180: train scaled MSE 0.00101802; val RMSE 0.003719933; lr 1e-05; 35s
network 1, training 9, epoch 190: train scaled MSE 0.00103146; val RMSE 0.003723435; lr 1e-05; 36s
network 1, training 9, epoch 200: train scaled MSE 0.00100768; val RMSE 0.003719826; lr 1e-05; 38s
network 1, training 9, epoch 210: train scaled MSE 0.00101692; val RMSE 0.003721934; lr 1e-05; 40s
Standard Linear Baseline Validation RMSE: 0.003584593

Network seed 1, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0040,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0040,-1.1902,"[-4.30%, 0.51%]",0.0771,0.0,0.0115
MLP,0.0044,-21.2745,"[-41.85%, -6.04%]",0.1630,111.3738,0.0050

Network 2: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   25.3s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   25.5s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   25.6s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   25.6s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   26.0s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   26.2s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   26.3s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   26.4s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   26.6s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   26.8s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   27.0s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   27.1s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   27.3s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   27.5s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   27.8s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   28.2s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   28.5s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   28.8s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   28.9s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   29.2s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   29.5s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   29.8s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   30.0s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   30.4s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   31.0s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   31.3s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   31.6s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   32.0s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   32.3s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   33.0s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   33.4s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   33.8s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   34.2s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   34.6s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   34.9s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   35.4s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   35.7s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   36.1s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   36.6s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   37.0s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   37.5s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   37.9s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   38.4s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   38.9s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   39.4s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   39.8s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   40.3s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   40.8s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   41.3s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   41.8s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   42.4s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   42.9s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   43.5s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   44.0s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   44.6s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   45.2s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   45.7s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   46.3s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   46.9s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   47.5s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   48.1s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   48.7s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   49.4s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   50.0s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   50.6s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   51.3s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   52.0s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   52.7s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   53.4s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   54.0s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   54.7s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   55.5s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   56.1s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   56.8s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   57.6s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   58.3s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   59.0s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   59.8s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.8min finished

network 2, training 0, epoch 1: train scaled MSE 0.878659; val RMSE 0.01203291; lr 0.001; 0s
network 2, training 0, epoch 10: train scaled MSE 0.023941; val RMSE 0.002149223; lr 0.001; 2s
network 2, training 0, epoch 20: train scaled MSE 0.00659865; val RMSE 0.001023769; lr 0.001; 4s
network 2, training 0, epoch 30: train scaled MSE 0.00626605; val RMSE 0.0008717976; lr 0.001; 7s
network 2, training 0, epoch 40: train scaled MSE 0.0049178; val RMSE 0.000795279; lr 0.001; 9s
network 2, training 0, epoch 50: train scaled MSE 0.00307386; val RMSE 0.0007377864; lr 0.001; 11s
network 2, training 0, epoch 60: train scaled MSE 0.00362993; val RMSE 0.000732196; lr 0.001; 13s
network 2, training 0, epoch 70: train scaled MSE 0.00227117; val RMSE 0.001186466; lr 0.001; 15s
network 2, training 0, epoch 80: train scaled MSE 0.00212675; val RMSE 0.0007056718; lr 0.001; 17s
network 2, training 0, epoch 90: train scaled MSE 0.00159284; val RMSE 0.000664421; lr 0.0005; 19s
network 2, training 0, epoch 100: train scaled MSE 0.00150012; val RMSE 0.0006808557; lr 0.0005; 21s
network 2, training 0, epoch 110: train scaled MSE 0.0014546; val RMSE 0.0006913076; lr 0.0005; 23s
network 2, training 0, epoch 120: train scaled MSE 0.00125404; val RMSE 0.0006779757; lr 0.00025; 25s
network 2, training 0, epoch 130: train scaled MSE 0.00124076; val RMSE 0.000669821; lr 0.00025; 28s
network 2, training 0, epoch 140: train scaled MSE 0.00116134; val RMSE 0.0007526394; lr 0.00025; 30s
network 2, training 0, epoch 150: train scaled MSE 0.00111413; val RMSE 0.0006900954; lr 0.00025; 32s
network 2, training 0, epoch 160: train scaled MSE 0.00109517; val RMSE 0.0006033553; lr 0.00025; 34s
network 2, training 0, epoch 170: train scaled MSE 0.00102795; val RMSE 0.0006089217; lr 0.000125; 36s
network 2, training 0, epoch 180: train scaled MSE 0.00096414; val RMSE 0.0005844393; lr 0.000125; 38s
network 2, training 0, epoch 190: train scaled MSE 0.000955286; val RMSE 0.000580735; lr 0.000125; 40s
network 2, training 0, epoch 200: train scaled MSE 0.000929432; val RMSE 0.0005853398; lr 0.000125; 42s
network 2, training 0, epoch 210: train scaled MSE 0.000912871; val RMSE 0.0005785641; lr 0.000125; 45s
network 2, training 0, epoch 220: train scaled MSE 0.000917838; val RMSE 0.0005753557; lr 0.000125; 47s
network 2, training 0, epoch 230: train scaled MSE 0.00110414; val RMSE 0.0005743604; lr 0.000125; 49s
network 2, training 0, epoch 240: train scaled MSE 0.000868827; val RMSE 0.0006391406; lr 0.000125; 51s
network 2, training 0, epoch 250: train scaled MSE 0.00161477; val RMSE 0.0006218858; lr 0.000125; 53s
network 2, training 0, epoch 260: train scaled MSE 0.000824146; val RMSE 0.0005671539; lr 0.000125; 55s
network 2, training 0, epoch 270: train scaled MSE 0.000816436; val RMSE 0.0005647373; lr 0.000125; 57s
network 2, training 0, epoch 280: train scaled MSE 0.000798651; val RMSE 0.0006833448; lr 0.000125; 59s
network 2, training 0, epoch 290: train scaled MSE 0.000796561; val RMSE 0.0005777045; lr 0.000125; 61s
network 2, training 0, epoch 300: train scaled MSE 0.000755834; val RMSE 0.0005609175; lr 6.25e-05; 63s
network 2, training 0, epoch 310: train scaled MSE 0.000746896; val RMSE 0.000559074; lr 6.25e-05; 65s
network 2, training 0, epoch 320: train scaled MSE 0.000958255; val RMSE 0.0005794053; lr 6.25e-05; 68s
network 2, training 0, epoch 330: train scaled MSE 0.000737018; val RMSE 0.000556621; lr 6.25e-05; 70s
network 2, training 0, epoch 340: train scaled MSE 0.000756469; val RMSE 0.0005576087; lr 6.25e-05; 72s
network 2, training 0, epoch 350: train scaled MSE 0.000719028; val RMSE 0.0005730816; lr 6.25e-05; 74s
network 2, training 0, epoch 360: train scaled MSE 0.000774591; val RMSE 0.0005576692; lr 3.125e-05; 76s
network 2, training 0, epoch 370: train scaled MSE 0.000701585; val RMSE 0.0005533775; lr 3.125e-05; 78s
network 2, training 0, epoch 380: train scaled MSE 0.000712267; val RMSE 0.0005574294; lr 3.125e-05; 80s
network 2, training 0, epoch 390: train scaled MSE 0.000693707; val RMSE 0.0005516984; lr 3.125e-05; 82s
network 2, training 0, epoch 400: train scaled MSE 0.000690863; val RMSE 0.0005512701; lr 3.125e-05; 83s
network 2, training 0, epoch 410: train scaled MSE 0.000688659; val RMSE 0.0005503886; lr 3.125e-05; 85s
network 2, training 0, epoch 420: train scaled MSE 0.000723712; val RMSE 0.0005556136; lr 3.125e-05; 87s
network 2, training 0, epoch 430: train scaled MSE 0.000675274; val RMSE 0.0005491474; lr 1.5625e-05; 89s
network 2, training 0, epoch 440: train scaled MSE 0.000673252; val RMSE 0.000548824; lr 1.5625e-05; 91s
network 2, training 0, epoch 450: train scaled MSE 0.000672905; val RMSE 0.0005489333; lr 1.5625e-05; 93s
network 2, training 0, epoch 460: train scaled MSE 0.000670663; val RMSE 0.0005502505; lr 1.5625e-05; 95s
network 2, training 0, epoch 470: train scaled MSE 0.000665791; val RMSE 0.0005502422; lr 1e-05; 97s
network 2, training 0, epoch 480: train scaled MSE 0.000667725; val RMSE 0.0005483879; lr 1e-05; 99s
network 2, training 0, epoch 490: train scaled MSE 0.000664; val RMSE 0.0005477306; lr 1e-05; 101s
network 2, training 0, epoch 500: train scaled MSE 0.000663738; val RMSE 0.0005477823; lr 1e-05; 103s
network 2, training 0, epoch 510: train scaled MSE 0.000661144; val RMSE 0.0005487047; lr 1e-05; 105s
network 2, training 0, epoch 520: train scaled MSE 0.000658891; val RMSE 0.0005470614; lr 1e-05; 107s
network 2, training 0, epoch 530: train scaled MSE 0.000675872; val RMSE 0.0005479023; lr 1e-05; 109s
network 2, training 0, epoch 540: train scaled MSE 0.000667799; val RMSE 0.0005472409; lr 1e-05; 111s
network 2, training 0, epoch 550: train scaled MSE 0.000655139; val RMSE 0.0005463768; lr 1e-05; 113s
network 2, training 0, epoch 560: train scaled MSE 0.000658537; val RMSE 0.0005467639; lr 1e-05; 114s
network 2, training 0, epoch 570: train scaled MSE 0.000652053; val RMSE 0.0005463332; lr 1e-05; 116s
network 2, training 0, epoch 580: train scaled MSE 0.000664107; val RMSE 0.000546614; lr 1e-05; 118s
network 2, training 0, epoch 590: train scaled MSE 0.00065529; val RMSE 0.0005488967; lr 1e-05; 120s
network 2, training 0, epoch 600: train scaled MSE 0.000649689; val RMSE 0.0005463013; lr 1e-05; 122s
network 2, training 0, epoch 610: train scaled MSE 0.0006855; val RMSE 0.0005479118; lr 1e-05; 124s
network 2, training 0, epoch 620: train scaled MSE 0.00064675; val RMSE 0.0005453115; lr 1e-05; 126s
network 2, training 0, epoch 630: train scaled MSE 0.000652175; val RMSE 0.0005451749; lr 1e-05; 128s
network 2, training 0, epoch 640: train scaled MSE 0.000643864; val RMSE 0.0005448724; lr 1e-05; 130s
network 2, training 0, epoch 650: train scaled MSE 0.00064248; val RMSE 0.0005447167; lr 1e-05; 132s
network 2, training 0, epoch 660: train scaled MSE 0.00064237; val RMSE 0.0005450144; lr 1e-05; 134s
network 2, training 0, epoch 670: train scaled MSE 0.000641141; val RMSE 0.0005446493; lr 1e-05; 136s
network 2, training 0, epoch 680: train scaled MSE 0.000637643; val RMSE 0.0005441449; lr 1e-05; 138s
network 2, training 0, epoch 690: train scaled MSE 0.000643214; val RMSE 0.0005442317; lr 1e-05; 140s
network 2, training 0, epoch 700: train scaled MSE 0.000639566; val RMSE 0.0005443324; lr 1e-05; 142s
network 2, training 0, epoch 710: train scaled MSE 0.000634961; val RMSE 0.000543728; lr 1e-05; 144s
network 2, training 0, epoch 720: train scaled MSE 0.000633078; val RMSE 0.0005436424; lr 1e-05; 146s
network 2, training 0, epoch 730: train scaled MSE 0.0006421; val RMSE 0.0005439989; lr 1e-05; 147s
network 2, training 0, epoch 740: train scaled MSE 0.000630643; val RMSE 0.0005430826; lr 1e-05; 149s
network 2, training 0, epoch 750: train scaled MSE 0.00064664; val RMSE 0.0005437012; lr 1e-05; 151s
network 2, training 0, epoch 760: train scaled MSE 0.000629913; val RMSE 0.0005432084; lr 1e-05; 153s
network 2, training 0, epoch 770: train scaled MSE 0.000626895; val RMSE 0.0005427236; lr 1e-05; 155s
network 2, training 0, epoch 780: train scaled MSE 0.000627192; val RMSE 0.0005427803; lr 1e-05; 157s
network 2, training 0, epoch 790: train scaled MSE 0.000625369; val RMSE 0.0005424296; lr 1e-05; 159s
network 2, training 0, epoch 800: train scaled MSE 0.000623609; val RMSE 0.0005424068; lr 1e-05; 161s
network 2, training 0, epoch 810: train scaled MSE 0.000621543; val RMSE 0.000541946; lr 1e-05; 163s
network 2, training 0, epoch 820: train scaled MSE 0.000620316; val RMSE 0.0005427705; lr 1e-05; 165s
network 2, training 0, epoch 830: train scaled MSE 0.000619453; val RMSE 0.0005416466; lr 1e-05; 167s
network 2, training 0, epoch 840: train scaled MSE 0.000618324; val RMSE 0.0005414502; lr 1e-05; 169s
network 2, training 0, epoch 850: train scaled MSE 0.000617555; val RMSE 0.0005412566; lr 1e-05; 171s
network 2, training 0, epoch 860: train scaled MSE 0.000615449; val RMSE 0.0005415057; lr 1e-05; 173s
network 2, training 0, epoch 870: train scaled MSE 0.000621593; val RMSE 0.0005437677; lr 1e-05; 174s
network 2, training 0, epoch 880: train scaled MSE 0.000611494; val RMSE 0.000540839; lr 1e-05; 176s
network 2, training 0, epoch 890: train scaled MSE 0.000610353; val RMSE 0.0005414535; lr 1e-05; 178s
network 2, training 0, epoch 900: train scaled MSE 0.00060994; val RMSE 0.0005406969; lr 1e-05; 180s
network 2, training 0, epoch 910: train scaled MSE 0.000629542; val RMSE 0.0005421429; lr 1e-05; 182s
network 2, training 0, epoch 920: train scaled MSE 0.000628885; val RMSE 0.0005420061; lr 1e-05; 184s
network 2, training 0, epoch 930: train scaled MSE 0.000604777; val RMSE 0.0005407917; lr 1e-05; 186s
network 2, training 0, epoch 940: train scaled MSE 0.000604127; val RMSE 0.0005399819; lr 1e-05; 188s
network 2, training 0, epoch 950: train scaled MSE 0.000608686; val RMSE 0.0005407074; lr 1e-05; 190s
network 2, training 0, epoch 960: train scaled MSE 0.000602107; val RMSE 0.0005406313; lr 1e-05; 192s
network 2, training 0, epoch 970: train scaled MSE 0.000599799; val RMSE 0.0005393562; lr 1e-05; 194s
network 2, training 0, epoch 980: train scaled MSE 0.000624723; val RMSE 0.0005430309; lr 1e-05; 196s
network 2, training 0, epoch 990: train scaled MSE 0.000598362; val RMSE 0.0005393095; lr 1e-05; 198s
network 2, training 0, epoch 1000: train scaled MSE 0.000596428; val RMSE 0.000538892; lr 1e-05; 200s
network 2, training 0, epoch 1010: train scaled MSE 0.000611432; val RMSE 0.0005394197; lr 1e-05; 201s
network 2, training 0, epoch 1020: train scaled MSE 0.000595567; val RMSE 0.0005391606; lr 1e-05; 203s
network 2, training 0, epoch 1030: train scaled MSE 0.000593746; val RMSE 0.0005387982; lr 1e-05; 205s
network 2, training 0, epoch 1040: train scaled MSE 0.000592014; val RMSE 0.0005386096; lr 1e-05; 207s
network 2, training 0, epoch 1050: train scaled MSE 0.000591774; val RMSE 0.0005388835; lr 1e-05; 209s
network 2, training 0, epoch 1060: train scaled MSE 0.000589631; val RMSE 0.0005390395; lr 1e-05; 211s
network 2, training 0, epoch 1070: train scaled MSE 0.0005883; val RMSE 0.0005383042; lr 1e-05; 213s
network 2, training 0, epoch 1080: train scaled MSE 0.000587613; val RMSE 0.0005381369; lr 1e-05; 215s
network 2, training 0, epoch 1090: train scaled MSE 0.000586059; val RMSE 0.0005380231; lr 1e-05; 217s
network 2, training 0, epoch 1100: train scaled MSE 0.000584809; val RMSE 0.0005378463; lr 1e-05; 219s
network 2, training 0, epoch 1110: train scaled MSE 0.000594706; val RMSE 0.0005396949; lr 1e-05; 220s
network 2, training 0, epoch 1120: train scaled MSE 0.000583775; val RMSE 0.0005381549; lr 1e-05; 222s
network 2, training 0, epoch 1130: train scaled MSE 0.000580964; val RMSE 0.0005375716; lr 1e-05; 224s
network 2, training 0, epoch 1140: train scaled MSE 0.000580182; val RMSE 0.000539057; lr 1e-05; 226s
network 2, training 0, epoch 1150: train scaled MSE 0.000581003; val RMSE 0.0005375598; lr 1e-05; 228s
network 2, training 0, epoch 1160: train scaled MSE 0.000593525; val RMSE 0.0005390508; lr 1e-05; 230s
network 2, training 0, epoch 1170: train scaled MSE 0.000580405; val RMSE 0.0005377929; lr 1e-05; 232s
network 2, training 0, epoch 1180: train scaled MSE 0.00057539; val RMSE 0.0005387186; lr 1e-05; 234s
network 2, training 0, epoch 1190: train scaled MSE 0.000574411; val RMSE 0.0005367073; lr 1e-05; 236s
network 2, training 0, epoch 1200: train scaled MSE 0.000573891; val RMSE 0.0005366856; lr 1e-05; 238s
network 2, training 0, epoch 1210: train scaled MSE 0.000582924; val RMSE 0.0005364506; lr 1e-05; 240s
network 2, training 0, epoch 1220: train scaled MSE 0.000591834; val RMSE 0.0005373157; lr 1e-05; 241s
network 2, training 0, epoch 1230: train scaled MSE 0.000572313; val RMSE 0.0005371841; lr 1e-05; 243s
network 2, training 0, epoch 1240: train scaled MSE 0.000576577; val RMSE 0.0005386725; lr 1e-05; 245s
network 2, training 0, epoch 1250: train scaled MSE 0.000570998; val RMSE 0.0005374076; lr 1e-05; 247s
network 2, training 0, epoch 1260: train scaled MSE 0.000567689; val RMSE 0.0005363526; lr 1e-05; 249s
network 2, training 0, epoch 1270: train scaled MSE 0.000565933; val RMSE 0.0005357051; lr 1e-05; 251s
network 2, training 0, epoch 1280: train scaled MSE 0.000567401; val RMSE 0.0005360331; lr 1e-05; 253s
network 2, training 0, epoch 1290: train scaled MSE 0.000564196; val RMSE 0.0005359135; lr 1e-05; 255s
network 2, training 0, epoch 1300: train scaled MSE 0.000565668; val RMSE 0.0005357359; lr 1e-05; 257s
network 2, training 0, epoch 1310: train scaled MSE 0.000564187; val RMSE 0.0005370748; lr 1e-05; 259s
network 2, training 0, epoch 1320: train scaled MSE 0.000560657; val RMSE 0.0005357869; lr 1e-05; 261s
network 2, training 0, epoch 1330: train scaled MSE 0.000559462; val RMSE 0.0005356203; lr 1e-05; 262s
network 2, training 0, epoch 1340: train scaled MSE 0.000558498; val RMSE 0.0005406458; lr 1e-05; 264s
network 2, training 0, epoch 1350: train scaled MSE 0.000559725; val RMSE 0.000535419; lr 1e-05; 266s
network 2, training 0, epoch 1360: train scaled MSE 0.000561074; val RMSE 0.0005363958; lr 1e-05; 268s
network 2, training 0, epoch 1370: train scaled MSE 0.000558325; val RMSE 0.0005354971; lr 1e-05; 270s
network 2, training 0, epoch 1380: train scaled MSE 0.000557263; val RMSE 0.0005350262; lr 1e-05; 272s
network 2, training 0, epoch 1390: train scaled MSE 0.000555702; val RMSE 0.0005360642; lr 1e-05; 274s
network 2, training 0, epoch 1400: train scaled MSE 0.000591533; val RMSE 0.0005360436; lr 1e-05; 276s
network 2, training 0, epoch 1410: train scaled MSE 0.000552372; val RMSE 0.0005343201; lr 1e-05; 278s
network 2, training 0, epoch 1420: train scaled MSE 0.000552011; val RMSE 0.0005346552; lr 1e-05; 280s
network 2, training 0, epoch 1430: train scaled MSE 0.00055315; val RMSE 0.0005346515; lr 1e-05; 281s
network 2, training 0, epoch 1440: train scaled MSE 0.000551772; val RMSE 0.0005342351; lr 1e-05; 283s
network 2, training 0, epoch 1450: train scaled MSE 0.000549244; val RMSE 0.0005348244; lr 1e-05; 285s
network 2, training 0, epoch 1460: train scaled MSE 0.000550392; val RMSE 0.0005341618; lr 1e-05; 287s
network 2, training 0, epoch 1470: train scaled MSE 0.000546892; val RMSE 0.0005340745; lr 1e-05; 289s
network 2, training 0, epoch 1480: train scaled MSE 0.000545627; val RMSE 0.0005339544; lr 1e-05; 291s
network 2, training 0, epoch 1490: train scaled MSE 0.000563785; val RMSE 0.0005351261; lr 1e-05; 293s
network 2, training 0, epoch 1500: train scaled MSE 0.000545453; val RMSE 0.0005335183; lr 1e-05; 295s
network 2, training 0, epoch 1510: train scaled MSE 0.00054411; val RMSE 0.0005337299; lr 1e-05; 297s
network 2, training 0, epoch 1520: train scaled MSE 0.000541853; val RMSE 0.0005333845; lr 1e-05; 298s
network 2, training 0, epoch 1530: train scaled MSE 0.000540758; val RMSE 0.0005333483; lr 1e-05; 301s
network 2, training 0, epoch 1540: train scaled MSE 0.000540617; val RMSE 0.0005332218; lr 1e-05; 303s
network 2, training 0, epoch 1550: train scaled MSE 0.000540288; val RMSE 0.0005334078; lr 1e-05; 305s
network 2, training 0, epoch 1560: train scaled MSE 0.000537917; val RMSE 0.0005329926; lr 1e-05; 307s
network 2, training 0, epoch 1570: train scaled MSE 0.000540717; val RMSE 0.000533706; lr 1e-05; 309s
network 2, training 0, epoch 1580: train scaled MSE 0.000536058; val RMSE 0.0005329239; lr 1e-05; 311s
network 2, training 0, epoch 1590: train scaled MSE 0.000534764; val RMSE 0.0005326613; lr 1e-05; 313s
network 2, training 0, epoch 1600: train scaled MSE 0.000533712; val RMSE 0.000532626; lr 1e-05; 315s
network 2, training 0, epoch 1610: train scaled MSE 0.000533714; val RMSE 0.000532676; lr 1e-05; 317s
network 2, training 0, epoch 1620: train scaled MSE 0.000532978; val RMSE 0.0005346629; lr 1e-05; 318s
Standard Linear Baseline Validation RMSE: 0.0004187615

Network seed 2, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-2.8627,"[-3.82%, -2.07%]",0.0036,0.0,0.5532
MLP,0.0007,-37.4205,"[-54.01%, -25.27%]",0.2084,5756.0696,0.3074

network 2, training 1, epoch 1: train scaled MSE 0.884878; val RMSE 0.01157186; lr 0.001; 0s
network 2, training 1, epoch 10: train scaled MSE 0.0130102; val RMSE 0.001945527; lr 0.001; 2s
network 2, training 1, epoch 20: train scaled MSE 0.00466499; val RMSE 0.00115063; lr 0.001; 4s
network 2, training 1, epoch 30: train scaled MSE 0.00399376; val RMSE 0.002101908; lr 0.001; 6s
network 2, training 1, epoch 40: train scaled MSE 0.0028932; val RMSE 0.0018158; lr 0.001; 8s
network 2, training 1, epoch 50: train scaled MSE 0.00836845; val RMSE 0.001033546; lr 0.0005; 10s
network 2, training 1, epoch 60: train scaled MSE 0.00218011; val RMSE 0.0008308831; lr 0.0005; 12s
network 2, training 1, epoch 70: train scaled MSE 0.00194694; val RMSE 0.0008147583; lr 0.0005; 14s
network 2, training 1, epoch 80: train scaled MSE 0.00192888; val RMSE 0.0008720347; lr 0.0005; 16s
network 2, training 1, epoch 90: train scaled MSE 0.00214734; val RMSE 0.0007886828; lr 0.0005; 18s
network 2, training 1, epoch 100: train scaled MSE 0.00161173; val RMSE 0.0007688493; lr 0.0005; 20s
network 2, training 1, epoch 110: train scaled MSE 0.00155462; val RMSE 0.0007791891; lr 0.0005; 22s
network 2, training 1, epoch 120: train scaled MSE 0.00133994; val RMSE 0.0007839178; lr 0.0005; 24s
network 2, training 1, epoch 130: train scaled MSE 0.00135207; val RMSE 0.0007562899; lr 0.0005; 26s
network 2, training 1, epoch 140: train scaled MSE 0.00133268; val RMSE 0.0007637984; lr 0.0005; 28s
network 2, training 1, epoch 150: train scaled MSE 0.00117202; val RMSE 0.0007740699; lr 0.0005; 30s
network 2, training 1, epoch 160: train scaled MSE 0.00108898; val RMSE 0.000749711; lr 0.0005; 32s
network 2, training 1, epoch 170: train scaled MSE 0.000987567; val RMSE 0.0007617057; lr 0.0005; 34s
network 2, training 1, epoch 180: train scaled MSE 0.000856667; val RMSE 0.0007403668; lr 0.00025; 36s
network 2, training 1, epoch 190: train scaled MSE 0.00083559; val RMSE 0.0007180177; lr 0.00025; 38s
network 2, training 1, epoch 200: train scaled MSE 0.000812924; val RMSE 0.000713334; lr 0.00025; 40s
network 2, training 1, epoch 210: train scaled MSE 0.000799246; val RMSE 0.000718657; lr 0.00025; 41s
network 2, training 1, epoch 220: train scaled MSE 0.000783345; val RMSE 0.000705509; lr 0.000125; 43s
network 2, training 1, epoch 230: train scaled MSE 0.000719782; val RMSE 0.0007049435; lr 0.000125; 45s
network 2, training 1, epoch 240: train scaled MSE 0.000704351; val RMSE 0.0007002399; lr 0.000125; 47s
network 2, training 1, epoch 250: train scaled MSE 0.000702966; val RMSE 0.0006996355; lr 0.000125; 49s
network 2, training 1, epoch 260: train scaled MSE 0.000683949; val RMSE 0.000696102; lr 0.000125; 51s
network 2, training 1, epoch 270: train scaled MSE 0.000672073; val RMSE 0.0006953418; lr 0.000125; 53s
network 2, training 1, epoch 280: train scaled MSE 0.000655633; val RMSE 0.0006931049; lr 0.000125; 55s
network 2, training 1, epoch 290: train scaled MSE 0.000647435; val RMSE 0.0007029165; lr 0.000125; 57s
network 2, training 1, epoch 300: train scaled MSE 0.000632418; val RMSE 0.0006936314; lr 0.000125; 59s
network 2, training 1, epoch 310: train scaled MSE 0.000635453; val RMSE 0.0007994033; lr 0.000125; 61s
network 2, training 1, epoch 320: train scaled MSE 0.000611195; val RMSE 0.0006905865; lr 0.000125; 63s
network 2, training 1, epoch 330: train scaled MSE 0.000600918; val RMSE 0.0007861552; lr 0.000125; 64s
network 2, training 1, epoch 340: train scaled MSE 0.000742456; val RMSE 0.0006923465; lr 0.000125; 66s
network 2, training 1, epoch 350: train scaled MSE 0.000579585; val RMSE 0.0006876465; lr 0.000125; 68s
network 2, training 1, epoch 360: train scaled MSE 0.000574927; val RMSE 0.0006860823; lr 0.000125; 70s
network 2, training 1, epoch 370: train scaled MSE 0.000561746; val RMSE 0.0007524857; lr 0.000125; 72s
network 2, training 1, epoch 380: train scaled MSE 0.000546829; val RMSE 0.0006848522; lr 0.000125; 74s
network 2, training 1, epoch 390: train scaled MSE 0.000542165; val RMSE 0.0006840942; lr 0.000125; 76s
network 2, training 1, epoch 400: train scaled MSE 0.000630902; val RMSE 0.0006927914; lr 0.000125; 78s
network 2, training 1, epoch 410: train scaled MSE 0.000572007; val RMSE 0.0006831421; lr 6.25e-05; 80s
network 2, training 1, epoch 420: train scaled MSE 0.000510907; val RMSE 0.0006798118; lr 6.25e-05; 82s
network 2, training 1, epoch 430: train scaled MSE 0.000504074; val RMSE 0.000678839; lr 6.25e-05; 84s
network 2, training 1, epoch 440: train scaled MSE 0.000500463; val RMSE 0.0006784633; lr 6.25e-05; 86s
network 2, training 1, epoch 450: train scaled MSE 0.0004965; val RMSE 0.0007140585; lr 6.25e-05; 88s
network 2, training 1, epoch 460: train scaled MSE 0.000493581; val RMSE 0.0006780085; lr 6.25e-05; 90s
network 2, training 1, epoch 470: train scaled MSE 0.000534963; val RMSE 0.0006794115; lr 6.25e-05; 92s
network 2, training 1, epoch 480: train scaled MSE 0.00048574; val RMSE 0.0006764816; lr 6.25e-05; 94s
network 2, training 1, epoch 490: train scaled MSE 0.000480789; val RMSE 0.0006769706; lr 6.25e-05; 96s
network 2, training 1, epoch 500: train scaled MSE 0.000469292; val RMSE 0.0006750586; lr 3.125e-05; 98s
network 2, training 1, epoch 510: train scaled MSE 0.000466689; val RMSE 0.0006743682; lr 3.125e-05; 100s
network 2, training 1, epoch 520: train scaled MSE 0.00046442; val RMSE 0.0006742088; lr 3.125e-05; 102s
network 2, training 1, epoch 530: train scaled MSE 0.000462603; val RMSE 0.0006738613; lr 3.125e-05; 104s
network 2, training 1, epoch 540: train scaled MSE 0.000459469; val RMSE 0.0006731784; lr 3.125e-05; 106s
network 2, training 1, epoch 550: train scaled MSE 0.000462681; val RMSE 0.0006734293; lr 3.125e-05; 108s
network 2, training 1, epoch 560: train scaled MSE 0.000454225; val RMSE 0.0006729312; lr 3.125e-05; 109s
network 2, training 1, epoch 570: train scaled MSE 0.000459055; val RMSE 0.0006734062; lr 3.125e-05; 111s
network 2, training 1, epoch 580: train scaled MSE 0.000445845; val RMSE 0.0006720616; lr 1.5625e-05; 113s
network 2, training 1, epoch 590: train scaled MSE 0.000444809; val RMSE 0.0006718215; lr 1.5625e-05; 115s
network 2, training 1, epoch 600: train scaled MSE 0.000445092; val RMSE 0.0006719156; lr 1.5625e-05; 117s
network 2, training 1, epoch 610: train scaled MSE 0.00045619; val RMSE 0.0006738929; lr 1.5625e-05; 119s
network 2, training 1, epoch 620: train scaled MSE 0.000440987; val RMSE 0.000671291; lr 1e-05; 121s
network 2, training 1, epoch 630: train scaled MSE 0.000440009; val RMSE 0.0006721656; lr 1e-05; 123s
network 2, training 1, epoch 640: train scaled MSE 0.000439709; val RMSE 0.0006737062; lr 1e-05; 124s
network 2, training 1, epoch 650: train scaled MSE 0.000441766; val RMSE 0.0006715268; lr 1e-05; 126s
network 2, training 1, epoch 660: train scaled MSE 0.000437096; val RMSE 0.0006717453; lr 1e-05; 128s
network 2, training 1, epoch 670: train scaled MSE 0.000435998; val RMSE 0.0006706361; lr 1e-05; 130s
network 2, training 1, epoch 680: train scaled MSE 0.000479662; val RMSE 0.0006767992; lr 1e-05; 132s
network 2, training 1, epoch 690: train scaled MSE 0.000459553; val RMSE 0.0006717869; lr 1e-05; 134s
network 2, training 1, epoch 700: train scaled MSE 0.000443996; val RMSE 0.0006710499; lr 1e-05; 136s
network 2, training 1, epoch 710: train scaled MSE 0.000437675; val RMSE 0.0006709073; lr 1e-05; 138s
network 2, training 1, epoch 720: train scaled MSE 0.000435159; val RMSE 0.0006711672; lr 1e-05; 140s
network 2, training 1, epoch 730: train scaled MSE 0.000433217; val RMSE 0.0006703624; lr 1e-05; 142s
network 2, training 1, epoch 740: train scaled MSE 0.000432115; val RMSE 0.0006726417; lr 1e-05; 144s
network 2, training 1, epoch 750: train scaled MSE 0.000435427; val RMSE 0.0006719601; lr 1e-05; 146s
network 2, training 1, epoch 760: train scaled MSE 0.000443757; val RMSE 0.0006711909; lr 1e-05; 148s
network 2, training 1, epoch 770: train scaled MSE 0.000432728; val RMSE 0.0006709631; lr 1e-05; 150s
Standard Linear Baseline Validation RMSE: 0.0006225959

Network seed 2, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-2.7028,"[-3.59%, -1.96%]",-0.0026,0.0,0.5728
MLP,0.0007,-31.5856,"[-42.76%, -23.48%]",0.1682,6626.5871,0.3056

network 2, training 2, epoch 1: train scaled MSE 0.884239; val RMSE 0.01217143; lr 0.001; 0s
network 2, training 2, epoch 10: train scaled MSE 0.0295721; val RMSE 0.002338642; lr 0.001; 2s
network 2, training 2, epoch 20: train scaled MSE 0.00628548; val RMSE 0.001156212; lr 0.001; 4s
network 2, training 2, epoch 30: train scaled MSE 0.00489496; val RMSE 0.002048823; lr 0.001; 6s
network 2, training 2, epoch 40: train scaled MSE 0.00405604; val RMSE 0.0008927199; lr 0.001; 8s
network 2, training 2, epoch 50: train scaled MSE 0.00375342; val RMSE 0.0009715467; lr 0.001; 10s
network 2, training 2, epoch 60: train scaled MSE 0.00307695; val RMSE 0.0009681773; lr 0.001; 12s
network 2, training 2, epoch 70: train scaled MSE 0.00253222; val RMSE 0.0008590914; lr 0.001; 14s
network 2, training 2, epoch 80: train scaled MSE 0.00225122; val RMSE 0.0008351838; lr 0.001; 16s
network 2, training 2, epoch 90: train scaled MSE 0.00198123; val RMSE 0.0008391704; lr 0.001; 17s
network 2, training 2, epoch 100: train scaled MSE 0.00154718; val RMSE 0.0008192591; lr 0.0005; 19s
network 2, training 2, epoch 110: train scaled MSE 0.00151217; val RMSE 0.0008028414; lr 0.0005; 21s
network 2, training 2, epoch 120: train scaled MSE 0.00135212; val RMSE 0.0007919235; lr 0.0005; 23s
network 2, training 2, epoch 130: train scaled MSE 0.00131224; val RMSE 0.0007922594; lr 0.0005; 25s
network 2, training 2, epoch 140: train scaled MSE 0.00208072; val RMSE 0.0008000903; lr 0.00025; 27s
network 2, training 2, epoch 150: train scaled MSE 0.00111353; val RMSE 0.0007723726; lr 0.00025; 29s
network 2, training 2, epoch 160: train scaled MSE 0.00106055; val RMSE 0.0007678774; lr 0.00025; 31s
network 2, training 2, epoch 170: train scaled MSE 0.00104222; val RMSE 0.0007644846; lr 0.00025; 33s
network 2, training 2, epoch 180: train scaled MSE 0.00097893; val RMSE 0.0007615728; lr 0.00025; 35s
network 2, training 2, epoch 190: train scaled MSE 0.000978054; val RMSE 0.0007634238; lr 0.00025; 37s
network 2, training 2, epoch 200: train scaled MSE 0.000917521; val RMSE 0.0007562911; lr 0.00025; 39s
network 2, training 2, epoch 210: train scaled MSE 0.0008628; val RMSE 0.0009775844; lr 0.00025; 41s
network 2, training 2, epoch 220: train scaled MSE 0.000844477; val RMSE 0.0007579207; lr 0.00025; 43s
network 2, training 2, epoch 230: train scaled MSE 0.00103916; val RMSE 0.000830761; lr 0.00025; 45s
network 2, training 2, epoch 240: train scaled MSE 0.000717029; val RMSE 0.0007469694; lr 0.000125; 47s
network 2, training 2, epoch 250: train scaled MSE 0.000728041; val RMSE 0.0007456006; lr 0.000125; 49s
network 2, training 2, epoch 260: train scaled MSE 0.000690448; val RMSE 0.0007468518; lr 0.000125; 51s
network 2, training 2, epoch 270: train scaled MSE 0.000782555; val RMSE 0.0007451789; lr 0.000125; 53s
network 2, training 2, epoch 280: train scaled MSE 0.000642795; val RMSE 0.0007577086; lr 6.25e-05; 55s
network 2, training 2, epoch 290: train scaled MSE 0.000636474; val RMSE 0.000740635; lr 6.25e-05; 57s
network 2, training 2, epoch 300: train scaled MSE 0.000628177; val RMSE 0.0007396108; lr 6.25e-05; 59s
network 2, training 2, epoch 310: train scaled MSE 0.000716379; val RMSE 0.0007425206; lr 6.25e-05; 61s
network 2, training 2, epoch 320: train scaled MSE 0.000605921; val RMSE 0.0007404291; lr 3.125e-05; 63s
network 2, training 2, epoch 330: train scaled MSE 0.000603715; val RMSE 0.0007380259; lr 3.125e-05; 66s
network 2, training 2, epoch 340: train scaled MSE 0.00059873; val RMSE 0.0007378072; lr 3.125e-05; 68s
network 2, training 2, epoch 350: train scaled MSE 0.000590609; val RMSE 0.0007373475; lr 1.5625e-05; 70s
network 2, training 2, epoch 360: train scaled MSE 0.000587734; val RMSE 0.0007369644; lr 1.5625e-05; 72s
network 2, training 2, epoch 370: train scaled MSE 0.000585237; val RMSE 0.0007366649; lr 1e-05; 74s
network 2, training 2, epoch 380: train scaled MSE 0.000581953; val RMSE 0.000738292; lr 1e-05; 76s
network 2, training 2, epoch 390: train scaled MSE 0.000580132; val RMSE 0.0007363195; lr 1e-05; 79s
network 2, training 2, epoch 400: train scaled MSE 0.000579318; val RMSE 0.0007361544; lr 1e-05; 81s
network 2, training 2, epoch 410: train scaled MSE 0.000579231; val RMSE 0.0007360339; lr 1e-05; 83s
network 2, training 2, epoch 420: train scaled MSE 0.000581115; val RMSE 0.000736866; lr 1e-05; 85s
network 2, training 2, epoch 430: train scaled MSE 0.00057623; val RMSE 0.000736142; lr 1e-05; 87s
network 2, training 2, epoch 440: train scaled MSE 0.000574467; val RMSE 0.0007356842; lr 1e-05; 89s
network 2, training 2, epoch 450: train scaled MSE 0.000573813; val RMSE 0.0007353358; lr 1e-05; 91s
network 2, training 2, epoch 460: train scaled MSE 0.000571751; val RMSE 0.0007352073; lr 1e-05; 93s
network 2, training 2, epoch 470: train scaled MSE 0.000573633; val RMSE 0.0007350807; lr 1e-05; 95s
network 2, training 2, epoch 480: train scaled MSE 0.000569499; val RMSE 0.0007347643; lr 1e-05; 97s
network 2, training 2, epoch 490: train scaled MSE 0.000576713; val RMSE 0.0007353227; lr 1e-05; 99s
network 2, training 2, epoch 500: train scaled MSE 0.000594149; val RMSE 0.0007365499; lr 1e-05; 101s
network 2, training 2, epoch 510: train scaled MSE 0.000569742; val RMSE 0.0007347172; lr 1e-05; 103s
network 2, training 2, epoch 520: train scaled MSE 0.000565259; val RMSE 0.000734369; lr 1e-05; 105s
network 2, training 2, epoch 530: train scaled MSE 0.00056278; val RMSE 0.0007341716; lr 1e-05; 107s
network 2, training 2, epoch 540: train scaled MSE 0.000561134; val RMSE 0.0007340551; lr 1e-05; 109s
network 2, training 2, epoch 550: train scaled MSE 0.000560647; val RMSE 0.0007341755; lr 1e-05; 111s
network 2, training 2, epoch 560: train scaled MSE 0.000558416; val RMSE 0.0007339796; lr 1e-05; 113s
network 2, training 2, epoch 570: train scaled MSE 0.000565725; val RMSE 0.0007342521; lr 1e-05; 115s
network 2, training 2, epoch 580: train scaled MSE 0.000556719; val RMSE 0.0007340938; lr 1e-05; 117s
network 2, training 2, epoch 590: train scaled MSE 0.00055448; val RMSE 0.0007335815; lr 1e-05; 119s
network 2, training 2, epoch 600: train scaled MSE 0.00055445; val RMSE 0.0007337086; lr 1e-05; 121s
network 2, training 2, epoch 610: train scaled MSE 0.000552337; val RMSE 0.0007335342; lr 1e-05; 123s
network 2, training 2, epoch 620: train scaled MSE 0.000550878; val RMSE 0.0007334722; lr 1e-05; 124s
network 2, training 2, epoch 630: train scaled MSE 0.000549582; val RMSE 0.0007334311; lr 1e-05; 126s
network 2, training 2, epoch 640: train scaled MSE 0.000548475; val RMSE 0.0007332995; lr 1e-05; 128s
network 2, training 2, epoch 650: train scaled MSE 0.000547524; val RMSE 0.0007333383; lr 1e-05; 130s
network 2, training 2, epoch 660: train scaled MSE 0.000546472; val RMSE 0.0007330742; lr 1e-05; 132s
network 2, training 2, epoch 670: train scaled MSE 0.000547307; val RMSE 0.0007334392; lr 1e-05; 134s
network 2, training 2, epoch 680: train scaled MSE 0.000543387; val RMSE 0.0007336175; lr 1e-05; 136s
network 2, training 2, epoch 690: train scaled MSE 0.000552524; val RMSE 0.0007334067; lr 1e-05; 138s
network 2, training 2, epoch 700: train scaled MSE 0.000547297; val RMSE 0.000733736; lr 1e-05; 140s
network 2, training 2, epoch 710: train scaled MSE 0.000540497; val RMSE 0.0007326363; lr 1e-05; 142s
network 2, training 2, epoch 720: train scaled MSE 0.000540252; val RMSE 0.0007326636; lr 1e-05; 144s
network 2, training 2, epoch 730: train scaled MSE 0.000542939; val RMSE 0.0007324569; lr 1e-05; 146s
network 2, training 2, epoch 740: train scaled MSE 0.000537337; val RMSE 0.0007322987; lr 1e-05; 148s
network 2, training 2, epoch 750: train scaled MSE 0.000536593; val RMSE 0.0007323315; lr 1e-05; 150s
network 2, training 2, epoch 760: train scaled MSE 0.0005372; val RMSE 0.0007322788; lr 1e-05; 152s
network 2, training 2, epoch 770: train scaled MSE 0.000573562; val RMSE 0.0007337738; lr 1e-05; 155s
network 2, training 2, epoch 780: train scaled MSE 0.000547785; val RMSE 0.0007322963; lr 1e-05; 157s
network 2, training 2, epoch 790: train scaled MSE 0.000532186; val RMSE 0.0007319562; lr 1e-05; 159s
network 2, training 2, epoch 800: train scaled MSE 0.000531739; val RMSE 0.0007319008; lr 1e-05; 161s
network 2, training 2, epoch 810: train scaled MSE 0.000529624; val RMSE 0.0007316959; lr 1e-05; 163s
network 2, training 2, epoch 820: train scaled MSE 0.000528273; val RMSE 0.0007320497; lr 1e-05; 165s
network 2, training 2, epoch 830: train scaled MSE 0.000532619; val RMSE 0.0007320352; lr 1e-05; 167s
network 2, training 2, epoch 840: train scaled MSE 0.000526824; val RMSE 0.0007315782; lr 1e-05; 169s
network 2, training 2, epoch 850: train scaled MSE 0.000525076; val RMSE 0.0007314756; lr 1e-05; 171s
network 2, training 2, epoch 860: train scaled MSE 0.000525494; val RMSE 0.0007325446; lr 1e-05; 173s
network 2, training 2, epoch 870: train scaled MSE 0.000522881; val RMSE 0.0007313937; lr 1e-05; 175s
network 2, training 2, epoch 880: train scaled MSE 0.000522692; val RMSE 0.0007313826; lr 1e-05; 177s
network 2, training 2, epoch 890: train scaled MSE 0.000525699; val RMSE 0.0007318766; lr 1e-05; 179s
network 2, training 2, epoch 900: train scaled MSE 0.000520276; val RMSE 0.0007310386; lr 1e-05; 181s
network 2, training 2, epoch 910: train scaled MSE 0.000519163; val RMSE 0.0007310281; lr 1e-05; 184s
network 2, training 2, epoch 920: train scaled MSE 0.000520239; val RMSE 0.0007311833; lr 1e-05; 186s
network 2, training 2, epoch 930: train scaled MSE 0.000516547; val RMSE 0.0007309865; lr 1e-05; 188s
network 2, training 2, epoch 940: train scaled MSE 0.000532395; val RMSE 0.0007312644; lr 1e-05; 191s
network 2, training 2, epoch 950: train scaled MSE 0.000542156; val RMSE 0.0007320769; lr 1e-05; 193s
network 2, training 2, epoch 960: train scaled MSE 0.000514745; val RMSE 0.0007306944; lr 1e-05; 195s
network 2, training 2, epoch 970: train scaled MSE 0.000513916; val RMSE 0.0007307688; lr 1e-05; 197s
network 2, training 2, epoch 980: train scaled MSE 0.000511403; val RMSE 0.0007306035; lr 1e-05; 199s
network 2, training 2, epoch 990: train scaled MSE 0.000510515; val RMSE 0.000730577; lr 1e-05; 201s
network 2, training 2, epoch 1000: train scaled MSE 0.00050951; val RMSE 0.0007304436; lr 1e-05; 203s
network 2, training 2, epoch 1010: train scaled MSE 0.000510276; val RMSE 0.0007306725; lr 1e-05; 205s
network 2, training 2, epoch 1020: train scaled MSE 0.000512945; val RMSE 0.0007314499; lr 1e-05; 207s
network 2, training 2, epoch 1030: train scaled MSE 0.000506219; val RMSE 0.0007304558; lr 1e-05; 209s
network 2, training 2, epoch 1040: train scaled MSE 0.000505185; val RMSE 0.0007300089; lr 1e-05; 211s
network 2, training 2, epoch 1050: train scaled MSE 0.000504308; val RMSE 0.0007299721; lr 1e-05; 213s
network 2, training 2, epoch 1060: train scaled MSE 0.000503438; val RMSE 0.0007300545; lr 1e-05; 215s
network 2, training 2, epoch 1070: train scaled MSE 0.000515168; val RMSE 0.0007303912; lr 1e-05; 217s
network 2, training 2, epoch 1080: train scaled MSE 0.00050113; val RMSE 0.0007298561; lr 1e-05; 219s
network 2, training 2, epoch 1090: train scaled MSE 0.000500571; val RMSE 0.0007300255; lr 1e-05; 221s
network 2, training 2, epoch 1100: train scaled MSE 0.000498953; val RMSE 0.0007304677; lr 1e-05; 223s
network 2, training 2, epoch 1110: train scaled MSE 0.000497979; val RMSE 0.0007297952; lr 1e-05; 225s
network 2, training 2, epoch 1120: train scaled MSE 0.000496876; val RMSE 0.0007296105; lr 1e-05; 227s
network 2, training 2, epoch 1130: train scaled MSE 0.000502316; val RMSE 0.0007328363; lr 1e-05; 229s
network 2, training 2, epoch 1140: train scaled MSE 0.000540487; val RMSE 0.0007318248; lr 1e-05; 231s
network 2, training 2, epoch 1150: train scaled MSE 0.000495946; val RMSE 0.0007300435; lr 1e-05; 233s
network 2, training 2, epoch 1160: train scaled MSE 0.000494219; val RMSE 0.0007295976; lr 1e-05; 235s
network 2, training 2, epoch 1170: train scaled MSE 0.000492367; val RMSE 0.0007299818; lr 1e-05; 237s
network 2, training 2, epoch 1180: train scaled MSE 0.000491451; val RMSE 0.0007297151; lr 1e-05; 238s
network 2, training 2, epoch 1190: train scaled MSE 0.000490319; val RMSE 0.0007307383; lr 1e-05; 240s
network 2, training 2, epoch 1200: train scaled MSE 0.000489599; val RMSE 0.0007293022; lr 1e-05; 242s
network 2, training 2, epoch 1210: train scaled MSE 0.000488674; val RMSE 0.0007292727; lr 1e-05; 244s
network 2, training 2, epoch 1220: train scaled MSE 0.000497387; val RMSE 0.0007296569; lr 1e-05; 246s
network 2, training 2, epoch 1230: train scaled MSE 0.000487061; val RMSE 0.0007292015; lr 1e-05; 248s
network 2, training 2, epoch 1240: train scaled MSE 0.000488185; val RMSE 0.0007293301; lr 1e-05; 250s
network 2, training 2, epoch 1250: train scaled MSE 0.000494372; val RMSE 0.0007289723; lr 1e-05; 252s
network 2, training 2, epoch 1260: train scaled MSE 0.000492397; val RMSE 0.000729457; lr 1e-05; 254s
network 2, training 2, epoch 1270: train scaled MSE 0.00048299; val RMSE 0.0007289899; lr 1e-05; 256s
network 2, training 2, epoch 1280: train scaled MSE 0.000483941; val RMSE 0.0007292234; lr 1e-05; 258s
network 2, training 2, epoch 1290: train scaled MSE 0.000483555; val RMSE 0.0007297231; lr 1e-05; 260s
network 2, training 2, epoch 1300: train scaled MSE 0.000483527; val RMSE 0.0007296014; lr 1e-05; 262s
network 2, training 2, epoch 1310: train scaled MSE 0.000481587; val RMSE 0.0007289572; lr 1e-05; 264s
network 2, training 2, epoch 1320: train scaled MSE 0.000479228; val RMSE 0.000728577; lr 1e-05; 266s
network 2, training 2, epoch 1330: train scaled MSE 0.000479303; val RMSE 0.0007287863; lr 1e-05; 268s
network 2, training 2, epoch 1340: train scaled MSE 0.00047794; val RMSE 0.0007288193; lr 1e-05; 270s
network 2, training 2, epoch 1350: train scaled MSE 0.000477638; val RMSE 0.0007286145; lr 1e-05; 272s
network 2, training 2, epoch 1360: train scaled MSE 0.000475899; val RMSE 0.0007290791; lr 1e-05; 274s
network 2, training 2, epoch 1370: train scaled MSE 0.000477322; val RMSE 0.0007285525; lr 1e-05; 276s
network 2, training 2, epoch 1380: train scaled MSE 0.000474522; val RMSE 0.0007284077; lr 1e-05; 277s
network 2, training 2, epoch 1390: train scaled MSE 0.000474006; val RMSE 0.0007286938; lr 1e-05; 279s
network 2, training 2, epoch 1400: train scaled MSE 0.000472406; val RMSE 0.0007283298; lr 1e-05; 281s
network 2, training 2, epoch 1410: train scaled MSE 0.000472311; val RMSE 0.0007284248; lr 1e-05; 283s
network 2, training 2, epoch 1420: train scaled MSE 0.00047149; val RMSE 0.0007284718; lr 1e-05; 285s
network 2, training 2, epoch 1430: train scaled MSE 0.000470209; val RMSE 0.0007282368; lr 1e-05; 287s
network 2, training 2, epoch 1440: train scaled MSE 0.000468977; val RMSE 0.0007282427; lr 1e-05; 289s
network 2, training 2, epoch 1450: train scaled MSE 0.000470151; val RMSE 0.0007289645; lr 1e-05; 291s
network 2, training 2, epoch 1460: train scaled MSE 0.000467876; val RMSE 0.0007281376; lr 1e-05; 293s
network 2, training 2, epoch 1470: train scaled MSE 0.000466375; val RMSE 0.0007280425; lr 1e-05; 295s
network 2, training 2, epoch 1480: train scaled MSE 0.000467208; val RMSE 0.0007279503; lr 1e-05; 297s
network 2, training 2, epoch 1490: train scaled MSE 0.000465137; val RMSE 0.0007276982; lr 1e-05; 299s
network 2, training 2, epoch 1500: train scaled MSE 0.000475905; val RMSE 0.000729399; lr 1e-05; 300s
network 2, training 2, epoch 1510: train scaled MSE 0.000464524; val RMSE 0.0007278794; lr 1e-05; 302s
network 2, training 2, epoch 1520: train scaled MSE 0.000464284; val RMSE 0.0007283293; lr 1e-05; 304s
network 2, training 2, epoch 1530: train scaled MSE 0.000461336; val RMSE 0.0007277847; lr 1e-05; 306s
Standard Linear Baseline Validation RMSE: 0.0006449285

Network seed 2, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-2.4730,"[-3.23%, -1.87%]",-0.0046,0.0,0.5736
MLP,0.0007,-33.6249,"[-48.85%, -21.75%]",0.1886,4224.86,0.2995

network 2, training 3, epoch 1: train scaled MSE 0.88116; val RMSE 0.01183675; lr 0.001; 0s
network 2, training 3, epoch 10: train scaled MSE 0.0158756; val RMSE 0.001993198; lr 0.001; 2s
network 2, training 3, epoch 20: train scaled MSE 0.00433412; val RMSE 0.001093163; lr 0.001; 4s
network 2, training 3, epoch 30: train scaled MSE 0.0048143; val RMSE 0.0009293984; lr 0.001; 6s
network 2, training 3, epoch 40: train scaled MSE 0.00277173; val RMSE 0.0008175292; lr 0.001; 8s
network 2, training 3, epoch 50: train scaled MSE 0.00953062; val RMSE 0.001013828; lr 0.001; 10s
network 2, training 3, epoch 60: train scaled MSE 0.00197601; val RMSE 0.0007824405; lr 0.0005; 12s
network 2, training 3, epoch 70: train scaled MSE 0.00210181; val RMSE 0.001024439; lr 0.0005; 13s
network 2, training 3, epoch 80: train scaled MSE 0.00164456; val RMSE 0.0007627076; lr 0.0005; 15s
network 2, training 3, epoch 90: train scaled MSE 0.00473562; val RMSE 0.0008444032; lr 0.0005; 17s
network 2, training 3, epoch 100: train scaled MSE 0.00142913; val RMSE 0.0007638948; lr 0.0005; 19s
network 2, training 3, epoch 110: train scaled MSE 0.00139956; val RMSE 0.0007446029; lr 0.0005; 21s
network 2, training 3, epoch 120: train scaled MSE 0.00152139; val RMSE 0.0007474045; lr 0.0005; 23s
network 2, training 3, epoch 130: train scaled MSE 0.00106596; val RMSE 0.0007729051; lr 0.00025; 25s
network 2, training 3, epoch 140: train scaled MSE 0.00107602; val RMSE 0.000728355; lr 0.00025; 27s
network 2, training 3, epoch 150: train scaled MSE 0.00102294; val RMSE 0.0007691966; lr 0.00025; 28s
network 2, training 3, epoch 160: train scaled MSE 0.000977693; val RMSE 0.00072129; lr 0.00025; 30s
network 2, training 3, epoch 170: train scaled MSE 0.00104664; val RMSE 0.0007232436; lr 0.00025; 32s
network 2, training 3, epoch 180: train scaled MSE 0.000875635; val RMSE 0.0007332458; lr 0.000125; 34s
network 2, training 3, epoch 190: train scaled MSE 0.000971672; val RMSE 0.0007284071; lr 0.000125; 36s
network 2, training 3, epoch 200: train scaled MSE 0.000864776; val RMSE 0.0007803796; lr 0.000125; 38s
network 2, training 3, epoch 210: train scaled MSE 0.00081212; val RMSE 0.0007083998; lr 6.25e-05; 40s
network 2, training 3, epoch 220: train scaled MSE 0.000802729; val RMSE 0.0007063613; lr 6.25e-05; 42s
network 2, training 3, epoch 230: train scaled MSE 0.00081399; val RMSE 0.0007214347; lr 6.25e-05; 44s
network 2, training 3, epoch 240: train scaled MSE 0.00197281; val RMSE 0.0007558371; lr 6.25e-05; 46s
network 2, training 3, epoch 250: train scaled MSE 0.000809101; val RMSE 0.0007075738; lr 6.25e-05; 47s
network 2, training 3, epoch 260: train scaled MSE 0.000765107; val RMSE 0.0007111314; lr 3.125e-05; 49s
network 2, training 3, epoch 270: train scaled MSE 0.000752138; val RMSE 0.0007038642; lr 1.5625e-05; 51s
network 2, training 3, epoch 280: train scaled MSE 0.000766446; val RMSE 0.0007041234; lr 1.5625e-05; 53s
network 2, training 3, epoch 290: train scaled MSE 0.000746648; val RMSE 0.0007027127; lr 1.5625e-05; 55s
network 2, training 3, epoch 300: train scaled MSE 0.000744654; val RMSE 0.0007025281; lr 1.5625e-05; 57s
network 2, training 3, epoch 310: train scaled MSE 0.000761829; val RMSE 0.0007082963; lr 1.5625e-05; 59s
network 2, training 3, epoch 320: train scaled MSE 0.00074101; val RMSE 0.0007016597; lr 1.5625e-05; 61s
network 2, training 3, epoch 330: train scaled MSE 0.000737588; val RMSE 0.000700989; lr 1.5625e-05; 62s
network 2, training 3, epoch 340: train scaled MSE 0.000734795; val RMSE 0.0007009438; lr 1.5625e-05; 64s
network 2, training 3, epoch 350: train scaled MSE 0.000731354; val RMSE 0.0007006162; lr 1.5625e-05; 66s
network 2, training 3, epoch 360: train scaled MSE 0.00072916; val RMSE 0.0007001003; lr 1.5625e-05; 68s
network 2, training 3, epoch 370: train scaled MSE 0.000738113; val RMSE 0.0007006831; lr 1.5625e-05; 70s
network 2, training 3, epoch 380: train scaled MSE 0.00074033; val RMSE 0.0007006017; lr 1.5625e-05; 72s
network 2, training 3, epoch 390: train scaled MSE 0.000722424; val RMSE 0.0006994801; lr 1.5625e-05; 74s
network 2, training 3, epoch 400: train scaled MSE 0.000731608; val RMSE 0.0006993196; lr 1.5625e-05; 76s
network 2, training 3, epoch 410: train scaled MSE 0.00071672; val RMSE 0.0007016448; lr 1.5625e-05; 78s
network 2, training 3, epoch 420: train scaled MSE 0.000712578; val RMSE 0.0006995504; lr 1.5625e-05; 80s
network 2, training 3, epoch 430: train scaled MSE 0.000710811; val RMSE 0.0006983805; lr 1.5625e-05; 82s
network 2, training 3, epoch 440: train scaled MSE 0.00070915; val RMSE 0.0006981336; lr 1.5625e-05; 84s
network 2, training 3, epoch 450: train scaled MSE 0.000705736; val RMSE 0.000697604; lr 1.5625e-05; 86s
network 2, training 3, epoch 460: train scaled MSE 0.000702668; val RMSE 0.000697247; lr 1.5625e-05; 88s
network 2, training 3, epoch 470: train scaled MSE 0.000701119; val RMSE 0.0006970356; lr 1.5625e-05; 90s
network 2, training 3, epoch 480: train scaled MSE 0.00071367; val RMSE 0.0006971912; lr 1.5625e-05; 92s
network 2, training 3, epoch 490: train scaled MSE 0.000704685; val RMSE 0.0006972714; lr 1.5625e-05; 93s
network 2, training 3, epoch 500: train scaled MSE 0.000691545; val RMSE 0.000696009; lr 1.5625e-05; 95s
network 2, training 3, epoch 510: train scaled MSE 0.000689433; val RMSE 0.0006991858; lr 1.5625e-05; 97s
network 2, training 3, epoch 520: train scaled MSE 0.000687367; val RMSE 0.0006953707; lr 1.5625e-05; 99s
network 2, training 3, epoch 530: train scaled MSE 0.000684812; val RMSE 0.0006951771; lr 1.5625e-05; 101s
network 2, training 3, epoch 540: train scaled MSE 0.000702116; val RMSE 0.000695595; lr 1.5625e-05; 103s
network 2, training 3, epoch 550: train scaled MSE 0.000679175; val RMSE 0.0006954072; lr 1e-05; 105s
network 2, training 3, epoch 560: train scaled MSE 0.000681668; val RMSE 0.0006951892; lr 1e-05; 107s
network 2, training 3, epoch 570: train scaled MSE 0.000673278; val RMSE 0.000695651; lr 1e-05; 109s
network 2, training 3, epoch 580: train scaled MSE 0.000672274; val RMSE 0.0006948918; lr 1e-05; 111s
network 2, training 3, epoch 590: train scaled MSE 0.000670275; val RMSE 0.000693974; lr 1e-05; 113s
network 2, training 3, epoch 600: train scaled MSE 0.000668687; val RMSE 0.0006940987; lr 1e-05; 115s
network 2, training 3, epoch 610: train scaled MSE 0.000668091; val RMSE 0.0006939005; lr 1e-05; 117s
network 2, training 3, epoch 620: train scaled MSE 0.000665746; val RMSE 0.0006936907; lr 1e-05; 119s
network 2, training 3, epoch 630: train scaled MSE 0.00066401; val RMSE 0.0006935968; lr 1e-05; 120s
network 2, training 3, epoch 640: train scaled MSE 0.000662581; val RMSE 0.000695156; lr 1e-05; 122s
network 2, training 3, epoch 650: train scaled MSE 0.000712199; val RMSE 0.0006943426; lr 1e-05; 124s
network 2, training 3, epoch 660: train scaled MSE 0.000659747; val RMSE 0.0006931944; lr 1e-05; 126s
network 2, training 3, epoch 670: train scaled MSE 0.000657205; val RMSE 0.0006929558; lr 1e-05; 128s
network 2, training 3, epoch 680: train scaled MSE 0.000655765; val RMSE 0.0006927223; lr 1e-05; 130s
network 2, training 3, epoch 690: train scaled MSE 0.000676755; val RMSE 0.0006943171; lr 1e-05; 132s
network 2, training 3, epoch 700: train scaled MSE 0.000665486; val RMSE 0.0006934847; lr 1e-05; 134s
network 2, training 3, epoch 710: train scaled MSE 0.000651334; val RMSE 0.0006925712; lr 1e-05; 136s
network 2, training 3, epoch 720: train scaled MSE 0.000652464; val RMSE 0.0006931662; lr 1e-05; 138s
network 2, training 3, epoch 730: train scaled MSE 0.000649342; val RMSE 0.0006925309; lr 1e-05; 140s
network 2, training 3, epoch 740: train scaled MSE 0.000647472; val RMSE 0.0006921402; lr 1e-05; 142s
network 2, training 3, epoch 750: train scaled MSE 0.00064623; val RMSE 0.0006918409; lr 1e-05; 144s
network 2, training 3, epoch 760: train scaled MSE 0.00065829; val RMSE 0.000692364; lr 1e-05; 146s
network 2, training 3, epoch 770: train scaled MSE 0.000643394; val RMSE 0.0006937385; lr 1e-05; 148s
network 2, training 3, epoch 780: train scaled MSE 0.000645371; val RMSE 0.0006916271; lr 1e-05; 150s
network 2, training 3, epoch 790: train scaled MSE 0.000640981; val RMSE 0.0006913459; lr 1e-05; 152s
network 2, training 3, epoch 800: train scaled MSE 0.00064963; val RMSE 0.0006922419; lr 1e-05; 154s
network 2, training 3, epoch 810: train scaled MSE 0.000638563; val RMSE 0.0006911491; lr 1e-05; 156s
network 2, training 3, epoch 820: train scaled MSE 0.000641093; val RMSE 0.0006915857; lr 1e-05; 158s
network 2, training 3, epoch 830: train scaled MSE 0.000635736; val RMSE 0.0006925313; lr 1e-05; 160s
network 2, training 3, epoch 840: train scaled MSE 0.000643676; val RMSE 0.0006911947; lr 1e-05; 162s
network 2, training 3, epoch 850: train scaled MSE 0.000642528; val RMSE 0.0006933621; lr 1e-05; 164s
network 2, training 3, epoch 860: train scaled MSE 0.000633232; val RMSE 0.0006914255; lr 1e-05; 166s
network 2, training 3, epoch 870: train scaled MSE 0.000632886; val RMSE 0.0006906874; lr 1e-05; 168s
network 2, training 3, epoch 880: train scaled MSE 0.000631339; val RMSE 0.0006904996; lr 1e-05; 170s
network 2, training 3, epoch 890: train scaled MSE 0.000631307; val RMSE 0.0006913495; lr 1e-05; 171s
network 2, training 3, epoch 900: train scaled MSE 0.000630685; val RMSE 0.0006912647; lr 1e-05; 173s
network 2, training 3, epoch 910: train scaled MSE 0.000626063; val RMSE 0.0006901034; lr 1e-05; 175s
network 2, training 3, epoch 920: train scaled MSE 0.000628293; val RMSE 0.0006905417; lr 1e-05; 177s
network 2, training 3, epoch 930: train scaled MSE 0.000623853; val RMSE 0.0006919511; lr 1e-05; 179s
network 2, training 3, epoch 940: train scaled MSE 0.00062271; val RMSE 0.000689876; lr 1e-05; 181s
network 2, training 3, epoch 950: train scaled MSE 0.000621284; val RMSE 0.0006897399; lr 1e-05; 183s
network 2, training 3, epoch 960: train scaled MSE 0.000620973; val RMSE 0.0006897839; lr 1e-05; 185s
network 2, training 3, epoch 970: train scaled MSE 0.000622473; val RMSE 0.0006898448; lr 1e-05; 187s
network 2, training 3, epoch 980: train scaled MSE 0.00062053; val RMSE 0.0006897014; lr 1e-05; 189s
network 2, training 3, epoch 990: train scaled MSE 0.000635002; val RMSE 0.0006904838; lr 1e-05; 191s
network 2, training 3, epoch 1000: train scaled MSE 0.00061765; val RMSE 0.0006910256; lr 1e-05; 193s
network 2, training 3, epoch 1010: train scaled MSE 0.000619051; val RMSE 0.0006894006; lr 1e-05; 195s
network 2, training 3, epoch 1020: train scaled MSE 0.000613596; val RMSE 0.0006891785; lr 1e-05; 197s
network 2, training 3, epoch 1030: train scaled MSE 0.000612516; val RMSE 0.0006890952; lr 1e-05; 199s
network 2, training 3, epoch 1040: train scaled MSE 0.000611658; val RMSE 0.0006887728; lr 1e-05; 201s
network 2, training 3, epoch 1050: train scaled MSE 0.000611173; val RMSE 0.0006889178; lr 1e-05; 203s
network 2, training 3, epoch 1060: train scaled MSE 0.000609112; val RMSE 0.000688976; lr 1e-05; 205s
network 2, training 3, epoch 1070: train scaled MSE 0.000608385; val RMSE 0.0006889286; lr 1e-05; 207s
network 2, training 3, epoch 1080: train scaled MSE 0.000612773; val RMSE 0.0006889681; lr 1e-05; 209s
network 2, training 3, epoch 1090: train scaled MSE 0.000610177; val RMSE 0.0006888586; lr 1e-05; 211s
network 2, training 3, epoch 1100: train scaled MSE 0.00063274; val RMSE 0.0006889318; lr 1e-05; 213s
network 2, training 3, epoch 1110: train scaled MSE 0.00060646; val RMSE 0.0006883869; lr 1e-05; 215s
network 2, training 3, epoch 1120: train scaled MSE 0.00060266; val RMSE 0.0006882998; lr 1e-05; 217s
network 2, training 3, epoch 1130: train scaled MSE 0.000604607; val RMSE 0.0006887342; lr 1e-05; 219s
network 2, training 3, epoch 1140: train scaled MSE 0.000600105; val RMSE 0.0006882243; lr 1e-05; 221s
network 2, training 3, epoch 1150: train scaled MSE 0.000604633; val RMSE 0.0006884141; lr 1e-05; 223s
network 2, training 3, epoch 1160: train scaled MSE 0.000597789; val RMSE 0.0006880472; lr 1e-05; 225s
network 2, training 3, epoch 1170: train scaled MSE 0.000596926; val RMSE 0.0006878437; lr 1e-05; 227s
network 2, training 3, epoch 1180: train scaled MSE 0.000607907; val RMSE 0.0006885934; lr 1e-05; 229s
network 2, training 3, epoch 1190: train scaled MSE 0.000595595; val RMSE 0.0006880382; lr 1e-05; 231s
network 2, training 3, epoch 1200: train scaled MSE 0.000593306; val RMSE 0.0006877041; lr 1e-05; 233s
network 2, training 3, epoch 1210: train scaled MSE 0.000592647; val RMSE 0.0006876187; lr 1e-05; 235s
network 2, training 3, epoch 1220: train scaled MSE 0.000591539; val RMSE 0.0006873761; lr 1e-05; 237s
network 2, training 3, epoch 1230: train scaled MSE 0.000589662; val RMSE 0.0006874328; lr 1e-05; 239s
network 2, training 3, epoch 1240: train scaled MSE 0.000590106; val RMSE 0.0006871055; lr 1e-05; 241s
network 2, training 3, epoch 1250: train scaled MSE 0.00058748; val RMSE 0.0006872135; lr 1e-05; 243s
network 2, training 3, epoch 1260: train scaled MSE 0.00060179; val RMSE 0.0006877354; lr 1e-05; 244s
network 2, training 3, epoch 1270: train scaled MSE 0.000584861; val RMSE 0.0006884417; lr 1e-05; 246s
network 2, training 3, epoch 1280: train scaled MSE 0.000584021; val RMSE 0.0006870336; lr 1e-05; 248s
network 2, training 3, epoch 1290: train scaled MSE 0.000590878; val RMSE 0.0006870136; lr 1e-05; 250s
network 2, training 3, epoch 1300: train scaled MSE 0.000582785; val RMSE 0.0006869678; lr 1e-05; 252s
network 2, training 3, epoch 1310: train scaled MSE 0.000580724; val RMSE 0.0006870131; lr 1e-05; 254s
network 2, training 3, epoch 1320: train scaled MSE 0.000592848; val RMSE 0.0006872642; lr 1e-05; 256s
network 2, training 3, epoch 1330: train scaled MSE 0.000579703; val RMSE 0.000687466; lr 1e-05; 258s
network 2, training 3, epoch 1340: train scaled MSE 0.000579722; val RMSE 0.0006870807; lr 1e-05; 259s
network 2, training 3, epoch 1350: train scaled MSE 0.000577251; val RMSE 0.0006868083; lr 1e-05; 261s
network 2, training 3, epoch 1360: train scaled MSE 0.000576432; val RMSE 0.000686996; lr 1e-05; 263s
Standard Linear Baseline Validation RMSE: 0.0006061356

Network seed 2, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-1.7900,"[-2.42%, -1.24%]",0.0013,0.0,0.6080
MLP,0.0007,-24.1294,"[-38.47%, -14.23%]",0.1883,14392.0832,0.3017

network 2, training 4, epoch 1: train scaled MSE 0.882382; val RMSE 0.01166589; lr 0.001; 0s
network 2, training 4, epoch 10: train scaled MSE 0.0131894; val RMSE 0.001771614; lr 0.001; 2s
network 2, training 4, epoch 20: train scaled MSE 0.00448612; val RMSE 0.002084769; lr 0.001; 4s
network 2, training 4, epoch 30: train scaled MSE 0.00357199; val RMSE 0.000985645; lr 0.001; 6s
network 2, training 4, epoch 40: train scaled MSE 0.00346245; val RMSE 0.0009886861; lr 0.001; 8s
network 2, training 4, epoch 50: train scaled MSE 0.00274417; val RMSE 0.0009285446; lr 0.001; 10s
network 2, training 4, epoch 60: train scaled MSE 0.0021825; val RMSE 0.0009028642; lr 0.0005; 12s
network 2, training 4, epoch 70: train scaled MSE 0.00199678; val RMSE 0.000880936; lr 0.0005; 13s
network 2, training 4, epoch 80: train scaled MSE 0.00180613; val RMSE 0.0008891783; lr 0.0005; 15s
network 2, training 4, epoch 90: train scaled MSE 0.00162074; val RMSE 0.0008888423; lr 0.0005; 17s
network 2, training 4, epoch 100: train scaled MSE 0.00145396; val RMSE 0.0008483962; lr 0.00025; 19s
network 2, training 4, epoch 110: train scaled MSE 0.00139974; val RMSE 0.0008492681; lr 0.00025; 21s
network 2, training 4, epoch 120: train scaled MSE 0.00228607; val RMSE 0.0008592598; lr 0.00025; 23s
network 2, training 4, epoch 130: train scaled MSE 0.00124568; val RMSE 0.0008372988; lr 0.00025; 25s
network 2, training 4, epoch 140: train scaled MSE 0.00119544; val RMSE 0.0008291113; lr 0.00025; 26s
network 2, training 4, epoch 150: train scaled MSE 0.00237405; val RMSE 0.0008411278; lr 0.00025; 28s
network 2, training 4, epoch 160: train scaled MSE 0.00112164; val RMSE 0.0008249469; lr 0.00025; 30s
network 2, training 4, epoch 170: train scaled MSE 0.00131139; val RMSE 0.0008623059; lr 0.00025; 32s
network 2, training 4, epoch 180: train scaled MSE 0.00100872; val RMSE 0.000812453; lr 0.00025; 34s
network 2, training 4, epoch 190: train scaled MSE 0.0010265; val RMSE 0.0008117733; lr 0.00025; 36s
network 2, training 4, epoch 200: train scaled MSE 0.00096238; val RMSE 0.0008193512; lr 0.00025; 38s
network 2, training 4, epoch 210: train scaled MSE 0.000927707; val RMSE 0.0008131; lr 0.00025; 39s
network 2, training 4, epoch 220: train scaled MSE 0.000918813; val RMSE 0.0008095644; lr 0.00025; 41s
network 2, training 4, epoch 230: train scaled MSE 0.00100097; val RMSE 0.0008070466; lr 0.000125; 43s
network 2, training 4, epoch 240: train scaled MSE 0.000820832; val RMSE 0.0008008398; lr 0.000125; 45s
network 2, training 4, epoch 250: train scaled MSE 0.000821271; val RMSE 0.00079769; lr 0.000125; 47s
network 2, training 4, epoch 260: train scaled MSE 0.000799105; val RMSE 0.0007969442; lr 0.000125; 49s
network 2, training 4, epoch 270: train scaled MSE 0.000917981; val RMSE 0.0008004406; lr 0.000125; 51s
network 2, training 4, epoch 280: train scaled MSE 0.000755606; val RMSE 0.0007929553; lr 6.25e-05; 53s
network 2, training 4, epoch 290: train scaled MSE 0.000749209; val RMSE 0.0007911191; lr 6.25e-05; 55s
network 2, training 4, epoch 300: train scaled MSE 0.000742028; val RMSE 0.000825228; lr 6.25e-05; 56s
network 2, training 4, epoch 310: train scaled MSE 0.000752304; val RMSE 0.0007899361; lr 6.25e-05; 58s
network 2, training 4, epoch 320: train scaled MSE 0.000731196; val RMSE 0.0007882341; lr 6.25e-05; 60s
network 2, training 4, epoch 330: train scaled MSE 0.000720862; val RMSE 0.0007937428; lr 6.25e-05; 62s
network 2, training 4, epoch 340: train scaled MSE 0.000717276; val RMSE 0.000786942; lr 6.25e-05; 64s
network 2, training 4, epoch 350: train scaled MSE 0.000705602; val RMSE 0.0007879423; lr 6.25e-05; 66s
network 2, training 4, epoch 360: train scaled MSE 0.000699341; val RMSE 0.0007864796; lr 6.25e-05; 68s
network 2, training 4, epoch 370: train scaled MSE 0.000695947; val RMSE 0.0007835556; lr 6.25e-05; 70s
network 2, training 4, epoch 380: train scaled MSE 0.000686141; val RMSE 0.0007837883; lr 6.25e-05; 72s
network 2, training 4, epoch 390: train scaled MSE 0.000680729; val RMSE 0.0007830222; lr 6.25e-05; 74s
network 2, training 4, epoch 400: train scaled MSE 0.0007867; val RMSE 0.0007862197; lr 6.25e-05; 76s
network 2, training 4, epoch 410: train scaled MSE 0.000665327; val RMSE 0.0007825895; lr 6.25e-05; 78s
network 2, training 4, epoch 420: train scaled MSE 0.000731708; val RMSE 0.0007861444; lr 6.25e-05; 80s
network 2, training 4, epoch 430: train scaled MSE 0.000651732; val RMSE 0.0007873551; lr 6.25e-05; 82s
network 2, training 4, epoch 440: train scaled MSE 0.000646837; val RMSE 0.0007801011; lr 6.25e-05; 84s
network 2, training 4, epoch 450: train scaled MSE 0.00064666; val RMSE 0.0007790171; lr 6.25e-05; 86s
network 2, training 4, epoch 460: train scaled MSE 0.000690482; val RMSE 0.0007839935; lr 3.125e-05; 88s
network 2, training 4, epoch 470: train scaled MSE 0.000625792; val RMSE 0.0007784756; lr 3.125e-05; 90s
network 2, training 4, epoch 480: train scaled MSE 0.000625607; val RMSE 0.0007779098; lr 3.125e-05; 92s
network 2, training 4, epoch 490: train scaled MSE 0.000620997; val RMSE 0.0007773028; lr 3.125e-05; 94s
network 2, training 4, epoch 500: train scaled MSE 0.000620419; val RMSE 0.0007774706; lr 3.125e-05; 96s
network 2, training 4, epoch 510: train scaled MSE 0.000614071; val RMSE 0.0007770296; lr 3.125e-05; 97s
network 2, training 4, epoch 520: train scaled MSE 0.000609108; val RMSE 0.0007769701; lr 3.125e-05; 99s
network 2, training 4, epoch 530: train scaled MSE 0.000646602; val RMSE 0.000777175; lr 3.125e-05; 101s
network 2, training 4, epoch 540: train scaled MSE 0.000601222; val RMSE 0.0007829464; lr 3.125e-05; 103s
network 2, training 4, epoch 550: train scaled MSE 0.000602599; val RMSE 0.0007757342; lr 3.125e-05; 105s
network 2, training 4, epoch 560: train scaled MSE 0.000614674; val RMSE 0.0007765033; lr 3.125e-05; 107s
network 2, training 4, epoch 570: train scaled MSE 0.000588962; val RMSE 0.0007748794; lr 1.5625e-05; 109s
network 2, training 4, epoch 580: train scaled MSE 0.000586976; val RMSE 0.0007747914; lr 1.5625e-05; 111s
network 2, training 4, epoch 590: train scaled MSE 0.000590306; val RMSE 0.0007764888; lr 1.5625e-05; 112s
network 2, training 4, epoch 600: train scaled MSE 0.0005873; val RMSE 0.0007756849; lr 1e-05; 114s
network 2, training 4, epoch 610: train scaled MSE 0.000583517; val RMSE 0.0007748145; lr 1e-05; 116s
network 2, training 4, epoch 620: train scaled MSE 0.00058708; val RMSE 0.0007743196; lr 1e-05; 118s
network 2, training 4, epoch 630: train scaled MSE 0.00057978; val RMSE 0.0007741212; lr 1e-05; 120s
network 2, training 4, epoch 640: train scaled MSE 0.000602009; val RMSE 0.0007744109; lr 1e-05; 122s
network 2, training 4, epoch 650: train scaled MSE 0.000578526; val RMSE 0.0007741075; lr 1e-05; 124s
network 2, training 4, epoch 660: train scaled MSE 0.000583128; val RMSE 0.0007742737; lr 1e-05; 126s
network 2, training 4, epoch 670: train scaled MSE 0.000575775; val RMSE 0.0007737185; lr 1e-05; 128s
network 2, training 4, epoch 680: train scaled MSE 0.000574775; val RMSE 0.0007734559; lr 1e-05; 129s
network 2, training 4, epoch 690: train scaled MSE 0.000576656; val RMSE 0.0007738422; lr 1e-05; 131s
network 2, training 4, epoch 700: train scaled MSE 0.000572718; val RMSE 0.0007733524; lr 1e-05; 133s
network 2, training 4, epoch 710: train scaled MSE 0.00057157; val RMSE 0.0007731903; lr 1e-05; 135s
network 2, training 4, epoch 720: train scaled MSE 0.000571138; val RMSE 0.0007739577; lr 1e-05; 137s
network 2, training 4, epoch 730: train scaled MSE 0.000576865; val RMSE 0.000773091; lr 1e-05; 139s
network 2, training 4, epoch 740: train scaled MSE 0.000569385; val RMSE 0.0007729455; lr 1e-05; 141s
network 2, training 4, epoch 750: train scaled MSE 0.000567301; val RMSE 0.000772636; lr 1e-05; 142s
network 2, training 4, epoch 760: train scaled MSE 0.000567817; val RMSE 0.0007726984; lr 1e-05; 144s
network 2, training 4, epoch 770: train scaled MSE 0.000565297; val RMSE 0.0007725111; lr 1e-05; 146s
network 2, training 4, epoch 780: train scaled MSE 0.000566077; val RMSE 0.0007726053; lr 1e-05; 148s
network 2, training 4, epoch 790: train scaled MSE 0.000564583; val RMSE 0.0007724988; lr 1e-05; 150s
network 2, training 4, epoch 800: train scaled MSE 0.000564965; val RMSE 0.0007725452; lr 1e-05; 152s
network 2, training 4, epoch 810: train scaled MSE 0.000561457; val RMSE 0.0007721651; lr 1e-05; 154s
network 2, training 4, epoch 820: train scaled MSE 0.000575952; val RMSE 0.0007726562; lr 1e-05; 156s
network 2, training 4, epoch 830: train scaled MSE 0.000560195; val RMSE 0.0007719239; lr 1e-05; 157s
network 2, training 4, epoch 840: train scaled MSE 0.000561911; val RMSE 0.0007721835; lr 1e-05; 159s
network 2, training 4, epoch 850: train scaled MSE 0.000558341; val RMSE 0.0007720278; lr 1e-05; 161s
network 2, training 4, epoch 860: train scaled MSE 0.000558655; val RMSE 0.0007717939; lr 1e-05; 163s
network 2, training 4, epoch 870: train scaled MSE 0.000555779; val RMSE 0.0007716319; lr 1e-05; 165s
network 2, training 4, epoch 880: train scaled MSE 0.000554549; val RMSE 0.0007714911; lr 1e-05; 167s
network 2, training 4, epoch 890: train scaled MSE 0.000556549; val RMSE 0.0007714948; lr 1e-05; 169s
network 2, training 4, epoch 900: train scaled MSE 0.00055297; val RMSE 0.000771393; lr 1e-05; 171s
network 2, training 4, epoch 910: train scaled MSE 0.000551977; val RMSE 0.000771253; lr 1e-05; 173s
network 2, training 4, epoch 920: train scaled MSE 0.000550279; val RMSE 0.0007712067; lr 1e-05; 175s
network 2, training 4, epoch 930: train scaled MSE 0.000551979; val RMSE 0.0007714178; lr 1e-05; 177s
network 2, training 4, epoch 940: train scaled MSE 0.000548772; val RMSE 0.0007709908; lr 1e-05; 179s
network 2, training 4, epoch 950: train scaled MSE 0.000547497; val RMSE 0.0007709368; lr 1e-05; 181s
network 2, training 4, epoch 960: train scaled MSE 0.000547184; val RMSE 0.0007708833; lr 1e-05; 183s
network 2, training 4, epoch 970: train scaled MSE 0.00054615; val RMSE 0.0007705826; lr 1e-05; 185s
network 2, training 4, epoch 980: train scaled MSE 0.00054465; val RMSE 0.0007708088; lr 1e-05; 187s
network 2, training 4, epoch 990: train scaled MSE 0.000544156; val RMSE 0.0007706774; lr 1e-05; 189s
network 2, training 4, epoch 1000: train scaled MSE 0.000542482; val RMSE 0.0007704664; lr 1e-05; 191s
network 2, training 4, epoch 1010: train scaled MSE 0.00054757; val RMSE 0.0007706529; lr 1e-05; 193s
network 2, training 4, epoch 1020: train scaled MSE 0.000540013; val RMSE 0.0007702376; lr 1e-05; 195s
network 2, training 4, epoch 1030: train scaled MSE 0.000539445; val RMSE 0.0007701153; lr 1e-05; 197s
network 2, training 4, epoch 1040: train scaled MSE 0.000561276; val RMSE 0.0007711704; lr 1e-05; 199s
network 2, training 4, epoch 1050: train scaled MSE 0.000538114; val RMSE 0.0007701498; lr 1e-05; 201s
network 2, training 4, epoch 1060: train scaled MSE 0.000536098; val RMSE 0.0007698939; lr 1e-05; 203s
network 2, training 4, epoch 1070: train scaled MSE 0.000534832; val RMSE 0.0007706315; lr 1e-05; 205s
network 2, training 4, epoch 1080: train scaled MSE 0.000534869; val RMSE 0.0007697734; lr 1e-05; 208s
network 2, training 4, epoch 1090: train scaled MSE 0.000538269; val RMSE 0.000770866; lr 1e-05; 210s
network 2, training 4, epoch 1100: train scaled MSE 0.000533385; val RMSE 0.0007697877; lr 1e-05; 212s
network 2, training 4, epoch 1110: train scaled MSE 0.00053188; val RMSE 0.0007695213; lr 1e-05; 214s
network 2, training 4, epoch 1120: train scaled MSE 0.000530422; val RMSE 0.0007693491; lr 1e-05; 216s
network 2, training 4, epoch 1130: train scaled MSE 0.000530086; val RMSE 0.0007693592; lr 1e-05; 218s
network 2, training 4, epoch 1140: train scaled MSE 0.000528871; val RMSE 0.0007692531; lr 1e-05; 221s
network 2, training 4, epoch 1150: train scaled MSE 0.000529286; val RMSE 0.0007695945; lr 1e-05; 223s
network 2, training 4, epoch 1160: train scaled MSE 0.000526516; val RMSE 0.0007692124; lr 1e-05; 225s
network 2, training 4, epoch 1170: train scaled MSE 0.000525805; val RMSE 0.000769027; lr 1e-05; 227s
network 2, training 4, epoch 1180: train scaled MSE 0.000525629; val RMSE 0.0007689633; lr 1e-05; 229s
network 2, training 4, epoch 1190: train scaled MSE 0.000524023; val RMSE 0.000769122; lr 1e-05; 231s
network 2, training 4, epoch 1200: train scaled MSE 0.000538563; val RMSE 0.0007689965; lr 1e-05; 233s
network 2, training 4, epoch 1210: train scaled MSE 0.000522045; val RMSE 0.0007687885; lr 1e-05; 235s
network 2, training 4, epoch 1220: train scaled MSE 0.000520841; val RMSE 0.000768751; lr 1e-05; 237s
network 2, training 4, epoch 1230: train scaled MSE 0.000521844; val RMSE 0.0007691599; lr 1e-05; 239s
network 2, training 4, epoch 1240: train scaled MSE 0.000518843; val RMSE 0.0007686282; lr 1e-05; 241s
network 2, training 4, epoch 1250: train scaled MSE 0.000518119; val RMSE 0.0007684294; lr 1e-05; 243s
network 2, training 4, epoch 1260: train scaled MSE 0.000517751; val RMSE 0.0007684415; lr 1e-05; 245s
network 2, training 4, epoch 1270: train scaled MSE 0.000516259; val RMSE 0.0007680523; lr 1e-05; 247s
network 2, training 4, epoch 1280: train scaled MSE 0.000515529; val RMSE 0.0007682353; lr 1e-05; 249s
network 2, training 4, epoch 1290: train scaled MSE 0.000514712; val RMSE 0.0007680705; lr 1e-05; 251s
network 2, training 4, epoch 1300: train scaled MSE 0.000514398; val RMSE 0.0007700216; lr 1e-05; 253s
network 2, training 4, epoch 1310: train scaled MSE 0.000512446; val RMSE 0.0007682388; lr 1e-05; 255s
network 2, training 4, epoch 1320: train scaled MSE 0.000513008; val RMSE 0.0007699511; lr 1e-05; 257s
network 2, training 4, epoch 1330: train scaled MSE 0.000510204; val RMSE 0.0007679321; lr 1e-05; 259s
network 2, training 4, epoch 1340: train scaled MSE 0.000509222; val RMSE 0.0007692227; lr 1e-05; 261s
network 2, training 4, epoch 1350: train scaled MSE 0.000515775; val RMSE 0.0007686294; lr 1e-05; 263s
network 2, training 4, epoch 1360: train scaled MSE 0.000508415; val RMSE 0.0007679464; lr 1e-05; 265s
network 2, training 4, epoch 1370: train scaled MSE 0.000506693; val RMSE 0.0007691823; lr 1e-05; 267s
network 2, training 4, epoch 1380: train scaled MSE 0.000506551; val RMSE 0.0007677084; lr 1e-05; 269s
network 2, training 4, epoch 1390: train scaled MSE 0.000505047; val RMSE 0.0007676514; lr 1e-05; 271s
network 2, training 4, epoch 1400: train scaled MSE 0.000503639; val RMSE 0.0007676736; lr 1e-05; 273s
network 2, training 4, epoch 1410: train scaled MSE 0.000503722; val RMSE 0.0007676313; lr 1e-05; 275s
network 2, training 4, epoch 1420: train scaled MSE 0.000503128; val RMSE 0.0007674643; lr 1e-05; 277s
network 2, training 4, epoch 1430: train scaled MSE 0.000501178; val RMSE 0.0007673453; lr 1e-05; 278s
network 2, training 4, epoch 1440: train scaled MSE 0.000500147; val RMSE 0.0007673325; lr 1e-05; 280s
network 2, training 4, epoch 1450: train scaled MSE 0.00050098; val RMSE 0.0007693591; lr 1e-05; 282s
network 2, training 4, epoch 1460: train scaled MSE 0.000507177; val RMSE 0.0007675473; lr 1e-05; 284s
network 2, training 4, epoch 1470: train scaled MSE 0.000504622; val RMSE 0.0007677193; lr 1e-05; 286s
network 2, training 4, epoch 1480: train scaled MSE 0.000496957; val RMSE 0.0007674481; lr 1e-05; 288s
Standard Linear Baseline Validation RMSE: 0.000717312

Network seed 2, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-1.7898,"[-2.41%, -1.24%]",0.0058,0.0,0.5717
MLP,0.0007,-29.0228,"[-42.73%, -18.27%]",0.1946,3233.3227,0.3053

network 2, training 5, epoch 1: train scaled MSE 0.884093; val RMSE 0.0124391; lr 0.001; 0s
network 2, training 5, epoch 10: train scaled MSE 0.0122126; val RMSE 0.001580804; lr 0.001; 2s
network 2, training 5, epoch 20: train scaled MSE 0.00379091; val RMSE 0.001039588; lr 0.001; 4s
network 2, training 5, epoch 30: train scaled MSE 0.00400107; val RMSE 0.00102602; lr 0.001; 6s
network 2, training 5, epoch 40: train scaled MSE 0.00715777; val RMSE 0.00215872; lr 0.001; 7s
network 2, training 5, epoch 50: train scaled MSE 0.00240447; val RMSE 0.0008861075; lr 0.001; 9s
network 2, training 5, epoch 60: train scaled MSE 0.0027125; val RMSE 0.0008617153; lr 0.001; 11s
network 2, training 5, epoch 70: train scaled MSE 0.00169494; val RMSE 0.0008167471; lr 0.0005; 13s
network 2, training 5, epoch 80: train scaled MSE 0.00164704; val RMSE 0.0008047025; lr 0.0005; 15s
network 2, training 5, epoch 90: train scaled MSE 0.00166646; val RMSE 0.0007990082; lr 0.0005; 17s
network 2, training 5, epoch 100: train scaled MSE 0.00164192; val RMSE 0.0008143364; lr 0.0005; 19s
network 2, training 5, epoch 110: train scaled MSE 0.00141533; val RMSE 0.0007904766; lr 0.0005; 21s
network 2, training 5, epoch 120: train scaled MSE 0.00130722; val RMSE 0.0008003221; lr 0.0005; 22s
network 2, training 5, epoch 130: train scaled MSE 0.00121592; val RMSE 0.0007840344; lr 0.0005; 24s
network 2, training 5, epoch 140: train scaled MSE 0.00112153; val RMSE 0.0007790357; lr 0.00025; 26s
network 2, training 5, epoch 150: train scaled MSE 0.00168381; val RMSE 0.0008306728; lr 0.00025; 28s
network 2, training 5, epoch 160: train scaled MSE 0.00107203; val RMSE 0.00076802; lr 0.00025; 30s
network 2, training 5, epoch 170: train scaled MSE 0.00103643; val RMSE 0.000761472; lr 0.00025; 32s
network 2, training 5, epoch 180: train scaled MSE 0.00098453; val RMSE 0.0008955394; lr 0.00025; 34s
network 2, training 5, epoch 190: train scaled MSE 0.000974813; val RMSE 0.0007578443; lr 0.000125; 36s
network 2, training 5, epoch 200: train scaled MSE 0.000901523; val RMSE 0.0007534402; lr 0.000125; 38s
network 2, training 5, epoch 210: train scaled MSE 0.000960754; val RMSE 0.0007939504; lr 0.000125; 40s
network 2, training 5, epoch 220: train scaled MSE 0.000871239; val RMSE 0.0007479245; lr 0.000125; 42s
network 2, training 5, epoch 230: train scaled MSE 0.000856645; val RMSE 0.0007471748; lr 0.000125; 44s
network 2, training 5, epoch 240: train scaled MSE 0.000838919; val RMSE 0.0007444257; lr 0.000125; 46s
network 2, training 5, epoch 250: train scaled MSE 0.000826652; val RMSE 0.0007569461; lr 0.000125; 48s
network 2, training 5, epoch 260: train scaled MSE 0.000813495; val RMSE 0.0007408542; lr 0.000125; 50s
network 2, training 5, epoch 270: train scaled MSE 0.000798068; val RMSE 0.0007387848; lr 0.000125; 52s
network 2, training 5, epoch 280: train scaled MSE 0.000781023; val RMSE 0.000736021; lr 0.000125; 54s
network 2, training 5, epoch 290: train scaled MSE 0.000754032; val RMSE 0.0007362007; lr 0.000125; 56s
network 2, training 5, epoch 300: train scaled MSE 0.000737751; val RMSE 0.0007354682; lr 0.000125; 58s
network 2, training 5, epoch 310: train scaled MSE 0.00088751; val RMSE 0.0007365104; lr 0.000125; 60s
network 2, training 5, epoch 320: train scaled MSE 0.00072308; val RMSE 0.000730503; lr 0.000125; 61s
network 2, training 5, epoch 330: train scaled MSE 0.00070568; val RMSE 0.0007805762; lr 0.000125; 63s
network 2, training 5, epoch 340: train scaled MSE 0.000685461; val RMSE 0.0007281825; lr 0.000125; 65s
network 2, training 5, epoch 350: train scaled MSE 0.000678745; val RMSE 0.0007276902; lr 0.000125; 67s
network 2, training 5, epoch 360: train scaled MSE 0.000668158; val RMSE 0.0007257333; lr 0.000125; 69s
network 2, training 5, epoch 370: train scaled MSE 0.00064687; val RMSE 0.0007297031; lr 0.000125; 71s
network 2, training 5, epoch 380: train scaled MSE 0.00116322; val RMSE 0.0007380102; lr 0.000125; 73s
network 2, training 5, epoch 390: train scaled MSE 0.000611694; val RMSE 0.0007397084; lr 6.25e-05; 75s
network 2, training 5, epoch 400: train scaled MSE 0.000606918; val RMSE 0.0007201568; lr 6.25e-05; 77s
network 2, training 5, epoch 410: train scaled MSE 0.000621465; val RMSE 0.0007207379; lr 6.25e-05; 79s
network 2, training 5, epoch 420: train scaled MSE 0.000599049; val RMSE 0.000719241; lr 6.25e-05; 81s
network 2, training 5, epoch 430: train scaled MSE 0.000586408; val RMSE 0.0007187399; lr 6.25e-05; 83s
network 2, training 5, epoch 440: train scaled MSE 0.000580948; val RMSE 0.0007180389; lr 6.25e-05; 85s
network 2, training 5, epoch 450: train scaled MSE 0.000588204; val RMSE 0.0007183259; lr 6.25e-05; 87s
network 2, training 5, epoch 460: train scaled MSE 0.000562657; val RMSE 0.0007210604; lr 3.125e-05; 89s
network 2, training 5, epoch 470: train scaled MSE 0.000560316; val RMSE 0.0007159238; lr 3.125e-05; 91s
network 2, training 5, epoch 480: train scaled MSE 0.000560036; val RMSE 0.0007159374; lr 3.125e-05; 93s
network 2, training 5, epoch 490: train scaled MSE 0.0005548; val RMSE 0.000716064; lr 3.125e-05; 95s
network 2, training 5, epoch 500: train scaled MSE 0.000553694; val RMSE 0.0007147069; lr 3.125e-05; 97s
network 2, training 5, epoch 510: train scaled MSE 0.000549987; val RMSE 0.0007293704; lr 3.125e-05; 98s
network 2, training 5, epoch 520: train scaled MSE 0.000542001; val RMSE 0.0007136417; lr 1.5625e-05; 100s
network 2, training 5, epoch 530: train scaled MSE 0.000541058; val RMSE 0.0007137689; lr 1.5625e-05; 102s
network 2, training 5, epoch 540: train scaled MSE 0.00053883; val RMSE 0.000713662; lr 1e-05; 104s
network 2, training 5, epoch 550: train scaled MSE 0.000536187; val RMSE 0.0007131216; lr 1e-05; 106s
network 2, training 5, epoch 560: train scaled MSE 0.000546647; val RMSE 0.0007134565; lr 1e-05; 108s
network 2, training 5, epoch 570: train scaled MSE 0.000535465; val RMSE 0.0007131473; lr 1e-05; 110s
network 2, training 5, epoch 580: train scaled MSE 0.000542965; val RMSE 0.0007133506; lr 1e-05; 112s
network 2, training 5, epoch 590: train scaled MSE 0.000567691; val RMSE 0.0007141985; lr 1e-05; 114s
network 2, training 5, epoch 600: train scaled MSE 0.000531518; val RMSE 0.0007125028; lr 1e-05; 116s
network 2, training 5, epoch 610: train scaled MSE 0.000530728; val RMSE 0.0007128139; lr 1e-05; 118s
network 2, training 5, epoch 620: train scaled MSE 0.00052988; val RMSE 0.0007125594; lr 1e-05; 120s
network 2, training 5, epoch 630: train scaled MSE 0.000539015; val RMSE 0.0007128273; lr 1e-05; 121s
network 2, training 5, epoch 640: train scaled MSE 0.000530301; val RMSE 0.0007129038; lr 1e-05; 123s
network 2, training 5, epoch 650: train scaled MSE 0.000529023; val RMSE 0.0007122629; lr 1e-05; 125s
network 2, training 5, epoch 660: train scaled MSE 0.00052675; val RMSE 0.0007126694; lr 1e-05; 127s
network 2, training 5, epoch 670: train scaled MSE 0.000527407; val RMSE 0.0007119156; lr 1e-05; 129s
network 2, training 5, epoch 680: train scaled MSE 0.000528743; val RMSE 0.0007129216; lr 1e-05; 131s
network 2, training 5, epoch 690: train scaled MSE 0.000525212; val RMSE 0.0007117754; lr 1e-05; 133s
network 2, training 5, epoch 700: train scaled MSE 0.000523677; val RMSE 0.000711858; lr 1e-05; 135s
network 2, training 5, epoch 710: train scaled MSE 0.000522983; val RMSE 0.0007117532; lr 1e-05; 137s
network 2, training 5, epoch 720: train scaled MSE 0.000524824; val RMSE 0.0007121991; lr 1e-05; 139s
network 2, training 5, epoch 730: train scaled MSE 0.000576457; val RMSE 0.0007145056; lr 1e-05; 141s
Standard Linear Baseline Validation RMSE: 0.0006179261

Network seed 2, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-1.6411,"[-2.35%, -1.09%]",0.0007,0.0,0.5608
MLP,0.0007,-26.1891,"[-42.45%, -16.05%]",0.1875,26732.2238,0.3056

network 2, training 6, epoch 1: train scaled MSE 0.880926; val RMSE 0.01167975; lr 0.001; 0s
network 2, training 6, epoch 10: train scaled MSE 0.0133997; val RMSE 0.001885785; lr 0.001; 2s
network 2, training 6, epoch 20: train scaled MSE 0.00506652; val RMSE 0.001028905; lr 0.001; 4s
network 2, training 6, epoch 30: train scaled MSE 0.004174; val RMSE 0.0009516882; lr 0.001; 6s
network 2, training 6, epoch 40: train scaled MSE 0.00357012; val RMSE 0.000940548; lr 0.001; 8s
network 2, training 6, epoch 50: train scaled MSE 0.00687201; val RMSE 0.00134875; lr 0.001; 10s
network 2, training 6, epoch 60: train scaled MSE 0.0029966; val RMSE 0.0008770118; lr 0.001; 12s
network 2, training 6, epoch 70: train scaled MSE 0.00256451; val RMSE 0.0009077465; lr 0.001; 14s
network 2, training 6, epoch 80: train scaled MSE 0.00199799; val RMSE 0.0008890952; lr 0.0005; 16s
network 2, training 6, epoch 90: train scaled MSE 0.00216679; val RMSE 0.0008816162; lr 0.0005; 18s
network 2, training 6, epoch 100: train scaled MSE 0.00176961; val RMSE 0.0008220048; lr 0.0005; 19s
network 2, training 6, epoch 110: train scaled MSE 0.00167739; val RMSE 0.0008512861; lr 0.0005; 21s
network 2, training 6, epoch 120: train scaled MSE 0.00269239; val RMSE 0.0008439443; lr 0.0005; 23s
network 2, training 6, epoch 130: train scaled MSE 0.00138647; val RMSE 0.0007969307; lr 0.00025; 25s
network 2, training 6, epoch 140: train scaled MSE 0.001396; val RMSE 0.0007958439; lr 0.00025; 27s
network 2, training 6, epoch 150: train scaled MSE 0.00136975; val RMSE 0.0008758825; lr 0.00025; 29s
network 2, training 6, epoch 160: train scaled MSE 0.00126144; val RMSE 0.000801822; lr 0.00025; 31s
network 2, training 6, epoch 170: train scaled MSE 0.00123582; val RMSE 0.0008170307; lr 0.000125; 33s
network 2, training 6, epoch 180: train scaled MSE 0.00113952; val RMSE 0.0007734975; lr 0.000125; 35s
network 2, training 6, epoch 190: train scaled MSE 0.00111868; val RMSE 0.0007736405; lr 0.000125; 37s
network 2, training 6, epoch 200: train scaled MSE 0.0010889; val RMSE 0.0008281068; lr 0.000125; 39s
network 2, training 6, epoch 210: train scaled MSE 0.00108471; val RMSE 0.0007719641; lr 6.25e-05; 41s
network 2, training 6, epoch 220: train scaled MSE 0.00128563; val RMSE 0.0007811702; lr 6.25e-05; 43s
network 2, training 6, epoch 230: train scaled MSE 0.00102734; val RMSE 0.0007678175; lr 3.125e-05; 46s
network 2, training 6, epoch 240: train scaled MSE 0.00101821; val RMSE 0.0007678904; lr 1.5625e-05; 48s
network 2, training 6, epoch 250: train scaled MSE 0.00100673; val RMSE 0.0007655138; lr 1.5625e-05; 50s
network 2, training 6, epoch 260: train scaled MSE 0.00103025; val RMSE 0.0007693332; lr 1.5625e-05; 52s
network 2, training 6, epoch 270: train scaled MSE 0.000999237; val RMSE 0.000765448; lr 1e-05; 54s
network 2, training 6, epoch 280: train scaled MSE 0.000996653; val RMSE 0.0007647624; lr 1e-05; 56s
network 2, training 6, epoch 290: train scaled MSE 0.000992143; val RMSE 0.0007642795; lr 1e-05; 58s
network 2, training 6, epoch 300: train scaled MSE 0.000990752; val RMSE 0.0007641421; lr 1e-05; 60s
network 2, training 6, epoch 310: train scaled MSE 0.000990253; val RMSE 0.000763663; lr 1e-05; 62s
network 2, training 6, epoch 320: train scaled MSE 0.000987385; val RMSE 0.0007637255; lr 1e-05; 64s
network 2, training 6, epoch 330: train scaled MSE 0.000996517; val RMSE 0.0007632198; lr 1e-05; 66s
network 2, training 6, epoch 340: train scaled MSE 0.000984344; val RMSE 0.0007630708; lr 1e-05; 67s
network 2, training 6, epoch 350: train scaled MSE 0.000978966; val RMSE 0.0007624351; lr 1e-05; 69s
network 2, training 6, epoch 360: train scaled MSE 0.000976668; val RMSE 0.0007622624; lr 1e-05; 71s
network 2, training 6, epoch 370: train scaled MSE 0.00097474; val RMSE 0.0007621505; lr 1e-05; 73s
network 2, training 6, epoch 380: train scaled MSE 0.0010064; val RMSE 0.0007636537; lr 1e-05; 75s
network 2, training 6, epoch 390: train scaled MSE 0.000971712; val RMSE 0.0007618715; lr 1e-05; 77s
network 2, training 6, epoch 400: train scaled MSE 0.000982765; val RMSE 0.0007616904; lr 1e-05; 79s
network 2, training 6, epoch 410: train scaled MSE 0.000965727; val RMSE 0.0007611314; lr 1e-05; 81s
network 2, training 6, epoch 420: train scaled MSE 0.000971369; val RMSE 0.0007607304; lr 1e-05; 83s
network 2, training 6, epoch 430: train scaled MSE 0.000961417; val RMSE 0.0007601774; lr 1e-05; 85s
network 2, training 6, epoch 440: train scaled MSE 0.000969147; val RMSE 0.000761635; lr 1e-05; 87s
network 2, training 6, epoch 450: train scaled MSE 0.000956913; val RMSE 0.000761033; lr 1e-05; 90s
network 2, training 6, epoch 460: train scaled MSE 0.000958036; val RMSE 0.0007606837; lr 1e-05; 92s
Standard Linear Baseline Validation RMSE: 0.0006858866

Network seed 2, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-2.4388,"[-3.25%, -1.75%]",0.0060,0.0,0.5675
MLP,0.0007,-46.4549,"[-64.65%, -34.68%]",0.1331,2118.1203,0.1801

network 2, training 7, epoch 1: train scaled MSE 0.884024; val RMSE 0.01168148; lr 0.001; 0s
network 2, training 7, epoch 10: train scaled MSE 0.0147534; val RMSE 0.002330568; lr 0.001; 2s
network 2, training 7, epoch 20: train scaled MSE 0.0052787; val RMSE 0.00101177; lr 0.001; 4s
network 2, training 7, epoch 30: train scaled MSE 0.0049434; val RMSE 0.0009347838; lr 0.001; 7s
network 2, training 7, epoch 40: train scaled MSE 0.0031821; val RMSE 0.0008542363; lr 0.001; 9s
network 2, training 7, epoch 50: train scaled MSE 0.00274898; val RMSE 0.0007967205; lr 0.001; 11s
network 2, training 7, epoch 60: train scaled MSE 0.00326092; val RMSE 0.0008205204; lr 0.001; 13s
network 2, training 7, epoch 70: train scaled MSE 0.00252; val RMSE 0.0007757106; lr 0.001; 15s
network 2, training 7, epoch 80: train scaled MSE 0.00162383; val RMSE 0.0008879295; lr 0.0005; 17s
network 2, training 7, epoch 90: train scaled MSE 0.00156153; val RMSE 0.0006990006; lr 0.0005; 19s
network 2, training 7, epoch 100: train scaled MSE 0.00140461; val RMSE 0.0006954077; lr 0.0005; 21s
network 2, training 7, epoch 110: train scaled MSE 0.00133543; val RMSE 0.002549981; lr 0.0005; 23s
network 2, training 7, epoch 120: train scaled MSE 0.00150759; val RMSE 0.000700607; lr 0.00025; 25s
network 2, training 7, epoch 130: train scaled MSE 0.00115478; val RMSE 0.0006821114; lr 0.00025; 27s
network 2, training 7, epoch 140: train scaled MSE 0.00111554; val RMSE 0.0007354603; lr 0.00025; 29s
network 2, training 7, epoch 150: train scaled MSE 0.0034128; val RMSE 0.0007099094; lr 0.00025; 31s
network 2, training 7, epoch 160: train scaled MSE 0.00110926; val RMSE 0.0006750644; lr 0.00025; 33s
network 2, training 7, epoch 170: train scaled MSE 0.000991625; val RMSE 0.0006653627; lr 0.000125; 35s
network 2, training 7, epoch 180: train scaled MSE 0.000971102; val RMSE 0.0006639399; lr 0.000125; 37s
network 2, training 7, epoch 190: train scaled MSE 0.00118298; val RMSE 0.0006672055; lr 0.000125; 39s
network 2, training 7, epoch 200: train scaled MSE 0.000942959; val RMSE 0.0006587098; lr 0.000125; 41s
network 2, training 7, epoch 210: train scaled MSE 0.000915018; val RMSE 0.000658295; lr 0.000125; 43s
network 2, training 7, epoch 220: train scaled MSE 0.00115967; val RMSE 0.0007569521; lr 0.000125; 45s
network 2, training 7, epoch 230: train scaled MSE 0.000868388; val RMSE 0.0006530731; lr 0.000125; 47s
network 2, training 7, epoch 240: train scaled MSE 0.000845264; val RMSE 0.000657263; lr 0.000125; 48s
network 2, training 7, epoch 250: train scaled MSE 0.000892184; val RMSE 0.0006539354; lr 0.000125; 50s
network 2, training 7, epoch 260: train scaled MSE 0.000824064; val RMSE 0.0006507097; lr 0.000125; 52s
network 2, training 7, epoch 270: train scaled MSE 0.000807843; val RMSE 0.0006486133; lr 6.25e-05; 54s
network 2, training 7, epoch 280: train scaled MSE 0.000770681; val RMSE 0.0006468508; lr 6.25e-05; 56s
network 2, training 7, epoch 290: train scaled MSE 0.000761739; val RMSE 0.0006456414; lr 6.25e-05; 58s
network 2, training 7, epoch 300: train scaled MSE 0.000741879; val RMSE 0.0006443894; lr 3.125e-05; 59s
network 2, training 7, epoch 310: train scaled MSE 0.000741269; val RMSE 0.0006434004; lr 3.125e-05; 61s
network 2, training 7, epoch 320: train scaled MSE 0.000729961; val RMSE 0.0006425837; lr 3.125e-05; 63s
network 2, training 7, epoch 330: train scaled MSE 0.000724778; val RMSE 0.0006422961; lr 3.125e-05; 65s
network 2, training 7, epoch 340: train scaled MSE 0.000721481; val RMSE 0.0006423317; lr 3.125e-05; 67s
network 2, training 7, epoch 350: train scaled MSE 0.00071654; val RMSE 0.0006424237; lr 3.125e-05; 69s
network 2, training 7, epoch 360: train scaled MSE 0.00071867; val RMSE 0.0006413908; lr 3.125e-05; 71s
network 2, training 7, epoch 370: train scaled MSE 0.000730456; val RMSE 0.0006411739; lr 1.5625e-05; 72s
network 2, training 7, epoch 380: train scaled MSE 0.000699442; val RMSE 0.0006399867; lr 1e-05; 74s
network 2, training 7, epoch 390: train scaled MSE 0.000697039; val RMSE 0.0006398329; lr 1e-05; 76s
network 2, training 7, epoch 400: train scaled MSE 0.000695707; val RMSE 0.0006396068; lr 1e-05; 78s
network 2, training 7, epoch 410: train scaled MSE 0.000694264; val RMSE 0.0006394872; lr 1e-05; 80s
network 2, training 7, epoch 420: train scaled MSE 0.000692513; val RMSE 0.0006394199; lr 1e-05; 82s
network 2, training 7, epoch 430: train scaled MSE 0.000702908; val RMSE 0.000642399; lr 1e-05; 84s
network 2, training 7, epoch 440: train scaled MSE 0.00068931; val RMSE 0.000639172; lr 1e-05; 86s
network 2, training 7, epoch 450: train scaled MSE 0.000687419; val RMSE 0.000638941; lr 1e-05; 87s
network 2, training 7, epoch 460: train scaled MSE 0.000685592; val RMSE 0.0006386711; lr 1e-05; 89s
network 2, training 7, epoch 470: train scaled MSE 0.000688182; val RMSE 0.0006387269; lr 1e-05; 91s
network 2, training 7, epoch 480: train scaled MSE 0.000682995; val RMSE 0.000638488; lr 1e-05; 93s
network 2, training 7, epoch 490: train scaled MSE 0.000681474; val RMSE 0.0006383208; lr 1e-05; 95s
network 2, training 7, epoch 500: train scaled MSE 0.000679535; val RMSE 0.0006381818; lr 1e-05; 97s
network 2, training 7, epoch 510: train scaled MSE 0.000677688; val RMSE 0.0006383345; lr 1e-05; 100s
network 2, training 7, epoch 520: train scaled MSE 0.000690367; val RMSE 0.0006386226; lr 1e-05; 102s
network 2, training 7, epoch 530: train scaled MSE 0.00067414; val RMSE 0.0006379532; lr 1e-05; 104s
network 2, training 7, epoch 540: train scaled MSE 0.00067649; val RMSE 0.0006385069; lr 1e-05; 106s
network 2, training 7, epoch 550: train scaled MSE 0.000683625; val RMSE 0.0006394919; lr 1e-05; 108s
network 2, training 7, epoch 560: train scaled MSE 0.000669734; val RMSE 0.0006378503; lr 1e-05; 110s
network 2, training 7, epoch 570: train scaled MSE 0.000669253; val RMSE 0.0006376703; lr 1e-05; 113s
network 2, training 7, epoch 580: train scaled MSE 0.000669643; val RMSE 0.0006378287; lr 1e-05; 114s
network 2, training 7, epoch 590: train scaled MSE 0.000666339; val RMSE 0.000637739; lr 1e-05; 116s
network 2, training 7, epoch 600: train scaled MSE 0.00066561; val RMSE 0.0006373514; lr 1e-05; 118s
network 2, training 7, epoch 610: train scaled MSE 0.000663366; val RMSE 0.0006371963; lr 1e-05; 120s
network 2, training 7, epoch 620: train scaled MSE 0.000661923; val RMSE 0.0006393519; lr 1e-05; 122s
network 2, training 7, epoch 630: train scaled MSE 0.000663074; val RMSE 0.0006371149; lr 1e-05; 124s
network 2, training 7, epoch 640: train scaled MSE 0.000663073; val RMSE 0.0006368065; lr 1e-05; 126s
network 2, training 7, epoch 650: train scaled MSE 0.000666228; val RMSE 0.0006369436; lr 1e-05; 128s
network 2, training 7, epoch 660: train scaled MSE 0.000656601; val RMSE 0.000636558; lr 1e-05; 130s
network 2, training 7, epoch 670: train scaled MSE 0.000662968; val RMSE 0.0006369256; lr 1e-05; 132s
network 2, training 7, epoch 680: train scaled MSE 0.000671157; val RMSE 0.0006379185; lr 1e-05; 133s
network 2, training 7, epoch 690: train scaled MSE 0.000653215; val RMSE 0.0006362676; lr 1e-05; 135s
network 2, training 7, epoch 700: train scaled MSE 0.000651633; val RMSE 0.0006361502; lr 1e-05; 137s
network 2, training 7, epoch 710: train scaled MSE 0.000649653; val RMSE 0.000635829; lr 1e-05; 139s
network 2, training 7, epoch 720: train scaled MSE 0.000648356; val RMSE 0.0006377688; lr 1e-05; 141s
network 2, training 7, epoch 730: train scaled MSE 0.000646857; val RMSE 0.0006357242; lr 1e-05; 143s
network 2, training 7, epoch 740: train scaled MSE 0.00064588; val RMSE 0.0006356762; lr 1e-05; 145s
network 2, training 7, epoch 750: train scaled MSE 0.000645112; val RMSE 0.0006356683; lr 1e-05; 147s
network 2, training 7, epoch 760: train scaled MSE 0.000647173; val RMSE 0.0006357981; lr 1e-05; 148s
network 2, training 7, epoch 770: train scaled MSE 0.000640718; val RMSE 0.0006357564; lr 1e-05; 150s
network 2, training 7, epoch 780: train scaled MSE 0.000641599; val RMSE 0.0006356632; lr 1e-05; 152s
network 2, training 7, epoch 790: train scaled MSE 0.000639752; val RMSE 0.0006353605; lr 1e-05; 154s
network 2, training 7, epoch 800: train scaled MSE 0.00066585; val RMSE 0.0006368547; lr 1e-05; 156s
network 2, training 7, epoch 810: train scaled MSE 0.000635199; val RMSE 0.0006349107; lr 1e-05; 158s
network 2, training 7, epoch 820: train scaled MSE 0.000633415; val RMSE 0.0006359604; lr 1e-05; 160s
network 2, training 7, epoch 830: train scaled MSE 0.000633642; val RMSE 0.0006353069; lr 1e-05; 162s
network 2, training 7, epoch 840: train scaled MSE 0.000631427; val RMSE 0.0006348512; lr 1e-05; 163s
network 2, training 7, epoch 850: train scaled MSE 0.000633945; val RMSE 0.000635481; lr 1e-05; 165s
network 2, training 7, epoch 860: train scaled MSE 0.000629952; val RMSE 0.0006347784; lr 1e-05; 167s
network 2, training 7, epoch 870: train scaled MSE 0.00062876; val RMSE 0.0006346437; lr 1e-05; 169s
network 2, training 7, epoch 880: train scaled MSE 0.00062777; val RMSE 0.0006346219; lr 1e-05; 171s
network 2, training 7, epoch 890: train scaled MSE 0.000627143; val RMSE 0.0006345786; lr 1e-05; 173s
network 2, training 7, epoch 900: train scaled MSE 0.000632968; val RMSE 0.0006349406; lr 1e-05; 175s
network 2, training 7, epoch 910: train scaled MSE 0.000623096; val RMSE 0.0006341015; lr 1e-05; 177s
network 2, training 7, epoch 920: train scaled MSE 0.000623615; val RMSE 0.0006341975; lr 1e-05; 179s
network 2, training 7, epoch 930: train scaled MSE 0.000622265; val RMSE 0.0006343614; lr 1e-05; 181s
network 2, training 7, epoch 940: train scaled MSE 0.000620291; val RMSE 0.0006340176; lr 1e-05; 183s
network 2, training 7, epoch 950: train scaled MSE 0.000619176; val RMSE 0.0006344067; lr 1e-05; 184s
network 2, training 7, epoch 960: train scaled MSE 0.000621256; val RMSE 0.0006341903; lr 1e-05; 186s
network 2, training 7, epoch 970: train scaled MSE 0.000616253; val RMSE 0.0006338158; lr 1e-05; 188s
network 2, training 7, epoch 980: train scaled MSE 0.000614996; val RMSE 0.0006336992; lr 1e-05; 190s
network 2, training 7, epoch 990: train scaled MSE 0.000613711; val RMSE 0.0006337517; lr 1e-05; 192s
network 2, training 7, epoch 1000: train scaled MSE 0.000633936; val RMSE 0.0006344106; lr 1e-05; 194s
network 2, training 7, epoch 1010: train scaled MSE 0.000611167; val RMSE 0.0006335701; lr 1e-05; 195s
network 2, training 7, epoch 1020: train scaled MSE 0.000610145; val RMSE 0.0006332967; lr 1e-05; 197s
network 2, training 7, epoch 1030: train scaled MSE 0.000614301; val RMSE 0.0006337255; lr 1e-05; 199s
network 2, training 7, epoch 1040: train scaled MSE 0.000608608; val RMSE 0.0006329141; lr 1e-05; 201s
network 2, training 7, epoch 1050: train scaled MSE 0.000606212; val RMSE 0.0006331802; lr 1e-05; 203s
network 2, training 7, epoch 1060: train scaled MSE 0.000605415; val RMSE 0.0006340165; lr 1e-05; 205s
network 2, training 7, epoch 1070: train scaled MSE 0.000603806; val RMSE 0.000632898; lr 1e-05; 206s
network 2, training 7, epoch 1080: train scaled MSE 0.000612633; val RMSE 0.0006334643; lr 1e-05; 208s
network 2, training 7, epoch 1090: train scaled MSE 0.000602413; val RMSE 0.0006332572; lr 1e-05; 210s
network 2, training 7, epoch 1100: train scaled MSE 0.000609022; val RMSE 0.0006348621; lr 1e-05; 212s
network 2, training 7, epoch 1110: train scaled MSE 0.000601411; val RMSE 0.0006350056; lr 1e-05; 214s
Standard Linear Baseline Validation RMSE: 0.0005340003

Network seed 2, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-2.1116,"[-2.66%, -1.63%]",0.0009,0.0,0.5881
MLP,0.0007,-37.5450,"[-52.45%, -25.50%]",0.1609,17883.8094,0.3025

network 2, training 8, epoch 1: train scaled MSE 0.88377; val RMSE 0.01202279; lr 0.001; 0s
network 2, training 8, epoch 10: train scaled MSE 0.0154715; val RMSE 0.001786197; lr 0.001; 2s
network 2, training 8, epoch 20: train scaled MSE 0.00517128; val RMSE 0.001090346; lr 0.001; 4s
network 2, training 8, epoch 30: train scaled MSE 0.0113203; val RMSE 0.00113565; lr 0.001; 6s
network 2, training 8, epoch 40: train scaled MSE 0.00383031; val RMSE 0.0009261726; lr 0.001; 8s
network 2, training 8, epoch 50: train scaled MSE 0.00302402; val RMSE 0.0009049896; lr 0.001; 10s
network 2, training 8, epoch 60: train scaled MSE 0.00279175; val RMSE 0.001026438; lr 0.001; 11s
network 2, training 8, epoch 70: train scaled MSE 0.00208974; val RMSE 0.0008142413; lr 0.001; 13s
network 2, training 8, epoch 80: train scaled MSE 0.00190345; val RMSE 0.001913345; lr 0.001; 15s
network 2, training 8, epoch 90: train scaled MSE 0.00152177; val RMSE 0.001022478; lr 0.0005; 17s
network 2, training 8, epoch 100: train scaled MSE 0.00141064; val RMSE 0.000845516; lr 0.0005; 19s
network 2, training 8, epoch 110: train scaled MSE 0.0013528; val RMSE 0.0007296237; lr 0.0005; 21s
network 2, training 8, epoch 120: train scaled MSE 0.00130342; val RMSE 0.0007364718; lr 0.0005; 23s
network 2, training 8, epoch 130: train scaled MSE 0.0019009; val RMSE 0.0007481464; lr 0.0005; 24s
network 2, training 8, epoch 140: train scaled MSE 0.00102968; val RMSE 0.0007139681; lr 0.00025; 26s
network 2, training 8, epoch 150: train scaled MSE 0.000993798; val RMSE 0.0007075348; lr 0.00025; 28s
network 2, training 8, epoch 160: train scaled MSE 0.000972344; val RMSE 0.0007025298; lr 0.00025; 30s
network 2, training 8, epoch 170: train scaled MSE 0.000958589; val RMSE 0.0007506682; lr 0.00025; 32s
network 2, training 8, epoch 180: train scaled MSE 0.000920019; val RMSE 0.000701676; lr 0.00025; 34s
network 2, training 8, epoch 190: train scaled MSE 0.000878996; val RMSE 0.001120209; lr 0.00025; 36s
network 2, training 8, epoch 200: train scaled MSE 0.000839292; val RMSE 0.0006976479; lr 0.00025; 38s
network 2, training 8, epoch 210: train scaled MSE 0.00081475; val RMSE 0.000875722; lr 0.00025; 40s
network 2, training 8, epoch 220: train scaled MSE 0.000754658; val RMSE 0.0007162844; lr 0.000125; 42s
network 2, training 8, epoch 230: train scaled MSE 0.000953098; val RMSE 0.0006943958; lr 0.000125; 44s
network 2, training 8, epoch 240: train scaled MSE 0.000740453; val RMSE 0.0006860271; lr 0.000125; 46s
network 2, training 8, epoch 250: train scaled MSE 0.000713867; val RMSE 0.0006853163; lr 0.000125; 48s
network 2, training 8, epoch 260: train scaled MSE 0.00070269; val RMSE 0.0007409536; lr 0.000125; 50s
network 2, training 8, epoch 270: train scaled MSE 0.00067664; val RMSE 0.000682891; lr 6.25e-05; 51s
network 2, training 8, epoch 280: train scaled MSE 0.000696394; val RMSE 0.0006893203; lr 6.25e-05; 53s
network 2, training 8, epoch 290: train scaled MSE 0.000665364; val RMSE 0.0006902956; lr 6.25e-05; 55s
network 2, training 8, epoch 300: train scaled MSE 0.000659004; val RMSE 0.0006809399; lr 6.25e-05; 57s
network 2, training 8, epoch 310: train scaled MSE 0.000654392; val RMSE 0.0006804566; lr 6.25e-05; 59s
network 2, training 8, epoch 320: train scaled MSE 0.000673367; val RMSE 0.0006798933; lr 6.25e-05; 61s
network 2, training 8, epoch 330: train scaled MSE 0.000640054; val RMSE 0.0006787513; lr 6.25e-05; 63s
network 2, training 8, epoch 340: train scaled MSE 0.000634488; val RMSE 0.0006917634; lr 6.25e-05; 64s
network 2, training 8, epoch 350: train scaled MSE 0.000644573; val RMSE 0.0006794533; lr 6.25e-05; 66s
network 2, training 8, epoch 360: train scaled MSE 0.000624298; val RMSE 0.0006776714; lr 6.25e-05; 68s
network 2, training 8, epoch 370: train scaled MSE 0.000617161; val RMSE 0.0006965458; lr 6.25e-05; 70s
network 2, training 8, epoch 380: train scaled MSE 0.000616052; val RMSE 0.0006764644; lr 6.25e-05; 72s
network 2, training 8, epoch 390: train scaled MSE 0.000610696; val RMSE 0.0006764647; lr 6.25e-05; 74s
network 2, training 8, epoch 400: train scaled MSE 0.00059736; val RMSE 0.0006755906; lr 6.25e-05; 76s
network 2, training 8, epoch 410: train scaled MSE 0.000590894; val RMSE 0.0006951915; lr 6.25e-05; 78s
network 2, training 8, epoch 420: train scaled MSE 0.000578103; val RMSE 0.0006744416; lr 3.125e-05; 80s
network 2, training 8, epoch 430: train scaled MSE 0.000576183; val RMSE 0.0006739993; lr 3.125e-05; 81s
network 2, training 8, epoch 440: train scaled MSE 0.00057777; val RMSE 0.0006741331; lr 3.125e-05; 83s
network 2, training 8, epoch 450: train scaled MSE 0.000570988; val RMSE 0.0006731491; lr 3.125e-05; 85s
network 2, training 8, epoch 460: train scaled MSE 0.000565504; val RMSE 0.000675497; lr 3.125e-05; 87s
network 2, training 8, epoch 470: train scaled MSE 0.000563217; val RMSE 0.0006752349; lr 3.125e-05; 89s
network 2, training 8, epoch 480: train scaled MSE 0.000561594; val RMSE 0.0006730393; lr 3.125e-05; 91s
network 2, training 8, epoch 490: train scaled MSE 0.00055265; val RMSE 0.0006724833; lr 1.5625e-05; 93s
network 2, training 8, epoch 500: train scaled MSE 0.000550757; val RMSE 0.0006734571; lr 1.5625e-05; 95s
network 2, training 8, epoch 510: train scaled MSE 0.000554544; val RMSE 0.000673396; lr 1.5625e-05; 97s
network 2, training 8, epoch 520: train scaled MSE 0.000546309; val RMSE 0.0006730547; lr 1e-05; 99s
network 2, training 8, epoch 530: train scaled MSE 0.000545994; val RMSE 0.0006718509; lr 1e-05; 101s
network 2, training 8, epoch 540: train scaled MSE 0.000544222; val RMSE 0.0006728561; lr 1e-05; 103s
network 2, training 8, epoch 550: train scaled MSE 0.000550234; val RMSE 0.0006717593; lr 1e-05; 105s
network 2, training 8, epoch 560: train scaled MSE 0.00054242; val RMSE 0.0006714824; lr 1e-05; 107s
network 2, training 8, epoch 570: train scaled MSE 0.000542347; val RMSE 0.0006712134; lr 1e-05; 109s
network 2, training 8, epoch 580: train scaled MSE 0.000548385; val RMSE 0.0006714694; lr 1e-05; 111s
network 2, training 8, epoch 590: train scaled MSE 0.000539433; val RMSE 0.0006711138; lr 1e-05; 113s
network 2, training 8, epoch 600: train scaled MSE 0.00056034; val RMSE 0.0006730115; lr 1e-05; 115s
network 2, training 8, epoch 610: train scaled MSE 0.000538636; val RMSE 0.0006711407; lr 1e-05; 117s
network 2, training 8, epoch 620: train scaled MSE 0.000547296; val RMSE 0.0006719459; lr 1e-05; 119s
network 2, training 8, epoch 630: train scaled MSE 0.000538595; val RMSE 0.0006709841; lr 1e-05; 121s
network 2, training 8, epoch 640: train scaled MSE 0.000534522; val RMSE 0.0006709223; lr 1e-05; 123s
network 2, training 8, epoch 650: train scaled MSE 0.000545778; val RMSE 0.0006716034; lr 1e-05; 125s
network 2, training 8, epoch 660: train scaled MSE 0.000533436; val RMSE 0.0006705363; lr 1e-05; 127s
network 2, training 8, epoch 670: train scaled MSE 0.000531817; val RMSE 0.0006702159; lr 1e-05; 129s
network 2, training 8, epoch 680: train scaled MSE 0.000533915; val RMSE 0.0006706325; lr 1e-05; 131s
network 2, training 8, epoch 690: train scaled MSE 0.000582858; val RMSE 0.0006745276; lr 1e-05; 132s
network 2, training 8, epoch 700: train scaled MSE 0.000529741; val RMSE 0.0006703968; lr 1e-05; 134s
network 2, training 8, epoch 710: train scaled MSE 0.000528304; val RMSE 0.000670701; lr 1e-05; 136s
network 2, training 8, epoch 720: train scaled MSE 0.000529695; val RMSE 0.0006703677; lr 1e-05; 138s
network 2, training 8, epoch 730: train scaled MSE 0.000526676; val RMSE 0.0006696647; lr 1e-05; 140s
network 2, training 8, epoch 740: train scaled MSE 0.0005255; val RMSE 0.0006695228; lr 1e-05; 142s
network 2, training 8, epoch 750: train scaled MSE 0.000525787; val RMSE 0.000670715; lr 1e-05; 144s
network 2, training 8, epoch 760: train scaled MSE 0.000533629; val RMSE 0.0006699107; lr 1e-05; 146s
network 2, training 8, epoch 770: train scaled MSE 0.000523027; val RMSE 0.0006694445; lr 1e-05; 148s
network 2, training 8, epoch 780: train scaled MSE 0.000544362; val RMSE 0.0006699321; lr 1e-05; 150s
network 2, training 8, epoch 790: train scaled MSE 0.000521297; val RMSE 0.0006693372; lr 1e-05; 152s
network 2, training 8, epoch 800: train scaled MSE 0.000520118; val RMSE 0.0006691798; lr 1e-05; 153s
network 2, training 8, epoch 810: train scaled MSE 0.000519734; val RMSE 0.0006693466; lr 1e-05; 155s
network 2, training 8, epoch 820: train scaled MSE 0.000519255; val RMSE 0.0006692789; lr 1e-05; 157s
network 2, training 8, epoch 830: train scaled MSE 0.000540691; val RMSE 0.0006718355; lr 1e-05; 159s
network 2, training 8, epoch 840: train scaled MSE 0.000516815; val RMSE 0.0006695892; lr 1e-05; 161s
Standard Linear Baseline Validation RMSE: 0.0005675792

Network seed 2, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-1.7656,"[-2.41%, -1.30%]",0.0022,0.0,0.5654
MLP,0.0007,-33.0860,"[-49.88%, -20.89%]",0.1782,7870.8578,0.3077

network 2, training 9, epoch 1: train scaled MSE 0.879321; val RMSE 0.01144383; lr 0.001; 0s
network 2, training 9, epoch 10: train scaled MSE 0.0133892; val RMSE 0.001912606; lr 0.001; 2s
network 2, training 9, epoch 20: train scaled MSE 0.00446825; val RMSE 0.001161909; lr 0.001; 4s
network 2, training 9, epoch 30: train scaled MSE 0.00363262; val RMSE 0.001002159; lr 0.001; 6s
network 2, training 9, epoch 40: train scaled MSE 0.003108; val RMSE 0.0008578618; lr 0.001; 8s
network 2, training 9, epoch 50: train scaled MSE 0.00252581; val RMSE 0.001065962; lr 0.001; 10s
network 2, training 9, epoch 60: train scaled MSE 0.00243558; val RMSE 0.0008287363; lr 0.001; 12s
network 2, training 9, epoch 70: train scaled MSE 0.00167921; val RMSE 0.0007835195; lr 0.0005; 14s
network 2, training 9, epoch 80: train scaled MSE 0.00162032; val RMSE 0.0009689828; lr 0.0005; 16s
network 2, training 9, epoch 90: train scaled MSE 0.00154864; val RMSE 0.000912472; lr 0.0005; 18s
network 2, training 9, epoch 100: train scaled MSE 0.00139675; val RMSE 0.0007927113; lr 0.0005; 19s
network 2, training 9, epoch 110: train scaled MSE 0.00133616; val RMSE 0.000844708; lr 0.0005; 21s
network 2, training 9, epoch 120: train scaled MSE 0.00228985; val RMSE 0.0007635849; lr 0.0005; 23s
network 2, training 9, epoch 130: train scaled MSE 0.00121261; val RMSE 0.0007740632; lr 0.0005; 25s
network 2, training 9, epoch 140: train scaled MSE 0.00109635; val RMSE 0.0007447031; lr 0.0005; 27s
network 2, training 9, epoch 150: train scaled MSE 0.00112462; val RMSE 0.0007546409; lr 0.0005; 29s
network 2, training 9, epoch 160: train scaled MSE 0.00147012; val RMSE 0.0007549282; lr 0.0005; 31s
network 2, training 9, epoch 170: train scaled MSE 0.000929123; val RMSE 0.0007513116; lr 0.0005; 33s
network 2, training 9, epoch 180: train scaled MSE 0.000893889; val RMSE 0.00136153; lr 0.0005; 35s
network 2, training 9, epoch 190: train scaled MSE 0.00159243; val RMSE 0.0007354276; lr 0.00025; 37s
network 2, training 9, epoch 200: train scaled MSE 0.000933009; val RMSE 0.0007222345; lr 0.00025; 39s
network 2, training 9, epoch 210: train scaled MSE 0.000729636; val RMSE 0.0007141387; lr 0.000125; 41s
network 2, training 9, epoch 220: train scaled MSE 0.000708547; val RMSE 0.0007097426; lr 0.000125; 43s
network 2, training 9, epoch 230: train scaled MSE 0.000674976; val RMSE 0.0007092011; lr 0.000125; 45s
network 2, training 9, epoch 240: train scaled MSE 0.000662687; val RMSE 0.0007057546; lr 0.000125; 47s
network 2, training 9, epoch 250: train scaled MSE 0.000650703; val RMSE 0.0007236183; lr 0.000125; 49s
network 2, training 9, epoch 260: train scaled MSE 0.00063775; val RMSE 0.0007056095; lr 0.000125; 51s
network 2, training 9, epoch 270: train scaled MSE 0.000630445; val RMSE 0.0007021543; lr 0.000125; 52s
network 2, training 9, epoch 280: train scaled MSE 0.000615853; val RMSE 0.0007029428; lr 0.000125; 54s
network 2, training 9, epoch 290: train scaled MSE 0.000601326; val RMSE 0.0006988053; lr 0.000125; 56s
network 2, training 9, epoch 300: train scaled MSE 0.000666274; val RMSE 0.0007661657; lr 0.000125; 58s
network 2, training 9, epoch 310: train scaled MSE 0.00061834; val RMSE 0.000757651; lr 0.000125; 60s
network 2, training 9, epoch 320: train scaled MSE 0.000569648; val RMSE 0.0006954051; lr 0.000125; 62s
network 2, training 9, epoch 330: train scaled MSE 0.000559563; val RMSE 0.000695889; lr 0.000125; 64s
network 2, training 9, epoch 340: train scaled MSE 0.000551651; val RMSE 0.0006944745; lr 0.000125; 66s
network 2, training 9, epoch 350: train scaled MSE 0.000542099; val RMSE 0.0006959737; lr 0.000125; 68s
network 2, training 9, epoch 360: train scaled MSE 0.00052618; val RMSE 0.0006943072; lr 0.000125; 70s
network 2, training 9, epoch 370: train scaled MSE 0.000525498; val RMSE 0.000694112; lr 0.000125; 72s
network 2, training 9, epoch 380: train scaled MSE 0.000535666; val RMSE 0.000692122; lr 0.000125; 74s
network 2, training 9, epoch 390: train scaled MSE 0.000682391; val RMSE 0.0006954574; lr 0.000125; 76s
network 2, training 9, epoch 400: train scaled MSE 0.00051024; val RMSE 0.0006895696; lr 6.25e-05; 78s
network 2, training 9, epoch 410: train scaled MSE 0.000591352; val RMSE 0.0006910246; lr 6.25e-05; 80s
network 2, training 9, epoch 420: train scaled MSE 0.000466281; val RMSE 0.0006875206; lr 6.25e-05; 82s
network 2, training 9, epoch 430: train scaled MSE 0.000462693; val RMSE 0.0006869867; lr 6.25e-05; 84s
network 2, training 9, epoch 440: train scaled MSE 0.000457347; val RMSE 0.0006870437; lr 6.25e-05; 86s
network 2, training 9, epoch 450: train scaled MSE 0.000462314; val RMSE 0.0006872948; lr 6.25e-05; 88s
network 2, training 9, epoch 460: train scaled MSE 0.000441427; val RMSE 0.0006843662; lr 3.125e-05; 90s
network 2, training 9, epoch 470: train scaled MSE 0.000451038; val RMSE 0.0006870482; lr 3.125e-05; 92s
network 2, training 9, epoch 480: train scaled MSE 0.000434731; val RMSE 0.0006851032; lr 1.5625e-05; 94s
network 2, training 9, epoch 490: train scaled MSE 0.000436159; val RMSE 0.0006847755; lr 1e-05; 96s
network 2, training 9, epoch 500: train scaled MSE 0.000434246; val RMSE 0.0006860047; lr 1e-05; 98s
network 2, training 9, epoch 510: train scaled MSE 0.000431449; val RMSE 0.0006867147; lr 1e-05; 100s
network 2, training 9, epoch 520: train scaled MSE 0.000431425; val RMSE 0.0006842539; lr 1e-05; 102s
network 2, training 9, epoch 530: train scaled MSE 0.000435127; val RMSE 0.000685241; lr 1e-05; 104s
network 2, training 9, epoch 540: train scaled MSE 0.000440499; val RMSE 0.0006843192; lr 1e-05; 106s
network 2, training 9, epoch 550: train scaled MSE 0.000428652; val RMSE 0.0006833855; lr 1e-05; 108s
network 2, training 9, epoch 560: train scaled MSE 0.000428679; val RMSE 0.0006835399; lr 1e-05; 110s
network 2, training 9, epoch 570: train scaled MSE 0.000426745; val RMSE 0.0006831175; lr 1e-05; 112s
network 2, training 9, epoch 580: train scaled MSE 0.000426159; val RMSE 0.0006833087; lr 1e-05; 114s
network 2, training 9, epoch 590: train scaled MSE 0.000430503; val RMSE 0.0006835576; lr 1e-05; 116s
network 2, training 9, epoch 600: train scaled MSE 0.000424598; val RMSE 0.00068374; lr 1e-05; 118s
network 2, training 9, epoch 790: train scaled MSE 0.00041244; val RMSE 0.0006811781; lr 1e-05; 156s
network 2, training 9, epoch 800: train scaled MSE 0.000411817; val RMSE 0.0006809869; lr 1e-05; 158s
network 2, training 9, epoch 810: train scaled MSE 0.000409744; val RMSE 0.0006817693; lr 1e-05; 160s
network 2, training 9, epoch 820: train scaled MSE 0.000411012; val RMSE 0.0006809348; lr 1e-05; 162s
network 2, training 9, epoch 830: train scaled MSE 0.000408491; val RMSE 0.0006804636; lr 1e-05; 164s
network 2, training 9, epoch 840: train scaled MSE 0.000409802; val RMSE 0.0006804654; lr 1e-05; 166s
network 2, training 9, epoch 850: train scaled MSE 0.000416472; val RMSE 0.0006814078; lr 1e-05; 168s
network 2, training 9, epoch 860: train scaled MSE 0.000408945; val RMSE 0.0006805227; lr 1e-05; 170s
network 2, training 9, epoch 870: train scaled MSE 0.000408325; val RMSE 0.0006808076; lr 1e-05; 172s
network 2, training 9, epoch 880: train scaled MSE 0.00040503; val RMSE 0.0006804429; lr 1e-05; 174s
network 2, training 9, epoch 890: train scaled MSE 0.000420323; val RMSE 0.0006808825; lr 1e-05; 176s
network 2, training 9, epoch 900: train scaled MSE 0.000403774; val RMSE 0.000680168; lr 1e-05; 178s
network 2, training 9, epoch 910: train scaled MSE 0.000402849; val RMSE 0.000680119; lr 1e-05; 180s
network 2, training 9, epoch 920: train scaled MSE 0.000406673; val RMSE 0.0006802635; lr 1e-05; 182s
network 2, training 9, epoch 930: train scaled MSE 0.000414196; val RMSE 0.0006802903; lr 1e-05; 184s
network 2, training 9, epoch 940: train scaled MSE 0.000401308; val RMSE 0.0006799294; lr 1e-05; 187s
network 2, training 9, epoch 950: train scaled MSE 0.000400915; val RMSE 0.0006799784; lr 1e-05; 189s
network 2, training 9, epoch 960: train scaled MSE 0.00039979; val RMSE 0.0006796565; lr 1e-05; 191s
network 2, training 9, epoch 970: train scaled MSE 0.000399242; val RMSE 0.0006794874; lr 1e-05; 193s
network 2, training 9, epoch 980: train scaled MSE 0.000399993; val RMSE 0.0006795594; lr 1e-05; 195s
network 2, training 9, epoch 990: train scaled MSE 0.000406144; val RMSE 0.0006798124; lr 1e-05; 197s
network 2, training 9, epoch 1000: train scaled MSE 0.00039788; val RMSE 0.0006795476; lr 1e-05; 200s
network 2, training 9, epoch 1010: train scaled MSE 0.000397022; val RMSE 0.0006794099; lr 1e-05; 202s
network 2, training 9, epoch 1020: train scaled MSE 0.000404796; val RMSE 0.0006800153; lr 1e-05; 204s
network 2, training 9, epoch 1030: train scaled MSE 0.000395336; val RMSE 0.0006793182; lr 1e-05; 206s
network 2, training 9, epoch 1040: train scaled MSE 0.000397196; val RMSE 0.0006793049; lr 1e-05; 209s
network 2, training 9, epoch 1050: train scaled MSE 0.000394109; val RMSE 0.0006808332; lr 1e-05; 211s
network 2, training 9, epoch 1060: train scaled MSE 0.000393845; val RMSE 0.0006790728; lr 1e-05; 213s
network 2, training 9, epoch 1070: train scaled MSE 0.00039273; val RMSE 0.0006788928; lr 1e-05; 215s
network 2, training 9, epoch 1080: train scaled MSE 0.00039205; val RMSE 0.000678805; lr 1e-05; 217s
network 2, training 9, epoch 1090: train scaled MSE 0.000392159; val RMSE 0.0006787871; lr 1e-05; 219s
network 2, training 9, epoch 1100: train scaled MSE 0.000395794; val RMSE 0.000678863; lr 1e-05; 221s
network 2, training 9, epoch 1110: train scaled MSE 0.000391297; val RMSE 0.0006805265; lr 1e-05; 223s
network 2, training 9, epoch 1120: train scaled MSE 0.000389558; val RMSE 0.0006785443; lr 1e-05; 225s
network 2, training 9, epoch 1130: train scaled MSE 0.000388742; val RMSE 0.000679366; lr 1e-05; 227s
network 2, training 9, epoch 1140: train scaled MSE 0.000388592; val RMSE 0.0006783977; lr 1e-05; 229s
network 2, training 9, epoch 1150: train scaled MSE 0.000395673; val RMSE 0.0006787181; lr 1e-05; 231s
network 2, training 9, epoch 1160: train scaled MSE 0.000387805; val RMSE 0.0006783754; lr 1e-05; 233s
network 2, training 9, epoch 1170: train scaled MSE 0.000386204; val RMSE 0.000681443; lr 1e-05; 234s
network 2, training 9, epoch 1180: train scaled MSE 0.000386003; val RMSE 0.0006787282; lr 1e-05; 236s
network 2, training 9, epoch 1190: train scaled MSE 0.000385587; val RMSE 0.0006783694; lr 1e-05; 238s
network 2, training 9, epoch 1200: train scaled MSE 0.000384869; val RMSE 0.0006781434; lr 1e-05; 240s
network 2, training 9, epoch 1210: train scaled MSE 0.00038487; val RMSE 0.0006780488; lr 1e-05; 242s
network 2, training 9, epoch 1220: train scaled MSE 0.000385382; val RMSE 0.0006778408; lr 1e-05; 244s
network 2, training 9, epoch 1230: train scaled MSE 0.000382314; val RMSE 0.000677794; lr 1e-05; 246s
network 2, training 9, epoch 1240: train scaled MSE 0.000385629; val RMSE 0.00067884; lr 1e-05; 247s
network 2, training 9, epoch 1250: train scaled MSE 0.00038187; val RMSE 0.0006779933; lr 1e-05; 249s
network 2, training 9, epoch 1260: train scaled MSE 0.000387863; val RMSE 0.0006778425; lr 1e-05; 251s
network 2, training 9, epoch 1270: train scaled MSE 0.000380277; val RMSE 0.000677526; lr 1e-05; 253s
network 2, training 9, epoch 1280: train scaled MSE 0.000380935; val RMSE 0.0006794632; lr 1e-05; 255s
network 2, training 9, epoch 1290: train scaled MSE 0.000378764; val RMSE 0.0006780027; lr 1e-05; 257s
network 2, training 9, epoch 1300: train scaled MSE 0.000379421; val RMSE 0.0006773941; lr 1e-05; 258s
network 2, training 9, epoch 1310: train scaled MSE 0.000377233; val RMSE 0.000677218; lr 1e-05; 260s
network 2, training 9, epoch 1320: train scaled MSE 0.000376704; val RMSE 0.0006771652; lr 1e-05; 262s
network 2, training 9, epoch 1330: train scaled MSE 0.000376905; val RMSE 0.0006771696; lr 1e-05; 264s
network 2, training 9, epoch 1340: train scaled MSE 0.000377148; val RMSE 0.0006777393; lr 1e-05; 266s
network 2, training 9, epoch 1350: train scaled MSE 0.000376426; val RMSE 0.0006771169; lr 1e-05; 268s
network 2, training 9, epoch 1360: train scaled MSE 0.000385145; val RMSE 0.0006784668; lr 1e-05; 269s
network 2, training 9, epoch 1370: train scaled MSE 0.000375345; val RMSE 0.0006774267; lr 1e-05; 271s
network 2, training 9, epoch 1380: train scaled MSE 0.000374069; val RMSE 0.0006769643; lr 1e-05; 273s
network 2, training 9, epoch 1390: train scaled MSE 0.000373045; val RMSE 0.0006768174; lr 1e-05; 275s
network 2, training 9, epoch 1400: train scaled MSE 0.000377666; val RMSE 0.0006771766; lr 1e-05; 277s
network 2, training 9, epoch 1410: train scaled MSE 0.000372068; val RMSE 0.0006766692; lr 1e-05; 278s
network 2, training 9, epoch 1420: train scaled MSE 0.000371612; val RMSE 0.0006767092; lr 1e-05; 280s
network 2, training 9, epoch 1430: train scaled MSE 0.000371689; val RMSE 0.0006770984; lr 1e-05; 282s
network 2, training 9, epoch 1440: train scaled MSE 0.000370403; val RMSE 0.0006765439; lr 1e-05; 284s
network 2, training 9, epoch 1450: train scaled MSE 0.00036987; val RMSE 0.0006764709; lr 1e-05; 286s
network 2, training 9, epoch 1460: train scaled MSE 0.000369003; val RMSE 0.0006763851; lr 1e-05; 288s
network 2, training 9, epoch 1470: train scaled MSE 0.000383505; val RMSE 0.000677034; lr 1e-05; 289s
network 2, training 9, epoch 1480: train scaled MSE 0.000368378; val RMSE 0.0006759126; lr 1e-05; 291s
network 2, training 9, epoch 1490: train scaled MSE 0.000367248; val RMSE 0.0006761697; lr 1e-05; 293s
network 2, training 9, epoch 1500: train scaled MSE 0.000366609; val RMSE 0.0006761836; lr 1e-05; 295s
network 2, training 9, epoch 1510: train scaled MSE 0.00036591; val RMSE 0.0006761254; lr 1e-05; 297s
network 2, training 9, epoch 1520: train scaled MSE 0.000366083; val RMSE 0.0006764093; lr 1e-05; 299s
Standard Linear Baseline Validation RMSE: 0.0006077577

Network seed 2, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-1.7567,"[-2.54%, -1.05%]",0.0151,0.0,0.5856
MLP,0.0007,-29.4903,"[-44.62%, -17.65%]",0.2213,1367.7466,0.3061

Network 3: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   15.8s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   15.9s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   16.0s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   16.1s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   16.1s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   16.3s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   16.5s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   16.6s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   16.8s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   16.9s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   17.1s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   17.2s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   17.4s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   17.6s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   17.8s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   17.9s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   18.2s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   18.4s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   18.6s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   18.8s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   19.0s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   19.3s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   19.5s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   19.8s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   20.0s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   20.3s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   20.6s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   20.9s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   21.2s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   21.5s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   21.8s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   22.1s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   22.5s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   22.8s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   23.1s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   23.5s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   23.8s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   24.2s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   24.5s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   25.0s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   25.3s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   26.1s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   26.5s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   26.9s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   27.3s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   27.7s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   28.2s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   28.6s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   29.0s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   29.5s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   29.9s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   30.4s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   30.9s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   31.4s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   31.9s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   32.3s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   32.9s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   33.4s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   33.9s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   34.4s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   34.9s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   35.4s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   36.0s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   36.6s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   37.2s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   37.8s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   38.3s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   38.9s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   39.6s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   40.1s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   40.8s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   41.5s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   42.0s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   42.7s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   43.3s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   43.9s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   44.6s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   45.3s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   46.0s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   46.6s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   47.3s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   48.0s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   48.6s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:   49.3s
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:   50.0s
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:   50.7s
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:   51.5s
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:   52.1s
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:   52.9s
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:   53.7s
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:   54.4s
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:   55.2s
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:   56.0s
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:   56.8s
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:   57.5s
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:   58.3s
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:   59.2s
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:   60.0s
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.3min finished

network 3, training 0, epoch 1: train scaled MSE 0.877128; val RMSE 0.01063712; lr 0.001; 0s
network 3, training 0, epoch 10: train scaled MSE 0.015236; val RMSE 0.001981119; lr 0.001; 2s
network 3, training 0, epoch 20: train scaled MSE 0.00629115; val RMSE 0.001287908; lr 0.001; 4s
network 3, training 0, epoch 30: train scaled MSE 0.00425858; val RMSE 0.0009553304; lr 0.001; 5s
network 3, training 0, epoch 40: train scaled MSE 0.0058496; val RMSE 0.0009187049; lr 0.001; 7s
network 3, training 0, epoch 50: train scaled MSE 0.00309354; val RMSE 0.0008669036; lr 0.001; 9s
network 3, training 0, epoch 60: train scaled MSE 0.00265593; val RMSE 0.0008755855; lr 0.001; 11s
network 3, training 0, epoch 70: train scaled MSE 0.00190115; val RMSE 0.00133352; lr 0.001; 13s
network 3, training 0, epoch 80: train scaled MSE 0.0022278; val RMSE 0.0008163496; lr 0.001; 14s
network 3, training 0, epoch 90: train scaled MSE 0.00124269; val RMSE 0.0007684725; lr 0.0005; 16s
network 3, training 0, epoch 100: train scaled MSE 0.00117231; val RMSE 0.0007802752; lr 0.0005; 18s
network 3, training 0, epoch 110: train scaled MSE 0.00111734; val RMSE 0.0007637547; lr 0.0005; 20s
network 3, training 0, epoch 120: train scaled MSE 0.00112878; val RMSE 0.0008510936; lr 0.0005; 22s
network 3, training 0, epoch 130: train scaled MSE 0.000801133; val RMSE 0.0007806787; lr 0.00025; 24s
network 3, training 0, epoch 140: train scaled MSE 0.000754995; val RMSE 0.0007509371; lr 0.00025; 26s
network 3, training 0, epoch 150: train scaled MSE 0.000954337; val RMSE 0.0007370867; lr 0.00025; 28s
network 3, training 0, epoch 160: train scaled MSE 0.000692892; val RMSE 0.0007289725; lr 0.00025; 30s
network 3, training 0, epoch 170: train scaled MSE 0.000670578; val RMSE 0.0007266747; lr 0.00025; 31s
network 3, training 0, epoch 180: train scaled MSE 0.000632021; val RMSE 0.0007250475; lr 0.00025; 33s
network 3, training 0, epoch 190: train scaled MSE 0.000859107; val RMSE 0.0007276709; lr 0.00025; 35s
network 3, training 0, epoch 200: train scaled MSE 0.000560773; val RMSE 0.00072511; lr 0.00025; 37s
network 3, training 0, epoch 210: train scaled MSE 0.00050999; val RMSE 0.0007213006; lr 0.000125; 39s
network 3, training 0, epoch 220: train scaled MSE 0.000500755; val RMSE 0.0007249941; lr 0.000125; 41s
network 3, training 0, epoch 230: train scaled MSE 0.000568685; val RMSE 0.0007090356; lr 0.000125; 43s
network 3, training 0, epoch 240: train scaled MSE 0.000494923; val RMSE 0.0007360955; lr 0.000125; 44s
network 3, training 0, epoch 250: train scaled MSE 0.000465727; val RMSE 0.0007064079; lr 0.000125; 46s
network 3, training 0, epoch 260: train scaled MSE 0.000442939; val RMSE 0.0007082057; lr 0.000125; 48s
network 3, training 0, epoch 270: train scaled MSE 0.000429643; val RMSE 0.0007025123; lr 0.000125; 50s
network 3, training 0, epoch 280: train scaled MSE 0.000415884; val RMSE 0.0007264337; lr 0.000125; 51s
network 3, training 0, epoch 290: train scaled MSE 0.000401804; val RMSE 0.0007016967; lr 0.000125; 53s
network 3, training 0, epoch 300: train scaled MSE 0.000395321; val RMSE 0.0006989977; lr 0.000125; 55s
network 3, training 0, epoch 310: train scaled MSE 0.000383354; val RMSE 0.0006973121; lr 0.000125; 57s
network 3, training 0, epoch 320: train scaled MSE 0.000494037; val RMSE 0.0007011639; lr 0.000125; 59s
network 3, training 0, epoch 330: train scaled MSE 0.000355849; val RMSE 0.0006961584; lr 0.000125; 60s
network 3, training 0, epoch 340: train scaled MSE 0.000352944; val RMSE 0.0006939199; lr 0.000125; 62s
network 3, training 0, epoch 350: train scaled MSE 0.000460364; val RMSE 0.0006967505; lr 0.000125; 64s
network 3, training 0, epoch 360: train scaled MSE 0.000317281; val RMSE 0.0006910413; lr 6.25e-05; 66s
network 3, training 0, epoch 370: train scaled MSE 0.000318951; val RMSE 0.000690159; lr 6.25e-05; 68s
network 3, training 0, epoch 380: train scaled MSE 0.000306875; val RMSE 0.0006893962; lr 6.25e-05; 69s
network 3, training 0, epoch 390: train scaled MSE 0.000303486; val RMSE 0.0006894285; lr 6.25e-05; 71s
network 3, training 0, epoch 400: train scaled MSE 0.000297907; val RMSE 0.0006882226; lr 6.25e-05; 73s
network 3, training 0, epoch 410: train scaled MSE 0.000337289; val RMSE 0.000697197; lr 6.25e-05; 75s
network 3, training 0, epoch 420: train scaled MSE 0.00028133; val RMSE 0.0006861188; lr 3.125e-05; 77s
network 3, training 0, epoch 430: train scaled MSE 0.000278853; val RMSE 0.000685651; lr 3.125e-05; 78s
network 3, training 0, epoch 440: train scaled MSE 0.000277248; val RMSE 0.0006852613; lr 3.125e-05; 80s
network 3, training 0, epoch 450: train scaled MSE 0.000274636; val RMSE 0.0006850056; lr 3.125e-05; 82s
network 3, training 0, epoch 460: train scaled MSE 0.000272037; val RMSE 0.0006848964; lr 3.125e-05; 84s
network 3, training 0, epoch 470: train scaled MSE 0.000271729; val RMSE 0.0006843191; lr 3.125e-05; 86s
network 3, training 0, epoch 480: train scaled MSE 0.000266634; val RMSE 0.0006882725; lr 3.125e-05; 87s
network 3, training 0, epoch 490: train scaled MSE 0.000265908; val RMSE 0.0006836843; lr 3.125e-05; 89s
network 3, training 0, epoch 500: train scaled MSE 0.000270782; val RMSE 0.0006838764; lr 3.125e-05; 91s
network 3, training 0, epoch 510: train scaled MSE 0.000260593; val RMSE 0.000688763; lr 3.125e-05; 93s
network 3, training 0, epoch 520: train scaled MSE 0.000257348; val RMSE 0.0006852563; lr 3.125e-05; 95s
network 3, training 0, epoch 530: train scaled MSE 0.00026572; val RMSE 0.0006822911; lr 3.125e-05; 96s
network 3, training 0, epoch 540: train scaled MSE 0.000254138; val RMSE 0.0006810389; lr 3.125e-05; 98s
network 3, training 0, epoch 550: train scaled MSE 0.000253784; val RMSE 0.0006815694; lr 3.125e-05; 100s
network 3, training 0, epoch 560: train scaled MSE 0.000259596; val RMSE 0.0006819667; lr 3.125e-05; 102s
network 3, training 0, epoch 570: train scaled MSE 0.000246694; val RMSE 0.0006811771; lr 1.5625e-05; 104s
network 3, training 0, epoch 580: train scaled MSE 0.000243813; val RMSE 0.0006803122; lr 1.5625e-05; 106s
network 3, training 0, epoch 590: train scaled MSE 0.000246557; val RMSE 0.0006803516; lr 1.5625e-05; 108s
network 3, training 0, epoch 600: train scaled MSE 0.000243351; val RMSE 0.0006799831; lr 1.5625e-05; 110s
network 3, training 0, epoch 610: train scaled MSE 0.000252374; val RMSE 0.0006803171; lr 1.5625e-05; 112s
network 3, training 0, epoch 620: train scaled MSE 0.000240306; val RMSE 0.0006796647; lr 1e-05; 113s
network 3, training 0, epoch 630: train scaled MSE 0.000237748; val RMSE 0.0006800235; lr 1e-05; 115s
network 3, training 0, epoch 640: train scaled MSE 0.00023961; val RMSE 0.0006793172; lr 1e-05; 117s
network 3, training 0, epoch 650: train scaled MSE 0.000236927; val RMSE 0.0006793831; lr 1e-05; 119s
network 3, training 0, epoch 660: train scaled MSE 0.000236234; val RMSE 0.0006792512; lr 1e-05; 121s
network 3, training 0, epoch 670: train scaled MSE 0.000236141; val RMSE 0.000679297; lr 1e-05; 123s
network 3, training 0, epoch 680: train scaled MSE 0.000234811; val RMSE 0.0006790349; lr 1e-05; 125s
network 3, training 0, epoch 690: train scaled MSE 0.000245841; val RMSE 0.000679843; lr 1e-05; 127s
network 3, training 0, epoch 700: train scaled MSE 0.000235488; val RMSE 0.0006792213; lr 1e-05; 129s
network 3, training 0, epoch 710: train scaled MSE 0.000232826; val RMSE 0.000678894; lr 1e-05; 130s
network 3, training 0, epoch 720: train scaled MSE 0.00023713; val RMSE 0.000679193; lr 1e-05; 132s
network 3, training 0, epoch 730: train scaled MSE 0.000231802; val RMSE 0.0006784186; lr 1e-05; 134s
network 3, training 0, epoch 740: train scaled MSE 0.000231785; val RMSE 0.0006784767; lr 1e-05; 136s
network 3, training 0, epoch 750: train scaled MSE 0.000238114; val RMSE 0.0006786287; lr 1e-05; 138s
network 3, training 0, epoch 760: train scaled MSE 0.000230627; val RMSE 0.0006782774; lr 1e-05; 140s
network 3, training 0, epoch 770: train scaled MSE 0.000230248; val RMSE 0.0006781541; lr 1e-05; 142s
network 3, training 0, epoch 780: train scaled MSE 0.000229806; val RMSE 0.0006781965; lr 1e-05; 143s
network 3, training 0, epoch 790: train scaled MSE 0.000231098; val RMSE 0.0006778363; lr 1e-05; 145s
network 3, training 0, epoch 800: train scaled MSE 0.000227818; val RMSE 0.0006777812; lr 1e-05; 147s
network 3, training 0, epoch 810: train scaled MSE 0.00023032; val RMSE 0.0006780276; lr 1e-05; 149s
network 3, training 0, epoch 820: train scaled MSE 0.000227053; val RMSE 0.0006776707; lr 1e-05; 151s
network 3, training 0, epoch 830: train scaled MSE 0.000229277; val RMSE 0.0006777353; lr 1e-05; 153s
network 3, training 0, epoch 840: train scaled MSE 0.000227497; val RMSE 0.0006777829; lr 1e-05; 155s
network 3, training 0, epoch 850: train scaled MSE 0.000225394; val RMSE 0.0006774136; lr 1e-05; 157s
network 3, training 0, epoch 860: train scaled MSE 0.000224503; val RMSE 0.0006773429; lr 1e-05; 159s
network 3, training 0, epoch 870: train scaled MSE 0.000224119; val RMSE 0.0006771578; lr 1e-05; 161s
network 3, training 0, epoch 880: train scaled MSE 0.000223578; val RMSE 0.0006769205; lr 1e-05; 162s
network 3, training 0, epoch 890: train scaled MSE 0.000223148; val RMSE 0.0006769191; lr 1e-05; 164s
network 3, training 0, epoch 900: train scaled MSE 0.000223505; val RMSE 0.0006770005; lr 1e-05; 166s
network 3, training 0, epoch 910: train scaled MSE 0.000230333; val RMSE 0.0006767888; lr 1e-05; 168s
network 3, training 0, epoch 920: train scaled MSE 0.000221935; val RMSE 0.0006769507; lr 1e-05; 170s
network 3, training 0, epoch 930: train scaled MSE 0.000221086; val RMSE 0.0006771373; lr 1e-05; 172s
network 3, training 0, epoch 940: train scaled MSE 0.000221623; val RMSE 0.000676778; lr 1e-05; 174s
network 3, training 0, epoch 950: train scaled MSE 0.000221497; val RMSE 0.0006769806; lr 1e-05; 176s
network 3, training 0, epoch 960: train scaled MSE 0.000219105; val RMSE 0.0006763381; lr 1e-05; 177s
network 3, training 0, epoch 970: train scaled MSE 0.000218695; val RMSE 0.0006763228; lr 1e-05; 179s
network 3, training 0, epoch 980: train scaled MSE 0.000218053; val RMSE 0.0006758744; lr 1e-05; 181s
network 3, training 0, epoch 990: train scaled MSE 0.00021773; val RMSE 0.0006761334; lr 1e-05; 183s
network 3, training 0, epoch 1000: train scaled MSE 0.000217083; val RMSE 0.0006760564; lr 1e-05; 185s
network 3, training 0, epoch 1010: train scaled MSE 0.000217086; val RMSE 0.0006758953; lr 1e-05; 187s
network 3, training 0, epoch 1020: train scaled MSE 0.000215673; val RMSE 0.0006758329; lr 1e-05; 188s
network 3, training 0, epoch 1030: train scaled MSE 0.000215924; val RMSE 0.0006758318; lr 1e-05; 190s
network 3, training 0, epoch 1040: train scaled MSE 0.000215033; val RMSE 0.0006757534; lr 1e-05; 192s
network 3, training 0, epoch 1050: train scaled MSE 0.000214446; val RMSE 0.0006755394; lr 1e-05; 194s
network 3, training 0, epoch 1060: train scaled MSE 0.000213535; val RMSE 0.0006755367; lr 1e-05; 196s
network 3, training 0, epoch 1070: train scaled MSE 0.000212992; val RMSE 0.0006754; lr 1e-05; 197s
network 3, training 0, epoch 1080: train scaled MSE 0.00021255; val RMSE 0.0006752102; lr 1e-05; 199s
network 3, training 0, epoch 1090: train scaled MSE 0.000212197; val RMSE 0.0006763108; lr 1e-05; 201s
network 3, training 0, epoch 1100: train scaled MSE 0.000211798; val RMSE 0.0006752188; lr 1e-05; 203s
network 3, training 0, epoch 1110: train scaled MSE 0.000211061; val RMSE 0.0006750727; lr 1e-05; 205s
network 3, training 0, epoch 1120: train scaled MSE 0.000210462; val RMSE 0.0006763248; lr 1e-05; 207s
network 3, training 0, epoch 1130: train scaled MSE 0.000209783; val RMSE 0.0006747951; lr 1e-05; 209s
network 3, training 0, epoch 1140: train scaled MSE 0.00020931; val RMSE 0.0006748032; lr 1e-05; 210s
network 3, training 0, epoch 1150: train scaled MSE 0.000209452; val RMSE 0.0006746326; lr 1e-05; 212s
network 3, training 0, epoch 1160: train scaled MSE 0.0002092; val RMSE 0.0006748464; lr 1e-05; 214s
network 3, training 0, epoch 1170: train scaled MSE 0.00020788; val RMSE 0.0006749921; lr 1e-05; 216s
network 3, training 0, epoch 1180: train scaled MSE 0.000207081; val RMSE 0.0006752823; lr 1e-05; 218s
network 3, training 0, epoch 1190: train scaled MSE 0.000207285; val RMSE 0.0006753972; lr 1e-05; 220s
network 3, training 0, epoch 1200: train scaled MSE 0.000205706; val RMSE 0.0006742272; lr 1e-05; 222s
network 3, training 0, epoch 1210: train scaled MSE 0.000212808; val RMSE 0.0006742978; lr 1e-05; 223s
network 3, training 0, epoch 1220: train scaled MSE 0.000205406; val RMSE 0.0006740868; lr 1e-05; 225s
network 3, training 0, epoch 1230: train scaled MSE 0.000206399; val RMSE 0.0006745902; lr 1e-05; 227s
network 3, training 0, epoch 1240: train scaled MSE 0.000203723; val RMSE 0.0006738715; lr 1e-05; 229s
network 3, training 0, epoch 1250: train scaled MSE 0.000204823; val RMSE 0.0006739645; lr 1e-05; 231s
network 3, training 0, epoch 1260: train scaled MSE 0.000203321; val RMSE 0.0006738094; lr 1e-05; 232s
network 3, training 0, epoch 1270: train scaled MSE 0.000202689; val RMSE 0.0006737918; lr 1e-05; 234s
network 3, training 0, epoch 1280: train scaled MSE 0.000202714; val RMSE 0.0006736634; lr 1e-05; 236s
network 3, training 0, epoch 1290: train scaled MSE 0.000201535; val RMSE 0.0006734632; lr 1e-05; 238s
network 3, training 0, epoch 1300: train scaled MSE 0.000201522; val RMSE 0.0006735443; lr 1e-05; 240s
network 3, training 0, epoch 1310: train scaled MSE 0.000201834; val RMSE 0.00067364; lr 1e-05; 242s
network 3, training 0, epoch 1320: train scaled MSE 0.000200482; val RMSE 0.0006733128; lr 1e-05; 244s
network 3, training 0, epoch 1330: train scaled MSE 0.000207071; val RMSE 0.0006737454; lr 1e-05; 246s
network 3, training 0, epoch 1340: train scaled MSE 0.000199367; val RMSE 0.0006731867; lr 1e-05; 248s
network 3, training 0, epoch 1350: train scaled MSE 0.00019897; val RMSE 0.0006728838; lr 1e-05; 250s
network 3, training 0, epoch 1360: train scaled MSE 0.000198903; val RMSE 0.0006733391; lr 1e-05; 252s
network 3, training 0, epoch 1370: train scaled MSE 0.000197761; val RMSE 0.0006730492; lr 1e-05; 254s
network 3, training 0, epoch 1380: train scaled MSE 0.000197645; val RMSE 0.0006729729; lr 1e-05; 255s
network 3, training 0, epoch 1390: train scaled MSE 0.000200307; val RMSE 0.0006731705; lr 1e-05; 257s
network 3, training 0, epoch 1400: train scaled MSE 0.000197378; val RMSE 0.0006726788; lr 1e-05; 259s
network 3, training 0, epoch 1410: train scaled MSE 0.000196213; val RMSE 0.0006725744; lr 1e-05; 261s
network 3, training 0, epoch 1420: train scaled MSE 0.000195886; val RMSE 0.0006732636; lr 1e-05; 263s
network 3, training 0, epoch 1430: train scaled MSE 0.000195531; val RMSE 0.0006724035; lr 1e-05; 265s
network 3, training 0, epoch 1440: train scaled MSE 0.000194994; val RMSE 0.0006723965; lr 1e-05; 267s
network 3, training 0, epoch 1450: train scaled MSE 0.000194376; val RMSE 0.0006723459; lr 1e-05; 268s
network 3, training 0, epoch 1460: train scaled MSE 0.000195895; val RMSE 0.0006722509; lr 1e-05; 270s
network 3, training 0, epoch 1470: train scaled MSE 0.000193928; val RMSE 0.0006721366; lr 1e-05; 272s
network 3, training 0, epoch 1480: train scaled MSE 0.000193973; val RMSE 0.0006721453; lr 1e-05; 274s
network 3, training 0, epoch 1490: train scaled MSE 0.000199074; val RMSE 0.000672347; lr 1e-05; 276s
network 3, training 0, epoch 1500: train scaled MSE 0.000192028; val RMSE 0.0006719327; lr 1e-05; 278s
network 3, training 0, epoch 1510: train scaled MSE 0.000194911; val RMSE 0.0006720239; lr 1e-05; 280s
network 3, training 0, epoch 1520: train scaled MSE 0.000192133; val RMSE 0.0006717324; lr 1e-05; 282s
network 3, training 0, epoch 1530: train scaled MSE 0.000191367; val RMSE 0.0006716968; lr 1e-05; 283s
network 3, training 0, epoch 1540: train scaled MSE 0.000191385; val RMSE 0.0006716228; lr 1e-05; 285s
network 3, training 0, epoch 1550: train scaled MSE 0.000189919; val RMSE 0.0006716093; lr 1e-05; 287s
network 3, training 0, epoch 1560: train scaled MSE 0.00019017; val RMSE 0.0006722215; lr 1e-05; 289s
network 3, training 0, epoch 1570: train scaled MSE 0.000189128; val RMSE 0.0006714035; lr 1e-05; 291s
network 3, training 0, epoch 1580: train scaled MSE 0.000188481; val RMSE 0.00067133; lr 1e-05; 293s
network 3, training 0, epoch 1590: train scaled MSE 0.000187959; val RMSE 0.0006712385; lr 1e-05; 295s
network 3, training 0, epoch 1600: train scaled MSE 0.000192483; val RMSE 0.0006711489; lr 1e-05; 296s
network 3, training 0, epoch 1610: train scaled MSE 0.000187151; val RMSE 0.0006711706; lr 1e-05; 298s
network 3, training 0, epoch 1620: train scaled MSE 0.000186781; val RMSE 0.0006710242; lr 1e-05; 300s
network 3, training 0, epoch 1630: train scaled MSE 0.000186573; val RMSE 0.0006709117; lr 1e-05; 302s
network 3, training 0, epoch 1640: train scaled MSE 0.000204264; val RMSE 0.0006713726; lr 1e-05; 304s
network 3, training 0, epoch 1650: train scaled MSE 0.000198967; val RMSE 0.0006723307; lr 1e-05; 306s
network 3, training 0, epoch 1660: train scaled MSE 0.000186658; val RMSE 0.0006705439; lr 1e-05; 308s
network 3, training 0, epoch 1670: train scaled MSE 0.00018731; val RMSE 0.0006711092; lr 1e-05; 310s
network 3, training 0, epoch 1680: train scaled MSE 0.000184721; val RMSE 0.0006705824; lr 1e-05; 312s
network 3, training 0, epoch 1690: train scaled MSE 0.000184032; val RMSE 0.0006704567; lr 1e-05; 314s
network 3, training 0, epoch 1700: train scaled MSE 0.000183707; val RMSE 0.0006703666; lr 1e-05; 316s
network 3, training 0, epoch 1710: train scaled MSE 0.000190297; val RMSE 0.0006712123; lr 1e-05; 318s
network 3, training 0, epoch 1720: train scaled MSE 0.00018418; val RMSE 0.0006717816; lr 1e-05; 320s
Standard Linear Baseline Validation RMSE: 0.0006171376

Network seed 3, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-0.6853,"[-1.49%, -0.06%]",0.0359,0.0,0.5823
MLP,0.0008,-22.4893,"[-40.89%, -10.22%]",0.1918,434.7722,0.3494

network 3, training 1, epoch 1: train scaled MSE 0.880391; val RMSE 0.01125259; lr 0.001; 0s
network 3, training 1, epoch 10: train scaled MSE 0.0149172; val RMSE 0.001969313; lr 0.001; 2s
network 3, training 1, epoch 20: train scaled MSE 0.00643121; val RMSE 0.001068447; lr 0.001; 4s
network 3, training 1, epoch 30: train scaled MSE 0.00548964; val RMSE 0.001047418; lr 0.001; 6s
network 3, training 1, epoch 40: train scaled MSE 0.00370539; val RMSE 0.0008735003; lr 0.001; 8s
network 3, training 1, epoch 50: train scaled MSE 0.0120688; val RMSE 0.001064667; lr 0.001; 10s
network 3, training 1, epoch 60: train scaled MSE 0.00258942; val RMSE 0.0007666017; lr 0.001; 12s
network 3, training 1, epoch 70: train scaled MSE 0.00214931; val RMSE 0.0007307653; lr 0.001; 14s
network 3, training 1, epoch 80: train scaled MSE 0.00198966; val RMSE 0.001413325; lr 0.001; 16s
network 3, training 1, epoch 90: train scaled MSE 0.00202177; val RMSE 0.0008059148; lr 0.001; 18s
network 3, training 1, epoch 100: train scaled MSE 0.0013699; val RMSE 0.000730188; lr 0.0005; 20s
network 3, training 1, epoch 110: train scaled MSE 0.00122715; val RMSE 0.0007100594; lr 0.0005; 22s
network 3, training 1, epoch 120: train scaled MSE 0.00118381; val RMSE 0.0007028684; lr 0.0005; 24s
network 3, training 1, epoch 130: train scaled MSE 0.00104904; val RMSE 0.0006943064; lr 0.0005; 26s
network 3, training 1, epoch 140: train scaled MSE 0.000889851; val RMSE 0.0007584351; lr 0.0005; 28s
network 3, training 1, epoch 150: train scaled MSE 0.000849378; val RMSE 0.0007765701; lr 0.0005; 30s
network 3, training 1, epoch 160: train scaled MSE 0.000762411; val RMSE 0.0006717828; lr 0.0005; 32s
network 3, training 1, epoch 170: train scaled MSE 0.000678021; val RMSE 0.0006668039; lr 0.0005; 34s
network 3, training 1, epoch 180: train scaled MSE 0.000562959; val RMSE 0.0006512183; lr 0.00025; 36s
network 3, training 1, epoch 190: train scaled MSE 0.00053528; val RMSE 0.0006435421; lr 0.00025; 38s
network 3, training 1, epoch 200: train scaled MSE 0.000511783; val RMSE 0.0006344998; lr 0.00025; 40s
network 3, training 1, epoch 210: train scaled MSE 0.00048532; val RMSE 0.0006321558; lr 0.00025; 42s
network 3, training 1, epoch 220: train scaled MSE 0.000459202; val RMSE 0.0006280057; lr 0.00025; 44s
network 3, training 1, epoch 230: train scaled MSE 0.000446967; val RMSE 0.0006284884; lr 0.00025; 46s
network 3, training 1, epoch 240: train scaled MSE 0.000409413; val RMSE 0.0006212186; lr 0.00025; 48s
network 3, training 1, epoch 250: train scaled MSE 0.000387315; val RMSE 0.0006226939; lr 0.00025; 49s
network 3, training 1, epoch 260: train scaled MSE 0.000580346; val RMSE 0.0006226584; lr 0.00025; 51s
network 3, training 1, epoch 270: train scaled MSE 0.000353606; val RMSE 0.0006178311; lr 0.00025; 53s
network 3, training 1, epoch 280: train scaled MSE 0.000347381; val RMSE 0.000618121; lr 0.00025; 55s
network 3, training 1, epoch 290: train scaled MSE 0.000312639; val RMSE 0.0007532098; lr 0.00025; 57s
network 3, training 1, epoch 300: train scaled MSE 0.000280051; val RMSE 0.0006176765; lr 0.000125; 59s
network 3, training 1, epoch 310: train scaled MSE 0.000272442; val RMSE 0.0006168487; lr 0.000125; 61s
network 3, training 1, epoch 320: train scaled MSE 0.000303134; val RMSE 0.0006022507; lr 0.000125; 63s
network 3, training 1, epoch 330: train scaled MSE 0.000272569; val RMSE 0.0006012253; lr 0.000125; 65s
network 3, training 1, epoch 340: train scaled MSE 0.000306211; val RMSE 0.0005975248; lr 0.000125; 67s
network 3, training 1, epoch 350: train scaled MSE 0.000241255; val RMSE 0.0005946053; lr 6.25e-05; 69s
network 3, training 1, epoch 360: train scaled MSE 0.000238929; val RMSE 0.0005935159; lr 6.25e-05; 71s
network 3, training 1, epoch 370: train scaled MSE 0.000244089; val RMSE 0.0005954445; lr 6.25e-05; 73s
network 3, training 1, epoch 380: train scaled MSE 0.000232257; val RMSE 0.000591818; lr 6.25e-05; 74s
network 3, training 1, epoch 390: train scaled MSE 0.000230867; val RMSE 0.0005899286; lr 6.25e-05; 76s
network 3, training 1, epoch 400: train scaled MSE 0.000232126; val RMSE 0.0005889074; lr 6.25e-05; 78s
network 3, training 1, epoch 410: train scaled MSE 0.00022107; val RMSE 0.0005878735; lr 6.25e-05; 80s
network 3, training 1, epoch 420: train scaled MSE 0.000217635; val RMSE 0.0005891753; lr 6.25e-05; 82s
network 3, training 1, epoch 430: train scaled MSE 0.000214992; val RMSE 0.0005865161; lr 6.25e-05; 84s
network 3, training 1, epoch 440: train scaled MSE 0.000210906; val RMSE 0.0005856581; lr 6.25e-05; 86s
network 3, training 1, epoch 450: train scaled MSE 0.000208888; val RMSE 0.000593822; lr 6.25e-05; 88s
network 3, training 1, epoch 460: train scaled MSE 0.0003484; val RMSE 0.0005921286; lr 6.25e-05; 89s
network 3, training 1, epoch 470: train scaled MSE 0.000202484; val RMSE 0.0005841724; lr 6.25e-05; 91s
network 3, training 1, epoch 480: train scaled MSE 0.000197587; val RMSE 0.0005821645; lr 6.25e-05; 93s
network 3, training 1, epoch 490: train scaled MSE 0.00019462; val RMSE 0.0005952433; lr 6.25e-05; 95s
network 3, training 1, epoch 500: train scaled MSE 0.000229728; val RMSE 0.0005839674; lr 6.25e-05; 97s
network 3, training 1, epoch 510: train scaled MSE 0.000189546; val RMSE 0.0005801604; lr 3.125e-05; 99s
network 3, training 1, epoch 520: train scaled MSE 0.000186152; val RMSE 0.0005794115; lr 3.125e-05; 101s
network 3, training 1, epoch 530: train scaled MSE 0.000185605; val RMSE 0.0005790821; lr 3.125e-05; 103s
network 3, training 1, epoch 540: train scaled MSE 0.000184683; val RMSE 0.0005788542; lr 3.125e-05; 105s
network 3, training 1, epoch 550: train scaled MSE 0.000183123; val RMSE 0.0005788979; lr 3.125e-05; 107s
network 3, training 1, epoch 560: train scaled MSE 0.000182105; val RMSE 0.0005841699; lr 3.125e-05; 108s
network 3, training 1, epoch 570: train scaled MSE 0.000178111; val RMSE 0.0005780265; lr 1.5625e-05; 110s
network 3, training 1, epoch 580: train scaled MSE 0.000177114; val RMSE 0.0005777212; lr 1.5625e-05; 112s
network 3, training 1, epoch 590: train scaled MSE 0.000176561; val RMSE 0.000577266; lr 1.5625e-05; 114s
network 3, training 1, epoch 600: train scaled MSE 0.000176007; val RMSE 0.0005772129; lr 1.5625e-05; 116s
network 3, training 1, epoch 610: train scaled MSE 0.000179565; val RMSE 0.000577079; lr 1.5625e-05; 118s
network 3, training 1, epoch 620: train scaled MSE 0.000174162; val RMSE 0.0005767385; lr 1e-05; 119s
network 3, training 1, epoch 630: train scaled MSE 0.000176703; val RMSE 0.000577341; lr 1e-05; 121s
network 3, training 1, epoch 640: train scaled MSE 0.000175539; val RMSE 0.0005768636; lr 1e-05; 123s
network 3, training 1, epoch 650: train scaled MSE 0.000173957; val RMSE 0.0005764343; lr 1e-05; 125s
network 3, training 1, epoch 660: train scaled MSE 0.000175942; val RMSE 0.0005764641; lr 1e-05; 127s
network 3, training 1, epoch 670: train scaled MSE 0.000175463; val RMSE 0.0005762611; lr 1e-05; 129s
network 3, training 1, epoch 680: train scaled MSE 0.000180428; val RMSE 0.000577078; lr 1e-05; 130s
network 3, training 1, epoch 690: train scaled MSE 0.000201822; val RMSE 0.0005791605; lr 1e-05; 132s
network 3, training 1, epoch 700: train scaled MSE 0.000170906; val RMSE 0.0005757214; lr 1e-05; 134s
network 3, training 1, epoch 710: train scaled MSE 0.000170487; val RMSE 0.0005755868; lr 1e-05; 136s
network 3, training 1, epoch 720: train scaled MSE 0.000170707; val RMSE 0.0005758135; lr 1e-05; 138s
network 3, training 1, epoch 730: train scaled MSE 0.00017011; val RMSE 0.0005752779; lr 1e-05; 140s
network 3, training 1, epoch 740: train scaled MSE 0.000170566; val RMSE 0.0005752418; lr 1e-05; 141s
network 3, training 1, epoch 750: train scaled MSE 0.000169311; val RMSE 0.0005758059; lr 1e-05; 143s
network 3, training 1, epoch 760: train scaled MSE 0.000168886; val RMSE 0.0005750482; lr 1e-05; 145s
network 3, training 1, epoch 770: train scaled MSE 0.000168684; val RMSE 0.0005748209; lr 1e-05; 147s
network 3, training 1, epoch 780: train scaled MSE 0.000168276; val RMSE 0.0005747376; lr 1e-05; 148s
network 3, training 1, epoch 790: train scaled MSE 0.00016856; val RMSE 0.0005744834; lr 1e-05; 150s
network 3, training 1, epoch 800: train scaled MSE 0.000172303; val RMSE 0.0005749242; lr 1e-05; 152s
network 3, training 1, epoch 810: train scaled MSE 0.00016726; val RMSE 0.0005744864; lr 1e-05; 154s
network 3, training 1, epoch 820: train scaled MSE 0.000167171; val RMSE 0.000575159; lr 1e-05; 156s
network 3, training 1, epoch 830: train scaled MSE 0.000166767; val RMSE 0.0005740965; lr 1e-05; 158s
network 3, training 1, epoch 840: train scaled MSE 0.000166022; val RMSE 0.0005744062; lr 1e-05; 159s
network 3, training 1, epoch 850: train scaled MSE 0.000166336; val RMSE 0.0005745207; lr 1e-05; 161s
network 3, training 1, epoch 860: train scaled MSE 0.000169513; val RMSE 0.0005743125; lr 1e-05; 163s
network 3, training 1, epoch 870: train scaled MSE 0.000165111; val RMSE 0.0005736887; lr 1e-05; 165s
network 3, training 1, epoch 880: train scaled MSE 0.000164684; val RMSE 0.0005736237; lr 1e-05; 166s
network 3, training 1, epoch 890: train scaled MSE 0.000164614; val RMSE 0.0005736169; lr 1e-05; 168s
network 3, training 1, epoch 900: train scaled MSE 0.00016411; val RMSE 0.0005734849; lr 1e-05; 170s
network 3, training 1, epoch 910: train scaled MSE 0.000164053; val RMSE 0.0005734494; lr 1e-05; 172s
network 3, training 1, epoch 920: train scaled MSE 0.000167383; val RMSE 0.000574066; lr 1e-05; 174s
network 3, training 1, epoch 930: train scaled MSE 0.000163256; val RMSE 0.0005732403; lr 1e-05; 176s
network 3, training 1, epoch 940: train scaled MSE 0.000163125; val RMSE 0.0005731605; lr 1e-05; 177s
network 3, training 1, epoch 950: train scaled MSE 0.000162397; val RMSE 0.0005735644; lr 1e-05; 179s
network 3, training 1, epoch 960: train scaled MSE 0.000162808; val RMSE 0.0005734393; lr 1e-05; 181s
network 3, training 1, epoch 970: train scaled MSE 0.000165442; val RMSE 0.0005732673; lr 1e-05; 183s
network 3, training 1, epoch 980: train scaled MSE 0.000161457; val RMSE 0.0005727952; lr 1e-05; 185s
network 3, training 1, epoch 990: train scaled MSE 0.000164935; val RMSE 0.0005728283; lr 1e-05; 187s
network 3, training 1, epoch 1000: train scaled MSE 0.000161556; val RMSE 0.0005727033; lr 1e-05; 188s
network 3, training 1, epoch 1010: train scaled MSE 0.000175161; val RMSE 0.0005731723; lr 1e-05; 190s
network 3, training 1, epoch 1020: train scaled MSE 0.000162068; val RMSE 0.0005725548; lr 1e-05; 192s
network 3, training 1, epoch 1030: train scaled MSE 0.000160567; val RMSE 0.0005725667; lr 1e-05; 194s
network 3, training 1, epoch 1040: train scaled MSE 0.000160335; val RMSE 0.0005724091; lr 1e-05; 195s
network 3, training 1, epoch 1050: train scaled MSE 0.00015948; val RMSE 0.0005722855; lr 1e-05; 197s
network 3, training 1, epoch 1060: train scaled MSE 0.00016466; val RMSE 0.000572446; lr 1e-05; 199s
network 3, training 1, epoch 1070: train scaled MSE 0.000158958; val RMSE 0.0005719345; lr 1e-05; 201s
network 3, training 1, epoch 1080: train scaled MSE 0.000158806; val RMSE 0.0005719186; lr 1e-05; 203s
network 3, training 1, epoch 1090: train scaled MSE 0.000159444; val RMSE 0.0005720928; lr 1e-05; 205s
network 3, training 1, epoch 1100: train scaled MSE 0.000170341; val RMSE 0.0005734171; lr 1e-05; 207s
network 3, training 1, epoch 1110: train scaled MSE 0.000157881; val RMSE 0.0005720022; lr 1e-05; 208s
network 3, training 1, epoch 1120: train scaled MSE 0.000159748; val RMSE 0.0005751267; lr 1e-05; 210s
network 3, training 1, epoch 1130: train scaled MSE 0.000157238; val RMSE 0.0005718331; lr 1e-05; 212s
network 3, training 1, epoch 1140: train scaled MSE 0.000156554; val RMSE 0.0005714963; lr 1e-05; 214s
network 3, training 1, epoch 1150: train scaled MSE 0.000156637; val RMSE 0.0005720272; lr 1e-05; 216s
network 3, training 1, epoch 1160: train scaled MSE 0.000156223; val RMSE 0.0005712711; lr 1e-05; 218s
network 3, training 1, epoch 1170: train scaled MSE 0.000156576; val RMSE 0.0005712967; lr 1e-05; 220s
network 3, training 1, epoch 1180: train scaled MSE 0.000156025; val RMSE 0.0005716661; lr 1e-05; 222s
network 3, training 1, epoch 1190: train scaled MSE 0.000158631; val RMSE 0.0005714371; lr 1e-05; 224s
network 3, training 1, epoch 1200: train scaled MSE 0.000155207; val RMSE 0.0005711569; lr 1e-05; 226s
network 3, training 1, epoch 1210: train scaled MSE 0.000156325; val RMSE 0.0005710255; lr 1e-05; 227s
network 3, training 1, epoch 1220: train scaled MSE 0.000156807; val RMSE 0.0005709538; lr 1e-05; 229s
network 3, training 1, epoch 1230: train scaled MSE 0.000163093; val RMSE 0.0005715334; lr 1e-05; 231s
network 3, training 1, epoch 1240: train scaled MSE 0.000154774; val RMSE 0.0005710853; lr 1e-05; 233s
network 3, training 1, epoch 1250: train scaled MSE 0.000154165; val RMSE 0.0005705807; lr 1e-05; 235s
network 3, training 1, epoch 1260: train scaled MSE 0.000154372; val RMSE 0.0005706886; lr 1e-05; 236s
network 3, training 1, epoch 1270: train scaled MSE 0.000153471; val RMSE 0.0005703469; lr 1e-05; 238s
network 3, training 1, epoch 1280: train scaled MSE 0.000153203; val RMSE 0.0005704024; lr 1e-05; 240s
network 3, training 1, epoch 1290: train scaled MSE 0.000152633; val RMSE 0.0005702872; lr 1e-05; 242s
network 3, training 1, epoch 1300: train scaled MSE 0.00015345; val RMSE 0.0005702026; lr 1e-05; 244s
network 3, training 1, epoch 1310: train scaled MSE 0.000152197; val RMSE 0.0005701825; lr 1e-05; 246s
network 3, training 1, epoch 1320: train scaled MSE 0.000160859; val RMSE 0.0005714437; lr 1e-05; 248s
network 3, training 1, epoch 1330: train scaled MSE 0.000152174; val RMSE 0.0005708477; lr 1e-05; 249s
network 3, training 1, epoch 1340: train scaled MSE 0.000150955; val RMSE 0.0005697054; lr 1e-05; 251s
network 3, training 1, epoch 1350: train scaled MSE 0.000151265; val RMSE 0.0005701022; lr 1e-05; 253s
network 3, training 1, epoch 1360: train scaled MSE 0.000153412; val RMSE 0.0005698311; lr 1e-05; 255s
network 3, training 1, epoch 1370: train scaled MSE 0.000150779; val RMSE 0.0005696839; lr 1e-05; 257s
network 3, training 1, epoch 1380: train scaled MSE 0.000151058; val RMSE 0.0005695367; lr 1e-05; 259s
network 3, training 1, epoch 1390: train scaled MSE 0.000149549; val RMSE 0.0005693227; lr 1e-05; 260s
network 3, training 1, epoch 1400: train scaled MSE 0.000159327; val RMSE 0.00057038; lr 1e-05; 262s
network 3, training 1, epoch 1410: train scaled MSE 0.000149301; val RMSE 0.000569386; lr 1e-05; 264s
network 3, training 1, epoch 1420: train scaled MSE 0.00014879; val RMSE 0.0005696406; lr 1e-05; 266s
network 3, training 1, epoch 1430: train scaled MSE 0.000149079; val RMSE 0.0005690064; lr 1e-05; 268s
network 3, training 1, epoch 1440: train scaled MSE 0.000151443; val RMSE 0.000569428; lr 1e-05; 270s
network 3, training 1, epoch 1450: train scaled MSE 0.000147967; val RMSE 0.0005690883; lr 1e-05; 271s
network 3, training 1, epoch 1460: train scaled MSE 0.000147771; val RMSE 0.0005689901; lr 1e-05; 273s
network 3, training 1, epoch 1470: train scaled MSE 0.000147353; val RMSE 0.0005688247; lr 1e-05; 275s
network 3, training 1, epoch 1480: train scaled MSE 0.000147346; val RMSE 0.0005694256; lr 1e-05; 277s
network 3, training 1, epoch 1490: train scaled MSE 0.000146948; val RMSE 0.0005686564; lr 1e-05; 279s
network 3, training 1, epoch 1500: train scaled MSE 0.000146599; val RMSE 0.000568458; lr 1e-05; 281s
network 3, training 1, epoch 1510: train scaled MSE 0.000146365; val RMSE 0.0005683015; lr 1e-05; 283s
network 3, training 1, epoch 1520: train scaled MSE 0.000145893; val RMSE 0.0005683943; lr 1e-05; 284s
network 3, training 1, epoch 1530: train scaled MSE 0.000145553; val RMSE 0.0005691379; lr 1e-05; 286s
network 3, training 1, epoch 1540: train scaled MSE 0.000157746; val RMSE 0.0005692005; lr 1e-05; 288s
network 3, training 1, epoch 1550: train scaled MSE 0.000152222; val RMSE 0.0005696472; lr 1e-05; 290s
network 3, training 1, epoch 1560: train scaled MSE 0.000144537; val RMSE 0.0005679198; lr 1e-05; 292s
network 3, training 1, epoch 1570: train scaled MSE 0.000145041; val RMSE 0.0005679512; lr 1e-05; 294s
network 3, training 1, epoch 1580: train scaled MSE 0.000143901; val RMSE 0.0005678904; lr 1e-05; 295s
network 3, training 1, epoch 1590: train scaled MSE 0.00014662; val RMSE 0.00056824; lr 1e-05; 297s
network 3, training 1, epoch 1600: train scaled MSE 0.000156252; val RMSE 0.0005697751; lr 1e-05; 299s
network 3, training 1, epoch 1610: train scaled MSE 0.000145807; val RMSE 0.000567916; lr 1e-05; 301s
network 3, training 1, epoch 1620: train scaled MSE 0.000142741; val RMSE 0.0005675681; lr 1e-05; 303s
network 3, training 1, epoch 1630: train scaled MSE 0.00014244; val RMSE 0.0005675691; lr 1e-05; 305s
network 3, training 1, epoch 1640: train scaled MSE 0.000142337; val RMSE 0.0005675724; lr 1e-05; 307s
network 3, training 1, epoch 1650: train scaled MSE 0.000142814; val RMSE 0.0005676041; lr 1e-05; 308s
network 3, training 1, epoch 1660: train scaled MSE 0.000141769; val RMSE 0.0005673801; lr 1e-05; 310s
network 3, training 1, epoch 1670: train scaled MSE 0.000147206; val RMSE 0.0005678105; lr 1e-05; 312s
network 3, training 1, epoch 1680: train scaled MSE 0.000141065; val RMSE 0.0005670196; lr 1e-05; 314s
network 3, training 1, epoch 1690: train scaled MSE 0.000140969; val RMSE 0.0005669747; lr 1e-05; 316s
network 3, training 1, epoch 1700: train scaled MSE 0.000170861; val RMSE 0.0005702987; lr 1e-05; 318s
network 3, training 1, epoch 1710: train scaled MSE 0.000140215; val RMSE 0.000567168; lr 1e-05; 320s
network 3, training 1, epoch 1720: train scaled MSE 0.000140081; val RMSE 0.0005667263; lr 1e-05; 322s
network 3, training 1, epoch 1730: train scaled MSE 0.000144124; val RMSE 0.0005669244; lr 1e-05; 323s
network 3, training 1, epoch 1740: train scaled MSE 0.000139647; val RMSE 0.0005667384; lr 1e-05; 325s
network 3, training 1, epoch 1750: train scaled MSE 0.000147069; val RMSE 0.0005673671; lr 1e-05; 327s
network 3, training 1, epoch 1760: train scaled MSE 0.000139674; val RMSE 0.0005669346; lr 1e-05; 329s
network 3, training 1, epoch 1770: train scaled MSE 0.000138872; val RMSE 0.0005671317; lr 1e-05; 331s
network 3, training 1, epoch 1780: train scaled MSE 0.000138534; val RMSE 0.0005664437; lr 1e-05; 333s
network 3, training 1, epoch 1790: train scaled MSE 0.000144893; val RMSE 0.0005665247; lr 1e-05; 335s
network 3, training 1, epoch 1800: train scaled MSE 0.00013843; val RMSE 0.0005664505; lr 1e-05; 336s
network 3, training 1, epoch 1810: train scaled MSE 0.000137813; val RMSE 0.000566638; lr 1e-05; 338s
network 3, training 1, epoch 1820: train scaled MSE 0.000137983; val RMSE 0.0005661593; lr 1e-05; 340s
network 3, training 1, epoch 1830: train scaled MSE 0.000137293; val RMSE 0.0005660562; lr 1e-05; 342s
network 3, training 1, epoch 1840: train scaled MSE 0.000140639; val RMSE 0.0005664741; lr 1e-05; 344s
network 3, training 1, epoch 1850: train scaled MSE 0.000136583; val RMSE 0.0005660049; lr 1e-05; 346s
network 3, training 1, epoch 1860: train scaled MSE 0.000136458; val RMSE 0.0005660049; lr 1e-05; 348s
network 3, training 1, epoch 1870: train scaled MSE 0.000136688; val RMSE 0.0005662722; lr 1e-05; 350s
network 3, training 1, epoch 1880: train scaled MSE 0.00013667; val RMSE 0.0005662237; lr 1e-05; 351s
network 3, training 1, epoch 1890: train scaled MSE 0.00013974; val RMSE 0.0005661804; lr 1e-05; 353s
network 3, training 1, epoch 1900: train scaled MSE 0.000135533; val RMSE 0.0005657498; lr 1e-05; 355s
network 3, training 1, epoch 1910: train scaled MSE 0.000135332; val RMSE 0.0005654741; lr 1e-05; 357s
network 3, training 1, epoch 1920: train scaled MSE 0.000137491; val RMSE 0.0005657414; lr 1e-05; 359s
network 3, training 1, epoch 1930: train scaled MSE 0.000135452; val RMSE 0.0005657269; lr 1e-05; 361s
network 3, training 1, epoch 1940: train scaled MSE 0.000134648; val RMSE 0.0005657017; lr 1e-05; 362s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-1.9422,"[-3.27%, -1.10%]",0.0026,0.0,0.5741
MLP,0.0008,-26.6093,"[-56.67%, -6.03%]",0.2340,9029.0084,0.3652

network 3, training 2, epoch 1: train scaled MSE 0.875893; val RMSE 0.01073027; lr 0.001; 0s
network 3, training 2, epoch 10: train scaled MSE 0.0184991; val RMSE 0.002435189; lr 0.001; 2s
network 3, training 2, epoch 20: train scaled MSE 0.0120433; val RMSE 0.001362746; lr 0.001; 4s
network 3, training 2, epoch 30: train scaled MSE 0.00659214; val RMSE 0.001209822; lr 0.001; 6s
network 3, training 2, epoch 40: train scaled MSE 0.00478148; val RMSE 0.001045769; lr 0.001; 7s
network 3, training 2, epoch 50: train scaled MSE 0.00306876; val RMSE 0.0009637812; lr 0.001; 9s
network 3, training 2, epoch 60: train scaled MSE 0.00233167; val RMSE 0.0009093304; lr 0.001; 11s
network 3, training 2, epoch 70: train scaled MSE 0.0020793; val RMSE 0.0008862969; lr 0.001; 13s
network 3, training 2, epoch 80: train scaled MSE 0.00176451; val RMSE 0.0008511605; lr 0.001; 15s
network 3, training 2, epoch 90: train scaled MSE 0.00157232; val RMSE 0.0008550816; lr 0.001; 16s
network 3, training 2, epoch 100: train scaled MSE 0.00158471; val RMSE 0.0008507365; lr 0.0005; 18s
network 3, training 2, epoch 110: train scaled MSE 0.00127185; val RMSE 0.0008125248; lr 0.0005; 20s
network 3, training 2, epoch 120: train scaled MSE 0.000901936; val RMSE 0.0007889182; lr 0.00025; 22s
network 3, training 2, epoch 130: train scaled MSE 0.000832488; val RMSE 0.0007840678; lr 0.00025; 24s
network 3, training 2, epoch 140: train scaled MSE 0.000822502; val RMSE 0.0007797367; lr 0.00025; 26s
network 3, training 2, epoch 150: train scaled MSE 0.000775173; val RMSE 0.0007799504; lr 0.00025; 27s
network 3, training 2, epoch 160: train scaled MSE 0.000710426; val RMSE 0.0007696367; lr 0.00025; 29s
network 3, training 2, epoch 170: train scaled MSE 0.000655264; val RMSE 0.0007678755; lr 0.00025; 31s
network 3, training 2, epoch 180: train scaled MSE 0.000734634; val RMSE 0.0008070745; lr 0.00025; 33s
network 3, training 2, epoch 190: train scaled MSE 0.000570245; val RMSE 0.0007688977; lr 0.000125; 35s
network 3, training 2, epoch 200: train scaled MSE 0.000548779; val RMSE 0.0007659981; lr 6.25e-05; 36s
network 3, training 2, epoch 210: train scaled MSE 0.000534516; val RMSE 0.0007640001; lr 6.25e-05; 38s
network 3, training 2, epoch 220: train scaled MSE 0.000523733; val RMSE 0.0007607842; lr 6.25e-05; 40s
network 3, training 2, epoch 230: train scaled MSE 0.000523635; val RMSE 0.000763403; lr 6.25e-05; 42s
network 3, training 2, epoch 240: train scaled MSE 0.000518203; val RMSE 0.0007591215; lr 6.25e-05; 44s
network 3, training 2, epoch 250: train scaled MSE 0.000503514; val RMSE 0.0007578093; lr 6.25e-05; 45s
network 3, training 2, epoch 260: train scaled MSE 0.000487938; val RMSE 0.0007560786; lr 6.25e-05; 47s
network 3, training 2, epoch 270: train scaled MSE 0.000480179; val RMSE 0.0007552394; lr 6.25e-05; 49s
network 3, training 2, epoch 280: train scaled MSE 0.000469847; val RMSE 0.0007530789; lr 6.25e-05; 51s
network 3, training 2, epoch 290: train scaled MSE 0.000466715; val RMSE 0.000751964; lr 6.25e-05; 53s
network 3, training 2, epoch 300: train scaled MSE 0.000451787; val RMSE 0.0007499804; lr 6.25e-05; 54s
network 3, training 2, epoch 310: train scaled MSE 0.000444645; val RMSE 0.0007493415; lr 6.25e-05; 56s
network 3, training 2, epoch 320: train scaled MSE 0.000437777; val RMSE 0.000753559; lr 6.25e-05; 58s
network 3, training 2, epoch 330: train scaled MSE 0.000424326; val RMSE 0.0007604592; lr 6.25e-05; 60s
network 3, training 2, epoch 340: train scaled MSE 0.000416497; val RMSE 0.0007500237; lr 6.25e-05; 61s
network 3, training 2, epoch 350: train scaled MSE 0.000412074; val RMSE 0.0007451713; lr 6.25e-05; 63s
network 3, training 2, epoch 360: train scaled MSE 0.000407564; val RMSE 0.0007454262; lr 6.25e-05; 65s
network 3, training 2, epoch 370: train scaled MSE 0.000397271; val RMSE 0.0007446617; lr 6.25e-05; 67s
network 3, training 2, epoch 380: train scaled MSE 0.000388853; val RMSE 0.0007461948; lr 6.25e-05; 69s
network 3, training 2, epoch 390: train scaled MSE 0.000384091; val RMSE 0.0007423488; lr 6.25e-05; 71s
network 3, training 2, epoch 400: train scaled MSE 0.000375867; val RMSE 0.0007421559; lr 6.25e-05; 72s
network 3, training 2, epoch 410: train scaled MSE 0.000372613; val RMSE 0.0007421132; lr 6.25e-05; 74s
network 3, training 2, epoch 420: train scaled MSE 0.00036248; val RMSE 0.0007404938; lr 6.25e-05; 76s
network 3, training 2, epoch 430: train scaled MSE 0.000367742; val RMSE 0.0007416797; lr 6.25e-05; 78s
network 3, training 2, epoch 440: train scaled MSE 0.000350409; val RMSE 0.0007383549; lr 6.25e-05; 80s
network 3, training 2, epoch 450: train scaled MSE 0.000346497; val RMSE 0.0007543374; lr 6.25e-05; 81s
network 3, training 2, epoch 460: train scaled MSE 0.000338833; val RMSE 0.0007382997; lr 6.25e-05; 83s
network 3, training 2, epoch 470: train scaled MSE 0.000346127; val RMSE 0.0007380792; lr 3.125e-05; 85s
network 3, training 2, epoch 480: train scaled MSE 0.000325575; val RMSE 0.0007367887; lr 3.125e-05; 87s
network 3, training 2, epoch 490: train scaled MSE 0.000322341; val RMSE 0.0007364391; lr 3.125e-05; 89s
network 3, training 2, epoch 500: train scaled MSE 0.000320243; val RMSE 0.000735872; lr 1.5625e-05; 90s
network 3, training 2, epoch 510: train scaled MSE 0.000316717; val RMSE 0.0007359157; lr 1.5625e-05; 92s
network 3, training 2, epoch 520: train scaled MSE 0.000336012; val RMSE 0.0007397515; lr 1.5625e-05; 94s
network 3, training 2, epoch 530: train scaled MSE 0.000313136; val RMSE 0.0007357926; lr 1e-05; 96s
network 3, training 2, epoch 540: train scaled MSE 0.000311607; val RMSE 0.0007353509; lr 1e-05; 98s
network 3, training 2, epoch 550: train scaled MSE 0.000310826; val RMSE 0.0007351617; lr 1e-05; 99s
network 3, training 2, epoch 560: train scaled MSE 0.000313995; val RMSE 0.0007350817; lr 1e-05; 101s
network 3, training 2, epoch 570: train scaled MSE 0.00030953; val RMSE 0.000734833; lr 1e-05; 103s
network 3, training 2, epoch 580: train scaled MSE 0.000308949; val RMSE 0.0007349749; lr 1e-05; 105s
network 3, training 2, epoch 590: train scaled MSE 0.000307714; val RMSE 0.0007354013; lr 1e-05; 106s
network 3, training 2, epoch 600: train scaled MSE 0.000306844; val RMSE 0.0007345547; lr 1e-05; 108s
network 3, training 2, epoch 610: train scaled MSE 0.000305992; val RMSE 0.0007346391; lr 1e-05; 110s
network 3, training 2, epoch 620: train scaled MSE 0.000304907; val RMSE 0.0007351212; lr 1e-05; 112s
network 3, training 2, epoch 630: train scaled MSE 0.000305294; val RMSE 0.0007346703; lr 1e-05; 114s
network 3, training 2, epoch 640: train scaled MSE 0.000303596; val RMSE 0.0007345143; lr 1e-05; 115s
network 3, training 2, epoch 650: train scaled MSE 0.00030236; val RMSE 0.0007344692; lr 1e-05; 117s
network 3, training 2, epoch 660: train scaled MSE 0.000302548; val RMSE 0.0007344168; lr 1e-05; 119s
network 3, training 2, epoch 670: train scaled MSE 0.000300538; val RMSE 0.0007340441; lr 1e-05; 121s
network 3, training 2, epoch 680: train scaled MSE 0.000300944; val RMSE 0.0007341384; lr 1e-05; 123s
network 3, training 2, epoch 690: train scaled MSE 0.000298782; val RMSE 0.000734066; lr 1e-05; 124s
network 3, training 2, epoch 700: train scaled MSE 0.000298607; val RMSE 0.0007340123; lr 1e-05; 126s
network 3, training 2, epoch 710: train scaled MSE 0.000297351; val RMSE 0.0007336136; lr 1e-05; 128s
network 3, training 2, epoch 720: train scaled MSE 0.000301979; val RMSE 0.0007338735; lr 1e-05; 130s
network 3, training 2, epoch 730: train scaled MSE 0.000296622; val RMSE 0.0007335148; lr 1e-05; 132s
network 3, training 2, epoch 740: train scaled MSE 0.00029492; val RMSE 0.0007333727; lr 1e-05; 133s
network 3, training 2, epoch 750: train scaled MSE 0.000293666; val RMSE 0.0007333509; lr 1e-05; 135s
network 3, training 2, epoch 760: train scaled MSE 0.000292704; val RMSE 0.0007330551; lr 1e-05; 137s
network 3, training 2, epoch 770: train scaled MSE 0.000304086; val RMSE 0.0007340306; lr 1e-05; 139s
network 3, training 2, epoch 780: train scaled MSE 0.000294487; val RMSE 0.0007330482; lr 1e-05; 140s
network 3, training 2, epoch 790: train scaled MSE 0.00028982; val RMSE 0.0007328949; lr 1e-05; 142s
network 3, training 2, epoch 800: train scaled MSE 0.000288789; val RMSE 0.0007328257; lr 1e-05; 144s
network 3, training 2, epoch 810: train scaled MSE 0.000288158; val RMSE 0.0007326923; lr 1e-05; 146s
network 3, training 2, epoch 820: train scaled MSE 0.000286875; val RMSE 0.0007330605; lr 1e-05; 148s
network 3, training 2, epoch 830: train scaled MSE 0.000287055; val RMSE 0.0007324855; lr 1e-05; 150s
network 3, training 2, epoch 840: train scaled MSE 0.000285584; val RMSE 0.0007324064; lr 1e-05; 151s
network 3, training 2, epoch 850: train scaled MSE 0.000286158; val RMSE 0.000732396; lr 1e-05; 153s
network 3, training 2, epoch 860: train scaled MSE 0.000284556; val RMSE 0.0007322874; lr 1e-05; 155s
network 3, training 2, epoch 870: train scaled MSE 0.000283508; val RMSE 0.0007323129; lr 1e-05; 157s
network 3, training 2, epoch 880: train scaled MSE 0.000282227; val RMSE 0.0007320003; lr 1e-05; 158s
network 3, training 2, epoch 890: train scaled MSE 0.000281207; val RMSE 0.0007319355; lr 1e-05; 160s
network 3, training 2, epoch 900: train scaled MSE 0.000280454; val RMSE 0.0007318068; lr 1e-05; 162s
network 3, training 2, epoch 910: train scaled MSE 0.000279814; val RMSE 0.0007318828; lr 1e-05; 164s
network 3, training 2, epoch 920: train scaled MSE 0.000289595; val RMSE 0.0007329753; lr 1e-05; 166s
network 3, training 2, epoch 930: train scaled MSE 0.000278143; val RMSE 0.0007317873; lr 1e-05; 167s
network 3, training 2, epoch 940: train scaled MSE 0.000278021; val RMSE 0.0007327466; lr 1e-05; 169s
network 3, training 2, epoch 950: train scaled MSE 0.000277701; val RMSE 0.0007315176; lr 1e-05; 171s
network 3, training 2, epoch 960: train scaled MSE 0.000276314; val RMSE 0.0007318382; lr 1e-05; 173s
network 3, training 2, epoch 970: train scaled MSE 0.000277488; val RMSE 0.0007315819; lr 1e-05; 174s
network 3, training 2, epoch 980: train scaled MSE 0.000273856; val RMSE 0.0007313354; lr 1e-05; 176s
network 3, training 2, epoch 990: train scaled MSE 0.000273016; val RMSE 0.0007310295; lr 1e-05; 178s
network 3, training 2, epoch 1000: train scaled MSE 0.000272527; val RMSE 0.000731183; lr 1e-05; 180s
network 3, training 2, epoch 1010: train scaled MSE 0.000273317; val RMSE 0.000731748; lr 1e-05; 182s
network 3, training 2, epoch 1020: train scaled MSE 0.000270678; val RMSE 0.0007308192; lr 1e-05; 184s
network 3, training 2, epoch 1030: train scaled MSE 0.000270794; val RMSE 0.0007309067; lr 1e-05; 186s
network 3, training 2, epoch 1040: train scaled MSE 0.000269269; val RMSE 0.0007307004; lr 1e-05; 187s
network 3, training 2, epoch 1050: train scaled MSE 0.000268229; val RMSE 0.0007304534; lr 1e-05; 189s
network 3, training 2, epoch 1060: train scaled MSE 0.00026769; val RMSE 0.000730764; lr 1e-05; 191s
network 3, training 2, epoch 1070: train scaled MSE 0.000268388; val RMSE 0.0007306439; lr 1e-05; 193s
network 3, training 2, epoch 1080: train scaled MSE 0.000266337; val RMSE 0.0007305694; lr 1e-05; 195s
network 3, training 2, epoch 1090: train scaled MSE 0.000265615; val RMSE 0.0007308882; lr 1e-05; 197s
network 3, training 2, epoch 1100: train scaled MSE 0.000264489; val RMSE 0.0007302413; lr 1e-05; 199s
network 3, training 2, epoch 1110: train scaled MSE 0.0002652; val RMSE 0.0007303864; lr 1e-05; 200s
network 3, training 2, epoch 1120: train scaled MSE 0.000263009; val RMSE 0.0007300972; lr 1e-05; 202s
network 3, training 2, epoch 1130: train scaled MSE 0.00026233; val RMSE 0.0007302656; lr 1e-05; 204s
network 3, training 2, epoch 1140: train scaled MSE 0.000264531; val RMSE 0.0007299673; lr 1e-05; 206s
network 3, training 2, epoch 1150: train scaled MSE 0.000261262; val RMSE 0.0007302551; lr 1e-05; 208s
network 3, training 2, epoch 1160: train scaled MSE 0.000264538; val RMSE 0.0007300066; lr 1e-05; 209s
network 3, training 2, epoch 1170: train scaled MSE 0.00025918; val RMSE 0.0007296394; lr 1e-05; 211s
network 3, training 2, epoch 1180: train scaled MSE 0.000259581; val RMSE 0.0007299796; lr 1e-05; 213s
network 3, training 2, epoch 1190: train scaled MSE 0.000258612; val RMSE 0.0007308843; lr 1e-05; 215s
network 3, training 2, epoch 1200: train scaled MSE 0.000257163; val RMSE 0.0007294728; lr 1e-05; 216s
network 3, training 2, epoch 1210: train scaled MSE 0.000260603; val RMSE 0.000730123; lr 1e-05; 218s
network 3, training 2, epoch 1220: train scaled MSE 0.000264625; val RMSE 0.000729519; lr 1e-05; 220s
network 3, training 2, epoch 1230: train scaled MSE 0.000255559; val RMSE 0.0007291602; lr 1e-05; 222s
network 3, training 2, epoch 1240: train scaled MSE 0.000254739; val RMSE 0.0007291164; lr 1e-05; 223s
network 3, training 2, epoch 1250: train scaled MSE 0.000254148; val RMSE 0.0007291322; lr 1e-05; 225s
network 3, training 2, epoch 1260: train scaled MSE 0.000254957; val RMSE 0.0007291102; lr 1e-05; 227s
network 3, training 2, epoch 1270: train scaled MSE 0.000252861; val RMSE 0.0007288694; lr 1e-05; 229s
network 3, training 2, epoch 1280: train scaled MSE 0.000252107; val RMSE 0.0007286967; lr 1e-05; 230s
network 3, training 2, epoch 1290: train scaled MSE 0.000251423; val RMSE 0.0007287398; lr 1e-05; 232s
network 3, training 2, epoch 1300: train scaled MSE 0.000250783; val RMSE 0.0007291686; lr 1e-05; 234s
network 3, training 2, epoch 1310: train scaled MSE 0.000250139; val RMSE 0.0007286299; lr 1e-05; 236s
network 3, training 2, epoch 1320: train scaled MSE 0.000249991; val RMSE 0.000728491; lr 1e-05; 237s
network 3, training 2, epoch 1330: train scaled MSE 0.000248351; val RMSE 0.0007284787; lr 1e-05; 239s
network 3, training 2, epoch 1340: train scaled MSE 0.000248349; val RMSE 0.0007285575; lr 1e-05; 241s
network 3, training 2, epoch 1350: train scaled MSE 0.000252389; val RMSE 0.0007293288; lr 1e-05; 243s
network 3, training 2, epoch 1360: train scaled MSE 0.000246322; val RMSE 0.0007286145; lr 1e-05; 245s
network 3, training 2, epoch 1370: train scaled MSE 0.000245591; val RMSE 0.0007280211; lr 1e-05; 247s
network 3, training 2, epoch 1380: train scaled MSE 0.000244915; val RMSE 0.0007280725; lr 1e-05; 248s
network 3, training 2, epoch 1390: train scaled MSE 0.000244407; val RMSE 0.0007278379; lr 1e-05; 250s
network 3, training 2, epoch 1400: train scaled MSE 0.000243842; val RMSE 0.0007279351; lr 1e-05; 252s
network 3, training 2, epoch 1410: train scaled MSE 0.000243559; val RMSE 0.0007277904; lr 1e-05; 254s
network 3, training 2, epoch 1420: train scaled MSE 0.000243265; val RMSE 0.0007276787; lr 1e-05; 255s
network 3, training 2, epoch 1430: train scaled MSE 0.000242169; val RMSE 0.0007276131; lr 1e-05; 257s
network 3, training 2, epoch 1440: train scaled MSE 0.000241483; val RMSE 0.0007275191; lr 1e-05; 259s
network 3, training 2, epoch 1450: train scaled MSE 0.00024796; val RMSE 0.0007278657; lr 1e-05; 261s
network 3, training 2, epoch 1460: train scaled MSE 0.000240424; val RMSE 0.0007276182; lr 1e-05; 263s
network 3, training 2, epoch 1470: train scaled MSE 0.000239398; val RMSE 0.0007273551; lr 1e-05; 264s
network 3, training 2, epoch 1480: train scaled MSE 0.000243307; val RMSE 0.0007279418; lr 1e-05; 266s
network 3, training 2, epoch 1490: train scaled MSE 0.00023985; val RMSE 0.000727714; lr 1e-05; 268s
network 3, training 2, epoch 1500: train scaled MSE 0.000237541; val RMSE 0.0007275092; lr 1e-05; 269s
network 3, training 2, epoch 1510: train scaled MSE 0.00023675; val RMSE 0.0007272749; lr 1e-05; 271s
network 3, training 2, epoch 1520: train scaled MSE 0.000236341; val RMSE 0.0007271154; lr 1e-05; 273s
network 3, training 2, epoch 1530: train scaled MSE 0.000235885; val RMSE 0.000726991; lr 1e-05; 275s
network 3, training 2, epoch 1540: train scaled MSE 0.0002351; val RMSE 0.0007276489; lr 1e-05; 276s
network 3, training 2, epoch 1550: train scaled MSE 0.000235495; val RMSE 0.000727071; lr 1e-05; 278s
network 3, training 2, epoch 1560: train scaled MSE 0.000235151; val RMSE 0.0007272041; lr 1e-05; 280s
network 3, training 2, epoch 1570: train scaled MSE 0.000235183; val RMSE 0.0007268949; lr 1e-05; 282s
network 3, training 2, epoch 1580: train scaled MSE 0.000232536; val RMSE 0.0007267633; lr 1e-05; 283s
network 3, training 2, epoch 1590: train scaled MSE 0.000231837; val RMSE 0.0007267702; lr 1e-05; 285s
network 3, training 2, epoch 1600: train scaled MSE 0.000231376; val RMSE 0.0007271269; lr 1e-05; 287s
network 3, training 2, epoch 1610: train scaled MSE 0.000232283; val RMSE 0.0007267595; lr 1e-05; 288s
network 3, training 2, epoch 1620: train scaled MSE 0.000230121; val RMSE 0.0007267903; lr 1e-05; 290s
network 3, training 2, epoch 1630: train scaled MSE 0.000229083; val RMSE 0.0007265215; lr 1e-05; 292s
network 3, training 2, epoch 1640: train scaled MSE 0.000229273; val RMSE 0.0007265989; lr 1e-05; 294s
network 3, training 2, epoch 1650: train scaled MSE 0.000228562; val RMSE 0.000726491; lr 1e-05; 295s
network 3, training 2, epoch 1660: train scaled MSE 0.000230122; val RMSE 0.000726434; lr 1e-05; 297s
network 3, training 2, epoch 1670: train scaled MSE 0.000226869; val RMSE 0.0007261331; lr 1e-05; 299s
network 3, training 2, epoch 1680: train scaled MSE 0.000227009; val RMSE 0.0007261958; lr 1e-05; 301s
network 3, training 2, epoch 1690: train scaled MSE 0.000226158; val RMSE 0.0007260396; lr 1e-05; 302s
network 3, training 2, epoch 1700: train scaled MSE 0.000225813; val RMSE 0.000726126; lr 1e-05; 304s
network 3, training 2, epoch 1710: train scaled MSE 0.000225098; val RMSE 0.0007258624; lr 1e-05; 306s
network 3, training 2, epoch 1720: train scaled MSE 0.000229997; val RMSE 0.0007260173; lr 1e-05; 308s
network 3, training 2, epoch 1730: train scaled MSE 0.000223686; val RMSE 0.0007257328; lr 1e-05; 309s
network 3, training 2, epoch 1740: train scaled MSE 0.000223025; val RMSE 0.0007256511; lr 1e-05; 311s
network 3, training 2, epoch 1750: train scaled MSE 0.000222411; val RMSE 0.0007260683; lr 1e-05; 313s
network 3, training 2, epoch 1760: train scaled MSE 0.000221708; val RMSE 0.0007261402; lr 1e-05; 315s
network 3, training 2, epoch 1770: train scaled MSE 0.000224928; val RMSE 0.0007256903; lr 1e-05; 316s
network 3, training 2, epoch 1780: train scaled MSE 0.000220524; val RMSE 0.0007254255; lr 1e-05; 318s
network 3, training 2, epoch 1790: train scaled MSE 0.000219996; val RMSE 0.0007253435; lr 1e-05; 320s
network 3, training 2, epoch 1800: train scaled MSE 0.000219478; val RMSE 0.0007254682; lr 1e-05; 322s
network 3, training 2, epoch 1810: train scaled MSE 0.000218725; val RMSE 0.0007252545; lr 1e-05; 324s
network 3, training 2, epoch 1820: train scaled MSE 0.000232964; val RMSE 0.0007259764; lr 1e-05; 326s
network 3, training 2, epoch 1830: train scaled MSE 0.000218854; val RMSE 0.0007252951; lr 1e-05; 327s
network 3, training 2, epoch 1840: train scaled MSE 0.000217594; val RMSE 0.00072594; lr 1e-05; 329s
network 3, training 2, epoch 1850: train scaled MSE 0.00021915; val RMSE 0.0007252455; lr 1e-05; 331s
network 3, training 2, epoch 1860: train scaled MSE 0.000216222; val RMSE 0.0007249635; lr 1e-05; 333s
network 3, training 2, epoch 1870: train scaled MSE 0.000215903; val RMSE 0.0007249036; lr 1e-05; 335s
network 3, training 2, epoch 1880: train scaled MSE 0.000216018; val RMSE 0.0007247836; lr 1e-05; 337s
network 3, training 2, epoch 1890: train scaled MSE 0.000214804; val RMSE 0.0007247439; lr 1e-05; 339s
network 3, training 2, epoch 1900: train scaled MSE 0.000214912; val RMSE 0.0007247376; lr 1e-05; 340s
network 3, training 2, epoch 1910: train scaled MSE 0.000222063; val RMSE 0.0007253346; lr 1e-05; 342s
network 3, training 2, epoch 1920: train scaled MSE 0.000213114; val RMSE 0.0007244499; lr 1e-05; 344s
network 3, training 2, epoch 1930: train scaled MSE 0.000212655; val RMSE 0.0007243766; lr 1e-05; 346s
network 3, training 2, epoch 1940: train scaled MSE 0.000212901; val RMSE 0.0007244196; lr 1e-05; 348s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-1.5486,"[-2.82%, -0.84%]",0.0137,0.0,0.5972
MLP,0.0008,-31.3734,"[-57.96%, -16.20%]",0.1391,915.2953,0.3525

network 3, training 3, epoch 1: train scaled MSE 0.877718; val RMSE 0.01161687; lr 0.001; 0s
network 3, training 3, epoch 10: train scaled MSE 0.0152908; val RMSE 0.002291144; lr 0.001; 2s
network 3, training 3, epoch 20: train scaled MSE 0.00628831; val RMSE 0.001134491; lr 0.001; 4s
network 3, training 3, epoch 30: train scaled MSE 0.00528801; val RMSE 0.0009411062; lr 0.001; 6s
network 3, training 3, epoch 40: train scaled MSE 0.00426409; val RMSE 0.0009635096; lr 0.001; 8s
network 3, training 3, epoch 50: train scaled MSE 0.00385623; val RMSE 0.0008799751; lr 0.001; 10s
network 3, training 3, epoch 60: train scaled MSE 0.00293088; val RMSE 0.0008134092; lr 0.001; 12s
network 3, training 3, epoch 70: train scaled MSE 0.0023687; val RMSE 0.001037856; lr 0.001; 14s
network 3, training 3, epoch 80: train scaled MSE 0.00167936; val RMSE 0.0007780995; lr 0.0005; 16s
network 3, training 3, epoch 90: train scaled MSE 0.00157947; val RMSE 0.0007675252; lr 0.0005; 18s
network 3, training 3, epoch 100: train scaled MSE 0.00154492; val RMSE 0.0007986647; lr 0.0005; 20s
network 3, training 3, epoch 110: train scaled MSE 0.001247; val RMSE 0.0007758665; lr 0.00025; 22s
network 3, training 3, epoch 120: train scaled MSE 0.00110961; val RMSE 0.0007642201; lr 0.000125; 24s
network 3, training 3, epoch 130: train scaled MSE 0.00106397; val RMSE 0.0007588362; lr 6.25e-05; 26s
network 3, training 3, epoch 140: train scaled MSE 0.00103892; val RMSE 0.0007573779; lr 6.25e-05; 28s
network 3, training 3, epoch 150: train scaled MSE 0.00100033; val RMSE 0.0007534542; lr 6.25e-05; 30s
network 3, training 3, epoch 160: train scaled MSE 0.000971881; val RMSE 0.0007503681; lr 6.25e-05; 32s
network 3, training 3, epoch 170: train scaled MSE 0.000942285; val RMSE 0.000747474; lr 6.25e-05; 34s
network 3, training 3, epoch 180: train scaled MSE 0.000952662; val RMSE 0.0007476266; lr 6.25e-05; 35s
network 3, training 3, epoch 190: train scaled MSE 0.000945828; val RMSE 0.0007479542; lr 6.25e-05; 37s
network 3, training 3, epoch 200: train scaled MSE 0.00086357; val RMSE 0.0007392411; lr 6.25e-05; 39s
network 3, training 3, epoch 210: train scaled MSE 0.000864632; val RMSE 0.0007380379; lr 6.25e-05; 41s
network 3, training 3, epoch 220: train scaled MSE 0.00081289; val RMSE 0.0007398828; lr 6.25e-05; 43s
network 3, training 3, epoch 230: train scaled MSE 0.00079367; val RMSE 0.000731911; lr 6.25e-05; 45s
network 3, training 3, epoch 240: train scaled MSE 0.000899457; val RMSE 0.0007448302; lr 6.25e-05; 47s
network 3, training 3, epoch 250: train scaled MSE 0.00075101; val RMSE 0.0007271412; lr 6.25e-05; 49s
network 3, training 3, epoch 260: train scaled MSE 0.000731717; val RMSE 0.0007259842; lr 6.25e-05; 51s
network 3, training 3, epoch 270: train scaled MSE 0.000712312; val RMSE 0.0007229943; lr 6.25e-05; 52s
network 3, training 3, epoch 280: train scaled MSE 0.00101254; val RMSE 0.0007368902; lr 6.25e-05; 54s
network 3, training 3, epoch 290: train scaled MSE 0.000682027; val RMSE 0.0007207008; lr 6.25e-05; 56s
network 3, training 3, epoch 300: train scaled MSE 0.000668183; val RMSE 0.0007255757; lr 6.25e-05; 58s
network 3, training 3, epoch 310: train scaled MSE 0.000753147; val RMSE 0.0007236921; lr 6.25e-05; 59s
network 3, training 3, epoch 320: train scaled MSE 0.000663838; val RMSE 0.0007171712; lr 6.25e-05; 61s
network 3, training 3, epoch 330: train scaled MSE 0.000630604; val RMSE 0.0007148494; lr 6.25e-05; 63s
network 3, training 3, epoch 340: train scaled MSE 0.000611474; val RMSE 0.0007137131; lr 6.25e-05; 65s
network 3, training 3, epoch 350: train scaled MSE 0.000599409; val RMSE 0.0007129402; lr 6.25e-05; 66s
network 3, training 3, epoch 360: train scaled MSE 0.000587573; val RMSE 0.000712788; lr 6.25e-05; 68s
network 3, training 3, epoch 370: train scaled MSE 0.000574754; val RMSE 0.0007105257; lr 6.25e-05; 70s
network 3, training 3, epoch 380: train scaled MSE 0.000562992; val RMSE 0.0007109679; lr 6.25e-05; 72s
network 3, training 3, epoch 390: train scaled MSE 0.000564966; val RMSE 0.0007101487; lr 6.25e-05; 74s
network 3, training 3, epoch 400: train scaled MSE 0.000532872; val RMSE 0.0007065251; lr 3.125e-05; 75s
network 3, training 3, epoch 410: train scaled MSE 0.00052745; val RMSE 0.0007065089; lr 3.125e-05; 77s
network 3, training 3, epoch 420: train scaled MSE 0.000521192; val RMSE 0.0007058895; lr 3.125e-05; 79s
network 3, training 3, epoch 430: train scaled MSE 0.000511253; val RMSE 0.0007047724; lr 1.5625e-05; 81s
network 3, training 3, epoch 440: train scaled MSE 0.000512923; val RMSE 0.0007048799; lr 1.5625e-05; 83s
network 3, training 3, epoch 450: train scaled MSE 0.000516093; val RMSE 0.0007045515; lr 1.5625e-05; 85s
network 3, training 3, epoch 460: train scaled MSE 0.000501886; val RMSE 0.0007037242; lr 1e-05; 86s
network 3, training 3, epoch 470: train scaled MSE 0.000498399; val RMSE 0.0007032344; lr 1e-05; 88s
network 3, training 3, epoch 480: train scaled MSE 0.000497044; val RMSE 0.0007031379; lr 1e-05; 90s
network 3, training 3, epoch 490: train scaled MSE 0.000494796; val RMSE 0.0007028338; lr 1e-05; 92s
network 3, training 3, epoch 500: train scaled MSE 0.000493191; val RMSE 0.0007025764; lr 1e-05; 93s
network 3, training 3, epoch 510: train scaled MSE 0.000490929; val RMSE 0.0007024665; lr 1e-05; 95s
network 3, training 3, epoch 520: train scaled MSE 0.000489555; val RMSE 0.0007022673; lr 1e-05; 97s
network 3, training 3, epoch 530: train scaled MSE 0.000487202; val RMSE 0.0007022073; lr 1e-05; 99s
network 3, training 3, epoch 540: train scaled MSE 0.000485228; val RMSE 0.000701847; lr 1e-05; 100s
network 3, training 3, epoch 550: train scaled MSE 0.000483322; val RMSE 0.0007015278; lr 1e-05; 102s
network 3, training 3, epoch 560: train scaled MSE 0.000480957; val RMSE 0.000701511; lr 1e-05; 104s
network 3, training 3, epoch 570: train scaled MSE 0.000479393; val RMSE 0.0007015316; lr 1e-05; 106s
network 3, training 3, epoch 580: train scaled MSE 0.000477157; val RMSE 0.0007009313; lr 1e-05; 108s
network 3, training 3, epoch 590: train scaled MSE 0.000474449; val RMSE 0.0007008152; lr 1e-05; 109s
network 3, training 3, epoch 600: train scaled MSE 0.000486067; val RMSE 0.0007015151; lr 1e-05; 111s
network 3, training 3, epoch 610: train scaled MSE 0.000470594; val RMSE 0.0007008626; lr 1e-05; 113s
network 3, training 3, epoch 620: train scaled MSE 0.000468894; val RMSE 0.0007001204; lr 1e-05; 115s
network 3, training 3, epoch 630: train scaled MSE 0.000468071; val RMSE 0.0007004413; lr 1e-05; 116s
network 3, training 3, epoch 640: train scaled MSE 0.000465672; val RMSE 0.0006998748; lr 1e-05; 118s
network 3, training 3, epoch 650: train scaled MSE 0.00046334; val RMSE 0.0006997043; lr 1e-05; 120s
network 3, training 3, epoch 660: train scaled MSE 0.000474131; val RMSE 0.0007007344; lr 1e-05; 122s
network 3, training 3, epoch 670: train scaled MSE 0.000460138; val RMSE 0.0006995501; lr 1e-05; 123s
network 3, training 3, epoch 680: train scaled MSE 0.000458231; val RMSE 0.0006990308; lr 1e-05; 125s
network 3, training 3, epoch 690: train scaled MSE 0.000472065; val RMSE 0.0006998512; lr 1e-05; 127s
network 3, training 3, epoch 700: train scaled MSE 0.000456073; val RMSE 0.0006992255; lr 1e-05; 129s
network 3, training 3, epoch 710: train scaled MSE 0.000453686; val RMSE 0.0006985515; lr 1e-05; 130s
network 3, training 3, epoch 720: train scaled MSE 0.000470843; val RMSE 0.0006992989; lr 1e-05; 132s
network 3, training 3, epoch 730: train scaled MSE 0.00045082; val RMSE 0.000698777; lr 1e-05; 134s
network 3, training 3, epoch 740: train scaled MSE 0.000448885; val RMSE 0.0006983469; lr 1e-05; 136s
network 3, training 3, epoch 750: train scaled MSE 0.000447104; val RMSE 0.0006979341; lr 1e-05; 138s
network 3, training 3, epoch 760: train scaled MSE 0.000474846; val RMSE 0.0007015579; lr 1e-05; 139s
network 3, training 3, epoch 770: train scaled MSE 0.00044465; val RMSE 0.0006976493; lr 1e-05; 141s
network 3, training 3, epoch 780: train scaled MSE 0.000442554; val RMSE 0.0006976194; lr 1e-05; 143s
network 3, training 3, epoch 790: train scaled MSE 0.000442432; val RMSE 0.0006980012; lr 1e-05; 145s
network 3, training 3, epoch 800: train scaled MSE 0.000444302; val RMSE 0.0006979041; lr 1e-05; 147s
network 3, training 3, epoch 810: train scaled MSE 0.00043896; val RMSE 0.0006972107; lr 1e-05; 149s
network 3, training 3, epoch 820: train scaled MSE 0.000437722; val RMSE 0.000697123; lr 1e-05; 151s
network 3, training 3, epoch 830: train scaled MSE 0.000436831; val RMSE 0.0006969524; lr 1e-05; 153s
network 3, training 3, epoch 840: train scaled MSE 0.000448326; val RMSE 0.0006981753; lr 1e-05; 155s
network 3, training 3, epoch 850: train scaled MSE 0.000434663; val RMSE 0.0006966492; lr 1e-05; 156s
network 3, training 3, epoch 860: train scaled MSE 0.000432815; val RMSE 0.0006965863; lr 1e-05; 158s
network 3, training 3, epoch 870: train scaled MSE 0.000438529; val RMSE 0.0006972551; lr 1e-05; 160s
network 3, training 3, epoch 880: train scaled MSE 0.000429981; val RMSE 0.0006963584; lr 1e-05; 162s
network 3, training 3, epoch 890: train scaled MSE 0.000431586; val RMSE 0.0006966943; lr 1e-05; 164s
network 3, training 3, epoch 900: train scaled MSE 0.000432302; val RMSE 0.0006962289; lr 1e-05; 166s
network 3, training 3, epoch 910: train scaled MSE 0.000425897; val RMSE 0.0006959452; lr 1e-05; 168s
network 3, training 3, epoch 920: train scaled MSE 0.000424539; val RMSE 0.0006959429; lr 1e-05; 170s
network 3, training 3, epoch 930: train scaled MSE 0.000436058; val RMSE 0.0006967344; lr 1e-05; 172s
network 3, training 3, epoch 940: train scaled MSE 0.000424358; val RMSE 0.0006963829; lr 1e-05; 173s
network 3, training 3, epoch 950: train scaled MSE 0.000422292; val RMSE 0.0006961093; lr 1e-05; 175s
network 3, training 3, epoch 960: train scaled MSE 0.00042092; val RMSE 0.0006959071; lr 1e-05; 177s
network 3, training 3, epoch 970: train scaled MSE 0.000422491; val RMSE 0.0006961453; lr 1e-05; 179s
network 3, training 3, epoch 980: train scaled MSE 0.00041916; val RMSE 0.0006959436; lr 1e-05; 181s
network 3, training 3, epoch 990: train scaled MSE 0.00041669; val RMSE 0.0006956842; lr 1e-05; 183s
network 3, training 3, epoch 1000: train scaled MSE 0.000419916; val RMSE 0.0006952368; lr 1e-05; 185s
network 3, training 3, epoch 1010: train scaled MSE 0.000415377; val RMSE 0.0006948951; lr 1e-05; 187s
network 3, training 3, epoch 1020: train scaled MSE 0.000413349; val RMSE 0.0006947292; lr 1e-05; 189s
network 3, training 3, epoch 1030: train scaled MSE 0.00041342; val RMSE 0.0006947372; lr 1e-05; 190s
network 3, training 3, epoch 1040: train scaled MSE 0.000410967; val RMSE 0.0006945993; lr 1e-05; 192s
network 3, training 3, epoch 1050: train scaled MSE 0.000409651; val RMSE 0.0006944158; lr 1e-05; 194s
network 3, training 3, epoch 1060: train scaled MSE 0.000409154; val RMSE 0.0006944257; lr 1e-05; 196s
network 3, training 3, epoch 1070: train scaled MSE 0.000408182; val RMSE 0.0006942763; lr 1e-05; 198s
network 3, training 3, epoch 1080: train scaled MSE 0.000406207; val RMSE 0.0006941598; lr 1e-05; 200s
network 3, training 3, epoch 1090: train scaled MSE 0.000406268; val RMSE 0.0006943775; lr 1e-05; 202s
network 3, training 3, epoch 1100: train scaled MSE 0.000404983; val RMSE 0.0006942825; lr 1e-05; 204s
network 3, training 3, epoch 1110: train scaled MSE 0.000423619; val RMSE 0.0006955554; lr 1e-05; 205s
network 3, training 3, epoch 1120: train scaled MSE 0.000401715; val RMSE 0.0006940468; lr 1e-05; 207s
network 3, training 3, epoch 1130: train scaled MSE 0.000399584; val RMSE 0.0006935468; lr 1e-05; 209s
network 3, training 3, epoch 1140: train scaled MSE 0.000399164; val RMSE 0.0006937027; lr 1e-05; 211s
network 3, training 3, epoch 1150: train scaled MSE 0.000398147; val RMSE 0.0006940245; lr 1e-05; 213s
network 3, training 3, epoch 1160: train scaled MSE 0.000396417; val RMSE 0.0006936253; lr 1e-05; 214s
network 3, training 3, epoch 1170: train scaled MSE 0.000394958; val RMSE 0.0006932286; lr 1e-05; 216s
network 3, training 3, epoch 1180: train scaled MSE 0.000393971; val RMSE 0.0006932057; lr 1e-05; 218s
network 3, training 3, epoch 1190: train scaled MSE 0.000407618; val RMSE 0.000694575; lr 1e-05; 220s
network 3, training 3, epoch 1200: train scaled MSE 0.000391285; val RMSE 0.0006929381; lr 1e-05; 222s
network 3, training 3, epoch 1210: train scaled MSE 0.000396041; val RMSE 0.0006935556; lr 1e-05; 224s
network 3, training 3, epoch 1220: train scaled MSE 0.000391966; val RMSE 0.0006932175; lr 1e-05; 225s
network 3, training 3, epoch 1230: train scaled MSE 0.000388608; val RMSE 0.0006928496; lr 1e-05; 227s
network 3, training 3, epoch 1240: train scaled MSE 0.000386835; val RMSE 0.0006927292; lr 1e-05; 229s
network 3, training 3, epoch 1250: train scaled MSE 0.000385941; val RMSE 0.0006925479; lr 1e-05; 231s
network 3, training 3, epoch 1260: train scaled MSE 0.000384996; val RMSE 0.0006932501; lr 1e-05; 232s
network 3, training 3, epoch 1270: train scaled MSE 0.000385987; val RMSE 0.0006929166; lr 1e-05; 234s
network 3, training 3, epoch 1280: train scaled MSE 0.000382963; val RMSE 0.0006924349; lr 1e-05; 236s
network 3, training 3, epoch 1290: train scaled MSE 0.000391159; val RMSE 0.000693242; lr 1e-05; 238s
network 3, training 3, epoch 1300: train scaled MSE 0.0003805; val RMSE 0.0006920529; lr 1e-05; 239s
network 3, training 3, epoch 1310: train scaled MSE 0.000379112; val RMSE 0.0006919994; lr 1e-05; 241s
network 3, training 3, epoch 1320: train scaled MSE 0.000378598; val RMSE 0.0006927806; lr 1e-05; 243s
network 3, training 3, epoch 1330: train scaled MSE 0.000377113; val RMSE 0.0006916414; lr 1e-05; 245s
network 3, training 3, epoch 1340: train scaled MSE 0.000376719; val RMSE 0.0006917683; lr 1e-05; 246s
network 3, training 3, epoch 1350: train scaled MSE 0.00037514; val RMSE 0.0006914786; lr 1e-05; 248s
network 3, training 3, epoch 1360: train scaled MSE 0.000374282; val RMSE 0.0006914015; lr 1e-05; 250s
network 3, training 3, epoch 1370: train scaled MSE 0.000372751; val RMSE 0.0006915397; lr 1e-05; 252s
network 3, training 3, epoch 1380: train scaled MSE 0.000371483; val RMSE 0.000691365; lr 1e-05; 254s
network 3, training 3, epoch 1390: train scaled MSE 0.000370388; val RMSE 0.0006912391; lr 1e-05; 256s
network 3, training 3, epoch 1400: train scaled MSE 0.000369137; val RMSE 0.0006914573; lr 1e-05; 258s
network 3, training 3, epoch 1410: train scaled MSE 0.000369574; val RMSE 0.0006912513; lr 1e-05; 260s
network 3, training 3, epoch 1420: train scaled MSE 0.000368822; val RMSE 0.0006913764; lr 1e-05; 261s
network 3, training 3, epoch 1430: train scaled MSE 0.000372194; val RMSE 0.0006916238; lr 1e-05; 263s
network 3, training 3, epoch 1440: train scaled MSE 0.000364524; val RMSE 0.000691008; lr 1e-05; 265s
network 3, training 3, epoch 1450: train scaled MSE 0.000363197; val RMSE 0.0006908348; lr 1e-05; 267s
network 3, training 3, epoch 1460: train scaled MSE 0.000365868; val RMSE 0.0006913475; lr 1e-05; 269s
network 3, training 3, epoch 1470: train scaled MSE 0.000360879; val RMSE 0.0006907192; lr 1e-05; 270s
network 3, training 3, epoch 1480: train scaled MSE 0.000360702; val RMSE 0.0006909487; lr 1e-05; 272s
network 3, training 3, epoch 1490: train scaled MSE 0.000359048; val RMSE 0.0006905517; lr 1e-05; 274s
network 3, training 3, epoch 1500: train scaled MSE 0.000357981; val RMSE 0.0006904859; lr 1e-05; 276s
network 3, training 3, epoch 1510: train scaled MSE 0.000357107; val RMSE 0.0006907319; lr 1e-05; 278s
network 3, training 3, epoch 1520: train scaled MSE 0.000356084; val RMSE 0.0006904567; lr 1e-05; 279s
network 3, training 3, epoch 1530: train scaled MSE 0.000354797; val RMSE 0.0006906534; lr 1e-05; 281s
network 3, training 3, epoch 1540: train scaled MSE 0.00035496; val RMSE 0.0006901085; lr 1e-05; 283s
network 3, training 3, epoch 1550: train scaled MSE 0.000352491; val RMSE 0.000690232; lr 1e-05; 284s
network 3, training 3, epoch 1560: train scaled MSE 0.000351633; val RMSE 0.0006903242; lr 1e-05; 286s
network 3, training 3, epoch 1570: train scaled MSE 0.000350361; val RMSE 0.0006900701; lr 1e-05; 287s
network 3, training 3, epoch 1580: train scaled MSE 0.000353957; val RMSE 0.000690088; lr 1e-05; 289s
network 3, training 3, epoch 1590: train scaled MSE 0.000356415; val RMSE 0.0006901688; lr 1e-05; 290s
network 3, training 3, epoch 1600: train scaled MSE 0.000348773; val RMSE 0.0006899334; lr 1e-05; 292s
network 3, training 3, epoch 1610: train scaled MSE 0.000366219; val RMSE 0.00069103; lr 1e-05; 293s
network 3, training 3, epoch 1620: train scaled MSE 0.000345534; val RMSE 0.0006898713; lr 1e-05; 295s
network 3, training 3, epoch 1630: train scaled MSE 0.000345026; val RMSE 0.0006898852; lr 1e-05; 297s
network 3, training 3, epoch 1640: train scaled MSE 0.000345151; val RMSE 0.000690142; lr 1e-05; 298s
network 3, training 3, epoch 1650: train scaled MSE 0.000342548; val RMSE 0.0006896345; lr 1e-05; 300s
network 3, training 3, epoch 1660: train scaled MSE 0.000341331; val RMSE 0.0006901654; lr 1e-05; 302s
network 3, training 3, epoch 1670: train scaled MSE 0.000341467; val RMSE 0.0006896022; lr 1e-05; 303s
network 3, training 3, epoch 1680: train scaled MSE 0.000340648; val RMSE 0.0006895327; lr 1e-05; 305s
network 3, training 3, epoch 1690: train scaled MSE 0.000338501; val RMSE 0.000689357; lr 1e-05; 307s
network 3, training 3, epoch 1700: train scaled MSE 0.00033845; val RMSE 0.0006892588; lr 1e-05; 308s
network 3, training 3, epoch 1710: train scaled MSE 0.000336455; val RMSE 0.0006893411; lr 1e-05; 310s
network 3, training 3, epoch 1720: train scaled MSE 0.00033557; val RMSE 0.0006903891; lr 1e-05; 312s
network 3, training 3, epoch 1730: train scaled MSE 0.000334864; val RMSE 0.0006893654; lr 1e-05; 314s
network 3, training 3, epoch 1740: train scaled MSE 0.000333901; val RMSE 0.000689797; lr 1e-05; 316s
network 3, training 3, epoch 1750: train scaled MSE 0.000332436; val RMSE 0.0006893172; lr 1e-05; 318s
network 3, training 3, epoch 1760: train scaled MSE 0.000332673; val RMSE 0.0006893887; lr 1e-05; 319s
network 3, training 3, epoch 1770: train scaled MSE 0.000337653; val RMSE 0.0006889881; lr 1e-05; 321s
network 3, training 3, epoch 1780: train scaled MSE 0.000337233; val RMSE 0.0006899423; lr 1e-05; 322s
network 3, training 3, epoch 1790: train scaled MSE 0.000328745; val RMSE 0.0006886665; lr 1e-05; 324s
network 3, training 3, epoch 1800: train scaled MSE 0.000338698; val RMSE 0.0006903939; lr 1e-05; 326s
network 3, training 3, epoch 1810: train scaled MSE 0.000340329; val RMSE 0.0006895931; lr 1e-05; 328s
network 3, training 3, epoch 1820: train scaled MSE 0.000327393; val RMSE 0.0006894182; lr 1e-05; 329s
network 3, training 3, epoch 1830: train scaled MSE 0.000328536; val RMSE 0.0006887436; lr 1e-05; 331s
network 3, training 3, epoch 1840: train scaled MSE 0.00032597; val RMSE 0.0006884658; lr 1e-05; 333s
network 3, training 3, epoch 1850: train scaled MSE 0.00032458; val RMSE 0.0006888423; lr 1e-05; 335s
network 3, training 3, epoch 1860: train scaled MSE 0.000325047; val RMSE 0.0006889993; lr 1e-05; 336s
network 3, training 3, epoch 1870: train scaled MSE 0.000322361; val RMSE 0.0006882608; lr 1e-05; 338s
network 3, training 3, epoch 1880: train scaled MSE 0.000323347; val RMSE 0.0006887752; lr 1e-05; 340s
network 3, training 3, epoch 1890: train scaled MSE 0.000334443; val RMSE 0.0006888957; lr 1e-05; 342s
network 3, training 3, epoch 1900: train scaled MSE 0.000319928; val RMSE 0.0006882252; lr 1e-05; 344s
network 3, training 3, epoch 1910: train scaled MSE 0.000319374; val RMSE 0.0006891367; lr 1e-05; 346s
network 3, training 3, epoch 1920: train scaled MSE 0.000319289; val RMSE 0.00068885; lr 1e-05; 348s
network 3, training 3, epoch 1930: train scaled MSE 0.000317088; val RMSE 0.0006881397; lr 1e-05; 350s
network 3, training 3, epoch 1940: train scaled MSE 0.000315981; val RMSE 0.000688106; lr 1e-05; 351s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0006,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0006,-1.5686,"[-2.86%, -0.85%]",0.0278,0.0,0.6225
MLP,0.0008,-39.4611,"[-64.66%, -24.72%]",0.1358,389.0306,0.3343

network 3, training 4, epoch 1: train scaled MSE 0.882189; val RMSE 0.01145591; lr 0.001; 0s
network 3, training 4, epoch 10: train scaled MSE 0.0133529; val RMSE 0.002134432; lr 0.001; 2s
network 3, training 4, epoch 20: train scaled MSE 0.00609724; val RMSE 0.001048799; lr 0.001; 4s
network 3, training 4, epoch 30: train scaled MSE 0.00453606; val RMSE 0.0009866069; lr 0.001; 6s
network 3, training 4, epoch 40: train scaled MSE 0.004215; val RMSE 0.0008020646; lr 0.001; 8s
network 3, training 4, epoch 50: train scaled MSE 0.00313626; val RMSE 0.0008224677; lr 0.001; 10s
network 3, training 4, epoch 60: train scaled MSE 0.00239636; val RMSE 0.0007366539; lr 0.0005; 12s
network 3, training 4, epoch 70: train scaled MSE 0.00210062; val RMSE 0.0007285048; lr 0.0005; 14s
network 3, training 4, epoch 80: train scaled MSE 0.00177584; val RMSE 0.0007196168; lr 0.0005; 16s
network 3, training 4, epoch 90: train scaled MSE 0.00149899; val RMSE 0.000730365; lr 0.0005; 18s
network 3, training 4, epoch 100: train scaled MSE 0.00172201; val RMSE 0.0007635026; lr 0.0005; 20s
network 3, training 4, epoch 110: train scaled MSE 0.00126946; val RMSE 0.0007222138; lr 0.00025; 22s
network 3, training 4, epoch 120: train scaled MSE 0.0011905; val RMSE 0.0007107092; lr 0.000125; 23s
network 3, training 4, epoch 130: train scaled MSE 0.00113529; val RMSE 0.0007465807; lr 0.000125; 25s
network 3, training 4, epoch 140: train scaled MSE 0.00121757; val RMSE 0.0007072754; lr 0.000125; 27s
network 3, training 4, epoch 150: train scaled MSE 0.00105992; val RMSE 0.0006966841; lr 0.000125; 29s
network 3, training 4, epoch 160: train scaled MSE 0.000976573; val RMSE 0.0006919931; lr 0.000125; 31s
network 3, training 4, epoch 170: train scaled MSE 0.000942164; val RMSE 0.0006878466; lr 0.000125; 33s
network 3, training 4, epoch 180: train scaled MSE 0.000894603; val RMSE 0.0006864712; lr 0.000125; 35s
network 3, training 4, epoch 190: train scaled MSE 0.000866983; val RMSE 0.0006819234; lr 0.000125; 37s
network 3, training 4, epoch 200: train scaled MSE 0.000828729; val RMSE 0.0006764073; lr 0.000125; 38s
network 3, training 4, epoch 210: train scaled MSE 0.000780635; val RMSE 0.0006809594; lr 0.000125; 40s
network 3, training 4, epoch 220: train scaled MSE 0.000754762; val RMSE 0.0006744096; lr 0.000125; 42s
network 3, training 4, epoch 230: train scaled MSE 0.000725776; val RMSE 0.0006706115; lr 6.25e-05; 44s
network 3, training 4, epoch 240: train scaled MSE 0.000697596; val RMSE 0.0006700719; lr 6.25e-05; 46s
network 3, training 4, epoch 250: train scaled MSE 0.00073238; val RMSE 0.0006821377; lr 6.25e-05; 48s
network 3, training 4, epoch 260: train scaled MSE 0.000667522; val RMSE 0.0006657318; lr 6.25e-05; 50s
network 3, training 4, epoch 270: train scaled MSE 0.000893843; val RMSE 0.0006776936; lr 6.25e-05; 52s
network 3, training 4, epoch 280: train scaled MSE 0.000636379; val RMSE 0.0006653581; lr 6.25e-05; 54s
network 3, training 4, epoch 290: train scaled MSE 0.000625539; val RMSE 0.0006675392; lr 6.25e-05; 56s
network 3, training 4, epoch 300: train scaled MSE 0.000610323; val RMSE 0.0006627917; lr 3.125e-05; 58s
network 3, training 4, epoch 310: train scaled MSE 0.000603373; val RMSE 0.0006602028; lr 3.125e-05; 60s
network 3, training 4, epoch 320: train scaled MSE 0.000596509; val RMSE 0.0006612222; lr 3.125e-05; 62s
network 3, training 4, epoch 330: train scaled MSE 0.000584877; val RMSE 0.0006589491; lr 3.125e-05; 64s
network 3, training 4, epoch 340: train scaled MSE 0.00057658; val RMSE 0.0006581609; lr 3.125e-05; 66s
network 3, training 4, epoch 350: train scaled MSE 0.000568424; val RMSE 0.0006596929; lr 3.125e-05; 68s
network 3, training 4, epoch 360: train scaled MSE 0.000561146; val RMSE 0.0006661488; lr 3.125e-05; 69s
network 3, training 4, epoch 370: train scaled MSE 0.000553815; val RMSE 0.0006571877; lr 3.125e-05; 71s
network 3, training 4, epoch 380: train scaled MSE 0.000552448; val RMSE 0.0006566513; lr 3.125e-05; 73s
network 3, training 4, epoch 390: train scaled MSE 0.000542421; val RMSE 0.0006557143; lr 3.125e-05; 75s
network 3, training 4, epoch 400: train scaled MSE 0.000592716; val RMSE 0.0006605959; lr 3.125e-05; 77s
network 3, training 4, epoch 410: train scaled MSE 0.000530609; val RMSE 0.0006557742; lr 3.125e-05; 79s
network 3, training 4, epoch 420: train scaled MSE 0.000528115; val RMSE 0.0006550775; lr 3.125e-05; 81s
network 3, training 4, epoch 430: train scaled MSE 0.000518785; val RMSE 0.0006544265; lr 3.125e-05; 82s
network 3, training 4, epoch 440: train scaled MSE 0.000513246; val RMSE 0.0006544893; lr 3.125e-05; 84s
network 3, training 4, epoch 450: train scaled MSE 0.000522148; val RMSE 0.000655927; lr 3.125e-05; 86s
network 3, training 4, epoch 460: train scaled MSE 0.000498774; val RMSE 0.0006533242; lr 1.5625e-05; 88s
network 3, training 4, epoch 470: train scaled MSE 0.000505298; val RMSE 0.0006560924; lr 1.5625e-05; 89s
network 3, training 4, epoch 480: train scaled MSE 0.000492187; val RMSE 0.0006533589; lr 1e-05; 91s
network 3, training 4, epoch 490: train scaled MSE 0.000491011; val RMSE 0.0006533021; lr 1e-05; 93s
network 3, training 4, epoch 500: train scaled MSE 0.000488574; val RMSE 0.0006528338; lr 1e-05; 95s
network 3, training 4, epoch 510: train scaled MSE 0.000489614; val RMSE 0.0006530838; lr 1e-05; 97s
network 3, training 4, epoch 520: train scaled MSE 0.000485693; val RMSE 0.0006530207; lr 1e-05; 98s
network 3, training 4, epoch 530: train scaled MSE 0.000484516; val RMSE 0.0006525573; lr 1e-05; 100s
network 3, training 4, epoch 540: train scaled MSE 0.000483159; val RMSE 0.0006525635; lr 1e-05; 102s
network 3, training 4, epoch 550: train scaled MSE 0.000481114; val RMSE 0.0006521218; lr 1e-05; 104s
network 3, training 4, epoch 560: train scaled MSE 0.00047934; val RMSE 0.0006520153; lr 1e-05; 105s
network 3, training 4, epoch 570: train scaled MSE 0.000477992; val RMSE 0.0006518643; lr 1e-05; 107s
network 3, training 4, epoch 580: train scaled MSE 0.000476365; val RMSE 0.0006519715; lr 1e-05; 109s
network 3, training 4, epoch 590: train scaled MSE 0.000476969; val RMSE 0.000651926; lr 1e-05; 111s
network 3, training 4, epoch 600: train scaled MSE 0.000476279; val RMSE 0.0006521776; lr 1e-05; 113s
network 3, training 4, epoch 610: train scaled MSE 0.000471325; val RMSE 0.0006518424; lr 1e-05; 115s
network 3, training 4, epoch 620: train scaled MSE 0.000470937; val RMSE 0.0006518219; lr 1e-05; 117s
network 3, training 4, epoch 630: train scaled MSE 0.000468341; val RMSE 0.0006518265; lr 1e-05; 119s
Standard Linear Baseline Validation RMSE: 0.0004992359

Network seed 3, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-1.2474,"[-2.31%, -0.54%]",0.0192,0.0,0.5803
MLP,0.0008,-29.3136,"[-51.91%, -14.74%]",0.1339,598.6982,0.2635

network 3, training 5, epoch 1: train scaled MSE 0.869627; val RMSE 0.01154726; lr 0.001; 0s
network 3, training 5, epoch 10: train scaled MSE 0.0139974; val RMSE 0.002252726; lr 0.001; 2s
network 3, training 5, epoch 20: train scaled MSE 0.0051739; val RMSE 0.002545594; lr 0.001; 4s
network 3, training 5, epoch 30: train scaled MSE 0.0041381; val RMSE 0.002592169; lr 0.001; 6s
network 3, training 5, epoch 40: train scaled MSE 0.00445329; val RMSE 0.001266968; lr 0.001; 8s
network 3, training 5, epoch 50: train scaled MSE 0.00271991; val RMSE 0.0009495664; lr 0.001; 10s
network 3, training 5, epoch 60: train scaled MSE 0.00249726; val RMSE 0.0009664366; lr 0.001; 12s
network 3, training 5, epoch 70: train scaled MSE 0.00187302; val RMSE 0.0009688885; lr 0.001; 14s
network 3, training 5, epoch 80: train scaled MSE 0.00180483; val RMSE 0.0009394448; lr 0.001; 15s
network 3, training 5, epoch 90: train scaled MSE 0.00322043; val RMSE 0.0009649008; lr 0.001; 17s
network 3, training 5, epoch 100: train scaled MSE 0.00186647; val RMSE 0.0009236674; lr 0.0005; 19s
network 3, training 5, epoch 110: train scaled MSE 0.00123419; val RMSE 0.0009998954; lr 0.0005; 21s
network 3, training 5, epoch 120: train scaled MSE 0.00101035; val RMSE 0.0008904361; lr 0.0005; 23s
network 3, training 5, epoch 130: train scaled MSE 0.000857726; val RMSE 0.0008846516; lr 0.0005; 25s
network 3, training 5, epoch 140: train scaled MSE 0.000776339; val RMSE 0.0008771836; lr 0.0005; 27s
network 3, training 5, epoch 150: train scaled MSE 0.000713918; val RMSE 0.0008746992; lr 0.0005; 29s
network 3, training 5, epoch 160: train scaled MSE 0.000701978; val RMSE 0.000879982; lr 0.0005; 31s
network 3, training 5, epoch 170: train scaled MSE 0.000659359; val RMSE 0.001064153; lr 0.0005; 33s
network 3, training 5, epoch 180: train scaled MSE 0.000543272; val RMSE 0.0008639371; lr 0.0005; 35s
network 3, training 5, epoch 190: train scaled MSE 0.000454954; val RMSE 0.0008489937; lr 0.00025; 37s
network 3, training 5, epoch 200: train scaled MSE 0.000446475; val RMSE 0.0008450112; lr 0.00025; 39s
network 3, training 5, epoch 210: train scaled MSE 0.000420329; val RMSE 0.0008515449; lr 0.00025; 41s
network 3, training 5, epoch 220: train scaled MSE 0.00037322; val RMSE 0.0008360043; lr 0.000125; 43s
network 3, training 5, epoch 230: train scaled MSE 0.00047015; val RMSE 0.0008372604; lr 0.000125; 44s
network 3, training 5, epoch 240: train scaled MSE 0.000351554; val RMSE 0.0008320548; lr 0.000125; 46s
network 3, training 5, epoch 250: train scaled MSE 0.000352085; val RMSE 0.0008313265; lr 0.000125; 48s
network 3, training 5, epoch 260: train scaled MSE 0.000365528; val RMSE 0.0008304688; lr 0.000125; 50s
network 3, training 5, epoch 270: train scaled MSE 0.000319006; val RMSE 0.0008281607; lr 0.000125; 52s
network 3, training 5, epoch 280: train scaled MSE 0.000309981; val RMSE 0.0008286471; lr 0.000125; 54s
network 3, training 5, epoch 290: train scaled MSE 0.000298065; val RMSE 0.0008477413; lr 0.000125; 56s
network 3, training 5, epoch 300: train scaled MSE 0.000292358; val RMSE 0.0008234661; lr 0.000125; 58s
network 3, training 5, epoch 310: train scaled MSE 0.000280823; val RMSE 0.0008237779; lr 0.000125; 60s
network 3, training 5, epoch 320: train scaled MSE 0.000274039; val RMSE 0.000822431; lr 0.000125; 62s
network 3, training 5, epoch 330: train scaled MSE 0.000271257; val RMSE 0.0008349634; lr 0.000125; 64s
network 3, training 5, epoch 340: train scaled MSE 0.000291735; val RMSE 0.0008224641; lr 6.25e-05; 66s
network 3, training 5, epoch 350: train scaled MSE 0.00024636; val RMSE 0.0008176662; lr 6.25e-05; 68s
network 3, training 5, epoch 360: train scaled MSE 0.000257886; val RMSE 0.0008187637; lr 6.25e-05; 69s
network 3, training 5, epoch 370: train scaled MSE 0.000238632; val RMSE 0.0008268225; lr 6.25e-05; 72s
network 3, training 5, epoch 380: train scaled MSE 0.000236465; val RMSE 0.0008155748; lr 6.25e-05; 73s
network 3, training 5, epoch 390: train scaled MSE 0.000260451; val RMSE 0.0008164964; lr 6.25e-05; 75s
network 3, training 5, epoch 400: train scaled MSE 0.000223173; val RMSE 0.0008149114; lr 3.125e-05; 77s
network 3, training 5, epoch 410: train scaled MSE 0.000221657; val RMSE 0.0008141527; lr 3.125e-05; 79s
network 3, training 5, epoch 420: train scaled MSE 0.000222243; val RMSE 0.0008149004; lr 3.125e-05; 81s
network 3, training 5, epoch 430: train scaled MSE 0.000215383; val RMSE 0.0008142547; lr 1.5625e-05; 83s
network 3, training 5, epoch 440: train scaled MSE 0.000214477; val RMSE 0.0008140223; lr 1.5625e-05; 84s
network 3, training 5, epoch 450: train scaled MSE 0.000243117; val RMSE 0.0008155014; lr 1.5625e-05; 86s
network 3, training 5, epoch 460: train scaled MSE 0.000213032; val RMSE 0.0008137265; lr 1e-05; 88s
network 3, training 5, epoch 470: train scaled MSE 0.000212483; val RMSE 0.0008137751; lr 1e-05; 90s
network 3, training 5, epoch 480: train scaled MSE 0.000212737; val RMSE 0.0008137939; lr 1e-05; 92s
network 3, training 5, epoch 490: train scaled MSE 0.000210731; val RMSE 0.0008135298; lr 1e-05; 94s
network 3, training 5, epoch 500: train scaled MSE 0.000210197; val RMSE 0.0008134343; lr 1e-05; 95s
network 3, training 5, epoch 510: train scaled MSE 0.000210455; val RMSE 0.0008130681; lr 1e-05; 97s
network 3, training 5, epoch 520: train scaled MSE 0.00020907; val RMSE 0.0008128335; lr 1e-05; 99s
network 3, training 5, epoch 530: train scaled MSE 0.000209881; val RMSE 0.0008130487; lr 1e-05; 101s
network 3, training 5, epoch 540: train scaled MSE 0.000208921; val RMSE 0.000812978; lr 1e-05; 103s
network 3, training 5, epoch 550: train scaled MSE 0.000207415; val RMSE 0.000813012; lr 1e-05; 104s
network 3, training 5, epoch 560: train scaled MSE 0.000206822; val RMSE 0.0008125394; lr 1e-05; 106s
network 3, training 5, epoch 570: train scaled MSE 0.000206264; val RMSE 0.0008123686; lr 1e-05; 108s
network 3, training 5, epoch 580: train scaled MSE 0.000206155; val RMSE 0.0008121364; lr 1e-05; 110s
network 3, training 5, epoch 590: train scaled MSE 0.000206772; val RMSE 0.0008122459; lr 1e-05; 112s
network 3, training 5, epoch 600: train scaled MSE 0.00020436; val RMSE 0.0008121676; lr 1e-05; 114s
network 3, training 5, epoch 610: train scaled MSE 0.000203937; val RMSE 0.0008118743; lr 1e-05; 116s
network 3, training 5, epoch 620: train scaled MSE 0.000204778; val RMSE 0.0008120931; lr 1e-05; 118s
network 3, training 5, epoch 630: train scaled MSE 0.00020299; val RMSE 0.0008113037; lr 1e-05; 120s
network 3, training 5, epoch 640: train scaled MSE 0.000202531; val RMSE 0.0008115681; lr 1e-05; 121s
network 3, training 5, epoch 650: train scaled MSE 0.000203034; val RMSE 0.0008117079; lr 1e-05; 123s
network 3, training 5, epoch 660: train scaled MSE 0.000208562; val RMSE 0.0008123441; lr 1e-05; 125s
network 3, training 5, epoch 670: train scaled MSE 0.000200915; val RMSE 0.0008113273; lr 1e-05; 127s
network 3, training 5, epoch 680: train scaled MSE 0.000201228; val RMSE 0.0008111767; lr 1e-05; 129s
network 3, training 5, epoch 690: train scaled MSE 0.000199841; val RMSE 0.0008110429; lr 1e-05; 131s
network 3, training 5, epoch 700: train scaled MSE 0.000199422; val RMSE 0.0008109121; lr 1e-05; 132s
network 3, training 5, epoch 710: train scaled MSE 0.000202147; val RMSE 0.0008107786; lr 1e-05; 134s
network 3, training 5, epoch 720: train scaled MSE 0.000200635; val RMSE 0.0008107296; lr 1e-05; 136s
network 3, training 5, epoch 730: train scaled MSE 0.000197836; val RMSE 0.0008106307; lr 1e-05; 138s
network 3, training 5, epoch 740: train scaled MSE 0.000197394; val RMSE 0.0008109327; lr 1e-05; 140s
network 3, training 5, epoch 750: train scaled MSE 0.000196994; val RMSE 0.000810308; lr 1e-05; 142s
network 3, training 5, epoch 760: train scaled MSE 0.000212056; val RMSE 0.0008110004; lr 1e-05; 144s
network 3, training 5, epoch 770: train scaled MSE 0.000196073; val RMSE 0.000810242; lr 1e-05; 146s
network 3, training 5, epoch 780: train scaled MSE 0.000196012; val RMSE 0.0008101856; lr 1e-05; 148s
network 3, training 5, epoch 790: train scaled MSE 0.000195156; val RMSE 0.0008101024; lr 1e-05; 149s
network 3, training 5, epoch 800: train scaled MSE 0.000194293; val RMSE 0.0008098504; lr 1e-05; 151s
network 3, training 5, epoch 810: train scaled MSE 0.000194501; val RMSE 0.0008098199; lr 1e-05; 153s
network 3, training 5, epoch 820: train scaled MSE 0.000198767; val RMSE 0.0008098858; lr 1e-05; 155s
network 3, training 5, epoch 830: train scaled MSE 0.000197818; val RMSE 0.0008098767; lr 1e-05; 157s
network 3, training 5, epoch 840: train scaled MSE 0.000193868; val RMSE 0.0008096104; lr 1e-05; 159s
network 3, training 5, epoch 850: train scaled MSE 0.000197153; val RMSE 0.000809834; lr 1e-05; 162s
network 3, training 5, epoch 860: train scaled MSE 0.000191941; val RMSE 0.0008094183; lr 1e-05; 164s
network 3, training 5, epoch 870: train scaled MSE 0.000191382; val RMSE 0.0008095624; lr 1e-05; 166s
network 3, training 5, epoch 880: train scaled MSE 0.000192199; val RMSE 0.0008094519; lr 1e-05; 168s
network 3, training 5, epoch 890: train scaled MSE 0.000195086; val RMSE 0.0008093544; lr 1e-05; 170s
network 3, training 5, epoch 900: train scaled MSE 0.000196479; val RMSE 0.0008100762; lr 1e-05; 172s
network 3, training 5, epoch 910: train scaled MSE 0.000189296; val RMSE 0.0008090294; lr 1e-05; 175s
network 3, training 5, epoch 920: train scaled MSE 0.00018905; val RMSE 0.000808647; lr 1e-05; 177s
network 3, training 5, epoch 930: train scaled MSE 0.00018852; val RMSE 0.0008085277; lr 1e-05; 179s
network 3, training 5, epoch 940: train scaled MSE 0.000189403; val RMSE 0.0008093242; lr 1e-05; 181s
network 3, training 5, epoch 950: train scaled MSE 0.000188379; val RMSE 0.000808814; lr 1e-05; 183s
network 3, training 5, epoch 960: train scaled MSE 0.000188324; val RMSE 0.00080889; lr 1e-05; 186s
network 3, training 5, epoch 970: train scaled MSE 0.000186249; val RMSE 0.0008087781; lr 1e-05; 188s
network 3, training 5, epoch 980: train scaled MSE 0.000185983; val RMSE 0.0008088827; lr 1e-05; 190s
network 3, training 5, epoch 990: train scaled MSE 0.000187867; val RMSE 0.0008085449; lr 1e-05; 192s
network 3, training 5, epoch 1000: train scaled MSE 0.000184557; val RMSE 0.0008082876; lr 1e-05; 194s
network 3, training 5, epoch 1010: train scaled MSE 0.000187508; val RMSE 0.0008084556; lr 1e-05; 196s
network 3, training 5, epoch 1020: train scaled MSE 0.000184133; val RMSE 0.000808142; lr 1e-05; 199s
network 3, training 5, epoch 1030: train scaled MSE 0.000183787; val RMSE 0.0008079766; lr 1e-05; 201s
network 3, training 5, epoch 1040: train scaled MSE 0.000185114; val RMSE 0.0008081728; lr 1e-05; 203s
network 3, training 5, epoch 1050: train scaled MSE 0.00018269; val RMSE 0.0008078083; lr 1e-05; 205s
network 3, training 5, epoch 1060: train scaled MSE 0.000182607; val RMSE 0.0008078459; lr 1e-05; 207s
network 3, training 5, epoch 1070: train scaled MSE 0.000181978; val RMSE 0.0008080128; lr 1e-05; 209s
network 3, training 5, epoch 1080: train scaled MSE 0.000190718; val RMSE 0.0008092069; lr 1e-05; 211s
network 3, training 5, epoch 1090: train scaled MSE 0.000181864; val RMSE 0.0008078581; lr 1e-05; 213s
network 3, training 5, epoch 1100: train scaled MSE 0.000180985; val RMSE 0.0008079449; lr 1e-05; 215s
network 3, training 5, epoch 1110: train scaled MSE 0.000181118; val RMSE 0.0008076556; lr 1e-05; 217s
network 3, training 5, epoch 1120: train scaled MSE 0.000187247; val RMSE 0.0008078592; lr 1e-05; 219s
network 3, training 5, epoch 1130: train scaled MSE 0.000181351; val RMSE 0.000809496; lr 1e-05; 220s
network 3, training 5, epoch 1140: train scaled MSE 0.00018114; val RMSE 0.0008077749; lr 1e-05; 222s
network 3, training 5, epoch 1150: train scaled MSE 0.000179353; val RMSE 0.0008074437; lr 1e-05; 224s
network 3, training 5, epoch 1160: train scaled MSE 0.000178121; val RMSE 0.0008071806; lr 1e-05; 226s
network 3, training 5, epoch 1170: train scaled MSE 0.000178207; val RMSE 0.0008070597; lr 1e-05; 228s
network 3, training 5, epoch 1180: train scaled MSE 0.000177748; val RMSE 0.0008071172; lr 1e-05; 230s
network 3, training 5, epoch 1190: train scaled MSE 0.000177614; val RMSE 0.0008068659; lr 1e-05; 232s
network 3, training 5, epoch 1200: train scaled MSE 0.000178345; val RMSE 0.0008077352; lr 1e-05; 234s
network 3, training 5, epoch 1210: train scaled MSE 0.000205651; val RMSE 0.0008067941; lr 1e-05; 236s
network 3, training 5, epoch 1220: train scaled MSE 0.000178328; val RMSE 0.0008068196; lr 1e-05; 238s
network 3, training 5, epoch 1230: train scaled MSE 0.000175904; val RMSE 0.0008067481; lr 1e-05; 240s
network 3, training 5, epoch 1240: train scaled MSE 0.000175371; val RMSE 0.0008065587; lr 1e-05; 242s
network 3, training 5, epoch 1250: train scaled MSE 0.000175215; val RMSE 0.0008066951; lr 1e-05; 243s
Standard Linear Baseline Validation RMSE: 0.0006744475

Network seed 3, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-1.6560,"[-2.95%, -0.78%]",0.0208,0.0,0.6197
MLP,0.0007,-23.3661,"[-44.32%, -10.32%]",0.1929,827.2305,0.3456

network 3, training 6, epoch 1: train scaled MSE 0.885815; val RMSE 0.01091342; lr 0.001; 0s
network 3, training 6, epoch 10: train scaled MSE 0.0219423; val RMSE 0.002712507; lr 0.001; 2s
network 3, training 6, epoch 20: train scaled MSE 0.00785551; val RMSE 0.001530341; lr 0.001; 4s
network 3, training 6, epoch 30: train scaled MSE 0.00462039; val RMSE 0.001210713; lr 0.001; 6s
network 3, training 6, epoch 40: train scaled MSE 0.00308128; val RMSE 0.001102629; lr 0.001; 7s
network 3, training 6, epoch 50: train scaled MSE 0.00337406; val RMSE 0.001201083; lr 0.001; 9s
network 3, training 6, epoch 60: train scaled MSE 0.0023375; val RMSE 0.001144595; lr 0.001; 11s
network 3, training 6, epoch 70: train scaled MSE 0.00195139; val RMSE 0.001010669; lr 0.001; 13s
network 3, training 6, epoch 80: train scaled MSE 0.00169024; val RMSE 0.00116739; lr 0.001; 15s
network 3, training 6, epoch 90: train scaled MSE 0.00189669; val RMSE 0.0009963945; lr 0.001; 16s
network 3, training 6, epoch 100: train scaled MSE 0.00222139; val RMSE 0.0009883153; lr 0.001; 18s
network 3, training 6, epoch 110: train scaled MSE 0.000934132; val RMSE 0.0009598081; lr 0.0005; 20s
network 3, training 6, epoch 120: train scaled MSE 0.00172431; val RMSE 0.0009655107; lr 0.0005; 22s
network 3, training 6, epoch 130: train scaled MSE 0.000778365; val RMSE 0.0009398863; lr 0.0005; 23s
network 3, training 6, epoch 140: train scaled MSE 0.000785345; val RMSE 0.0009527052; lr 0.0005; 25s
network 3, training 6, epoch 150: train scaled MSE 0.000661597; val RMSE 0.0009423084; lr 0.0005; 27s
network 3, training 6, epoch 160: train scaled MSE 0.000649877; val RMSE 0.0009254367; lr 0.0005; 29s
network 3, training 6, epoch 170: train scaled MSE 0.000766293; val RMSE 0.0009321957; lr 0.0005; 31s
network 3, training 6, epoch 180: train scaled MSE 0.000494072; val RMSE 0.0009127438; lr 0.00025; 33s
network 3, training 6, epoch 190: train scaled MSE 0.000484081; val RMSE 0.0009079793; lr 0.00025; 35s
network 3, training 6, epoch 200: train scaled MSE 0.000453747; val RMSE 0.0009323477; lr 0.00025; 37s
network 3, training 6, epoch 210: train scaled MSE 0.000429409; val RMSE 0.0009013636; lr 0.00025; 38s
network 3, training 6, epoch 220: train scaled MSE 0.000807481; val RMSE 0.0009049663; lr 0.00025; 40s
network 3, training 6, epoch 230: train scaled MSE 0.000388813; val RMSE 0.0008940019; lr 0.00025; 42s
network 3, training 6, epoch 240: train scaled MSE 0.000372004; val RMSE 0.0008912521; lr 0.00025; 44s
network 3, training 6, epoch 250: train scaled MSE 0.000364342; val RMSE 0.0008913964; lr 0.00025; 46s
network 3, training 6, epoch 260: train scaled MSE 0.000353109; val RMSE 0.0008853166; lr 0.000125; 48s
network 3, training 6, epoch 270: train scaled MSE 0.000315733; val RMSE 0.0008833632; lr 0.000125; 49s
network 3, training 6, epoch 280: train scaled MSE 0.000303726; val RMSE 0.0008982531; lr 0.000125; 51s
network 3, training 6, epoch 290: train scaled MSE 0.000294571; val RMSE 0.0008813833; lr 0.000125; 53s
network 3, training 6, epoch 300: train scaled MSE 0.000287573; val RMSE 0.000880825; lr 0.000125; 55s
network 3, training 6, epoch 310: train scaled MSE 0.000707714; val RMSE 0.0008869588; lr 0.000125; 57s
network 3, training 6, epoch 320: train scaled MSE 0.000271431; val RMSE 0.0008779043; lr 0.000125; 59s
network 3, training 6, epoch 330: train scaled MSE 0.000672862; val RMSE 0.0008838503; lr 0.000125; 61s
network 3, training 6, epoch 340: train scaled MSE 0.0002728; val RMSE 0.0008769831; lr 0.000125; 62s
network 3, training 6, epoch 350: train scaled MSE 0.000263839; val RMSE 0.0008743868; lr 0.000125; 64s
network 3, training 6, epoch 360: train scaled MSE 0.000252928; val RMSE 0.000874334; lr 0.000125; 66s
network 3, training 6, epoch 370: train scaled MSE 0.000247287; val RMSE 0.0008732591; lr 0.000125; 68s
network 3, training 6, epoch 380: train scaled MSE 0.000318799; val RMSE 0.0008824455; lr 0.000125; 70s
network 3, training 6, epoch 390: train scaled MSE 0.000229574; val RMSE 0.0008711339; lr 0.000125; 72s
network 3, training 6, epoch 400: train scaled MSE 0.000235086; val RMSE 0.0008705538; lr 0.000125; 74s
network 3, training 6, epoch 410: train scaled MSE 0.000311653; val RMSE 0.0008713837; lr 0.000125; 77s
network 3, training 6, epoch 420: train scaled MSE 0.00029962; val RMSE 0.0008707692; lr 0.000125; 79s
network 3, training 6, epoch 430: train scaled MSE 0.000203209; val RMSE 0.0008674311; lr 6.25e-05; 81s
network 3, training 6, epoch 440: train scaled MSE 0.000201014; val RMSE 0.0008666247; lr 6.25e-05; 83s
network 3, training 6, epoch 450: train scaled MSE 0.000196002; val RMSE 0.0008666537; lr 6.25e-05; 86s
network 3, training 6, epoch 460: train scaled MSE 0.0001953; val RMSE 0.0008655671; lr 6.25e-05; 88s
network 3, training 6, epoch 470: train scaled MSE 0.000239871; val RMSE 0.000866785; lr 6.25e-05; 90s
network 3, training 6, epoch 480: train scaled MSE 0.000184764; val RMSE 0.0008639783; lr 3.125e-05; 92s
network 3, training 6, epoch 490: train scaled MSE 0.000182718; val RMSE 0.0008646335; lr 3.125e-05; 94s
network 3, training 6, epoch 500: train scaled MSE 0.00020739; val RMSE 0.0008647617; lr 3.125e-05; 97s
network 3, training 6, epoch 510: train scaled MSE 0.000191393; val RMSE 0.0008644806; lr 3.125e-05; 99s
network 3, training 6, epoch 520: train scaled MSE 0.000178748; val RMSE 0.000863309; lr 3.125e-05; 101s
network 3, training 6, epoch 530: train scaled MSE 0.000177127; val RMSE 0.0008632506; lr 3.125e-05; 103s
network 3, training 6, epoch 540: train scaled MSE 0.000175763; val RMSE 0.0008629445; lr 3.125e-05; 105s
network 3, training 6, epoch 550: train scaled MSE 0.000174478; val RMSE 0.0008625271; lr 3.125e-05; 108s
network 3, training 6, epoch 560: train scaled MSE 0.000172286; val RMSE 0.0008625256; lr 3.125e-05; 110s
network 3, training 6, epoch 570: train scaled MSE 0.000170328; val RMSE 0.000862425; lr 3.125e-05; 112s
network 3, training 6, epoch 580: train scaled MSE 0.00017057; val RMSE 0.0008617674; lr 1.5625e-05; 114s
network 3, training 6, epoch 590: train scaled MSE 0.000167236; val RMSE 0.000861803; lr 1.5625e-05; 116s
network 3, training 6, epoch 600: train scaled MSE 0.000173675; val RMSE 0.0008617992; lr 1.5625e-05; 119s
network 3, training 6, epoch 610: train scaled MSE 0.000166109; val RMSE 0.0008623094; lr 1.5625e-05; 121s
network 3, training 6, epoch 620: train scaled MSE 0.0001643; val RMSE 0.0008612769; lr 1e-05; 123s
network 3, training 6, epoch 630: train scaled MSE 0.000163782; val RMSE 0.0008611156; lr 1e-05; 125s
network 3, training 6, epoch 640: train scaled MSE 0.00016353; val RMSE 0.0008611445; lr 1e-05; 127s
network 3, training 6, epoch 650: train scaled MSE 0.000164074; val RMSE 0.0008612089; lr 1e-05; 130s
network 3, training 6, epoch 660: train scaled MSE 0.000162415; val RMSE 0.0008608782; lr 1e-05; 132s
network 3, training 6, epoch 670: train scaled MSE 0.000164538; val RMSE 0.0008609168; lr 1e-05; 134s
network 3, training 6, epoch 680: train scaled MSE 0.000163206; val RMSE 0.0008609669; lr 1e-05; 136s
network 3, training 6, epoch 690: train scaled MSE 0.000161217; val RMSE 0.0008606882; lr 1e-05; 138s
network 3, training 6, epoch 700: train scaled MSE 0.000165796; val RMSE 0.0008609101; lr 1e-05; 140s
network 3, training 6, epoch 710: train scaled MSE 0.000160265; val RMSE 0.0008605688; lr 1e-05; 142s
network 3, training 6, epoch 720: train scaled MSE 0.000159826; val RMSE 0.0008603574; lr 1e-05; 144s
network 3, training 6, epoch 730: train scaled MSE 0.000161574; val RMSE 0.0008603766; lr 1e-05; 146s
network 3, training 6, epoch 740: train scaled MSE 0.000163561; val RMSE 0.0008604583; lr 1e-05; 147s
network 3, training 6, epoch 750: train scaled MSE 0.00017862; val RMSE 0.0008618546; lr 1e-05; 149s
network 3, training 6, epoch 760: train scaled MSE 0.000158268; val RMSE 0.0008602152; lr 1e-05; 151s
network 3, training 6, epoch 770: train scaled MSE 0.000157799; val RMSE 0.000860078; lr 1e-05; 153s
network 3, training 6, epoch 780: train scaled MSE 0.000157529; val RMSE 0.0008603621; lr 1e-05; 155s
network 3, training 6, epoch 790: train scaled MSE 0.000156916; val RMSE 0.0008598666; lr 1e-05; 157s
network 3, training 6, epoch 800: train scaled MSE 0.000156956; val RMSE 0.0008598042; lr 1e-05; 159s
network 3, training 6, epoch 810: train scaled MSE 0.000156223; val RMSE 0.0008596354; lr 1e-05; 161s
network 3, training 6, epoch 820: train scaled MSE 0.000156363; val RMSE 0.00085995; lr 1e-05; 163s
network 3, training 6, epoch 830: train scaled MSE 0.000155511; val RMSE 0.0008596036; lr 1e-05; 165s
network 3, training 6, epoch 840: train scaled MSE 0.000155395; val RMSE 0.0008596718; lr 1e-05; 167s
network 3, training 6, epoch 850: train scaled MSE 0.000154625; val RMSE 0.0008601039; lr 1e-05; 168s
network 3, training 6, epoch 860: train scaled MSE 0.00015406; val RMSE 0.0008594426; lr 1e-05; 170s
network 3, training 6, epoch 870: train scaled MSE 0.000160648; val RMSE 0.0008604059; lr 1e-05; 172s
network 3, training 6, epoch 880: train scaled MSE 0.000153459; val RMSE 0.0008595945; lr 1e-05; 174s
network 3, training 6, epoch 890: train scaled MSE 0.000152737; val RMSE 0.0008592729; lr 1e-05; 176s
network 3, training 6, epoch 900: train scaled MSE 0.000152416; val RMSE 0.0008600543; lr 1e-05; 178s
network 3, training 6, epoch 910: train scaled MSE 0.000152324; val RMSE 0.0008594403; lr 1e-05; 181s
network 3, training 6, epoch 920: train scaled MSE 0.00015181; val RMSE 0.0008592437; lr 1e-05; 183s
network 3, training 6, epoch 930: train scaled MSE 0.000151084; val RMSE 0.0008590268; lr 1e-05; 184s
network 3, training 6, epoch 940: train scaled MSE 0.00015101; val RMSE 0.0008589165; lr 1e-05; 186s
network 3, training 6, epoch 950: train scaled MSE 0.000150572; val RMSE 0.0008588351; lr 1e-05; 188s
network 3, training 6, epoch 960: train scaled MSE 0.000150566; val RMSE 0.000859094; lr 1e-05; 190s
network 3, training 6, epoch 970: train scaled MSE 0.000150549; val RMSE 0.0008589175; lr 1e-05; 192s
network 3, training 6, epoch 980: train scaled MSE 0.00014996; val RMSE 0.0008585292; lr 1e-05; 194s
network 3, training 6, epoch 990: train scaled MSE 0.000149339; val RMSE 0.0008588559; lr 1e-05; 196s
network 3, training 6, epoch 1000: train scaled MSE 0.000148923; val RMSE 0.0008585977; lr 1e-05; 198s
network 3, training 6, epoch 1010: train scaled MSE 0.000155935; val RMSE 0.0008588411; lr 1e-05; 200s
network 3, training 6, epoch 1020: train scaled MSE 0.000148144; val RMSE 0.0008585874; lr 1e-05; 202s
network 3, training 6, epoch 1030: train scaled MSE 0.000148182; val RMSE 0.0008581625; lr 1e-05; 204s
network 3, training 6, epoch 1040: train scaled MSE 0.000147512; val RMSE 0.0008581497; lr 1e-05; 207s
network 3, training 6, epoch 1050: train scaled MSE 0.000153341; val RMSE 0.0008588905; lr 1e-05; 209s
network 3, training 6, epoch 1060: train scaled MSE 0.000154772; val RMSE 0.0008586448; lr 1e-05; 211s
network 3, training 6, epoch 1070: train scaled MSE 0.000149011; val RMSE 0.000858016; lr 1e-05; 213s
network 3, training 6, epoch 1080: train scaled MSE 0.000146196; val RMSE 0.0008578599; lr 1e-05; 215s
network 3, training 6, epoch 1090: train scaled MSE 0.000167839; val RMSE 0.0008612734; lr 1e-05; 218s
network 3, training 6, epoch 1100: train scaled MSE 0.00014562; val RMSE 0.0008579007; lr 1e-05; 220s
network 3, training 6, epoch 1110: train scaled MSE 0.000145113; val RMSE 0.0008576934; lr 1e-05; 222s
network 3, training 6, epoch 1120: train scaled MSE 0.000145221; val RMSE 0.0008576987; lr 1e-05; 224s
network 3, training 6, epoch 1130: train scaled MSE 0.000147089; val RMSE 0.0008579813; lr 1e-05; 227s
network 3, training 6, epoch 1140: train scaled MSE 0.000144153; val RMSE 0.0008575864; lr 1e-05; 229s
network 3, training 6, epoch 1150: train scaled MSE 0.000144587; val RMSE 0.0008575176; lr 1e-05; 231s
network 3, training 6, epoch 1160: train scaled MSE 0.000145099; val RMSE 0.0008575495; lr 1e-05; 233s
network 3, training 6, epoch 1170: train scaled MSE 0.000144055; val RMSE 0.0008574599; lr 1e-05; 236s
network 3, training 6, epoch 1180: train scaled MSE 0.000143892; val RMSE 0.0008574378; lr 1e-05; 238s
network 3, training 6, epoch 1190: train scaled MSE 0.000142679; val RMSE 0.0008571978; lr 1e-05; 240s
network 3, training 6, epoch 1200: train scaled MSE 0.000143036; val RMSE 0.0008573245; lr 1e-05; 242s
network 3, training 6, epoch 1210: train scaled MSE 0.000142073; val RMSE 0.0008572637; lr 1e-05; 244s
network 3, training 6, epoch 1220: train scaled MSE 0.000141737; val RMSE 0.0008570184; lr 1e-05; 246s
network 3, training 6, epoch 1230: train scaled MSE 0.000141861; val RMSE 0.0008571635; lr 1e-05; 249s
network 3, training 6, epoch 1240: train scaled MSE 0.000141314; val RMSE 0.0008570519; lr 1e-05; 251s
network 3, training 6, epoch 1250: train scaled MSE 0.000141087; val RMSE 0.0008575824; lr 1e-05; 253s
network 3, training 6, epoch 1260: train scaled MSE 0.000142041; val RMSE 0.0008578749; lr 1e-05; 255s
network 3, training 6, epoch 1270: train scaled MSE 0.00014127; val RMSE 0.0008569924; lr 1e-05; 257s
network 3, training 6, epoch 1280: train scaled MSE 0.000140909; val RMSE 0.0008569586; lr 1e-05; 259s
network 3, training 6, epoch 1290: train scaled MSE 0.000140585; val RMSE 0.0008569475; lr 1e-05; 261s
network 3, training 6, epoch 1300: train scaled MSE 0.000139461; val RMSE 0.0008567208; lr 1e-05; 263s
network 3, training 6, epoch 1310: train scaled MSE 0.000139809; val RMSE 0.0008568339; lr 1e-05; 265s
network 3, training 6, epoch 1320: train scaled MSE 0.000143959; val RMSE 0.0008566961; lr 1e-05; 268s
network 3, training 6, epoch 1330: train scaled MSE 0.000139854; val RMSE 0.0008565407; lr 1e-05; 270s
network 3, training 6, epoch 1340: train scaled MSE 0.000140797; val RMSE 0.0008568822; lr 1e-05; 272s
network 3, training 6, epoch 1350: train scaled MSE 0.000143498; val RMSE 0.0008566815; lr 1e-05; 274s
network 3, training 6, epoch 1360: train scaled MSE 0.000137576; val RMSE 0.0008564805; lr 1e-05; 276s
network 3, training 6, epoch 1370: train scaled MSE 0.000153901; val RMSE 0.0008567163; lr 1e-05; 278s
network 3, training 6, epoch 1380: train scaled MSE 0.000136931; val RMSE 0.000856233; lr 1e-05; 280s
network 3, training 6, epoch 1390: train scaled MSE 0.000137463; val RMSE 0.0008562338; lr 1e-05; 282s
network 3, training 6, epoch 1400: train scaled MSE 0.000137042; val RMSE 0.0008562958; lr 1e-05; 284s
network 3, training 6, epoch 1410: train scaled MSE 0.000136965; val RMSE 0.000856474; lr 1e-05; 287s
network 3, training 6, epoch 1420: train scaled MSE 0.000136313; val RMSE 0.0008562123; lr 1e-05; 289s
network 3, training 6, epoch 1430: train scaled MSE 0.000135437; val RMSE 0.0008561294; lr 1e-05; 291s
network 3, training 6, epoch 1440: train scaled MSE 0.00013534; val RMSE 0.0008560895; lr 1e-05; 293s
network 3, training 6, epoch 1450: train scaled MSE 0.000134954; val RMSE 0.0008558734; lr 1e-05; 295s
network 3, training 6, epoch 1460: train scaled MSE 0.00013513; val RMSE 0.0008561705; lr 1e-05; 297s
network 3, training 6, epoch 1470: train scaled MSE 0.000134496; val RMSE 0.0008557839; lr 1e-05; 299s
network 3, training 6, epoch 1480: train scaled MSE 0.000134046; val RMSE 0.0008558112; lr 1e-05; 301s
network 3, training 6, epoch 1490: train scaled MSE 0.00013434; val RMSE 0.0008558677; lr 1e-05; 303s
network 3, training 6, epoch 1500: train scaled MSE 0.000133749; val RMSE 0.0008557447; lr 1e-05; 305s
Standard Linear Baseline Validation RMSE: 0.0008284043

Network seed 3, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-2.2145,"[-3.64%, -1.28%]",0.0121,0.0,0.6036
MLP,0.0007,-32.7234,"[-54.16%, -17.67%]",0.1636,1247.462,0.3316

network 3, training 7, epoch 1: train scaled MSE 0.875595; val RMSE 0.01127747; lr 0.001; 0s
network 3, training 7, epoch 10: train scaled MSE 0.013104; val RMSE 0.001928841; lr 0.001; 2s
network 3, training 7, epoch 20: train scaled MSE 0.00479323; val RMSE 0.001046765; lr 0.001; 4s
network 3, training 7, epoch 30: train scaled MSE 0.00389075; val RMSE 0.002417261; lr 0.001; 6s
network 3, training 7, epoch 40: train scaled MSE 0.00293294; val RMSE 0.0008475532; lr 0.001; 8s
network 3, training 7, epoch 50: train scaled MSE 0.00263926; val RMSE 0.0009482169; lr 0.001; 11s
network 3, training 7, epoch 60: train scaled MSE 0.00237292; val RMSE 0.0009297878; lr 0.001; 13s
network 3, training 7, epoch 70: train scaled MSE 0.00193207; val RMSE 0.0008014287; lr 0.001; 15s
network 3, training 7, epoch 80: train scaled MSE 0.00172933; val RMSE 0.0007767558; lr 0.001; 17s
network 3, training 7, epoch 90: train scaled MSE 0.00143603; val RMSE 0.0007634365; lr 0.001; 19s
network 3, training 7, epoch 100: train scaled MSE 0.0015104; val RMSE 0.0008384634; lr 0.001; 20s
network 3, training 7, epoch 110: train scaled MSE 0.00100374; val RMSE 0.0007872421; lr 0.0005; 22s
network 3, training 7, epoch 120: train scaled MSE 0.000933269; val RMSE 0.0007381139; lr 0.0005; 24s
network 3, training 7, epoch 130: train scaled MSE 0.000813507; val RMSE 0.0007316825; lr 0.0005; 26s
network 3, training 7, epoch 140: train scaled MSE 0.000756523; val RMSE 0.0007199391; lr 0.0005; 28s
network 3, training 7, epoch 150: train scaled MSE 0.00577031; val RMSE 0.0007921873; lr 0.0005; 30s
network 3, training 7, epoch 160: train scaled MSE 0.000617403; val RMSE 0.0007232432; lr 0.00025; 32s
network 3, training 7, epoch 170: train scaled MSE 0.000586494; val RMSE 0.0007082872; lr 0.00025; 33s
network 3, training 7, epoch 180: train scaled MSE 0.000558573; val RMSE 0.0007115562; lr 0.00025; 35s
network 3, training 7, epoch 190: train scaled MSE 0.000531554; val RMSE 0.0007016129; lr 0.00025; 37s
network 3, training 7, epoch 200: train scaled MSE 0.000505921; val RMSE 0.0007054431; lr 0.00025; 39s
network 3, training 7, epoch 210: train scaled MSE 0.000471347; val RMSE 0.0007239065; lr 0.00025; 41s
network 3, training 7, epoch 220: train scaled MSE 0.000469038; val RMSE 0.0006989556; lr 0.00025; 43s
network 3, training 7, epoch 230: train scaled MSE 0.000407903; val RMSE 0.000691011; lr 0.000125; 45s
network 3, training 7, epoch 240: train scaled MSE 0.000406098; val RMSE 0.0006869287; lr 0.000125; 47s
network 3, training 7, epoch 250: train scaled MSE 0.000393105; val RMSE 0.0006865003; lr 0.000125; 48s
network 3, training 7, epoch 260: train scaled MSE 0.000370672; val RMSE 0.0006892466; lr 6.25e-05; 50s
network 3, training 7, epoch 270: train scaled MSE 0.000352099; val RMSE 0.0006818465; lr 3.125e-05; 52s
network 3, training 7, epoch 280: train scaled MSE 0.000352403; val RMSE 0.0006815132; lr 3.125e-05; 54s
network 3, training 7, epoch 290: train scaled MSE 0.000341414; val RMSE 0.0006811158; lr 1.5625e-05; 56s
network 3, training 7, epoch 300: train scaled MSE 0.000342747; val RMSE 0.0006812384; lr 1.5625e-05; 58s
network 3, training 7, epoch 310: train scaled MSE 0.000336769; val RMSE 0.0006803221; lr 1.5625e-05; 59s
network 3, training 7, epoch 320: train scaled MSE 0.00033523; val RMSE 0.0006802403; lr 1.5625e-05; 61s
network 3, training 7, epoch 330: train scaled MSE 0.00033372; val RMSE 0.0006800078; lr 1.5625e-05; 63s
network 3, training 7, epoch 340: train scaled MSE 0.000331669; val RMSE 0.0006797104; lr 1e-05; 65s
network 3, training 7, epoch 350: train scaled MSE 0.000331709; val RMSE 0.0006791987; lr 1e-05; 67s
network 3, training 7, epoch 360: train scaled MSE 0.000331315; val RMSE 0.0006795237; lr 1e-05; 69s
network 3, training 7, epoch 370: train scaled MSE 0.000328548; val RMSE 0.0006790996; lr 1e-05; 70s
network 3, training 7, epoch 380: train scaled MSE 0.000331186; val RMSE 0.0006790941; lr 1e-05; 72s
network 3, training 7, epoch 390: train scaled MSE 0.00032619; val RMSE 0.0006783924; lr 1e-05; 74s
network 3, training 7, epoch 400: train scaled MSE 0.000323897; val RMSE 0.0006783578; lr 1e-05; 76s
network 3, training 7, epoch 410: train scaled MSE 0.000323117; val RMSE 0.0006780823; lr 1e-05; 78s
network 3, training 7, epoch 420: train scaled MSE 0.000321558; val RMSE 0.0006776122; lr 1e-05; 79s
network 3, training 7, epoch 430: train scaled MSE 0.000320717; val RMSE 0.0006773102; lr 1e-05; 81s
network 3, training 7, epoch 440: train scaled MSE 0.000319787; val RMSE 0.0006776687; lr 1e-05; 83s
network 3, training 7, epoch 450: train scaled MSE 0.000318272; val RMSE 0.0006771793; lr 1e-05; 85s
network 3, training 7, epoch 460: train scaled MSE 0.000317664; val RMSE 0.0006776683; lr 1e-05; 87s
network 3, training 7, epoch 470: train scaled MSE 0.000316114; val RMSE 0.0006769721; lr 1e-05; 88s
network 3, training 7, epoch 480: train scaled MSE 0.000314623; val RMSE 0.0006767164; lr 1e-05; 90s
network 3, training 7, epoch 490: train scaled MSE 0.000313724; val RMSE 0.0006761209; lr 1e-05; 92s
network 3, training 7, epoch 500: train scaled MSE 0.000314832; val RMSE 0.0006764939; lr 1e-05; 94s
network 3, training 7, epoch 510: train scaled MSE 0.000311194; val RMSE 0.0006760753; lr 1e-05; 96s
network 3, training 7, epoch 520: train scaled MSE 0.000310213; val RMSE 0.0006760167; lr 1e-05; 98s
network 3, training 7, epoch 530: train scaled MSE 0.000308942; val RMSE 0.0006755095; lr 1e-05; 100s
network 3, training 7, epoch 540: train scaled MSE 0.000307677; val RMSE 0.0006756271; lr 1e-05; 101s
network 3, training 7, epoch 550: train scaled MSE 0.000307584; val RMSE 0.0006759857; lr 1e-05; 103s
network 3, training 7, epoch 560: train scaled MSE 0.000306831; val RMSE 0.0006754862; lr 1e-05; 105s
network 3, training 7, epoch 570: train scaled MSE 0.000304706; val RMSE 0.0006752049; lr 1e-05; 107s
network 3, training 7, epoch 580: train scaled MSE 0.000304582; val RMSE 0.0006750725; lr 1e-05; 109s
network 3, training 7, epoch 590: train scaled MSE 0.000303441; val RMSE 0.0006754614; lr 1e-05; 110s
network 3, training 7, epoch 600: train scaled MSE 0.000303871; val RMSE 0.0006750865; lr 1e-05; 112s
Standard Linear Baseline Validation RMSE: 0.0005913658

Network seed 3, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-0.8064,"[-1.81%, -0.20%]",0.0327,0.0,0.6197
MLP,0.0008,-25.0631,"[-51.47%, -8.72%]",0.1621,396.1299,0.3131

network 3, training 8, epoch 1: train scaled MSE 0.881721; val RMSE 0.01136196; lr 0.001; 0s
network 3, training 8, epoch 10: train scaled MSE 0.0131876; val RMSE 0.002116327; lr 0.001; 2s
network 3, training 8, epoch 20: train scaled MSE 0.00495669; val RMSE 0.001379807; lr 0.001; 4s
network 3, training 8, epoch 30: train scaled MSE 0.0045057; val RMSE 0.001237204; lr 0.001; 6s
network 3, training 8, epoch 40: train scaled MSE 0.00299806; val RMSE 0.001146391; lr 0.001; 8s
network 3, training 8, epoch 50: train scaled MSE 0.00280144; val RMSE 0.001427391; lr 0.001; 10s
network 3, training 8, epoch 60: train scaled MSE 0.00199824; val RMSE 0.001171603; lr 0.001; 11s
network 3, training 8, epoch 70: train scaled MSE 0.00164541; val RMSE 0.001351861; lr 0.001; 13s
network 3, training 8, epoch 80: train scaled MSE 0.00143248; val RMSE 0.001402121; lr 0.001; 15s
network 3, training 8, epoch 90: train scaled MSE 0.00120208; val RMSE 0.001066524; lr 0.001; 17s
network 3, training 8, epoch 100: train scaled MSE 0.00130357; val RMSE 0.00102963; lr 0.001; 19s
network 3, training 8, epoch 110: train scaled MSE 0.000983042; val RMSE 0.001034357; lr 0.001; 21s
network 3, training 8, epoch 120: train scaled MSE 0.000801056; val RMSE 0.001016327; lr 0.001; 23s
network 3, training 8, epoch 130: train scaled MSE 0.00069233; val RMSE 0.001001528; lr 0.001; 25s
network 3, training 8, epoch 140: train scaled MSE 0.000658141; val RMSE 0.001110364; lr 0.001; 27s
network 3, training 8, epoch 150: train scaled MSE 0.000452955; val RMSE 0.0009697851; lr 0.0005; 29s
network 3, training 8, epoch 160: train scaled MSE 0.000462676; val RMSE 0.0009647196; lr 0.0005; 30s
network 3, training 8, epoch 170: train scaled MSE 0.000433067; val RMSE 0.001023842; lr 0.0005; 32s
network 3, training 8, epoch 180: train scaled MSE 0.000586685; val RMSE 0.0009548275; lr 0.00025; 34s
network 3, training 8, epoch 190: train scaled MSE 0.000319036; val RMSE 0.000954722; lr 0.00025; 36s
network 3, training 8, epoch 200: train scaled MSE 0.000316525; val RMSE 0.000941066; lr 0.00025; 38s
network 3, training 8, epoch 210: train scaled MSE 0.000295084; val RMSE 0.0009808759; lr 0.00025; 40s
network 3, training 8, epoch 220: train scaled MSE 0.000285336; val RMSE 0.0009407618; lr 0.00025; 42s
network 3, training 8, epoch 230: train scaled MSE 0.000257068; val RMSE 0.0009354612; lr 0.000125; 43s
network 3, training 8, epoch 240: train scaled MSE 0.00025125; val RMSE 0.0009336806; lr 0.000125; 45s
network 3, training 8, epoch 250: train scaled MSE 0.000242097; val RMSE 0.0009305892; lr 0.000125; 47s
network 3, training 8, epoch 260: train scaled MSE 0.000240729; val RMSE 0.0009514345; lr 0.000125; 49s
network 3, training 8, epoch 270: train scaled MSE 0.000240284; val RMSE 0.0009353107; lr 0.000125; 51s
network 3, training 8, epoch 280: train scaled MSE 0.00028207; val RMSE 0.000926348; lr 0.000125; 52s
network 3, training 8, epoch 290: train scaled MSE 0.000220234; val RMSE 0.0009240298; lr 0.000125; 54s
network 3, training 8, epoch 300: train scaled MSE 0.00021111; val RMSE 0.0009270284; lr 6.25e-05; 56s
network 3, training 8, epoch 310: train scaled MSE 0.000201595; val RMSE 0.0009243092; lr 6.25e-05; 58s
network 3, training 8, epoch 320: train scaled MSE 0.000238929; val RMSE 0.0009222502; lr 6.25e-05; 60s
network 3, training 8, epoch 330: train scaled MSE 0.000196643; val RMSE 0.0009201195; lr 6.25e-05; 61s
network 3, training 8, epoch 340: train scaled MSE 0.000193153; val RMSE 0.0009198712; lr 3.125e-05; 63s
network 3, training 8, epoch 350: train scaled MSE 0.00019142; val RMSE 0.0009192978; lr 3.125e-05; 65s
network 3, training 8, epoch 360: train scaled MSE 0.000256001; val RMSE 0.0009216832; lr 3.125e-05; 67s
network 3, training 8, epoch 370: train scaled MSE 0.000188382; val RMSE 0.0009182412; lr 3.125e-05; 69s
network 3, training 8, epoch 380: train scaled MSE 0.000186704; val RMSE 0.0009178312; lr 3.125e-05; 70s
network 3, training 8, epoch 390: train scaled MSE 0.000186555; val RMSE 0.0009172059; lr 3.125e-05; 72s
network 3, training 8, epoch 400: train scaled MSE 0.000184587; val RMSE 0.000916786; lr 3.125e-05; 74s
network 3, training 8, epoch 410: train scaled MSE 0.000183604; val RMSE 0.0009166028; lr 3.125e-05; 76s
network 3, training 8, epoch 420: train scaled MSE 0.000182792; val RMSE 0.0009199674; lr 3.125e-05; 78s
network 3, training 8, epoch 430: train scaled MSE 0.000182241; val RMSE 0.0009151768; lr 3.125e-05; 80s
network 3, training 8, epoch 440: train scaled MSE 0.00017901; val RMSE 0.0009172685; lr 3.125e-05; 82s
network 3, training 8, epoch 450: train scaled MSE 0.000178489; val RMSE 0.0009145511; lr 3.125e-05; 84s
network 3, training 8, epoch 460: train scaled MSE 0.000176636; val RMSE 0.000914054; lr 3.125e-05; 85s
network 3, training 8, epoch 470: train scaled MSE 0.000177705; val RMSE 0.0009148298; lr 3.125e-05; 87s
network 3, training 8, epoch 480: train scaled MSE 0.000174065; val RMSE 0.0009141313; lr 1.5625e-05; 89s
network 3, training 8, epoch 490: train scaled MSE 0.000173097; val RMSE 0.0009135681; lr 1.5625e-05; 91s
network 3, training 8, epoch 500: train scaled MSE 0.000171784; val RMSE 0.0009132658; lr 1.5625e-05; 93s
network 3, training 8, epoch 510: train scaled MSE 0.000170533; val RMSE 0.0009133674; lr 1.5625e-05; 94s
network 3, training 8, epoch 520: train scaled MSE 0.000169899; val RMSE 0.0009128136; lr 1.5625e-05; 96s
network 3, training 8, epoch 530: train scaled MSE 0.00016946; val RMSE 0.0009125106; lr 1.5625e-05; 98s
network 3, training 8, epoch 540: train scaled MSE 0.000168918; val RMSE 0.0009126577; lr 1.5625e-05; 100s
network 3, training 8, epoch 550: train scaled MSE 0.00016837; val RMSE 0.0009121954; lr 1.5625e-05; 102s
network 3, training 8, epoch 560: train scaled MSE 0.000168946; val RMSE 0.0009126339; lr 1.5625e-05; 104s
network 3, training 8, epoch 570: train scaled MSE 0.000167268; val RMSE 0.000912032; lr 1.5625e-05; 105s
network 3, training 8, epoch 580: train scaled MSE 0.000165625; val RMSE 0.000911555; lr 1e-05; 107s
network 3, training 8, epoch 590: train scaled MSE 0.000164716; val RMSE 0.0009114164; lr 1e-05; 109s
network 3, training 8, epoch 600: train scaled MSE 0.000182544; val RMSE 0.0009126302; lr 1e-05; 111s
network 3, training 8, epoch 610: train scaled MSE 0.000164605; val RMSE 0.0009112904; lr 1e-05; 112s
network 3, training 8, epoch 620: train scaled MSE 0.000163419; val RMSE 0.0009110038; lr 1e-05; 114s
network 3, training 8, epoch 630: train scaled MSE 0.000163041; val RMSE 0.0009109089; lr 1e-05; 116s
network 3, training 8, epoch 640: train scaled MSE 0.0001627; val RMSE 0.0009107152; lr 1e-05; 118s
network 3, training 8, epoch 650: train scaled MSE 0.000167675; val RMSE 0.0009110776; lr 1e-05; 120s
network 3, training 8, epoch 660: train scaled MSE 0.000163169; val RMSE 0.000910684; lr 1e-05; 122s
network 3, training 8, epoch 670: train scaled MSE 0.000162261; val RMSE 0.0009103312; lr 1e-05; 123s
network 3, training 8, epoch 680: train scaled MSE 0.000163099; val RMSE 0.0009103674; lr 1e-05; 125s
network 3, training 8, epoch 690: train scaled MSE 0.000161847; val RMSE 0.0009101665; lr 1e-05; 127s
network 3, training 8, epoch 700: train scaled MSE 0.000160413; val RMSE 0.0009097708; lr 1e-05; 129s
network 3, training 8, epoch 710: train scaled MSE 0.000160221; val RMSE 0.0009097493; lr 1e-05; 131s
network 3, training 8, epoch 720: train scaled MSE 0.00016345; val RMSE 0.0009098256; lr 1e-05; 132s
network 3, training 8, epoch 730: train scaled MSE 0.000164596; val RMSE 0.0009097427; lr 1e-05; 134s
network 3, training 8, epoch 740: train scaled MSE 0.000175447; val RMSE 0.0009109728; lr 1e-05; 136s
network 3, training 8, epoch 750: train scaled MSE 0.000158882; val RMSE 0.0009095142; lr 1e-05; 138s
network 3, training 8, epoch 760: train scaled MSE 0.000159563; val RMSE 0.0009093394; lr 1e-05; 139s
network 3, training 8, epoch 770: train scaled MSE 0.000159069; val RMSE 0.0009091594; lr 1e-05; 141s
network 3, training 8, epoch 780: train scaled MSE 0.000158318; val RMSE 0.0009090585; lr 1e-05; 143s
network 3, training 8, epoch 790: train scaled MSE 0.000157043; val RMSE 0.0009087365; lr 1e-05; 145s
network 3, training 8, epoch 800: train scaled MSE 0.000158484; val RMSE 0.0009089157; lr 1e-05; 147s
network 3, training 8, epoch 810: train scaled MSE 0.000156298; val RMSE 0.000908914; lr 1e-05; 149s
network 3, training 8, epoch 820: train scaled MSE 0.000156471; val RMSE 0.0009086569; lr 1e-05; 151s
network 3, training 8, epoch 830: train scaled MSE 0.00015677; val RMSE 0.0009086126; lr 1e-05; 153s
network 3, training 8, epoch 840: train scaled MSE 0.000155255; val RMSE 0.0009083097; lr 1e-05; 155s
network 3, training 8, epoch 850: train scaled MSE 0.000155675; val RMSE 0.0009083886; lr 1e-05; 156s
network 3, training 8, epoch 860: train scaled MSE 0.000156124; val RMSE 0.0009082484; lr 1e-05; 158s
network 3, training 8, epoch 870: train scaled MSE 0.000153982; val RMSE 0.0009080187; lr 1e-05; 160s
network 3, training 8, epoch 880: train scaled MSE 0.000153774; val RMSE 0.0009079454; lr 1e-05; 162s
network 3, training 8, epoch 890: train scaled MSE 0.000154566; val RMSE 0.000907813; lr 1e-05; 164s
network 3, training 8, epoch 900: train scaled MSE 0.000152967; val RMSE 0.0009076392; lr 1e-05; 166s
network 3, training 8, epoch 910: train scaled MSE 0.000154574; val RMSE 0.000907806; lr 1e-05; 167s
network 3, training 8, epoch 920: train scaled MSE 0.000152995; val RMSE 0.0009075908; lr 1e-05; 169s
network 3, training 8, epoch 930: train scaled MSE 0.000152853; val RMSE 0.0009074851; lr 1e-05; 171s
network 3, training 8, epoch 940: train scaled MSE 0.000152561; val RMSE 0.0009074742; lr 1e-05; 173s
network 3, training 8, epoch 950: train scaled MSE 0.000151172; val RMSE 0.0009072528; lr 1e-05; 175s
network 3, training 8, epoch 960: train scaled MSE 0.000152017; val RMSE 0.0009073322; lr 1e-05; 176s
network 3, training 8, epoch 970: train scaled MSE 0.000150446; val RMSE 0.0009069793; lr 1e-05; 178s
network 3, training 8, epoch 980: train scaled MSE 0.000151299; val RMSE 0.0009071564; lr 1e-05; 180s
network 3, training 8, epoch 990: train scaled MSE 0.000150062; val RMSE 0.000906656; lr 1e-05; 182s
network 3, training 8, epoch 1000: train scaled MSE 0.000153615; val RMSE 0.0009068055; lr 1e-05; 183s
network 3, training 8, epoch 1010: train scaled MSE 0.000149344; val RMSE 0.0009065604; lr 1e-05; 185s
network 3, training 8, epoch 1020: train scaled MSE 0.000166479; val RMSE 0.0009080651; lr 1e-05; 187s
network 3, training 8, epoch 1030: train scaled MSE 0.000150745; val RMSE 0.000906559; lr 1e-05; 188s
network 3, training 8, epoch 1040: train scaled MSE 0.000148381; val RMSE 0.0009062694; lr 1e-05; 190s
network 3, training 8, epoch 1050: train scaled MSE 0.000149875; val RMSE 0.0009061908; lr 1e-05; 192s
network 3, training 8, epoch 1060: train scaled MSE 0.000148529; val RMSE 0.0009061115; lr 1e-05; 194s
network 3, training 8, epoch 1070: train scaled MSE 0.000147286; val RMSE 0.0009059334; lr 1e-05; 196s
network 3, training 8, epoch 1080: train scaled MSE 0.00014691; val RMSE 0.0009058983; lr 1e-05; 198s
network 3, training 8, epoch 1090: train scaled MSE 0.000146593; val RMSE 0.000906077; lr 1e-05; 200s
network 3, training 8, epoch 1100: train scaled MSE 0.00014618; val RMSE 0.0009057264; lr 1e-05; 201s
network 3, training 8, epoch 1110: train scaled MSE 0.000146944; val RMSE 0.0009060153; lr 1e-05; 203s
network 3, training 8, epoch 1120: train scaled MSE 0.000146061; val RMSE 0.0009056848; lr 1e-05; 204s
network 3, training 8, epoch 1130: train scaled MSE 0.00014517; val RMSE 0.000905457; lr 1e-05; 206s
network 3, training 8, epoch 1140: train scaled MSE 0.000145355; val RMSE 0.000905889; lr 1e-05; 208s
network 3, training 8, epoch 1150: train scaled MSE 0.000145597; val RMSE 0.0009056935; lr 1e-05; 209s
network 3, training 8, epoch 1160: train scaled MSE 0.000144782; val RMSE 0.0009056161; lr 1e-05; 211s
network 3, training 8, epoch 1170: train scaled MSE 0.000144155; val RMSE 0.0009054476; lr 1e-05; 213s
network 3, training 8, epoch 1180: train scaled MSE 0.00014477; val RMSE 0.0009052888; lr 1e-05; 214s
network 3, training 8, epoch 1190: train scaled MSE 0.000143782; val RMSE 0.0009051744; lr 1e-05; 216s
network 3, training 8, epoch 1200: train scaled MSE 0.000143653; val RMSE 0.0009050574; lr 1e-05; 218s
network 3, training 8, epoch 1210: train scaled MSE 0.000144796; val RMSE 0.0009053569; lr 1e-05; 220s
network 3, training 8, epoch 1220: train scaled MSE 0.000145086; val RMSE 0.0009051133; lr 1e-05; 222s
network 3, training 8, epoch 1230: train scaled MSE 0.000142762; val RMSE 0.000904713; lr 1e-05; 224s
network 3, training 8, epoch 1240: train scaled MSE 0.000142231; val RMSE 0.0009047523; lr 1e-05; 225s
network 3, training 8, epoch 1250: train scaled MSE 0.000141989; val RMSE 0.0009047426; lr 1e-05; 227s
network 3, training 8, epoch 1260: train scaled MSE 0.00014172; val RMSE 0.0009046312; lr 1e-05; 229s
network 3, training 8, epoch 1270: train scaled MSE 0.000142143; val RMSE 0.0009046563; lr 1e-05; 231s
network 3, training 8, epoch 1280: train scaled MSE 0.000141192; val RMSE 0.0009045438; lr 1e-05; 233s
network 3, training 8, epoch 1290: train scaled MSE 0.000140799; val RMSE 0.0009044126; lr 1e-05; 234s
network 3, training 8, epoch 1300: train scaled MSE 0.000141126; val RMSE 0.0009044445; lr 1e-05; 236s
network 3, training 8, epoch 1310: train scaled MSE 0.000141296; val RMSE 0.0009047386; lr 1e-05; 238s
network 3, training 8, epoch 1320: train scaled MSE 0.000139889; val RMSE 0.0009036052; lr 1e-05; 239s
network 3, training 8, epoch 1330: train scaled MSE 0.000143156; val RMSE 0.0009040097; lr 1e-05; 241s
network 3, training 8, epoch 1340: train scaled MSE 0.000139219; val RMSE 0.0009040611; lr 1e-05; 243s
network 3, training 8, epoch 1350: train scaled MSE 0.000139218; val RMSE 0.0009036401; lr 1e-05; 245s
Standard Linear Baseline Validation RMSE: 0.0009098528

Network seed 3, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-2.1744,"[-3.12%, -1.43%]",-0.0058,0.0,0.6422
MLP,0.0008,-33.7146,"[-50.64%, -21.71%]",0.1107,1994.7162,0.3581

network 3, training 9, epoch 1: train scaled MSE 0.877563; val RMSE 0.01112405; lr 0.001; 0s
network 3, training 9, epoch 10: train scaled MSE 0.0150504; val RMSE 0.002123897; lr 0.001; 2s
network 3, training 9, epoch 20: train scaled MSE 0.00537469; val RMSE 0.001106885; lr 0.001; 3s
network 3, training 9, epoch 30: train scaled MSE 0.0042061; val RMSE 0.001008767; lr 0.001; 5s
network 3, training 9, epoch 40: train scaled MSE 0.00355814; val RMSE 0.0009489328; lr 0.001; 7s
network 3, training 9, epoch 50: train scaled MSE 0.00260529; val RMSE 0.0009073526; lr 0.001; 9s
network 3, training 9, epoch 60: train scaled MSE 0.00213479; val RMSE 0.0008491652; lr 0.001; 11s
network 3, training 9, epoch 70: train scaled MSE 0.00281672; val RMSE 0.0009855809; lr 0.001; 12s
network 3, training 9, epoch 80: train scaled MSE 0.00143037; val RMSE 0.0008799767; lr 0.001; 14s
network 3, training 9, epoch 90: train scaled MSE 0.00161799; val RMSE 0.001069403; lr 0.001; 16s
network 3, training 9, epoch 100: train scaled MSE 0.00104562; val RMSE 0.0007902603; lr 0.001; 18s
network 3, training 9, epoch 110: train scaled MSE 0.00125521; val RMSE 0.0007906283; lr 0.001; 19s
network 3, training 9, epoch 120: train scaled MSE 0.000676692; val RMSE 0.0007449518; lr 0.0005; 21s
network 3, training 9, epoch 130: train scaled MSE 0.00143673; val RMSE 0.0007559442; lr 0.0005; 23s
network 3, training 9, epoch 140: train scaled MSE 0.000596793; val RMSE 0.0007376943; lr 0.0005; 25s
network 3, training 9, epoch 150: train scaled MSE 0.000565718; val RMSE 0.0007396579; lr 0.0005; 27s
network 3, training 9, epoch 160: train scaled MSE 0.000550659; val RMSE 0.0007403313; lr 0.0005; 29s
network 3, training 9, epoch 170: train scaled MSE 0.000448102; val RMSE 0.0007244034; lr 0.00025; 30s
network 3, training 9, epoch 180: train scaled MSE 0.000438862; val RMSE 0.0007172059; lr 0.00025; 32s
network 3, training 9, epoch 190: train scaled MSE 0.000476709; val RMSE 0.000716593; lr 0.00025; 34s
network 3, training 9, epoch 200: train scaled MSE 0.000387151; val RMSE 0.0007104874; lr 0.00025; 36s
network 3, training 9, epoch 210: train scaled MSE 0.000394413; val RMSE 0.0007094247; lr 0.00025; 38s
network 3, training 9, epoch 220: train scaled MSE 0.000357991; val RMSE 0.0007049913; lr 0.00025; 40s
network 3, training 9, epoch 230: train scaled MSE 0.000338743; val RMSE 0.0007017182; lr 0.00025; 42s
network 3, training 9, epoch 240: train scaled MSE 0.000332742; val RMSE 0.000701653; lr 0.00025; 44s
network 3, training 9, epoch 250: train scaled MSE 0.000447881; val RMSE 0.0007026329; lr 0.00025; 46s
network 3, training 9, epoch 260: train scaled MSE 0.000303353; val RMSE 0.0006964075; lr 0.00025; 48s
network 3, training 9, epoch 270: train scaled MSE 0.000298064; val RMSE 0.0007817177; lr 0.00025; 50s
network 3, training 9, epoch 280: train scaled MSE 0.000274145; val RMSE 0.000693799; lr 0.000125; 51s
network 3, training 9, epoch 290: train scaled MSE 0.000253692; val RMSE 0.0006907378; lr 0.000125; 53s
network 3, training 9, epoch 300: train scaled MSE 0.000359781; val RMSE 0.0007047505; lr 0.000125; 55s
network 3, training 9, epoch 310: train scaled MSE 0.000238603; val RMSE 0.0006883625; lr 0.000125; 57s
network 3, training 9, epoch 320: train scaled MSE 0.000272836; val RMSE 0.0006913908; lr 0.000125; 58s
network 3, training 9, epoch 330: train scaled MSE 0.000228465; val RMSE 0.0006869553; lr 0.000125; 60s
network 3, training 9, epoch 340: train scaled MSE 0.000217866; val RMSE 0.0006854241; lr 0.000125; 62s
network 3, training 9, epoch 350: train scaled MSE 0.000204051; val RMSE 0.0006922056; lr 6.25e-05; 64s
network 3, training 9, epoch 360: train scaled MSE 0.000207236; val RMSE 0.0006912201; lr 6.25e-05; 66s
network 3, training 9, epoch 370: train scaled MSE 0.000194882; val RMSE 0.0006803507; lr 3.125e-05; 67s
network 3, training 9, epoch 380: train scaled MSE 0.0001933; val RMSE 0.0006799444; lr 3.125e-05; 69s
network 3, training 9, epoch 390: train scaled MSE 0.000191985; val RMSE 0.0006793765; lr 3.125e-05; 71s
network 3, training 9, epoch 400: train scaled MSE 0.000191755; val RMSE 0.0006790648; lr 3.125e-05; 73s
network 3, training 9, epoch 410: train scaled MSE 0.000188961; val RMSE 0.0006782514; lr 3.125e-05; 74s
network 3, training 9, epoch 420: train scaled MSE 0.000192313; val RMSE 0.0006786877; lr 3.125e-05; 76s
network 3, training 9, epoch 430: train scaled MSE 0.000185582; val RMSE 0.0006797095; lr 3.125e-05; 78s
network 3, training 9, epoch 440: train scaled MSE 0.000245851; val RMSE 0.0006787748; lr 3.125e-05; 79s
network 3, training 9, epoch 450: train scaled MSE 0.000182252; val RMSE 0.000676029; lr 3.125e-05; 81s
network 3, training 9, epoch 460: train scaled MSE 0.000181026; val RMSE 0.0006765905; lr 3.125e-05; 83s
network 3, training 9, epoch 470: train scaled MSE 0.000182015; val RMSE 0.0006761335; lr 1.5625e-05; 85s
network 3, training 9, epoch 480: train scaled MSE 0.00017734; val RMSE 0.0006758578; lr 1.5625e-05; 86s
network 3, training 9, epoch 490: train scaled MSE 0.000180271; val RMSE 0.0006755344; lr 1.5625e-05; 88s
network 3, training 9, epoch 500: train scaled MSE 0.000175984; val RMSE 0.0006752649; lr 1.5625e-05; 90s
network 3, training 9, epoch 510: train scaled MSE 0.000174606; val RMSE 0.0006758933; lr 1.5625e-05; 92s
network 3, training 9, epoch 520: train scaled MSE 0.000174229; val RMSE 0.0006750265; lr 1.5625e-05; 94s
network 3, training 9, epoch 530: train scaled MSE 0.000173815; val RMSE 0.0006748149; lr 1.5625e-05; 95s
network 3, training 9, epoch 540: train scaled MSE 0.000176939; val RMSE 0.0006751141; lr 1.5625e-05; 97s
network 3, training 9, epoch 550: train scaled MSE 0.000173837; val RMSE 0.0006742118; lr 1e-05; 99s
network 3, training 9, epoch 560: train scaled MSE 0.000171397; val RMSE 0.0006740795; lr 1e-05; 100s
network 3, training 9, epoch 570: train scaled MSE 0.000170557; val RMSE 0.0006740171; lr 1e-05; 102s
network 3, training 9, epoch 580: train scaled MSE 0.000169953; val RMSE 0.0006737699; lr 1e-05; 104s
network 3, training 9, epoch 590: train scaled MSE 0.0001697; val RMSE 0.0006738259; lr 1e-05; 106s
network 3, training 9, epoch 600: train scaled MSE 0.000169248; val RMSE 0.0006735489; lr 1e-05; 107s
network 3, training 9, epoch 610: train scaled MSE 0.000168174; val RMSE 0.0006741068; lr 1e-05; 109s
network 3, training 9, epoch 620: train scaled MSE 0.00016829; val RMSE 0.0006733349; lr 1e-05; 111s
network 3, training 9, epoch 630: train scaled MSE 0.000167536; val RMSE 0.0006731279; lr 1e-05; 113s
network 3, training 9, epoch 640: train scaled MSE 0.000167674; val RMSE 0.0006741443; lr 1e-05; 115s
network 3, training 9, epoch 650: train scaled MSE 0.000167795; val RMSE 0.0006729875; lr 1e-05; 116s
network 3, training 9, epoch 660: train scaled MSE 0.000166254; val RMSE 0.0006728267; lr 1e-05; 118s
network 3, training 9, epoch 670: train scaled MSE 0.000165651; val RMSE 0.0006726768; lr 1e-05; 120s
network 3, training 9, epoch 680: train scaled MSE 0.000165703; val RMSE 0.0006726804; lr 1e-05; 122s
network 3, training 9, epoch 690: train scaled MSE 0.000165301; val RMSE 0.000672805; lr 1e-05; 124s
network 3, training 9, epoch 700: train scaled MSE 0.000165112; val RMSE 0.000672452; lr 1e-05; 125s
network 3, training 9, epoch 710: train scaled MSE 0.000164051; val RMSE 0.0006722771; lr 1e-05; 127s
network 3, training 9, epoch 720: train scaled MSE 0.000163512; val RMSE 0.0006720612; lr 1e-05; 129s
network 3, training 9, epoch 730: train scaled MSE 0.000163424; val RMSE 0.0006718625; lr 1e-05; 131s
network 3, training 9, epoch 740: train scaled MSE 0.000162607; val RMSE 0.0006717107; lr 1e-05; 132s
network 3, training 9, epoch 750: train scaled MSE 0.000164371; val RMSE 0.0006719267; lr 1e-05; 134s
network 3, training 9, epoch 760: train scaled MSE 0.00016181; val RMSE 0.0006713444; lr 1e-05; 136s
network 3, training 9, epoch 770: train scaled MSE 0.000161522; val RMSE 0.0006717123; lr 1e-05; 138s
network 3, training 9, epoch 780: train scaled MSE 0.00016192; val RMSE 0.0006712436; lr 1e-05; 139s
network 3, training 9, epoch 790: train scaled MSE 0.000162891; val RMSE 0.000671466; lr 1e-05; 141s
network 3, training 9, epoch 800: train scaled MSE 0.000162095; val RMSE 0.0006714411; lr 1e-05; 143s
network 3, training 9, epoch 810: train scaled MSE 0.000159858; val RMSE 0.0006712897; lr 1e-05; 145s
network 3, training 9, epoch 820: train scaled MSE 0.000159424; val RMSE 0.0006709803; lr 1e-05; 147s
network 3, training 9, epoch 830: train scaled MSE 0.00015921; val RMSE 0.0006706957; lr 1e-05; 148s
network 3, training 9, epoch 840: train scaled MSE 0.000160298; val RMSE 0.0006708834; lr 1e-05; 150s
network 3, training 9, epoch 850: train scaled MSE 0.000161437; val RMSE 0.0006708137; lr 1e-05; 152s
network 3, training 9, epoch 860: train scaled MSE 0.00015854; val RMSE 0.0006707345; lr 1e-05; 154s
network 3, training 9, epoch 870: train scaled MSE 0.000166551; val RMSE 0.0006710954; lr 1e-05; 156s
network 3, training 9, epoch 880: train scaled MSE 0.00016163; val RMSE 0.0006707; lr 1e-05; 158s
network 3, training 9, epoch 890: train scaled MSE 0.000156778; val RMSE 0.0006702514; lr 1e-05; 159s
network 3, training 9, epoch 900: train scaled MSE 0.000156604; val RMSE 0.0006701447; lr 1e-05; 161s
network 3, training 9, epoch 910: train scaled MSE 0.000156599; val RMSE 0.0006700168; lr 1e-05; 163s
network 3, training 9, epoch 920: train scaled MSE 0.0001555; val RMSE 0.0006697087; lr 1e-05; 165s
network 3, training 9, epoch 930: train scaled MSE 0.000155544; val RMSE 0.0006696948; lr 1e-05; 167s
network 3, training 9, epoch 940: train scaled MSE 0.000154881; val RMSE 0.00066959; lr 1e-05; 169s
network 3, training 9, epoch 950: train scaled MSE 0.000155035; val RMSE 0.0006695919; lr 1e-05; 171s
network 3, training 9, epoch 960: train scaled MSE 0.000154186; val RMSE 0.0006696354; lr 1e-05; 172s
network 3, training 9, epoch 970: train scaled MSE 0.000153846; val RMSE 0.0006695471; lr 1e-05; 174s
network 3, training 9, epoch 980: train scaled MSE 0.000153687; val RMSE 0.0006693423; lr 1e-05; 176s
network 3, training 9, epoch 990: train scaled MSE 0.000153292; val RMSE 0.000669144; lr 1e-05; 178s
network 3, training 9, epoch 1000: train scaled MSE 0.000153355; val RMSE 0.000669136; lr 1e-05; 180s
network 3, training 9, epoch 1010: train scaled MSE 0.000152295; val RMSE 0.0006689407; lr 1e-05; 182s
network 3, training 9, epoch 1020: train scaled MSE 0.000152243; val RMSE 0.0006691737; lr 1e-05; 183s
network 3, training 9, epoch 1030: train scaled MSE 0.000151617; val RMSE 0.0006688; lr 1e-05; 185s
network 3, training 9, epoch 1040: train scaled MSE 0.000151239; val RMSE 0.0006687635; lr 1e-05; 187s
network 3, training 9, epoch 1050: train scaled MSE 0.000150809; val RMSE 0.0006684907; lr 1e-05; 189s
network 3, training 9, epoch 1060: train scaled MSE 0.000156048; val RMSE 0.0006688606; lr 1e-05; 191s
network 3, training 9, epoch 1070: train scaled MSE 0.00014997; val RMSE 0.0006684472; lr 1e-05; 193s
network 3, training 9, epoch 1080: train scaled MSE 0.000149689; val RMSE 0.000668333; lr 1e-05; 194s
network 3, training 9, epoch 1090: train scaled MSE 0.000149165; val RMSE 0.0006681113; lr 1e-05; 196s
network 3, training 9, epoch 1100: train scaled MSE 0.000149668; val RMSE 0.0006681511; lr 1e-05; 198s
network 3, training 9, epoch 1110: train scaled MSE 0.000148421; val RMSE 0.0006687718; lr 1e-05; 200s
network 3, training 9, epoch 1120: train scaled MSE 0.000147918; val RMSE 0.0006681708; lr 1e-05; 202s
network 3, training 9, epoch 1130: train scaled MSE 0.000147505; val RMSE 0.0006683651; lr 1e-05; 203s
network 3, training 9, epoch 1140: train scaled MSE 0.000148049; val RMSE 0.0006680353; lr 1e-05; 205s
network 3, training 9, epoch 1150: train scaled MSE 0.000146851; val RMSE 0.0006677354; lr 1e-05; 207s
network 3, training 9, epoch 1160: train scaled MSE 0.000146604; val RMSE 0.0006675279; lr 1e-05; 209s
network 3, training 9, epoch 1170: train scaled MSE 0.000160394; val RMSE 0.0006689865; lr 1e-05; 211s
network 3, training 9, epoch 1180: train scaled MSE 0.00015046; val RMSE 0.0006676132; lr 1e-05; 212s
network 3, training 9, epoch 1190: train scaled MSE 0.000145816; val RMSE 0.0006674993; lr 1e-05; 214s
network 3, training 9, epoch 1200: train scaled MSE 0.000145255; val RMSE 0.0006672701; lr 1e-05; 216s
network 3, training 9, epoch 1210: train scaled MSE 0.000145179; val RMSE 0.0006670518; lr 1e-05; 218s
network 3, training 9, epoch 1220: train scaled MSE 0.000144779; val RMSE 0.0006668825; lr 1e-05; 220s
network 3, training 9, epoch 1230: train scaled MSE 0.000144203; val RMSE 0.0006669823; lr 1e-05; 222s
network 3, training 9, epoch 1240: train scaled MSE 0.000145694; val RMSE 0.000667443; lr 1e-05; 224s
network 3, training 9, epoch 1250: train scaled MSE 0.000145127; val RMSE 0.0006670449; lr 1e-05; 226s
network 3, training 9, epoch 1260: train scaled MSE 0.000142879; val RMSE 0.0006671246; lr 1e-05; 228s
network 3, training 9, epoch 1270: train scaled MSE 0.000142628; val RMSE 0.0006666154; lr 1e-05; 230s
network 3, training 9, epoch 1280: train scaled MSE 0.000143; val RMSE 0.0006670691; lr 1e-05; 232s
network 3, training 9, epoch 1290: train scaled MSE 0.000141813; val RMSE 0.0006664269; lr 1e-05; 234s
network 3, training 9, epoch 1300: train scaled MSE 0.000142286; val RMSE 0.0006663815; lr 1e-05; 236s
network 3, training 9, epoch 1310: train scaled MSE 0.000141263; val RMSE 0.0006662609; lr 1e-05; 238s
network 3, training 9, epoch 1320: train scaled MSE 0.000141333; val RMSE 0.0006660986; lr 1e-05; 240s
network 3, training 9, epoch 1330: train scaled MSE 0.000140813; val RMSE 0.0006661209; lr 1e-05; 242s
network 3, training 9, epoch 1340: train scaled MSE 0.000158296; val RMSE 0.0006688304; lr 1e-05; 243s
network 3, training 9, epoch 1350: train scaled MSE 0.000139676; val RMSE 0.0006658769; lr 1e-05; 245s
network 3, training 9, epoch 1360: train scaled MSE 0.000146006; val RMSE 0.0006662042; lr 1e-05; 247s
network 3, training 9, epoch 1370: train scaled MSE 0.000139978; val RMSE 0.0006658266; lr 1e-05; 249s
network 3, training 9, epoch 1380: train scaled MSE 0.000139185; val RMSE 0.0006656331; lr 1e-05; 251s
network 3, training 9, epoch 1390: train scaled MSE 0.000139128; val RMSE 0.0006658804; lr 1e-05; 253s
network 3, training 9, epoch 1400: train scaled MSE 0.000138294; val RMSE 0.0006653976; lr 1e-05; 255s
network 3, training 9, epoch 1410: train scaled MSE 0.000138036; val RMSE 0.0006663554; lr 1e-05; 256s
network 3, training 9, epoch 1420: train scaled MSE 0.000137859; val RMSE 0.0006657654; lr 1e-05; 258s
network 3, training 9, epoch 1430: train scaled MSE 0.00014241; val RMSE 0.0006654203; lr 1e-05; 260s
network 3, training 9, epoch 1440: train scaled MSE 0.000137123; val RMSE 0.000665112; lr 1e-05; 262s
network 3, training 9, epoch 1450: train scaled MSE 0.000136981; val RMSE 0.0006648954; lr 1e-05; 264s
network 3, training 9, epoch 1460: train scaled MSE 0.000136967; val RMSE 0.0006647843; lr 1e-05; 266s
network 3, training 9, epoch 1470: train scaled MSE 0.000136366; val RMSE 0.0006646677; lr 1e-05; 268s
network 3, training 9, epoch 1480: train scaled MSE 0.000136031; val RMSE 0.0006647749; lr 1e-05; 270s
network 3, training 9, epoch 1490: train scaled MSE 0.00013577; val RMSE 0.0006645001; lr 1e-05; 272s
network 3, training 9, epoch 1500: train scaled MSE 0.000137876; val RMSE 0.0006647288; lr 1e-05; 274s
network 3, training 9, epoch 1510: train scaled MSE 0.000134944; val RMSE 0.0006644972; lr 1e-05; 276s
network 3, training 9, epoch 1520: train scaled MSE 0.000134566; val RMSE 0.0006644813; lr 1e-05; 278s
network 3, training 9, epoch 1530: train scaled MSE 0.000134103; val RMSE 0.0006643717; lr 1e-05; 280s
network 3, training 9, epoch 1540: train scaled MSE 0.000133765; val RMSE 0.000664159; lr 1e-05; 282s
network 3, training 9, epoch 1550: train scaled MSE 0.000133987; val RMSE 0.0006642362; lr 1e-05; 284s
network 3, training 9, epoch 1560: train scaled MSE 0.000133351; val RMSE 0.0006641861; lr 1e-05; 286s
network 3, training 9, epoch 1570: train scaled MSE 0.000133093; val RMSE 0.0006640599; lr 1e-05; 287s
network 3, training 9, epoch 1580: train scaled MSE 0.000132817; val RMSE 0.0006640455; lr 1e-05; 289s
network 3, training 9, epoch 1590: train scaled MSE 0.000132517; val RMSE 0.0006638706; lr 1e-05; 291s
network 3, training 9, epoch 1600: train scaled MSE 0.00013294; val RMSE 0.0006638656; lr 1e-05; 293s
network 3, training 9, epoch 1610: train scaled MSE 0.000131821; val RMSE 0.0006637353; lr 1e-05; 295s
network 3, training 9, epoch 1620: train scaled MSE 0.00013339; val RMSE 0.0006639034; lr 1e-05; 297s
network 3, training 9, epoch 1630: train scaled MSE 0.000131335; val RMSE 0.0006634848; lr 1e-05; 299s
network 3, training 9, epoch 1640: train scaled MSE 0.000131358; val RMSE 0.0006638955; lr 1e-05; 301s
network 3, training 9, epoch 1650: train scaled MSE 0.000130554; val RMSE 0.0006634218; lr 1e-05; 303s
network 3, training 9, epoch 1660: train scaled MSE 0.000130354; val RMSE 0.0006632667; lr 1e-05; 305s
network 3, training 9, epoch 1670: train scaled MSE 0.000129776; val RMSE 0.0006632273; lr 1e-05; 307s
network 3, training 9, epoch 1680: train scaled MSE 0.000129607; val RMSE 0.0006632062; lr 1e-05; 309s
network 3, training 9, epoch 1690: train scaled MSE 0.000129425; val RMSE 0.0006632771; lr 1e-05; 311s
network 3, training 9, epoch 1700: train scaled MSE 0.000130342; val RMSE 0.0006633913; lr 1e-05; 313s
network 3, training 9, epoch 1710: train scaled MSE 0.000130566; val RMSE 0.000663113; lr 1e-05; 315s
network 3, training 9, epoch 1720: train scaled MSE 0.000129379; val RMSE 0.0006632563; lr 1e-05; 316s
network 3, training 9, epoch 1730: train scaled MSE 0.000129209; val RMSE 0.0006629349; lr 1e-05; 318s
network 3, training 9, epoch 1740: train scaled MSE 0.000128095; val RMSE 0.0006629216; lr 1e-05; 320s
network 3, training 9, epoch 1750: train scaled MSE 0.000127678; val RMSE 0.0006627202; lr 1e-05; 322s
network 3, training 9, epoch 1760: train scaled MSE 0.000127752; val RMSE 0.0006629618; lr 1e-05; 324s
network 3, training 9, epoch 1770: train scaled MSE 0.000130872; val RMSE 0.0006628392; lr 1e-05; 326s
network 3, training 9, epoch 1780: train scaled MSE 0.000128104; val RMSE 0.0006626109; lr 1e-05; 328s
network 3, training 9, epoch 1790: train scaled MSE 0.000127952; val RMSE 0.0006625857; lr 1e-05; 329s
network 3, training 9, epoch 1800: train scaled MSE 0.000126144; val RMSE 0.0006623542; lr 1e-05; 331s
network 3, training 9, epoch 1810: train scaled MSE 0.000125955; val RMSE 0.0006622784; lr 1e-05; 333s
network 3, training 9, epoch 1820: train scaled MSE 0.000126018; val RMSE 0.0006622213; lr 1e-05; 335s
network 3, training 9, epoch 1830: train scaled MSE 0.000128369; val RMSE 0.0006622352; lr 1e-05; 337s
network 3, training 9, epoch 1840: train scaled MSE 0.000125176; val RMSE 0.0006618735; lr 1e-05; 338s
network 3, training 9, epoch 1850: train scaled MSE 0.000128096; val RMSE 0.0006625703; lr 1e-05; 340s
network 3, training 9, epoch 1860: train scaled MSE 0.000125202; val RMSE 0.00066187; lr 1e-05; 342s
network 3, training 9, epoch 1870: train scaled MSE 0.000124474; val RMSE 0.000661681; lr 1e-05; 344s
network 3, training 9, epoch 1880: train scaled MSE 0.000133291; val RMSE 0.0006617911; lr 1e-05; 346s
network 3, training 9, epoch 1890: train scaled MSE 0.000128579; val RMSE 0.0006617815; lr 1e-05; 348s
network 3, training 9, epoch 1900: train scaled MSE 0.000123767; val RMSE 0.0006613861; lr 1e-05; 349s
network 3, training 9, epoch 1910: train scaled MSE 0.000123484; val RMSE 0.0006615376; lr 1e-05; 351s
network 3, training 9, epoch 1920: train scaled MSE 0.000123149; val RMSE 0.0006613488; lr 1e-05; 353s
network 3, training 9, epoch 1930: train scaled MSE 0.000123183; val RMSE 0.0006614239; lr 1e-05; 356s
network 3, training 9, epoch 1940: train scaled MSE 0.000126278; val RMSE 0.0006613958; lr 1e-05; 358s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0007,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0007,-2.4702,"[-3.81%, -1.57%]",0.0016,0.0,0.6072
MLP,0.0008,-24.1562,"[-45.52%, -10.06%]",0.1927,12239.5496,0.3854

Network 4: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

network 4, training 8, epoch 100: train scaled MSE 0.00208244; val RMSE 0.001591723; lr 0.001; 18s
network 4, training 8, epoch 110: train scaled MSE 0.00139409; val RMSE 0.001519432; lr 0.0005; 20s
network 4, training 8, epoch 120: train scaled MSE 0.00125377; val RMSE 0.001634901; lr 0.0005; 22s
network 4, training 8, epoch 130: train scaled MSE 0.00114514; val RMSE 0.001483656; lr 0.0005; 23s
network 4, training 8, epoch 140: train scaled MSE 0.00108048; val RMSE 0.001731861; lr 0.0005; 25s
network 4, training 8, epoch 150: train scaled MSE 0.000907438; val RMSE 0.001463764; lr 0.00025; 27s
network 4, training 8, epoch 160: train scaled MSE 0.000880332; val RMSE 0.001458764; lr 0.00025; 29s
network 4, training 8, epoch 170: train scaled MSE 0.000841844; val RMSE 0.001595354; lr 0.00025; 31s
network 4, training 8, epoch 180: train scaled MSE 0.00079894; val RMSE 0.001449234; lr 0.00025; 33s
network 4, training 8, epoch 190: train scaled MSE 0.000781628; val RMSE 0.001472246; lr 0.00025; 35s
network 4, training 8, epoch 200: train scaled MSE 0.000993909; val RMSE 0.001449026; lr 0.00025; 37s
network 4, training 8, epoch 210: train scaled MSE 0.000697912; val RMSE 0.001453306; lr 0.00025; 39s
network 4, training 8, epoch 220: train scaled MSE 0.000670024; val RMSE 0.001444157; lr 0.00025; 41s
network 4, training 8, epoch 230: train scaled MSE 0.000641484; val RMSE 0.001429367; lr 0.00025; 42s
network 4, training 8, epoch 240: train scaled MSE 0.000632181; val RMSE 0.001419736; lr 0.00025; 44s
network 4, training 8, epoch 250: train scaled MSE 0.00059634; val RMSE 0.001415953; lr 0.00025; 46s
network 4, training 8, epoch 260: train scaled MSE 0.000584199; val RMSE 0.001527735; lr 0.00025; 48s
network 4, training 8, epoch 270: train scaled MSE 0.000884537; val RMSE 0.00141991; lr 0.00025; 49s
network 4, training 8, epoch 280: train scaled MSE 0.000609774; val RMSE 0.001406683; lr 0.00025; 51s
network 4, training 8, epoch 290: train scaled MSE 0.000524803; val RMSE 0.001417552; lr 0.00025; 53s
network 4, training 8, epoch 300: train scaled MSE 0.000471355; val RMSE 0.001407566; lr 0.000125; 54s
network 4, training 8, epoch 310: train scaled MSE 0.00045651; val RMSE 0.001400111; lr 0.000125; 56s
network 4, training 8, epoch 320: train scaled MSE 0.000455679; val RMSE 0.001393549; lr 6.25e-05; 58s
network 4, training 8, epoch 330: train scaled MSE 0.000429205; val RMSE 0.001389603; lr 6.25e-05; 59s
network 4, training 8, epoch 340: train scaled MSE 0.000426354; val RMSE 0.001389247; lr 6.25e-05; 61s
network 4, training 8, epoch 350: train scaled MSE 0.000422551; val RMSE 0.001388675; lr 6.25e-05; 63s
network 4, training 8, epoch 360: train scaled MSE 0.000441689; val RMSE 0.001387755; lr 6.25e-05; 64s
network 4, training 8, epoch 370: train scaled MSE 0.000410657; val RMSE 0.001387051; lr 6.25e-05; 66s
network 4, training 8, epoch 380: train scaled MSE 0.000406139; val RMSE 0.001385458; lr 6.25e-05; 68s
network 4, training 8, epoch 390: train scaled MSE 0.000401725; val RMSE 0.001384513; lr 6.25e-05; 70s
network 4, training 8, epoch 400: train scaled MSE 0.000397853; val RMSE 0.001383019; lr 6.25e-05; 71s
network 4, training 8, epoch 410: train scaled MSE 0.000389413; val RMSE 0.001381814; lr 6.25e-05; 73s
network 4, training 8, epoch 420: train scaled MSE 0.000404989; val RMSE 0.00138207; lr 6.25e-05; 75s
network 4, training 8, epoch 430: train scaled MSE 0.000721874; val RMSE 0.001383207; lr 6.25e-05; 76s
network 4, training 8, epoch 440: train scaled MSE 0.000375753; val RMSE 0.001379123; lr 6.25e-05; 78s
network 4, training 8, epoch 450: train scaled MSE 0.00037328; val RMSE 0.001378173; lr 6.25e-05; 80s
network 4, training 8, epoch 460: train scaled MSE 0.000368626; val RMSE 0.001388274; lr 6.25e-05; 81s
network 4, training 8, epoch 470: train scaled MSE 0.000363919; val RMSE 0.001376004; lr 6.25e-05; 83s
network 4, training 8, epoch 480: train scaled MSE 0.000360437; val RMSE 0.001374223; lr 6.25e-05; 85s
network 4, training 8, epoch 490: train scaled MSE 0.000357181; val RMSE 0.001373423; lr 6.25e-05; 86s
network 4, training 8, epoch 500: train scaled MSE 0.000354297; val RMSE 0.00137262; lr 6.25e-05; 88s
network 4, training 8, epoch 510: train scaled MSE 0.000351259; val RMSE 0.001372375; lr 6.25e-05; 89s
network 4, training 8, epoch 520: train scaled MSE 0.000346574; val RMSE 0.001383589; lr 6.25e-05; 91s
network 4, training 8, epoch 530: train scaled MSE 0.000338738; val RMSE 0.001371166; lr 6.25e-05; 93s
network 4, training 8, epoch 540: train scaled MSE 0.000335225; val RMSE 0.001378218; lr 6.25e-05; 94s
network 4, training 8, epoch 550: train scaled MSE 0.000331123; val RMSE 0.001368446; lr 3.125e-05; 96s
network 4, training 8, epoch 560: train scaled MSE 0.000324949; val RMSE 0.001371582; lr 3.125e-05; 98s
network 4, training 8, epoch 570: train scaled MSE 0.000322927; val RMSE 0.001366759; lr 3.125e-05; 99s
network 4, training 8, epoch 580: train scaled MSE 0.000346751; val RMSE 0.001368343; lr 3.125e-05; 101s
network 4, training 8, epoch 590: train scaled MSE 0.000369686; val RMSE 0.001368819; lr 3.125e-05; 103s
network 4, training 8, epoch 600: train scaled MSE 0.00033508; val RMSE 0.001365751; lr 1.5625e-05; 104s
network 4, training 8, epoch 610: train scaled MSE 0.000313395; val RMSE 0.001364831; lr 1.5625e-05; 106s
network 4, training 8, epoch 620: train scaled MSE 0.000320888; val RMSE 0.001364891; lr 1.5625e-05; 107s
network 4, training 8, epoch 630: train scaled MSE 0.000310197; val RMSE 0.001364144; lr 1e-05; 109s
network 4, training 8, epoch 640: train scaled MSE 0.000311264; val RMSE 0.001364254; lr 1e-05; 111s
network 4, training 8, epoch 650: train scaled MSE 0.000330291; val RMSE 0.001364085; lr 1e-05; 113s
network 4, training 8, epoch 660: train scaled MSE 0.000310058; val RMSE 0.001363778; lr 1e-05; 114s
network 4, training 8, epoch 670: train scaled MSE 0.00030679; val RMSE 0.001363497; lr 1e-05; 116s
network 4, training 8, epoch 680: train scaled MSE 0.000307136; val RMSE 0.001363386; lr 1e-05; 118s
network 4, training 8, epoch 690: train scaled MSE 0.000306555; val RMSE 0.001363368; lr 1e-05; 120s
network 4, training 8, epoch 700: train scaled MSE 0.00030577; val RMSE 0.00136321; lr 1e-05; 122s
network 4, training 8, epoch 710: train scaled MSE 0.00031824; val RMSE 0.001363492; lr 1e-05; 123s
network 4, training 8, epoch 720: train scaled MSE 0.000304565; val RMSE 0.001362697; lr 1e-05; 125s
network 4, training 8, epoch 730: train scaled MSE 0.000303868; val RMSE 0.001362583; lr 1e-05; 126s
network 4, training 8, epoch 740: train scaled MSE 0.00030319; val RMSE 0.001362536; lr 1e-05; 128s
network 4, training 8, epoch 750: train scaled MSE 0.000302781; val RMSE 0.001362376; lr 1e-05; 129s
network 4, training 8, epoch 760: train scaled MSE 0.000312989; val RMSE 0.001362117; lr 1e-05; 131s
network 4, training 8, epoch 770: train scaled MSE 0.000302857; val RMSE 0.001362288; lr 1e-05; 133s
network 4, training 8, epoch 780: train scaled MSE 0.000300888; val RMSE 0.001361668; lr 1e-05; 134s
network 4, training 8, epoch 790: train scaled MSE 0.000300255; val RMSE 0.001361423; lr 1e-05; 136s
network 4, training 8, epoch 800: train scaled MSE 0.000299699; val RMSE 0.001361292; lr 1e-05; 138s
network 4, training 8, epoch 810: train scaled MSE 0.000299104; val RMSE 0.001362068; lr 1e-05; 140s
network 4, training 8, epoch 820: train scaled MSE 0.000298304; val RMSE 0.001360817; lr 1e-05; 141s
network 4, training 8, epoch 830: train scaled MSE 0.000299414; val RMSE 0.001360925; lr 1e-05; 143s
network 4, training 8, epoch 840: train scaled MSE 0.000296961; val RMSE 0.00136042; lr 1e-05; 144s
network 4, training 8, epoch 850: train scaled MSE 0.000300719; val RMSE 0.001360538; lr 1e-05; 146s
network 4, training 8, epoch 860: train scaled MSE 0.000302895; val RMSE 0.00136049; lr 1e-05; 148s
network 4, training 8, epoch 870: train scaled MSE 0.000294913; val RMSE 0.001359826; lr 1e-05; 149s
network 4, training 8, epoch 880: train scaled MSE 0.000296332; val RMSE 0.001360066; lr 1e-05; 151s
network 4, training 8, epoch 890: train scaled MSE 0.000310305; val RMSE 0.00136113; lr 1e-05; 153s
network 4, training 8, epoch 900: train scaled MSE 0.000293079; val RMSE 0.001359448; lr 1e-05; 155s
network 4, training 8, epoch 910: train scaled MSE 0.000292584; val RMSE 0.001359252; lr 1e-05; 156s
network 4, training 8, epoch 920: train scaled MSE 0.000296182; val RMSE 0.001359168; lr 1e-05; 158s
network 4, training 8, epoch 930: train scaled MSE 0.000292534; val RMSE 0.001359063; lr 1e-05; 160s
network 4, training 8, epoch 940: train scaled MSE 0.000291751; val RMSE 0.001358839; lr 1e-05; 161s
network 4, training 8, epoch 950: train scaled MSE 0.000290991; val RMSE 0.001359391; lr 1e-05; 163s
network 4, training 8, epoch 960: train scaled MSE 0.000290492; val RMSE 0.001358841; lr 1e-05; 164s
network 4, training 8, epoch 970: train scaled MSE 0.000292609; val RMSE 0.001358681; lr 1e-05; 166s
network 4, training 8, epoch 980: train scaled MSE 0.000292032; val RMSE 0.001358576; lr 1e-05; 167s
network 4, training 8, epoch 990: train scaled MSE 0.000288722; val RMSE 0.001358199; lr 1e-05; 169s
network 4, training 8, epoch 1000: train scaled MSE 0.000292899; val RMSE 0.001358252; lr 1e-05; 171s
network 4, training 8, epoch 1010: train scaled MSE 0.00028744; val RMSE 0.001357981; lr 1e-05; 172s
network 4, training 8, epoch 1020: train scaled MSE 0.00029927; val RMSE 0.001358414; lr 1e-05; 174s
network 4, training 8, epoch 1030: train scaled MSE 0.000287722; val RMSE 0.001357566; lr 1e-05; 175s
network 4, training 8, epoch 1040: train scaled MSE 0.000293088; val RMSE 0.001357804; lr 1e-05; 177s
network 4, training 8, epoch 1050: train scaled MSE 0.000285729; val RMSE 0.001357319; lr 1e-05; 179s
network 4, training 8, epoch 1060: train scaled MSE 0.000285716; val RMSE 0.00135719; lr 1e-05; 180s
network 4, training 8, epoch 1070: train scaled MSE 0.000290959; val RMSE 0.001357356; lr 1e-05; 182s
network 4, training 8, epoch 1080: train scaled MSE 0.000285135; val RMSE 0.001356976; lr 1e-05; 184s
network 4, training 8, epoch 1090: train scaled MSE 0.000283931; val RMSE 0.001356778; lr 1e-05; 185s
network 4, training 8, epoch 1100: train scaled MSE 0.000283401; val RMSE 0.001356796; lr 1e-05; 187s
network 4, training 8, epoch 1110: train scaled MSE 0.000282824; val RMSE 0.001356784; lr 1e-05; 189s
network 4, training 8, epoch 1120: train scaled MSE 0.000299401; val RMSE 0.001356944; lr 1e-05; 191s
network 4, training 8, epoch 1130: train scaled MSE 0.000281261; val RMSE 0.001355972; lr 1e-05; 192s
network 4, training 8, epoch 1140: train scaled MSE 0.00028096; val RMSE 0.001356016; lr 1e-05; 194s
network 4, training 8, epoch 1150: train scaled MSE 0.000280972; val RMSE 0.001355598; lr 1e-05; 196s
network 4, training 8, epoch 1160: train scaled MSE 0.000281698; val RMSE 0.001355921; lr 1e-05; 197s
network 4, training 8, epoch 1170: train scaled MSE 0.00027964; val RMSE 0.001355655; lr 1e-05; 199s
network 4, training 8, epoch 1180: train scaled MSE 0.000283259; val RMSE 0.001355618; lr 1e-05; 200s
network 4, training 8, epoch 1190: train scaled MSE 0.000280213; val RMSE 0.00135519; lr 1e-05; 202s
network 4, training 8, epoch 1200: train scaled MSE 0.00027849; val RMSE 0.001355129; lr 1e-05; 204s
network 4, training 8, epoch 1210: train scaled MSE 0.000279323; val RMSE 0.001355226; lr 1e-05; 205s
network 4, training 8, epoch 1220: train scaled MSE 0.000277439; val RMSE 0.001354939; lr 1e-05; 207s
network 4, training 8, epoch 1230: train scaled MSE 0.000276905; val RMSE 0.00135463; lr 1e-05; 209s
network 4, training 8, epoch 1240: train scaled MSE 0.00027827; val RMSE 0.001354802; lr 1e-05; 210s
network 4, training 8, epoch 1250: train scaled MSE 0.000275772; val RMSE 0.001354472; lr 1e-05; 212s
network 4, training 8, epoch 1260: train scaled MSE 0.000275694; val RMSE 0.001354422; lr 1e-05; 214s
network 4, training 8, epoch 1270: train scaled MSE 0.000275139; val RMSE 0.001354074; lr 1e-05; 216s
network 4, training 8, epoch 1280: train scaled MSE 0.000274546; val RMSE 0.001354095; lr 1e-05; 217s
network 4, training 8, epoch 1290: train scaled MSE 0.000275096; val RMSE 0.00135413; lr 1e-05; 219s
network 4, training 8, epoch 1300: train scaled MSE 0.000274604; val RMSE 0.001354133; lr 1e-05; 221s
network 4, training 8, epoch 1310: train scaled MSE 0.000273219; val RMSE 0.001353683; lr 1e-05; 223s
network 4, training 8, epoch 1320: train scaled MSE 0.000273113; val RMSE 0.001353543; lr 1e-05; 224s
network 4, training 8, epoch 1330: train scaled MSE 0.000272937; val RMSE 0.001353447; lr 1e-05; 226s
network 4, training 8, epoch 1340: train scaled MSE 0.000272632; val RMSE 0.001353625; lr 1e-05; 228s
network 4, training 8, epoch 1350: train scaled MSE 0.000270886; val RMSE 0.001353128; lr 1e-05; 230s
network 4, training 8, epoch 1360: train scaled MSE 0.000270401; val RMSE 0.001353115; lr 1e-05; 231s
network 4, training 8, epoch 1370: train scaled MSE 0.000270022; val RMSE 0.001352853; lr 1e-05; 233s
network 4, training 8, epoch 1380: train scaled MSE 0.000269851; val RMSE 0.001352698; lr 1e-05; 235s
network 4, training 8, epoch 1390: train scaled MSE 0.000269221; val RMSE 0.001352613; lr 1e-05; 237s
network 4, training 8, epoch 1400: train scaled MSE 0.000268611; val RMSE 0.001352292; lr 1e-05; 238s
network 4, training 8, epoch 1410: train scaled MSE 0.000268142; val RMSE 0.001352366; lr 1e-05; 240s
network 4, training 8, epoch 1420: train scaled MSE 0.000270742; val RMSE 0.001352013; lr 1e-05; 242s
network 4, training 8, epoch 1430: train scaled MSE 0.000267995; val RMSE 0.00135201; lr 1e-05; 244s
network 4, training 8, epoch 1440: train scaled MSE 0.000272082; val RMSE 0.001351788; lr 1e-05; 246s
network 4, training 8, epoch 1450: train scaled MSE 0.000266116; val RMSE 0.001352542; lr 1e-05; 247s
network 4, training 8, epoch 1460: train scaled MSE 0.000266043; val RMSE 0.001351964; lr 1e-05; 249s
network 4, training 8, epoch 1470: train scaled MSE 0.000265377; val RMSE 0.001351578; lr 1e-05; 251s
network 4, training 8, epoch 1480: train scaled MSE 0.000264937; val RMSE 0.001352017; lr 1e-05; 252s
network 4, training 8, epoch 1490: train scaled MSE 0.000264552; val RMSE 0.001351435; lr 1e-05; 254s
network 4, training 8, epoch 1500: train scaled MSE 0.00026544; val RMSE 0.001351941; lr 1e-05; 256s
network 4, training 8, epoch 1510: train scaled MSE 0.000263883; val RMSE 0.001350993; lr 1e-05; 258s
network 4, training 8, epoch 1520: train scaled MSE 0.000263991; val RMSE 0.001350848; lr 1e-05; 259s
network 4, training 8, epoch 1530: train scaled MSE 0.000263077; val RMSE 0.001350767; lr 1e-05; 261s
network 4, training 8, epoch 1540: train scaled MSE 0.000262794; val RMSE 0.001351361; lr 1e-05; 263s
network 4, training 8, epoch 1550: train scaled MSE 0.000262603; val RMSE 0.00135067; lr 1e-05; 264s
network 4, training 8, epoch 1560: train scaled MSE 0.000261773; val RMSE 0.001350337; lr 1e-05; 266s
network 4, training 8, epoch 1570: train scaled MSE 0.000260775; val RMSE 0.001349878; lr 1e-05; 268s
network 4, training 8, epoch 1580: train scaled MSE 0.000268031; val RMSE 0.0013511; lr 1e-05; 270s
network 4, training 8, epoch 1590: train scaled MSE 0.000261678; val RMSE 0.001349993; lr 1e-05; 271s
network 4, training 8, epoch 1600: train scaled MSE 0.000259424; val RMSE 0.001349786; lr 1e-05; 273s
network 4, training 8, epoch 1610: train scaled MSE 0.000259518; val RMSE 0.001349597; lr 1e-05; 275s
network 4, training 8, epoch 1620: train scaled MSE 0.000258982; val RMSE 0.001349528; lr 1e-05; 277s
network 4, training 8, epoch 1630: train scaled MSE 0.000258924; val RMSE 0.001349474; lr 1e-05; 278s
network 4, training 8, epoch 1640: train scaled MSE 0.000259564; val RMSE 0.001349324; lr 1e-05; 280s
network 4, training 8, epoch 1650: train scaled MSE 0.000257525; val RMSE 0.001349456; lr 1e-05; 282s
network 4, training 8, epoch 1660: train scaled MSE 0.000257291; val RMSE 0.001349003; lr 1e-05; 284s
network 4, training 8, epoch 1670: train scaled MSE 0.000261581; val RMSE 0.001349403; lr 1e-05; 285s
network 4, training 8, epoch 1680: train scaled MSE 0.000256269; val RMSE 0.00134875; lr 1e-05; 287s
network 4, training 8, epoch 1690: train scaled MSE 0.000256567; val RMSE 0.001348672; lr 1e-05; 288s
network 4, training 8, epoch 1700: train scaled MSE 0.000255521; val RMSE 0.001349261; lr 1e-05; 290s
network 4, training 8, epoch 1710: train scaled MSE 0.000263136; val RMSE 0.001348809; lr 1e-05; 291s
network 4, training 8, epoch 1720: train scaled MSE 0.000254565; val RMSE 0.001348381; lr 1e-05; 293s
network 4, training 8, epoch 1730: train scaled MSE 0.000254394; val RMSE 0.001348388; lr 1e-05; 294s
network 4, training 8, epoch 1740: train scaled MSE 0.000253598; val RMSE 0.001348099; lr 1e-05; 296s
network 4, training 8, epoch 1750: train scaled MSE 0.000253268; val RMSE 0.001347742; lr 1e-05; 298s
network 4, training 8, epoch 1760: train scaled MSE 0.000255101; val RMSE 0.001347915; lr 1e-05; 299s
network 4, training 8, epoch 1770: train scaled MSE 0.000252676; val RMSE 0.001347727; lr 1e-05; 301s
network 4, training 8, epoch 1780: train scaled MSE 0.000251973; val RMSE 0.001347266; lr 1e-05; 303s
network 4, training 8, epoch 1790: train scaled MSE 0.000252416; val RMSE 0.00134747; lr 1e-05; 305s
network 4, training 8, epoch 1800: train scaled MSE 0.000261287; val RMSE 0.001347862; lr 1e-05; 307s
network 4, training 8, epoch 1810: train scaled MSE 0.00025146; val RMSE 0.001347; lr 1e-05; 308s
network 4, training 8, epoch 1820: train scaled MSE 0.000250115; val RMSE 0.00134701; lr 1e-05; 310s
network 4, training 8, epoch 1830: train scaled MSE 0.000255093; val RMSE 0.001346989; lr 1e-05; 312s
network 4, training 8, epoch 1840: train scaled MSE 0.000249327; val RMSE 0.001346657; lr 1e-05; 314s
network 4, training 8, epoch 1850: train scaled MSE 0.000249453; val RMSE 0.0013471; lr 1e-05; 316s
network 4, training 8, epoch 1860: train scaled MSE 0.000260628; val RMSE 0.001346815; lr 1e-05; 317s
network 4, training 8, epoch 1870: train scaled MSE 0.000248428; val RMSE 0.001346341; lr 1e-05; 319s
network 4, training 8, epoch 1880: train scaled MSE 0.000248058; val RMSE 0.001346447; lr 1e-05; 321s
network 4, training 8, epoch 1890: train scaled MSE 0.000247433; val RMSE 0.001346344; lr 1e-05; 323s
network 4, training 8, epoch 1900: train scaled MSE 0.000246666; val RMSE 0.001346003; lr 1e-05; 324s
network 4, training 8, epoch 1910: train scaled MSE 0.00024661; val RMSE 0.001345636; lr 1e-05; 326s
network 4, training 8, epoch 1920: train scaled MSE 0.000246157; val RMSE 0.00134574; lr 1e-05; 328s
network 4, training 8, epoch 1930: train scaled MSE 0.000268156; val RMSE 0.001345996; lr 1e-05; 330s
network 4, training 8, epoch 1940: train scaled MSE 0.000245029; val RMSE 0.001345786; lr 1e-05; 331s
network 4, training 8, epoch 1950: train scaled MSE 0.000245035; val RMSE 0.001345599; lr 1e-05; 333s
network 4, training 8, epoch 1960: train scaled MSE 0.000244248; val RMSE 0.001346163; lr 1e-05; 334s
network 4, training 8, epoch 1970: train scaled MSE 0.000247752; val RMSE 0.001345631; lr 1e-05; 336s
network 4, training 8, epoch 1980: train scaled MSE 0.000244521; val RMSE 0.001345072; lr 1e-05; 337s
network 4, training 8, epoch 1990: train scaled MSE 0.00024405; val RMSE 0.001345035; lr 1e-05; 339s
network 4, training 8, epoch 2000: train scaled MSE 0.000243862; val RMSE 0.001345174; lr 1e-05; 340s
network 4, training 8, epoch 2010: train scaled MSE 0.000242518; val RMSE 0.001344785; lr 1e-05; 342s
network 4, training 8, epoch 2020: train scaled MSE 0.000242655; val RMSE 0.001344546; lr 1e-05; 344s
network 4, training 8, epoch 2030: train scaled MSE 0.000241882; val RMSE 0.001344352; lr 1e-05; 346s
network 4, training 8, epoch 2040: train scaled MSE 0.000241571; val RMSE 0.001344377; lr 1e-05; 348s
network 4, training 8, epoch 2050: train scaled MSE 0.000241808; val RMSE 0.001344205; lr 1e-05; 350s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0013,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0013,-2.0331,"[-3.68%, -0.49%]",0.0326,0.0,0.3205
MLP,0.0012,6.7018,"[-12.19%, 17.40%]",0.3865,1084.9726,0.2737

network 4, training 9, epoch 1: train scaled MSE 0.839514; val RMSE 0.01508441; lr 0.001; 0s
network 4, training 9, epoch 10: train scaled MSE 0.0174652; val RMSE 0.002328232; lr 0.001; 2s
network 4, training 9, epoch 20: train scaled MSE 0.00651677; val RMSE 0.001565979; lr 0.001; 4s
network 4, training 9, epoch 30: train scaled MSE 0.00667854; val RMSE 0.001514685; lr 0.001; 5s
network 4, training 9, epoch 40: train scaled MSE 0.00478276; val RMSE 0.001443758; lr 0.001; 7s
network 4, training 9, epoch 50: train scaled MSE 0.00331807; val RMSE 0.001665369; lr 0.001; 9s
network 4, training 9, epoch 60: train scaled MSE 0.00304007; val RMSE 0.001316184; lr 0.001; 11s
network 4, training 9, epoch 70: train scaled MSE 0.00240468; val RMSE 0.001276895; lr 0.001; 13s
network 4, training 9, epoch 80: train scaled MSE 0.00206804; val RMSE 0.001269491; lr 0.001; 14s
network 4, training 9, epoch 90: train scaled MSE 0.00187516; val RMSE 0.00139436; lr 0.001; 16s
network 4, training 9, epoch 100: train scaled MSE 0.00142203; val RMSE 0.00119192; lr 0.0005; 18s
network 4, training 9, epoch 110: train scaled MSE 0.00127284; val RMSE 0.00115831; lr 0.0005; 20s
network 4, training 9, epoch 120: train scaled MSE 0.00118632; val RMSE 0.001145268; lr 0.0005; 21s
network 4, training 9, epoch 130: train scaled MSE 0.00114612; val RMSE 0.00113677; lr 0.0005; 23s
network 4, training 9, epoch 140: train scaled MSE 0.00102023; val RMSE 0.001134511; lr 0.0005; 25s
network 4, training 9, epoch 150: train scaled MSE 0.000964833; val RMSE 0.001192183; lr 0.0005; 27s
network 4, training 9, epoch 160: train scaled MSE 0.000822744; val RMSE 0.001114455; lr 0.00025; 29s
network 4, training 9, epoch 170: train scaled MSE 0.000792744; val RMSE 0.001112515; lr 0.00025; 31s
network 4, training 9, epoch 180: train scaled MSE 0.00079679; val RMSE 0.001112536; lr 0.00025; 33s
network 4, training 9, epoch 190: train scaled MSE 0.000751124; val RMSE 0.001107707; lr 0.00025; 35s
network 4, training 9, epoch 200: train scaled MSE 0.000717867; val RMSE 0.001102617; lr 0.00025; 37s
network 4, training 9, epoch 210: train scaled MSE 0.000726996; val RMSE 0.00110576; lr 0.00025; 39s
network 4, training 9, epoch 220: train scaled MSE 0.000691185; val RMSE 0.001240214; lr 0.00025; 41s
network 4, training 9, epoch 230: train scaled MSE 0.000626228; val RMSE 0.001155824; lr 0.00025; 42s
network 4, training 9, epoch 240: train scaled MSE 0.000584131; val RMSE 0.001090778; lr 0.000125; 44s
network 4, training 9, epoch 250: train scaled MSE 0.000571791; val RMSE 0.00111571; lr 0.000125; 46s
network 4, training 9, epoch 260: train scaled MSE 0.000559407; val RMSE 0.001102266; lr 0.000125; 48s
network 4, training 9, epoch 270: train scaled MSE 0.000562442; val RMSE 0.001106408; lr 0.000125; 50s
network 4, training 9, epoch 280: train scaled MSE 0.000525528; val RMSE 0.001083333; lr 6.25e-05; 52s
network 4, training 9, epoch 290: train scaled MSE 0.000521795; val RMSE 0.001082127; lr 6.25e-05; 54s
network 4, training 9, epoch 300: train scaled MSE 0.000581772; val RMSE 0.001098967; lr 6.25e-05; 56s
network 4, training 9, epoch 310: train scaled MSE 0.000501126; val RMSE 0.001081961; lr 3.125e-05; 57s
network 4, training 9, epoch 320: train scaled MSE 0.00049886; val RMSE 0.001080783; lr 3.125e-05; 59s
network 4, training 9, epoch 330: train scaled MSE 0.000509579; val RMSE 0.001081545; lr 3.125e-05; 61s
network 4, training 9, epoch 340: train scaled MSE 0.000493643; val RMSE 0.001079501; lr 3.125e-05; 63s
network 4, training 9, epoch 350: train scaled MSE 0.000488857; val RMSE 0.001078535; lr 3.125e-05; 65s
network 4, training 9, epoch 360: train scaled MSE 0.000492456; val RMSE 0.001080656; lr 3.125e-05; 67s
network 4, training 9, epoch 370: train scaled MSE 0.000482271; val RMSE 0.001078257; lr 3.125e-05; 68s
network 4, training 9, epoch 380: train scaled MSE 0.000478194; val RMSE 0.001076306; lr 3.125e-05; 70s
network 4, training 9, epoch 390: train scaled MSE 0.000488562; val RMSE 0.001076853; lr 3.125e-05; 72s
network 4, training 9, epoch 400: train scaled MSE 0.000473744; val RMSE 0.001075772; lr 3.125e-05; 74s
network 4, training 9, epoch 410: train scaled MSE 0.000468853; val RMSE 0.001079175; lr 3.125e-05; 76s
network 4, training 9, epoch 420: train scaled MSE 0.000473012; val RMSE 0.001074793; lr 3.125e-05; 78s
network 4, training 9, epoch 430: train scaled MSE 0.000478664; val RMSE 0.001075046; lr 3.125e-05; 79s
network 4, training 9, epoch 440: train scaled MSE 0.000460302; val RMSE 0.001073684; lr 3.125e-05; 81s
network 4, training 9, epoch 450: train scaled MSE 0.000452951; val RMSE 0.001072353; lr 1.5625e-05; 83s
network 4, training 9, epoch 460: train scaled MSE 0.000451917; val RMSE 0.001072312; lr 1.5625e-05; 85s
network 4, training 9, epoch 470: train scaled MSE 0.000451581; val RMSE 0.001073178; lr 1.5625e-05; 87s
network 4, training 9, epoch 480: train scaled MSE 0.000453507; val RMSE 0.001072279; lr 1e-05; 89s
network 4, training 9, epoch 490: train scaled MSE 0.000446297; val RMSE 0.001071789; lr 1e-05; 91s
network 4, training 9, epoch 500: train scaled MSE 0.000446468; val RMSE 0.001072756; lr 1e-05; 92s
network 4, training 9, epoch 510: train scaled MSE 0.000444422; val RMSE 0.001071792; lr 1e-05; 94s
network 4, training 9, epoch 520: train scaled MSE 0.000442948; val RMSE 0.001071256; lr 1e-05; 96s
network 4, training 9, epoch 530: train scaled MSE 0.000442881; val RMSE 0.001071201; lr 1e-05; 98s
network 4, training 9, epoch 540: train scaled MSE 0.000441683; val RMSE 0.001071065; lr 1e-05; 100s
network 4, training 9, epoch 550: train scaled MSE 0.000440589; val RMSE 0.001070814; lr 1e-05; 102s
network 4, training 9, epoch 560: train scaled MSE 0.00043988; val RMSE 0.001070551; lr 1e-05; 104s
network 4, training 9, epoch 570: train scaled MSE 0.000437687; val RMSE 0.001070267; lr 1e-05; 106s
network 4, training 9, epoch 580: train scaled MSE 0.000436832; val RMSE 0.001070213; lr 1e-05; 107s
network 4, training 9, epoch 590: train scaled MSE 0.000435714; val RMSE 0.001069941; lr 1e-05; 109s
network 4, training 9, epoch 600: train scaled MSE 0.000434878; val RMSE 0.001070075; lr 1e-05; 111s
network 4, training 9, epoch 610: train scaled MSE 0.000437139; val RMSE 0.001071469; lr 1e-05; 113s
network 4, training 9, epoch 620: train scaled MSE 0.000432476; val RMSE 0.00106983; lr 1e-05; 115s
network 4, training 9, epoch 630: train scaled MSE 0.000431151; val RMSE 0.001069972; lr 1e-05; 117s
network 4, training 9, epoch 640: train scaled MSE 0.000429898; val RMSE 0.001069309; lr 1e-05; 118s
network 4, training 9, epoch 650: train scaled MSE 0.000429203; val RMSE 0.001069088; lr 1e-05; 120s
Standard Linear Baseline Validation RMSE: 0.001084581

Network seed 4, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0014,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0014,-1.0539,"[-2.55%, -0.25%]",0.0260,0.0,0.4511
MLP,0.0014,7.7159,"[-8.31%, 16.10%]",0.3726,1333.6068,0.2735

Network 5: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   20.1s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   20.2s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   20.3s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   20.4s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   20.5s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   20.7s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   20.8s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   21.0s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   21.1s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   21.4s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   21.6s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   21.7s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   21.9s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   22.0s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   22.2s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   22.5s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   22.6s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   22.9s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   23.1s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   23.3s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   23.6s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   23.8s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   24.1s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   24.3s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   24.5s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   24.8s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   25.1s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   25.4s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   26.0s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   26.3s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   26.6s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   26.9s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   27.3s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   27.6s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   28.3s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   28.7s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   29.1s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   29.4s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   29.7s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   30.2s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   31.0s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   31.4s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   32.0s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   32.4s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   33.0s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   33.4s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   33.9s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   34.3s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   34.8s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   35.3s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   35.8s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   36.3s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   36.8s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   37.2s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   37.7s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   38.3s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   38.8s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   39.3s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   39.8s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   40.4s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   40.9s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   41.5s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   42.1s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   42.6s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   43.2s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   43.8s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   44.4s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   45.0s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   45.7s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   46.2s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   46.9s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   47.6s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   48.2s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   48.9s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   49.5s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   50.2s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   50.9s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   51.5s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   52.2s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   52.9s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   53.6s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:   54.3s
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:   55.0s
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:   55.7s
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:   56.4s
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:   57.1s
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:   57.8s
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:   58.6s
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:   59.3s
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.4min finished

network 5, training 0, epoch 1: train scaled MSE 0.791442; val RMSE 0.02393015; lr 0.001; 0s
network 5, training 0, epoch 10: train scaled MSE 0.023229; val RMSE 0.005121626; lr 0.001; 2s
network 5, training 0, epoch 20: train scaled MSE 0.010589; val RMSE 0.003405401; lr 0.001; 4s
network 5, training 0, epoch 30: train scaled MSE 0.0164581; val RMSE 0.003296485; lr 0.001; 6s
network 5, training 0, epoch 40: train scaled MSE 0.00530184; val RMSE 0.002852132; lr 0.001; 8s
network 5, training 0, epoch 50: train scaled MSE 0.00396201; val RMSE 0.002715494; lr 0.001; 11s
network 5, training 0, epoch 60: train scaled MSE 0.00307381; val RMSE 0.002538687; lr 0.001; 13s
network 5, training 0, epoch 70: train scaled MSE 0.00233538; val RMSE 0.002679513; lr 0.001; 15s
network 5, training 0, epoch 80: train scaled MSE 0.00171517; val RMSE 0.002430847; lr 0.0005; 17s
network 5, training 0, epoch 90: train scaled MSE 0.00149392; val RMSE 0.00242063; lr 0.0005; 19s
network 5, training 0, epoch 100: train scaled MSE 0.00130547; val RMSE 0.002375212; lr 0.0005; 21s
network 5, training 0, epoch 110: train scaled MSE 0.00168236; val RMSE 0.002380717; lr 0.0005; 23s
network 5, training 0, epoch 120: train scaled MSE 0.0015204; val RMSE 0.00237746; lr 0.0005; 26s
network 5, training 0, epoch 130: train scaled MSE 0.000937888; val RMSE 0.002376524; lr 0.0005; 28s
network 5, training 0, epoch 140: train scaled MSE 0.00104182; val RMSE 0.002360616; lr 0.0005; 30s
network 5, training 0, epoch 150: train scaled MSE 0.000864727; val RMSE 0.002305985; lr 0.00025; 32s
network 5, training 0, epoch 160: train scaled MSE 0.0007134; val RMSE 0.002287088; lr 0.00025; 34s
network 5, training 0, epoch 170: train scaled MSE 0.000801738; val RMSE 0.002282058; lr 0.00025; 37s
network 5, training 0, epoch 180: train scaled MSE 0.000594079; val RMSE 0.002273515; lr 0.000125; 39s
network 5, training 0, epoch 190: train scaled MSE 0.000569882; val RMSE 0.002266826; lr 0.000125; 41s
network 5, training 0, epoch 200: train scaled MSE 0.000556439; val RMSE 0.002285285; lr 0.000125; 43s
network 5, training 0, epoch 210: train scaled MSE 0.000535971; val RMSE 0.002260363; lr 0.000125; 45s
network 5, training 0, epoch 220: train scaled MSE 0.000524949; val RMSE 0.002263406; lr 0.000125; 47s
network 5, training 0, epoch 230: train scaled MSE 0.000512377; val RMSE 0.00225557; lr 0.000125; 49s
network 5, training 0, epoch 240: train scaled MSE 0.000950181; val RMSE 0.002275232; lr 0.000125; 51s
network 5, training 0, epoch 250: train scaled MSE 0.000508909; val RMSE 0.002248613; lr 0.000125; 53s
network 5, training 0, epoch 260: train scaled MSE 0.000465221; val RMSE 0.00225703; lr 0.000125; 56s
network 5, training 0, epoch 270: train scaled MSE 0.000447582; val RMSE 0.002242535; lr 0.000125; 58s
network 5, training 0, epoch 280: train scaled MSE 0.000433843; val RMSE 0.002239083; lr 0.000125; 60s
network 5, training 0, epoch 290: train scaled MSE 0.000415037; val RMSE 0.002234461; lr 0.000125; 62s
network 5, training 0, epoch 300: train scaled MSE 0.000399301; val RMSE 0.002233787; lr 0.000125; 64s
network 5, training 0, epoch 310: train scaled MSE 0.000418918; val RMSE 0.002231458; lr 6.25e-05; 66s
network 5, training 0, epoch 320: train scaled MSE 0.00040049; val RMSE 0.002229066; lr 6.25e-05; 69s
network 5, training 0, epoch 330: train scaled MSE 0.00036413; val RMSE 0.002224575; lr 6.25e-05; 71s
network 5, training 0, epoch 340: train scaled MSE 0.000359619; val RMSE 0.002223396; lr 6.25e-05; 73s
network 5, training 0, epoch 350: train scaled MSE 0.000354121; val RMSE 0.002219821; lr 6.25e-05; 75s
network 5, training 0, epoch 360: train scaled MSE 0.000366991; val RMSE 0.002219388; lr 6.25e-05; 77s
network 5, training 0, epoch 370: train scaled MSE 0.000337253; val RMSE 0.002217119; lr 6.25e-05; 79s
network 5, training 0, epoch 380: train scaled MSE 0.000340475; val RMSE 0.002217349; lr 6.25e-05; 81s
network 5, training 0, epoch 390: train scaled MSE 0.000330493; val RMSE 0.002216736; lr 3.125e-05; 84s
network 5, training 0, epoch 400: train scaled MSE 0.000321087; val RMSE 0.002213237; lr 3.125e-05; 86s
network 5, training 0, epoch 410: train scaled MSE 0.000346192; val RMSE 0.00221545; lr 3.125e-05; 88s
network 5, training 0, epoch 420: train scaled MSE 0.000315423; val RMSE 0.002211636; lr 3.125e-05; 90s
network 5, training 0, epoch 430: train scaled MSE 0.000312482; val RMSE 0.002211092; lr 3.125e-05; 92s
network 5, training 0, epoch 440: train scaled MSE 0.000310909; val RMSE 0.00221021; lr 3.125e-05; 94s
network 5, training 0, epoch 450: train scaled MSE 0.000307842; val RMSE 0.002209234; lr 3.125e-05; 97s
network 5, training 0, epoch 460: train scaled MSE 0.000304069; val RMSE 0.002208148; lr 3.125e-05; 99s
network 5, training 0, epoch 470: train scaled MSE 0.000301667; val RMSE 0.002207773; lr 3.125e-05; 101s
network 5, training 0, epoch 480: train scaled MSE 0.000298276; val RMSE 0.002207698; lr 3.125e-05; 103s
network 5, training 0, epoch 490: train scaled MSE 0.00029958; val RMSE 0.002206188; lr 3.125e-05; 105s
network 5, training 0, epoch 500: train scaled MSE 0.000292675; val RMSE 0.002205229; lr 3.125e-05; 107s
network 5, training 0, epoch 510: train scaled MSE 0.000295431; val RMSE 0.002207605; lr 3.125e-05; 109s
network 5, training 0, epoch 520: train scaled MSE 0.00028443; val RMSE 0.002203048; lr 1.5625e-05; 111s
network 5, training 0, epoch 530: train scaled MSE 0.000284441; val RMSE 0.002202547; lr 1.5625e-05; 113s
network 5, training 0, epoch 540: train scaled MSE 0.00028488; val RMSE 0.002202377; lr 1.5625e-05; 115s
network 5, training 0, epoch 550: train scaled MSE 0.000280245; val RMSE 0.002201091; lr 1.5625e-05; 117s
network 5, training 0, epoch 560: train scaled MSE 0.000279872; val RMSE 0.002201465; lr 1.5625e-05; 118s
network 5, training 0, epoch 570: train scaled MSE 0.000279245; val RMSE 0.002200801; lr 1e-05; 120s
network 5, training 0, epoch 580: train scaled MSE 0.000275242; val RMSE 0.002199776; lr 1e-05; 122s
network 5, training 0, epoch 590: train scaled MSE 0.000280044; val RMSE 0.002200147; lr 1e-05; 124s
network 5, training 0, epoch 600: train scaled MSE 0.000273498; val RMSE 0.002199923; lr 1e-05; 126s
network 5, training 0, epoch 610: train scaled MSE 0.000276586; val RMSE 0.002200173; lr 1e-05; 128s
network 5, training 0, epoch 620: train scaled MSE 0.00027894; val RMSE 0.002199855; lr 1e-05; 129s
network 5, training 0, epoch 630: train scaled MSE 0.000271121; val RMSE 0.002198847; lr 1e-05; 131s
network 5, training 0, epoch 640: train scaled MSE 0.000276761; val RMSE 0.002200453; lr 1e-05; 133s
network 5, training 0, epoch 650: train scaled MSE 0.000269956; val RMSE 0.002198628; lr 1e-05; 135s
network 5, training 0, epoch 660: train scaled MSE 0.00026856; val RMSE 0.002198487; lr 1e-05; 137s
network 5, training 0, epoch 670: train scaled MSE 0.000268579; val RMSE 0.002198238; lr 1e-05; 138s
network 5, training 0, epoch 680: train scaled MSE 0.000267037; val RMSE 0.002197724; lr 1e-05; 140s
network 5, training 0, epoch 690: train scaled MSE 0.00026626; val RMSE 0.002197584; lr 1e-05; 142s
network 5, training 0, epoch 700: train scaled MSE 0.00026568; val RMSE 0.002197574; lr 1e-05; 144s
network 5, training 0, epoch 710: train scaled MSE 0.000264386; val RMSE 0.0021968; lr 1e-05; 146s
network 5, training 0, epoch 720: train scaled MSE 0.000264842; val RMSE 0.002196706; lr 1e-05; 147s
network 5, training 0, epoch 730: train scaled MSE 0.000262529; val RMSE 0.002196187; lr 1e-05; 149s
network 5, training 0, epoch 740: train scaled MSE 0.000261624; val RMSE 0.002195573; lr 1e-05; 151s
network 5, training 0, epoch 750: train scaled MSE 0.000262015; val RMSE 0.002195509; lr 1e-05; 153s
network 5, training 0, epoch 760: train scaled MSE 0.000261184; val RMSE 0.002195608; lr 1e-05; 155s
network 5, training 0, epoch 770: train scaled MSE 0.000258935; val RMSE 0.002195047; lr 1e-05; 157s
network 5, training 0, epoch 780: train scaled MSE 0.000259249; val RMSE 0.002195255; lr 1e-05; 158s
network 5, training 0, epoch 790: train scaled MSE 0.000257404; val RMSE 0.002194969; lr 1e-05; 160s
network 5, training 0, epoch 800: train scaled MSE 0.000257333; val RMSE 0.002194611; lr 1e-05; 162s
network 5, training 0, epoch 810: train scaled MSE 0.000256314; val RMSE 0.002194703; lr 1e-05; 164s
network 5, training 0, epoch 820: train scaled MSE 0.00025554; val RMSE 0.002194191; lr 1e-05; 166s
network 5, training 0, epoch 830: train scaled MSE 0.000255767; val RMSE 0.002193818; lr 1e-05; 168s
network 5, training 0, epoch 840: train scaled MSE 0.000255417; val RMSE 0.002193803; lr 1e-05; 169s
network 5, training 0, epoch 850: train scaled MSE 0.00025483; val RMSE 0.002193837; lr 1e-05; 171s
network 5, training 0, epoch 860: train scaled MSE 0.000252432; val RMSE 0.002193162; lr 1e-05; 173s
network 5, training 0, epoch 870: train scaled MSE 0.000254645; val RMSE 0.002193387; lr 1e-05; 175s
network 5, training 0, epoch 880: train scaled MSE 0.000250913; val RMSE 0.00219241; lr 1e-05; 177s
network 5, training 0, epoch 890: train scaled MSE 0.00024985; val RMSE 0.002192284; lr 1e-05; 179s
network 5, training 0, epoch 900: train scaled MSE 0.000265713; val RMSE 0.002193499; lr 1e-05; 181s
network 5, training 0, epoch 910: train scaled MSE 0.000249008; val RMSE 0.00219181; lr 1e-05; 182s
network 5, training 0, epoch 920: train scaled MSE 0.000247333; val RMSE 0.002191501; lr 1e-05; 184s
network 5, training 0, epoch 930: train scaled MSE 0.000246738; val RMSE 0.002191411; lr 1e-05; 186s
network 5, training 0, epoch 940: train scaled MSE 0.000245766; val RMSE 0.002191346; lr 1e-05; 188s
network 5, training 0, epoch 950: train scaled MSE 0.000246229; val RMSE 0.002190717; lr 1e-05; 190s
network 5, training 0, epoch 960: train scaled MSE 0.000248277; val RMSE 0.002190649; lr 1e-05; 192s
network 5, training 0, epoch 970: train scaled MSE 0.000243234; val RMSE 0.002189867; lr 1e-05; 193s
network 5, training 0, epoch 980: train scaled MSE 0.000242522; val RMSE 0.002189852; lr 1e-05; 195s
network 5, training 0, epoch 990: train scaled MSE 0.00024276; val RMSE 0.002189326; lr 1e-05; 197s
network 5, training 0, epoch 1000: train scaled MSE 0.000241732; val RMSE 0.00218924; lr 1e-05; 199s
network 5, training 0, epoch 1010: train scaled MSE 0.000240604; val RMSE 0.002189229; lr 1e-05; 201s
network 5, training 0, epoch 1020: train scaled MSE 0.000239804; val RMSE 0.00218874; lr 1e-05; 202s
network 5, training 0, epoch 1030: train scaled MSE 0.000239517; val RMSE 0.002188446; lr 1e-05; 204s
network 5, training 0, epoch 1040: train scaled MSE 0.000239124; val RMSE 0.002188284; lr 1e-05; 206s
network 5, training 0, epoch 1050: train scaled MSE 0.000239155; val RMSE 0.002188616; lr 1e-05; 208s
network 5, training 0, epoch 1060: train scaled MSE 0.000237168; val RMSE 0.002187598; lr 1e-05; 210s
network 5, training 0, epoch 1070: train scaled MSE 0.000236863; val RMSE 0.002187712; lr 1e-05; 211s
network 5, training 0, epoch 1080: train scaled MSE 0.000237062; val RMSE 0.00218735; lr 1e-05; 213s
network 5, training 0, epoch 1090: train scaled MSE 0.000235359; val RMSE 0.002187096; lr 1e-05; 215s
network 5, training 0, epoch 1100: train scaled MSE 0.000234639; val RMSE 0.002186851; lr 1e-05; 216s
network 5, training 0, epoch 1110: train scaled MSE 0.000233897; val RMSE 0.002186766; lr 1e-05; 218s
network 5, training 0, epoch 1120: train scaled MSE 0.000233092; val RMSE 0.00218653; lr 1e-05; 220s
network 5, training 0, epoch 1130: train scaled MSE 0.000232595; val RMSE 0.002186073; lr 1e-05; 222s
network 5, training 0, epoch 1140: train scaled MSE 0.00023203; val RMSE 0.002186204; lr 1e-05; 223s
network 5, training 0, epoch 1150: train scaled MSE 0.000231289; val RMSE 0.002185942; lr 1e-05; 225s
network 5, training 0, epoch 1160: train scaled MSE 0.000232124; val RMSE 0.002185997; lr 1e-05; 227s
network 5, training 0, epoch 1170: train scaled MSE 0.00022985; val RMSE 0.002185407; lr 1e-05; 229s
network 5, training 0, epoch 1180: train scaled MSE 0.000229326; val RMSE 0.002185136; lr 1e-05; 230s
network 5, training 0, epoch 1190: train scaled MSE 0.000229288; val RMSE 0.002185484; lr 1e-05; 232s
network 5, training 0, epoch 1200: train scaled MSE 0.000227915; val RMSE 0.002185037; lr 1e-05; 234s
network 5, training 0, epoch 1210: train scaled MSE 0.000228836; val RMSE 0.002184908; lr 1e-05; 236s
network 5, training 0, epoch 1220: train scaled MSE 0.000226868; val RMSE 0.002184632; lr 1e-05; 238s
network 5, training 0, epoch 1230: train scaled MSE 0.000227244; val RMSE 0.002184829; lr 1e-05; 239s
network 5, training 0, epoch 1240: train scaled MSE 0.000225959; val RMSE 0.002184488; lr 1e-05; 241s
network 5, training 0, epoch 1250: train scaled MSE 0.00022542; val RMSE 0.002183785; lr 1e-05; 243s
network 5, training 0, epoch 1260: train scaled MSE 0.00022606; val RMSE 0.002183823; lr 1e-05; 245s
network 5, training 0, epoch 1270: train scaled MSE 0.000225587; val RMSE 0.002183922; lr 1e-05; 246s
network 5, training 0, epoch 1280: train scaled MSE 0.00022337; val RMSE 0.002183145; lr 1e-05; 248s
network 5, training 0, epoch 1290: train scaled MSE 0.000222796; val RMSE 0.00218277; lr 1e-05; 250s
network 5, training 0, epoch 1300: train scaled MSE 0.000222729; val RMSE 0.002182668; lr 1e-05; 252s
network 5, training 0, epoch 1310: train scaled MSE 0.000223025; val RMSE 0.002182823; lr 1e-05; 253s
network 5, training 0, epoch 1320: train scaled MSE 0.00022123; val RMSE 0.002182545; lr 1e-05; 255s
network 5, training 0, epoch 1330: train scaled MSE 0.000220527; val RMSE 0.002182098; lr 1e-05; 257s
network 5, training 0, epoch 1340: train scaled MSE 0.000219952; val RMSE 0.002182693; lr 1e-05; 259s
network 5, training 0, epoch 1350: train scaled MSE 0.000219421; val RMSE 0.002182298; lr 1e-05; 260s
network 5, training 0, epoch 1360: train scaled MSE 0.000221463; val RMSE 0.002182591; lr 1e-05; 262s
network 5, training 0, epoch 1370: train scaled MSE 0.000218384; val RMSE 0.002181552; lr 1e-05; 264s
network 5, training 0, epoch 1380: train scaled MSE 0.000217633; val RMSE 0.00218159; lr 1e-05; 266s
network 5, training 0, epoch 1390: train scaled MSE 0.000217766; val RMSE 0.002181025; lr 1e-05; 268s
network 5, training 0, epoch 1400: train scaled MSE 0.000217757; val RMSE 0.002181431; lr 1e-05; 269s
network 5, training 0, epoch 1410: train scaled MSE 0.000216614; val RMSE 0.002181254; lr 1e-05; 271s
network 5, training 0, epoch 1420: train scaled MSE 0.000215151; val RMSE 0.002180663; lr 1e-05; 273s
network 5, training 0, epoch 1430: train scaled MSE 0.000214637; val RMSE 0.002180791; lr 1e-05; 274s
network 5, training 0, epoch 1440: train scaled MSE 0.00021399; val RMSE 0.002179876; lr 1e-05; 276s
network 5, training 0, epoch 1450: train scaled MSE 0.000213612; val RMSE 0.002179914; lr 1e-05; 278s
network 5, training 0, epoch 1460: train scaled MSE 0.000212812; val RMSE 0.002179708; lr 1e-05; 280s
network 5, training 0, epoch 1470: train scaled MSE 0.000213443; val RMSE 0.002180499; lr 1e-05; 282s
network 5, training 0, epoch 1480: train scaled MSE 0.00021157; val RMSE 0.002179351; lr 1e-05; 283s
network 5, training 0, epoch 1490: train scaled MSE 0.000211187; val RMSE 0.002179358; lr 1e-05; 285s
network 5, training 0, epoch 1500: train scaled MSE 0.000210446; val RMSE 0.002178861; lr 1e-05; 287s
network 5, training 0, epoch 1510: train scaled MSE 0.000210238; val RMSE 0.002178582; lr 1e-05; 289s
network 5, training 0, epoch 1520: train scaled MSE 0.000209856; val RMSE 0.00217902; lr 1e-05; 291s
network 5, training 0, epoch 1530: train scaled MSE 0.000210044; val RMSE 0.002180103; lr 1e-05; 292s
network 5, training 0, epoch 1540: train scaled MSE 0.000208564; val RMSE 0.002178846; lr 1e-05; 294s
network 5, training 0, epoch 1550: train scaled MSE 0.000209764; val RMSE 0.002179344; lr 1e-05; 296s
network 5, training 0, epoch 1560: train scaled MSE 0.000207253; val RMSE 0.002178707; lr 1e-05; 297s
network 5, training 0, epoch 1570: train scaled MSE 0.000206721; val RMSE 0.002178235; lr 1e-05; 299s
network 5, training 0, epoch 1580: train scaled MSE 0.000206129; val RMSE 0.002178177; lr 1e-05; 301s
network 5, training 0, epoch 1590: train scaled MSE 0.000205769; val RMSE 0.002177645; lr 1e-05; 303s
network 5, training 0, epoch 1600: train scaled MSE 0.000220386; val RMSE 0.002180057; lr 1e-05; 305s
network 5, training 0, epoch 1610: train scaled MSE 0.000210529; val RMSE 0.002178791; lr 1e-05; 307s
network 5, training 0, epoch 1620: train scaled MSE 0.000205141; val RMSE 0.002177093; lr 1e-05; 309s
network 5, training 0, epoch 1630: train scaled MSE 0.000204048; val RMSE 0.002177045; lr 1e-05; 311s
network 5, training 0, epoch 1640: train scaled MSE 0.000217114; val RMSE 0.002177776; lr 1e-05; 312s
network 5, training 0, epoch 1650: train scaled MSE 0.000207514; val RMSE 0.002177547; lr 1e-05; 314s
network 5, training 0, epoch 1660: train scaled MSE 0.000203868; val RMSE 0.002176794; lr 1e-05; 316s
network 5, training 0, epoch 1670: train scaled MSE 0.000202747; val RMSE 0.002176827; lr 1e-05; 318s
network 5, training 0, epoch 1680: train scaled MSE 0.000202156; val RMSE 0.002176541; lr 1e-05; 319s
network 5, training 0, epoch 1690: train scaled MSE 0.000201767; val RMSE 0.002176561; lr 1e-05; 321s
network 5, training 0, epoch 1700: train scaled MSE 0.000202062; val RMSE 0.002176478; lr 1e-05; 323s
network 5, training 0, epoch 1710: train scaled MSE 0.000202525; val RMSE 0.002176293; lr 1e-05; 325s
network 5, training 0, epoch 1720: train scaled MSE 0.000201289; val RMSE 0.002176051; lr 1e-05; 326s
network 5, training 0, epoch 1730: train scaled MSE 0.000199922; val RMSE 0.00217617; lr 1e-05; 328s
network 5, training 0, epoch 1740: train scaled MSE 0.00019941; val RMSE 0.002175751; lr 1e-05; 330s
network 5, training 0, epoch 1750: train scaled MSE 0.00019895; val RMSE 0.002175968; lr 1e-05; 332s
network 5, training 0, epoch 1760: train scaled MSE 0.000198719; val RMSE 0.00217546; lr 1e-05; 334s
network 5, training 0, epoch 1770: train scaled MSE 0.000197898; val RMSE 0.002175262; lr 1e-05; 335s
network 5, training 0, epoch 1780: train scaled MSE 0.000198028; val RMSE 0.002175115; lr 1e-05; 337s
network 5, training 0, epoch 1790: train scaled MSE 0.0001972; val RMSE 0.002174899; lr 1e-05; 339s
network 5, training 0, epoch 1800: train scaled MSE 0.000196285; val RMSE 0.002174622; lr 1e-05; 341s
network 5, training 0, epoch 1810: train scaled MSE 0.000208986; val RMSE 0.002176076; lr 1e-05; 343s
network 5, training 0, epoch 1820: train scaled MSE 0.00019773; val RMSE 0.002175237; lr 1e-05; 344s
network 5, training 0, epoch 1830: train scaled MSE 0.000195018; val RMSE 0.00217426; lr 1e-05; 346s
network 5, training 0, epoch 1840: train scaled MSE 0.000194648; val RMSE 0.002174081; lr 1e-05; 348s
network 5, training 0, epoch 1850: train scaled MSE 0.000206758; val RMSE 0.002175433; lr 1e-05; 350s
network 5, training 0, epoch 1860: train scaled MSE 0.000193605; val RMSE 0.0021737; lr 1e-05; 351s
network 5, training 0, epoch 1870: train scaled MSE 0.000193392; val RMSE 0.002173722; lr 1e-05; 353s
network 5, training 0, epoch 1880: train scaled MSE 0.000192756; val RMSE 0.002173253; lr 1e-05; 355s
network 5, training 0, epoch 1890: train scaled MSE 0.00019309; val RMSE 0.002173368; lr 1e-05; 357s
network 5, training 0, epoch 1900: train scaled MSE 0.00019503; val RMSE 0.00217342; lr 1e-05; 359s
network 5, training 0, epoch 1910: train scaled MSE 0.000196237; val RMSE 0.002173854; lr 1e-05; 361s
network 5, training 0, epoch 1920: train scaled MSE 0.000195595; val RMSE 0.002173259; lr 1e-05; 362s
network 5, training 0, epoch 1930: train scaled MSE 0.00019407; val RMSE 0.002173388; lr 1e-05; 364s
network 5, training 0, epoch 1940: train scaled MSE 0.000190449; val RMSE 0.00217219; lr 1e-05; 366s
network 5, training 0, epoch 1950: train scaled MSE 0.000198568; val RMSE 0.002173446; lr 1e-05; 368s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,0.5086,"[-1.06%, 1.72%]",0.1203,0.0,0.2318
MLP,0.0033,38.9161,"[25.58%, 50.16%]",0.6238,418.599,0.5384

network 5, training 1, epoch 1: train scaled MSE 0.799571; val RMSE 0.02546784; lr 0.001; 0s
network 5, training 1, epoch 10: train scaled MSE 0.0252625; val RMSE 0.005971266; lr 0.001; 2s
network 5, training 1, epoch 20: train scaled MSE 0.0101232; val RMSE 0.004036726; lr 0.001; 4s
network 5, training 1, epoch 30: train scaled MSE 0.00652494; val RMSE 0.004043099; lr 0.001; 5s
network 5, training 1, epoch 40: train scaled MSE 0.00499618; val RMSE 0.00351251; lr 0.001; 7s
network 5, training 1, epoch 50: train scaled MSE 0.00411395; val RMSE 0.003387316; lr 0.001; 9s
network 5, training 1, epoch 60: train scaled MSE 0.00278706; val RMSE 0.003249238; lr 0.001; 11s
network 5, training 1, epoch 70: train scaled MSE 0.00223704; val RMSE 0.003205966; lr 0.001; 13s
network 5, training 1, epoch 80: train scaled MSE 0.00181241; val RMSE 0.003262159; lr 0.001; 15s
network 5, training 1, epoch 90: train scaled MSE 0.00386069; val RMSE 0.003306467; lr 0.001; 17s
network 5, training 1, epoch 100: train scaled MSE 0.00109657; val RMSE 0.003106281; lr 0.0005; 19s
network 5, training 1, epoch 110: train scaled MSE 0.000970768; val RMSE 0.003096363; lr 0.0005; 21s
network 5, training 1, epoch 120: train scaled MSE 0.00087592; val RMSE 0.00317298; lr 0.0005; 22s
network 5, training 1, epoch 130: train scaled MSE 0.000808482; val RMSE 0.003079646; lr 0.0005; 24s
network 5, training 1, epoch 140: train scaled MSE 0.000746602; val RMSE 0.003091393; lr 0.0005; 26s
network 5, training 1, epoch 150: train scaled MSE 0.000602416; val RMSE 0.00307201; lr 0.00025; 28s
network 5, training 1, epoch 160: train scaled MSE 0.0005671; val RMSE 0.003063146; lr 0.00025; 30s
network 5, training 1, epoch 170: train scaled MSE 0.000528201; val RMSE 0.003065276; lr 0.00025; 32s
network 5, training 1, epoch 180: train scaled MSE 0.000508928; val RMSE 0.00305723; lr 0.00025; 34s
network 5, training 1, epoch 190: train scaled MSE 0.000479759; val RMSE 0.003058535; lr 0.00025; 36s
network 5, training 1, epoch 200: train scaled MSE 0.000427274; val RMSE 0.003055559; lr 0.000125; 37s
network 5, training 1, epoch 210: train scaled MSE 0.000397682; val RMSE 0.003051497; lr 6.25e-05; 39s
network 5, training 1, epoch 220: train scaled MSE 0.000399194; val RMSE 0.003048817; lr 6.25e-05; 41s
network 5, training 1, epoch 230: train scaled MSE 0.00038601; val RMSE 0.003048741; lr 6.25e-05; 43s
network 5, training 1, epoch 240: train scaled MSE 0.000380243; val RMSE 0.003047426; lr 6.25e-05; 44s
network 5, training 1, epoch 250: train scaled MSE 0.000365633; val RMSE 0.003045461; lr 3.125e-05; 46s
network 5, training 1, epoch 260: train scaled MSE 0.000373476; val RMSE 0.003047586; lr 3.125e-05; 48s
network 5, training 1, epoch 270: train scaled MSE 0.000358576; val RMSE 0.003044016; lr 3.125e-05; 50s
network 5, training 1, epoch 280: train scaled MSE 0.000350267; val RMSE 0.003044107; lr 1.5625e-05; 52s
network 5, training 1, epoch 290: train scaled MSE 0.000348391; val RMSE 0.003043715; lr 1.5625e-05; 54s
network 5, training 1, epoch 300: train scaled MSE 0.000344955; val RMSE 0.003043637; lr 1e-05; 55s
network 5, training 1, epoch 310: train scaled MSE 0.000344503; val RMSE 0.003042934; lr 1e-05; 57s
network 5, training 1, epoch 320: train scaled MSE 0.000344181; val RMSE 0.003042348; lr 1e-05; 59s
network 5, training 1, epoch 330: train scaled MSE 0.00034222; val RMSE 0.003043254; lr 1e-05; 61s
network 5, training 1, epoch 340: train scaled MSE 0.00034015; val RMSE 0.003042261; lr 1e-05; 63s
network 5, training 1, epoch 350: train scaled MSE 0.000339046; val RMSE 0.003041771; lr 1e-05; 64s
network 5, training 1, epoch 360: train scaled MSE 0.000338284; val RMSE 0.0030418; lr 1e-05; 66s
network 5, training 1, epoch 370: train scaled MSE 0.000337163; val RMSE 0.003041497; lr 1e-05; 68s
network 5, training 1, epoch 380: train scaled MSE 0.000338658; val RMSE 0.003040818; lr 1e-05; 70s
network 5, training 1, epoch 390: train scaled MSE 0.000335017; val RMSE 0.003040851; lr 1e-05; 72s
network 5, training 1, epoch 400: train scaled MSE 0.000333738; val RMSE 0.003040801; lr 1e-05; 74s
network 5, training 1, epoch 410: train scaled MSE 0.000333126; val RMSE 0.003040563; lr 1e-05; 75s
network 5, training 1, epoch 420: train scaled MSE 0.000331236; val RMSE 0.003040339; lr 1e-05; 77s
network 5, training 1, epoch 430: train scaled MSE 0.000331203; val RMSE 0.003040427; lr 1e-05; 79s
network 5, training 1, epoch 440: train scaled MSE 0.000329805; val RMSE 0.003040201; lr 1e-05; 81s
network 5, training 1, epoch 450: train scaled MSE 0.000328803; val RMSE 0.003040317; lr 1e-05; 83s
network 5, training 1, epoch 460: train scaled MSE 0.000326645; val RMSE 0.003039661; lr 1e-05; 84s
network 5, training 1, epoch 470: train scaled MSE 0.000325641; val RMSE 0.003039511; lr 1e-05; 86s
network 5, training 1, epoch 480: train scaled MSE 0.000324966; val RMSE 0.003039753; lr 1e-05; 88s
network 5, training 1, epoch 490: train scaled MSE 0.000325967; val RMSE 0.003040133; lr 1e-05; 90s
network 5, training 1, epoch 500: train scaled MSE 0.00032589; val RMSE 0.003039444; lr 1e-05; 91s
network 5, training 1, epoch 510: train scaled MSE 0.000323306; val RMSE 0.003038802; lr 1e-05; 93s
network 5, training 1, epoch 520: train scaled MSE 0.000320323; val RMSE 0.003038888; lr 1e-05; 95s
network 5, training 1, epoch 530: train scaled MSE 0.000322285; val RMSE 0.003039035; lr 1e-05; 97s
network 5, training 1, epoch 540: train scaled MSE 0.000318762; val RMSE 0.003038973; lr 1e-05; 99s
network 5, training 1, epoch 550: train scaled MSE 0.000317207; val RMSE 0.003038504; lr 1e-05; 101s
network 5, training 1, epoch 560: train scaled MSE 0.000323341; val RMSE 0.003038297; lr 1e-05; 102s
network 5, training 1, epoch 570: train scaled MSE 0.000315055; val RMSE 0.003037799; lr 1e-05; 104s
network 5, training 1, epoch 580: train scaled MSE 0.000314377; val RMSE 0.003038091; lr 1e-05; 106s
network 5, training 1, epoch 590: train scaled MSE 0.000312385; val RMSE 0.003037635; lr 1e-05; 108s
network 5, training 1, epoch 600: train scaled MSE 0.000312704; val RMSE 0.003037791; lr 1e-05; 109s
network 5, training 1, epoch 610: train scaled MSE 0.000329167; val RMSE 0.003039972; lr 1e-05; 111s
network 5, training 1, epoch 620: train scaled MSE 0.000313937; val RMSE 0.003037927; lr 1e-05; 113s
network 5, training 1, epoch 630: train scaled MSE 0.000310077; val RMSE 0.003037424; lr 1e-05; 115s
network 5, training 1, epoch 640: train scaled MSE 0.000307852; val RMSE 0.003037915; lr 1e-05; 117s
network 5, training 1, epoch 650: train scaled MSE 0.000311339; val RMSE 0.003037764; lr 1e-05; 119s
network 5, training 1, epoch 660: train scaled MSE 0.000307272; val RMSE 0.003036684; lr 1e-05; 120s
network 5, training 1, epoch 670: train scaled MSE 0.000305313; val RMSE 0.003036801; lr 1e-05; 122s
network 5, training 1, epoch 680: train scaled MSE 0.000327082; val RMSE 0.003037839; lr 1e-05; 124s
network 5, training 1, epoch 690: train scaled MSE 0.00030803; val RMSE 0.003037182; lr 1e-05; 126s
network 5, training 1, epoch 700: train scaled MSE 0.000302557; val RMSE 0.003036259; lr 1e-05; 127s
network 5, training 1, epoch 710: train scaled MSE 0.000301471; val RMSE 0.003036271; lr 1e-05; 129s
network 5, training 1, epoch 720: train scaled MSE 0.000301402; val RMSE 0.003036013; lr 1e-05; 131s
network 5, training 1, epoch 730: train scaled MSE 0.000299931; val RMSE 0.003036035; lr 1e-05; 133s
network 5, training 1, epoch 740: train scaled MSE 0.000299479; val RMSE 0.00303551; lr 1e-05; 135s
network 5, training 1, epoch 750: train scaled MSE 0.000299175; val RMSE 0.003035759; lr 1e-05; 137s
network 5, training 1, epoch 760: train scaled MSE 0.000297897; val RMSE 0.003035342; lr 1e-05; 138s
network 5, training 1, epoch 770: train scaled MSE 0.00029707; val RMSE 0.003035441; lr 1e-05; 140s
network 5, training 1, epoch 780: train scaled MSE 0.000296239; val RMSE 0.003035546; lr 1e-05; 142s
Standard Linear Baseline Validation RMSE: 0.004051254

Network seed 5, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0042,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0041,1.0086,"[-0.50%, 2.17%]",0.1308,0.0,0.2333
MLP,0.0032,39.6287,"[27.24%, 51.40%]",0.6331,383.8626,0.3356

network 5, training 2, epoch 1: train scaled MSE 0.807358; val RMSE 0.02466979; lr 0.001; 0s
network 5, training 2, epoch 10: train scaled MSE 0.024474; val RMSE 0.005726465; lr 0.001; 2s
network 5, training 2, epoch 20: train scaled MSE 0.0106933; val RMSE 0.00410098; lr 0.001; 4s
network 5, training 2, epoch 30: train scaled MSE 0.0106174; val RMSE 0.004286039; lr 0.001; 5s
network 5, training 2, epoch 40: train scaled MSE 0.00592614; val RMSE 0.003761158; lr 0.001; 7s
network 5, training 2, epoch 50: train scaled MSE 0.00458107; val RMSE 0.003696079; lr 0.001; 9s
network 5, training 2, epoch 60: train scaled MSE 0.00365534; val RMSE 0.003640078; lr 0.001; 11s
network 5, training 2, epoch 70: train scaled MSE 0.0026765; val RMSE 0.003580472; lr 0.001; 13s
network 5, training 2, epoch 80: train scaled MSE 0.00223521; val RMSE 0.003501337; lr 0.001; 15s
network 5, training 2, epoch 90: train scaled MSE 0.00238461; val RMSE 0.003437476; lr 0.001; 16s
network 5, training 2, epoch 100: train scaled MSE 0.00148573; val RMSE 0.003394769; lr 0.001; 18s
network 5, training 2, epoch 110: train scaled MSE 0.00215216; val RMSE 0.003386449; lr 0.001; 20s
network 5, training 2, epoch 120: train scaled MSE 0.00117847; val RMSE 0.003370644; lr 0.001; 22s
network 5, training 2, epoch 130: train scaled MSE 0.00111724; val RMSE 0.003317654; lr 0.001; 24s
network 5, training 2, epoch 140: train scaled MSE 0.000836749; val RMSE 0.003259577; lr 0.001; 26s
network 5, training 2, epoch 150: train scaled MSE 0.00169914; val RMSE 0.003269273; lr 0.001; 28s
network 5, training 2, epoch 160: train scaled MSE 0.000885963; val RMSE 0.003234658; lr 0.001; 30s
network 5, training 2, epoch 170: train scaled MSE 0.000608622; val RMSE 0.003178774; lr 0.001; 31s
network 5, training 2, epoch 180: train scaled MSE 0.000641746; val RMSE 0.003188053; lr 0.001; 33s
network 5, training 2, epoch 190: train scaled MSE 0.000367258; val RMSE 0.003162901; lr 0.0005; 35s
network 5, training 2, epoch 200: train scaled MSE 0.0005216; val RMSE 0.003115052; lr 0.0005; 37s
network 5, training 2, epoch 210: train scaled MSE 0.000335403; val RMSE 0.003119192; lr 0.0005; 39s
network 5, training 2, epoch 220: train scaled MSE 0.00215893; val RMSE 0.00328281; lr 0.0005; 41s
network 5, training 2, epoch 230: train scaled MSE 0.000286054; val RMSE 0.003075811; lr 0.0005; 42s
network 5, training 2, epoch 240: train scaled MSE 0.000280735; val RMSE 0.003066814; lr 0.0005; 44s
network 5, training 2, epoch 250: train scaled MSE 0.0028055; val RMSE 0.003164954; lr 0.0005; 46s
network 5, training 2, epoch 260: train scaled MSE 0.000232247; val RMSE 0.003051559; lr 0.00025; 48s
network 5, training 2, epoch 270: train scaled MSE 0.000220824; val RMSE 0.003050903; lr 0.00025; 50s
network 5, training 2, epoch 280: train scaled MSE 0.000207321; val RMSE 0.00304115; lr 0.00025; 52s
network 5, training 2, epoch 290: train scaled MSE 0.000224133; val RMSE 0.003078083; lr 0.00025; 54s
network 5, training 2, epoch 300: train scaled MSE 0.000181698; val RMSE 0.003030827; lr 0.000125; 55s
network 5, training 2, epoch 310: train scaled MSE 0.000172152; val RMSE 0.003029183; lr 6.25e-05; 57s
network 5, training 2, epoch 320: train scaled MSE 0.000170234; val RMSE 0.003026018; lr 6.25e-05; 59s
network 5, training 2, epoch 330: train scaled MSE 0.000167636; val RMSE 0.003025179; lr 6.25e-05; 61s
network 5, training 2, epoch 340: train scaled MSE 0.000165968; val RMSE 0.003023181; lr 6.25e-05; 63s
network 5, training 2, epoch 350: train scaled MSE 0.000163265; val RMSE 0.003019867; lr 6.25e-05; 65s
network 5, training 2, epoch 360: train scaled MSE 0.000163153; val RMSE 0.003020512; lr 6.25e-05; 67s
network 5, training 2, epoch 370: train scaled MSE 0.000165405; val RMSE 0.00301925; lr 6.25e-05; 68s
network 5, training 2, epoch 380: train scaled MSE 0.000152872; val RMSE 0.003018847; lr 3.125e-05; 70s
network 5, training 2, epoch 390: train scaled MSE 0.00015194; val RMSE 0.003017262; lr 3.125e-05; 72s
network 5, training 2, epoch 400: train scaled MSE 0.000151213; val RMSE 0.003015857; lr 3.125e-05; 74s
network 5, training 2, epoch 410: train scaled MSE 0.000152374; val RMSE 0.003016306; lr 3.125e-05; 76s
network 5, training 2, epoch 420: train scaled MSE 0.000147712; val RMSE 0.003013499; lr 3.125e-05; 77s
network 5, training 2, epoch 430: train scaled MSE 0.000147319; val RMSE 0.003012436; lr 3.125e-05; 79s
network 5, training 2, epoch 440: train scaled MSE 0.000146215; val RMSE 0.00301134; lr 3.125e-05; 81s
network 5, training 2, epoch 450: train scaled MSE 0.000145002; val RMSE 0.003011304; lr 3.125e-05; 83s
network 5, training 2, epoch 460: train scaled MSE 0.000143377; val RMSE 0.00300926; lr 3.125e-05; 85s
network 5, training 2, epoch 470: train scaled MSE 0.000145878; val RMSE 0.003010363; lr 3.125e-05; 86s
network 5, training 2, epoch 480: train scaled MSE 0.000140799; val RMSE 0.003008968; lr 3.125e-05; 88s
network 5, training 2, epoch 490: train scaled MSE 0.000139591; val RMSE 0.003007596; lr 3.125e-05; 90s
network 5, training 2, epoch 500: train scaled MSE 0.000137212; val RMSE 0.003007699; lr 1.5625e-05; 92s
network 5, training 2, epoch 510: train scaled MSE 0.000136734; val RMSE 0.003006579; lr 1.5625e-05; 94s
network 5, training 2, epoch 520: train scaled MSE 0.000137123; val RMSE 0.003006844; lr 1e-05; 96s
network 5, training 2, epoch 530: train scaled MSE 0.000134307; val RMSE 0.003005961; lr 1e-05; 98s
network 5, training 2, epoch 540: train scaled MSE 0.000133867; val RMSE 0.003006036; lr 1e-05; 99s
network 5, training 2, epoch 550: train scaled MSE 0.000133663; val RMSE 0.003005583; lr 1e-05; 101s
network 5, training 2, epoch 560: train scaled MSE 0.000133523; val RMSE 0.00300556; lr 1e-05; 103s
network 5, training 2, epoch 570: train scaled MSE 0.000132569; val RMSE 0.003004535; lr 1e-05; 105s
network 5, training 2, epoch 580: train scaled MSE 0.000132143; val RMSE 0.003004142; lr 1e-05; 107s
network 5, training 2, epoch 590: train scaled MSE 0.000132047; val RMSE 0.003003922; lr 1e-05; 109s
network 5, training 2, epoch 600: train scaled MSE 0.000131404; val RMSE 0.003003498; lr 1e-05; 110s
network 5, training 2, epoch 610: train scaled MSE 0.000131246; val RMSE 0.003003074; lr 1e-05; 112s
network 5, training 2, epoch 620: train scaled MSE 0.000131568; val RMSE 0.003002942; lr 1e-05; 114s
network 5, training 2, epoch 630: train scaled MSE 0.000130371; val RMSE 0.003002892; lr 1e-05; 116s
network 5, training 2, epoch 640: train scaled MSE 0.000129885; val RMSE 0.003002481; lr 1e-05; 118s
network 5, training 2, epoch 650: train scaled MSE 0.00012967; val RMSE 0.003002008; lr 1e-05; 120s
network 5, training 2, epoch 660: train scaled MSE 0.000129637; val RMSE 0.003002108; lr 1e-05; 122s
network 5, training 2, epoch 670: train scaled MSE 0.000128884; val RMSE 0.0030014; lr 1e-05; 124s
network 5, training 2, epoch 680: train scaled MSE 0.000128836; val RMSE 0.003001507; lr 1e-05; 125s
network 5, training 2, epoch 690: train scaled MSE 0.000128468; val RMSE 0.003000912; lr 1e-05; 127s
network 5, training 2, epoch 700: train scaled MSE 0.000128477; val RMSE 0.00300199; lr 1e-05; 129s
network 5, training 2, epoch 710: train scaled MSE 0.00012836; val RMSE 0.003000972; lr 1e-05; 131s
network 5, training 2, epoch 720: train scaled MSE 0.000128869; val RMSE 0.003001487; lr 1e-05; 133s
network 5, training 2, epoch 730: train scaled MSE 0.000127181; val RMSE 0.003000462; lr 1e-05; 135s
network 5, training 2, epoch 740: train scaled MSE 0.000126811; val RMSE 0.003000554; lr 1e-05; 137s
network 5, training 2, epoch 750: train scaled MSE 0.000127155; val RMSE 0.003000305; lr 1e-05; 139s
network 5, training 2, epoch 760: train scaled MSE 0.000126148; val RMSE 0.002999464; lr 1e-05; 141s
network 5, training 2, epoch 770: train scaled MSE 0.000134647; val RMSE 0.002999887; lr 1e-05; 143s
network 5, training 2, epoch 780: train scaled MSE 0.000125367; val RMSE 0.002999011; lr 1e-05; 145s
network 5, training 2, epoch 790: train scaled MSE 0.000126533; val RMSE 0.002998705; lr 1e-05; 147s
network 5, training 2, epoch 800: train scaled MSE 0.000127; val RMSE 0.002997753; lr 1e-05; 149s
network 5, training 2, epoch 810: train scaled MSE 0.000124376; val RMSE 0.002997945; lr 1e-05; 151s
network 5, training 2, epoch 820: train scaled MSE 0.000125248; val RMSE 0.002997499; lr 1e-05; 152s
network 5, training 2, epoch 830: train scaled MSE 0.000124553; val RMSE 0.002998016; lr 1e-05; 154s
network 5, training 2, epoch 840: train scaled MSE 0.000123437; val RMSE 0.002997222; lr 1e-05; 156s
network 5, training 2, epoch 850: train scaled MSE 0.000123282; val RMSE 0.002997005; lr 1e-05; 158s
network 5, training 2, epoch 860: train scaled MSE 0.000123074; val RMSE 0.002996639; lr 1e-05; 160s
network 5, training 2, epoch 870: train scaled MSE 0.00012252; val RMSE 0.002996686; lr 1e-05; 162s
network 5, training 2, epoch 880: train scaled MSE 0.000122606; val RMSE 0.00299638; lr 1e-05; 164s
network 5, training 2, epoch 890: train scaled MSE 0.000121956; val RMSE 0.0029966; lr 1e-05; 166s
network 5, training 2, epoch 900: train scaled MSE 0.000121436; val RMSE 0.00299594; lr 1e-05; 168s
network 5, training 2, epoch 910: train scaled MSE 0.000121068; val RMSE 0.002995266; lr 1e-05; 169s
network 5, training 2, epoch 920: train scaled MSE 0.000121752; val RMSE 0.002995659; lr 1e-05; 171s
network 5, training 2, epoch 930: train scaled MSE 0.000120568; val RMSE 0.002994753; lr 1e-05; 173s
network 5, training 2, epoch 940: train scaled MSE 0.000120307; val RMSE 0.002995287; lr 1e-05; 175s
network 5, training 2, epoch 950: train scaled MSE 0.000121962; val RMSE 0.002994996; lr 1e-05; 177s
network 5, training 2, epoch 960: train scaled MSE 0.000119995; val RMSE 0.002994602; lr 1e-05; 178s
network 5, training 2, epoch 970: train scaled MSE 0.000120236; val RMSE 0.002994963; lr 1e-05; 180s
network 5, training 2, epoch 980: train scaled MSE 0.000118883; val RMSE 0.002994654; lr 1e-05; 182s
network 5, training 2, epoch 990: train scaled MSE 0.00011846; val RMSE 0.002993972; lr 1e-05; 184s
network 5, training 2, epoch 1000: train scaled MSE 0.000118296; val RMSE 0.002993893; lr 1e-05; 186s
network 5, training 2, epoch 1010: train scaled MSE 0.000118069; val RMSE 0.002993835; lr 1e-05; 188s
network 5, training 2, epoch 1020: train scaled MSE 0.000117628; val RMSE 0.002993079; lr 1e-05; 190s
network 5, training 2, epoch 1030: train scaled MSE 0.000117517; val RMSE 0.002993195; lr 1e-05; 192s
network 5, training 2, epoch 1040: train scaled MSE 0.000117152; val RMSE 0.002992936; lr 1e-05; 194s
network 5, training 2, epoch 1050: train scaled MSE 0.000116495; val RMSE 0.002993035; lr 1e-05; 196s
network 5, training 2, epoch 1060: train scaled MSE 0.000116682; val RMSE 0.002992794; lr 1e-05; 197s
network 5, training 2, epoch 1070: train scaled MSE 0.000117112; val RMSE 0.002992626; lr 1e-05; 199s
network 5, training 2, epoch 1080: train scaled MSE 0.00011563; val RMSE 0.002992058; lr 1e-05; 201s
network 5, training 2, epoch 1090: train scaled MSE 0.000115371; val RMSE 0.002991828; lr 1e-05; 203s
network 5, training 2, epoch 1100: train scaled MSE 0.000115951; val RMSE 0.002991732; lr 1e-05; 205s
network 5, training 2, epoch 1110: train scaled MSE 0.000114655; val RMSE 0.00299138; lr 1e-05; 207s
network 5, training 2, epoch 1120: train scaled MSE 0.000114862; val RMSE 0.002991277; lr 1e-05; 208s
network 5, training 2, epoch 1130: train scaled MSE 0.000114075; val RMSE 0.00299145; lr 1e-05; 210s
network 5, training 2, epoch 1140: train scaled MSE 0.000113763; val RMSE 0.00299042; lr 1e-05; 212s
network 5, training 2, epoch 1150: train scaled MSE 0.000113305; val RMSE 0.002990897; lr 1e-05; 214s
network 5, training 2, epoch 1160: train scaled MSE 0.000115671; val RMSE 0.002990082; lr 1e-05; 216s
network 5, training 2, epoch 1170: train scaled MSE 0.0001127; val RMSE 0.002989613; lr 1e-05; 218s
network 5, training 2, epoch 1180: train scaled MSE 0.000112562; val RMSE 0.002990169; lr 1e-05; 220s
network 5, training 2, epoch 1190: train scaled MSE 0.000112258; val RMSE 0.002990249; lr 1e-05; 222s
network 5, training 2, epoch 1200: train scaled MSE 0.000111958; val RMSE 0.002989617; lr 1e-05; 224s
network 5, training 2, epoch 1210: train scaled MSE 0.000111993; val RMSE 0.00298931; lr 1e-05; 226s
network 5, training 2, epoch 1220: train scaled MSE 0.000111249; val RMSE 0.002989265; lr 1e-05; 227s
network 5, training 2, epoch 1230: train scaled MSE 0.00011099; val RMSE 0.002989272; lr 1e-05; 229s
network 5, training 2, epoch 1240: train scaled MSE 0.000111664; val RMSE 0.002989228; lr 1e-05; 231s
network 5, training 2, epoch 1250: train scaled MSE 0.000115186; val RMSE 0.002989389; lr 1e-05; 233s
network 5, training 2, epoch 1260: train scaled MSE 0.000110513; val RMSE 0.002988334; lr 1e-05; 235s
network 5, training 2, epoch 1270: train scaled MSE 0.000110022; val RMSE 0.002988255; lr 1e-05; 237s
network 5, training 2, epoch 1280: train scaled MSE 0.000109768; val RMSE 0.002988272; lr 1e-05; 239s
network 5, training 2, epoch 1290: train scaled MSE 0.000109358; val RMSE 0.002987689; lr 1e-05; 241s
network 5, training 2, epoch 1300: train scaled MSE 0.000109391; val RMSE 0.002987514; lr 1e-05; 243s
network 5, training 2, epoch 1310: train scaled MSE 0.000109838; val RMSE 0.00298763; lr 1e-05; 245s
network 5, training 2, epoch 1320: train scaled MSE 0.000108439; val RMSE 0.002987839; lr 1e-05; 246s
network 5, training 2, epoch 1330: train scaled MSE 0.000108446; val RMSE 0.00298739; lr 1e-05; 248s
network 5, training 2, epoch 1340: train scaled MSE 0.000108152; val RMSE 0.002987144; lr 1e-05; 250s
network 5, training 2, epoch 1350: train scaled MSE 0.000111111; val RMSE 0.002987482; lr 1e-05; 252s
network 5, training 2, epoch 1360: train scaled MSE 0.000107591; val RMSE 0.002986476; lr 1e-05; 254s
network 5, training 2, epoch 1370: train scaled MSE 0.000108451; val RMSE 0.002986274; lr 1e-05; 256s
network 5, training 2, epoch 1380: train scaled MSE 0.000107295; val RMSE 0.002986202; lr 1e-05; 258s
network 5, training 2, epoch 1390: train scaled MSE 0.000106773; val RMSE 0.002986078; lr 1e-05; 260s
network 5, training 2, epoch 1400: train scaled MSE 0.00010677; val RMSE 0.002985823; lr 1e-05; 262s
network 5, training 2, epoch 1410: train scaled MSE 0.000106367; val RMSE 0.002985793; lr 1e-05; 264s
network 5, training 2, epoch 1420: train scaled MSE 0.000105943; val RMSE 0.002985452; lr 1e-05; 266s
network 5, training 2, epoch 1430: train scaled MSE 0.000105736; val RMSE 0.002985265; lr 1e-05; 267s
network 5, training 2, epoch 1440: train scaled MSE 0.000105441; val RMSE 0.002985609; lr 1e-05; 270s
network 5, training 2, epoch 1450: train scaled MSE 0.000109803; val RMSE 0.002984861; lr 1e-05; 271s
network 5, training 2, epoch 1460: train scaled MSE 0.000105075; val RMSE 0.002984538; lr 1e-05; 273s
network 5, training 2, epoch 1470: train scaled MSE 0.000104568; val RMSE 0.00298428; lr 1e-05; 275s
network 5, training 2, epoch 1480: train scaled MSE 0.000105477; val RMSE 0.002984528; lr 1e-05; 277s
network 5, training 2, epoch 1490: train scaled MSE 0.000105592; val RMSE 0.002983459; lr 1e-05; 279s
network 5, training 2, epoch 1500: train scaled MSE 0.000104228; val RMSE 0.00298384; lr 1e-05; 281s
network 5, training 2, epoch 1510: train scaled MSE 0.000103425; val RMSE 0.002983444; lr 1e-05; 283s
network 5, training 2, epoch 1520: train scaled MSE 0.000103227; val RMSE 0.002983222; lr 1e-05; 285s
network 5, training 2, epoch 1530: train scaled MSE 0.000103084; val RMSE 0.002983495; lr 1e-05; 287s
network 5, training 2, epoch 1540: train scaled MSE 0.000102992; val RMSE 0.002982924; lr 1e-05; 289s
network 5, training 2, epoch 1550: train scaled MSE 0.000106259; val RMSE 0.00298302; lr 1e-05; 290s
network 5, training 2, epoch 1560: train scaled MSE 0.000110684; val RMSE 0.002983279; lr 1e-05; 292s
network 5, training 2, epoch 1570: train scaled MSE 0.000101873; val RMSE 0.002982603; lr 1e-05; 294s
network 5, training 2, epoch 1580: train scaled MSE 0.000101695; val RMSE 0.002982243; lr 1e-05; 296s
network 5, training 2, epoch 1590: train scaled MSE 0.00010145; val RMSE 0.002982208; lr 1e-05; 298s
network 5, training 2, epoch 1600: train scaled MSE 0.000101372; val RMSE 0.002981097; lr 1e-05; 300s
network 5, training 2, epoch 1610: train scaled MSE 0.000101001; val RMSE 0.002981734; lr 1e-05; 302s
network 5, training 2, epoch 1620: train scaled MSE 0.000100779; val RMSE 0.002981139; lr 1e-05; 304s
network 5, training 2, epoch 1630: train scaled MSE 0.000100457; val RMSE 0.002981075; lr 1e-05; 306s
network 5, training 2, epoch 1640: train scaled MSE 0.000100648; val RMSE 0.002981675; lr 1e-05; 308s
network 5, training 2, epoch 1650: train scaled MSE 0.000100333; val RMSE 0.002981361; lr 1e-05; 310s
network 5, training 2, epoch 1660: train scaled MSE 0.000100941; val RMSE 0.002980927; lr 1e-05; 311s
network 5, training 2, epoch 1670: train scaled MSE 9.98953e-05; val RMSE 0.0029807; lr 1e-05; 313s
network 5, training 2, epoch 1680: train scaled MSE 9.94751e-05; val RMSE 0.002980602; lr 1e-05; 315s
network 5, training 2, epoch 1690: train scaled MSE 9.92042e-05; val RMSE 0.002980289; lr 1e-05; 317s
network 5, training 2, epoch 1700: train scaled MSE 9.91631e-05; val RMSE 0.002981084; lr 1e-05; 319s
network 5, training 2, epoch 1710: train scaled MSE 9.89368e-05; val RMSE 0.002980511; lr 1e-05; 321s
network 5, training 2, epoch 1720: train scaled MSE 9.9588e-05; val RMSE 0.002980336; lr 1e-05; 323s
network 5, training 2, epoch 1730: train scaled MSE 9.90023e-05; val RMSE 0.002979779; lr 1e-05; 325s
network 5, training 2, epoch 1740: train scaled MSE 9.80925e-05; val RMSE 0.002979602; lr 1e-05; 327s
network 5, training 2, epoch 1750: train scaled MSE 9.86136e-05; val RMSE 0.002979431; lr 1e-05; 328s
network 5, training 2, epoch 1760: train scaled MSE 9.78355e-05; val RMSE 0.002979276; lr 1e-05; 330s
network 5, training 2, epoch 1770: train scaled MSE 9.76707e-05; val RMSE 0.002979624; lr 1e-05; 332s
network 5, training 2, epoch 1780: train scaled MSE 9.75359e-05; val RMSE 0.002979227; lr 1e-05; 334s
network 5, training 2, epoch 1790: train scaled MSE 9.74077e-05; val RMSE 0.002979011; lr 1e-05; 336s
network 5, training 2, epoch 1800: train scaled MSE 0.000101046; val RMSE 0.002979391; lr 1e-05; 338s
Standard Linear Baseline Validation RMSE: 0.003932667

Network seed 5, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0041,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0041,-0.3020,"[-1.87%, 0.91%]",0.1048,0.0,0.2264
MLP,0.0032,41.6875,"[32.55%, 50.12%]",0.6478,518.1218,0.6582

network 5, training 3, epoch 1: train scaled MSE 0.806719; val RMSE 0.0244426; lr 0.001; 0s
network 5, training 3, epoch 10: train scaled MSE 0.0225935; val RMSE 0.005205058; lr 0.001; 2s
network 5, training 3, epoch 20: train scaled MSE 0.00930398; val RMSE 0.003328663; lr 0.001; 4s
network 5, training 3, epoch 30: train scaled MSE 0.00647525; val RMSE 0.003169944; lr 0.001; 6s
network 5, training 3, epoch 40: train scaled MSE 0.00497051; val RMSE 0.002708991; lr 0.001; 8s
network 5, training 3, epoch 50: train scaled MSE 0.00331694; val RMSE 0.002580454; lr 0.001; 10s
network 5, training 3, epoch 60: train scaled MSE 0.00255032; val RMSE 0.002556303; lr 0.001; 12s
network 5, training 3, epoch 70: train scaled MSE 0.00244122; val RMSE 0.002594087; lr 0.001; 13s
network 5, training 3, epoch 80: train scaled MSE 0.00196072; val RMSE 0.002502748; lr 0.001; 15s
network 5, training 3, epoch 90: train scaled MSE 0.0104094; val RMSE 0.002818867; lr 0.001; 17s
network 5, training 3, epoch 100: train scaled MSE 0.00118613; val RMSE 0.002414337; lr 0.001; 19s
network 5, training 3, epoch 110: train scaled MSE 0.000973669; val RMSE 0.002406752; lr 0.001; 21s
network 5, training 3, epoch 120: train scaled MSE 0.000795164; val RMSE 0.00238583; lr 0.0005; 23s
network 5, training 3, epoch 130: train scaled MSE 0.000722959; val RMSE 0.002375088; lr 0.0005; 25s
network 5, training 3, epoch 140: train scaled MSE 0.000801183; val RMSE 0.00240904; lr 0.0005; 27s
network 5, training 3, epoch 150: train scaled MSE 0.000601011; val RMSE 0.002359279; lr 0.0005; 29s
network 5, training 3, epoch 160: train scaled MSE 0.000555935; val RMSE 0.002361473; lr 0.0005; 31s
network 5, training 3, epoch 170: train scaled MSE 0.000491068; val RMSE 0.002337549; lr 0.00025; 32s
network 5, training 3, epoch 180: train scaled MSE 0.000444937; val RMSE 0.00232152; lr 0.000125; 34s
network 5, training 3, epoch 190: train scaled MSE 0.000431659; val RMSE 0.002314512; lr 0.000125; 36s
network 5, training 3, epoch 200: train scaled MSE 0.000414449; val RMSE 0.002307367; lr 0.000125; 38s
network 5, training 3, epoch 210: train scaled MSE 0.000408741; val RMSE 0.002310239; lr 0.000125; 40s
network 5, training 3, epoch 220: train scaled MSE 0.000388376; val RMSE 0.002299055; lr 0.000125; 42s
network 5, training 3, epoch 230: train scaled MSE 0.000405373; val RMSE 0.002296372; lr 0.000125; 43s
network 5, training 3, epoch 240: train scaled MSE 0.000436218; val RMSE 0.002300732; lr 0.000125; 45s
network 5, training 3, epoch 250: train scaled MSE 0.00041099; val RMSE 0.002290296; lr 0.000125; 47s
network 5, training 3, epoch 260: train scaled MSE 0.000347883; val RMSE 0.002287985; lr 0.000125; 49s
network 5, training 3, epoch 270: train scaled MSE 0.000322561; val RMSE 0.002278419; lr 6.25e-05; 51s
network 5, training 3, epoch 280: train scaled MSE 0.000610591; val RMSE 0.002277382; lr 6.25e-05; 53s
network 5, training 3, epoch 290: train scaled MSE 0.000313009; val RMSE 0.002276214; lr 6.25e-05; 55s
network 5, training 3, epoch 300: train scaled MSE 0.000307391; val RMSE 0.002274547; lr 6.25e-05; 56s
network 5, training 3, epoch 310: train scaled MSE 0.000304731; val RMSE 0.002271321; lr 6.25e-05; 58s
network 5, training 3, epoch 320: train scaled MSE 0.0003167; val RMSE 0.002269478; lr 6.25e-05; 60s
network 5, training 3, epoch 330: train scaled MSE 0.000306112; val RMSE 0.002268343; lr 6.25e-05; 62s
network 5, training 3, epoch 340: train scaled MSE 0.000290702; val RMSE 0.00226986; lr 6.25e-05; 64s
network 5, training 3, epoch 350: train scaled MSE 0.000293562; val RMSE 0.002268163; lr 6.25e-05; 66s
network 5, training 3, epoch 360: train scaled MSE 0.000339936; val RMSE 0.00226463; lr 6.25e-05; 68s
network 5, training 3, epoch 370: train scaled MSE 0.000303393; val RMSE 0.002264762; lr 6.25e-05; 69s
network 5, training 3, epoch 380: train scaled MSE 0.000275735; val RMSE 0.002262593; lr 6.25e-05; 71s
network 5, training 3, epoch 390: train scaled MSE 0.000272806; val RMSE 0.002259366; lr 3.125e-05; 73s
network 5, training 3, epoch 400: train scaled MSE 0.000265741; val RMSE 0.002259431; lr 3.125e-05; 75s
network 5, training 3, epoch 410: train scaled MSE 0.000311009; val RMSE 0.002261382; lr 3.125e-05; 77s
network 5, training 3, epoch 420: train scaled MSE 0.000261462; val RMSE 0.002257518; lr 3.125e-05; 79s
network 5, training 3, epoch 430: train scaled MSE 0.000261266; val RMSE 0.0022567; lr 3.125e-05; 81s
network 5, training 3, epoch 440: train scaled MSE 0.000256281; val RMSE 0.002255491; lr 1.5625e-05; 82s
network 5, training 3, epoch 450: train scaled MSE 0.0002549; val RMSE 0.002255096; lr 1.5625e-05; 84s
network 5, training 3, epoch 460: train scaled MSE 0.000253517; val RMSE 0.002254565; lr 1.5625e-05; 86s
network 5, training 3, epoch 470: train scaled MSE 0.000252756; val RMSE 0.002253239; lr 1.5625e-05; 88s
network 5, training 3, epoch 480: train scaled MSE 0.000250912; val RMSE 0.002252824; lr 1.5625e-05; 90s
network 5, training 3, epoch 490: train scaled MSE 0.000250177; val RMSE 0.002252689; lr 1.5625e-05; 92s
network 5, training 3, epoch 500: train scaled MSE 0.000248815; val RMSE 0.002252264; lr 1e-05; 94s
network 5, training 3, epoch 510: train scaled MSE 0.000246659; val RMSE 0.002251656; lr 1e-05; 96s
network 5, training 3, epoch 520: train scaled MSE 0.000246187; val RMSE 0.002251371; lr 1e-05; 98s
network 5, training 3, epoch 530: train scaled MSE 0.000244739; val RMSE 0.002250804; lr 1e-05; 100s
network 5, training 3, epoch 540: train scaled MSE 0.000244031; val RMSE 0.002250119; lr 1e-05; 102s
network 5, training 3, epoch 550: train scaled MSE 0.000243078; val RMSE 0.00225046; lr 1e-05; 104s
network 5, training 3, epoch 560: train scaled MSE 0.00025144; val RMSE 0.002250313; lr 1e-05; 106s
network 5, training 3, epoch 570: train scaled MSE 0.000241536; val RMSE 0.002250115; lr 1e-05; 108s
network 5, training 3, epoch 580: train scaled MSE 0.000240937; val RMSE 0.002249269; lr 1e-05; 110s
network 5, training 3, epoch 590: train scaled MSE 0.000240183; val RMSE 0.00224879; lr 1e-05; 111s
network 5, training 3, epoch 600: train scaled MSE 0.000239745; val RMSE 0.002248145; lr 1e-05; 113s
network 5, training 3, epoch 610: train scaled MSE 0.000238434; val RMSE 0.002248523; lr 1e-05; 115s
network 5, training 3, epoch 620: train scaled MSE 0.000237828; val RMSE 0.002248195; lr 1e-05; 117s
network 5, training 3, epoch 630: train scaled MSE 0.000242337; val RMSE 0.002247261; lr 1e-05; 119s
network 5, training 3, epoch 640: train scaled MSE 0.000236289; val RMSE 0.002247102; lr 1e-05; 121s
network 5, training 3, epoch 650: train scaled MSE 0.000238698; val RMSE 0.002246556; lr 1e-05; 123s
network 5, training 3, epoch 660: train scaled MSE 0.000235814; val RMSE 0.00224657; lr 1e-05; 125s
network 5, training 3, epoch 670: train scaled MSE 0.000234701; val RMSE 0.002246366; lr 1e-05; 127s
network 5, training 3, epoch 680: train scaled MSE 0.000233794; val RMSE 0.002246094; lr 1e-05; 129s
network 5, training 3, epoch 690: train scaled MSE 0.000239433; val RMSE 0.002246555; lr 1e-05; 131s
network 5, training 3, epoch 700: train scaled MSE 0.000232372; val RMSE 0.002245424; lr 1e-05; 133s
network 5, training 3, epoch 710: train scaled MSE 0.000232092; val RMSE 0.002245271; lr 1e-05; 135s
network 5, training 3, epoch 720: train scaled MSE 0.00024361; val RMSE 0.002246358; lr 1e-05; 136s
network 5, training 3, epoch 730: train scaled MSE 0.000230733; val RMSE 0.002244859; lr 1e-05; 138s
network 5, training 3, epoch 740: train scaled MSE 0.00022995; val RMSE 0.002244205; lr 1e-05; 140s
network 5, training 3, epoch 750: train scaled MSE 0.000229156; val RMSE 0.002244218; lr 1e-05; 142s
network 5, training 3, epoch 760: train scaled MSE 0.000229077; val RMSE 0.002244113; lr 1e-05; 144s
network 5, training 3, epoch 770: train scaled MSE 0.000228011; val RMSE 0.002243647; lr 1e-05; 146s
network 5, training 3, epoch 780: train scaled MSE 0.000227345; val RMSE 0.002243774; lr 1e-05; 148s
network 5, training 3, epoch 790: train scaled MSE 0.000227709; val RMSE 0.002243062; lr 1e-05; 150s
network 5, training 3, epoch 800: train scaled MSE 0.000228054; val RMSE 0.00224325; lr 1e-05; 152s
network 5, training 3, epoch 810: train scaled MSE 0.000225441; val RMSE 0.002242687; lr 1e-05; 154s
network 5, training 3, epoch 820: train scaled MSE 0.000225158; val RMSE 0.002242483; lr 1e-05; 156s
network 5, training 3, epoch 830: train scaled MSE 0.000224674; val RMSE 0.002242026; lr 1e-05; 158s
network 5, training 3, epoch 840: train scaled MSE 0.000225222; val RMSE 0.002242786; lr 1e-05; 160s
network 5, training 3, epoch 850: train scaled MSE 0.000223773; val RMSE 0.002241298; lr 1e-05; 162s
network 5, training 3, epoch 860: train scaled MSE 0.000222402; val RMSE 0.00224138; lr 1e-05; 164s
network 5, training 3, epoch 870: train scaled MSE 0.000221837; val RMSE 0.002241056; lr 1e-05; 166s
network 5, training 3, epoch 880: train scaled MSE 0.000221192; val RMSE 0.002240411; lr 1e-05; 168s
network 5, training 3, epoch 890: train scaled MSE 0.000220825; val RMSE 0.00224063; lr 1e-05; 170s
network 5, training 3, epoch 900: train scaled MSE 0.000221399; val RMSE 0.002240507; lr 1e-05; 172s
network 5, training 3, epoch 910: train scaled MSE 0.000219115; val RMSE 0.002239736; lr 1e-05; 174s
network 5, training 3, epoch 920: train scaled MSE 0.000219267; val RMSE 0.002239459; lr 1e-05; 176s
network 5, training 3, epoch 930: train scaled MSE 0.000220618; val RMSE 0.00224021; lr 1e-05; 178s
network 5, training 3, epoch 940: train scaled MSE 0.00021908; val RMSE 0.002239346; lr 1e-05; 179s
network 5, training 3, epoch 950: train scaled MSE 0.000218196; val RMSE 0.002238641; lr 1e-05; 181s
network 5, training 3, epoch 960: train scaled MSE 0.000217794; val RMSE 0.002238579; lr 1e-05; 183s
network 5, training 3, epoch 970: train scaled MSE 0.000216643; val RMSE 0.002238756; lr 1e-05; 185s
network 5, training 3, epoch 980: train scaled MSE 0.000215044; val RMSE 0.002238137; lr 1e-05; 187s
network 5, training 3, epoch 990: train scaled MSE 0.000214606; val RMSE 0.002238515; lr 1e-05; 189s
network 5, training 3, epoch 1000: train scaled MSE 0.000214182; val RMSE 0.002237977; lr 1e-05; 191s
network 5, training 3, epoch 1010: train scaled MSE 0.000213441; val RMSE 0.002237074; lr 1e-05; 193s
network 5, training 3, epoch 1020: train scaled MSE 0.000212765; val RMSE 0.002237603; lr 1e-05; 195s
network 5, training 3, epoch 1030: train scaled MSE 0.000213349; val RMSE 0.002237605; lr 1e-05; 197s
network 5, training 3, epoch 1040: train scaled MSE 0.000217624; val RMSE 0.002238743; lr 1e-05; 199s
network 5, training 3, epoch 1050: train scaled MSE 0.000220193; val RMSE 0.00224011; lr 1e-05; 201s
network 5, training 3, epoch 1060: train scaled MSE 0.000210936; val RMSE 0.002236341; lr 1e-05; 203s
network 5, training 3, epoch 1070: train scaled MSE 0.000210865; val RMSE 0.002236111; lr 1e-05; 205s
network 5, training 3, epoch 1080: train scaled MSE 0.000210189; val RMSE 0.002236208; lr 1e-05; 207s
network 5, training 3, epoch 1090: train scaled MSE 0.00020979; val RMSE 0.002236391; lr 1e-05; 208s
network 5, training 3, epoch 1100: train scaled MSE 0.000210023; val RMSE 0.002235886; lr 1e-05; 210s
network 5, training 3, epoch 1110: train scaled MSE 0.000210181; val RMSE 0.002235289; lr 1e-05; 212s
network 5, training 3, epoch 1120: train scaled MSE 0.000208177; val RMSE 0.002234949; lr 1e-05; 214s
network 5, training 3, epoch 1130: train scaled MSE 0.000208709; val RMSE 0.002235234; lr 1e-05; 216s
network 5, training 3, epoch 1140: train scaled MSE 0.000207278; val RMSE 0.002234478; lr 1e-05; 218s
network 5, training 3, epoch 1150: train scaled MSE 0.000207107; val RMSE 0.002234252; lr 1e-05; 220s
network 5, training 3, epoch 1160: train scaled MSE 0.000206213; val RMSE 0.002233864; lr 1e-05; 222s
network 5, training 3, epoch 1170: train scaled MSE 0.000207172; val RMSE 0.002234092; lr 1e-05; 223s
network 5, training 3, epoch 1180: train scaled MSE 0.000205997; val RMSE 0.002233504; lr 1e-05; 225s
network 5, training 3, epoch 1190: train scaled MSE 0.00020507; val RMSE 0.002233348; lr 1e-05; 227s
network 5, training 3, epoch 1200: train scaled MSE 0.000203708; val RMSE 0.002233017; lr 1e-05; 229s
network 5, training 3, epoch 1210: train scaled MSE 0.000203495; val RMSE 0.002233026; lr 1e-05; 231s
network 5, training 3, epoch 1220: train scaled MSE 0.000203333; val RMSE 0.00223221; lr 1e-05; 233s
network 5, training 3, epoch 1230: train scaled MSE 0.000201813; val RMSE 0.002233128; lr 1e-05; 235s
network 5, training 3, epoch 1240: train scaled MSE 0.000201367; val RMSE 0.002232369; lr 1e-05; 236s
network 5, training 3, epoch 1250: train scaled MSE 0.000200637; val RMSE 0.002232738; lr 1e-05; 238s
network 5, training 3, epoch 1260: train scaled MSE 0.000199979; val RMSE 0.002231906; lr 1e-05; 240s
network 5, training 3, epoch 1270: train scaled MSE 0.000199508; val RMSE 0.00223154; lr 1e-05; 242s
network 5, training 3, epoch 1280: train scaled MSE 0.000198679; val RMSE 0.002231342; lr 1e-05; 244s
network 5, training 3, epoch 1290: train scaled MSE 0.000201534; val RMSE 0.002231585; lr 1e-05; 245s
network 5, training 3, epoch 1300: train scaled MSE 0.000197525; val RMSE 0.00223126; lr 1e-05; 247s
network 5, training 3, epoch 1310: train scaled MSE 0.000196795; val RMSE 0.002230635; lr 1e-05; 249s
network 5, training 3, epoch 1320: train scaled MSE 0.000200848; val RMSE 0.002230482; lr 1e-05; 251s
network 5, training 3, epoch 1330: train scaled MSE 0.00019607; val RMSE 0.002230121; lr 1e-05; 253s
network 5, training 3, epoch 1340: train scaled MSE 0.000195931; val RMSE 0.002230598; lr 1e-05; 255s
network 5, training 3, epoch 1350: train scaled MSE 0.000194724; val RMSE 0.00223008; lr 1e-05; 256s
network 5, training 3, epoch 1360: train scaled MSE 0.000194589; val RMSE 0.002229697; lr 1e-05; 258s
network 5, training 3, epoch 1370: train scaled MSE 0.000193881; val RMSE 0.002229982; lr 1e-05; 260s
network 5, training 3, epoch 1380: train scaled MSE 0.000193251; val RMSE 0.002229255; lr 1e-05; 262s
network 5, training 3, epoch 1390: train scaled MSE 0.000192779; val RMSE 0.002229124; lr 1e-05; 264s
network 5, training 3, epoch 1400: train scaled MSE 0.000192129; val RMSE 0.002229127; lr 1e-05; 266s
network 5, training 3, epoch 1410: train scaled MSE 0.000193127; val RMSE 0.00222854; lr 1e-05; 267s
network 5, training 3, epoch 1420: train scaled MSE 0.000191394; val RMSE 0.002228597; lr 1e-05; 269s
network 5, training 3, epoch 1430: train scaled MSE 0.00019151; val RMSE 0.00222933; lr 1e-05; 271s
network 5, training 3, epoch 1440: train scaled MSE 0.000190229; val RMSE 0.002228476; lr 1e-05; 273s
network 5, training 3, epoch 1450: train scaled MSE 0.000190168; val RMSE 0.002228374; lr 1e-05; 275s
network 5, training 3, epoch 1460: train scaled MSE 0.000190491; val RMSE 0.002228765; lr 1e-05; 277s
network 5, training 3, epoch 1470: train scaled MSE 0.00018856; val RMSE 0.002228334; lr 1e-05; 278s
network 5, training 3, epoch 1480: train scaled MSE 0.000188725; val RMSE 0.00222788; lr 1e-05; 280s
network 5, training 3, epoch 1490: train scaled MSE 0.000187948; val RMSE 0.002227689; lr 1e-05; 282s
network 5, training 3, epoch 1500: train scaled MSE 0.00018738; val RMSE 0.002227399; lr 1e-05; 284s
network 5, training 3, epoch 1510: train scaled MSE 0.000188461; val RMSE 0.002228526; lr 1e-05; 286s
network 5, training 3, epoch 1520: train scaled MSE 0.000186949; val RMSE 0.002227854; lr 1e-05; 288s
network 5, training 3, epoch 1530: train scaled MSE 0.000186259; val RMSE 0.002227361; lr 1e-05; 290s
network 5, training 3, epoch 1540: train scaled MSE 0.000186838; val RMSE 0.002226261; lr 1e-05; 292s
network 5, training 3, epoch 1550: train scaled MSE 0.000185474; val RMSE 0.002226733; lr 1e-05; 294s
network 5, training 3, epoch 1560: train scaled MSE 0.000185066; val RMSE 0.002226216; lr 1e-05; 296s
network 5, training 3, epoch 1570: train scaled MSE 0.000184647; val RMSE 0.002226142; lr 1e-05; 297s
network 5, training 3, epoch 1580: train scaled MSE 0.000184553; val RMSE 0.00222545; lr 1e-05; 299s
network 5, training 3, epoch 1590: train scaled MSE 0.000183777; val RMSE 0.002225033; lr 1e-05; 301s
network 5, training 3, epoch 1600: train scaled MSE 0.000187287; val RMSE 0.002225383; lr 1e-05; 303s
network 5, training 3, epoch 1610: train scaled MSE 0.000184372; val RMSE 0.002225008; lr 1e-05; 305s
network 5, training 3, epoch 1620: train scaled MSE 0.000183446; val RMSE 0.002224892; lr 1e-05; 306s
network 5, training 3, epoch 1630: train scaled MSE 0.000181743; val RMSE 0.002224503; lr 1e-05; 308s
network 5, training 3, epoch 1640: train scaled MSE 0.000181179; val RMSE 0.002224403; lr 1e-05; 310s
network 5, training 3, epoch 1650: train scaled MSE 0.000180836; val RMSE 0.002224736; lr 1e-05; 312s
network 5, training 3, epoch 1660: train scaled MSE 0.000180349; val RMSE 0.002224018; lr 1e-05; 313s
network 5, training 3, epoch 1670: train scaled MSE 0.000180136; val RMSE 0.002223698; lr 1e-05; 315s
network 5, training 3, epoch 1680: train scaled MSE 0.000179976; val RMSE 0.002223253; lr 1e-05; 317s
network 5, training 3, epoch 1690: train scaled MSE 0.000179232; val RMSE 0.002223583; lr 1e-05; 319s
network 5, training 3, epoch 1700: train scaled MSE 0.000178475; val RMSE 0.002223267; lr 1e-05; 321s
network 5, training 3, epoch 1710: train scaled MSE 0.000179056; val RMSE 0.002223278; lr 1e-05; 322s
network 5, training 3, epoch 1720: train scaled MSE 0.000179154; val RMSE 0.002222719; lr 1e-05; 324s
network 5, training 3, epoch 1730: train scaled MSE 0.000177361; val RMSE 0.002222689; lr 1e-05; 326s
network 5, training 3, epoch 1740: train scaled MSE 0.00017821; val RMSE 0.002221886; lr 1e-05; 328s
network 5, training 3, epoch 1750: train scaled MSE 0.000176466; val RMSE 0.002222421; lr 1e-05; 330s
network 5, training 3, epoch 1760: train scaled MSE 0.000175882; val RMSE 0.002222475; lr 1e-05; 331s
network 5, training 3, epoch 1770: train scaled MSE 0.000178445; val RMSE 0.002222785; lr 1e-05; 333s
Standard Linear Baseline Validation RMSE: 0.003298809

Network seed 5, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,0.4638,"[-1.01%, 1.54%]",0.1205,0.0,0.2322
MLP,0.0033,38.7184,"[27.62%, 48.32%]",0.6259,419.651,0.5167

network 5, training 4, epoch 1: train scaled MSE 0.802528; val RMSE 0.02370511; lr 0.001; 0s
network 5, training 4, epoch 10: train scaled MSE 0.0231243; val RMSE 0.005645468; lr 0.001; 2s
network 5, training 4, epoch 20: train scaled MSE 0.0135088; val RMSE 0.004479023; lr 0.001; 4s
network 5, training 4, epoch 30: train scaled MSE 0.00765919; val RMSE 0.004264723; lr 0.001; 6s
network 5, training 4, epoch 40: train scaled MSE 0.00557949; val RMSE 0.004183929; lr 0.001; 8s
network 5, training 4, epoch 50: train scaled MSE 0.00406533; val RMSE 0.0039181; lr 0.001; 10s
network 5, training 4, epoch 60: train scaled MSE 0.00324623; val RMSE 0.003920223; lr 0.001; 11s
network 5, training 4, epoch 70: train scaled MSE 0.0026641; val RMSE 0.003788249; lr 0.001; 13s
network 5, training 4, epoch 80: train scaled MSE 0.0020256; val RMSE 0.003763402; lr 0.001; 15s
network 5, training 4, epoch 90: train scaled MSE 0.00134672; val RMSE 0.003763918; lr 0.0005; 17s
network 5, training 4, epoch 100: train scaled MSE 0.00118591; val RMSE 0.00368893; lr 0.0005; 19s
network 5, training 4, epoch 110: train scaled MSE 0.00108156; val RMSE 0.003707806; lr 0.0005; 21s
network 5, training 4, epoch 120: train scaled MSE 0.000999381; val RMSE 0.003663912; lr 0.0005; 23s
network 5, training 4, epoch 130: train scaled MSE 0.000886586; val RMSE 0.003652294; lr 0.0005; 25s
network 5, training 4, epoch 140: train scaled MSE 0.000982376; val RMSE 0.003676365; lr 0.0005; 27s
network 5, training 4, epoch 150: train scaled MSE 0.0016694; val RMSE 0.003641165; lr 0.00025; 29s
network 5, training 4, epoch 160: train scaled MSE 0.000632258; val RMSE 0.003624547; lr 0.00025; 31s
network 5, training 4, epoch 170: train scaled MSE 0.00060545; val RMSE 0.003615563; lr 0.00025; 33s
network 5, training 4, epoch 180: train scaled MSE 0.00056567; val RMSE 0.003604206; lr 0.00025; 35s
network 5, training 4, epoch 190: train scaled MSE 0.000556027; val RMSE 0.00359572; lr 0.00025; 37s
network 5, training 4, epoch 200: train scaled MSE 0.000545957; val RMSE 0.003588454; lr 0.00025; 39s
network 5, training 4, epoch 210: train scaled MSE 0.00049293; val RMSE 0.003593867; lr 0.00025; 41s
network 5, training 4, epoch 220: train scaled MSE 0.000447735; val RMSE 0.003576753; lr 0.000125; 43s
network 5, training 4, epoch 230: train scaled MSE 0.000476324; val RMSE 0.003572864; lr 0.000125; 45s
network 5, training 4, epoch 240: train scaled MSE 0.000426098; val RMSE 0.003566131; lr 0.000125; 47s
network 5, training 4, epoch 250: train scaled MSE 0.00042461; val RMSE 0.003559813; lr 0.000125; 49s
network 5, training 4, epoch 260: train scaled MSE 0.000402591; val RMSE 0.003557687; lr 0.000125; 51s
network 5, training 4, epoch 270: train scaled MSE 0.000463725; val RMSE 0.003554354; lr 0.000125; 53s
network 5, training 4, epoch 280: train scaled MSE 0.000377862; val RMSE 0.00355013; lr 0.000125; 55s
network 5, training 4, epoch 290: train scaled MSE 0.000370249; val RMSE 0.003544086; lr 0.000125; 57s
network 5, training 4, epoch 300: train scaled MSE 0.000353601; val RMSE 0.003541226; lr 0.000125; 59s
network 5, training 4, epoch 310: train scaled MSE 0.000413853; val RMSE 0.003540936; lr 0.000125; 61s
network 5, training 4, epoch 320: train scaled MSE 0.000326661; val RMSE 0.003543003; lr 0.000125; 63s
network 5, training 4, epoch 330: train scaled MSE 0.000320703; val RMSE 0.003543368; lr 0.000125; 65s
network 5, training 4, epoch 340: train scaled MSE 0.000332729; val RMSE 0.003534334; lr 0.000125; 67s
network 5, training 4, epoch 350: train scaled MSE 0.000356168; val RMSE 0.003535285; lr 0.000125; 69s
network 5, training 4, epoch 360: train scaled MSE 0.000292823; val RMSE 0.003549406; lr 0.000125; 71s
network 5, training 4, epoch 370: train scaled MSE 0.000286811; val RMSE 0.003527738; lr 0.000125; 73s
network 5, training 4, epoch 380: train scaled MSE 0.000274061; val RMSE 0.00352371; lr 6.25e-05; 75s
network 5, training 4, epoch 390: train scaled MSE 0.000277822; val RMSE 0.003523212; lr 6.25e-05; 77s
network 5, training 4, epoch 400: train scaled MSE 0.000366563; val RMSE 0.003523476; lr 6.25e-05; 79s
network 5, training 4, epoch 410: train scaled MSE 0.000264001; val RMSE 0.003519327; lr 3.125e-05; 81s
network 5, training 4, epoch 420: train scaled MSE 0.000264569; val RMSE 0.003516751; lr 3.125e-05; 83s
network 5, training 4, epoch 430: train scaled MSE 0.000254957; val RMSE 0.003517023; lr 3.125e-05; 85s
network 5, training 4, epoch 440: train scaled MSE 0.000252305; val RMSE 0.003516292; lr 1.5625e-05; 87s
network 5, training 4, epoch 450: train scaled MSE 0.000250905; val RMSE 0.003515824; lr 1.5625e-05; 89s
network 5, training 4, epoch 460: train scaled MSE 0.000250102; val RMSE 0.003515346; lr 1.5625e-05; 91s
network 5, training 4, epoch 470: train scaled MSE 0.000254208; val RMSE 0.003515698; lr 1.5625e-05; 93s
network 5, training 4, epoch 480: train scaled MSE 0.000249675; val RMSE 0.003513106; lr 1.5625e-05; 95s
network 5, training 4, epoch 490: train scaled MSE 0.000246951; val RMSE 0.003512815; lr 1e-05; 97s
network 5, training 4, epoch 500: train scaled MSE 0.000246018; val RMSE 0.003512451; lr 1e-05; 99s
network 5, training 4, epoch 510: train scaled MSE 0.000245895; val RMSE 0.003511775; lr 1e-05; 101s
network 5, training 4, epoch 520: train scaled MSE 0.000246246; val RMSE 0.003512073; lr 1e-05; 103s
network 5, training 4, epoch 530: train scaled MSE 0.000244104; val RMSE 0.003511363; lr 1e-05; 105s
network 5, training 4, epoch 540: train scaled MSE 0.000243518; val RMSE 0.00351106; lr 1e-05; 107s
network 5, training 4, epoch 550: train scaled MSE 0.00024272; val RMSE 0.003510914; lr 1e-05; 109s
network 5, training 4, epoch 560: train scaled MSE 0.000243356; val RMSE 0.003511231; lr 1e-05; 111s
network 5, training 4, epoch 570: train scaled MSE 0.000241425; val RMSE 0.003509696; lr 1e-05; 113s
network 5, training 4, epoch 580: train scaled MSE 0.000240987; val RMSE 0.003509831; lr 1e-05; 115s
network 5, training 4, epoch 590: train scaled MSE 0.000240637; val RMSE 0.003510986; lr 1e-05; 117s
network 5, training 4, epoch 600: train scaled MSE 0.000239707; val RMSE 0.003509944; lr 1e-05; 119s
network 5, training 4, epoch 610: train scaled MSE 0.000238719; val RMSE 0.00350887; lr 1e-05; 121s
network 5, training 4, epoch 620: train scaled MSE 0.000238804; val RMSE 0.003508501; lr 1e-05; 123s
network 5, training 4, epoch 630: train scaled MSE 0.000237467; val RMSE 0.003507378; lr 1e-05; 125s
network 5, training 4, epoch 640: train scaled MSE 0.000236572; val RMSE 0.003507409; lr 1e-05; 127s
network 5, training 4, epoch 650: train scaled MSE 0.00023599; val RMSE 0.003507686; lr 1e-05; 129s
network 5, training 4, epoch 660: train scaled MSE 0.000236916; val RMSE 0.003506253; lr 1e-05; 131s
network 5, training 4, epoch 670: train scaled MSE 0.000235253; val RMSE 0.00350716; lr 1e-05; 134s
network 5, training 4, epoch 680: train scaled MSE 0.000233869; val RMSE 0.003506189; lr 1e-05; 136s
network 5, training 4, epoch 690: train scaled MSE 0.000233612; val RMSE 0.00350547; lr 1e-05; 138s
network 5, training 4, epoch 700: train scaled MSE 0.000233216; val RMSE 0.003505906; lr 1e-05; 140s
network 5, training 4, epoch 710: train scaled MSE 0.000231907; val RMSE 0.003505068; lr 1e-05; 142s
network 5, training 4, epoch 720: train scaled MSE 0.000231068; val RMSE 0.003504364; lr 1e-05; 144s
network 5, training 4, epoch 730: train scaled MSE 0.000234316; val RMSE 0.003504618; lr 1e-05; 146s
network 5, training 4, epoch 740: train scaled MSE 0.000230346; val RMSE 0.003504359; lr 1e-05; 148s
network 5, training 4, epoch 750: train scaled MSE 0.0002297; val RMSE 0.003503531; lr 1e-05; 150s
network 5, training 4, epoch 760: train scaled MSE 0.000228398; val RMSE 0.0035033; lr 1e-05; 152s
network 5, training 4, epoch 770: train scaled MSE 0.000227686; val RMSE 0.003502548; lr 1e-05; 154s
network 5, training 4, epoch 780: train scaled MSE 0.000232599; val RMSE 0.003503057; lr 1e-05; 156s
network 5, training 4, epoch 790: train scaled MSE 0.00022658; val RMSE 0.003502974; lr 1e-05; 158s
network 5, training 4, epoch 800: train scaled MSE 0.000225643; val RMSE 0.003502543; lr 1e-05; 160s
network 5, training 4, epoch 810: train scaled MSE 0.000226767; val RMSE 0.00350265; lr 1e-05; 162s
network 5, training 4, epoch 820: train scaled MSE 0.000224418; val RMSE 0.003502023; lr 1e-05; 164s
network 5, training 4, epoch 830: train scaled MSE 0.000227916; val RMSE 0.003505628; lr 1e-05; 166s
network 5, training 4, epoch 840: train scaled MSE 0.000224386; val RMSE 0.003501275; lr 1e-05; 168s
network 5, training 4, epoch 850: train scaled MSE 0.000223019; val RMSE 0.003501407; lr 1e-05; 170s
network 5, training 4, epoch 860: train scaled MSE 0.000223217; val RMSE 0.003500631; lr 1e-05; 172s
network 5, training 4, epoch 870: train scaled MSE 0.000221689; val RMSE 0.003500434; lr 1e-05; 174s
network 5, training 4, epoch 880: train scaled MSE 0.000220654; val RMSE 0.003500265; lr 1e-05; 176s
network 5, training 4, epoch 890: train scaled MSE 0.000224687; val RMSE 0.003500098; lr 1e-05; 178s
network 5, training 4, epoch 900: train scaled MSE 0.000223706; val RMSE 0.003499547; lr 1e-05; 180s
network 5, training 4, epoch 910: train scaled MSE 0.000219173; val RMSE 0.003499081; lr 1e-05; 182s
network 5, training 4, epoch 920: train scaled MSE 0.000218407; val RMSE 0.003498656; lr 1e-05; 184s
network 5, training 4, epoch 930: train scaled MSE 0.000217972; val RMSE 0.003498211; lr 1e-05; 186s
network 5, training 4, epoch 940: train scaled MSE 0.000217931; val RMSE 0.003498087; lr 1e-05; 188s
network 5, training 4, epoch 950: train scaled MSE 0.000216778; val RMSE 0.003498306; lr 1e-05; 190s
network 5, training 4, epoch 960: train scaled MSE 0.000216131; val RMSE 0.003497886; lr 1e-05; 192s
network 5, training 4, epoch 970: train scaled MSE 0.000217789; val RMSE 0.003497776; lr 1e-05; 195s
network 5, training 4, epoch 980: train scaled MSE 0.000215539; val RMSE 0.003497229; lr 1e-05; 197s
network 5, training 4, epoch 990: train scaled MSE 0.000214448; val RMSE 0.003497285; lr 1e-05; 199s
network 5, training 4, epoch 1000: train scaled MSE 0.000213839; val RMSE 0.003497094; lr 1e-05; 201s
network 5, training 4, epoch 1010: train scaled MSE 0.000213139; val RMSE 0.003496332; lr 1e-05; 203s
network 5, training 4, epoch 1020: train scaled MSE 0.000212504; val RMSE 0.003496521; lr 1e-05; 205s
network 5, training 4, epoch 1030: train scaled MSE 0.00021217; val RMSE 0.003495759; lr 1e-05; 207s
network 5, training 4, epoch 1040: train scaled MSE 0.000211649; val RMSE 0.003495923; lr 1e-05; 210s
network 5, training 4, epoch 1050: train scaled MSE 0.000210608; val RMSE 0.003495291; lr 1e-05; 212s
network 5, training 4, epoch 1060: train scaled MSE 0.000209834; val RMSE 0.003494834; lr 1e-05; 214s
network 5, training 4, epoch 1070: train scaled MSE 0.000209483; val RMSE 0.003494951; lr 1e-05; 216s
network 5, training 4, epoch 1080: train scaled MSE 0.00020891; val RMSE 0.00349468; lr 1e-05; 218s
network 5, training 4, epoch 1090: train scaled MSE 0.000208413; val RMSE 0.003494338; lr 1e-05; 220s
network 5, training 4, epoch 1100: train scaled MSE 0.000207299; val RMSE 0.00349379; lr 1e-05; 223s
network 5, training 4, epoch 1110: train scaled MSE 0.000206972; val RMSE 0.003493414; lr 1e-05; 225s
network 5, training 4, epoch 1120: train scaled MSE 0.000206133; val RMSE 0.003493523; lr 1e-05; 227s
network 5, training 4, epoch 1130: train scaled MSE 0.000210481; val RMSE 0.003493887; lr 1e-05; 229s
network 5, training 4, epoch 1140: train scaled MSE 0.000204966; val RMSE 0.003493206; lr 1e-05; 231s
network 5, training 4, epoch 1150: train scaled MSE 0.000211354; val RMSE 0.003492983; lr 1e-05; 233s
network 5, training 4, epoch 1160: train scaled MSE 0.000203816; val RMSE 0.003492398; lr 1e-05; 235s
network 5, training 4, epoch 1170: train scaled MSE 0.000203299; val RMSE 0.0034923; lr 1e-05; 237s
network 5, training 4, epoch 1180: train scaled MSE 0.000203119; val RMSE 0.003491442; lr 1e-05; 239s
network 5, training 4, epoch 1190: train scaled MSE 0.000202403; val RMSE 0.003491209; lr 1e-05; 242s
network 5, training 4, epoch 1200: train scaled MSE 0.000202067; val RMSE 0.003490925; lr 1e-05; 244s
network 5, training 4, epoch 1210: train scaled MSE 0.000201183; val RMSE 0.003490901; lr 1e-05; 246s
network 5, training 4, epoch 1220: train scaled MSE 0.000200691; val RMSE 0.003490563; lr 1e-05; 248s
network 5, training 4, epoch 1230: train scaled MSE 0.000199966; val RMSE 0.003490864; lr 1e-05; 250s
network 5, training 4, epoch 1240: train scaled MSE 0.000199876; val RMSE 0.003490372; lr 1e-05; 252s
network 5, training 4, epoch 1250: train scaled MSE 0.000199507; val RMSE 0.00348964; lr 1e-05; 254s
network 5, training 4, epoch 1260: train scaled MSE 0.000201088; val RMSE 0.003489646; lr 1e-05; 256s
network 5, training 4, epoch 1270: train scaled MSE 0.000199033; val RMSE 0.003489491; lr 1e-05; 258s
network 5, training 4, epoch 1280: train scaled MSE 0.000197205; val RMSE 0.003489245; lr 1e-05; 260s
network 5, training 4, epoch 1290: train scaled MSE 0.000196695; val RMSE 0.003488982; lr 1e-05; 262s
network 5, training 4, epoch 1300: train scaled MSE 0.000196144; val RMSE 0.003488244; lr 1e-05; 264s
network 5, training 4, epoch 1310: train scaled MSE 0.000195927; val RMSE 0.003487902; lr 1e-05; 266s
network 5, training 4, epoch 1320: train scaled MSE 0.000199158; val RMSE 0.003487473; lr 1e-05; 268s
network 5, training 4, epoch 1330: train scaled MSE 0.000194677; val RMSE 0.00348809; lr 1e-05; 270s
network 5, training 4, epoch 1340: train scaled MSE 0.000193831; val RMSE 0.003487475; lr 1e-05; 272s
network 5, training 4, epoch 1350: train scaled MSE 0.000193344; val RMSE 0.003487566; lr 1e-05; 274s
network 5, training 4, epoch 1360: train scaled MSE 0.000193141; val RMSE 0.003487588; lr 1e-05; 276s
network 5, training 4, epoch 1370: train scaled MSE 0.000192279; val RMSE 0.003486514; lr 1e-05; 278s
network 5, training 4, epoch 1380: train scaled MSE 0.000193364; val RMSE 0.003486747; lr 1e-05; 280s
network 5, training 4, epoch 1390: train scaled MSE 0.000191145; val RMSE 0.003486396; lr 1e-05; 282s
network 5, training 4, epoch 1400: train scaled MSE 0.000190543; val RMSE 0.003486174; lr 1e-05; 284s
network 5, training 4, epoch 1410: train scaled MSE 0.000189994; val RMSE 0.003485577; lr 1e-05; 286s
network 5, training 4, epoch 1420: train scaled MSE 0.00019025; val RMSE 0.003485635; lr 1e-05; 288s
network 5, training 4, epoch 1430: train scaled MSE 0.000189723; val RMSE 0.003485472; lr 1e-05; 290s
network 5, training 4, epoch 1440: train scaled MSE 0.000188707; val RMSE 0.003485142; lr 1e-05; 292s
network 5, training 4, epoch 1450: train scaled MSE 0.000187997; val RMSE 0.003484859; lr 1e-05; 294s
network 5, training 4, epoch 1460: train scaled MSE 0.000186878; val RMSE 0.003484945; lr 1e-05; 296s
network 5, training 4, epoch 1470: train scaled MSE 0.000206926; val RMSE 0.003486371; lr 1e-05; 298s
network 5, training 4, epoch 1480: train scaled MSE 0.000185905; val RMSE 0.003483957; lr 1e-05; 300s
network 5, training 4, epoch 1490: train scaled MSE 0.000185673; val RMSE 0.003484566; lr 1e-05; 302s
network 5, training 4, epoch 1500: train scaled MSE 0.000185092; val RMSE 0.003483596; lr 1e-05; 304s
network 5, training 4, epoch 1510: train scaled MSE 0.000184744; val RMSE 0.003483753; lr 1e-05; 306s
network 5, training 4, epoch 1520: train scaled MSE 0.000184152; val RMSE 0.003483516; lr 1e-05; 308s
network 5, training 4, epoch 1530: train scaled MSE 0.000183822; val RMSE 0.003483207; lr 1e-05; 310s
network 5, training 4, epoch 1540: train scaled MSE 0.000185275; val RMSE 0.00348389; lr 1e-05; 312s
network 5, training 4, epoch 1550: train scaled MSE 0.000182319; val RMSE 0.003482952; lr 1e-05; 314s
network 5, training 4, epoch 1560: train scaled MSE 0.000184235; val RMSE 0.003482566; lr 1e-05; 316s
network 5, training 4, epoch 1570: train scaled MSE 0.000184002; val RMSE 0.003482814; lr 1e-05; 318s
network 5, training 4, epoch 1580: train scaled MSE 0.000186803; val RMSE 0.003482466; lr 1e-05; 320s
network 5, training 4, epoch 1590: train scaled MSE 0.000180781; val RMSE 0.003481461; lr 1e-05; 322s
network 5, training 4, epoch 1600: train scaled MSE 0.000180758; val RMSE 0.003481297; lr 1e-05; 324s
network 5, training 4, epoch 1610: train scaled MSE 0.000179964; val RMSE 0.003481123; lr 1e-05; 326s
network 5, training 4, epoch 1620: train scaled MSE 0.000179588; val RMSE 0.003481779; lr 1e-05; 328s
network 5, training 4, epoch 1630: train scaled MSE 0.000179741; val RMSE 0.003481126; lr 1e-05; 330s
network 5, training 4, epoch 1640: train scaled MSE 0.000178694; val RMSE 0.00348028; lr 1e-05; 332s
network 5, training 4, epoch 1650: train scaled MSE 0.000178307; val RMSE 0.003480661; lr 1e-05; 334s
network 5, training 4, epoch 1660: train scaled MSE 0.00017792; val RMSE 0.003480554; lr 1e-05; 336s
network 5, training 4, epoch 1670: train scaled MSE 0.000179195; val RMSE 0.003479925; lr 1e-05; 338s
network 5, training 4, epoch 1680: train scaled MSE 0.000177012; val RMSE 0.003479661; lr 1e-05; 340s
network 5, training 4, epoch 1690: train scaled MSE 0.000196217; val RMSE 0.003480848; lr 1e-05; 342s
network 5, training 4, epoch 1700: train scaled MSE 0.000176353; val RMSE 0.00347983; lr 1e-05; 344s
network 5, training 4, epoch 1710: train scaled MSE 0.000175991; val RMSE 0.003478764; lr 1e-05; 346s
network 5, training 4, epoch 1720: train scaled MSE 0.000176551; val RMSE 0.0034793; lr 1e-05; 348s
network 5, training 4, epoch 1730: train scaled MSE 0.000176078; val RMSE 0.003479736; lr 1e-05; 350s
network 5, training 4, epoch 1740: train scaled MSE 0.000174641; val RMSE 0.003478494; lr 1e-05; 352s
network 5, training 4, epoch 1750: train scaled MSE 0.000175282; val RMSE 0.003478228; lr 1e-05; 354s
network 5, training 4, epoch 1760: train scaled MSE 0.00017432; val RMSE 0.003479465; lr 1e-05; 356s
network 5, training 4, epoch 1770: train scaled MSE 0.000173474; val RMSE 0.003477675; lr 1e-05; 358s
network 5, training 4, epoch 1780: train scaled MSE 0.000175234; val RMSE 0.003479745; lr 1e-05; 360s
network 5, training 4, epoch 1790: train scaled MSE 0.00017707; val RMSE 0.003479823; lr 1e-05; 362s
network 5, training 4, epoch 1800: train scaled MSE 0.000172385; val RMSE 0.003478583; lr 1e-05; 364s
network 5, training 4, epoch 1810: train scaled MSE 0.000172107; val RMSE 0.003478249; lr 1e-05; 366s
Standard Linear Baseline Validation RMSE: 0.003948106

Network seed 5, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,1.3703,"[0.16%, 2.37%]",0.1325,0.0,0.2728
MLP,0.0031,47.5853,"[36.35%, 57.50%]",0.6901,420.8147,0.5142

network 5, training 5, epoch 1: train scaled MSE 0.793537; val RMSE 0.02358203; lr 0.001; 0s
network 5, training 5, epoch 10: train scaled MSE 0.0244877; val RMSE 0.005607908; lr 0.001; 2s
network 5, training 5, epoch 20: train scaled MSE 0.0107129; val RMSE 0.00412953; lr 0.001; 4s
network 5, training 5, epoch 30: train scaled MSE 0.0072185; val RMSE 0.003623567; lr 0.001; 6s
network 5, training 5, epoch 40: train scaled MSE 0.0211386; val RMSE 0.004202669; lr 0.001; 8s
network 5, training 5, epoch 50: train scaled MSE 0.0044958; val RMSE 0.003283628; lr 0.001; 10s
network 5, training 5, epoch 60: train scaled MSE 0.00372856; val RMSE 0.003350978; lr 0.001; 12s
network 5, training 5, epoch 70: train scaled MSE 0.00263875; val RMSE 0.003214982; lr 0.001; 14s
network 5, training 5, epoch 80: train scaled MSE 0.00206157; val RMSE 0.003153577; lr 0.001; 16s
network 5, training 5, epoch 90: train scaled MSE 0.00255979; val RMSE 0.00326044; lr 0.001; 18s
network 5, training 5, epoch 100: train scaled MSE 0.00154079; val RMSE 0.003102905; lr 0.0005; 20s
network 5, training 5, epoch 110: train scaled MSE 0.00126424; val RMSE 0.003095357; lr 0.0005; 22s
network 5, training 5, epoch 120: train scaled MSE 0.00138959; val RMSE 0.003090226; lr 0.0005; 24s
network 5, training 5, epoch 130: train scaled MSE 0.00103809; val RMSE 0.003055914; lr 0.0005; 26s
network 5, training 5, epoch 140: train scaled MSE 0.000914132; val RMSE 0.003058503; lr 0.0005; 28s
network 5, training 5, epoch 150: train scaled MSE 0.000815373; val RMSE 0.003026516; lr 0.00025; 30s
network 5, training 5, epoch 160: train scaled MSE 0.000720029; val RMSE 0.003022098; lr 0.000125; 32s
network 5, training 5, epoch 170: train scaled MSE 0.000705289; val RMSE 0.003035155; lr 0.000125; 34s
network 5, training 5, epoch 180: train scaled MSE 0.000670079; val RMSE 0.003012856; lr 0.000125; 36s
network 5, training 5, epoch 190: train scaled MSE 0.00064739; val RMSE 0.002999628; lr 0.000125; 38s
network 5, training 5, epoch 200: train scaled MSE 0.000623888; val RMSE 0.00300302; lr 0.000125; 40s
network 5, training 5, epoch 210: train scaled MSE 0.000647641; val RMSE 0.003002536; lr 0.000125; 42s
network 5, training 5, epoch 220: train scaled MSE 0.000571183; val RMSE 0.002987496; lr 6.25e-05; 44s
network 5, training 5, epoch 230: train scaled MSE 0.000577285; val RMSE 0.002986412; lr 6.25e-05; 46s
network 5, training 5, epoch 240: train scaled MSE 0.000577004; val RMSE 0.002987673; lr 6.25e-05; 47s
network 5, training 5, epoch 250: train scaled MSE 0.000538998; val RMSE 0.00298563; lr 6.25e-05; 49s
network 5, training 5, epoch 260: train scaled MSE 0.000525731; val RMSE 0.002980072; lr 6.25e-05; 51s
network 5, training 5, epoch 270: train scaled MSE 0.000519062; val RMSE 0.002976229; lr 6.25e-05; 53s
network 5, training 5, epoch 280: train scaled MSE 0.00051127; val RMSE 0.002973144; lr 6.25e-05; 55s
network 5, training 5, epoch 290: train scaled MSE 0.00049888; val RMSE 0.002974134; lr 6.25e-05; 57s
network 5, training 5, epoch 300: train scaled MSE 0.000490396; val RMSE 0.00297014; lr 6.25e-05; 59s
network 5, training 5, epoch 310: train scaled MSE 0.000474913; val RMSE 0.002967743; lr 3.125e-05; 61s
network 5, training 5, epoch 320: train scaled MSE 0.000468306; val RMSE 0.002966896; lr 3.125e-05; 63s
network 5, training 5, epoch 330: train scaled MSE 0.000464102; val RMSE 0.002962607; lr 3.125e-05; 65s
network 5, training 5, epoch 340: train scaled MSE 0.000458481; val RMSE 0.002964391; lr 3.125e-05; 67s
network 5, training 5, epoch 350: train scaled MSE 0.000454479; val RMSE 0.002962034; lr 3.125e-05; 69s
network 5, training 5, epoch 360: train scaled MSE 0.000459708; val RMSE 0.002962459; lr 3.125e-05; 71s
network 5, training 5, epoch 370: train scaled MSE 0.000444261; val RMSE 0.002960065; lr 3.125e-05; 72s
network 5, training 5, epoch 380: train scaled MSE 0.00043977; val RMSE 0.002961992; lr 3.125e-05; 74s
network 5, training 5, epoch 390: train scaled MSE 0.000446968; val RMSE 0.00296207; lr 3.125e-05; 76s
network 5, training 5, epoch 400: train scaled MSE 0.000431138; val RMSE 0.002957306; lr 1.5625e-05; 78s
network 5, training 5, epoch 410: train scaled MSE 0.000429095; val RMSE 0.002957626; lr 1.5625e-05; 80s
network 5, training 5, epoch 420: train scaled MSE 0.000423694; val RMSE 0.002956633; lr 1e-05; 82s
network 5, training 5, epoch 430: train scaled MSE 0.000419237; val RMSE 0.002955963; lr 1e-05; 84s
network 5, training 5, epoch 440: train scaled MSE 0.000417477; val RMSE 0.00295612; lr 1e-05; 86s
network 5, training 5, epoch 450: train scaled MSE 0.000419253; val RMSE 0.002955945; lr 1e-05; 87s
network 5, training 5, epoch 460: train scaled MSE 0.000415439; val RMSE 0.002955263; lr 1e-05; 89s
network 5, training 5, epoch 470: train scaled MSE 0.000413928; val RMSE 0.002954861; lr 1e-05; 91s
network 5, training 5, epoch 480: train scaled MSE 0.000413935; val RMSE 0.002955582; lr 1e-05; 93s
network 5, training 5, epoch 490: train scaled MSE 0.000410827; val RMSE 0.002954525; lr 1e-05; 95s
network 5, training 5, epoch 500: train scaled MSE 0.00040952; val RMSE 0.002953821; lr 1e-05; 97s
network 5, training 5, epoch 510: train scaled MSE 0.000408358; val RMSE 0.002954135; lr 1e-05; 98s
network 5, training 5, epoch 520: train scaled MSE 0.000406892; val RMSE 0.002953751; lr 1e-05; 100s
network 5, training 5, epoch 530: train scaled MSE 0.000405987; val RMSE 0.002953199; lr 1e-05; 102s
network 5, training 5, epoch 540: train scaled MSE 0.000404819; val RMSE 0.002953207; lr 1e-05; 104s
network 5, training 5, epoch 550: train scaled MSE 0.000402877; val RMSE 0.002953126; lr 1e-05; 106s
network 5, training 5, epoch 560: train scaled MSE 0.000406566; val RMSE 0.002953059; lr 1e-05; 108s
network 5, training 5, epoch 570: train scaled MSE 0.00040057; val RMSE 0.002952169; lr 1e-05; 110s
network 5, training 5, epoch 580: train scaled MSE 0.000399188; val RMSE 0.002952296; lr 1e-05; 112s
network 5, training 5, epoch 590: train scaled MSE 0.000404982; val RMSE 0.00295368; lr 1e-05; 114s
network 5, training 5, epoch 600: train scaled MSE 0.000396498; val RMSE 0.002952266; lr 1e-05; 116s
network 5, training 5, epoch 610: train scaled MSE 0.000395455; val RMSE 0.002950978; lr 1e-05; 118s
network 5, training 5, epoch 620: train scaled MSE 0.000395469; val RMSE 0.002947098; lr 1e-05; 120s
network 5, training 5, epoch 630: train scaled MSE 0.000392767; val RMSE 0.002947812; lr 1e-05; 122s
network 5, training 5, epoch 640: train scaled MSE 0.000391666; val RMSE 0.002948068; lr 1e-05; 124s
network 5, training 5, epoch 650: train scaled MSE 0.00039045; val RMSE 0.002948099; lr 1e-05; 126s
Standard Linear Baseline Validation RMSE: 0.004403519

Network seed 5, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0040,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0040,1.2593,"[-0.16%, 2.39%]",0.1394,0.0,0.2298
MLP,0.0031,41.7959,"[29.50%, 52.16%]",0.6490,365.7171,0.3171

network 5, training 6, epoch 1: train scaled MSE 0.80102; val RMSE 0.02392551; lr 0.001; 0s
network 5, training 6, epoch 10: train scaled MSE 0.0218527; val RMSE 0.005457883; lr 0.001; 2s
network 5, training 6, epoch 20: train scaled MSE 0.0098842; val RMSE 0.004056973; lr 0.001; 4s
network 5, training 6, epoch 30: train scaled MSE 0.00686682; val RMSE 0.004826303; lr 0.001; 6s
network 5, training 6, epoch 40: train scaled MSE 0.00533275; val RMSE 0.004467133; lr 0.001; 8s
network 5, training 6, epoch 50: train scaled MSE 0.00503148; val RMSE 0.003890463; lr 0.001; 10s
network 5, training 6, epoch 60: train scaled MSE 0.00274066; val RMSE 0.003697007; lr 0.001; 12s
network 5, training 6, epoch 70: train scaled MSE 0.00226878; val RMSE 0.003585722; lr 0.001; 14s
network 5, training 6, epoch 80: train scaled MSE 0.00186655; val RMSE 0.003560793; lr 0.001; 16s
network 5, training 6, epoch 90: train scaled MSE 0.0018209; val RMSE 0.003518231; lr 0.001; 18s
network 5, training 6, epoch 100: train scaled MSE 0.00134474; val RMSE 0.00353464; lr 0.001; 20s
network 5, training 6, epoch 110: train scaled MSE 0.00106551; val RMSE 0.003504938; lr 0.001; 22s
network 5, training 6, epoch 120: train scaled MSE 0.000930692; val RMSE 0.003468561; lr 0.0005; 24s
network 5, training 6, epoch 130: train scaled MSE 0.000764156; val RMSE 0.003441628; lr 0.0005; 26s
network 5, training 6, epoch 140: train scaled MSE 0.000723839; val RMSE 0.003479421; lr 0.0005; 28s
network 5, training 6, epoch 150: train scaled MSE 0.000709863; val RMSE 0.003451196; lr 0.0005; 30s
network 5, training 6, epoch 160: train scaled MSE 0.000597269; val RMSE 0.003662697; lr 0.0005; 32s
network 5, training 6, epoch 170: train scaled MSE 0.00055798; val RMSE 0.003434228; lr 0.0005; 34s
network 5, training 6, epoch 180: train scaled MSE 0.000470917; val RMSE 0.003410036; lr 0.00025; 36s
network 5, training 6, epoch 190: train scaled MSE 0.000450206; val RMSE 0.003409891; lr 0.00025; 38s
network 5, training 6, epoch 200: train scaled MSE 0.000424994; val RMSE 0.003420697; lr 0.00025; 39s
network 5, training 6, epoch 210: train scaled MSE 0.000402768; val RMSE 0.003401565; lr 0.00025; 41s
network 5, training 6, epoch 220: train scaled MSE 0.000514463; val RMSE 0.003431892; lr 0.00025; 43s
network 5, training 6, epoch 230: train scaled MSE 0.000352464; val RMSE 0.003397307; lr 0.000125; 45s
network 5, training 6, epoch 240: train scaled MSE 0.000334715; val RMSE 0.003394444; lr 0.000125; 47s
network 5, training 6, epoch 250: train scaled MSE 0.000339996; val RMSE 0.003393188; lr 6.25e-05; 49s
network 5, training 6, epoch 260: train scaled MSE 0.000310759; val RMSE 0.003391331; lr 6.25e-05; 51s
network 5, training 6, epoch 270: train scaled MSE 0.000304187; val RMSE 0.003388873; lr 3.125e-05; 53s
network 5, training 6, epoch 280: train scaled MSE 0.000309755; val RMSE 0.003389224; lr 1.5625e-05; 55s
network 5, training 6, epoch 290: train scaled MSE 0.00029767; val RMSE 0.003387365; lr 1.5625e-05; 57s
network 5, training 6, epoch 300: train scaled MSE 0.000294556; val RMSE 0.003387515; lr 1.5625e-05; 59s
network 5, training 6, epoch 310: train scaled MSE 0.000296982; val RMSE 0.003387157; lr 1.5625e-05; 61s
network 5, training 6, epoch 320: train scaled MSE 0.000290864; val RMSE 0.003387041; lr 1e-05; 63s
network 5, training 6, epoch 330: train scaled MSE 0.000308604; val RMSE 0.003389568; lr 1e-05; 65s
network 5, training 6, epoch 340: train scaled MSE 0.000307642; val RMSE 0.00338829; lr 1e-05; 67s
Standard Linear Baseline Validation RMSE: 0.004156077

Network seed 5, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0044,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0044,1.3957,"[0.34%, 2.25%]",0.1296,0.0,0.2938
MLP,0.0035,36.6249,"[24.41%, 47.68%]",0.6119,372.2849,0.3252

network 5, training 7, epoch 1: train scaled MSE 0.802441; val RMSE 0.02423563; lr 0.001; 0s
network 5, training 7, epoch 10: train scaled MSE 0.0238531; val RMSE 0.005769702; lr 0.001; 2s
network 5, training 7, epoch 20: train scaled MSE 0.00999926; val RMSE 0.004176604; lr 0.001; 4s
network 5, training 7, epoch 30: train scaled MSE 0.00674161; val RMSE 0.003844821; lr 0.001; 6s
network 5, training 7, epoch 40: train scaled MSE 0.00446441; val RMSE 0.003544405; lr 0.001; 8s
network 5, training 7, epoch 50: train scaled MSE 0.00328981; val RMSE 0.003484734; lr 0.001; 10s
network 5, training 7, epoch 60: train scaled MSE 0.0025642; val RMSE 0.003409315; lr 0.001; 12s
network 5, training 7, epoch 70: train scaled MSE 0.00235591; val RMSE 0.003323044; lr 0.001; 14s
network 5, training 7, epoch 80: train scaled MSE 0.00182174; val RMSE 0.003334979; lr 0.001; 16s
network 5, training 7, epoch 90: train scaled MSE 0.00141462; val RMSE 0.003325164; lr 0.001; 18s
network 5, training 7, epoch 100: train scaled MSE 0.00165238; val RMSE 0.003371762; lr 0.001; 20s
network 5, training 7, epoch 110: train scaled MSE 0.00118543; val RMSE 0.00329064; lr 0.0005; 22s
network 5, training 7, epoch 120: train scaled MSE 0.000872986; val RMSE 0.003279416; lr 0.0005; 24s
network 5, training 7, epoch 130: train scaled MSE 0.000756097; val RMSE 0.00321484; lr 0.0005; 26s
network 5, training 7, epoch 140: train scaled MSE 0.000678565; val RMSE 0.00322477; lr 0.0005; 28s
network 5, training 7, epoch 150: train scaled MSE 0.00325164; val RMSE 0.003307624; lr 0.0005; 30s
network 5, training 7, epoch 160: train scaled MSE 0.000578365; val RMSE 0.003233542; lr 0.00025; 32s
network 5, training 7, epoch 170: train scaled MSE 0.000523188; val RMSE 0.003219576; lr 0.000125; 34s
network 5, training 7, epoch 180: train scaled MSE 0.000500225; val RMSE 0.003213683; lr 6.25e-05; 36s
Standard Linear Baseline Validation RMSE: 0.003693929

Network seed 5, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0040,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0040,0.3294,"[-1.29%, 1.61%]",0.1237,0.0,0.1897
MLP,0.0032,38.6163,"[28.83%, 46.98%]",0.6237,404.3452,0.0211

network 5, training 8, epoch 1: train scaled MSE 0.791133; val RMSE 0.02360592; lr 0.001; 0s
network 5, training 8, epoch 10: train scaled MSE 0.0237169; val RMSE 0.005588746; lr 0.001; 2s
network 5, training 8, epoch 20: train scaled MSE 0.0120167; val RMSE 0.004229166; lr 0.001; 4s
network 5, training 8, epoch 30: train scaled MSE 0.0151557; val RMSE 0.00391668; lr 0.001; 6s
network 5, training 8, epoch 40: train scaled MSE 0.00582317; val RMSE 0.003657699; lr 0.001; 8s
network 5, training 8, epoch 50: train scaled MSE 0.00429871; val RMSE 0.003555338; lr 0.001; 10s
network 5, training 8, epoch 60: train scaled MSE 0.00311053; val RMSE 0.003499847; lr 0.001; 12s
network 5, training 8, epoch 70: train scaled MSE 0.0026043; val RMSE 0.003411147; lr 0.001; 14s
network 5, training 8, epoch 80: train scaled MSE 0.00175772; val RMSE 0.003401714; lr 0.0005; 16s
network 5, training 8, epoch 90: train scaled MSE 0.00158534; val RMSE 0.003305134; lr 0.0005; 18s
network 5, training 8, epoch 100: train scaled MSE 0.00138024; val RMSE 0.00327982; lr 0.00025; 20s
network 5, training 8, epoch 110: train scaled MSE 0.00129853; val RMSE 0.003269439; lr 0.00025; 22s
network 5, training 8, epoch 120: train scaled MSE 0.00135276; val RMSE 0.003280675; lr 0.00025; 24s
network 5, training 8, epoch 130: train scaled MSE 0.00107115; val RMSE 0.003255164; lr 0.000125; 26s
network 5, training 8, epoch 140: train scaled MSE 0.00102961; val RMSE 0.003252685; lr 0.000125; 28s
network 5, training 8, epoch 150: train scaled MSE 0.000984294; val RMSE 0.003246625; lr 0.000125; 30s
network 5, training 8, epoch 160: train scaled MSE 0.000943775; val RMSE 0.003251944; lr 0.000125; 32s
network 5, training 8, epoch 170: train scaled MSE 0.000900741; val RMSE 0.00324594; lr 0.000125; 34s
network 5, training 8, epoch 180: train scaled MSE 0.000860939; val RMSE 0.00323889; lr 0.000125; 36s
network 5, training 8, epoch 190: train scaled MSE 0.000856534; val RMSE 0.003241641; lr 0.000125; 38s
network 5, training 8, epoch 200: train scaled MSE 0.000794854; val RMSE 0.003222713; lr 0.000125; 40s
network 5, training 8, epoch 210: train scaled MSE 0.000754016; val RMSE 0.003228898; lr 0.000125; 42s
network 5, training 8, epoch 220: train scaled MSE 0.000740164; val RMSE 0.003218163; lr 0.000125; 44s
network 5, training 8, epoch 230: train scaled MSE 0.000694466; val RMSE 0.003214616; lr 6.25e-05; 46s
network 5, training 8, epoch 240: train scaled MSE 0.000677561; val RMSE 0.003210835; lr 6.25e-05; 48s
network 5, training 8, epoch 250: train scaled MSE 0.000667702; val RMSE 0.003208043; lr 6.25e-05; 50s
network 5, training 8, epoch 260: train scaled MSE 0.000645914; val RMSE 0.003207558; lr 3.125e-05; 52s
network 5, training 8, epoch 270: train scaled MSE 0.000639007; val RMSE 0.003205619; lr 3.125e-05; 54s
network 5, training 8, epoch 280: train scaled MSE 0.000632985; val RMSE 0.003203336; lr 3.125e-05; 56s
network 5, training 8, epoch 290: train scaled MSE 0.000626617; val RMSE 0.00320347; lr 3.125e-05; 58s
network 5, training 8, epoch 300: train scaled MSE 0.000621922; val RMSE 0.003206101; lr 3.125e-05; 60s
network 5, training 8, epoch 310: train scaled MSE 0.000609609; val RMSE 0.003201575; lr 1.5625e-05; 62s
network 5, training 8, epoch 320: train scaled MSE 0.000608109; val RMSE 0.003200777; lr 1.5625e-05; 64s
network 5, training 8, epoch 330: train scaled MSE 0.000601603; val RMSE 0.003201462; lr 1.5625e-05; 66s
network 5, training 8, epoch 340: train scaled MSE 0.000599733; val RMSE 0.003200025; lr 1.5625e-05; 68s
network 5, training 8, epoch 350: train scaled MSE 0.000609275; val RMSE 0.003197549; lr 1.5625e-05; 70s
network 5, training 8, epoch 360: train scaled MSE 0.000636941; val RMSE 0.003204573; lr 1.5625e-05; 71s
network 5, training 8, epoch 370: train scaled MSE 0.000591902; val RMSE 0.003199067; lr 1e-05; 73s
network 5, training 8, epoch 380: train scaled MSE 0.000587893; val RMSE 0.003198232; lr 1e-05; 75s
network 5, training 8, epoch 390: train scaled MSE 0.000586782; val RMSE 0.003197186; lr 1e-05; 77s
Standard Linear Baseline Validation RMSE: 0.004377986

Network seed 5, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0042,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0042,1.5917,"[0.47%, 2.49%]",0.1369,0.0,0.2551
MLP,0.0033,37.9096,"[25.55%, 50.71%]",0.6196,352.6671,0.1902

network 5, training 9, epoch 1: train scaled MSE 0.801092; val RMSE 0.0238184; lr 0.001; 0s
network 5, training 9, epoch 10: train scaled MSE 0.0403748; val RMSE 0.005367033; lr 0.001; 2s
network 5, training 9, epoch 20: train scaled MSE 0.0106664; val RMSE 0.003368559; lr 0.001; 4s
network 5, training 9, epoch 30: train scaled MSE 0.00721934; val RMSE 0.003008644; lr 0.001; 6s
network 5, training 9, epoch 40: train scaled MSE 0.00495876; val RMSE 0.002913738; lr 0.001; 8s
network 5, training 9, epoch 50: train scaled MSE 0.00350827; val RMSE 0.002928057; lr 0.001; 10s
network 5, training 9, epoch 60: train scaled MSE 0.00305433; val RMSE 0.002859427; lr 0.001; 12s
network 5, training 9, epoch 70: train scaled MSE 0.00265968; val RMSE 0.002863525; lr 0.001; 13s
network 5, training 9, epoch 80: train scaled MSE 0.00179684; val RMSE 0.002823116; lr 0.001; 15s
network 5, training 9, epoch 90: train scaled MSE 0.00360055; val RMSE 0.002817467; lr 0.001; 17s
network 5, training 9, epoch 100: train scaled MSE 0.00144434; val RMSE 0.00267736; lr 0.001; 19s
network 5, training 9, epoch 110: train scaled MSE 0.00150016; val RMSE 0.002796827; lr 0.001; 21s
network 5, training 9, epoch 120: train scaled MSE 0.000949552; val RMSE 0.002597253; lr 0.001; 23s
network 5, training 9, epoch 130: train scaled MSE 0.000972045; val RMSE 0.002609524; lr 0.001; 24s
network 5, training 9, epoch 140: train scaled MSE 0.000630019; val RMSE 0.002535427; lr 0.0005; 26s
network 5, training 9, epoch 150: train scaled MSE 0.000587359; val RMSE 0.002528472; lr 0.0005; 28s
network 5, training 9, epoch 160: train scaled MSE 0.000572764; val RMSE 0.00254133; lr 0.0005; 30s
network 5, training 9, epoch 170: train scaled MSE 0.000460022; val RMSE 0.002505563; lr 0.00025; 32s
network 5, training 9, epoch 180: train scaled MSE 0.000481045; val RMSE 0.00249242; lr 0.00025; 34s
network 5, training 9, epoch 190: train scaled MSE 0.000501552; val RMSE 0.002498515; lr 0.00025; 36s
network 5, training 9, epoch 200: train scaled MSE 0.00038986; val RMSE 0.002484647; lr 0.000125; 38s
network 5, training 9, epoch 210: train scaled MSE 0.000385459; val RMSE 0.002483201; lr 0.000125; 39s
network 5, training 9, epoch 220: train scaled MSE 0.000428103; val RMSE 0.00248021; lr 0.000125; 41s
network 5, training 9, epoch 230: train scaled MSE 0.000358122; val RMSE 0.002476362; lr 0.000125; 43s
network 5, training 9, epoch 240: train scaled MSE 0.00034692; val RMSE 0.002475347; lr 6.25e-05; 45s
network 5, training 9, epoch 250: train scaled MSE 0.000391105; val RMSE 0.002479076; lr 6.25e-05; 46s
network 5, training 9, epoch 260: train scaled MSE 0.000332559; val RMSE 0.002473712; lr 6.25e-05; 48s
network 5, training 9, epoch 270: train scaled MSE 0.000361386; val RMSE 0.002474876; lr 6.25e-05; 50s
network 5, training 9, epoch 280: train scaled MSE 0.00032158; val RMSE 0.002474245; lr 6.25e-05; 52s
network 5, training 9, epoch 290: train scaled MSE 0.000316723; val RMSE 0.002466138; lr 6.25e-05; 54s
network 5, training 9, epoch 300: train scaled MSE 0.00031373; val RMSE 0.002467443; lr 6.25e-05; 56s
network 5, training 9, epoch 310: train scaled MSE 0.000307143; val RMSE 0.002469732; lr 6.25e-05; 57s
network 5, training 9, epoch 320: train scaled MSE 0.000299339; val RMSE 0.002464007; lr 3.125e-05; 59s
network 5, training 9, epoch 330: train scaled MSE 0.000296431; val RMSE 0.002463241; lr 3.125e-05; 61s
network 5, training 9, epoch 340: train scaled MSE 0.000296877; val RMSE 0.00246337; lr 3.125e-05; 63s
network 5, training 9, epoch 350: train scaled MSE 0.000289655; val RMSE 0.002463282; lr 3.125e-05; 65s
network 5, training 9, epoch 360: train scaled MSE 0.000286195; val RMSE 0.002462177; lr 1.5625e-05; 66s
network 5, training 9, epoch 370: train scaled MSE 0.000284654; val RMSE 0.002461757; lr 1e-05; 68s
network 5, training 9, epoch 380: train scaled MSE 0.000282239; val RMSE 0.002461293; lr 1e-05; 70s
network 5, training 9, epoch 390: train scaled MSE 0.000281799; val RMSE 0.002460995; lr 1e-05; 72s
network 5, training 9, epoch 400: train scaled MSE 0.000280344; val RMSE 0.002460604; lr 1e-05; 73s
network 5, training 9, epoch 410: train scaled MSE 0.000279548; val RMSE 0.002461021; lr 1e-05; 75s
network 5, training 9, epoch 420: train scaled MSE 0.000280411; val RMSE 0.002460765; lr 1e-05; 77s
network 5, training 9, epoch 430: train scaled MSE 0.000278271; val RMSE 0.002460762; lr 1e-05; 79s
network 5, training 9, epoch 440: train scaled MSE 0.000277765; val RMSE 0.002460091; lr 1e-05; 80s
network 5, training 9, epoch 450: train scaled MSE 0.000275792; val RMSE 0.002460134; lr 1e-05; 82s
network 5, training 9, epoch 460: train scaled MSE 0.000278804; val RMSE 0.002459287; lr 1e-05; 84s
network 5, training 9, epoch 470: train scaled MSE 0.000274543; val RMSE 0.002458983; lr 1e-05; 86s
network 5, training 9, epoch 480: train scaled MSE 0.000273476; val RMSE 0.002458306; lr 1e-05; 87s
network 5, training 9, epoch 490: train scaled MSE 0.00027358; val RMSE 0.002458609; lr 1e-05; 89s
network 5, training 9, epoch 500: train scaled MSE 0.000272512; val RMSE 0.002458372; lr 1e-05; 91s
network 5, training 9, epoch 510: train scaled MSE 0.000271391; val RMSE 0.002458803; lr 1e-05; 93s
network 5, training 9, epoch 520: train scaled MSE 0.00027263; val RMSE 0.002457691; lr 1e-05; 94s
network 5, training 9, epoch 530: train scaled MSE 0.000270321; val RMSE 0.002458026; lr 1e-05; 96s
network 5, training 9, epoch 540: train scaled MSE 0.000269431; val RMSE 0.002457555; lr 1e-05; 98s
network 5, training 9, epoch 550: train scaled MSE 0.000268004; val RMSE 0.002457163; lr 1e-05; 100s
network 5, training 9, epoch 560: train scaled MSE 0.000266907; val RMSE 0.00245683; lr 1e-05; 101s
network 5, training 9, epoch 570: train scaled MSE 0.000266004; val RMSE 0.002456797; lr 1e-05; 103s
network 5, training 9, epoch 580: train scaled MSE 0.000264944; val RMSE 0.002456596; lr 1e-05; 105s
network 5, training 9, epoch 590: train scaled MSE 0.000264144; val RMSE 0.002455933; lr 1e-05; 107s
network 5, training 9, epoch 600: train scaled MSE 0.00026347; val RMSE 0.002456107; lr 1e-05; 108s
network 5, training 9, epoch 610: train scaled MSE 0.000262591; val RMSE 0.002455676; lr 1e-05; 110s
network 5, training 9, epoch 620: train scaled MSE 0.000261149; val RMSE 0.00245506; lr 1e-05; 112s
network 5, training 9, epoch 630: train scaled MSE 0.00026088; val RMSE 0.002454812; lr 1e-05; 114s
network 5, training 9, epoch 640: train scaled MSE 0.000260232; val RMSE 0.002455192; lr 1e-05; 116s
network 5, training 9, epoch 650: train scaled MSE 0.000258387; val RMSE 0.002454694; lr 1e-05; 117s
network 5, training 9, epoch 660: train scaled MSE 0.000257412; val RMSE 0.002454632; lr 1e-05; 119s
network 5, training 9, epoch 670: train scaled MSE 0.000257303; val RMSE 0.002454087; lr 1e-05; 121s
network 5, training 9, epoch 680: train scaled MSE 0.00025729; val RMSE 0.002454402; lr 1e-05; 122s
network 5, training 9, epoch 690: train scaled MSE 0.000256471; val RMSE 0.002454039; lr 1e-05; 124s
network 5, training 9, epoch 700: train scaled MSE 0.000254679; val RMSE 0.002454262; lr 1e-05; 126s
network 5, training 9, epoch 710: train scaled MSE 0.000256069; val RMSE 0.002453718; lr 1e-05; 128s
network 5, training 9, epoch 720: train scaled MSE 0.000252952; val RMSE 0.002453547; lr 1e-05; 129s
network 5, training 9, epoch 730: train scaled MSE 0.000252173; val RMSE 0.002453174; lr 1e-05; 131s
network 5, training 9, epoch 740: train scaled MSE 0.000254392; val RMSE 0.00245302; lr 1e-05; 133s
network 5, training 9, epoch 750: train scaled MSE 0.000250777; val RMSE 0.00245295; lr 1e-05; 135s
network 5, training 9, epoch 760: train scaled MSE 0.000250057; val RMSE 0.002452479; lr 1e-05; 137s
network 5, training 9, epoch 770: train scaled MSE 0.000249063; val RMSE 0.002451727; lr 1e-05; 138s
network 5, training 9, epoch 780: train scaled MSE 0.000248227; val RMSE 0.002452139; lr 1e-05; 140s
network 5, training 9, epoch 790: train scaled MSE 0.0002479; val RMSE 0.002451161; lr 1e-05; 142s
network 5, training 9, epoch 800: train scaled MSE 0.000246937; val RMSE 0.002451758; lr 1e-05; 144s
network 5, training 9, epoch 810: train scaled MSE 0.000245768; val RMSE 0.002450988; lr 1e-05; 145s
network 5, training 9, epoch 820: train scaled MSE 0.000245014; val RMSE 0.002451507; lr 1e-05; 147s
network 5, training 9, epoch 830: train scaled MSE 0.000244235; val RMSE 0.002450978; lr 1e-05; 149s
network 5, training 9, epoch 840: train scaled MSE 0.000244035; val RMSE 0.002450635; lr 1e-05; 150s
network 5, training 9, epoch 850: train scaled MSE 0.000245296; val RMSE 0.002451125; lr 1e-05; 152s
network 5, training 9, epoch 860: train scaled MSE 0.000242918; val RMSE 0.002450174; lr 1e-05; 154s
network 5, training 9, epoch 870: train scaled MSE 0.000240835; val RMSE 0.002449985; lr 1e-05; 155s
network 5, training 9, epoch 880: train scaled MSE 0.000243073; val RMSE 0.002450418; lr 1e-05; 157s
network 5, training 9, epoch 890: train scaled MSE 0.000239457; val RMSE 0.002449723; lr 1e-05; 159s
network 5, training 9, epoch 900: train scaled MSE 0.000241162; val RMSE 0.002449746; lr 1e-05; 161s
network 5, training 9, epoch 910: train scaled MSE 0.000238283; val RMSE 0.002449302; lr 1e-05; 162s
network 5, training 9, epoch 920: train scaled MSE 0.000237686; val RMSE 0.00244894; lr 1e-05; 164s
network 5, training 9, epoch 930: train scaled MSE 0.000236611; val RMSE 0.00244816; lr 1e-05; 166s
network 5, training 9, epoch 940: train scaled MSE 0.000237015; val RMSE 0.002448404; lr 1e-05; 168s
network 5, training 9, epoch 950: train scaled MSE 0.00023551; val RMSE 0.002448637; lr 1e-05; 169s
network 5, training 9, epoch 960: train scaled MSE 0.000234699; val RMSE 0.002448299; lr 1e-05; 171s
network 5, training 9, epoch 970: train scaled MSE 0.000235577; val RMSE 0.002448191; lr 1e-05; 172s
network 5, training 9, epoch 980: train scaled MSE 0.000234278; val RMSE 0.002448003; lr 1e-05; 174s
network 5, training 9, epoch 990: train scaled MSE 0.000240948; val RMSE 0.002448316; lr 1e-05; 176s
Standard Linear Baseline Validation RMSE: 0.003223778

Network seed 5, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0043,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0043,1.4795,"[0.16%, 2.53%]",0.1368,0.0,0.2572
MLP,0.0033,41.0234,"[29.34%, 51.33%]",0.6435,370.5026,0.4021

Network 6: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   14.0s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   14.1s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   14.3s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   14.3s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   14.5s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   14.7s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   14.8s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   15.0s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   15.2s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   15.5s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   15.8s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   15.9s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   16.2s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   16.3s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   16.5s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   16.8s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   17.0s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   17.3s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   17.6s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   17.9s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   18.2s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   18.4s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   18.7s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   19.2s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   19.5s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   19.9s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   20.3s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   20.7s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   21.0s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   21.4s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   21.8s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   22.2s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   22.6s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   23.1s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   23.5s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   24.0s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   24.4s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   24.8s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   25.3s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   25.8s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   26.3s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   26.8s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   27.3s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   27.9s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   28.4s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   28.9s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   29.5s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   30.2s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   30.7s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   31.2s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   31.8s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   32.4s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   33.1s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   33.5s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   34.3s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   34.9s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   35.6s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   36.2s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   36.9s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   37.6s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   38.2s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   38.9s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   39.5s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   40.4s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   41.2s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   41.9s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   42.7s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   43.5s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   44.4s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   45.1s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   46.0s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   46.9s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   47.8s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   48.7s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   49.5s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   50.3s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   51.1s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   51.9s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   52.8s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   53.6s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   54.5s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   55.5s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   56.5s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   57.3s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:   58.2s
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:   59.3s
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.6min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.7min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.8min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.9min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  5.0min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  5.1min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  5.1min finished

network 6, training 0, epoch 1: train scaled MSE 0.858936; val RMSE 0.02614199; lr 0.001; 0s
network 6, training 0, epoch 10: train scaled MSE 0.0239882; val RMSE 0.005121908; lr 0.001; 2s
network 6, training 0, epoch 20: train scaled MSE 0.0135779; val RMSE 0.00347442; lr 0.001; 4s
network 6, training 0, epoch 30: train scaled MSE 0.0104951; val RMSE 0.003285845; lr 0.001; 6s
network 6, training 0, epoch 40: train scaled MSE 0.00601795; val RMSE 0.003083636; lr 0.001; 7s
network 6, training 0, epoch 50: train scaled MSE 0.00481172; val RMSE 0.002965045; lr 0.001; 9s
network 6, training 0, epoch 60: train scaled MSE 0.00429385; val RMSE 0.002890312; lr 0.001; 11s
network 6, training 0, epoch 70: train scaled MSE 0.00323814; val RMSE 0.002941368; lr 0.001; 13s
network 6, training 0, epoch 80: train scaled MSE 0.00297834; val RMSE 0.002821687; lr 0.001; 15s
network 6, training 0, epoch 90: train scaled MSE 0.00229346; val RMSE 0.002779543; lr 0.001; 17s
network 6, training 0, epoch 100: train scaled MSE 0.00210081; val RMSE 0.00277854; lr 0.001; 19s
network 6, training 0, epoch 110: train scaled MSE 0.00198438; val RMSE 0.002846062; lr 0.0005; 21s
network 6, training 0, epoch 120: train scaled MSE 0.0014047; val RMSE 0.002798686; lr 0.0005; 23s
network 6, training 0, epoch 130: train scaled MSE 0.00123286; val RMSE 0.002788611; lr 0.00025; 25s
network 6, training 0, epoch 140: train scaled MSE 0.00115945; val RMSE 0.002727011; lr 0.00025; 27s
network 6, training 0, epoch 150: train scaled MSE 0.00110453; val RMSE 0.002710854; lr 0.00025; 29s
network 6, training 0, epoch 160: train scaled MSE 0.00107774; val RMSE 0.002683045; lr 0.00025; 31s
network 6, training 0, epoch 170: train scaled MSE 0.000984527; val RMSE 0.002707726; lr 0.00025; 33s
network 6, training 0, epoch 180: train scaled MSE 0.000939067; val RMSE 0.002661995; lr 0.00025; 35s
network 6, training 0, epoch 190: train scaled MSE 0.00088118; val RMSE 0.00265863; lr 0.00025; 37s
network 6, training 0, epoch 200: train scaled MSE 0.0008733; val RMSE 0.002645332; lr 0.00025; 39s
network 6, training 0, epoch 210: train scaled MSE 0.000784757; val RMSE 0.002637209; lr 0.00025; 41s
network 6, training 0, epoch 220: train scaled MSE 0.000762186; val RMSE 0.002756704; lr 0.00025; 43s
network 6, training 0, epoch 230: train scaled MSE 0.000794493; val RMSE 0.002647566; lr 0.00025; 45s
network 6, training 0, epoch 240: train scaled MSE 0.000696185; val RMSE 0.002648377; lr 0.00025; 47s
network 6, training 0, epoch 250: train scaled MSE 0.00207587; val RMSE 0.002684248; lr 0.00025; 48s
network 6, training 0, epoch 260: train scaled MSE 0.000633508; val RMSE 0.002606091; lr 0.00025; 50s
network 6, training 0, epoch 270: train scaled MSE 0.000592253; val RMSE 0.002604436; lr 0.00025; 52s
network 6, training 0, epoch 280: train scaled MSE 0.000690561; val RMSE 0.002710393; lr 0.00025; 54s
network 6, training 0, epoch 290: train scaled MSE 0.000513489; val RMSE 0.002592845; lr 0.000125; 56s
network 6, training 0, epoch 300: train scaled MSE 0.000499112; val RMSE 0.002591228; lr 0.000125; 58s
network 6, training 0, epoch 310: train scaled MSE 0.000494746; val RMSE 0.002588782; lr 0.000125; 60s
network 6, training 0, epoch 320: train scaled MSE 0.000528489; val RMSE 0.002589233; lr 0.000125; 62s
network 6, training 0, epoch 330: train scaled MSE 0.000473699; val RMSE 0.002584591; lr 0.000125; 64s
network 6, training 0, epoch 340: train scaled MSE 0.000455223; val RMSE 0.002590788; lr 0.000125; 66s
network 6, training 0, epoch 350: train scaled MSE 0.00044719; val RMSE 0.002584859; lr 0.000125; 68s
network 6, training 0, epoch 360: train scaled MSE 0.000472914; val RMSE 0.002586117; lr 6.25e-05; 70s
network 6, training 0, epoch 370: train scaled MSE 0.00046002; val RMSE 0.002578319; lr 6.25e-05; 73s
network 6, training 0, epoch 380: train scaled MSE 0.000411364; val RMSE 0.002579544; lr 6.25e-05; 74s
network 6, training 0, epoch 390: train scaled MSE 0.000404169; val RMSE 0.002574787; lr 6.25e-05; 76s
network 6, training 0, epoch 400: train scaled MSE 0.000405371; val RMSE 0.002582697; lr 6.25e-05; 78s
network 6, training 0, epoch 410: train scaled MSE 0.000398097; val RMSE 0.00257503; lr 3.125e-05; 80s
network 6, training 0, epoch 420: train scaled MSE 0.000385275; val RMSE 0.002573354; lr 1.5625e-05; 82s
network 6, training 0, epoch 430: train scaled MSE 0.000384464; val RMSE 0.002573113; lr 1.5625e-05; 84s
network 6, training 0, epoch 440: train scaled MSE 0.000381649; val RMSE 0.0025733; lr 1.5625e-05; 86s
network 6, training 0, epoch 450: train scaled MSE 0.000382048; val RMSE 0.002572448; lr 1.5625e-05; 88s
network 6, training 0, epoch 460: train scaled MSE 0.000378321; val RMSE 0.002571743; lr 1.5625e-05; 90s
network 6, training 0, epoch 470: train scaled MSE 0.000378384; val RMSE 0.002572084; lr 1.5625e-05; 92s
network 6, training 0, epoch 480: train scaled MSE 0.000375239; val RMSE 0.002571685; lr 1.5625e-05; 94s
network 6, training 0, epoch 490: train scaled MSE 0.000373492; val RMSE 0.002570667; lr 1e-05; 96s
network 6, training 0, epoch 500: train scaled MSE 0.000371314; val RMSE 0.002570028; lr 1e-05; 98s
network 6, training 0, epoch 510: train scaled MSE 0.000370028; val RMSE 0.002570032; lr 1e-05; 100s
network 6, training 0, epoch 520: train scaled MSE 0.000369017; val RMSE 0.002569979; lr 1e-05; 102s
network 6, training 0, epoch 530: train scaled MSE 0.000377477; val RMSE 0.002570467; lr 1e-05; 104s
network 6, training 0, epoch 540: train scaled MSE 0.000370431; val RMSE 0.002570382; lr 1e-05; 106s
network 6, training 0, epoch 550: train scaled MSE 0.000365607; val RMSE 0.002569452; lr 1e-05; 108s
network 6, training 0, epoch 560: train scaled MSE 0.000365089; val RMSE 0.002568987; lr 1e-05; 110s
network 6, training 0, epoch 570: train scaled MSE 0.000368427; val RMSE 0.002568741; lr 1e-05; 112s
network 6, training 0, epoch 580: train scaled MSE 0.000362571; val RMSE 0.002568315; lr 1e-05; 114s
network 6, training 0, epoch 590: train scaled MSE 0.000362468; val RMSE 0.002568166; lr 1e-05; 116s
network 6, training 0, epoch 600: train scaled MSE 0.000361241; val RMSE 0.002568337; lr 1e-05; 117s
network 6, training 0, epoch 610: train scaled MSE 0.000368129; val RMSE 0.002569768; lr 1e-05; 119s
network 6, training 0, epoch 620: train scaled MSE 0.00035904; val RMSE 0.002568033; lr 1e-05; 121s
network 6, training 0, epoch 630: train scaled MSE 0.000357826; val RMSE 0.00256765; lr 1e-05; 123s
network 6, training 0, epoch 640: train scaled MSE 0.000370926; val RMSE 0.002570643; lr 1e-05; 125s
network 6, training 0, epoch 650: train scaled MSE 0.000356337; val RMSE 0.002567298; lr 1e-05; 127s
network 6, training 0, epoch 660: train scaled MSE 0.000355171; val RMSE 0.002567046; lr 1e-05; 129s
network 6, training 0, epoch 670: train scaled MSE 0.000358674; val RMSE 0.002567762; lr 1e-05; 131s
network 6, training 0, epoch 680: train scaled MSE 0.000354692; val RMSE 0.002566894; lr 1e-05; 133s
network 6, training 0, epoch 690: train scaled MSE 0.000352278; val RMSE 0.002566843; lr 1e-05; 135s
network 6, training 0, epoch 700: train scaled MSE 0.000353343; val RMSE 0.002566455; lr 1e-05; 137s
network 6, training 0, epoch 710: train scaled MSE 0.000350621; val RMSE 0.002566199; lr 1e-05; 139s
network 6, training 0, epoch 720: train scaled MSE 0.000353995; val RMSE 0.002567073; lr 1e-05; 141s
network 6, training 0, epoch 730: train scaled MSE 0.000349014; val RMSE 0.002565659; lr 1e-05; 143s
network 6, training 0, epoch 740: train scaled MSE 0.000347925; val RMSE 0.002565824; lr 1e-05; 145s
network 6, training 0, epoch 750: train scaled MSE 0.00035123; val RMSE 0.00256577; lr 1e-05; 147s
network 6, training 0, epoch 760: train scaled MSE 0.000347033; val RMSE 0.00256546; lr 1e-05; 149s
network 6, training 0, epoch 770: train scaled MSE 0.000345608; val RMSE 0.002565169; lr 1e-05; 151s
network 6, training 0, epoch 780: train scaled MSE 0.000347529; val RMSE 0.002566111; lr 1e-05; 153s
network 6, training 0, epoch 790: train scaled MSE 0.000344635; val RMSE 0.002565207; lr 1e-05; 155s
network 6, training 0, epoch 800: train scaled MSE 0.000344328; val RMSE 0.002565704; lr 1e-05; 157s
network 6, training 0, epoch 810: train scaled MSE 0.000342345; val RMSE 0.002565002; lr 1e-05; 159s
network 6, training 0, epoch 820: train scaled MSE 0.000355625; val RMSE 0.002565751; lr 1e-05; 161s
network 6, training 0, epoch 830: train scaled MSE 0.000340455; val RMSE 0.0025647; lr 1e-05; 163s
network 6, training 0, epoch 840: train scaled MSE 0.000340456; val RMSE 0.002564408; lr 1e-05; 165s
network 6, training 0, epoch 850: train scaled MSE 0.000338853; val RMSE 0.002563786; lr 1e-05; 166s
network 6, training 0, epoch 860: train scaled MSE 0.000338157; val RMSE 0.002563574; lr 1e-05; 168s
network 6, training 0, epoch 870: train scaled MSE 0.000338555; val RMSE 0.002564036; lr 1e-05; 170s
network 6, training 0, epoch 880: train scaled MSE 0.000336293; val RMSE 0.002563537; lr 1e-05; 172s
network 6, training 0, epoch 890: train scaled MSE 0.000335381; val RMSE 0.002563217; lr 1e-05; 175s
network 6, training 0, epoch 900: train scaled MSE 0.00033855; val RMSE 0.002563409; lr 1e-05; 177s
network 6, training 0, epoch 910: train scaled MSE 0.000345787; val RMSE 0.002564875; lr 1e-05; 179s
network 6, training 0, epoch 920: train scaled MSE 0.000333203; val RMSE 0.002563172; lr 1e-05; 181s
network 6, training 0, epoch 930: train scaled MSE 0.000332909; val RMSE 0.002562426; lr 1e-05; 183s
network 6, training 0, epoch 940: train scaled MSE 0.000331927; val RMSE 0.0025627; lr 1e-05; 185s
network 6, training 0, epoch 950: train scaled MSE 0.000335789; val RMSE 0.002564203; lr 1e-05; 187s
network 6, training 0, epoch 960: train scaled MSE 0.000329552; val RMSE 0.002563097; lr 1e-05; 189s
network 6, training 0, epoch 970: train scaled MSE 0.000329197; val RMSE 0.002562948; lr 1e-05; 191s
network 6, training 0, epoch 980: train scaled MSE 0.000328687; val RMSE 0.00256237; lr 1e-05; 193s
network 6, training 0, epoch 990: train scaled MSE 0.000327704; val RMSE 0.002562181; lr 1e-05; 195s
network 6, training 0, epoch 1000: train scaled MSE 0.000327097; val RMSE 0.002561736; lr 1e-05; 197s
network 6, training 0, epoch 1010: train scaled MSE 0.000326335; val RMSE 0.002561972; lr 1e-05; 199s
network 6, training 0, epoch 1020: train scaled MSE 0.000325405; val RMSE 0.002561472; lr 1e-05; 201s
network 6, training 0, epoch 1030: train scaled MSE 0.00032832; val RMSE 0.002561452; lr 1e-05; 203s
network 6, training 0, epoch 1040: train scaled MSE 0.000326123; val RMSE 0.002562214; lr 1e-05; 205s
network 6, training 0, epoch 1050: train scaled MSE 0.00032487; val RMSE 0.002562102; lr 1e-05; 207s
network 6, training 0, epoch 1060: train scaled MSE 0.000322274; val RMSE 0.002561626; lr 1e-05; 209s
network 6, training 0, epoch 1070: train scaled MSE 0.000321579; val RMSE 0.002561473; lr 1e-05; 211s
network 6, training 0, epoch 1080: train scaled MSE 0.000321039; val RMSE 0.002561061; lr 1e-05; 213s
network 6, training 0, epoch 1090: train scaled MSE 0.000321172; val RMSE 0.002561101; lr 1e-05; 215s
network 6, training 0, epoch 1100: train scaled MSE 0.000321669; val RMSE 0.002560958; lr 1e-05; 217s
network 6, training 0, epoch 1110: train scaled MSE 0.00032015; val RMSE 0.002560658; lr 1e-05; 219s
network 6, training 0, epoch 1120: train scaled MSE 0.000318034; val RMSE 0.002560452; lr 1e-05; 221s
network 6, training 0, epoch 1130: train scaled MSE 0.000317845; val RMSE 0.002560495; lr 1e-05; 223s
network 6, training 0, epoch 1140: train scaled MSE 0.000316693; val RMSE 0.002560269; lr 1e-05; 225s
network 6, training 0, epoch 1150: train scaled MSE 0.000315943; val RMSE 0.002559693; lr 1e-05; 227s
network 6, training 0, epoch 1160: train scaled MSE 0.000315999; val RMSE 0.002560579; lr 1e-05; 229s
network 6, training 0, epoch 1170: train scaled MSE 0.000314421; val RMSE 0.002559787; lr 1e-05; 232s
network 6, training 0, epoch 1180: train scaled MSE 0.000314029; val RMSE 0.002560208; lr 1e-05; 233s
network 6, training 0, epoch 1190: train scaled MSE 0.000312647; val RMSE 0.002559862; lr 1e-05; 235s
network 6, training 0, epoch 1200: train scaled MSE 0.000312071; val RMSE 0.002558785; lr 1e-05; 237s
network 6, training 0, epoch 1210: train scaled MSE 0.000316046; val RMSE 0.002559831; lr 1e-05; 239s
network 6, training 0, epoch 1220: train scaled MSE 0.000312167; val RMSE 0.002559083; lr 1e-05; 241s
network 6, training 0, epoch 1230: train scaled MSE 0.000309753; val RMSE 0.00255877; lr 1e-05; 243s
network 6, training 0, epoch 1240: train scaled MSE 0.000309186; val RMSE 0.002558794; lr 1e-05; 245s
network 6, training 0, epoch 1250: train scaled MSE 0.000308559; val RMSE 0.00255912; lr 1e-05; 247s
network 6, training 0, epoch 1260: train scaled MSE 0.000311176; val RMSE 0.002558904; lr 1e-05; 249s
network 6, training 0, epoch 1270: train scaled MSE 0.000308259; val RMSE 0.002559092; lr 1e-05; 251s
network 6, training 0, epoch 1280: train scaled MSE 0.000306709; val RMSE 0.002558488; lr 1e-05; 253s
network 6, training 0, epoch 1290: train scaled MSE 0.000305439; val RMSE 0.002558433; lr 1e-05; 255s
network 6, training 0, epoch 1300: train scaled MSE 0.000306806; val RMSE 0.002558098; lr 1e-05; 257s
network 6, training 0, epoch 1310: train scaled MSE 0.000309392; val RMSE 0.002558514; lr 1e-05; 259s
network 6, training 0, epoch 1320: train scaled MSE 0.000303611; val RMSE 0.002558405; lr 1e-05; 260s
network 6, training 0, epoch 1330: train scaled MSE 0.000302232; val RMSE 0.00255795; lr 1e-05; 262s
network 6, training 0, epoch 1340: train scaled MSE 0.000301562; val RMSE 0.002558048; lr 1e-05; 264s
network 6, training 0, epoch 1350: train scaled MSE 0.000302115; val RMSE 0.002557973; lr 1e-05; 266s
network 6, training 0, epoch 1360: train scaled MSE 0.000304257; val RMSE 0.002558083; lr 1e-05; 268s
network 6, training 0, epoch 1370: train scaled MSE 0.000299861; val RMSE 0.002557801; lr 1e-05; 270s
network 6, training 0, epoch 1380: train scaled MSE 0.000298949; val RMSE 0.002557731; lr 1e-05; 272s
network 6, training 0, epoch 1390: train scaled MSE 0.000298304; val RMSE 0.002557309; lr 1e-05; 274s
network 6, training 0, epoch 1400: train scaled MSE 0.000318166; val RMSE 0.002561705; lr 1e-05; 276s
network 6, training 0, epoch 1410: train scaled MSE 0.000298022; val RMSE 0.002556996; lr 1e-05; 278s
network 6, training 0, epoch 1420: train scaled MSE 0.000296298; val RMSE 0.002557092; lr 1e-05; 280s
network 6, training 0, epoch 1430: train scaled MSE 0.000299603; val RMSE 0.002557644; lr 1e-05; 282s
network 6, training 0, epoch 1440: train scaled MSE 0.000295262; val RMSE 0.002556699; lr 1e-05; 284s
network 6, training 0, epoch 1450: train scaled MSE 0.000295518; val RMSE 0.002557289; lr 1e-05; 286s
network 6, training 0, epoch 1460: train scaled MSE 0.000293815; val RMSE 0.002556731; lr 1e-05; 288s
network 6, training 0, epoch 1470: train scaled MSE 0.000293917; val RMSE 0.002556929; lr 1e-05; 290s
network 6, training 0, epoch 1480: train scaled MSE 0.000292341; val RMSE 0.002556555; lr 1e-05; 292s
network 6, training 0, epoch 1490: train scaled MSE 0.000291983; val RMSE 0.002556702; lr 1e-05; 294s
network 6, training 0, epoch 1500: train scaled MSE 0.000291645; val RMSE 0.002556634; lr 1e-05; 296s
network 6, training 0, epoch 1510: train scaled MSE 0.00029147; val RMSE 0.002555948; lr 1e-05; 297s
network 6, training 0, epoch 1520: train scaled MSE 0.000290172; val RMSE 0.002556322; lr 1e-05; 299s
network 6, training 0, epoch 1530: train scaled MSE 0.000289404; val RMSE 0.002556007; lr 1e-05; 301s
network 6, training 0, epoch 1540: train scaled MSE 0.000289413; val RMSE 0.002556437; lr 1e-05; 303s
network 6, training 0, epoch 1550: train scaled MSE 0.00028884; val RMSE 0.002556089; lr 1e-05; 305s
network 6, training 0, epoch 1560: train scaled MSE 0.000287439; val RMSE 0.002556403; lr 1e-05; 307s
network 6, training 0, epoch 1570: train scaled MSE 0.000290883; val RMSE 0.00255603; lr 1e-05; 309s
network 6, training 0, epoch 1580: train scaled MSE 0.0002863; val RMSE 0.002556667; lr 1e-05; 311s
network 6, training 0, epoch 1590: train scaled MSE 0.000286898; val RMSE 0.002555896; lr 1e-05; 313s
network 6, training 0, epoch 1600: train scaled MSE 0.000285049; val RMSE 0.002555616; lr 1e-05; 315s
network 6, training 0, epoch 1610: train scaled MSE 0.000286533; val RMSE 0.002556465; lr 1e-05; 317s
network 6, training 0, epoch 1620: train scaled MSE 0.000283948; val RMSE 0.002555512; lr 1e-05; 319s
network 6, training 0, epoch 1630: train scaled MSE 0.000284223; val RMSE 0.002555588; lr 1e-05; 321s
network 6, training 0, epoch 1640: train scaled MSE 0.000283603; val RMSE 0.002554624; lr 1e-05; 323s
network 6, training 0, epoch 1650: train scaled MSE 0.000283021; val RMSE 0.002555344; lr 1e-05; 325s
network 6, training 0, epoch 1660: train scaled MSE 0.000286247; val RMSE 0.002555261; lr 1e-05; 327s
network 6, training 0, epoch 1670: train scaled MSE 0.000281; val RMSE 0.002554458; lr 1e-05; 329s
network 6, training 0, epoch 1680: train scaled MSE 0.000281054; val RMSE 0.002554934; lr 1e-05; 331s
network 6, training 0, epoch 1690: train scaled MSE 0.000280073; val RMSE 0.002554363; lr 1e-05; 333s
network 6, training 0, epoch 1700: train scaled MSE 0.000289508; val RMSE 0.002554953; lr 1e-05; 335s
network 6, training 0, epoch 1710: train scaled MSE 0.000281071; val RMSE 0.002554642; lr 1e-05; 337s
network 6, training 0, epoch 1720: train scaled MSE 0.000278225; val RMSE 0.002554869; lr 1e-05; 339s
network 6, training 0, epoch 1730: train scaled MSE 0.000278832; val RMSE 0.002554471; lr 1e-05; 341s
network 6, training 0, epoch 1740: train scaled MSE 0.000276991; val RMSE 0.002553988; lr 1e-05; 343s
network 6, training 0, epoch 1750: train scaled MSE 0.000277076; val RMSE 0.002554571; lr 1e-05; 344s
network 6, training 0, epoch 1760: train scaled MSE 0.000276203; val RMSE 0.002554047; lr 1e-05; 346s
network 6, training 0, epoch 1770: train scaled MSE 0.000275614; val RMSE 0.002553984; lr 1e-05; 348s
network 6, training 0, epoch 1780: train scaled MSE 0.000276142; val RMSE 0.002553362; lr 1e-05; 350s
network 6, training 0, epoch 1790: train scaled MSE 0.000277237; val RMSE 0.002553898; lr 1e-05; 352s
network 6, training 0, epoch 1800: train scaled MSE 0.000274515; val RMSE 0.002554029; lr 1e-05; 354s
network 6, training 0, epoch 1810: train scaled MSE 0.000286509; val RMSE 0.002555727; lr 1e-05; 356s
network 6, training 0, epoch 1820: train scaled MSE 0.000275971; val RMSE 0.002554299; lr 1e-05; 358s
Standard Linear Baseline Validation RMSE: 0.002861087

Network seed 6, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0026,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0026,1.4659,"[-1.09%, 2.99%]",0.1445,0.0,0.0275
MLP,0.0023,20.9126,"[0.69%, 34.45%]",0.5300,266.6761,0.2138

network 6, training 1, epoch 1: train scaled MSE 0.847692; val RMSE 0.02531157; lr 0.001; 0s
network 6, training 1, epoch 10: train scaled MSE 0.0175477; val RMSE 0.00438822; lr 0.001; 2s
network 6, training 1, epoch 20: train scaled MSE 0.0097321; val RMSE 0.002631141; lr 0.001; 4s
network 6, training 1, epoch 30: train scaled MSE 0.0109625; val RMSE 0.003385426; lr 0.001; 6s
network 6, training 1, epoch 40: train scaled MSE 0.00641449; val RMSE 0.002551911; lr 0.001; 8s
network 6, training 1, epoch 50: train scaled MSE 0.00969246; val RMSE 0.002494832; lr 0.001; 9s
network 6, training 1, epoch 60: train scaled MSE 0.00473186; val RMSE 0.002296954; lr 0.0005; 11s
network 6, training 1, epoch 70: train scaled MSE 0.00415424; val RMSE 0.002209183; lr 0.0005; 13s
network 6, training 1, epoch 80: train scaled MSE 0.00357862; val RMSE 0.002182932; lr 0.0005; 15s
network 6, training 1, epoch 90: train scaled MSE 0.00405738; val RMSE 0.002238804; lr 0.0005; 17s
network 6, training 1, epoch 100: train scaled MSE 0.00277449; val RMSE 0.002132981; lr 0.00025; 19s
network 6, training 1, epoch 110: train scaled MSE 0.00246579; val RMSE 0.00213002; lr 0.00025; 21s
network 6, training 1, epoch 120: train scaled MSE 0.00224439; val RMSE 0.002107677; lr 0.00025; 23s
network 6, training 1, epoch 130: train scaled MSE 0.00207521; val RMSE 0.002090785; lr 0.00025; 25s
network 6, training 1, epoch 140: train scaled MSE 0.00186721; val RMSE 0.002186975; lr 0.00025; 27s
network 6, training 1, epoch 150: train scaled MSE 0.00174112; val RMSE 0.002101176; lr 0.00025; 29s
network 6, training 1, epoch 160: train scaled MSE 0.00157378; val RMSE 0.002194044; lr 0.00025; 31s
network 6, training 1, epoch 170: train scaled MSE 0.00144922; val RMSE 0.002091306; lr 0.00025; 33s
network 6, training 1, epoch 180: train scaled MSE 0.00136331; val RMSE 0.002027557; lr 0.00025; 35s
network 6, training 1, epoch 190: train scaled MSE 0.00126931; val RMSE 0.002014267; lr 0.00025; 36s
network 6, training 1, epoch 200: train scaled MSE 0.00118152; val RMSE 0.002011917; lr 0.00025; 38s
network 6, training 1, epoch 210: train scaled MSE 0.00108817; val RMSE 0.002002729; lr 0.00025; 40s
network 6, training 1, epoch 220: train scaled MSE 0.00109419; val RMSE 0.002002998; lr 0.00025; 42s
network 6, training 1, epoch 230: train scaled MSE 0.000961864; val RMSE 0.00200739; lr 0.00025; 44s
network 6, training 1, epoch 240: train scaled MSE 0.000872075; val RMSE 0.001977411; lr 0.000125; 46s
network 6, training 1, epoch 250: train scaled MSE 0.000850727; val RMSE 0.001973483; lr 0.000125; 47s
network 6, training 1, epoch 260: train scaled MSE 0.000824857; val RMSE 0.001967493; lr 0.000125; 49s
network 6, training 1, epoch 270: train scaled MSE 0.000801641; val RMSE 0.001961725; lr 0.000125; 51s
network 6, training 1, epoch 280: train scaled MSE 0.000775782; val RMSE 0.001960111; lr 0.000125; 53s
network 6, training 1, epoch 290: train scaled MSE 0.000744529; val RMSE 0.001999753; lr 0.000125; 55s
network 6, training 1, epoch 300: train scaled MSE 0.00074121; val RMSE 0.001954536; lr 0.000125; 57s
network 6, training 1, epoch 310: train scaled MSE 0.000784131; val RMSE 0.001958288; lr 6.25e-05; 59s
network 6, training 1, epoch 320: train scaled MSE 0.000685203; val RMSE 0.001945776; lr 6.25e-05; 61s
network 6, training 1, epoch 330: train scaled MSE 0.000677391; val RMSE 0.001977274; lr 6.25e-05; 62s
network 6, training 1, epoch 340: train scaled MSE 0.00066358; val RMSE 0.001940233; lr 6.25e-05; 64s
network 6, training 1, epoch 350: train scaled MSE 0.000659893; val RMSE 0.001938432; lr 6.25e-05; 66s
network 6, training 1, epoch 360: train scaled MSE 0.000685278; val RMSE 0.001941464; lr 6.25e-05; 68s
network 6, training 1, epoch 370: train scaled MSE 0.000641392; val RMSE 0.001934859; lr 6.25e-05; 70s
network 6, training 1, epoch 380: train scaled MSE 0.000657985; val RMSE 0.001936121; lr 6.25e-05; 72s
network 6, training 1, epoch 390: train scaled MSE 0.00061539; val RMSE 0.001929474; lr 3.125e-05; 74s
network 6, training 1, epoch 400: train scaled MSE 0.000617056; val RMSE 0.001930229; lr 3.125e-05; 75s
network 6, training 1, epoch 410: train scaled MSE 0.000606623; val RMSE 0.001926544; lr 3.125e-05; 77s
network 6, training 1, epoch 420: train scaled MSE 0.000601813; val RMSE 0.001926156; lr 3.125e-05; 79s
network 6, training 1, epoch 430: train scaled MSE 0.000592445; val RMSE 0.001925148; lr 1.5625e-05; 81s
network 6, training 1, epoch 440: train scaled MSE 0.000589249; val RMSE 0.001923763; lr 1.5625e-05; 83s
network 6, training 1, epoch 450: train scaled MSE 0.000586613; val RMSE 0.001923878; lr 1.5625e-05; 85s
network 6, training 1, epoch 460: train scaled MSE 0.00058544; val RMSE 0.001922825; lr 1.5625e-05; 86s
network 6, training 1, epoch 470: train scaled MSE 0.000581908; val RMSE 0.001924392; lr 1.5625e-05; 88s
network 6, training 1, epoch 480: train scaled MSE 0.000578957; val RMSE 0.00192116; lr 1.5625e-05; 90s
network 6, training 1, epoch 490: train scaled MSE 0.000576242; val RMSE 0.001920954; lr 1.5625e-05; 92s
network 6, training 1, epoch 500: train scaled MSE 0.000572466; val RMSE 0.00192081; lr 1e-05; 94s
network 6, training 1, epoch 510: train scaled MSE 0.000572701; val RMSE 0.001919722; lr 1e-05; 96s
network 6, training 1, epoch 520: train scaled MSE 0.00056887; val RMSE 0.001918894; lr 1e-05; 97s
network 6, training 1, epoch 530: train scaled MSE 0.000567468; val RMSE 0.001918197; lr 1e-05; 99s
network 6, training 1, epoch 540: train scaled MSE 0.00056595; val RMSE 0.001918269; lr 1e-05; 101s
network 6, training 1, epoch 550: train scaled MSE 0.000564823; val RMSE 0.001917696; lr 1e-05; 103s
network 6, training 1, epoch 560: train scaled MSE 0.000564266; val RMSE 0.001917736; lr 1e-05; 105s
network 6, training 1, epoch 570: train scaled MSE 0.000560389; val RMSE 0.001916907; lr 1e-05; 107s
network 6, training 1, epoch 580: train scaled MSE 0.000559557; val RMSE 0.001916884; lr 1e-05; 109s
network 6, training 1, epoch 590: train scaled MSE 0.000557638; val RMSE 0.001916398; lr 1e-05; 111s
network 6, training 1, epoch 600: train scaled MSE 0.000556952; val RMSE 0.001916485; lr 1e-05; 113s
network 6, training 1, epoch 610: train scaled MSE 0.000566385; val RMSE 0.001917721; lr 1e-05; 114s
network 6, training 1, epoch 620: train scaled MSE 0.000563536; val RMSE 0.001916697; lr 1e-05; 116s
network 6, training 1, epoch 630: train scaled MSE 0.000551425; val RMSE 0.001915733; lr 1e-05; 118s
network 6, training 1, epoch 640: train scaled MSE 0.000552212; val RMSE 0.001916562; lr 1e-05; 120s
network 6, training 1, epoch 650: train scaled MSE 0.000552194; val RMSE 0.001915578; lr 1e-05; 122s
network 6, training 1, epoch 660: train scaled MSE 0.000547367; val RMSE 0.001914285; lr 1e-05; 123s
network 6, training 1, epoch 670: train scaled MSE 0.000545972; val RMSE 0.001913648; lr 1e-05; 125s
network 6, training 1, epoch 680: train scaled MSE 0.000553402; val RMSE 0.0019155; lr 1e-05; 127s
network 6, training 1, epoch 690: train scaled MSE 0.000569867; val RMSE 0.001917444; lr 1e-05; 129s
network 6, training 1, epoch 700: train scaled MSE 0.000545145; val RMSE 0.001913025; lr 1e-05; 131s
network 6, training 1, epoch 710: train scaled MSE 0.000543489; val RMSE 0.001913444; lr 1e-05; 132s
network 6, training 1, epoch 720: train scaled MSE 0.00053988; val RMSE 0.001912753; lr 1e-05; 134s
network 6, training 1, epoch 730: train scaled MSE 0.000542172; val RMSE 0.001913722; lr 1e-05; 136s
network 6, training 1, epoch 740: train scaled MSE 0.000537129; val RMSE 0.001911937; lr 1e-05; 138s
network 6, training 1, epoch 750: train scaled MSE 0.000536028; val RMSE 0.001911917; lr 1e-05; 140s
network 6, training 1, epoch 760: train scaled MSE 0.000534956; val RMSE 0.001911531; lr 1e-05; 142s
network 6, training 1, epoch 770: train scaled MSE 0.000534354; val RMSE 0.001911062; lr 1e-05; 143s
network 6, training 1, epoch 780: train scaled MSE 0.000535902; val RMSE 0.001912302; lr 1e-05; 145s
network 6, training 1, epoch 790: train scaled MSE 0.000531287; val RMSE 0.001910484; lr 1e-05; 147s
network 6, training 1, epoch 800: train scaled MSE 0.000530209; val RMSE 0.001910372; lr 1e-05; 149s
network 6, training 1, epoch 810: train scaled MSE 0.00053049; val RMSE 0.001911139; lr 1e-05; 151s
network 6, training 1, epoch 820: train scaled MSE 0.000527813; val RMSE 0.001910485; lr 1e-05; 153s
network 6, training 1, epoch 830: train scaled MSE 0.000530007; val RMSE 0.001909199; lr 1e-05; 155s
network 6, training 1, epoch 840: train scaled MSE 0.000530351; val RMSE 0.001909826; lr 1e-05; 156s
network 6, training 1, epoch 850: train scaled MSE 0.000525719; val RMSE 0.001909736; lr 1e-05; 158s
network 6, training 1, epoch 860: train scaled MSE 0.000530223; val RMSE 0.001910222; lr 1e-05; 160s
network 6, training 1, epoch 870: train scaled MSE 0.00052227; val RMSE 0.001908646; lr 1e-05; 162s
network 6, training 1, epoch 880: train scaled MSE 0.000520618; val RMSE 0.001908356; lr 1e-05; 164s
network 6, training 1, epoch 890: train scaled MSE 0.0005201; val RMSE 0.001908124; lr 1e-05; 166s
network 6, training 1, epoch 900: train scaled MSE 0.000519358; val RMSE 0.001908455; lr 1e-05; 168s
network 6, training 1, epoch 910: train scaled MSE 0.00051766; val RMSE 0.001908086; lr 1e-05; 169s
network 6, training 1, epoch 920: train scaled MSE 0.000516576; val RMSE 0.001906843; lr 1e-05; 171s
network 6, training 1, epoch 930: train scaled MSE 0.00051553; val RMSE 0.001906975; lr 1e-05; 173s
network 6, training 1, epoch 940: train scaled MSE 0.000515483; val RMSE 0.001907612; lr 1e-05; 175s
network 6, training 1, epoch 950: train scaled MSE 0.000512594; val RMSE 0.001907291; lr 1e-05; 177s
network 6, training 1, epoch 960: train scaled MSE 0.000511112; val RMSE 0.001906331; lr 1e-05; 178s
network 6, training 1, epoch 970: train scaled MSE 0.000510167; val RMSE 0.00190602; lr 1e-05; 180s
network 6, training 1, epoch 980: train scaled MSE 0.000508904; val RMSE 0.001905515; lr 1e-05; 182s
network 6, training 1, epoch 990: train scaled MSE 0.00050799; val RMSE 0.001905548; lr 1e-05; 184s
network 6, training 1, epoch 1000: train scaled MSE 0.000508079; val RMSE 0.001906746; lr 1e-05; 186s
network 6, training 1, epoch 1010: train scaled MSE 0.000520707; val RMSE 0.001907557; lr 1e-05; 187s
network 6, training 1, epoch 1020: train scaled MSE 0.000503646; val RMSE 0.001904572; lr 1e-05; 189s
network 6, training 1, epoch 1030: train scaled MSE 0.000501787; val RMSE 0.001904422; lr 1e-05; 191s
network 6, training 1, epoch 1040: train scaled MSE 0.000507183; val RMSE 0.001905862; lr 1e-05; 193s
network 6, training 1, epoch 1050: train scaled MSE 0.000502309; val RMSE 0.001904913; lr 1e-05; 195s
network 6, training 1, epoch 1060: train scaled MSE 0.000501441; val RMSE 0.001904126; lr 1e-05; 196s
network 6, training 1, epoch 1070: train scaled MSE 0.000497056; val RMSE 0.001903559; lr 1e-05; 198s
network 6, training 1, epoch 1080: train scaled MSE 0.000496446; val RMSE 0.001903517; lr 1e-05; 200s
network 6, training 1, epoch 1090: train scaled MSE 0.000495283; val RMSE 0.001902737; lr 1e-05; 202s
network 6, training 1, epoch 1100: train scaled MSE 0.0004935; val RMSE 0.00190303; lr 1e-05; 204s
network 6, training 1, epoch 1110: train scaled MSE 0.000492037; val RMSE 0.001902677; lr 1e-05; 206s
network 6, training 1, epoch 1120: train scaled MSE 0.00049215; val RMSE 0.00190258; lr 1e-05; 207s
network 6, training 1, epoch 1130: train scaled MSE 0.000492157; val RMSE 0.001902884; lr 1e-05; 209s
network 6, training 1, epoch 1140: train scaled MSE 0.000489125; val RMSE 0.001901693; lr 1e-05; 211s
network 6, training 1, epoch 1150: train scaled MSE 0.000490175; val RMSE 0.001901931; lr 1e-05; 213s
network 6, training 1, epoch 1160: train scaled MSE 0.00048601; val RMSE 0.001902002; lr 1e-05; 215s
network 6, training 1, epoch 1170: train scaled MSE 0.000485426; val RMSE 0.001901923; lr 1e-05; 217s
network 6, training 1, epoch 1180: train scaled MSE 0.000485217; val RMSE 0.001902839; lr 1e-05; 219s
network 6, training 1, epoch 1190: train scaled MSE 0.000482272; val RMSE 0.001901419; lr 1e-05; 220s
network 6, training 1, epoch 1200: train scaled MSE 0.000481758; val RMSE 0.001900708; lr 1e-05; 222s
network 6, training 1, epoch 1210: train scaled MSE 0.00048009; val RMSE 0.001900403; lr 1e-05; 224s
network 6, training 1, epoch 1220: train scaled MSE 0.000479153; val RMSE 0.001900165; lr 1e-05; 226s
network 6, training 1, epoch 1230: train scaled MSE 0.000482049; val RMSE 0.001900304; lr 1e-05; 228s
network 6, training 1, epoch 1240: train scaled MSE 0.000476619; val RMSE 0.001899719; lr 1e-05; 230s
network 6, training 1, epoch 1250: train scaled MSE 0.000477141; val RMSE 0.001899959; lr 1e-05; 231s
network 6, training 1, epoch 1260: train scaled MSE 0.000496115; val RMSE 0.001901187; lr 1e-05; 233s
network 6, training 1, epoch 1270: train scaled MSE 0.000473311; val RMSE 0.001898982; lr 1e-05; 235s
network 6, training 1, epoch 1280: train scaled MSE 0.000473957; val RMSE 0.001899712; lr 1e-05; 237s
network 6, training 1, epoch 1290: train scaled MSE 0.00047112; val RMSE 0.001899212; lr 1e-05; 239s
network 6, training 1, epoch 1300: train scaled MSE 0.000477748; val RMSE 0.001898285; lr 1e-05; 240s
network 6, training 1, epoch 1310: train scaled MSE 0.000469202; val RMSE 0.001898426; lr 1e-05; 242s
network 6, training 1, epoch 1320: train scaled MSE 0.00046885; val RMSE 0.001898331; lr 1e-05; 244s
network 6, training 1, epoch 1330: train scaled MSE 0.000467259; val RMSE 0.001898754; lr 1e-05; 246s
network 6, training 1, epoch 1340: train scaled MSE 0.000466223; val RMSE 0.001898126; lr 1e-05; 248s
network 6, training 1, epoch 1350: train scaled MSE 0.000465639; val RMSE 0.001898337; lr 1e-05; 250s
Standard Linear Baseline Validation RMSE: 0.002119578

Network seed 6, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0031,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0031,1.7417,"[0.58%, 2.61%]",0.1332,0.0,0.0477
MLP,0.0027,23.7840,"[12.48%, 32.52%]",0.5069,280.5152,0.1115

network 6, training 2, epoch 1: train scaled MSE 0.859033; val RMSE 0.02628132; lr 0.001; 0s
network 6, training 2, epoch 10: train scaled MSE 0.034891; val RMSE 0.005618449; lr 0.001; 2s
network 6, training 2, epoch 20: train scaled MSE 0.0111956; val RMSE 0.003245968; lr 0.001; 4s
network 6, training 2, epoch 30: train scaled MSE 0.00941488; val RMSE 0.003705567; lr 0.001; 5s
network 6, training 2, epoch 40: train scaled MSE 0.00776743; val RMSE 0.002877521; lr 0.001; 7s
network 6, training 2, epoch 50: train scaled MSE 0.00705163; val RMSE 0.002978738; lr 0.001; 9s
network 6, training 2, epoch 60: train scaled MSE 0.00519856; val RMSE 0.002808642; lr 0.001; 11s
network 6, training 2, epoch 70: train scaled MSE 0.00421025; val RMSE 0.002783165; lr 0.001; 13s
network 6, training 2, epoch 80: train scaled MSE 0.00275249; val RMSE 0.002658202; lr 0.0005; 14s
network 6, training 2, epoch 90: train scaled MSE 0.00268872; val RMSE 0.002630557; lr 0.0005; 16s
network 6, training 2, epoch 100: train scaled MSE 0.00205769; val RMSE 0.003422009; lr 0.0005; 18s
network 6, training 2, epoch 110: train scaled MSE 0.00168474; val RMSE 0.002563548; lr 0.00025; 20s
network 6, training 2, epoch 120: train scaled MSE 0.00153981; val RMSE 0.002563518; lr 0.00025; 22s
network 6, training 2, epoch 130: train scaled MSE 0.00145502; val RMSE 0.00254358; lr 0.00025; 24s
network 6, training 2, epoch 140: train scaled MSE 0.00136504; val RMSE 0.002541213; lr 0.00025; 26s
network 6, training 2, epoch 150: train scaled MSE 0.00127456; val RMSE 0.002538468; lr 0.00025; 28s
network 6, training 2, epoch 160: train scaled MSE 0.00120371; val RMSE 0.002532307; lr 0.00025; 29s
network 6, training 2, epoch 170: train scaled MSE 0.00111083; val RMSE 0.002522949; lr 0.00025; 31s
network 6, training 2, epoch 180: train scaled MSE 0.00105286; val RMSE 0.002518434; lr 0.00025; 33s
network 6, training 2, epoch 190: train scaled MSE 0.000983497; val RMSE 0.002518177; lr 0.00025; 35s
network 6, training 2, epoch 200: train scaled MSE 0.000944156; val RMSE 0.00251513; lr 0.00025; 37s
network 6, training 2, epoch 210: train scaled MSE 0.000880246; val RMSE 0.002873144; lr 0.00025; 39s
network 6, training 2, epoch 220: train scaled MSE 0.000835011; val RMSE 0.002517338; lr 0.00025; 41s
network 6, training 2, epoch 230: train scaled MSE 0.000756425; val RMSE 0.002496229; lr 0.000125; 42s
network 6, training 2, epoch 240: train scaled MSE 0.00093568; val RMSE 0.002505778; lr 0.000125; 44s
network 6, training 2, epoch 250: train scaled MSE 0.000712611; val RMSE 0.00250567; lr 0.000125; 46s
network 6, training 2, epoch 260: train scaled MSE 0.000690443; val RMSE 0.002489325; lr 0.000125; 48s
network 6, training 2, epoch 270: train scaled MSE 0.000707944; val RMSE 0.002479715; lr 0.000125; 50s
network 6, training 2, epoch 280: train scaled MSE 0.000646567; val RMSE 0.002534826; lr 0.000125; 52s
network 6, training 2, epoch 290: train scaled MSE 0.000629283; val RMSE 0.002478976; lr 0.000125; 54s
network 6, training 2, epoch 300: train scaled MSE 0.000608682; val RMSE 0.002471986; lr 0.000125; 55s
network 6, training 2, epoch 310: train scaled MSE 0.000595979; val RMSE 0.00246906; lr 0.000125; 57s
network 6, training 2, epoch 320: train scaled MSE 0.000550334; val RMSE 0.002464278; lr 6.25e-05; 59s
network 6, training 2, epoch 330: train scaled MSE 0.000549298; val RMSE 0.002468214; lr 6.25e-05; 61s
network 6, training 2, epoch 340: train scaled MSE 0.000530878; val RMSE 0.002456251; lr 6.25e-05; 63s
network 6, training 2, epoch 350: train scaled MSE 0.00052296; val RMSE 0.00245586; lr 6.25e-05; 65s
network 6, training 2, epoch 360: train scaled MSE 0.000517921; val RMSE 0.002455596; lr 6.25e-05; 67s
network 6, training 2, epoch 370: train scaled MSE 0.000508961; val RMSE 0.002454836; lr 6.25e-05; 69s
network 6, training 2, epoch 380: train scaled MSE 0.000500151; val RMSE 0.002456125; lr 6.25e-05; 71s
network 6, training 2, epoch 390: train scaled MSE 0.000492645; val RMSE 0.002452121; lr 6.25e-05; 72s
network 6, training 2, epoch 400: train scaled MSE 0.000494549; val RMSE 0.002453698; lr 6.25e-05; 74s
network 6, training 2, epoch 410: train scaled MSE 0.000905073; val RMSE 0.002471405; lr 6.25e-05; 76s
network 6, training 2, epoch 420: train scaled MSE 0.000466689; val RMSE 0.002449428; lr 3.125e-05; 78s
network 6, training 2, epoch 430: train scaled MSE 0.000464347; val RMSE 0.002447431; lr 3.125e-05; 80s
network 6, training 2, epoch 440: train scaled MSE 0.000530446; val RMSE 0.002452832; lr 3.125e-05; 82s
network 6, training 2, epoch 450: train scaled MSE 0.00045204; val RMSE 0.002446267; lr 1.5625e-05; 84s
network 6, training 2, epoch 460: train scaled MSE 0.00045035; val RMSE 0.00244566; lr 1.5625e-05; 85s
network 6, training 2, epoch 470: train scaled MSE 0.000456706; val RMSE 0.002445187; lr 1.5625e-05; 88s
network 6, training 2, epoch 480: train scaled MSE 0.000446221; val RMSE 0.002444289; lr 1e-05; 90s
network 6, training 2, epoch 490: train scaled MSE 0.000444783; val RMSE 0.002444691; lr 1e-05; 91s
network 6, training 2, epoch 500: train scaled MSE 0.000473562; val RMSE 0.002441437; lr 1e-05; 93s
network 6, training 2, epoch 510: train scaled MSE 0.000442916; val RMSE 0.002444118; lr 1e-05; 95s
network 6, training 2, epoch 520: train scaled MSE 0.000440699; val RMSE 0.002443436; lr 1e-05; 97s
network 6, training 2, epoch 530: train scaled MSE 0.000439513; val RMSE 0.002443749; lr 1e-05; 99s
network 6, training 2, epoch 540: train scaled MSE 0.000438422; val RMSE 0.00244254; lr 1e-05; 101s
Standard Linear Baseline Validation RMSE: 0.002629801

Network seed 6, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0028,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0028,1.5091,"[-0.37%, 2.96%]",0.1362,0.0,0.0341
MLP,0.0024,25.7942,"[12.93%, 37.45%]",0.5434,298.9595,0.0100

network 6, training 3, epoch 1: train scaled MSE 0.843963; val RMSE 0.02483711; lr 0.001; 0s
network 6, training 3, epoch 10: train scaled MSE 0.0261508; val RMSE 0.005090947; lr 0.001; 2s
network 6, training 3, epoch 20: train scaled MSE 0.0130888; val RMSE 0.003402335; lr 0.001; 4s
network 6, training 3, epoch 30: train scaled MSE 0.00941017; val RMSE 0.003204551; lr 0.001; 6s
network 6, training 3, epoch 40: train scaled MSE 0.00666963; val RMSE 0.003202169; lr 0.001; 8s
network 6, training 3, epoch 50: train scaled MSE 0.0138387; val RMSE 0.003134318; lr 0.001; 9s
network 6, training 3, epoch 60: train scaled MSE 0.0041531; val RMSE 0.002794119; lr 0.001; 11s
network 6, training 3, epoch 70: train scaled MSE 0.00382152; val RMSE 0.002813373; lr 0.001; 13s
network 6, training 3, epoch 80: train scaled MSE 0.00421385; val RMSE 0.002801251; lr 0.001; 15s
network 6, training 3, epoch 90: train scaled MSE 0.00277446; val RMSE 0.002710326; lr 0.001; 17s
network 6, training 3, epoch 100: train scaled MSE 0.00225583; val RMSE 0.002819297; lr 0.001; 19s
network 6, training 3, epoch 110: train scaled MSE 0.0015361; val RMSE 0.002655799; lr 0.001; 21s
network 6, training 3, epoch 120: train scaled MSE 0.00248231; val RMSE 0.002684104; lr 0.001; 23s
network 6, training 3, epoch 130: train scaled MSE 0.00269182; val RMSE 0.002636618; lr 0.0005; 25s
network 6, training 3, epoch 140: train scaled MSE 0.00100358; val RMSE 0.002577271; lr 0.0005; 26s
network 6, training 3, epoch 150: train scaled MSE 0.00102652; val RMSE 0.002605286; lr 0.0005; 28s
network 6, training 3, epoch 160: train scaled MSE 0.000801716; val RMSE 0.002554942; lr 0.00025; 30s
network 6, training 3, epoch 170: train scaled MSE 0.000836225; val RMSE 0.002545658; lr 0.00025; 32s
network 6, training 3, epoch 180: train scaled MSE 0.000742479; val RMSE 0.00258079; lr 0.00025; 34s
network 6, training 3, epoch 190: train scaled MSE 0.00140969; val RMSE 0.002634116; lr 0.00025; 36s
network 6, training 3, epoch 200: train scaled MSE 0.000671882; val RMSE 0.002605437; lr 0.00025; 38s
network 6, training 3, epoch 210: train scaled MSE 0.000696154; val RMSE 0.002535123; lr 0.00025; 39s
network 6, training 3, epoch 220: train scaled MSE 0.000633007; val RMSE 0.002529375; lr 0.00025; 41s
network 6, training 3, epoch 230: train scaled MSE 0.000592308; val RMSE 0.002524963; lr 0.000125; 43s
network 6, training 3, epoch 240: train scaled MSE 0.000995326; val RMSE 0.002549485; lr 0.000125; 45s
network 6, training 3, epoch 250: train scaled MSE 0.000550191; val RMSE 0.002511882; lr 0.000125; 47s
network 6, training 3, epoch 260: train scaled MSE 0.000543866; val RMSE 0.002510402; lr 0.000125; 49s
network 6, training 3, epoch 270: train scaled MSE 0.000526496; val RMSE 0.002509944; lr 0.000125; 51s
network 6, training 3, epoch 280: train scaled MSE 0.00127724; val RMSE 0.002518468; lr 0.000125; 53s
network 6, training 3, epoch 290: train scaled MSE 0.000493289; val RMSE 0.002502965; lr 6.25e-05; 55s
network 6, training 3, epoch 300: train scaled MSE 0.000486326; val RMSE 0.002503687; lr 6.25e-05; 57s
network 6, training 3, epoch 310: train scaled MSE 0.000572409; val RMSE 0.002505284; lr 6.25e-05; 58s
network 6, training 3, epoch 320: train scaled MSE 0.000476478; val RMSE 0.002497009; lr 6.25e-05; 60s
network 6, training 3, epoch 330: train scaled MSE 0.000497596; val RMSE 0.002498356; lr 6.25e-05; 62s
network 6, training 3, epoch 340: train scaled MSE 0.000463956; val RMSE 0.002492877; lr 6.25e-05; 64s
network 6, training 3, epoch 350: train scaled MSE 0.00045835; val RMSE 0.002491196; lr 6.25e-05; 66s
network 6, training 3, epoch 360: train scaled MSE 0.000592347; val RMSE 0.00249617; lr 6.25e-05; 68s
network 6, training 3, epoch 370: train scaled MSE 0.000443599; val RMSE 0.002490666; lr 3.125e-05; 70s
network 6, training 3, epoch 380: train scaled MSE 0.000454364; val RMSE 0.002504344; lr 3.125e-05; 72s
network 6, training 3, epoch 390: train scaled MSE 0.000435693; val RMSE 0.002488323; lr 1.5625e-05; 73s
network 6, training 3, epoch 400: train scaled MSE 0.000433434; val RMSE 0.002488052; lr 1.5625e-05; 75s
network 6, training 3, epoch 410: train scaled MSE 0.000434413; val RMSE 0.002487497; lr 1.5625e-05; 77s
network 6, training 3, epoch 420: train scaled MSE 0.000429285; val RMSE 0.002486392; lr 1.5625e-05; 79s
network 6, training 3, epoch 430: train scaled MSE 0.000427572; val RMSE 0.002486395; lr 1.5625e-05; 81s
network 6, training 3, epoch 440: train scaled MSE 0.000428365; val RMSE 0.002486157; lr 1.5625e-05; 83s
network 6, training 3, epoch 450: train scaled MSE 0.000422895; val RMSE 0.002485005; lr 1e-05; 85s
network 6, training 3, epoch 460: train scaled MSE 0.000421552; val RMSE 0.002484781; lr 1e-05; 86s
network 6, training 3, epoch 470: train scaled MSE 0.000420424; val RMSE 0.002484306; lr 1e-05; 88s
network 6, training 3, epoch 480: train scaled MSE 0.000419557; val RMSE 0.002484371; lr 1e-05; 90s
network 6, training 3, epoch 490: train scaled MSE 0.00042559; val RMSE 0.002485587; lr 1e-05; 92s
network 6, training 3, epoch 500: train scaled MSE 0.000416943; val RMSE 0.002483405; lr 1e-05; 94s
network 6, training 3, epoch 510: train scaled MSE 0.000415686; val RMSE 0.002483127; lr 1e-05; 96s
network 6, training 3, epoch 520: train scaled MSE 0.000415229; val RMSE 0.002482817; lr 1e-05; 98s
network 6, training 3, epoch 530: train scaled MSE 0.000413077; val RMSE 0.002482154; lr 1e-05; 100s
network 6, training 3, epoch 540: train scaled MSE 0.000415631; val RMSE 0.002482148; lr 1e-05; 101s
network 6, training 3, epoch 550: train scaled MSE 0.000411622; val RMSE 0.002481122; lr 1e-05; 103s
network 6, training 3, epoch 560: train scaled MSE 0.000409692; val RMSE 0.002481545; lr 1e-05; 105s
network 6, training 3, epoch 570: train scaled MSE 0.000408665; val RMSE 0.002480545; lr 1e-05; 107s
network 6, training 3, epoch 580: train scaled MSE 0.000407511; val RMSE 0.002480725; lr 1e-05; 109s
network 6, training 3, epoch 590: train scaled MSE 0.00040883; val RMSE 0.002479818; lr 1e-05; 111s
network 6, training 3, epoch 600: train scaled MSE 0.000405178; val RMSE 0.002479672; lr 1e-05; 113s
network 6, training 3, epoch 610: train scaled MSE 0.000408336; val RMSE 0.002480335; lr 1e-05; 114s
network 6, training 3, epoch 620: train scaled MSE 0.000403182; val RMSE 0.002480204; lr 1e-05; 116s
network 6, training 3, epoch 630: train scaled MSE 0.000401844; val RMSE 0.002478942; lr 1e-05; 118s
network 6, training 3, epoch 640: train scaled MSE 0.000400617; val RMSE 0.002479277; lr 1e-05; 120s
network 6, training 3, epoch 650: train scaled MSE 0.000412652; val RMSE 0.002479698; lr 1e-05; 122s
network 6, training 3, epoch 660: train scaled MSE 0.000399706; val RMSE 0.002477932; lr 1e-05; 123s
network 6, training 3, epoch 670: train scaled MSE 0.000397689; val RMSE 0.002477559; lr 1e-05; 125s
network 6, training 3, epoch 680: train scaled MSE 0.0003972; val RMSE 0.002477292; lr 1e-05; 127s
network 6, training 3, epoch 690: train scaled MSE 0.000397667; val RMSE 0.002477934; lr 1e-05; 129s
network 6, training 3, epoch 700: train scaled MSE 0.000398774; val RMSE 0.002477455; lr 1e-05; 131s
network 6, training 3, epoch 710: train scaled MSE 0.000396393; val RMSE 0.002476452; lr 1e-05; 133s
network 6, training 3, epoch 720: train scaled MSE 0.000395097; val RMSE 0.002476435; lr 1e-05; 135s
network 6, training 3, epoch 730: train scaled MSE 0.000392203; val RMSE 0.002475766; lr 1e-05; 136s
network 6, training 3, epoch 740: train scaled MSE 0.000391491; val RMSE 0.002475891; lr 1e-05; 138s
network 6, training 3, epoch 750: train scaled MSE 0.000390212; val RMSE 0.002474532; lr 1e-05; 140s
network 6, training 3, epoch 760: train scaled MSE 0.000389408; val RMSE 0.002476143; lr 1e-05; 142s
network 6, training 3, epoch 770: train scaled MSE 0.000388197; val RMSE 0.002476447; lr 1e-05; 144s
network 6, training 3, epoch 780: train scaled MSE 0.000387281; val RMSE 0.002475212; lr 1e-05; 146s
network 6, training 3, epoch 790: train scaled MSE 0.000386425; val RMSE 0.002475161; lr 1e-05; 147s
network 6, training 3, epoch 800: train scaled MSE 0.000388002; val RMSE 0.002474962; lr 1e-05; 149s
network 6, training 3, epoch 810: train scaled MSE 0.000384033; val RMSE 0.002474273; lr 1e-05; 151s
network 6, training 3, epoch 820: train scaled MSE 0.000391837; val RMSE 0.002475125; lr 1e-05; 153s
network 6, training 3, epoch 830: train scaled MSE 0.000382272; val RMSE 0.002473985; lr 1e-05; 155s
network 6, training 3, epoch 840: train scaled MSE 0.000381182; val RMSE 0.002473401; lr 1e-05; 157s
network 6, training 3, epoch 850: train scaled MSE 0.000381249; val RMSE 0.002473472; lr 1e-05; 159s
network 6, training 3, epoch 860: train scaled MSE 0.00038118; val RMSE 0.002473572; lr 1e-05; 160s
network 6, training 3, epoch 870: train scaled MSE 0.000380086; val RMSE 0.002474031; lr 1e-05; 162s
network 6, training 3, epoch 880: train scaled MSE 0.000378604; val RMSE 0.002472667; lr 1e-05; 164s
network 6, training 3, epoch 890: train scaled MSE 0.000382084; val RMSE 0.002473677; lr 1e-05; 166s
network 6, training 3, epoch 900: train scaled MSE 0.000375862; val RMSE 0.002473511; lr 1e-05; 168s
network 6, training 3, epoch 910: train scaled MSE 0.000377311; val RMSE 0.002473312; lr 1e-05; 170s
network 6, training 3, epoch 920: train scaled MSE 0.000377951; val RMSE 0.002474207; lr 1e-05; 172s
Standard Linear Baseline Validation RMSE: 0.003022422

Network seed 6, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0025,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0025,0.2003,"[-2.81%, 2.14%]",0.1285,0.0,0.0262
MLP,0.0023,13.4273,"[-6.06%, 25.25%]",0.4691,265.1548,0.1509

network 6, training 4, epoch 1: train scaled MSE 0.857012; val RMSE 0.02588473; lr 0.001; 0s
network 6, training 4, epoch 10: train scaled MSE 0.0171333; val RMSE 0.005048568; lr 0.001; 2s
network 6, training 4, epoch 20: train scaled MSE 0.013965; val RMSE 0.003887347; lr 0.001; 4s
network 6, training 4, epoch 30: train scaled MSE 0.00684841; val RMSE 0.003490395; lr 0.001; 6s
network 6, training 4, epoch 40: train scaled MSE 0.00577517; val RMSE 0.00366504; lr 0.001; 7s
network 6, training 4, epoch 50: train scaled MSE 0.00451265; val RMSE 0.003658481; lr 0.001; 9s
network 6, training 4, epoch 60: train scaled MSE 0.00409835; val RMSE 0.003243834; lr 0.001; 11s
network 6, training 4, epoch 70: train scaled MSE 0.00290858; val RMSE 0.00319346; lr 0.0005; 13s
network 6, training 4, epoch 80: train scaled MSE 0.00252531; val RMSE 0.00314253; lr 0.0005; 15s
network 6, training 4, epoch 90: train scaled MSE 0.00224235; val RMSE 0.003128505; lr 0.0005; 17s
network 6, training 4, epoch 100: train scaled MSE 0.00194834; val RMSE 0.003107997; lr 0.0005; 18s
network 6, training 4, epoch 110: train scaled MSE 0.00183646; val RMSE 0.003657704; lr 0.0005; 21s
network 6, training 4, epoch 120: train scaled MSE 0.00234694; val RMSE 0.003097549; lr 0.0005; 23s
network 6, training 4, epoch 130: train scaled MSE 0.0013575; val RMSE 0.003039086; lr 0.00025; 25s
network 6, training 4, epoch 140: train scaled MSE 0.00125159; val RMSE 0.00303375; lr 0.00025; 27s
network 6, training 4, epoch 150: train scaled MSE 0.00167954; val RMSE 0.003045469; lr 0.00025; 29s
network 6, training 4, epoch 160: train scaled MSE 0.00115321; val RMSE 0.003019157; lr 0.00025; 31s
network 6, training 4, epoch 170: train scaled MSE 0.0011946; val RMSE 0.003022441; lr 0.00025; 33s
network 6, training 4, epoch 180: train scaled MSE 0.0010294; val RMSE 0.003003323; lr 0.00025; 35s
network 6, training 4, epoch 190: train scaled MSE 0.000994066; val RMSE 0.003000161; lr 0.00025; 37s
network 6, training 4, epoch 200: train scaled MSE 0.000946572; val RMSE 0.003019811; lr 0.00025; 39s
network 6, training 4, epoch 210: train scaled MSE 0.000880403; val RMSE 0.003076468; lr 0.00025; 41s
network 6, training 4, epoch 220: train scaled MSE 0.00084434; val RMSE 0.002994959; lr 0.00025; 43s
network 6, training 4, epoch 230: train scaled MSE 0.00221354; val RMSE 0.002979636; lr 0.00025; 45s
network 6, training 4, epoch 240: train scaled MSE 0.000872946; val RMSE 0.002999935; lr 0.00025; 47s
network 6, training 4, epoch 250: train scaled MSE 0.000692733; val RMSE 0.002974593; lr 0.000125; 49s
network 6, training 4, epoch 260: train scaled MSE 0.000669391; val RMSE 0.002970348; lr 0.000125; 51s
network 6, training 4, epoch 270: train scaled MSE 0.00150713; val RMSE 0.002985955; lr 0.000125; 53s
network 6, training 4, epoch 280: train scaled MSE 0.000632871; val RMSE 0.00296684; lr 6.25e-05; 55s
network 6, training 4, epoch 290: train scaled MSE 0.000623789; val RMSE 0.002965558; lr 6.25e-05; 57s
network 6, training 4, epoch 300: train scaled MSE 0.000611611; val RMSE 0.002967613; lr 6.25e-05; 59s
network 6, training 4, epoch 310: train scaled MSE 0.000637092; val RMSE 0.002965604; lr 6.25e-05; 61s
network 6, training 4, epoch 320: train scaled MSE 0.000593499; val RMSE 0.002960025; lr 6.25e-05; 63s
network 6, training 4, epoch 330: train scaled MSE 0.000584728; val RMSE 0.002960227; lr 6.25e-05; 65s
network 6, training 4, epoch 340: train scaled MSE 0.000612962; val RMSE 0.002960027; lr 6.25e-05; 67s
network 6, training 4, epoch 350: train scaled MSE 0.000565926; val RMSE 0.002957458; lr 6.25e-05; 69s
network 6, training 4, epoch 360: train scaled MSE 0.000555184; val RMSE 0.002969564; lr 6.25e-05; 71s
network 6, training 4, epoch 370: train scaled MSE 0.000549064; val RMSE 0.00295516; lr 6.25e-05; 73s
network 6, training 4, epoch 380: train scaled MSE 0.000604098; val RMSE 0.002964037; lr 6.25e-05; 75s
network 6, training 4, epoch 390: train scaled MSE 0.000548508; val RMSE 0.002954275; lr 6.25e-05; 76s
network 6, training 4, epoch 400: train scaled MSE 0.000525381; val RMSE 0.002951369; lr 3.125e-05; 78s
network 6, training 4, epoch 410: train scaled MSE 0.000514577; val RMSE 0.002950432; lr 3.125e-05; 80s
network 6, training 4, epoch 420: train scaled MSE 0.000522302; val RMSE 0.002952083; lr 1.5625e-05; 82s
network 6, training 4, epoch 430: train scaled MSE 0.000505794; val RMSE 0.002949539; lr 1.5625e-05; 84s
network 6, training 4, epoch 440: train scaled MSE 0.000502652; val RMSE 0.002949036; lr 1.5625e-05; 86s
network 6, training 4, epoch 450: train scaled MSE 0.000500765; val RMSE 0.002948838; lr 1.5625e-05; 87s
network 6, training 4, epoch 460: train scaled MSE 0.000502525; val RMSE 0.002949262; lr 1.5625e-05; 89s
network 6, training 4, epoch 470: train scaled MSE 0.000497618; val RMSE 0.002948571; lr 1e-05; 91s
network 6, training 4, epoch 480: train scaled MSE 0.000494403; val RMSE 0.002948219; lr 1e-05; 93s
network 6, training 4, epoch 490: train scaled MSE 0.00049321; val RMSE 0.002948434; lr 1e-05; 95s
network 6, training 4, epoch 500: train scaled MSE 0.000492001; val RMSE 0.002947734; lr 1e-05; 97s
network 6, training 4, epoch 510: train scaled MSE 0.000491943; val RMSE 0.00294795; lr 1e-05; 99s
network 6, training 4, epoch 520: train scaled MSE 0.000488958; val RMSE 0.002947721; lr 1e-05; 101s
network 6, training 4, epoch 530: train scaled MSE 0.000489253; val RMSE 0.002946206; lr 1e-05; 103s
network 6, training 4, epoch 540: train scaled MSE 0.000487657; val RMSE 0.002947294; lr 1e-05; 104s
network 6, training 4, epoch 550: train scaled MSE 0.000487828; val RMSE 0.002947426; lr 1e-05; 106s
network 6, training 4, epoch 560: train scaled MSE 0.000484806; val RMSE 0.002946284; lr 1e-05; 108s
network 6, training 4, epoch 570: train scaled MSE 0.000483298; val RMSE 0.002946252; lr 1e-05; 110s
network 6, training 4, epoch 580: train scaled MSE 0.000483502; val RMSE 0.002946901; lr 1e-05; 112s
network 6, training 4, epoch 590: train scaled MSE 0.000484686; val RMSE 0.002946596; lr 1e-05; 114s
network 6, training 4, epoch 600: train scaled MSE 0.000480519; val RMSE 0.002946596; lr 1e-05; 116s
Standard Linear Baseline Validation RMSE: 0.003330033

Network seed 6, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0026,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0026,0.8037,"[-1.76%, 2.77%]",0.1330,0.0,0.0431
MLP,0.0023,22.3656,"[4.57%, 37.25%]",0.5452,310.0192,0.0430

network 6, training 5, epoch 1: train scaled MSE 0.843294; val RMSE 0.02508835; lr 0.001; 0s
network 6, training 5, epoch 10: train scaled MSE 0.0180201; val RMSE 0.004763248; lr 0.001; 2s
network 6, training 5, epoch 20: train scaled MSE 0.00878543; val RMSE 0.003013213; lr 0.001; 4s
network 6, training 5, epoch 30: train scaled MSE 0.00719364; val RMSE 0.002933875; lr 0.001; 6s
network 6, training 5, epoch 40: train scaled MSE 0.00635374; val RMSE 0.003192799; lr 0.001; 7s
network 6, training 5, epoch 50: train scaled MSE 0.00553783; val RMSE 0.002829268; lr 0.001; 9s
network 6, training 5, epoch 60: train scaled MSE 0.00504586; val RMSE 0.002562364; lr 0.001; 11s
network 6, training 5, epoch 70: train scaled MSE 0.00275725; val RMSE 0.002522597; lr 0.001; 13s
network 6, training 5, epoch 80: train scaled MSE 0.00202651; val RMSE 0.002634454; lr 0.001; 15s
network 6, training 5, epoch 90: train scaled MSE 0.00208101; val RMSE 0.002505894; lr 0.001; 17s
network 6, training 5, epoch 100: train scaled MSE 0.00163353; val RMSE 0.002431641; lr 0.001; 19s
network 6, training 5, epoch 110: train scaled MSE 0.00142958; val RMSE 0.002582795; lr 0.001; 20s
network 6, training 5, epoch 120: train scaled MSE 0.00164047; val RMSE 0.002396393; lr 0.001; 22s
network 6, training 5, epoch 130: train scaled MSE 0.000832817; val RMSE 0.002323822; lr 0.0005; 24s
network 6, training 5, epoch 140: train scaled MSE 0.000786624; val RMSE 0.00231025; lr 0.0005; 26s
network 6, training 5, epoch 150: train scaled MSE 0.000955042; val RMSE 0.002310004; lr 0.0005; 28s
network 6, training 5, epoch 160: train scaled MSE 0.00066568; val RMSE 0.002288199; lr 0.00025; 30s
network 6, training 5, epoch 170: train scaled MSE 0.000605214; val RMSE 0.002413141; lr 0.00025; 32s
network 6, training 5, epoch 180: train scaled MSE 0.000588185; val RMSE 0.002281493; lr 0.00025; 34s
network 6, training 5, epoch 190: train scaled MSE 0.000569645; val RMSE 0.002279286; lr 0.00025; 36s
network 6, training 5, epoch 200: train scaled MSE 0.000553916; val RMSE 0.002271799; lr 0.00025; 38s
network 6, training 5, epoch 210: train scaled MSE 0.000526368; val RMSE 0.002271797; lr 0.00025; 40s
network 6, training 5, epoch 220: train scaled MSE 0.00050964; val RMSE 0.002330361; lr 0.00025; 42s
network 6, training 5, epoch 230: train scaled MSE 0.000461322; val RMSE 0.002258816; lr 0.000125; 44s
network 6, training 5, epoch 240: train scaled MSE 0.000447328; val RMSE 0.002268143; lr 0.000125; 46s
network 6, training 5, epoch 250: train scaled MSE 0.000503105; val RMSE 0.00226187; lr 0.000125; 48s
network 6, training 5, epoch 260: train scaled MSE 0.000433832; val RMSE 0.002248394; lr 0.000125; 50s
network 6, training 5, epoch 270: train scaled MSE 0.0004186; val RMSE 0.002247047; lr 0.000125; 52s
network 6, training 5, epoch 280: train scaled MSE 0.000412032; val RMSE 0.002245805; lr 0.000125; 54s
network 6, training 5, epoch 290: train scaled MSE 0.000397936; val RMSE 0.002236882; lr 0.000125; 57s
network 6, training 5, epoch 300: train scaled MSE 0.000389288; val RMSE 0.002236155; lr 0.000125; 59s
network 6, training 5, epoch 310: train scaled MSE 0.000380728; val RMSE 0.002234423; lr 0.000125; 61s
network 6, training 5, epoch 320: train scaled MSE 0.00035795; val RMSE 0.002230117; lr 6.25e-05; 63s
network 6, training 5, epoch 330: train scaled MSE 0.000352261; val RMSE 0.002229939; lr 6.25e-05; 65s
network 6, training 5, epoch 340: train scaled MSE 0.000349382; val RMSE 0.002234809; lr 6.25e-05; 67s
network 6, training 5, epoch 350: train scaled MSE 0.000338254; val RMSE 0.002226196; lr 3.125e-05; 69s
network 6, training 5, epoch 360: train scaled MSE 0.000411341; val RMSE 0.002230225; lr 3.125e-05; 71s
network 6, training 5, epoch 370: train scaled MSE 0.000330136; val RMSE 0.002225992; lr 1.5625e-05; 73s
network 6, training 5, epoch 380: train scaled MSE 0.000343022; val RMSE 0.00222625; lr 1.5625e-05; 75s
network 6, training 5, epoch 390: train scaled MSE 0.000342458; val RMSE 0.00222528; lr 1.5625e-05; 77s
network 6, training 5, epoch 400: train scaled MSE 0.000336451; val RMSE 0.002224405; lr 1.5625e-05; 79s
network 6, training 5, epoch 410: train scaled MSE 0.000324578; val RMSE 0.002223071; lr 1e-05; 81s
network 6, training 5, epoch 420: train scaled MSE 0.000324108; val RMSE 0.002223695; lr 1e-05; 83s
network 6, training 5, epoch 430: train scaled MSE 0.000325703; val RMSE 0.002223509; lr 1e-05; 86s
network 6, training 5, epoch 440: train scaled MSE 0.000321682; val RMSE 0.002222404; lr 1e-05; 88s
network 6, training 5, epoch 450: train scaled MSE 0.000337334; val RMSE 0.00222515; lr 1e-05; 90s
network 6, training 5, epoch 460: train scaled MSE 0.000343339; val RMSE 0.002225364; lr 1e-05; 92s
network 6, training 5, epoch 470: train scaled MSE 0.000319419; val RMSE 0.002221147; lr 1e-05; 94s
network 6, training 5, epoch 480: train scaled MSE 0.000318474; val RMSE 0.002221217; lr 1e-05; 96s
network 6, training 5, epoch 490: train scaled MSE 0.000318502; val RMSE 0.002220822; lr 1e-05; 98s
network 6, training 5, epoch 500: train scaled MSE 0.000317281; val RMSE 0.002220383; lr 1e-05; 100s
network 6, training 5, epoch 510: train scaled MSE 0.000316684; val RMSE 0.002220673; lr 1e-05; 102s
network 6, training 5, epoch 520: train scaled MSE 0.000316429; val RMSE 0.002220121; lr 1e-05; 105s
network 6, training 5, epoch 530: train scaled MSE 0.000314737; val RMSE 0.002219792; lr 1e-05; 107s
network 6, training 5, epoch 540: train scaled MSE 0.000315967; val RMSE 0.002219839; lr 1e-05; 109s
network 6, training 5, epoch 550: train scaled MSE 0.000313027; val RMSE 0.002219694; lr 1e-05; 111s
network 6, training 5, epoch 560: train scaled MSE 0.000324092; val RMSE 0.002220636; lr 1e-05; 113s
network 6, training 5, epoch 570: train scaled MSE 0.000311514; val RMSE 0.002218693; lr 1e-05; 115s
network 6, training 5, epoch 580: train scaled MSE 0.000313909; val RMSE 0.002219082; lr 1e-05; 117s
network 6, training 5, epoch 590: train scaled MSE 0.000310947; val RMSE 0.00221898; lr 1e-05; 119s
network 6, training 5, epoch 600: train scaled MSE 0.000309327; val RMSE 0.002218405; lr 1e-05; 121s
network 6, training 5, epoch 610: train scaled MSE 0.000309007; val RMSE 0.002218481; lr 1e-05; 124s
network 6, training 5, epoch 620: train scaled MSE 0.000308377; val RMSE 0.002218039; lr 1e-05; 126s
network 6, training 5, epoch 630: train scaled MSE 0.000307418; val RMSE 0.002217486; lr 1e-05; 128s
network 6, training 5, epoch 640: train scaled MSE 0.000308181; val RMSE 0.002217731; lr 1e-05; 130s
network 6, training 5, epoch 650: train scaled MSE 0.000306156; val RMSE 0.002217082; lr 1e-05; 132s
network 6, training 5, epoch 660: train scaled MSE 0.000305253; val RMSE 0.002217456; lr 1e-05; 134s
network 6, training 5, epoch 670: train scaled MSE 0.000315827; val RMSE 0.002220043; lr 1e-05; 136s
network 6, training 5, epoch 680: train scaled MSE 0.00030408; val RMSE 0.002216505; lr 1e-05; 139s
network 6, training 5, epoch 690: train scaled MSE 0.000302854; val RMSE 0.002216526; lr 1e-05; 141s
network 6, training 5, epoch 700: train scaled MSE 0.000302648; val RMSE 0.002215866; lr 1e-05; 143s
network 6, training 5, epoch 710: train scaled MSE 0.00030279; val RMSE 0.002216045; lr 1e-05; 145s
network 6, training 5, epoch 720: train scaled MSE 0.000301378; val RMSE 0.002216229; lr 1e-05; 147s
network 6, training 5, epoch 730: train scaled MSE 0.000306138; val RMSE 0.002217; lr 1e-05; 149s
network 6, training 5, epoch 740: train scaled MSE 0.000301211; val RMSE 0.002215729; lr 1e-05; 151s
network 6, training 5, epoch 750: train scaled MSE 0.000299016; val RMSE 0.002214835; lr 1e-05; 153s
network 6, training 5, epoch 760: train scaled MSE 0.00032639; val RMSE 0.002216494; lr 1e-05; 155s
network 6, training 5, epoch 770: train scaled MSE 0.000297441; val RMSE 0.002214166; lr 1e-05; 158s
network 6, training 5, epoch 780: train scaled MSE 0.000301564; val RMSE 0.002214665; lr 1e-05; 160s
network 6, training 5, epoch 790: train scaled MSE 0.000296459; val RMSE 0.002214729; lr 1e-05; 162s
network 6, training 5, epoch 800: train scaled MSE 0.000295443; val RMSE 0.002214242; lr 1e-05; 164s
network 6, training 5, epoch 810: train scaled MSE 0.000294819; val RMSE 0.002214278; lr 1e-05; 166s
network 6, training 5, epoch 820: train scaled MSE 0.000295731; val RMSE 0.002214607; lr 1e-05; 168s
network 6, training 5, epoch 830: train scaled MSE 0.00029651; val RMSE 0.002214103; lr 1e-05; 170s
network 6, training 5, epoch 840: train scaled MSE 0.000296079; val RMSE 0.002214173; lr 1e-05; 172s
network 6, training 5, epoch 850: train scaled MSE 0.000302582; val RMSE 0.002215249; lr 1e-05; 174s
network 6, training 5, epoch 860: train scaled MSE 0.00029394; val RMSE 0.002214261; lr 1e-05; 177s
network 6, training 5, epoch 870: train scaled MSE 0.000290776; val RMSE 0.00221332; lr 1e-05; 179s
network 6, training 5, epoch 880: train scaled MSE 0.000292068; val RMSE 0.002213465; lr 1e-05; 181s
network 6, training 5, epoch 890: train scaled MSE 0.000290062; val RMSE 0.002213105; lr 1e-05; 183s
network 6, training 5, epoch 900: train scaled MSE 0.000289889; val RMSE 0.002213056; lr 1e-05; 184s
network 6, training 5, epoch 910: train scaled MSE 0.000288463; val RMSE 0.002212637; lr 1e-05; 186s
network 6, training 5, epoch 920: train scaled MSE 0.000288556; val RMSE 0.002212811; lr 1e-05; 188s
network 6, training 5, epoch 930: train scaled MSE 0.000287173; val RMSE 0.002212365; lr 1e-05; 191s
network 6, training 5, epoch 940: train scaled MSE 0.000287108; val RMSE 0.002212754; lr 1e-05; 193s
network 6, training 5, epoch 950: train scaled MSE 0.000286266; val RMSE 0.002211577; lr 1e-05; 195s
network 6, training 5, epoch 960: train scaled MSE 0.000287322; val RMSE 0.002211969; lr 1e-05; 197s
network 6, training 5, epoch 970: train scaled MSE 0.000291169; val RMSE 0.002212395; lr 1e-05; 198s
network 6, training 5, epoch 980: train scaled MSE 0.000293729; val RMSE 0.002212738; lr 1e-05; 200s
network 6, training 5, epoch 990: train scaled MSE 0.000285441; val RMSE 0.002211935; lr 1e-05; 202s
network 6, training 5, epoch 1000: train scaled MSE 0.00028405; val RMSE 0.002210975; lr 1e-05; 204s
network 6, training 5, epoch 1010: train scaled MSE 0.000283225; val RMSE 0.002210827; lr 1e-05; 206s
network 6, training 5, epoch 1020: train scaled MSE 0.000281846; val RMSE 0.002210521; lr 1e-05; 208s
network 6, training 5, epoch 1030: train scaled MSE 0.00028094; val RMSE 0.00220983; lr 1e-05; 210s
network 6, training 5, epoch 1040: train scaled MSE 0.000280802; val RMSE 0.002210487; lr 1e-05; 212s
network 6, training 5, epoch 1050: train scaled MSE 0.000280571; val RMSE 0.002211054; lr 1e-05; 214s
network 6, training 5, epoch 1060: train scaled MSE 0.000286096; val RMSE 0.002210143; lr 1e-05; 216s
network 6, training 5, epoch 1070: train scaled MSE 0.000278362; val RMSE 0.002209716; lr 1e-05; 218s
Standard Linear Baseline Validation RMSE: 0.00249733

Network seed 6, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0029,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0029,1.6338,"[-0.08%, 2.75%]",0.1359,0.0,0.0308
MLP,0.0026,20.3116,"[8.56%, 28.80%]",0.4877,258.9282,0.1894

network 6, training 6, epoch 1: train scaled MSE 0.854063; val RMSE 0.02527907; lr 0.001; 0s
network 6, training 6, epoch 10: train scaled MSE 0.0261221; val RMSE 0.005794674; lr 0.001; 2s
network 6, training 6, epoch 20: train scaled MSE 0.0121378; val RMSE 0.003470529; lr 0.001; 4s
network 6, training 6, epoch 30: train scaled MSE 0.0114786; val RMSE 0.003165974; lr 0.001; 6s
network 6, training 6, epoch 40: train scaled MSE 0.00771518; val RMSE 0.00303799; lr 0.001; 8s
network 6, training 6, epoch 50: train scaled MSE 0.00593456; val RMSE 0.008551528; lr 0.001; 10s
network 6, training 6, epoch 60: train scaled MSE 0.0046048; val RMSE 0.002875407; lr 0.0005; 12s
network 6, training 6, epoch 70: train scaled MSE 0.00386886; val RMSE 0.002857666; lr 0.0005; 14s
network 6, training 6, epoch 80: train scaled MSE 0.00333947; val RMSE 0.0028825; lr 0.0005; 16s
network 6, training 6, epoch 90: train scaled MSE 0.0029043; val RMSE 0.002816; lr 0.0005; 18s
network 6, training 6, epoch 100: train scaled MSE 0.00249161; val RMSE 0.002813513; lr 0.0005; 20s
network 6, training 6, epoch 110: train scaled MSE 0.00215969; val RMSE 0.002813168; lr 0.0005; 22s
network 6, training 6, epoch 120: train scaled MSE 0.00222083; val RMSE 0.002777821; lr 0.0005; 25s
network 6, training 6, epoch 130: train scaled MSE 0.00175203; val RMSE 0.00277268; lr 0.0005; 27s
network 6, training 6, epoch 140: train scaled MSE 0.00171135; val RMSE 0.002783191; lr 0.0005; 29s
network 6, training 6, epoch 150: train scaled MSE 0.00141574; val RMSE 0.002774387; lr 0.0005; 31s
network 6, training 6, epoch 160: train scaled MSE 0.00126753; val RMSE 0.002796503; lr 0.0005; 33s
network 6, training 6, epoch 170: train scaled MSE 0.00119735; val RMSE 0.002765836; lr 0.0005; 35s
network 6, training 6, epoch 180: train scaled MSE 0.000939545; val RMSE 0.002749986; lr 0.00025; 37s
network 6, training 6, epoch 190: train scaled MSE 0.000896002; val RMSE 0.002737425; lr 0.00025; 39s
network 6, training 6, epoch 200: train scaled MSE 0.000861975; val RMSE 0.002737456; lr 0.00025; 41s
network 6, training 6, epoch 210: train scaled MSE 0.000780226; val RMSE 0.002728384; lr 0.000125; 43s
network 6, training 6, epoch 220: train scaled MSE 0.00094447; val RMSE 0.002779991; lr 0.000125; 45s
network 6, training 6, epoch 230: train scaled MSE 0.000718316; val RMSE 0.002720907; lr 6.25e-05; 47s
network 6, training 6, epoch 240: train scaled MSE 0.000708496; val RMSE 0.002722291; lr 6.25e-05; 49s
network 6, training 6, epoch 250: train scaled MSE 0.000694454; val RMSE 0.002717876; lr 3.125e-05; 51s
network 6, training 6, epoch 260: train scaled MSE 0.000687892; val RMSE 0.002717807; lr 3.125e-05; 53s
network 6, training 6, epoch 270: train scaled MSE 0.000685338; val RMSE 0.002718569; lr 1.5625e-05; 55s
network 6, training 6, epoch 280: train scaled MSE 0.000673803; val RMSE 0.002716332; lr 1.5625e-05; 57s
network 6, training 6, epoch 290: train scaled MSE 0.000670575; val RMSE 0.002715876; lr 1.5625e-05; 59s
network 6, training 6, epoch 300: train scaled MSE 0.000668302; val RMSE 0.002715031; lr 1.5625e-05; 61s
network 6, training 6, epoch 310: train scaled MSE 0.000671501; val RMSE 0.002714796; lr 1.5625e-05; 63s
network 6, training 6, epoch 320: train scaled MSE 0.000658601; val RMSE 0.002714109; lr 1e-05; 65s
network 6, training 6, epoch 330: train scaled MSE 0.000689621; val RMSE 0.002717548; lr 1e-05; 67s
network 6, training 6, epoch 340: train scaled MSE 0.000654422; val RMSE 0.002713928; lr 1e-05; 69s
network 6, training 6, epoch 350: train scaled MSE 0.000651835; val RMSE 0.002713256; lr 1e-05; 71s
network 6, training 6, epoch 360: train scaled MSE 0.000653308; val RMSE 0.002714158; lr 1e-05; 73s
network 6, training 6, epoch 370: train scaled MSE 0.000647922; val RMSE 0.002713485; lr 1e-05; 75s
network 6, training 6, epoch 380: train scaled MSE 0.000648708; val RMSE 0.00271324; lr 1e-05; 77s
network 6, training 6, epoch 390: train scaled MSE 0.000643843; val RMSE 0.002712262; lr 1e-05; 79s
network 6, training 6, epoch 400: train scaled MSE 0.000643019; val RMSE 0.002712121; lr 1e-05; 82s
network 6, training 6, epoch 410: train scaled MSE 0.000639779; val RMSE 0.002711749; lr 1e-05; 84s
network 6, training 6, epoch 420: train scaled MSE 0.000650574; val RMSE 0.002713283; lr 1e-05; 86s
network 6, training 6, epoch 430: train scaled MSE 0.000636383; val RMSE 0.00271091; lr 1e-05; 88s
network 6, training 6, epoch 440: train scaled MSE 0.000634676; val RMSE 0.002710895; lr 1e-05; 90s
network 6, training 6, epoch 450: train scaled MSE 0.000632064; val RMSE 0.002710909; lr 1e-05; 92s
network 6, training 6, epoch 460: train scaled MSE 0.00063016; val RMSE 0.002710197; lr 1e-05; 94s
network 6, training 6, epoch 470: train scaled MSE 0.000629087; val RMSE 0.002710408; lr 1e-05; 96s
network 6, training 6, epoch 480: train scaled MSE 0.000625409; val RMSE 0.002709694; lr 1e-05; 98s
network 6, training 6, epoch 490: train scaled MSE 0.000623366; val RMSE 0.002710145; lr 1e-05; 100s
network 6, training 6, epoch 500: train scaled MSE 0.000621624; val RMSE 0.002709012; lr 1e-05; 102s
network 6, training 6, epoch 510: train scaled MSE 0.000619078; val RMSE 0.002708922; lr 1e-05; 104s
network 6, training 6, epoch 520: train scaled MSE 0.000618795; val RMSE 0.002709336; lr 1e-05; 106s
network 6, training 6, epoch 530: train scaled MSE 0.000614999; val RMSE 0.0027086; lr 1e-05; 108s
network 6, training 6, epoch 540: train scaled MSE 0.000615318; val RMSE 0.002708396; lr 1e-05; 110s
network 6, training 6, epoch 550: train scaled MSE 0.000613036; val RMSE 0.00270845; lr 1e-05; 113s
network 6, training 6, epoch 560: train scaled MSE 0.000608483; val RMSE 0.002707756; lr 1e-05; 115s
network 6, training 6, epoch 570: train scaled MSE 0.000606686; val RMSE 0.002707405; lr 1e-05; 117s
network 6, training 6, epoch 580: train scaled MSE 0.000604409; val RMSE 0.002707205; lr 1e-05; 119s
network 6, training 6, epoch 590: train scaled MSE 0.000602417; val RMSE 0.00270699; lr 1e-05; 121s
network 6, training 6, epoch 600: train scaled MSE 0.000601408; val RMSE 0.002706954; lr 1e-05; 123s
network 6, training 6, epoch 610: train scaled MSE 0.000598381; val RMSE 0.002706608; lr 1e-05; 125s
network 6, training 6, epoch 620: train scaled MSE 0.000595852; val RMSE 0.002706366; lr 1e-05; 127s
network 6, training 6, epoch 630: train scaled MSE 0.000594562; val RMSE 0.002706062; lr 1e-05; 130s
network 6, training 6, epoch 640: train scaled MSE 0.000591749; val RMSE 0.002705744; lr 1e-05; 132s
network 6, training 6, epoch 650: train scaled MSE 0.000589804; val RMSE 0.002705611; lr 1e-05; 134s
network 6, training 6, epoch 660: train scaled MSE 0.000588216; val RMSE 0.002705994; lr 1e-05; 136s
network 6, training 6, epoch 670: train scaled MSE 0.000586861; val RMSE 0.002705098; lr 1e-05; 138s
network 6, training 6, epoch 680: train scaled MSE 0.000583544; val RMSE 0.002704743; lr 1e-05; 140s
network 6, training 6, epoch 690: train scaled MSE 0.000581233; val RMSE 0.002705407; lr 1e-05; 142s
network 6, training 6, epoch 700: train scaled MSE 0.000589641; val RMSE 0.002706079; lr 1e-05; 144s
network 6, training 6, epoch 710: train scaled MSE 0.000577064; val RMSE 0.002705578; lr 1e-05; 146s
network 6, training 6, epoch 720: train scaled MSE 0.000575707; val RMSE 0.002704458; lr 1e-05; 148s
network 6, training 6, epoch 730: train scaled MSE 0.000577519; val RMSE 0.002704604; lr 1e-05; 150s
network 6, training 6, epoch 740: train scaled MSE 0.000576244; val RMSE 0.002704025; lr 1e-05; 152s
network 6, training 6, epoch 750: train scaled MSE 0.000598785; val RMSE 0.002709927; lr 1e-05; 154s
network 6, training 6, epoch 760: train scaled MSE 0.00056888; val RMSE 0.002703735; lr 1e-05; 156s
network 6, training 6, epoch 770: train scaled MSE 0.000568607; val RMSE 0.002703961; lr 1e-05; 158s
network 6, training 6, epoch 780: train scaled MSE 0.000565651; val RMSE 0.002703105; lr 1e-05; 160s
network 6, training 6, epoch 790: train scaled MSE 0.000564377; val RMSE 0.002703036; lr 1e-05; 162s
network 6, training 6, epoch 800: train scaled MSE 0.00056293; val RMSE 0.00270262; lr 1e-05; 164s
network 6, training 6, epoch 810: train scaled MSE 0.000560676; val RMSE 0.002702475; lr 1e-05; 167s
network 6, training 6, epoch 820: train scaled MSE 0.000559941; val RMSE 0.002702179; lr 1e-05; 169s
network 6, training 6, epoch 830: train scaled MSE 0.000557463; val RMSE 0.002702207; lr 1e-05; 171s
network 6, training 6, epoch 840: train scaled MSE 0.000555815; val RMSE 0.002701891; lr 1e-05; 173s
network 6, training 6, epoch 850: train scaled MSE 0.000553904; val RMSE 0.002702023; lr 1e-05; 175s
network 6, training 6, epoch 860: train scaled MSE 0.00055223; val RMSE 0.002701575; lr 1e-05; 177s
network 6, training 6, epoch 870: train scaled MSE 0.000551714; val RMSE 0.002701493; lr 1e-05; 179s
network 6, training 6, epoch 880: train scaled MSE 0.000550642; val RMSE 0.002701316; lr 1e-05; 181s
network 6, training 6, epoch 890: train scaled MSE 0.000547081; val RMSE 0.002701044; lr 1e-05; 183s
network 6, training 6, epoch 900: train scaled MSE 0.000561991; val RMSE 0.002703203; lr 1e-05; 185s
network 6, training 6, epoch 910: train scaled MSE 0.000553158; val RMSE 0.002701701; lr 1e-05; 187s
network 6, training 6, epoch 920: train scaled MSE 0.0005419; val RMSE 0.002701202; lr 1e-05; 189s
network 6, training 6, epoch 930: train scaled MSE 0.000540629; val RMSE 0.002699709; lr 1e-05; 191s
network 6, training 6, epoch 940: train scaled MSE 0.000539261; val RMSE 0.002699795; lr 1e-05; 193s
network 6, training 6, epoch 950: train scaled MSE 0.000536898; val RMSE 0.002699797; lr 1e-05; 195s
network 6, training 6, epoch 960: train scaled MSE 0.000541708; val RMSE 0.002699977; lr 1e-05; 197s
network 6, training 6, epoch 970: train scaled MSE 0.000534072; val RMSE 0.002699643; lr 1e-05; 199s
network 6, training 6, epoch 980: train scaled MSE 0.000532199; val RMSE 0.002699426; lr 1e-05; 202s
network 6, training 6, epoch 990: train scaled MSE 0.00053033; val RMSE 0.002699046; lr 1e-05; 204s
network 6, training 6, epoch 1000: train scaled MSE 0.000530073; val RMSE 0.002699191; lr 1e-05; 206s
network 6, training 6, epoch 1010: train scaled MSE 0.000527432; val RMSE 0.002699108; lr 1e-05; 208s
network 6, training 6, epoch 1020: train scaled MSE 0.000526399; val RMSE 0.002699361; lr 1e-05; 210s
network 6, training 6, epoch 1030: train scaled MSE 0.000524198; val RMSE 0.002698955; lr 1e-05; 212s
network 6, training 6, epoch 1040: train scaled MSE 0.000521512; val RMSE 0.002698595; lr 1e-05; 214s
network 6, training 6, epoch 1050: train scaled MSE 0.00053409; val RMSE 0.002699893; lr 1e-05; 216s
network 6, training 6, epoch 1060: train scaled MSE 0.000524549; val RMSE 0.002699549; lr 1e-05; 218s
network 6, training 6, epoch 1070: train scaled MSE 0.000517367; val RMSE 0.00269795; lr 1e-05; 220s
network 6, training 6, epoch 1080: train scaled MSE 0.000517607; val RMSE 0.002697971; lr 1e-05; 222s
Standard Linear Baseline Validation RMSE: 0.002668662

Network seed 6, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0025,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0025,0.2045,"[-3.12%, 2.53%]",0.1380,0.0,0.0298
MLP,0.0023,19.3775,"[1.42%, 31.80%]",0.5219,278.2295,0.0384

network 6, training 7, epoch 1: train scaled MSE 0.847871; val RMSE 0.02539189; lr 0.001; 0s
network 6, training 7, epoch 10: train scaled MSE 0.0226174; val RMSE 0.004724118; lr 0.001; 2s
network 6, training 7, epoch 20: train scaled MSE 0.0120177; val RMSE 0.002663923; lr 0.001; 4s
network 6, training 7, epoch 30: train scaled MSE 0.00985731; val RMSE 0.002657283; lr 0.001; 6s
network 6, training 7, epoch 40: train scaled MSE 0.00778841; val RMSE 0.002211007; lr 0.001; 8s
network 6, training 7, epoch 50: train scaled MSE 0.00667022; val RMSE 0.002290583; lr 0.001; 10s
network 6, training 7, epoch 60: train scaled MSE 0.00531684; val RMSE 0.002131996; lr 0.001; 12s
network 6, training 7, epoch 70: train scaled MSE 0.00405839; val RMSE 0.002092543; lr 0.001; 14s
network 6, training 7, epoch 80: train scaled MSE 0.00567657; val RMSE 0.003146494; lr 0.001; 16s
network 6, training 7, epoch 90: train scaled MSE 0.00385352; val RMSE 0.002104639; lr 0.001; 18s
network 6, training 7, epoch 100: train scaled MSE 0.00189759; val RMSE 0.001942554; lr 0.0005; 19s
network 6, training 7, epoch 110: train scaled MSE 0.00259634; val RMSE 0.002242048; lr 0.0005; 21s
network 6, training 7, epoch 120: train scaled MSE 0.00147306; val RMSE 0.001946334; lr 0.0005; 23s
network 6, training 7, epoch 130: train scaled MSE 0.00133258; val RMSE 0.001899575; lr 0.0005; 25s
network 6, training 7, epoch 140: train scaled MSE 0.0011845; val RMSE 0.002188156; lr 0.0005; 27s
network 6, training 7, epoch 150: train scaled MSE 0.00197208; val RMSE 0.0018767; lr 0.00025; 29s
network 6, training 7, epoch 160: train scaled MSE 0.00104971; val RMSE 0.001834004; lr 0.00025; 31s
network 6, training 7, epoch 170: train scaled MSE 0.000905934; val RMSE 0.001822808; lr 0.00025; 33s
network 6, training 7, epoch 180: train scaled MSE 0.000869935; val RMSE 0.001820132; lr 0.00025; 35s
network 6, training 7, epoch 190: train scaled MSE 0.000806259; val RMSE 0.001809882; lr 0.00025; 37s
network 6, training 7, epoch 200: train scaled MSE 0.000766023; val RMSE 0.00180126; lr 0.00025; 39s
network 6, training 7, epoch 210: train scaled MSE 0.000720614; val RMSE 0.001811237; lr 0.00025; 41s
network 6, training 7, epoch 220: train scaled MSE 0.000705058; val RMSE 0.00218493; lr 0.00025; 43s
network 6, training 7, epoch 230: train scaled MSE 0.000648178; val RMSE 0.001787403; lr 0.00025; 45s
network 6, training 7, epoch 240: train scaled MSE 0.000658592; val RMSE 0.001794312; lr 0.00025; 47s
network 6, training 7, epoch 250: train scaled MSE 0.000733971; val RMSE 0.001814593; lr 0.00025; 49s
network 6, training 7, epoch 260: train scaled MSE 0.00156892; val RMSE 0.001820545; lr 0.00025; 51s
network 6, training 7, epoch 270: train scaled MSE 0.000553456; val RMSE 0.00177789; lr 0.00025; 53s
network 6, training 7, epoch 280: train scaled MSE 0.000528026; val RMSE 0.00176738; lr 0.00025; 55s
network 6, training 7, epoch 290: train scaled MSE 0.000495423; val RMSE 0.00176247; lr 0.00025; 57s
network 6, training 7, epoch 300: train scaled MSE 0.000513343; val RMSE 0.001768175; lr 0.00025; 59s
network 6, training 7, epoch 310: train scaled MSE 0.000456788; val RMSE 0.001752208; lr 0.000125; 61s
network 6, training 7, epoch 320: train scaled MSE 0.000420146; val RMSE 0.001748015; lr 6.25e-05; 63s
network 6, training 7, epoch 330: train scaled MSE 0.000412284; val RMSE 0.001746815; lr 6.25e-05; 65s
network 6, training 7, epoch 340: train scaled MSE 0.000408108; val RMSE 0.001742894; lr 6.25e-05; 67s
network 6, training 7, epoch 350: train scaled MSE 0.000411082; val RMSE 0.001739735; lr 6.25e-05; 69s
network 6, training 7, epoch 360: train scaled MSE 0.000445265; val RMSE 0.00173914; lr 6.25e-05; 70s
network 6, training 7, epoch 370: train scaled MSE 0.000402387; val RMSE 0.001739492; lr 6.25e-05; 72s
network 6, training 7, epoch 380: train scaled MSE 0.000384745; val RMSE 0.001735809; lr 6.25e-05; 74s
network 6, training 7, epoch 390: train scaled MSE 0.000390545; val RMSE 0.001744057; lr 6.25e-05; 76s
network 6, training 7, epoch 400: train scaled MSE 0.000374608; val RMSE 0.001733275; lr 6.25e-05; 78s
network 6, training 7, epoch 410: train scaled MSE 0.000372192; val RMSE 0.001731234; lr 6.25e-05; 80s
network 6, training 7, epoch 420: train scaled MSE 0.000363539; val RMSE 0.001730773; lr 6.25e-05; 83s
network 6, training 7, epoch 430: train scaled MSE 0.000359809; val RMSE 0.001775573; lr 6.25e-05; 85s
network 6, training 7, epoch 440: train scaled MSE 0.000355257; val RMSE 0.001725872; lr 6.25e-05; 87s
network 6, training 7, epoch 450: train scaled MSE 0.000351435; val RMSE 0.001725604; lr 6.25e-05; 89s
network 6, training 7, epoch 460: train scaled MSE 0.000347061; val RMSE 0.001728808; lr 6.25e-05; 91s
network 6, training 7, epoch 470: train scaled MSE 0.000404079; val RMSE 0.001731688; lr 6.25e-05; 93s
network 6, training 7, epoch 480: train scaled MSE 0.000359929; val RMSE 0.001721683; lr 6.25e-05; 95s
network 6, training 7, epoch 490: train scaled MSE 0.000335249; val RMSE 0.001719989; lr 6.25e-05; 97s
network 6, training 7, epoch 500: train scaled MSE 0.00033168; val RMSE 0.001718926; lr 6.25e-05; 99s
network 6, training 7, epoch 510: train scaled MSE 0.000326486; val RMSE 0.001716569; lr 6.25e-05; 101s
network 6, training 7, epoch 520: train scaled MSE 0.000323845; val RMSE 0.00171695; lr 6.25e-05; 103s
network 6, training 7, epoch 530: train scaled MSE 0.000319785; val RMSE 0.001712663; lr 3.125e-05; 105s
network 6, training 7, epoch 540: train scaled MSE 0.00030887; val RMSE 0.001712016; lr 3.125e-05; 107s
network 6, training 7, epoch 550: train scaled MSE 0.000318581; val RMSE 0.001713452; lr 3.125e-05; 109s
network 6, training 7, epoch 560: train scaled MSE 0.000304319; val RMSE 0.001710033; lr 3.125e-05; 111s
network 6, training 7, epoch 570: train scaled MSE 0.000308629; val RMSE 0.001710706; lr 3.125e-05; 112s
network 6, training 7, epoch 580: train scaled MSE 0.000299284; val RMSE 0.001709083; lr 1.5625e-05; 114s
network 6, training 7, epoch 590: train scaled MSE 0.00029742; val RMSE 0.001708173; lr 1.5625e-05; 116s
network 6, training 7, epoch 600: train scaled MSE 0.000296882; val RMSE 0.001708021; lr 1.5625e-05; 118s
network 6, training 7, epoch 610: train scaled MSE 0.00032755; val RMSE 0.001715222; lr 1.5625e-05; 120s
network 6, training 7, epoch 620: train scaled MSE 0.000294919; val RMSE 0.001707397; lr 1e-05; 122s
network 6, training 7, epoch 630: train scaled MSE 0.000293107; val RMSE 0.001707234; lr 1e-05; 124s
network 6, training 7, epoch 640: train scaled MSE 0.000292405; val RMSE 0.001706448; lr 1e-05; 126s
network 6, training 7, epoch 650: train scaled MSE 0.000300506; val RMSE 0.001707531; lr 1e-05; 128s
network 6, training 7, epoch 660: train scaled MSE 0.000291652; val RMSE 0.001706035; lr 1e-05; 130s
network 6, training 7, epoch 670: train scaled MSE 0.000312865; val RMSE 0.001711516; lr 1e-05; 131s
network 6, training 7, epoch 680: train scaled MSE 0.000290704; val RMSE 0.001705602; lr 1e-05; 133s
network 6, training 7, epoch 690: train scaled MSE 0.000289804; val RMSE 0.001705362; lr 1e-05; 135s
network 6, training 7, epoch 700: train scaled MSE 0.000289381; val RMSE 0.001705144; lr 1e-05; 137s
network 6, training 7, epoch 710: train scaled MSE 0.00028855; val RMSE 0.001706027; lr 1e-05; 139s
network 6, training 7, epoch 720: train scaled MSE 0.000288725; val RMSE 0.001704635; lr 1e-05; 141s
network 6, training 7, epoch 730: train scaled MSE 0.00028818; val RMSE 0.001704969; lr 1e-05; 143s
network 6, training 7, epoch 740: train scaled MSE 0.000286959; val RMSE 0.001704083; lr 1e-05; 145s
network 6, training 7, epoch 750: train scaled MSE 0.000286325; val RMSE 0.001703667; lr 1e-05; 147s
network 6, training 7, epoch 760: train scaled MSE 0.000291129; val RMSE 0.001704068; lr 1e-05; 149s
network 6, training 7, epoch 770: train scaled MSE 0.000285106; val RMSE 0.001703303; lr 1e-05; 151s
network 6, training 7, epoch 780: train scaled MSE 0.000287114; val RMSE 0.001704322; lr 1e-05; 152s
network 6, training 7, epoch 790: train scaled MSE 0.000284534; val RMSE 0.001703301; lr 1e-05; 154s
network 6, training 7, epoch 800: train scaled MSE 0.000283227; val RMSE 0.001703098; lr 1e-05; 156s
network 6, training 7, epoch 810: train scaled MSE 0.000282525; val RMSE 0.001702892; lr 1e-05; 158s
network 6, training 7, epoch 820: train scaled MSE 0.000281843; val RMSE 0.001702505; lr 1e-05; 160s
network 6, training 7, epoch 830: train scaled MSE 0.000282196; val RMSE 0.001702607; lr 1e-05; 162s
network 6, training 7, epoch 840: train scaled MSE 0.000285548; val RMSE 0.001703133; lr 1e-05; 164s
network 6, training 7, epoch 850: train scaled MSE 0.000280271; val RMSE 0.001702036; lr 1e-05; 166s
network 6, training 7, epoch 860: train scaled MSE 0.00027988; val RMSE 0.001701761; lr 1e-05; 167s
network 6, training 7, epoch 870: train scaled MSE 0.000282454; val RMSE 0.001702228; lr 1e-05; 169s
network 6, training 7, epoch 880: train scaled MSE 0.000278724; val RMSE 0.00170129; lr 1e-05; 171s
network 6, training 7, epoch 890: train scaled MSE 0.000278438; val RMSE 0.001701354; lr 1e-05; 173s
network 6, training 7, epoch 900: train scaled MSE 0.00027812; val RMSE 0.001701197; lr 1e-05; 175s
network 6, training 7, epoch 910: train scaled MSE 0.000283288; val RMSE 0.001701104; lr 1e-05; 177s
network 6, training 7, epoch 920: train scaled MSE 0.000277227; val RMSE 0.00170073; lr 1e-05; 179s
network 6, training 7, epoch 930: train scaled MSE 0.000276216; val RMSE 0.001700344; lr 1e-05; 181s
network 6, training 7, epoch 940: train scaled MSE 0.00027582; val RMSE 0.001700127; lr 1e-05; 183s
network 6, training 7, epoch 950: train scaled MSE 0.000275419; val RMSE 0.001699808; lr 1e-05; 184s
network 6, training 7, epoch 960: train scaled MSE 0.00027803; val RMSE 0.001700185; lr 1e-05; 186s
network 6, training 7, epoch 970: train scaled MSE 0.000274499; val RMSE 0.001699219; lr 1e-05; 188s
network 6, training 7, epoch 980: train scaled MSE 0.000273866; val RMSE 0.001699321; lr 1e-05; 190s
network 6, training 7, epoch 990: train scaled MSE 0.000272451; val RMSE 0.001698641; lr 1e-05; 192s
network 6, training 7, epoch 1000: train scaled MSE 0.00027256; val RMSE 0.001698475; lr 1e-05; 194s
network 6, training 7, epoch 1010: train scaled MSE 0.000271907; val RMSE 0.001698447; lr 1e-05; 196s
network 6, training 7, epoch 1020: train scaled MSE 0.00028917; val RMSE 0.001701629; lr 1e-05; 198s
network 6, training 7, epoch 1030: train scaled MSE 0.000274304; val RMSE 0.001699406; lr 1e-05; 200s
network 6, training 7, epoch 1040: train scaled MSE 0.000275138; val RMSE 0.001698469; lr 1e-05; 202s
network 6, training 7, epoch 1050: train scaled MSE 0.000269546; val RMSE 0.001698042; lr 1e-05; 204s
network 6, training 7, epoch 1060: train scaled MSE 0.000270421; val RMSE 0.001697925; lr 1e-05; 206s
network 6, training 7, epoch 1070: train scaled MSE 0.000268276; val RMSE 0.001697599; lr 1e-05; 208s
network 6, training 7, epoch 1080: train scaled MSE 0.000267774; val RMSE 0.001697286; lr 1e-05; 210s
network 6, training 7, epoch 1090: train scaled MSE 0.000267526; val RMSE 0.001697084; lr 1e-05; 212s
network 6, training 7, epoch 1100: train scaled MSE 0.000267044; val RMSE 0.001696676; lr 1e-05; 214s
network 6, training 7, epoch 1110: train scaled MSE 0.000266975; val RMSE 0.001696174; lr 1e-05; 216s
network 6, training 7, epoch 1120: train scaled MSE 0.000265973; val RMSE 0.001696786; lr 1e-05; 218s
network 6, training 7, epoch 1130: train scaled MSE 0.00026628; val RMSE 0.001696606; lr 1e-05; 220s
network 6, training 7, epoch 1140: train scaled MSE 0.000266944; val RMSE 0.001696017; lr 1e-05; 222s
network 6, training 7, epoch 1150: train scaled MSE 0.000268616; val RMSE 0.001696387; lr 1e-05; 224s
network 6, training 7, epoch 1160: train scaled MSE 0.000265467; val RMSE 0.001695975; lr 1e-05; 226s
network 6, training 7, epoch 1170: train scaled MSE 0.000264014; val RMSE 0.001695589; lr 1e-05; 228s
network 6, training 7, epoch 1180: train scaled MSE 0.000265174; val RMSE 0.001695442; lr 1e-05; 229s
network 6, training 7, epoch 1190: train scaled MSE 0.000262837; val RMSE 0.001694975; lr 1e-05; 231s
network 6, training 7, epoch 1200: train scaled MSE 0.000262898; val RMSE 0.001695254; lr 1e-05; 233s
network 6, training 7, epoch 1210: train scaled MSE 0.000262081; val RMSE 0.001694706; lr 1e-05; 235s
network 6, training 7, epoch 1220: train scaled MSE 0.000264294; val RMSE 0.001696054; lr 1e-05; 237s
network 6, training 7, epoch 1230: train scaled MSE 0.000261044; val RMSE 0.001695006; lr 1e-05; 239s
network 6, training 7, epoch 1240: train scaled MSE 0.000260674; val RMSE 0.001695751; lr 1e-05; 241s
network 6, training 7, epoch 1250: train scaled MSE 0.000263692; val RMSE 0.001694827; lr 1e-05; 243s
network 6, training 7, epoch 1260: train scaled MSE 0.000259749; val RMSE 0.001694458; lr 1e-05; 245s
network 6, training 7, epoch 1270: train scaled MSE 0.000260698; val RMSE 0.001694249; lr 1e-05; 247s
network 6, training 7, epoch 1280: train scaled MSE 0.000258816; val RMSE 0.001694023; lr 1e-05; 249s
network 6, training 7, epoch 1290: train scaled MSE 0.00025882; val RMSE 0.001694081; lr 1e-05; 251s
network 6, training 7, epoch 1300: train scaled MSE 0.000259756; val RMSE 0.001693482; lr 1e-05; 253s
network 6, training 7, epoch 1310: train scaled MSE 0.000258629; val RMSE 0.001693288; lr 1e-05; 255s
network 6, training 7, epoch 1320: train scaled MSE 0.000257242; val RMSE 0.001692999; lr 1e-05; 257s
network 6, training 7, epoch 1330: train scaled MSE 0.000256684; val RMSE 0.001694642; lr 1e-05; 259s
network 6, training 7, epoch 1340: train scaled MSE 0.000256282; val RMSE 0.001693337; lr 1e-05; 260s
network 6, training 7, epoch 1350: train scaled MSE 0.000266121; val RMSE 0.001694495; lr 1e-05; 262s
network 6, training 7, epoch 1360: train scaled MSE 0.000255686; val RMSE 0.001692793; lr 1e-05; 264s
network 6, training 7, epoch 1370: train scaled MSE 0.000254981; val RMSE 0.001692385; lr 1e-05; 266s
network 6, training 7, epoch 1380: train scaled MSE 0.000258704; val RMSE 0.001692618; lr 1e-05; 268s
network 6, training 7, epoch 1390: train scaled MSE 0.000253988; val RMSE 0.001692026; lr 1e-05; 270s
network 6, training 7, epoch 1400: train scaled MSE 0.000253731; val RMSE 0.001691519; lr 1e-05; 272s
network 6, training 7, epoch 1410: train scaled MSE 0.000253098; val RMSE 0.001691727; lr 1e-05; 274s
network 6, training 7, epoch 1420: train scaled MSE 0.000252828; val RMSE 0.001691221; lr 1e-05; 276s
network 6, training 7, epoch 1430: train scaled MSE 0.000252466; val RMSE 0.001691219; lr 1e-05; 278s
network 6, training 7, epoch 1440: train scaled MSE 0.000252451; val RMSE 0.001690958; lr 1e-05; 280s
network 6, training 7, epoch 1450: train scaled MSE 0.000251743; val RMSE 0.001690995; lr 1e-05; 282s
network 6, training 7, epoch 1460: train scaled MSE 0.000250778; val RMSE 0.001690613; lr 1e-05; 284s
network 6, training 7, epoch 1470: train scaled MSE 0.000250009; val RMSE 0.001690579; lr 1e-05; 286s
network 6, training 7, epoch 1480: train scaled MSE 0.000253825; val RMSE 0.00169088; lr 1e-05; 288s
network 6, training 7, epoch 1490: train scaled MSE 0.000248865; val RMSE 0.001690177; lr 1e-05; 290s
network 6, training 7, epoch 1500: train scaled MSE 0.000248847; val RMSE 0.00168998; lr 1e-05; 292s
network 6, training 7, epoch 1510: train scaled MSE 0.000255769; val RMSE 0.001690405; lr 1e-05; 294s
network 6, training 7, epoch 1520: train scaled MSE 0.00024808; val RMSE 0.00168986; lr 1e-05; 296s
network 6, training 7, epoch 1530: train scaled MSE 0.000247225; val RMSE 0.001689752; lr 1e-05; 297s
network 6, training 7, epoch 1540: train scaled MSE 0.000247112; val RMSE 0.001689156; lr 1e-05; 299s
network 6, training 7, epoch 1550: train scaled MSE 0.000246405; val RMSE 0.001689138; lr 1e-05; 301s
network 6, training 7, epoch 1560: train scaled MSE 0.000245965; val RMSE 0.001689085; lr 1e-05; 303s
network 6, training 7, epoch 1570: train scaled MSE 0.000254434; val RMSE 0.001691562; lr 1e-05; 305s
network 6, training 7, epoch 1580: train scaled MSE 0.000248079; val RMSE 0.001689406; lr 1e-05; 307s
network 6, training 7, epoch 1590: train scaled MSE 0.000247055; val RMSE 0.001688929; lr 1e-05; 309s
network 6, training 7, epoch 1600: train scaled MSE 0.000244071; val RMSE 0.001688308; lr 1e-05; 311s
network 6, training 7, epoch 1610: train scaled MSE 0.00024424; val RMSE 0.001688263; lr 1e-05; 312s
network 6, training 7, epoch 1620: train scaled MSE 0.000243324; val RMSE 0.00168763; lr 1e-05; 314s
network 6, training 7, epoch 1630: train scaled MSE 0.000242993; val RMSE 0.001687725; lr 1e-05; 316s
network 6, training 7, epoch 1640: train scaled MSE 0.000242724; val RMSE 0.001687834; lr 1e-05; 318s
network 6, training 7, epoch 1650: train scaled MSE 0.000242175; val RMSE 0.001687305; lr 1e-05; 320s
network 6, training 7, epoch 1660: train scaled MSE 0.000246822; val RMSE 0.001687903; lr 1e-05; 321s
network 6, training 7, epoch 1670: train scaled MSE 0.000246066; val RMSE 0.001687278; lr 1e-05; 323s
network 6, training 7, epoch 1680: train scaled MSE 0.000240754; val RMSE 0.00168672; lr 1e-05; 325s
network 6, training 7, epoch 1690: train scaled MSE 0.000242212; val RMSE 0.001688132; lr 1e-05; 327s
network 6, training 7, epoch 1700: train scaled MSE 0.000243663; val RMSE 0.001689419; lr 1e-05; 329s
network 6, training 7, epoch 1710: train scaled MSE 0.000239767; val RMSE 0.001686573; lr 1e-05; 331s
network 6, training 7, epoch 1720: train scaled MSE 0.000251744; val RMSE 0.001689065; lr 1e-05; 332s
network 6, training 7, epoch 1730: train scaled MSE 0.000241558; val RMSE 0.001687247; lr 1e-05; 334s
network 6, training 7, epoch 1740: train scaled MSE 0.000238717; val RMSE 0.001686626; lr 1e-05; 336s
network 6, training 7, epoch 1750: train scaled MSE 0.000239986; val RMSE 0.001686733; lr 1e-05; 338s
Standard Linear Baseline Validation RMSE: 0.001725683

Network seed 6, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0028,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0028,1.4681,"[-0.53%, 2.85%]",0.1352,0.0,0.0266
MLP,0.0024,27.9844,"[10.94%, 41.30%]",0.5494,306.3428,0.0928

network 6, training 8, epoch 1: train scaled MSE 0.857052; val RMSE 0.02624374; lr 0.001; 0s
network 6, training 8, epoch 10: train scaled MSE 0.0199104; val RMSE 0.005064627; lr 0.001; 2s
network 6, training 8, epoch 20: train scaled MSE 0.0101545; val RMSE 0.003055874; lr 0.001; 4s
network 6, training 8, epoch 30: train scaled MSE 0.00936596; val RMSE 0.003016706; lr 0.001; 6s
network 6, training 8, epoch 40: train scaled MSE 0.00786785; val RMSE 0.003332905; lr 0.001; 7s
network 6, training 8, epoch 50: train scaled MSE 0.00551655; val RMSE 0.002511784; lr 0.001; 9s
network 6, training 8, epoch 60: train scaled MSE 0.0043831; val RMSE 0.00248267; lr 0.001; 11s
network 6, training 8, epoch 70: train scaled MSE 0.00323047; val RMSE 0.002801961; lr 0.001; 13s
network 6, training 8, epoch 80: train scaled MSE 0.00270215; val RMSE 0.002498765; lr 0.001; 15s
network 6, training 8, epoch 90: train scaled MSE 0.00208706; val RMSE 0.002463236; lr 0.001; 17s
network 6, training 8, epoch 100: train scaled MSE 0.00195845; val RMSE 0.002352149; lr 0.001; 18s
network 6, training 8, epoch 110: train scaled MSE 0.00158447; val RMSE 0.002349556; lr 0.001; 20s
network 6, training 8, epoch 120: train scaled MSE 0.00136214; val RMSE 0.002333885; lr 0.001; 22s
network 6, training 8, epoch 130: train scaled MSE 0.00125437; val RMSE 0.002319747; lr 0.001; 24s
network 6, training 8, epoch 140: train scaled MSE 0.000869355; val RMSE 0.00223838; lr 0.0005; 26s
network 6, training 8, epoch 150: train scaled MSE 0.000810119; val RMSE 0.002246455; lr 0.0005; 27s
network 6, training 8, epoch 160: train scaled MSE 0.000715495; val RMSE 0.002215615; lr 0.00025; 29s
network 6, training 8, epoch 170: train scaled MSE 0.000701915; val RMSE 0.002210829; lr 0.00025; 31s
network 6, training 8, epoch 180: train scaled MSE 0.000653664; val RMSE 0.002198805; lr 0.00025; 33s
network 6, training 8, epoch 190: train scaled MSE 0.000632719; val RMSE 0.002330332; lr 0.00025; 35s
network 6, training 8, epoch 200: train scaled MSE 0.000577446; val RMSE 0.002188781; lr 0.000125; 36s
network 6, training 8, epoch 210: train scaled MSE 0.000556856; val RMSE 0.002183738; lr 0.000125; 38s
network 6, training 8, epoch 220: train scaled MSE 0.000672429; val RMSE 0.002185692; lr 0.000125; 40s
network 6, training 8, epoch 230: train scaled MSE 0.000528051; val RMSE 0.002182851; lr 0.000125; 42s
network 6, training 8, epoch 240: train scaled MSE 0.000539333; val RMSE 0.002184042; lr 0.000125; 43s
network 6, training 8, epoch 250: train scaled MSE 0.000491828; val RMSE 0.002172134; lr 6.25e-05; 45s
network 6, training 8, epoch 260: train scaled MSE 0.000486985; val RMSE 0.002184104; lr 6.25e-05; 47s
network 6, training 8, epoch 270: train scaled MSE 0.000482108; val RMSE 0.002170025; lr 6.25e-05; 49s
network 6, training 8, epoch 280: train scaled MSE 0.000476108; val RMSE 0.002167791; lr 6.25e-05; 51s
network 6, training 8, epoch 290: train scaled MSE 0.000486352; val RMSE 0.002172057; lr 6.25e-05; 52s
network 6, training 8, epoch 300: train scaled MSE 0.000458505; val RMSE 0.00216736; lr 6.25e-05; 54s
network 6, training 8, epoch 310: train scaled MSE 0.000455053; val RMSE 0.002177557; lr 6.25e-05; 56s
network 6, training 8, epoch 320: train scaled MSE 0.000447477; val RMSE 0.002161995; lr 3.125e-05; 58s
network 6, training 8, epoch 330: train scaled MSE 0.000439791; val RMSE 0.00216076; lr 3.125e-05; 60s
network 6, training 8, epoch 340: train scaled MSE 0.000441145; val RMSE 0.002160266; lr 3.125e-05; 61s
network 6, training 8, epoch 350: train scaled MSE 0.000437073; val RMSE 0.002158265; lr 3.125e-05; 63s
network 6, training 8, epoch 360: train scaled MSE 0.000438718; val RMSE 0.002158995; lr 3.125e-05; 65s
network 6, training 8, epoch 370: train scaled MSE 0.000428454; val RMSE 0.002157004; lr 3.125e-05; 67s
network 6, training 8, epoch 380: train scaled MSE 0.000425399; val RMSE 0.002156485; lr 3.125e-05; 68s
network 6, training 8, epoch 390: train scaled MSE 0.00042211; val RMSE 0.002156289; lr 3.125e-05; 70s
network 6, training 8, epoch 400: train scaled MSE 0.000418001; val RMSE 0.002156145; lr 3.125e-05; 72s
network 6, training 8, epoch 410: train scaled MSE 0.000414359; val RMSE 0.002155691; lr 3.125e-05; 74s
network 6, training 8, epoch 420: train scaled MSE 0.0004063; val RMSE 0.002154462; lr 1.5625e-05; 76s
network 6, training 8, epoch 430: train scaled MSE 0.000409208; val RMSE 0.002154994; lr 1.5625e-05; 78s
network 6, training 8, epoch 440: train scaled MSE 0.000401849; val RMSE 0.002153957; lr 1e-05; 80s
network 6, training 8, epoch 450: train scaled MSE 0.000400516; val RMSE 0.002153562; lr 1e-05; 82s
network 6, training 8, epoch 460: train scaled MSE 0.000398892; val RMSE 0.00215334; lr 1e-05; 84s
network 6, training 8, epoch 470: train scaled MSE 0.000397531; val RMSE 0.002153586; lr 1e-05; 86s
network 6, training 8, epoch 480: train scaled MSE 0.000404588; val RMSE 0.002153433; lr 1e-05; 88s
network 6, training 8, epoch 490: train scaled MSE 0.000395347; val RMSE 0.002152684; lr 1e-05; 90s
network 6, training 8, epoch 500: train scaled MSE 0.000395107; val RMSE 0.002152294; lr 1e-05; 92s
network 6, training 8, epoch 510: train scaled MSE 0.00039506; val RMSE 0.002153444; lr 1e-05; 94s
network 6, training 8, epoch 520: train scaled MSE 0.000393987; val RMSE 0.002152801; lr 1e-05; 96s
network 6, training 8, epoch 530: train scaled MSE 0.000391587; val RMSE 0.002152454; lr 1e-05; 97s
network 6, training 8, epoch 540: train scaled MSE 0.000391308; val RMSE 0.002153099; lr 1e-05; 99s
network 6, training 8, epoch 550: train scaled MSE 0.00038937; val RMSE 0.002152067; lr 1e-05; 101s
network 6, training 8, epoch 560: train scaled MSE 0.000388976; val RMSE 0.002151992; lr 1e-05; 103s
network 6, training 8, epoch 570: train scaled MSE 0.000388155; val RMSE 0.00215256; lr 1e-05; 105s
network 6, training 8, epoch 580: train scaled MSE 0.000403327; val RMSE 0.002154149; lr 1e-05; 107s
network 6, training 8, epoch 590: train scaled MSE 0.000385366; val RMSE 0.002151879; lr 1e-05; 109s
network 6, training 8, epoch 600: train scaled MSE 0.000392928; val RMSE 0.002152593; lr 1e-05; 111s
network 6, training 8, epoch 610: train scaled MSE 0.000384458; val RMSE 0.002151541; lr 1e-05; 113s
network 6, training 8, epoch 620: train scaled MSE 0.000388285; val RMSE 0.002151756; lr 1e-05; 115s
network 6, training 8, epoch 630: train scaled MSE 0.000383036; val RMSE 0.002151198; lr 1e-05; 117s
network 6, training 8, epoch 640: train scaled MSE 0.00038194; val RMSE 0.002151372; lr 1e-05; 118s
network 6, training 8, epoch 650: train scaled MSE 0.000388368; val RMSE 0.002151745; lr 1e-05; 120s
network 6, training 8, epoch 660: train scaled MSE 0.00037958; val RMSE 0.002150454; lr 1e-05; 122s
network 6, training 8, epoch 670: train scaled MSE 0.000378763; val RMSE 0.002150623; lr 1e-05; 124s
network 6, training 8, epoch 680: train scaled MSE 0.000377838; val RMSE 0.002150833; lr 1e-05; 125s
network 6, training 8, epoch 690: train scaled MSE 0.000381395; val RMSE 0.0021506; lr 1e-05; 127s
network 6, training 8, epoch 700: train scaled MSE 0.000375923; val RMSE 0.002150306; lr 1e-05; 129s
network 6, training 8, epoch 710: train scaled MSE 0.000375249; val RMSE 0.002150191; lr 1e-05; 131s
network 6, training 8, epoch 720: train scaled MSE 0.000374209; val RMSE 0.002150293; lr 1e-05; 132s
network 6, training 8, epoch 730: train scaled MSE 0.000374159; val RMSE 0.002150297; lr 1e-05; 134s
network 6, training 8, epoch 740: train scaled MSE 0.000373646; val RMSE 0.002149481; lr 1e-05; 136s
network 6, training 8, epoch 750: train scaled MSE 0.000371724; val RMSE 0.002149413; lr 1e-05; 138s
network 6, training 8, epoch 760: train scaled MSE 0.000371212; val RMSE 0.002149886; lr 1e-05; 140s
network 6, training 8, epoch 770: train scaled MSE 0.000369977; val RMSE 0.002149456; lr 1e-05; 141s
network 6, training 8, epoch 780: train scaled MSE 0.00037735; val RMSE 0.002150116; lr 1e-05; 143s
network 6, training 8, epoch 790: train scaled MSE 0.000368321; val RMSE 0.002149099; lr 1e-05; 145s
network 6, training 8, epoch 800: train scaled MSE 0.000367334; val RMSE 0.002149169; lr 1e-05; 147s
network 6, training 8, epoch 810: train scaled MSE 0.000367285; val RMSE 0.0021492; lr 1e-05; 149s
network 6, training 8, epoch 820: train scaled MSE 0.00036538; val RMSE 0.002148649; lr 1e-05; 151s
network 6, training 8, epoch 830: train scaled MSE 0.000366122; val RMSE 0.002149476; lr 1e-05; 152s
network 6, training 8, epoch 840: train scaled MSE 0.000366152; val RMSE 0.002148308; lr 1e-05; 155s
network 6, training 8, epoch 850: train scaled MSE 0.000362914; val RMSE 0.00214829; lr 1e-05; 157s
network 6, training 8, epoch 860: train scaled MSE 0.000369693; val RMSE 0.002149988; lr 1e-05; 159s
network 6, training 8, epoch 870: train scaled MSE 0.000361099; val RMSE 0.002147938; lr 1e-05; 161s
network 6, training 8, epoch 880: train scaled MSE 0.000360219; val RMSE 0.002147972; lr 1e-05; 162s
network 6, training 8, epoch 890: train scaled MSE 0.00035944; val RMSE 0.002147959; lr 1e-05; 165s
network 6, training 8, epoch 900: train scaled MSE 0.000359244; val RMSE 0.002147316; lr 1e-05; 166s
network 6, training 8, epoch 910: train scaled MSE 0.000357457; val RMSE 0.002147663; lr 1e-05; 168s
network 6, training 8, epoch 920: train scaled MSE 0.000356633; val RMSE 0.002147524; lr 1e-05; 170s
network 6, training 8, epoch 930: train scaled MSE 0.000355478; val RMSE 0.00214777; lr 1e-05; 172s
network 6, training 8, epoch 940: train scaled MSE 0.00035511; val RMSE 0.002147335; lr 1e-05; 174s
network 6, training 8, epoch 950: train scaled MSE 0.000353695; val RMSE 0.002147347; lr 1e-05; 176s
network 6, training 8, epoch 960: train scaled MSE 0.000353446; val RMSE 0.002147645; lr 1e-05; 178s
network 6, training 8, epoch 970: train scaled MSE 0.000352043; val RMSE 0.002146941; lr 1e-05; 180s
network 6, training 8, epoch 980: train scaled MSE 0.00035425; val RMSE 0.00214728; lr 1e-05; 182s
network 6, training 8, epoch 990: train scaled MSE 0.000350549; val RMSE 0.002146874; lr 1e-05; 184s
Standard Linear Baseline Validation RMSE: 0.002402263

Network seed 6, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0029,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0029,1.3798,"[-0.79%, 2.91%]",0.1328,0.0,0.0351
MLP,0.0025,25.3072,"[11.79%, 36.00%]",0.5239,294.3921,0.1001

network 6, training 9, epoch 1: train scaled MSE 0.845352; val RMSE 0.0263282; lr 0.001; 0s
network 6, training 9, epoch 10: train scaled MSE 0.0217216; val RMSE 0.005393257; lr 0.001; 2s
network 6, training 9, epoch 20: train scaled MSE 0.0107696; val RMSE 0.003704316; lr 0.001; 4s
network 6, training 9, epoch 30: train scaled MSE 0.0093219; val RMSE 0.003322877; lr 0.001; 5s
network 6, training 9, epoch 40: train scaled MSE 0.00795756; val RMSE 0.003201556; lr 0.001; 7s
network 6, training 9, epoch 50: train scaled MSE 0.00593756; val RMSE 0.003142067; lr 0.001; 9s
network 6, training 9, epoch 60: train scaled MSE 0.00442602; val RMSE 0.00299537; lr 0.001; 11s
network 6, training 9, epoch 70: train scaled MSE 0.00402019; val RMSE 0.002960217; lr 0.001; 13s
network 6, training 9, epoch 80: train scaled MSE 0.00281141; val RMSE 0.002973154; lr 0.001; 15s
network 6, training 9, epoch 90: train scaled MSE 0.00221993; val RMSE 0.002855756; lr 0.0005; 17s
network 6, training 9, epoch 100: train scaled MSE 0.00164971; val RMSE 0.002821914; lr 0.0005; 19s
network 6, training 9, epoch 110: train scaled MSE 0.00149044; val RMSE 0.003095721; lr 0.0005; 21s
network 6, training 9, epoch 120: train scaled MSE 0.00132534; val RMSE 0.002791216; lr 0.0005; 23s
network 6, training 9, epoch 130: train scaled MSE 0.00134355; val RMSE 0.002778308; lr 0.0005; 25s
network 6, training 9, epoch 140: train scaled MSE 0.00102181; val RMSE 0.002753764; lr 0.00025; 27s
network 6, training 9, epoch 150: train scaled MSE 0.000956875; val RMSE 0.002748835; lr 0.00025; 29s
network 6, training 9, epoch 160: train scaled MSE 0.000912017; val RMSE 0.002736341; lr 0.00025; 31s
network 6, training 9, epoch 170: train scaled MSE 0.000856129; val RMSE 0.00273537; lr 0.00025; 33s
network 6, training 9, epoch 180: train scaled MSE 0.000908628; val RMSE 0.002734596; lr 0.00025; 35s
network 6, training 9, epoch 190: train scaled MSE 0.00142871; val RMSE 0.002744681; lr 0.00025; 37s
network 6, training 9, epoch 200: train scaled MSE 0.000741197; val RMSE 0.00273177; lr 0.00025; 39s
network 6, training 9, epoch 210: train scaled MSE 0.000695223; val RMSE 0.002716539; lr 0.00025; 41s
network 6, training 9, epoch 220: train scaled MSE 0.000679382; val RMSE 0.002713151; lr 0.00025; 43s
network 6, training 9, epoch 230: train scaled MSE 0.000637605; val RMSE 0.002711288; lr 0.00025; 45s
network 6, training 9, epoch 240: train scaled MSE 0.000727327; val RMSE 0.002709076; lr 0.00025; 47s
network 6, training 9, epoch 250: train scaled MSE 0.000580656; val RMSE 0.002711329; lr 0.00025; 49s
network 6, training 9, epoch 260: train scaled MSE 0.000541686; val RMSE 0.002718775; lr 0.00025; 51s
network 6, training 9, epoch 270: train scaled MSE 0.00064897; val RMSE 0.00270193; lr 0.000125; 53s
network 6, training 9, epoch 280: train scaled MSE 0.000485809; val RMSE 0.002696015; lr 0.000125; 55s
network 6, training 9, epoch 290: train scaled MSE 0.000475046; val RMSE 0.002688942; lr 0.000125; 58s
network 6, training 9, epoch 300: train scaled MSE 0.000570967; val RMSE 0.002719073; lr 0.000125; 60s
network 6, training 9, epoch 310: train scaled MSE 0.000459979; val RMSE 0.002715228; lr 0.000125; 62s
network 6, training 9, epoch 320: train scaled MSE 0.000443825; val RMSE 0.002684068; lr 0.000125; 64s
network 6, training 9, epoch 330: train scaled MSE 0.000430518; val RMSE 0.002711114; lr 0.000125; 66s
network 6, training 9, epoch 340: train scaled MSE 0.000420969; val RMSE 0.002682437; lr 0.000125; 68s
network 6, training 9, epoch 350: train scaled MSE 0.000414779; val RMSE 0.002680094; lr 0.000125; 70s
network 6, training 9, epoch 360: train scaled MSE 0.000426744; val RMSE 0.002681626; lr 0.000125; 72s
network 6, training 9, epoch 370: train scaled MSE 0.00038095; val RMSE 0.002676528; lr 6.25e-05; 74s
network 6, training 9, epoch 380: train scaled MSE 0.000376806; val RMSE 0.002676286; lr 6.25e-05; 76s
network 6, training 9, epoch 390: train scaled MSE 0.000369543; val RMSE 0.0026729; lr 6.25e-05; 78s
network 6, training 9, epoch 400: train scaled MSE 0.000363334; val RMSE 0.002675502; lr 6.25e-05; 80s
network 6, training 9, epoch 410: train scaled MSE 0.000351678; val RMSE 0.002671951; lr 3.125e-05; 82s
network 6, training 9, epoch 420: train scaled MSE 0.00034961; val RMSE 0.002672333; lr 3.125e-05; 84s
network 6, training 9, epoch 430: train scaled MSE 0.000347401; val RMSE 0.002670437; lr 3.125e-05; 86s
network 6, training 9, epoch 440: train scaled MSE 0.000342545; val RMSE 0.002669834; lr 1.5625e-05; 88s
network 6, training 9, epoch 450: train scaled MSE 0.000340693; val RMSE 0.002668387; lr 1.5625e-05; 90s
network 6, training 9, epoch 460: train scaled MSE 0.000344815; val RMSE 0.002669212; lr 1.5625e-05; 92s
network 6, training 9, epoch 470: train scaled MSE 0.0003409; val RMSE 0.002668853; lr 1e-05; 94s
network 6, training 9, epoch 480: train scaled MSE 0.000337906; val RMSE 0.002668229; lr 1e-05; 96s
network 6, training 9, epoch 490: train scaled MSE 0.00033505; val RMSE 0.002667596; lr 1e-05; 98s
network 6, training 9, epoch 500: train scaled MSE 0.000335241; val RMSE 0.002667977; lr 1e-05; 100s
network 6, training 9, epoch 510: train scaled MSE 0.000335458; val RMSE 0.002667902; lr 1e-05; 102s
network 6, training 9, epoch 520: train scaled MSE 0.000333437; val RMSE 0.002667098; lr 1e-05; 104s
network 6, training 9, epoch 530: train scaled MSE 0.000332512; val RMSE 0.002667278; lr 1e-05; 106s
network 6, training 9, epoch 540: train scaled MSE 0.000334844; val RMSE 0.002667001; lr 1e-05; 107s
network 6, training 9, epoch 550: train scaled MSE 0.000331076; val RMSE 0.002666524; lr 1e-05; 109s
network 6, training 9, epoch 560: train scaled MSE 0.000330518; val RMSE 0.00266622; lr 1e-05; 111s
network 6, training 9, epoch 570: train scaled MSE 0.00032987; val RMSE 0.002666428; lr 1e-05; 113s
network 6, training 9, epoch 580: train scaled MSE 0.000329225; val RMSE 0.002665619; lr 1e-05; 115s
network 6, training 9, epoch 590: train scaled MSE 0.000328044; val RMSE 0.002665992; lr 1e-05; 116s
network 6, training 9, epoch 600: train scaled MSE 0.000327354; val RMSE 0.002665609; lr 1e-05; 118s
network 6, training 9, epoch 610: train scaled MSE 0.000327048; val RMSE 0.002665818; lr 1e-05; 120s
network 6, training 9, epoch 620: train scaled MSE 0.000325989; val RMSE 0.002665016; lr 1e-05; 122s
network 6, training 9, epoch 630: train scaled MSE 0.000324496; val RMSE 0.002664723; lr 1e-05; 124s
network 6, training 9, epoch 640: train scaled MSE 0.000324518; val RMSE 0.002665107; lr 1e-05; 126s
network 6, training 9, epoch 650: train scaled MSE 0.000323766; val RMSE 0.00266426; lr 1e-05; 128s
network 6, training 9, epoch 660: train scaled MSE 0.000322296; val RMSE 0.002663987; lr 1e-05; 130s
network 6, training 9, epoch 670: train scaled MSE 0.000324794; val RMSE 0.002663493; lr 1e-05; 132s
network 6, training 9, epoch 680: train scaled MSE 0.000322068; val RMSE 0.002663393; lr 1e-05; 133s
network 6, training 9, epoch 690: train scaled MSE 0.0003232; val RMSE 0.002663877; lr 1e-05; 135s
network 6, training 9, epoch 700: train scaled MSE 0.000321333; val RMSE 0.002663724; lr 1e-05; 137s
network 6, training 9, epoch 710: train scaled MSE 0.00031957; val RMSE 0.002663093; lr 1e-05; 139s
Standard Linear Baseline Validation RMSE: 0.003082824

Network seed 6, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0028,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0028,1.6437,"[0.16%, 2.71%]",0.1319,0.0,0.0518
MLP,0.0026,16.7945,"[2.08%, 29.13%]",0.4601,248.7799,0.1191

Network 7: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   22.1s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   22.1s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   22.2s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   22.4s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   22.5s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   22.6s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   22.8s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   22.9s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   23.1s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   23.2s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   23.5s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   23.7s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   23.9s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   24.1s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   24.3s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   24.4s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   24.6s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   24.9s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   25.1s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   25.3s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   25.6s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   25.8s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   26.0s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   26.3s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   26.5s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   26.8s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   27.1s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   27.4s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   27.7s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   28.3s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   28.6s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   28.9s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   29.3s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   29.6s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   29.9s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   30.2s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   31.0s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   31.3s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   31.7s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   32.0s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   32.5s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   32.8s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   33.2s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   33.6s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   34.0s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   34.4s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   34.9s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   35.3s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   35.7s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   36.2s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   36.6s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   37.1s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   37.6s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   38.1s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   38.6s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   39.1s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   39.5s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   40.0s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   40.5s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   41.1s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   41.6s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   42.1s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   42.6s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   43.2s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   43.8s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   44.3s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   44.9s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   45.4s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   46.0s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   46.6s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   47.2s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   47.8s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   48.3s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   48.9s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   49.5s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   50.2s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   50.9s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   51.4s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   52.1s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   52.8s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   53.4s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   54.1s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:   54.8s
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:   55.5s
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:   56.2s
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:   56.8s
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:   57.6s
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:   58.3s
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:   59.0s
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:   59.8s
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.3min finished

network 7, training 0, epoch 1: train scaled MSE 0.806081; val RMSE 0.01817027; lr 0.001; 0s
network 7, training 0, epoch 10: train scaled MSE 0.0229425; val RMSE 0.00370597; lr 0.001; 2s
network 7, training 0, epoch 20: train scaled MSE 0.00822206; val RMSE 0.002135137; lr 0.001; 4s
network 7, training 0, epoch 30: train scaled MSE 0.00855818; val RMSE 0.001841745; lr 0.001; 6s
network 7, training 0, epoch 40: train scaled MSE 0.00508868; val RMSE 0.00173501; lr 0.001; 8s
network 7, training 0, epoch 50: train scaled MSE 0.0055344; val RMSE 0.001808189; lr 0.001; 10s
network 7, training 0, epoch 60: train scaled MSE 0.00311641; val RMSE 0.001656924; lr 0.001; 12s
network 7, training 0, epoch 70: train scaled MSE 0.0025251; val RMSE 0.001656151; lr 0.001; 14s
network 7, training 0, epoch 80: train scaled MSE 0.00229704; val RMSE 0.001604096; lr 0.001; 16s
network 7, training 0, epoch 90: train scaled MSE 0.00169553; val RMSE 0.001606952; lr 0.001; 18s
network 7, training 0, epoch 100: train scaled MSE 0.00167778; val RMSE 0.001539611; lr 0.001; 20s
network 7, training 0, epoch 110: train scaled MSE 0.00172579; val RMSE 0.001543759; lr 0.001; 22s
network 7, training 0, epoch 120: train scaled MSE 0.00110536; val RMSE 0.001557786; lr 0.001; 24s
network 7, training 0, epoch 130: train scaled MSE 0.00198788; val RMSE 0.001540722; lr 0.0005; 26s
network 7, training 0, epoch 140: train scaled MSE 0.0006246; val RMSE 0.001436728; lr 0.0005; 28s
network 7, training 0, epoch 150: train scaled MSE 0.000709022; val RMSE 0.001522326; lr 0.0005; 30s
network 7, training 0, epoch 160: train scaled MSE 0.00204539; val RMSE 0.001449875; lr 0.0005; 32s
network 7, training 0, epoch 170: train scaled MSE 0.000506676; val RMSE 0.001402392; lr 0.00025; 35s
network 7, training 0, epoch 180: train scaled MSE 0.000446341; val RMSE 0.001389123; lr 0.00025; 37s
network 7, training 0, epoch 190: train scaled MSE 0.00040902; val RMSE 0.001381227; lr 0.00025; 39s
network 7, training 0, epoch 200: train scaled MSE 0.000392146; val RMSE 0.00138795; lr 0.00025; 41s
network 7, training 0, epoch 210: train scaled MSE 0.000372124; val RMSE 0.001374084; lr 0.00025; 43s
network 7, training 0, epoch 220: train scaled MSE 0.000446139; val RMSE 0.001395611; lr 0.00025; 45s
network 7, training 0, epoch 230: train scaled MSE 0.000660761; val RMSE 0.001374276; lr 0.00025; 47s
network 7, training 0, epoch 240: train scaled MSE 0.000329154; val RMSE 0.001351318; lr 0.00025; 50s
network 7, training 0, epoch 250: train scaled MSE 0.000525119; val RMSE 0.001355913; lr 0.00025; 52s
network 7, training 0, epoch 260: train scaled MSE 0.000313572; val RMSE 0.001351189; lr 0.00025; 54s
network 7, training 0, epoch 270: train scaled MSE 0.000284828; val RMSE 0.001337806; lr 0.00025; 56s
network 7, training 0, epoch 280: train scaled MSE 0.000240477; val RMSE 0.001325599; lr 0.000125; 58s
network 7, training 0, epoch 290: train scaled MSE 0.000228711; val RMSE 0.001354699; lr 0.000125; 60s
network 7, training 0, epoch 300: train scaled MSE 0.000226728; val RMSE 0.001319345; lr 0.000125; 62s
network 7, training 0, epoch 310: train scaled MSE 0.000238075; val RMSE 0.001317207; lr 0.000125; 65s
network 7, training 0, epoch 320: train scaled MSE 0.000330829; val RMSE 0.001320227; lr 0.000125; 67s
network 7, training 0, epoch 330: train scaled MSE 0.000207266; val RMSE 0.001310364; lr 0.000125; 69s
network 7, training 0, epoch 340: train scaled MSE 0.000208429; val RMSE 0.00130957; lr 0.000125; 71s
network 7, training 0, epoch 350: train scaled MSE 0.000267995; val RMSE 0.001322479; lr 0.000125; 73s
network 7, training 0, epoch 360: train scaled MSE 0.000208738; val RMSE 0.00130913; lr 6.25e-05; 75s
network 7, training 0, epoch 370: train scaled MSE 0.000181064; val RMSE 0.001305235; lr 6.25e-05; 78s
network 7, training 0, epoch 380: train scaled MSE 0.000176148; val RMSE 0.001302554; lr 6.25e-05; 80s
network 7, training 0, epoch 390: train scaled MSE 0.000214937; val RMSE 0.001303347; lr 6.25e-05; 82s
network 7, training 0, epoch 400: train scaled MSE 0.000173995; val RMSE 0.001301057; lr 6.25e-05; 84s
network 7, training 0, epoch 410: train scaled MSE 0.000172314; val RMSE 0.001306554; lr 6.25e-05; 86s
network 7, training 0, epoch 420: train scaled MSE 0.000169616; val RMSE 0.00130159; lr 6.25e-05; 89s
network 7, training 0, epoch 430: train scaled MSE 0.000167151; val RMSE 0.0012976; lr 6.25e-05; 91s
network 7, training 0, epoch 440: train scaled MSE 0.000164841; val RMSE 0.001297149; lr 6.25e-05; 93s
network 7, training 0, epoch 450: train scaled MSE 0.000221722; val RMSE 0.001300156; lr 6.25e-05; 95s
network 7, training 0, epoch 460: train scaled MSE 0.000159845; val RMSE 0.00129339; lr 6.25e-05; 98s
network 7, training 0, epoch 470: train scaled MSE 0.000174276; val RMSE 0.001294334; lr 6.25e-05; 100s
network 7, training 0, epoch 480: train scaled MSE 0.000155786; val RMSE 0.001292481; lr 6.25e-05; 102s
network 7, training 0, epoch 490: train scaled MSE 0.000155395; val RMSE 0.00129137; lr 6.25e-05; 104s
network 7, training 0, epoch 500: train scaled MSE 0.000192598; val RMSE 0.001294343; lr 6.25e-05; 106s
network 7, training 0, epoch 510: train scaled MSE 0.000149758; val RMSE 0.001288757; lr 6.25e-05; 108s
network 7, training 0, epoch 520: train scaled MSE 0.000148987; val RMSE 0.001288212; lr 6.25e-05; 110s
network 7, training 0, epoch 530: train scaled MSE 0.000181654; val RMSE 0.001289353; lr 6.25e-05; 113s
network 7, training 0, epoch 540: train scaled MSE 0.00015314; val RMSE 0.001287122; lr 6.25e-05; 115s
network 7, training 0, epoch 550: train scaled MSE 0.000157595; val RMSE 0.001285708; lr 3.125e-05; 117s
network 7, training 0, epoch 560: train scaled MSE 0.000137418; val RMSE 0.001283833; lr 3.125e-05; 119s
network 7, training 0, epoch 570: train scaled MSE 0.000136788; val RMSE 0.001283932; lr 3.125e-05; 121s
network 7, training 0, epoch 580: train scaled MSE 0.000152169; val RMSE 0.001284692; lr 3.125e-05; 122s
network 7, training 0, epoch 590: train scaled MSE 0.000137561; val RMSE 0.001284229; lr 3.125e-05; 124s
network 7, training 0, epoch 600: train scaled MSE 0.000131151; val RMSE 0.001282616; lr 1.5625e-05; 126s
network 7, training 0, epoch 610: train scaled MSE 0.000139715; val RMSE 0.00128303; lr 1.5625e-05; 128s
network 7, training 0, epoch 620: train scaled MSE 0.000129989; val RMSE 0.001281366; lr 1.5625e-05; 130s
network 7, training 0, epoch 630: train scaled MSE 0.00013009; val RMSE 0.001281476; lr 1.5625e-05; 132s
network 7, training 0, epoch 640: train scaled MSE 0.000139246; val RMSE 0.001281707; lr 1.5625e-05; 134s
network 7, training 0, epoch 650: train scaled MSE 0.000129353; val RMSE 0.001280878; lr 1e-05; 136s
network 7, training 0, epoch 660: train scaled MSE 0.000127533; val RMSE 0.001279969; lr 1e-05; 138s
network 7, training 0, epoch 670: train scaled MSE 0.000127361; val RMSE 0.001279878; lr 1e-05; 140s
network 7, training 0, epoch 680: train scaled MSE 0.000126877; val RMSE 0.001279466; lr 1e-05; 142s
network 7, training 0, epoch 690: train scaled MSE 0.00012793; val RMSE 0.001279373; lr 1e-05; 144s
network 7, training 0, epoch 700: train scaled MSE 0.000126493; val RMSE 0.001279209; lr 1e-05; 146s
network 7, training 0, epoch 710: train scaled MSE 0.000126262; val RMSE 0.001279034; lr 1e-05; 148s
network 7, training 0, epoch 720: train scaled MSE 0.000127754; val RMSE 0.001279229; lr 1e-05; 150s
network 7, training 0, epoch 730: train scaled MSE 0.000125279; val RMSE 0.00127847; lr 1e-05; 152s
network 7, training 0, epoch 740: train scaled MSE 0.000124991; val RMSE 0.001278498; lr 1e-05; 154s
network 7, training 0, epoch 750: train scaled MSE 0.000125309; val RMSE 0.001278696; lr 1e-05; 156s
network 7, training 0, epoch 760: train scaled MSE 0.000125242; val RMSE 0.001278275; lr 1e-05; 158s
network 7, training 0, epoch 770: train scaled MSE 0.000124045; val RMSE 0.001277977; lr 1e-05; 160s
network 7, training 0, epoch 780: train scaled MSE 0.000125311; val RMSE 0.001279; lr 1e-05; 162s
network 7, training 0, epoch 790: train scaled MSE 0.000123536; val RMSE 0.001277898; lr 1e-05; 164s
network 7, training 0, epoch 800: train scaled MSE 0.000123195; val RMSE 0.001277624; lr 1e-05; 166s
network 7, training 0, epoch 810: train scaled MSE 0.000122929; val RMSE 0.00127727; lr 1e-05; 168s
network 7, training 0, epoch 820: train scaled MSE 0.000122759; val RMSE 0.001278053; lr 1e-05; 170s
network 7, training 0, epoch 830: train scaled MSE 0.00012235; val RMSE 0.001276903; lr 1e-05; 172s
network 7, training 0, epoch 840: train scaled MSE 0.000122626; val RMSE 0.001276779; lr 1e-05; 174s
network 7, training 0, epoch 850: train scaled MSE 0.000121823; val RMSE 0.001276282; lr 1e-05; 176s
network 7, training 0, epoch 860: train scaled MSE 0.000121356; val RMSE 0.00127612; lr 1e-05; 178s
network 7, training 0, epoch 870: train scaled MSE 0.000121473; val RMSE 0.001275825; lr 1e-05; 180s
network 7, training 0, epoch 880: train scaled MSE 0.000120724; val RMSE 0.001275413; lr 1e-05; 182s
network 7, training 0, epoch 890: train scaled MSE 0.000121177; val RMSE 0.001275385; lr 1e-05; 184s
network 7, training 0, epoch 900: train scaled MSE 0.000120247; val RMSE 0.001275579; lr 1e-05; 186s
network 7, training 0, epoch 910: train scaled MSE 0.000139227; val RMSE 0.001276761; lr 1e-05; 188s
network 7, training 0, epoch 920: train scaled MSE 0.000121457; val RMSE 0.001274921; lr 1e-05; 190s
network 7, training 0, epoch 930: train scaled MSE 0.000119196; val RMSE 0.001274885; lr 1e-05; 192s
network 7, training 0, epoch 940: train scaled MSE 0.000119089; val RMSE 0.001274216; lr 1e-05; 194s
network 7, training 0, epoch 950: train scaled MSE 0.000119093; val RMSE 0.001274527; lr 1e-05; 196s
network 7, training 0, epoch 960: train scaled MSE 0.000119297; val RMSE 0.001274572; lr 1e-05; 198s
network 7, training 0, epoch 970: train scaled MSE 0.000118103; val RMSE 0.001274009; lr 1e-05; 200s
network 7, training 0, epoch 980: train scaled MSE 0.000120935; val RMSE 0.001273958; lr 1e-05; 202s
network 7, training 0, epoch 990: train scaled MSE 0.000117799; val RMSE 0.001273844; lr 1e-05; 204s
network 7, training 0, epoch 1000: train scaled MSE 0.000117208; val RMSE 0.00127354; lr 1e-05; 206s
network 7, training 0, epoch 1010: train scaled MSE 0.000116969; val RMSE 0.00127323; lr 1e-05; 208s
network 7, training 0, epoch 1020: train scaled MSE 0.000117161; val RMSE 0.001273056; lr 1e-05; 210s
network 7, training 0, epoch 1030: train scaled MSE 0.000122789; val RMSE 0.001273368; lr 1e-05; 212s
network 7, training 0, epoch 1040: train scaled MSE 0.000116136; val RMSE 0.001272726; lr 1e-05; 214s
network 7, training 0, epoch 1050: train scaled MSE 0.000116022; val RMSE 0.001272789; lr 1e-05; 216s
network 7, training 0, epoch 1060: train scaled MSE 0.000115327; val RMSE 0.001272349; lr 1e-05; 218s
network 7, training 0, epoch 1070: train scaled MSE 0.000115135; val RMSE 0.001272932; lr 1e-05; 220s
network 7, training 0, epoch 1080: train scaled MSE 0.000114758; val RMSE 0.001272273; lr 1e-05; 222s
network 7, training 0, epoch 1090: train scaled MSE 0.000114887; val RMSE 0.00127207; lr 1e-05; 224s
network 7, training 0, epoch 1100: train scaled MSE 0.0001141; val RMSE 0.001272251; lr 1e-05; 226s
network 7, training 0, epoch 1110: train scaled MSE 0.000118377; val RMSE 0.001272692; lr 1e-05; 228s
network 7, training 0, epoch 1120: train scaled MSE 0.000114028; val RMSE 0.001272053; lr 1e-05; 230s
network 7, training 0, epoch 1130: train scaled MSE 0.00011343; val RMSE 0.001271573; lr 1e-05; 232s
network 7, training 0, epoch 1140: train scaled MSE 0.000113064; val RMSE 0.001271528; lr 1e-05; 234s
network 7, training 0, epoch 1150: train scaled MSE 0.000112967; val RMSE 0.001271012; lr 1e-05; 236s
network 7, training 0, epoch 1160: train scaled MSE 0.000113517; val RMSE 0.001270981; lr 1e-05; 238s
network 7, training 0, epoch 1170: train scaled MSE 0.000112201; val RMSE 0.001270863; lr 1e-05; 240s
network 7, training 0, epoch 1180: train scaled MSE 0.000111979; val RMSE 0.001271739; lr 1e-05; 242s
network 7, training 0, epoch 1190: train scaled MSE 0.000111935; val RMSE 0.001270708; lr 1e-05; 245s
network 7, training 0, epoch 1200: train scaled MSE 0.000111743; val RMSE 0.001270603; lr 1e-05; 247s
network 7, training 0, epoch 1210: train scaled MSE 0.000118642; val RMSE 0.001270758; lr 1e-05; 249s
network 7, training 0, epoch 1220: train scaled MSE 0.000110989; val RMSE 0.001269877; lr 1e-05; 251s
network 7, training 0, epoch 1230: train scaled MSE 0.000110706; val RMSE 0.001269949; lr 1e-05; 253s
network 7, training 0, epoch 1240: train scaled MSE 0.000111118; val RMSE 0.001269953; lr 1e-05; 255s
network 7, training 0, epoch 1250: train scaled MSE 0.000111155; val RMSE 0.001269884; lr 1e-05; 257s
network 7, training 0, epoch 1260: train scaled MSE 0.000111047; val RMSE 0.001269819; lr 1e-05; 259s
network 7, training 0, epoch 1270: train scaled MSE 0.000109779; val RMSE 0.001269678; lr 1e-05; 261s
network 7, training 0, epoch 1280: train scaled MSE 0.000110452; val RMSE 0.001269418; lr 1e-05; 263s
network 7, training 0, epoch 1290: train scaled MSE 0.000109389; val RMSE 0.001269135; lr 1e-05; 265s
network 7, training 0, epoch 1300: train scaled MSE 0.000115767; val RMSE 0.001269303; lr 1e-05; 267s
network 7, training 0, epoch 1310: train scaled MSE 0.000109293; val RMSE 0.001269221; lr 1e-05; 269s
network 7, training 0, epoch 1320: train scaled MSE 0.00011081; val RMSE 0.001269143; lr 1e-05; 271s
network 7, training 0, epoch 1330: train scaled MSE 0.000108623; val RMSE 0.001269021; lr 1e-05; 273s
network 7, training 0, epoch 1340: train scaled MSE 0.0001085; val RMSE 0.001268488; lr 1e-05; 275s
network 7, training 0, epoch 1350: train scaled MSE 0.000108386; val RMSE 0.001269174; lr 1e-05; 277s
network 7, training 0, epoch 1360: train scaled MSE 0.00010792; val RMSE 0.00126911; lr 1e-05; 279s
network 7, training 0, epoch 1370: train scaled MSE 0.000107678; val RMSE 0.001268519; lr 1e-05; 281s
network 7, training 0, epoch 1380: train scaled MSE 0.000114307; val RMSE 0.001269274; lr 1e-05; 283s
network 7, training 0, epoch 1390: train scaled MSE 0.000107569; val RMSE 0.001268756; lr 1e-05; 285s
network 7, training 0, epoch 1400: train scaled MSE 0.000107298; val RMSE 0.001268266; lr 1e-05; 287s
network 7, training 0, epoch 1410: train scaled MSE 0.000106877; val RMSE 0.001267984; lr 1e-05; 289s
network 7, training 0, epoch 1420: train scaled MSE 0.000107522; val RMSE 0.001268355; lr 1e-05; 291s
network 7, training 0, epoch 1430: train scaled MSE 0.000106948; val RMSE 0.001268225; lr 1e-05; 293s
network 7, training 0, epoch 1440: train scaled MSE 0.000108461; val RMSE 0.001267862; lr 1e-05; 295s
network 7, training 0, epoch 1450: train scaled MSE 0.000106351; val RMSE 0.001267648; lr 1e-05; 297s
network 7, training 0, epoch 1460: train scaled MSE 0.000105632; val RMSE 0.001267039; lr 1e-05; 299s
network 7, training 0, epoch 1470: train scaled MSE 0.000105573; val RMSE 0.001267233; lr 1e-05; 301s
network 7, training 0, epoch 1480: train scaled MSE 0.000105198; val RMSE 0.001267197; lr 1e-05; 303s
network 7, training 0, epoch 1490: train scaled MSE 0.000107294; val RMSE 0.001267291; lr 1e-05; 306s
network 7, training 0, epoch 1500: train scaled MSE 0.000104993; val RMSE 0.001268316; lr 1e-05; 308s
network 7, training 0, epoch 1510: train scaled MSE 0.000104767; val RMSE 0.001266984; lr 1e-05; 310s
network 7, training 0, epoch 1520: train scaled MSE 0.000104337; val RMSE 0.001266799; lr 1e-05; 312s
network 7, training 0, epoch 1530: train scaled MSE 0.00010444; val RMSE 0.001267007; lr 1e-05; 315s
network 7, training 0, epoch 1540: train scaled MSE 0.000103934; val RMSE 0.001266532; lr 1e-05; 317s
network 7, training 0, epoch 1550: train scaled MSE 0.000103808; val RMSE 0.001266541; lr 1e-05; 319s
network 7, training 0, epoch 1560: train scaled MSE 0.00010349; val RMSE 0.001266227; lr 1e-05; 321s
network 7, training 0, epoch 1570: train scaled MSE 0.000105326; val RMSE 0.001266601; lr 1e-05; 323s
network 7, training 0, epoch 1580: train scaled MSE 0.000102789; val RMSE 0.001266191; lr 1e-05; 325s
network 7, training 0, epoch 1590: train scaled MSE 0.000107197; val RMSE 0.001266011; lr 1e-05; 327s
network 7, training 0, epoch 1600: train scaled MSE 0.000102377; val RMSE 0.001265512; lr 1e-05; 329s
network 7, training 0, epoch 1610: train scaled MSE 0.000104604; val RMSE 0.001266001; lr 1e-05; 331s
network 7, training 0, epoch 1620: train scaled MSE 0.00010254; val RMSE 0.00126564; lr 1e-05; 333s
network 7, training 0, epoch 1630: train scaled MSE 0.000101858; val RMSE 0.001265065; lr 1e-05; 335s
network 7, training 0, epoch 1640: train scaled MSE 0.000102514; val RMSE 0.001265247; lr 1e-05; 337s
network 7, training 0, epoch 1650: train scaled MSE 0.000101844; val RMSE 0.001265185; lr 1e-05; 339s
network 7, training 0, epoch 1660: train scaled MSE 0.000103291; val RMSE 0.00126517; lr 1e-05; 341s
network 7, training 0, epoch 1670: train scaled MSE 0.000101227; val RMSE 0.001265397; lr 1e-05; 343s
network 7, training 0, epoch 1680: train scaled MSE 0.000100819; val RMSE 0.001264847; lr 1e-05; 345s
network 7, training 0, epoch 1690: train scaled MSE 0.000100793; val RMSE 0.001264739; lr 1e-05; 347s
network 7, training 0, epoch 1700: train scaled MSE 0.000100785; val RMSE 0.00126453; lr 1e-05; 349s
network 7, training 0, epoch 1710: train scaled MSE 0.000100611; val RMSE 0.001264435; lr 1e-05; 351s
network 7, training 0, epoch 1720: train scaled MSE 0.000100085; val RMSE 0.001264229; lr 1e-05; 353s
network 7, training 0, epoch 1730: train scaled MSE 0.000100171; val RMSE 0.001264217; lr 1e-05; 355s
network 7, training 0, epoch 1740: train scaled MSE 9.97183e-05; val RMSE 0.001264048; lr 1e-05; 357s
network 7, training 0, epoch 1750: train scaled MSE 9.97184e-05; val RMSE 0.001265304; lr 1e-05; 359s
network 7, training 0, epoch 1760: train scaled MSE 9.93961e-05; val RMSE 0.001263963; lr 1e-05; 361s
network 7, training 0, epoch 1770: train scaled MSE 9.90629e-05; val RMSE 0.001263433; lr 1e-05; 363s
network 7, training 0, epoch 1780: train scaled MSE 9.89083e-05; val RMSE 0.001263748; lr 1e-05; 365s
network 7, training 0, epoch 1790: train scaled MSE 9.95232e-05; val RMSE 0.001263755; lr 1e-05; 367s
network 7, training 0, epoch 1800: train scaled MSE 9.86091e-05; val RMSE 0.001263781; lr 1e-05; 370s
network 7, training 0, epoch 1810: train scaled MSE 0.000118749; val RMSE 0.001266151; lr 1e-05; 372s
network 7, training 0, epoch 1820: train scaled MSE 9.82666e-05; val RMSE 0.001262902; lr 1e-05; 374s
network 7, training 0, epoch 1830: train scaled MSE 9.77372e-05; val RMSE 0.00126285; lr 1e-05; 376s
network 7, training 0, epoch 1840: train scaled MSE 9.80697e-05; val RMSE 0.001262771; lr 1e-05; 378s
network 7, training 0, epoch 1850: train scaled MSE 0.00010402; val RMSE 0.001263955; lr 1e-05; 381s
network 7, training 0, epoch 1860: train scaled MSE 9.72028e-05; val RMSE 0.001262799; lr 1e-05; 383s
network 7, training 0, epoch 1870: train scaled MSE 9.70115e-05; val RMSE 0.001262491; lr 1e-05; 385s
network 7, training 0, epoch 1880: train scaled MSE 9.7635e-05; val RMSE 0.001262689; lr 1e-05; 387s
network 7, training 0, epoch 1890: train scaled MSE 9.65885e-05; val RMSE 0.00126261; lr 1e-05; 389s
network 7, training 0, epoch 1900: train scaled MSE 9.64255e-05; val RMSE 0.001262232; lr 1e-05; 391s
network 7, training 0, epoch 1910: train scaled MSE 9.64188e-05; val RMSE 0.001262149; lr 1e-05; 393s
network 7, training 0, epoch 1920: train scaled MSE 9.61324e-05; val RMSE 0.001262019; lr 1e-05; 396s
network 7, training 0, epoch 1930: train scaled MSE 0.000109418; val RMSE 0.001263527; lr 1e-05; 398s
network 7, training 0, epoch 1940: train scaled MSE 9.58842e-05; val RMSE 0.001261876; lr 1e-05; 400s
network 7, training 0, epoch 1950: train scaled MSE 9.55536e-05; val RMSE 0.001261674; lr 1e-05; 402s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0018,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0018,-3.4557,"[-5.93%, -1.38%]",0.0391,0.0,0.0877
MLP,0.0017,9.6053,"[-4.86%, 23.09%]",0.4346,1011.807,0.3393

network 7, training 1, epoch 1: train scaled MSE 0.815983; val RMSE 0.01951594; lr 0.001; 0s
network 7, training 1, epoch 10: train scaled MSE 0.0184503; val RMSE 0.003975896; lr 0.001; 2s
network 7, training 1, epoch 20: train scaled MSE 0.00762729; val RMSE 0.003144378; lr 0.001; 4s
network 7, training 1, epoch 30: train scaled MSE 0.00580351; val RMSE 0.002572756; lr 0.001; 6s
network 7, training 1, epoch 40: train scaled MSE 0.00471368; val RMSE 0.002397146; lr 0.001; 8s
network 7, training 1, epoch 50: train scaled MSE 0.0219857; val RMSE 0.002549255; lr 0.001; 10s
network 7, training 1, epoch 60: train scaled MSE 0.00303792; val RMSE 0.002260401; lr 0.0005; 12s
network 7, training 1, epoch 70: train scaled MSE 0.00266017; val RMSE 0.002185695; lr 0.0005; 14s
network 7, training 1, epoch 80: train scaled MSE 0.00230935; val RMSE 0.002163979; lr 0.0005; 16s
network 7, training 1, epoch 90: train scaled MSE 0.00200428; val RMSE 0.002233478; lr 0.0005; 18s
network 7, training 1, epoch 100: train scaled MSE 0.00178057; val RMSE 0.002087804; lr 0.0005; 20s
network 7, training 1, epoch 110: train scaled MSE 0.00156717; val RMSE 0.002068671; lr 0.0005; 22s
network 7, training 1, epoch 120: train scaled MSE 0.00133854; val RMSE 0.002502064; lr 0.0005; 23s
network 7, training 1, epoch 130: train scaled MSE 0.00117202; val RMSE 0.002039868; lr 0.0005; 25s
network 7, training 1, epoch 140: train scaled MSE 0.00104851; val RMSE 0.002108401; lr 0.0005; 27s
network 7, training 1, epoch 150: train scaled MSE 0.00115797; val RMSE 0.002016726; lr 0.0005; 29s
network 7, training 1, epoch 160: train scaled MSE 0.000860199; val RMSE 0.002035252; lr 0.0005; 31s
network 7, training 1, epoch 170: train scaled MSE 0.000758896; val RMSE 0.002004588; lr 0.0005; 33s
network 7, training 1, epoch 180: train scaled MSE 0.000684432; val RMSE 0.001969377; lr 0.0005; 35s
network 7, training 1, epoch 190: train scaled MSE 0.000629678; val RMSE 0.002014292; lr 0.0005; 37s
network 7, training 1, epoch 200: train scaled MSE 0.000587454; val RMSE 0.00196586; lr 0.0005; 39s
network 7, training 1, epoch 210: train scaled MSE 0.000783906; val RMSE 0.001980223; lr 0.0005; 41s
network 7, training 1, epoch 220: train scaled MSE 0.000462416; val RMSE 0.001941871; lr 0.0005; 43s
network 7, training 1, epoch 230: train scaled MSE 0.000478826; val RMSE 0.001941645; lr 0.0005; 44s
network 7, training 1, epoch 240: train scaled MSE 0.000344992; val RMSE 0.001924581; lr 0.00025; 46s
network 7, training 1, epoch 250: train scaled MSE 0.000342613; val RMSE 0.001913851; lr 0.00025; 48s
network 7, training 1, epoch 260: train scaled MSE 0.000336069; val RMSE 0.001912047; lr 0.00025; 50s
network 7, training 1, epoch 270: train scaled MSE 0.000305653; val RMSE 0.001904904; lr 0.00025; 52s
network 7, training 1, epoch 280: train scaled MSE 0.000304022; val RMSE 0.001901878; lr 0.00025; 54s
network 7, training 1, epoch 290: train scaled MSE 0.000283556; val RMSE 0.001927383; lr 0.00025; 56s
network 7, training 1, epoch 300: train scaled MSE 0.000373082; val RMSE 0.001912231; lr 0.00025; 58s
network 7, training 1, epoch 310: train scaled MSE 0.000238465; val RMSE 0.001893876; lr 0.000125; 60s
network 7, training 1, epoch 320: train scaled MSE 0.000233508; val RMSE 0.001886161; lr 0.000125; 62s
network 7, training 1, epoch 330: train scaled MSE 0.000285265; val RMSE 0.00191947; lr 0.000125; 63s
network 7, training 1, epoch 340: train scaled MSE 0.000224781; val RMSE 0.001896581; lr 0.000125; 65s
network 7, training 1, epoch 350: train scaled MSE 0.000226409; val RMSE 0.00188446; lr 0.000125; 67s
network 7, training 1, epoch 360: train scaled MSE 0.000215605; val RMSE 0.001881688; lr 0.000125; 69s
network 7, training 1, epoch 370: train scaled MSE 0.000299476; val RMSE 0.001882322; lr 0.000125; 71s
network 7, training 1, epoch 380: train scaled MSE 0.000208652; val RMSE 0.00188074; lr 6.25e-05; 73s
network 7, training 1, epoch 390: train scaled MSE 0.000193581; val RMSE 0.001878266; lr 6.25e-05; 75s
network 7, training 1, epoch 400: train scaled MSE 0.000200885; val RMSE 0.001878821; lr 6.25e-05; 77s
network 7, training 1, epoch 410: train scaled MSE 0.000188983; val RMSE 0.001876314; lr 6.25e-05; 79s
network 7, training 1, epoch 420: train scaled MSE 0.00018683; val RMSE 0.001875248; lr 6.25e-05; 80s
network 7, training 1, epoch 430: train scaled MSE 0.000187199; val RMSE 0.00187358; lr 6.25e-05; 82s
network 7, training 1, epoch 440: train scaled MSE 0.000180451; val RMSE 0.001871234; lr 6.25e-05; 84s
network 7, training 1, epoch 450: train scaled MSE 0.000178756; val RMSE 0.001876948; lr 6.25e-05; 86s
network 7, training 1, epoch 460: train scaled MSE 0.000181773; val RMSE 0.001869642; lr 3.125e-05; 88s
network 7, training 1, epoch 470: train scaled MSE 0.000172824; val RMSE 0.001870924; lr 3.125e-05; 90s
network 7, training 1, epoch 480: train scaled MSE 0.000170139; val RMSE 0.001868371; lr 3.125e-05; 92s
network 7, training 1, epoch 490: train scaled MSE 0.000168552; val RMSE 0.001868235; lr 3.125e-05; 94s
network 7, training 1, epoch 500: train scaled MSE 0.00017137; val RMSE 0.001869432; lr 3.125e-05; 96s
network 7, training 1, epoch 510: train scaled MSE 0.000172282; val RMSE 0.001867875; lr 1.5625e-05; 97s
network 7, training 1, epoch 520: train scaled MSE 0.000164779; val RMSE 0.001867228; lr 1.5625e-05; 99s
network 7, training 1, epoch 530: train scaled MSE 0.000169228; val RMSE 0.001867042; lr 1.5625e-05; 101s
network 7, training 1, epoch 540: train scaled MSE 0.000163094; val RMSE 0.001866401; lr 1.5625e-05; 103s
network 7, training 1, epoch 550: train scaled MSE 0.000162443; val RMSE 0.001866698; lr 1.5625e-05; 105s
network 7, training 1, epoch 560: train scaled MSE 0.00018406; val RMSE 0.001866496; lr 1.5625e-05; 107s
network 7, training 1, epoch 570: train scaled MSE 0.000169745; val RMSE 0.001866221; lr 1.5625e-05; 109s
network 7, training 1, epoch 580: train scaled MSE 0.000160638; val RMSE 0.001865408; lr 1.5625e-05; 111s
network 7, training 1, epoch 590: train scaled MSE 0.000160277; val RMSE 0.001865246; lr 1.5625e-05; 113s
network 7, training 1, epoch 600: train scaled MSE 0.000159253; val RMSE 0.001864596; lr 1.5625e-05; 115s
network 7, training 1, epoch 610: train scaled MSE 0.000169862; val RMSE 0.001864918; lr 1.5625e-05; 116s
network 7, training 1, epoch 620: train scaled MSE 0.00017624; val RMSE 0.001864638; lr 1.5625e-05; 118s
network 7, training 1, epoch 630: train scaled MSE 0.000158373; val RMSE 0.001863101; lr 1e-05; 120s
network 7, training 1, epoch 640: train scaled MSE 0.000156279; val RMSE 0.001863309; lr 1e-05; 122s
network 7, training 1, epoch 650: train scaled MSE 0.000157968; val RMSE 0.001863073; lr 1e-05; 124s
network 7, training 1, epoch 660: train scaled MSE 0.000160605; val RMSE 0.001863021; lr 1e-05; 126s
network 7, training 1, epoch 670: train scaled MSE 0.000155678; val RMSE 0.001862424; lr 1e-05; 128s
network 7, training 1, epoch 680: train scaled MSE 0.000155794; val RMSE 0.001862588; lr 1e-05; 130s
network 7, training 1, epoch 690: train scaled MSE 0.000171902; val RMSE 0.001862818; lr 1e-05; 132s
network 7, training 1, epoch 700: train scaled MSE 0.00015566; val RMSE 0.001862937; lr 1e-05; 134s
network 7, training 1, epoch 710: train scaled MSE 0.000159141; val RMSE 0.001862825; lr 1e-05; 136s
Standard Linear Baseline Validation RMSE: 0.002398835

Network seed 7, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0019,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0019,-0.1773,"[-1.10%, 0.53%]",0.0596,0.0,0.2596
MLP,0.0018,15.7308,"[5.13%, 24.23%]",0.4466,649.2313,0.2481

network 7, training 2, epoch 1: train scaled MSE 0.816306; val RMSE 0.01907581; lr 0.001; 0s
network 7, training 2, epoch 10: train scaled MSE 0.0232589; val RMSE 0.003515175; lr 0.001; 2s
network 7, training 2, epoch 20: train scaled MSE 0.010545; val RMSE 0.002072419; lr 0.001; 4s
network 7, training 2, epoch 30: train scaled MSE 0.00790926; val RMSE 0.002280277; lr 0.001; 6s
network 7, training 2, epoch 40: train scaled MSE 0.00962713; val RMSE 0.001758012; lr 0.001; 8s
network 7, training 2, epoch 50: train scaled MSE 0.00526513; val RMSE 0.001560759; lr 0.001; 10s
network 7, training 2, epoch 60: train scaled MSE 0.00408649; val RMSE 0.001655092; lr 0.001; 12s
network 7, training 2, epoch 70: train scaled MSE 0.00293674; val RMSE 0.001452615; lr 0.0005; 14s
network 7, training 2, epoch 80: train scaled MSE 0.00244671; val RMSE 0.001449522; lr 0.0005; 16s
network 7, training 2, epoch 90: train scaled MSE 0.00296686; val RMSE 0.00145832; lr 0.0005; 18s
network 7, training 2, epoch 100: train scaled MSE 0.00227709; val RMSE 0.001652633; lr 0.0005; 19s
network 7, training 2, epoch 110: train scaled MSE 0.00156311; val RMSE 0.001461707; lr 0.0005; 21s
network 7, training 2, epoch 120: train scaled MSE 0.00129279; val RMSE 0.001366897; lr 0.00025; 23s
network 7, training 2, epoch 130: train scaled MSE 0.00118722; val RMSE 0.001490723; lr 0.00025; 25s
network 7, training 2, epoch 140: train scaled MSE 0.00113224; val RMSE 0.001355142; lr 0.00025; 27s
network 7, training 2, epoch 150: train scaled MSE 0.00104503; val RMSE 0.001345562; lr 0.00025; 29s
network 7, training 2, epoch 160: train scaled MSE 0.000967988; val RMSE 0.001333976; lr 0.00025; 31s
network 7, training 2, epoch 170: train scaled MSE 0.000889609; val RMSE 0.001330522; lr 0.00025; 33s
network 7, training 2, epoch 180: train scaled MSE 0.00085151; val RMSE 0.001332575; lr 0.00025; 35s
network 7, training 2, epoch 190: train scaled MSE 0.000758896; val RMSE 0.001314741; lr 0.000125; 37s
network 7, training 2, epoch 200: train scaled MSE 0.000974474; val RMSE 0.001319456; lr 0.000125; 39s
network 7, training 2, epoch 210: train scaled MSE 0.000708088; val RMSE 0.001311136; lr 0.000125; 41s
network 7, training 2, epoch 220: train scaled MSE 0.000737243; val RMSE 0.00130766; lr 0.000125; 43s
network 7, training 2, epoch 230: train scaled MSE 0.000657906; val RMSE 0.001308879; lr 0.000125; 45s
network 7, training 2, epoch 240: train scaled MSE 0.000634708; val RMSE 0.001301629; lr 0.000125; 47s
network 7, training 2, epoch 250: train scaled MSE 0.000771762; val RMSE 0.00137346; lr 0.000125; 49s
network 7, training 2, epoch 260: train scaled MSE 0.000595685; val RMSE 0.001302461; lr 0.000125; 51s
network 7, training 2, epoch 270: train scaled MSE 0.000564642; val RMSE 0.001292553; lr 6.25e-05; 52s
network 7, training 2, epoch 280: train scaled MSE 0.00054712; val RMSE 0.00129152; lr 6.25e-05; 54s
network 7, training 2, epoch 290: train scaled MSE 0.000538384; val RMSE 0.001301883; lr 6.25e-05; 56s
network 7, training 2, epoch 300: train scaled MSE 0.000523595; val RMSE 0.001287528; lr 6.25e-05; 58s
network 7, training 2, epoch 310: train scaled MSE 0.000534393; val RMSE 0.001286588; lr 6.25e-05; 60s
network 7, training 2, epoch 320: train scaled MSE 0.000505542; val RMSE 0.001287652; lr 6.25e-05; 62s
network 7, training 2, epoch 330: train scaled MSE 0.000494994; val RMSE 0.001284963; lr 6.25e-05; 64s
network 7, training 2, epoch 340: train scaled MSE 0.00048313; val RMSE 0.001283936; lr 6.25e-05; 66s
network 7, training 2, epoch 350: train scaled MSE 0.000474002; val RMSE 0.001281821; lr 6.25e-05; 68s
network 7, training 2, epoch 360: train scaled MSE 0.000493188; val RMSE 0.00128375; lr 6.25e-05; 70s
network 7, training 2, epoch 370: train scaled MSE 0.000470048; val RMSE 0.001279926; lr 6.25e-05; 72s
network 7, training 2, epoch 380: train scaled MSE 0.000449097; val RMSE 0.001279576; lr 6.25e-05; 74s
network 7, training 2, epoch 390: train scaled MSE 0.000439648; val RMSE 0.001277682; lr 6.25e-05; 76s
network 7, training 2, epoch 400: train scaled MSE 0.000429899; val RMSE 0.00127696; lr 6.25e-05; 78s
network 7, training 2, epoch 410: train scaled MSE 0.00043239; val RMSE 0.001277281; lr 6.25e-05; 80s
network 7, training 2, epoch 420: train scaled MSE 0.000414044; val RMSE 0.001275354; lr 6.25e-05; 82s
network 7, training 2, epoch 430: train scaled MSE 0.000405766; val RMSE 0.001276535; lr 6.25e-05; 83s
network 7, training 2, epoch 440: train scaled MSE 0.000398578; val RMSE 0.001293363; lr 6.25e-05; 85s
network 7, training 2, epoch 450: train scaled MSE 0.000392511; val RMSE 0.001274423; lr 6.25e-05; 87s
network 7, training 2, epoch 460: train scaled MSE 0.000381043; val RMSE 0.001274904; lr 6.25e-05; 89s
network 7, training 2, epoch 470: train scaled MSE 0.000420572; val RMSE 0.001279602; lr 6.25e-05; 91s
network 7, training 2, epoch 480: train scaled MSE 0.000359207; val RMSE 0.001271155; lr 3.125e-05; 93s
network 7, training 2, epoch 490: train scaled MSE 0.000354419; val RMSE 0.001273768; lr 3.125e-05; 95s
network 7, training 2, epoch 500: train scaled MSE 0.000355918; val RMSE 0.001269925; lr 3.125e-05; 96s
network 7, training 2, epoch 510: train scaled MSE 0.000344765; val RMSE 0.001269496; lr 3.125e-05; 98s
network 7, training 2, epoch 520: train scaled MSE 0.000343352; val RMSE 0.001268689; lr 3.125e-05; 100s
network 7, training 2, epoch 530: train scaled MSE 0.000334453; val RMSE 0.001268451; lr 1.5625e-05; 102s
network 7, training 2, epoch 540: train scaled MSE 0.000331406; val RMSE 0.001267789; lr 1.5625e-05; 103s
network 7, training 2, epoch 550: train scaled MSE 0.000331692; val RMSE 0.001267949; lr 1.5625e-05; 105s
network 7, training 2, epoch 560: train scaled MSE 0.000327614; val RMSE 0.00126707; lr 1.5625e-05; 107s
network 7, training 2, epoch 570: train scaled MSE 0.000341496; val RMSE 0.001268654; lr 1.5625e-05; 109s
network 7, training 2, epoch 580: train scaled MSE 0.000323835; val RMSE 0.00126672; lr 1e-05; 111s
network 7, training 2, epoch 590: train scaled MSE 0.000322382; val RMSE 0.001267065; lr 1e-05; 112s
network 7, training 2, epoch 600: train scaled MSE 0.000320271; val RMSE 0.00126617; lr 1e-05; 114s
network 7, training 2, epoch 610: train scaled MSE 0.000332136; val RMSE 0.001267175; lr 1e-05; 116s
network 7, training 2, epoch 620: train scaled MSE 0.000318956; val RMSE 0.001266183; lr 1e-05; 118s
network 7, training 2, epoch 630: train scaled MSE 0.000317717; val RMSE 0.001265692; lr 1e-05; 120s
network 7, training 2, epoch 640: train scaled MSE 0.000316646; val RMSE 0.00126544; lr 1e-05; 122s
network 7, training 2, epoch 650: train scaled MSE 0.000316513; val RMSE 0.001265681; lr 1e-05; 123s
network 7, training 2, epoch 660: train scaled MSE 0.000315661; val RMSE 0.001265023; lr 1e-05; 125s
network 7, training 2, epoch 670: train scaled MSE 0.000313066; val RMSE 0.001265145; lr 1e-05; 127s
network 7, training 2, epoch 680: train scaled MSE 0.000315017; val RMSE 0.001265727; lr 1e-05; 129s
network 7, training 2, epoch 690: train scaled MSE 0.000312496; val RMSE 0.001264879; lr 1e-05; 131s
network 7, training 2, epoch 700: train scaled MSE 0.000316464; val RMSE 0.00126562; lr 1e-05; 133s
network 7, training 2, epoch 710: train scaled MSE 0.000315016; val RMSE 0.001265107; lr 1e-05; 134s
network 7, training 2, epoch 720: train scaled MSE 0.000315139; val RMSE 0.001265887; lr 1e-05; 136s
network 7, training 2, epoch 730: train scaled MSE 0.000307555; val RMSE 0.001264422; lr 1e-05; 138s
network 7, training 2, epoch 740: train scaled MSE 0.000307126; val RMSE 0.001264143; lr 1e-05; 140s
network 7, training 2, epoch 750: train scaled MSE 0.000307785; val RMSE 0.001264857; lr 1e-05; 142s
network 7, training 2, epoch 760: train scaled MSE 0.000305685; val RMSE 0.001264052; lr 1e-05; 143s
network 7, training 2, epoch 770: train scaled MSE 0.000310557; val RMSE 0.001264313; lr 1e-05; 145s
network 7, training 2, epoch 780: train scaled MSE 0.000302636; val RMSE 0.001263658; lr 1e-05; 147s
network 7, training 2, epoch 790: train scaled MSE 0.000301528; val RMSE 0.001263439; lr 1e-05; 149s
network 7, training 2, epoch 800: train scaled MSE 0.000300533; val RMSE 0.001263402; lr 1e-05; 151s
network 7, training 2, epoch 810: train scaled MSE 0.000299177; val RMSE 0.001263086; lr 1e-05; 152s
network 7, training 2, epoch 820: train scaled MSE 0.000299289; val RMSE 0.00126366; lr 1e-05; 154s
network 7, training 2, epoch 830: train scaled MSE 0.000298455; val RMSE 0.001263125; lr 1e-05; 156s
network 7, training 2, epoch 840: train scaled MSE 0.000295742; val RMSE 0.00126277; lr 1e-05; 158s
network 7, training 2, epoch 850: train scaled MSE 0.000323512; val RMSE 0.001263799; lr 1e-05; 160s
network 7, training 2, epoch 860: train scaled MSE 0.000295257; val RMSE 0.001262579; lr 1e-05; 162s
network 7, training 2, epoch 870: train scaled MSE 0.000295402; val RMSE 0.001262906; lr 1e-05; 164s
network 7, training 2, epoch 880: train scaled MSE 0.000292211; val RMSE 0.001262253; lr 1e-05; 166s
network 7, training 2, epoch 890: train scaled MSE 0.000291391; val RMSE 0.001262003; lr 1e-05; 167s
network 7, training 2, epoch 900: train scaled MSE 0.000290028; val RMSE 0.001262039; lr 1e-05; 169s
network 7, training 2, epoch 910: train scaled MSE 0.00028929; val RMSE 0.001261498; lr 1e-05; 171s
network 7, training 2, epoch 920: train scaled MSE 0.000289515; val RMSE 0.001262239; lr 1e-05; 173s
network 7, training 2, epoch 930: train scaled MSE 0.000298619; val RMSE 0.001263112; lr 1e-05; 175s
network 7, training 2, epoch 940: train scaled MSE 0.000289453; val RMSE 0.001261582; lr 1e-05; 177s
network 7, training 2, epoch 950: train scaled MSE 0.000300361; val RMSE 0.00126202; lr 1e-05; 179s
network 7, training 2, epoch 960: train scaled MSE 0.000284249; val RMSE 0.001261174; lr 1e-05; 181s
network 7, training 2, epoch 970: train scaled MSE 0.000284756; val RMSE 0.001261185; lr 1e-05; 182s
network 7, training 2, epoch 980: train scaled MSE 0.000281715; val RMSE 0.001261131; lr 1e-05; 184s
network 7, training 2, epoch 990: train scaled MSE 0.000281223; val RMSE 0.001260828; lr 1e-05; 186s
network 7, training 2, epoch 1000: train scaled MSE 0.00028775; val RMSE 0.001261794; lr 1e-05; 188s
network 7, training 2, epoch 1010: train scaled MSE 0.000280768; val RMSE 0.001261928; lr 1e-05; 190s
network 7, training 2, epoch 1020: train scaled MSE 0.000279592; val RMSE 0.00126123; lr 1e-05; 191s
network 7, training 2, epoch 1030: train scaled MSE 0.000277528; val RMSE 0.001260594; lr 1e-05; 193s
network 7, training 2, epoch 1040: train scaled MSE 0.000276521; val RMSE 0.001260344; lr 1e-05; 195s
network 7, training 2, epoch 1050: train scaled MSE 0.000275766; val RMSE 0.001260283; lr 1e-05; 197s
network 7, training 2, epoch 1060: train scaled MSE 0.000274491; val RMSE 0.001260017; lr 1e-05; 199s
network 7, training 2, epoch 1070: train scaled MSE 0.000273885; val RMSE 0.00125995; lr 1e-05; 200s
network 7, training 2, epoch 1080: train scaled MSE 0.000273077; val RMSE 0.001259945; lr 1e-05; 202s
network 7, training 2, epoch 1090: train scaled MSE 0.000271852; val RMSE 0.001259609; lr 1e-05; 204s
network 7, training 2, epoch 1100: train scaled MSE 0.000271057; val RMSE 0.001259353; lr 1e-05; 206s
network 7, training 2, epoch 1110: train scaled MSE 0.000270601; val RMSE 0.001259485; lr 1e-05; 207s
network 7, training 2, epoch 1120: train scaled MSE 0.000269608; val RMSE 0.001259309; lr 1e-05; 209s
network 7, training 2, epoch 1130: train scaled MSE 0.000267598; val RMSE 0.001260254; lr 1e-05; 211s
network 7, training 2, epoch 1140: train scaled MSE 0.000277248; val RMSE 0.001260253; lr 1e-05; 213s
network 7, training 2, epoch 1150: train scaled MSE 0.000265519; val RMSE 0.001258895; lr 1e-05; 215s
network 7, training 2, epoch 1160: train scaled MSE 0.000269606; val RMSE 0.00125955; lr 1e-05; 216s
network 7, training 2, epoch 1170: train scaled MSE 0.000264187; val RMSE 0.001258789; lr 1e-05; 218s
network 7, training 2, epoch 1180: train scaled MSE 0.000264664; val RMSE 0.001258474; lr 1e-05; 220s
network 7, training 2, epoch 1190: train scaled MSE 0.000263068; val RMSE 0.00125831; lr 1e-05; 222s
network 7, training 2, epoch 1200: train scaled MSE 0.000263585; val RMSE 0.001258264; lr 1e-05; 224s
network 7, training 2, epoch 1210: train scaled MSE 0.00026448; val RMSE 0.001259935; lr 1e-05; 226s
network 7, training 2, epoch 1220: train scaled MSE 0.000260735; val RMSE 0.001258297; lr 1e-05; 227s
network 7, training 2, epoch 1230: train scaled MSE 0.00026311; val RMSE 0.001258114; lr 1e-05; 229s
network 7, training 2, epoch 1240: train scaled MSE 0.000258728; val RMSE 0.001257591; lr 1e-05; 231s
network 7, training 2, epoch 1250: train scaled MSE 0.0002645; val RMSE 0.001257815; lr 1e-05; 233s
network 7, training 2, epoch 1260: train scaled MSE 0.000257902; val RMSE 0.001257161; lr 1e-05; 235s
network 7, training 2, epoch 1270: train scaled MSE 0.000256942; val RMSE 0.001257596; lr 1e-05; 237s
network 7, training 2, epoch 1280: train scaled MSE 0.000255188; val RMSE 0.001257163; lr 1e-05; 238s
network 7, training 2, epoch 1290: train scaled MSE 0.000254344; val RMSE 0.001256964; lr 1e-05; 240s
network 7, training 2, epoch 1300: train scaled MSE 0.00025391; val RMSE 0.001256821; lr 1e-05; 242s
network 7, training 2, epoch 1310: train scaled MSE 0.000253788; val RMSE 0.001257722; lr 1e-05; 244s
network 7, training 2, epoch 1320: train scaled MSE 0.000252069; val RMSE 0.001256644; lr 1e-05; 246s
network 7, training 2, epoch 1330: train scaled MSE 0.000252056; val RMSE 0.001256683; lr 1e-05; 247s
network 7, training 2, epoch 1340: train scaled MSE 0.000252952; val RMSE 0.001257541; lr 1e-05; 249s
network 7, training 2, epoch 1350: train scaled MSE 0.000250258; val RMSE 0.001256333; lr 1e-05; 251s
network 7, training 2, epoch 1360: train scaled MSE 0.000259182; val RMSE 0.001256893; lr 1e-05; 253s
network 7, training 2, epoch 1370: train scaled MSE 0.000248381; val RMSE 0.001255911; lr 1e-05; 255s
network 7, training 2, epoch 1380: train scaled MSE 0.000247928; val RMSE 0.001255781; lr 1e-05; 257s
network 7, training 2, epoch 1390: train scaled MSE 0.00024695; val RMSE 0.001255631; lr 1e-05; 258s
network 7, training 2, epoch 1400: train scaled MSE 0.000249489; val RMSE 0.00125635; lr 1e-05; 260s
network 7, training 2, epoch 1410: train scaled MSE 0.000245478; val RMSE 0.001255478; lr 1e-05; 262s
network 7, training 2, epoch 1420: train scaled MSE 0.000244793; val RMSE 0.001255831; lr 1e-05; 264s
network 7, training 2, epoch 1430: train scaled MSE 0.000244505; val RMSE 0.00125537; lr 1e-05; 266s
network 7, training 2, epoch 1440: train scaled MSE 0.000243312; val RMSE 0.001255359; lr 1e-05; 268s
network 7, training 2, epoch 1450: train scaled MSE 0.00024512; val RMSE 0.001254915; lr 1e-05; 269s
network 7, training 2, epoch 1460: train scaled MSE 0.00024528; val RMSE 0.001254956; lr 1e-05; 271s
network 7, training 2, epoch 1470: train scaled MSE 0.00024191; val RMSE 0.001254588; lr 1e-05; 273s
network 7, training 2, epoch 1480: train scaled MSE 0.000240661; val RMSE 0.001254344; lr 1e-05; 275s
network 7, training 2, epoch 1490: train scaled MSE 0.000239951; val RMSE 0.001254507; lr 1e-05; 277s
network 7, training 2, epoch 1500: train scaled MSE 0.00024749; val RMSE 0.001255295; lr 1e-05; 278s
network 7, training 2, epoch 1510: train scaled MSE 0.000238891; val RMSE 0.001254333; lr 1e-05; 280s
network 7, training 2, epoch 1520: train scaled MSE 0.000238773; val RMSE 0.001254314; lr 1e-05; 282s
network 7, training 2, epoch 1530: train scaled MSE 0.000237108; val RMSE 0.001254115; lr 1e-05; 284s
network 7, training 2, epoch 1540: train scaled MSE 0.000242259; val RMSE 0.001254233; lr 1e-05; 286s
network 7, training 2, epoch 1550: train scaled MSE 0.000235864; val RMSE 0.001253867; lr 1e-05; 287s
network 7, training 2, epoch 1560: train scaled MSE 0.000255362; val RMSE 0.001257424; lr 1e-05; 289s
network 7, training 2, epoch 1570: train scaled MSE 0.000246692; val RMSE 0.001254467; lr 1e-05; 291s
network 7, training 2, epoch 1580: train scaled MSE 0.000234015; val RMSE 0.001253734; lr 1e-05; 293s
network 7, training 2, epoch 1590: train scaled MSE 0.000234937; val RMSE 0.001253777; lr 1e-05; 295s
network 7, training 2, epoch 1600: train scaled MSE 0.000232479; val RMSE 0.001254033; lr 1e-05; 296s
network 7, training 2, epoch 1610: train scaled MSE 0.000231514; val RMSE 0.00125315; lr 1e-05; 298s
network 7, training 2, epoch 1620: train scaled MSE 0.000231074; val RMSE 0.001254267; lr 1e-05; 300s
network 7, training 2, epoch 1630: train scaled MSE 0.000230107; val RMSE 0.001252829; lr 1e-05; 302s
network 7, training 2, epoch 1640: train scaled MSE 0.000229573; val RMSE 0.001252863; lr 1e-05; 304s
network 7, training 2, epoch 1650: train scaled MSE 0.000228679; val RMSE 0.001252598; lr 1e-05; 306s
network 7, training 2, epoch 1660: train scaled MSE 0.0002283; val RMSE 0.00125253; lr 1e-05; 307s
network 7, training 2, epoch 1670: train scaled MSE 0.000227274; val RMSE 0.001252237; lr 1e-05; 309s
network 7, training 2, epoch 1680: train scaled MSE 0.000226823; val RMSE 0.001252397; lr 1e-05; 311s
network 7, training 2, epoch 1690: train scaled MSE 0.000237235; val RMSE 0.00125376; lr 1e-05; 313s
network 7, training 2, epoch 1700: train scaled MSE 0.000224957; val RMSE 0.001252048; lr 1e-05; 315s
network 7, training 2, epoch 1710: train scaled MSE 0.000224236; val RMSE 0.001251819; lr 1e-05; 317s
network 7, training 2, epoch 1720: train scaled MSE 0.000223386; val RMSE 0.001251772; lr 1e-05; 319s
network 7, training 2, epoch 1730: train scaled MSE 0.000225127; val RMSE 0.001251182; lr 1e-05; 320s
network 7, training 2, epoch 1740: train scaled MSE 0.000222177; val RMSE 0.001252646; lr 1e-05; 322s
network 7, training 2, epoch 1750: train scaled MSE 0.000225665; val RMSE 0.00125181; lr 1e-05; 324s
network 7, training 2, epoch 1760: train scaled MSE 0.000221931; val RMSE 0.001251294; lr 1e-05; 326s
network 7, training 2, epoch 1770: train scaled MSE 0.000221221; val RMSE 0.001250875; lr 1e-05; 328s
network 7, training 2, epoch 1780: train scaled MSE 0.000224095; val RMSE 0.001251015; lr 1e-05; 330s
network 7, training 2, epoch 1790: train scaled MSE 0.000219701; val RMSE 0.00125055; lr 1e-05; 332s
network 7, training 2, epoch 1800: train scaled MSE 0.000223108; val RMSE 0.001251363; lr 1e-05; 334s
network 7, training 2, epoch 1810: train scaled MSE 0.000218823; val RMSE 0.001250897; lr 1e-05; 336s
network 7, training 2, epoch 1820: train scaled MSE 0.000217376; val RMSE 0.001251318; lr 1e-05; 338s
network 7, training 2, epoch 1830: train scaled MSE 0.000216556; val RMSE 0.001250322; lr 1e-05; 340s
network 7, training 2, epoch 1840: train scaled MSE 0.000215945; val RMSE 0.001250211; lr 1e-05; 342s
network 7, training 2, epoch 1850: train scaled MSE 0.000217847; val RMSE 0.001250409; lr 1e-05; 343s
network 7, training 2, epoch 1860: train scaled MSE 0.00021528; val RMSE 0.001250131; lr 1e-05; 345s
network 7, training 2, epoch 1870: train scaled MSE 0.000214521; val RMSE 0.001249727; lr 1e-05; 347s
network 7, training 2, epoch 1880: train scaled MSE 0.000215471; val RMSE 0.001250085; lr 1e-05; 349s
network 7, training 2, epoch 1890: train scaled MSE 0.000213127; val RMSE 0.001249829; lr 1e-05; 351s
network 7, training 2, epoch 1900: train scaled MSE 0.00021333; val RMSE 0.00124979; lr 1e-05; 353s
network 7, training 2, epoch 1910: train scaled MSE 0.00021501; val RMSE 0.001250184; lr 1e-05; 355s
network 7, training 2, epoch 1920: train scaled MSE 0.000211131; val RMSE 0.001248902; lr 1e-05; 357s
network 7, training 2, epoch 1930: train scaled MSE 0.000210562; val RMSE 0.001249136; lr 1e-05; 358s
network 7, training 2, epoch 1940: train scaled MSE 0.000210434; val RMSE 0.001249073; lr 1e-05; 360s
network 7, training 2, epoch 1950: train scaled MSE 0.000219924; val RMSE 0.00124997; lr 1e-05; 362s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0020,0.0000,-,0.000,-,0.0000
Linear Regression,0.0020,-0.8408,"[-2.37%, 0.52%]",0.055,0.0,0.2067
MLP,0.0017,29.8162,"[20.37%, 38.74%]",0.555,908.2819,0.2947

network 7, training 3, epoch 1: train scaled MSE 0.835435; val RMSE 0.01871444; lr 0.001; 0s
network 7, training 3, epoch 10: train scaled MSE 0.0156028; val RMSE 0.006337761; lr 0.001; 2s
network 7, training 3, epoch 20: train scaled MSE 0.00713756; val RMSE 0.001990616; lr 0.001; 4s
network 7, training 3, epoch 30: train scaled MSE 0.00610249; val RMSE 0.001992112; lr 0.001; 6s
network 7, training 3, epoch 40: train scaled MSE 0.00491458; val RMSE 0.002361469; lr 0.001; 8s
network 7, training 3, epoch 50: train scaled MSE 0.00447622; val RMSE 0.001579946; lr 0.001; 10s
network 7, training 3, epoch 60: train scaled MSE 0.00366996; val RMSE 0.00151648; lr 0.001; 12s
network 7, training 3, epoch 70: train scaled MSE 0.00363079; val RMSE 0.001489396; lr 0.001; 14s
network 7, training 3, epoch 80: train scaled MSE 0.00227042; val RMSE 0.001812747; lr 0.001; 16s
network 7, training 3, epoch 90: train scaled MSE 0.0459694; val RMSE 0.002093529; lr 0.001; 18s
network 7, training 3, epoch 100: train scaled MSE 0.00201314; val RMSE 0.001432569; lr 0.0005; 20s
network 7, training 3, epoch 110: train scaled MSE 0.00140615; val RMSE 0.001380816; lr 0.0005; 22s
network 7, training 3, epoch 120: train scaled MSE 0.00126496; val RMSE 0.001363754; lr 0.0005; 24s
network 7, training 3, epoch 130: train scaled MSE 0.00113756; val RMSE 0.001340983; lr 0.0005; 26s
network 7, training 3, epoch 140: train scaled MSE 0.00103844; val RMSE 0.001372573; lr 0.0005; 28s
network 7, training 3, epoch 150: train scaled MSE 0.000858306; val RMSE 0.001333598; lr 0.0005; 30s
network 7, training 3, epoch 160: train scaled MSE 0.000860819; val RMSE 0.001331534; lr 0.0005; 32s
network 7, training 3, epoch 170: train scaled MSE 0.000701571; val RMSE 0.001307079; lr 0.00025; 34s
network 7, training 3, epoch 180: train scaled MSE 0.000749628; val RMSE 0.001314398; lr 0.00025; 36s
network 7, training 3, epoch 190: train scaled MSE 0.000668962; val RMSE 0.001305108; lr 0.00025; 38s
network 7, training 3, epoch 200: train scaled MSE 0.00058542; val RMSE 0.001295428; lr 0.00025; 40s
network 7, training 3, epoch 210: train scaled MSE 0.000647798; val RMSE 0.001301721; lr 0.00025; 42s
network 7, training 3, epoch 220: train scaled MSE 0.000504573; val RMSE 0.001284678; lr 0.000125; 44s
network 7, training 3, epoch 230: train scaled MSE 0.000512224; val RMSE 0.001281057; lr 0.000125; 46s
network 7, training 3, epoch 240: train scaled MSE 0.000631825; val RMSE 0.00130346; lr 0.000125; 48s
network 7, training 3, epoch 250: train scaled MSE 0.000508658; val RMSE 0.001274168; lr 0.000125; 50s
network 7, training 3, epoch 260: train scaled MSE 0.000441848; val RMSE 0.001268622; lr 0.000125; 52s
network 7, training 3, epoch 270: train scaled MSE 0.000424388; val RMSE 0.001266721; lr 0.000125; 54s
network 7, training 3, epoch 280: train scaled MSE 0.000558012; val RMSE 0.00130248; lr 0.000125; 56s
network 7, training 3, epoch 290: train scaled MSE 0.000394161; val RMSE 0.001262795; lr 0.000125; 58s
network 7, training 3, epoch 300: train scaled MSE 0.000389422; val RMSE 0.001262931; lr 0.000125; 60s
network 7, training 3, epoch 310: train scaled MSE 0.000378742; val RMSE 0.001259118; lr 0.000125; 62s
network 7, training 3, epoch 320: train scaled MSE 0.000359563; val RMSE 0.001256218; lr 0.000125; 64s
network 7, training 3, epoch 330: train scaled MSE 0.000462515; val RMSE 0.0012905; lr 0.000125; 66s
network 7, training 3, epoch 340: train scaled MSE 0.000333131; val RMSE 0.001257694; lr 6.25e-05; 68s
network 7, training 3, epoch 350: train scaled MSE 0.000336663; val RMSE 0.001258613; lr 3.125e-05; 70s
network 7, training 3, epoch 360: train scaled MSE 0.000347454; val RMSE 0.001255132; lr 3.125e-05; 72s
network 7, training 3, epoch 370: train scaled MSE 0.000316315; val RMSE 0.001252707; lr 3.125e-05; 73s
network 7, training 3, epoch 380: train scaled MSE 0.000312432; val RMSE 0.001254335; lr 3.125e-05; 75s
network 7, training 3, epoch 390: train scaled MSE 0.000310592; val RMSE 0.001250819; lr 3.125e-05; 77s
network 7, training 3, epoch 400: train scaled MSE 0.000336883; val RMSE 0.001252767; lr 3.125e-05; 79s
network 7, training 3, epoch 410: train scaled MSE 0.000305699; val RMSE 0.001249028; lr 3.125e-05; 81s
network 7, training 3, epoch 420: train scaled MSE 0.000299777; val RMSE 0.001247927; lr 3.125e-05; 83s
network 7, training 3, epoch 430: train scaled MSE 0.000303783; val RMSE 0.001248471; lr 3.125e-05; 85s
network 7, training 3, epoch 440: train scaled MSE 0.000298229; val RMSE 0.001247936; lr 3.125e-05; 87s
network 7, training 3, epoch 450: train scaled MSE 0.000290708; val RMSE 0.001246043; lr 3.125e-05; 89s
network 7, training 3, epoch 460: train scaled MSE 0.000287112; val RMSE 0.001247284; lr 3.125e-05; 91s
network 7, training 3, epoch 470: train scaled MSE 0.000285043; val RMSE 0.001245686; lr 1.5625e-05; 93s
network 7, training 3, epoch 480: train scaled MSE 0.000281144; val RMSE 0.001244742; lr 1.5625e-05; 95s
network 7, training 3, epoch 490: train scaled MSE 0.000285158; val RMSE 0.001245116; lr 1.5625e-05; 97s
network 7, training 3, epoch 500: train scaled MSE 0.000277949; val RMSE 0.00124412; lr 1e-05; 99s
network 7, training 3, epoch 510: train scaled MSE 0.000276234; val RMSE 0.001243428; lr 1e-05; 100s
network 7, training 3, epoch 520: train scaled MSE 0.000275833; val RMSE 0.001243691; lr 1e-05; 102s
network 7, training 3, epoch 530: train scaled MSE 0.000274367; val RMSE 0.00124313; lr 1e-05; 104s
network 7, training 3, epoch 540: train scaled MSE 0.000273353; val RMSE 0.001243073; lr 1e-05; 106s
network 7, training 3, epoch 550: train scaled MSE 0.000272314; val RMSE 0.001242654; lr 1e-05; 108s
network 7, training 3, epoch 560: train scaled MSE 0.00027135; val RMSE 0.001242792; lr 1e-05; 110s
network 7, training 3, epoch 570: train scaled MSE 0.000270095; val RMSE 0.00124211; lr 1e-05; 112s
network 7, training 3, epoch 580: train scaled MSE 0.000269608; val RMSE 0.001241903; lr 1e-05; 114s
network 7, training 3, epoch 590: train scaled MSE 0.000267883; val RMSE 0.001241422; lr 1e-05; 116s
network 7, training 3, epoch 600: train scaled MSE 0.000266838; val RMSE 0.001241396; lr 1e-05; 118s
network 7, training 3, epoch 610: train scaled MSE 0.000268324; val RMSE 0.001241657; lr 1e-05; 120s
network 7, training 3, epoch 620: train scaled MSE 0.000264773; val RMSE 0.001241152; lr 1e-05; 122s
network 7, training 3, epoch 630: train scaled MSE 0.000264605; val RMSE 0.001240811; lr 1e-05; 124s
network 7, training 3, epoch 640: train scaled MSE 0.000262546; val RMSE 0.00124095; lr 1e-05; 125s
network 7, training 3, epoch 650: train scaled MSE 0.000271693; val RMSE 0.001240785; lr 1e-05; 127s
network 7, training 3, epoch 660: train scaled MSE 0.000261009; val RMSE 0.001240271; lr 1e-05; 129s
network 7, training 3, epoch 670: train scaled MSE 0.000259847; val RMSE 0.001240746; lr 1e-05; 131s
network 7, training 3, epoch 680: train scaled MSE 0.000280864; val RMSE 0.001242384; lr 1e-05; 133s
network 7, training 3, epoch 690: train scaled MSE 0.000258408; val RMSE 0.001240041; lr 1e-05; 135s
network 7, training 3, epoch 700: train scaled MSE 0.000258562; val RMSE 0.001240418; lr 1e-05; 137s
network 7, training 3, epoch 710: train scaled MSE 0.000257497; val RMSE 0.00123954; lr 1e-05; 139s
network 7, training 3, epoch 720: train scaled MSE 0.000275; val RMSE 0.001242074; lr 1e-05; 141s
network 7, training 3, epoch 730: train scaled MSE 0.000255511; val RMSE 0.001239325; lr 1e-05; 143s
network 7, training 3, epoch 740: train scaled MSE 0.000254841; val RMSE 0.001239362; lr 1e-05; 145s
network 7, training 3, epoch 750: train scaled MSE 0.000253721; val RMSE 0.001238955; lr 1e-05; 147s
network 7, training 3, epoch 760: train scaled MSE 0.000254705; val RMSE 0.00123899; lr 1e-05; 148s
network 7, training 3, epoch 770: train scaled MSE 0.000252644; val RMSE 0.001238933; lr 1e-05; 150s
network 7, training 3, epoch 780: train scaled MSE 0.000258008; val RMSE 0.00123921; lr 1e-05; 152s
network 7, training 3, epoch 790: train scaled MSE 0.000274738; val RMSE 0.001241355; lr 1e-05; 154s
network 7, training 3, epoch 800: train scaled MSE 0.00025065; val RMSE 0.001238317; lr 1e-05; 156s
network 7, training 3, epoch 810: train scaled MSE 0.000249517; val RMSE 0.001238045; lr 1e-05; 158s
network 7, training 3, epoch 820: train scaled MSE 0.000249276; val RMSE 0.001237793; lr 1e-05; 160s
network 7, training 3, epoch 830: train scaled MSE 0.000247923; val RMSE 0.0012376; lr 1e-05; 162s
network 7, training 3, epoch 840: train scaled MSE 0.000247239; val RMSE 0.001237322; lr 1e-05; 164s
network 7, training 3, epoch 850: train scaled MSE 0.000251851; val RMSE 0.001238001; lr 1e-05; 166s
network 7, training 3, epoch 860: train scaled MSE 0.000245145; val RMSE 0.001237258; lr 1e-05; 168s
network 7, training 3, epoch 870: train scaled MSE 0.000246893; val RMSE 0.001237136; lr 1e-05; 170s
network 7, training 3, epoch 880: train scaled MSE 0.000246769; val RMSE 0.001236809; lr 1e-05; 172s
network 7, training 3, epoch 890: train scaled MSE 0.000244251; val RMSE 0.001237092; lr 1e-05; 175s
network 7, training 3, epoch 900: train scaled MSE 0.000242015; val RMSE 0.001236818; lr 1e-05; 177s
network 7, training 3, epoch 910: train scaled MSE 0.000241382; val RMSE 0.001236121; lr 1e-05; 179s
network 7, training 3, epoch 920: train scaled MSE 0.000240539; val RMSE 0.001236287; lr 1e-05; 181s
network 7, training 3, epoch 1480: train scaled MSE 0.000205981; val RMSE 0.001229477; lr 1e-05; 289s
network 7, training 3, epoch 1490: train scaled MSE 0.000204415; val RMSE 0.001229505; lr 1e-05; 291s
network 7, training 3, epoch 1500: train scaled MSE 0.000203997; val RMSE 0.00122934; lr 1e-05; 293s
network 7, training 3, epoch 1510: train scaled MSE 0.00020364; val RMSE 0.001229182; lr 1e-05; 294s
network 7, training 3, epoch 1520: train scaled MSE 0.00020714; val RMSE 0.00122983; lr 1e-05; 296s
network 7, training 3, epoch 1530: train scaled MSE 0.000202296; val RMSE 0.001229184; lr 1e-05; 298s
network 7, training 3, epoch 1540: train scaled MSE 0.000201994; val RMSE 0.001229221; lr 1e-05; 300s
network 7, training 3, epoch 1550: train scaled MSE 0.000201454; val RMSE 0.001228943; lr 1e-05; 302s
network 7, training 3, epoch 1560: train scaled MSE 0.000200716; val RMSE 0.001229171; lr 1e-05; 304s
network 7, training 3, epoch 1570: train scaled MSE 0.000200228; val RMSE 0.001228854; lr 1e-05; 306s
network 7, training 3, epoch 1580: train scaled MSE 0.00020032; val RMSE 0.001229001; lr 1e-05; 308s
network 7, training 3, epoch 1590: train scaled MSE 0.000199297; val RMSE 0.001228718; lr 1e-05; 310s
network 7, training 3, epoch 1600: train scaled MSE 0.000202332; val RMSE 0.001228966; lr 1e-05; 312s
network 7, training 3, epoch 1610: train scaled MSE 0.000197992; val RMSE 0.001228544; lr 1e-05; 314s
network 7, training 3, epoch 1620: train scaled MSE 0.000197635; val RMSE 0.001228229; lr 1e-05; 316s
network 7, training 3, epoch 1630: train scaled MSE 0.00019659; val RMSE 0.00122802; lr 1e-05; 317s
network 7, training 3, epoch 1640: train scaled MSE 0.000196045; val RMSE 0.001228723; lr 1e-05; 319s
network 7, training 3, epoch 1650: train scaled MSE 0.000196384; val RMSE 0.00122843; lr 1e-05; 321s
network 7, training 3, epoch 1660: train scaled MSE 0.000194833; val RMSE 0.001228003; lr 1e-05; 323s
network 7, training 3, epoch 1670: train scaled MSE 0.000194413; val RMSE 0.001227766; lr 1e-05; 325s
network 7, training 3, epoch 1680: train scaled MSE 0.000194668; val RMSE 0.001227585; lr 1e-05; 327s
network 7, training 3, epoch 1690: train scaled MSE 0.000194129; val RMSE 0.001227439; lr 1e-05; 329s
network 7, training 3, epoch 1700: train scaled MSE 0.000194822; val RMSE 0.001229196; lr 1e-05; 331s
network 7, training 3, epoch 1710: train scaled MSE 0.00019279; val RMSE 0.001227977; lr 1e-05; 333s
Standard Linear Baseline Validation RMSE: 0.001459323

Network seed 7, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0022,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0022,-0.1526,"[-1.18%, 0.74%]",0.0581,0.0,0.2042
MLP,0.0020,17.4938,"[5.56%, 27.92%]",0.4521,678.3112,0.3205

network 7, training 4, epoch 1: train scaled MSE 0.809242; val RMSE 0.01961301; lr 0.001; 0s
network 7, training 4, epoch 10: train scaled MSE 0.0226853; val RMSE 0.003974233; lr 0.001; 2s
network 7, training 4, epoch 20: train scaled MSE 0.00923203; val RMSE 0.002399274; lr 0.001; 4s
network 7, training 4, epoch 30: train scaled MSE 0.00670322; val RMSE 0.002076855; lr 0.001; 6s
network 7, training 4, epoch 40: train scaled MSE 0.00637626; val RMSE 0.002142246; lr 0.001; 8s
network 7, training 4, epoch 50: train scaled MSE 0.00479959; val RMSE 0.001976565; lr 0.001; 10s
network 7, training 4, epoch 60: train scaled MSE 0.00404139; val RMSE 0.001921624; lr 0.0005; 11s
network 7, training 4, epoch 70: train scaled MSE 0.00340599; val RMSE 0.001880755; lr 0.00025; 13s
network 7, training 4, epoch 80: train scaled MSE 0.00318441; val RMSE 0.001913123; lr 0.00025; 15s
network 7, training 4, epoch 90: train scaled MSE 0.0029162; val RMSE 0.001873245; lr 0.000125; 17s
network 7, training 4, epoch 100: train scaled MSE 0.00278991; val RMSE 0.001866307; lr 0.000125; 19s
network 7, training 4, epoch 110: train scaled MSE 0.00264954; val RMSE 0.001874371; lr 0.000125; 21s
network 7, training 4, epoch 120: train scaled MSE 0.00267126; val RMSE 0.001869703; lr 0.000125; 23s
network 7, training 4, epoch 130: train scaled MSE 0.00237409; val RMSE 0.001854784; lr 6.25e-05; 25s
network 7, training 4, epoch 140: train scaled MSE 0.00232671; val RMSE 0.001857132; lr 6.25e-05; 27s
network 7, training 4, epoch 150: train scaled MSE 0.00222134; val RMSE 0.001848971; lr 6.25e-05; 29s
network 7, training 4, epoch 160: train scaled MSE 0.00210891; val RMSE 0.001851638; lr 6.25e-05; 31s
network 7, training 4, epoch 170: train scaled MSE 0.00237888; val RMSE 0.001869363; lr 6.25e-05; 33s
network 7, training 4, epoch 180: train scaled MSE 0.00196365; val RMSE 0.001841449; lr 6.25e-05; 35s
network 7, training 4, epoch 190: train scaled MSE 0.00190253; val RMSE 0.001840176; lr 6.25e-05; 37s
network 7, training 4, epoch 200: train scaled MSE 0.00191745; val RMSE 0.001841669; lr 6.25e-05; 39s
network 7, training 4, epoch 210: train scaled MSE 0.00178324; val RMSE 0.001835859; lr 6.25e-05; 41s
network 7, training 4, epoch 220: train scaled MSE 0.00174922; val RMSE 0.001835882; lr 6.25e-05; 43s
network 7, training 4, epoch 230: train scaled MSE 0.00175596; val RMSE 0.001858071; lr 6.25e-05; 44s
network 7, training 4, epoch 240: train scaled MSE 0.00159063; val RMSE 0.001839961; lr 3.125e-05; 46s
network 7, training 4, epoch 250: train scaled MSE 0.00155218; val RMSE 0.001836418; lr 1.5625e-05; 48s
network 7, training 4, epoch 260: train scaled MSE 0.00153671; val RMSE 0.001836131; lr 1.5625e-05; 50s
network 7, training 4, epoch 270: train scaled MSE 0.00153252; val RMSE 0.001837991; lr 1.5625e-05; 52s
network 7, training 4, epoch 280: train scaled MSE 0.0015035; val RMSE 0.00183434; lr 1e-05; 54s
network 7, training 4, epoch 290: train scaled MSE 0.00149367; val RMSE 0.001834629; lr 1e-05; 56s
network 7, training 4, epoch 300: train scaled MSE 0.0014825; val RMSE 0.001833424; lr 1e-05; 58s
network 7, training 4, epoch 310: train scaled MSE 0.00147504; val RMSE 0.001832805; lr 1e-05; 60s
network 7, training 4, epoch 320: train scaled MSE 0.00146198; val RMSE 0.00183225; lr 1e-05; 62s
network 7, training 4, epoch 330: train scaled MSE 0.00145339; val RMSE 0.001832473; lr 1e-05; 64s
network 7, training 4, epoch 340: train scaled MSE 0.00144006; val RMSE 0.001830567; lr 1e-05; 66s
network 7, training 4, epoch 350: train scaled MSE 0.00143605; val RMSE 0.001831562; lr 1e-05; 68s
network 7, training 4, epoch 360: train scaled MSE 0.00142202; val RMSE 0.001830792; lr 1e-05; 70s
network 7, training 4, epoch 370: train scaled MSE 0.00141163; val RMSE 0.001829481; lr 1e-05; 71s
network 7, training 4, epoch 380: train scaled MSE 0.0014026; val RMSE 0.00183078; lr 1e-05; 73s
network 7, training 4, epoch 390: train scaled MSE 0.00139212; val RMSE 0.001828572; lr 1e-05; 75s
network 7, training 4, epoch 400: train scaled MSE 0.0013833; val RMSE 0.001828177; lr 1e-05; 77s
network 7, training 4, epoch 410: train scaled MSE 0.00137308; val RMSE 0.001828775; lr 1e-05; 79s
network 7, training 4, epoch 420: train scaled MSE 0.00136598; val RMSE 0.001828299; lr 1e-05; 81s
network 7, training 4, epoch 430: train scaled MSE 0.0013539; val RMSE 0.001828371; lr 1e-05; 83s
network 7, training 4, epoch 440: train scaled MSE 0.00134545; val RMSE 0.001826849; lr 1e-05; 85s
network 7, training 4, epoch 450: train scaled MSE 0.00133427; val RMSE 0.00182693; lr 1e-05; 87s
network 7, training 4, epoch 460: train scaled MSE 0.00132607; val RMSE 0.001826605; lr 1e-05; 89s
network 7, training 4, epoch 470: train scaled MSE 0.00132104; val RMSE 0.001825921; lr 1e-05; 91s
network 7, training 4, epoch 480: train scaled MSE 0.0013094; val RMSE 0.001825775; lr 1e-05; 93s
network 7, training 4, epoch 490: train scaled MSE 0.0013001; val RMSE 0.001825173; lr 1e-05; 95s
network 7, training 4, epoch 500: train scaled MSE 0.00129583; val RMSE 0.001824779; lr 1e-05; 97s
network 7, training 4, epoch 510: train scaled MSE 0.00129197; val RMSE 0.001826098; lr 1e-05; 99s
network 7, training 4, epoch 520: train scaled MSE 0.00127697; val RMSE 0.001824773; lr 1e-05; 101s
network 7, training 4, epoch 530: train scaled MSE 0.00127296; val RMSE 0.001824106; lr 1e-05; 103s
network 7, training 4, epoch 540: train scaled MSE 0.00126231; val RMSE 0.001825096; lr 1e-05; 105s
network 7, training 4, epoch 550: train scaled MSE 0.00126263; val RMSE 0.001823644; lr 1e-05; 107s
network 7, training 4, epoch 560: train scaled MSE 0.00124665; val RMSE 0.001823532; lr 1e-05; 109s
network 7, training 4, epoch 570: train scaled MSE 0.00123798; val RMSE 0.001823537; lr 1e-05; 111s
network 7, training 4, epoch 580: train scaled MSE 0.00123673; val RMSE 0.001823826; lr 1e-05; 113s
network 7, training 4, epoch 590: train scaled MSE 0.00122263; val RMSE 0.00182326; lr 1e-05; 115s
network 7, training 4, epoch 600: train scaled MSE 0.00121441; val RMSE 0.001821365; lr 1e-05; 117s
network 7, training 4, epoch 610: train scaled MSE 0.00120921; val RMSE 0.001821204; lr 1e-05; 118s
network 7, training 4, epoch 620: train scaled MSE 0.00119968; val RMSE 0.001821421; lr 1e-05; 120s
network 7, training 4, epoch 630: train scaled MSE 0.00119641; val RMSE 0.001821538; lr 1e-05; 122s
network 7, training 4, epoch 640: train scaled MSE 0.00118606; val RMSE 0.001821083; lr 1e-05; 124s
network 7, training 4, epoch 650: train scaled MSE 0.00118028; val RMSE 0.001819742; lr 1e-05; 126s
network 7, training 4, epoch 660: train scaled MSE 0.00117855; val RMSE 0.00182108; lr 1e-05; 128s
network 7, training 4, epoch 670: train scaled MSE 0.00116601; val RMSE 0.001820062; lr 1e-05; 130s
network 7, training 4, epoch 680: train scaled MSE 0.00116479; val RMSE 0.001821252; lr 1e-05; 132s
network 7, training 4, epoch 690: train scaled MSE 0.00115487; val RMSE 0.001819867; lr 1e-05; 134s
network 7, training 4, epoch 700: train scaled MSE 0.00114964; val RMSE 0.001819127; lr 1e-05; 136s
network 7, training 4, epoch 710: train scaled MSE 0.00114455; val RMSE 0.001819684; lr 1e-05; 138s
network 7, training 4, epoch 720: train scaled MSE 0.00113606; val RMSE 0.001819834; lr 1e-05; 140s
network 7, training 4, epoch 730: train scaled MSE 0.00113099; val RMSE 0.001819878; lr 1e-05; 142s
network 7, training 4, epoch 740: train scaled MSE 0.00112483; val RMSE 0.00181864; lr 1e-05; 144s
network 7, training 4, epoch 750: train scaled MSE 0.00111853; val RMSE 0.001817915; lr 1e-05; 146s
network 7, training 4, epoch 760: train scaled MSE 0.00111363; val RMSE 0.001817876; lr 1e-05; 148s
network 7, training 4, epoch 770: train scaled MSE 0.00110571; val RMSE 0.001816743; lr 1e-05; 150s
network 7, training 4, epoch 780: train scaled MSE 0.00112449; val RMSE 0.001820248; lr 1e-05; 152s
network 7, training 4, epoch 790: train scaled MSE 0.00109379; val RMSE 0.001817081; lr 1e-05; 153s
network 7, training 4, epoch 800: train scaled MSE 0.00108871; val RMSE 0.001816592; lr 1e-05; 155s
network 7, training 4, epoch 810: train scaled MSE 0.00108126; val RMSE 0.001816674; lr 1e-05; 157s
network 7, training 4, epoch 820: train scaled MSE 0.00107634; val RMSE 0.001815887; lr 1e-05; 159s
network 7, training 4, epoch 830: train scaled MSE 0.00106899; val RMSE 0.001815291; lr 1e-05; 161s
network 7, training 4, epoch 840: train scaled MSE 0.00109584; val RMSE 0.001821481; lr 1e-05; 163s
network 7, training 4, epoch 850: train scaled MSE 0.00107533; val RMSE 0.001818058; lr 1e-05; 164s
network 7, training 4, epoch 860: train scaled MSE 0.00105347; val RMSE 0.001816358; lr 1e-05; 166s
network 7, training 4, epoch 870: train scaled MSE 0.00104984; val RMSE 0.001815794; lr 1e-05; 168s
Standard Linear Baseline Validation RMSE: 0.001684047

Network seed 7, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0018,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0018,-0.4514,"[-1.63%, 0.60%]",0.0694,0.0,0.2235
MLP,0.0017,11.7777,"[-4.19%, 24.95%]",0.4482,545.8916,0.0103

network 7, training 5, epoch 1: train scaled MSE 0.817825; val RMSE 0.01817704; lr 0.001; 0s
network 7, training 5, epoch 10: train scaled MSE 0.0194916; val RMSE 0.004012083; lr 0.001; 2s
network 7, training 5, epoch 20: train scaled MSE 0.00790541; val RMSE 0.00278753; lr 0.001; 4s
network 7, training 5, epoch 30: train scaled MSE 0.00578; val RMSE 0.002353251; lr 0.001; 6s
network 7, training 5, epoch 40: train scaled MSE 0.00962789; val RMSE 0.002615713; lr 0.001; 8s
network 7, training 5, epoch 50: train scaled MSE 0.00340504; val RMSE 0.002185131; lr 0.001; 10s
network 7, training 5, epoch 60: train scaled MSE 0.00507773; val RMSE 0.002213732; lr 0.001; 12s
network 7, training 5, epoch 70: train scaled MSE 0.00206181; val RMSE 0.002086594; lr 0.001; 14s
network 7, training 5, epoch 80: train scaled MSE 0.00184396; val RMSE 0.002142417; lr 0.001; 16s
network 7, training 5, epoch 90: train scaled MSE 0.00244579; val RMSE 0.002119953; lr 0.001; 18s
network 7, training 5, epoch 100: train scaled MSE 0.00308396; val RMSE 0.002154876; lr 0.001; 20s
network 7, training 5, epoch 110: train scaled MSE 0.000894346; val RMSE 0.002035438; lr 0.0005; 22s
network 7, training 5, epoch 120: train scaled MSE 0.000787075; val RMSE 0.002019779; lr 0.0005; 24s
network 7, training 5, epoch 130: train scaled MSE 0.000714529; val RMSE 0.002051196; lr 0.0005; 26s
network 7, training 5, epoch 140: train scaled MSE 0.000633579; val RMSE 0.00201293; lr 0.0005; 28s
network 7, training 5, epoch 150: train scaled MSE 0.000857904; val RMSE 0.002023356; lr 0.0005; 30s
network 7, training 5, epoch 160: train scaled MSE 0.000519246; val RMSE 0.002000654; lr 0.00025; 32s
network 7, training 5, epoch 170: train scaled MSE 0.000487824; val RMSE 0.002014104; lr 0.00025; 34s
network 7, training 5, epoch 180: train scaled MSE 0.000459792; val RMSE 0.001989178; lr 0.00025; 36s
network 7, training 5, epoch 190: train scaled MSE 0.000451606; val RMSE 0.001976986; lr 0.00025; 37s
network 7, training 5, epoch 200: train scaled MSE 0.000414483; val RMSE 0.001972223; lr 0.00025; 39s
network 7, training 5, epoch 210: train scaled MSE 0.00038675; val RMSE 0.001961882; lr 0.00025; 41s
network 7, training 5, epoch 220: train scaled MSE 0.000375752; val RMSE 0.001958646; lr 0.00025; 43s
network 7, training 5, epoch 230: train scaled MSE 0.000581425; val RMSE 0.001955081; lr 0.00025; 45s
network 7, training 5, epoch 240: train scaled MSE 0.00031987; val RMSE 0.001950338; lr 0.00025; 47s
network 7, training 5, epoch 250: train scaled MSE 0.000341121; val RMSE 0.002001425; lr 0.00025; 49s
network 7, training 5, epoch 260: train scaled MSE 0.000293163; val RMSE 0.00193726; lr 0.00025; 51s
network 7, training 5, epoch 270: train scaled MSE 0.000280207; val RMSE 0.001929492; lr 0.00025; 52s
network 7, training 5, epoch 280: train scaled MSE 0.000263287; val RMSE 0.001923217; lr 0.00025; 54s
network 7, training 5, epoch 290: train scaled MSE 0.00026163; val RMSE 0.001923526; lr 0.00025; 56s
network 7, training 5, epoch 300: train scaled MSE 0.000241114; val RMSE 0.001915751; lr 0.000125; 58s
network 7, training 5, epoch 310: train scaled MSE 0.000221674; val RMSE 0.001913506; lr 0.000125; 60s
network 7, training 5, epoch 320: train scaled MSE 0.000219576; val RMSE 0.001908216; lr 0.000125; 62s
network 7, training 5, epoch 330: train scaled MSE 0.000211096; val RMSE 0.001912741; lr 0.000125; 64s
network 7, training 5, epoch 340: train scaled MSE 0.00022339; val RMSE 0.00189968; lr 0.000125; 66s
network 7, training 5, epoch 350: train scaled MSE 0.000200357; val RMSE 0.001906876; lr 0.000125; 68s
network 7, training 5, epoch 360: train scaled MSE 0.000215527; val RMSE 0.001893251; lr 0.000125; 70s
network 7, training 5, epoch 370: train scaled MSE 0.00021712; val RMSE 0.00191387; lr 0.000125; 72s
network 7, training 5, epoch 380: train scaled MSE 0.000201456; val RMSE 0.001889212; lr 0.000125; 74s
network 7, training 5, epoch 390: train scaled MSE 0.000210048; val RMSE 0.001884284; lr 0.000125; 76s
network 7, training 5, epoch 400: train scaled MSE 0.000255627; val RMSE 0.001882128; lr 0.000125; 77s
network 7, training 5, epoch 410: train scaled MSE 0.000175287; val RMSE 0.001878202; lr 0.000125; 79s
network 7, training 5, epoch 420: train scaled MSE 0.000170775; val RMSE 0.001875238; lr 0.000125; 81s
network 7, training 5, epoch 430: train scaled MSE 0.000164881; val RMSE 0.001872189; lr 0.000125; 83s
network 7, training 5, epoch 440: train scaled MSE 0.000158965; val RMSE 0.001870722; lr 0.000125; 85s
network 7, training 5, epoch 450: train scaled MSE 0.00016308; val RMSE 0.001866735; lr 0.000125; 87s
network 7, training 5, epoch 460: train scaled MSE 0.000157108; val RMSE 0.001864202; lr 0.000125; 89s
network 7, training 5, epoch 470: train scaled MSE 0.000153297; val RMSE 0.001860827; lr 0.000125; 91s
network 7, training 5, epoch 480: train scaled MSE 0.000146643; val RMSE 0.001859235; lr 0.000125; 93s
network 7, training 5, epoch 490: train scaled MSE 0.000157144; val RMSE 0.001859073; lr 0.000125; 95s
network 7, training 5, epoch 500: train scaled MSE 0.000156471; val RMSE 0.001857019; lr 0.000125; 97s
network 7, training 5, epoch 510: train scaled MSE 0.000140656; val RMSE 0.001854242; lr 0.000125; 99s
network 7, training 5, epoch 520: train scaled MSE 0.000135284; val RMSE 0.001850688; lr 0.000125; 100s
network 7, training 5, epoch 530: train scaled MSE 0.000218293; val RMSE 0.001853462; lr 0.000125; 102s
network 7, training 5, epoch 540: train scaled MSE 0.000132516; val RMSE 0.001859495; lr 0.000125; 104s
network 7, training 5, epoch 550: train scaled MSE 0.000121061; val RMSE 0.001848567; lr 6.25e-05; 106s
network 7, training 5, epoch 560: train scaled MSE 0.000121276; val RMSE 0.001847074; lr 6.25e-05; 108s
network 7, training 5, epoch 570: train scaled MSE 0.000118856; val RMSE 0.001845675; lr 6.25e-05; 110s
network 7, training 5, epoch 580: train scaled MSE 0.000118414; val RMSE 0.001845407; lr 6.25e-05; 112s
network 7, training 5, epoch 590: train scaled MSE 0.000129449; val RMSE 0.001843017; lr 6.25e-05; 114s
network 7, training 5, epoch 600: train scaled MSE 0.000115178; val RMSE 0.001841904; lr 6.25e-05; 116s
network 7, training 5, epoch 610: train scaled MSE 0.000113154; val RMSE 0.00184158; lr 6.25e-05; 118s
network 7, training 5, epoch 620: train scaled MSE 0.000113328; val RMSE 0.001840938; lr 6.25e-05; 120s
network 7, training 5, epoch 630: train scaled MSE 0.000113054; val RMSE 0.001839108; lr 6.25e-05; 122s
network 7, training 5, epoch 640: train scaled MSE 0.000111675; val RMSE 0.001852984; lr 6.25e-05; 124s
network 7, training 5, epoch 650: train scaled MSE 0.000109435; val RMSE 0.001838077; lr 6.25e-05; 126s
network 7, training 5, epoch 660: train scaled MSE 0.000107831; val RMSE 0.00183627; lr 6.25e-05; 128s
network 7, training 5, epoch 670: train scaled MSE 0.000108383; val RMSE 0.001835551; lr 6.25e-05; 130s
network 7, training 5, epoch 680: train scaled MSE 0.000105615; val RMSE 0.001839793; lr 6.25e-05; 132s
network 7, training 5, epoch 690: train scaled MSE 0.000103871; val RMSE 0.001833801; lr 6.25e-05; 134s
network 7, training 5, epoch 700: train scaled MSE 0.000103175; val RMSE 0.001832697; lr 6.25e-05; 136s
network 7, training 5, epoch 710: train scaled MSE 0.00010264; val RMSE 0.001830875; lr 6.25e-05; 138s
network 7, training 5, epoch 720: train scaled MSE 9.93658e-05; val RMSE 0.001831666; lr 3.125e-05; 140s
network 7, training 5, epoch 730: train scaled MSE 9.78045e-05; val RMSE 0.001829825; lr 3.125e-05; 141s
network 7, training 5, epoch 740: train scaled MSE 9.69568e-05; val RMSE 0.001830257; lr 3.125e-05; 143s
network 7, training 5, epoch 750: train scaled MSE 9.65056e-05; val RMSE 0.001828212; lr 3.125e-05; 145s
network 7, training 5, epoch 760: train scaled MSE 0.000104001; val RMSE 0.001827382; lr 3.125e-05; 147s
network 7, training 5, epoch 770: train scaled MSE 9.54403e-05; val RMSE 0.001829759; lr 3.125e-05; 149s
network 7, training 5, epoch 780: train scaled MSE 0.000120463; val RMSE 0.001827364; lr 3.125e-05; 151s
network 7, training 5, epoch 790: train scaled MSE 9.44338e-05; val RMSE 0.00182624; lr 3.125e-05; 153s
network 7, training 5, epoch 800: train scaled MSE 9.751e-05; val RMSE 0.00182567; lr 3.125e-05; 155s
network 7, training 5, epoch 810: train scaled MSE 0.000105914; val RMSE 0.001825793; lr 3.125e-05; 157s
network 7, training 5, epoch 820: train scaled MSE 9.46916e-05; val RMSE 0.001824157; lr 3.125e-05; 159s
network 7, training 5, epoch 830: train scaled MSE 9.1858e-05; val RMSE 0.001823301; lr 3.125e-05; 161s
network 7, training 5, epoch 840: train scaled MSE 9.00339e-05; val RMSE 0.001822625; lr 1.5625e-05; 162s
network 7, training 5, epoch 850: train scaled MSE 0.000116854; val RMSE 0.001823075; lr 1.5625e-05; 164s
network 7, training 5, epoch 860: train scaled MSE 9.23912e-05; val RMSE 0.001822074; lr 1.5625e-05; 166s
network 7, training 5, epoch 870: train scaled MSE 8.93557e-05; val RMSE 0.001821769; lr 1.5625e-05; 168s
network 7, training 5, epoch 880: train scaled MSE 8.91342e-05; val RMSE 0.001821142; lr 1.5625e-05; 170s
network 7, training 5, epoch 890: train scaled MSE 8.92178e-05; val RMSE 0.001820914; lr 1.5625e-05; 172s
network 7, training 5, epoch 900: train scaled MSE 9.07354e-05; val RMSE 0.001820723; lr 1.5625e-05; 174s
network 7, training 5, epoch 910: train scaled MSE 8.86061e-05; val RMSE 0.001820215; lr 1.5625e-05; 176s
network 7, training 5, epoch 920: train scaled MSE 8.80127e-05; val RMSE 0.001819532; lr 1.5625e-05; 178s
network 7, training 5, epoch 930: train scaled MSE 8.80024e-05; val RMSE 0.001819907; lr 1.5625e-05; 180s
network 7, training 5, epoch 940: train scaled MSE 8.75113e-05; val RMSE 0.001819538; lr 1.5625e-05; 181s
network 7, training 5, epoch 950: train scaled MSE 9.49973e-05; val RMSE 0.001819475; lr 1.5625e-05; 183s
network 7, training 5, epoch 960: train scaled MSE 8.89073e-05; val RMSE 0.001818723; lr 1.5625e-05; 185s
network 7, training 5, epoch 970: train scaled MSE 8.77612e-05; val RMSE 0.001818662; lr 1.5625e-05; 187s
network 7, training 5, epoch 980: train scaled MSE 8.65929e-05; val RMSE 0.001817718; lr 1.5625e-05; 189s
network 7, training 5, epoch 990: train scaled MSE 8.61614e-05; val RMSE 0.001817698; lr 1.5625e-05; 191s
network 7, training 5, epoch 1000: train scaled MSE 8.79495e-05; val RMSE 0.001818004; lr 1.5625e-05; 193s
network 7, training 5, epoch 1010: train scaled MSE 8.53262e-05; val RMSE 0.001817301; lr 1e-05; 195s
network 7, training 5, epoch 1020: train scaled MSE 8.51641e-05; val RMSE 0.001817239; lr 1e-05; 197s
network 7, training 5, epoch 1030: train scaled MSE 8.49793e-05; val RMSE 0.001816768; lr 1e-05; 199s
network 7, training 5, epoch 1040: train scaled MSE 8.47446e-05; val RMSE 0.001816402; lr 1e-05; 201s
network 7, training 5, epoch 1050: train scaled MSE 8.56209e-05; val RMSE 0.001816724; lr 1e-05; 202s
network 7, training 5, epoch 1060: train scaled MSE 8.45036e-05; val RMSE 0.001816016; lr 1e-05; 204s
network 7, training 5, epoch 1070: train scaled MSE 8.81393e-05; val RMSE 0.001816215; lr 1e-05; 206s
network 7, training 5, epoch 1080: train scaled MSE 8.55996e-05; val RMSE 0.00181578; lr 1e-05; 208s
network 7, training 5, epoch 1090: train scaled MSE 8.42655e-05; val RMSE 0.001815735; lr 1e-05; 210s
network 7, training 5, epoch 1100: train scaled MSE 8.37554e-05; val RMSE 0.001815188; lr 1e-05; 212s
network 7, training 5, epoch 1110: train scaled MSE 8.38844e-05; val RMSE 0.001815309; lr 1e-05; 214s
network 7, training 5, epoch 1120: train scaled MSE 8.36061e-05; val RMSE 0.001814945; lr 1e-05; 216s
network 7, training 5, epoch 1130: train scaled MSE 8.42727e-05; val RMSE 0.001815394; lr 1e-05; 218s
network 7, training 5, epoch 1140: train scaled MSE 8.31705e-05; val RMSE 0.001815094; lr 1e-05; 220s
network 7, training 5, epoch 1150: train scaled MSE 8.53744e-05; val RMSE 0.001814951; lr 1e-05; 222s
network 7, training 5, epoch 1160: train scaled MSE 8.27777e-05; val RMSE 0.001814563; lr 1e-05; 223s
network 7, training 5, epoch 1170: train scaled MSE 8.27919e-05; val RMSE 0.001814124; lr 1e-05; 225s
network 7, training 5, epoch 1180: train scaled MSE 8.25677e-05; val RMSE 0.001814477; lr 1e-05; 227s
network 7, training 5, epoch 1190: train scaled MSE 8.26662e-05; val RMSE 0.001814106; lr 1e-05; 229s
network 7, training 5, epoch 1200: train scaled MSE 8.24809e-05; val RMSE 0.001814065; lr 1e-05; 231s
network 7, training 5, epoch 1210: train scaled MSE 8.33176e-05; val RMSE 0.001814153; lr 1e-05; 233s
network 7, training 5, epoch 1220: train scaled MSE 8.23304e-05; val RMSE 0.001814028; lr 1e-05; 235s
network 7, training 5, epoch 1230: train scaled MSE 8.27668e-05; val RMSE 0.001813748; lr 1e-05; 237s
network 7, training 5, epoch 1240: train scaled MSE 8.2136e-05; val RMSE 0.001813448; lr 1e-05; 239s
network 7, training 5, epoch 1250: train scaled MSE 9.15041e-05; val RMSE 0.001814614; lr 1e-05; 240s
network 7, training 5, epoch 1260: train scaled MSE 8.15943e-05; val RMSE 0.001813097; lr 1e-05; 242s
network 7, training 5, epoch 1270: train scaled MSE 8.12712e-05; val RMSE 0.001813089; lr 1e-05; 244s
network 7, training 5, epoch 1280: train scaled MSE 8.25823e-05; val RMSE 0.001812531; lr 1e-05; 246s
network 7, training 5, epoch 1290: train scaled MSE 8.22212e-05; val RMSE 0.001812721; lr 1e-05; 248s
network 7, training 5, epoch 1300: train scaled MSE 8.12029e-05; val RMSE 0.00181192; lr 1e-05; 250s
network 7, training 5, epoch 1310: train scaled MSE 8.0678e-05; val RMSE 0.001811765; lr 1e-05; 252s
network 7, training 5, epoch 1320: train scaled MSE 8.05464e-05; val RMSE 0.001812197; lr 1e-05; 254s
network 7, training 5, epoch 1330: train scaled MSE 8.08075e-05; val RMSE 0.001811559; lr 1e-05; 256s
network 7, training 5, epoch 1340: train scaled MSE 8.02912e-05; val RMSE 0.001811237; lr 1e-05; 258s
network 7, training 5, epoch 1350: train scaled MSE 8.16635e-05; val RMSE 0.001811367; lr 1e-05; 259s
network 7, training 5, epoch 1360: train scaled MSE 8.00535e-05; val RMSE 0.001811398; lr 1e-05; 261s
network 7, training 5, epoch 1370: train scaled MSE 8.02993e-05; val RMSE 0.001811169; lr 1e-05; 263s
network 7, training 5, epoch 1380: train scaled MSE 8.14972e-05; val RMSE 0.001811552; lr 1e-05; 265s
network 7, training 5, epoch 1390: train scaled MSE 8.07166e-05; val RMSE 0.001811282; lr 1e-05; 267s
network 7, training 5, epoch 1400: train scaled MSE 8.19127e-05; val RMSE 0.001810709; lr 1e-05; 269s
network 7, training 5, epoch 1410: train scaled MSE 7.92601e-05; val RMSE 0.001810996; lr 1e-05; 271s
network 7, training 5, epoch 1420: train scaled MSE 8.17788e-05; val RMSE 0.001810738; lr 1e-05; 273s
network 7, training 5, epoch 1430: train scaled MSE 8.13106e-05; val RMSE 0.001810515; lr 1e-05; 275s
network 7, training 5, epoch 1440: train scaled MSE 7.9702e-05; val RMSE 0.001810057; lr 1e-05; 277s
network 7, training 5, epoch 1450: train scaled MSE 7.98021e-05; val RMSE 0.001810337; lr 1e-05; 279s
network 7, training 5, epoch 1460: train scaled MSE 7.89848e-05; val RMSE 0.001809927; lr 1e-05; 280s
network 7, training 5, epoch 1470: train scaled MSE 7.85852e-05; val RMSE 0.001809692; lr 1e-05; 282s
network 7, training 5, epoch 1480: train scaled MSE 7.85326e-05; val RMSE 0.001809653; lr 1e-05; 284s
network 7, training 5, epoch 1490: train scaled MSE 7.89543e-05; val RMSE 0.001809229; lr 1e-05; 286s
network 7, training 5, epoch 1500: train scaled MSE 7.87722e-05; val RMSE 0.001809347; lr 1e-05; 289s
network 7, training 5, epoch 1510: train scaled MSE 7.8345e-05; val RMSE 0.001808967; lr 1e-05; 291s
network 7, training 5, epoch 1520: train scaled MSE 7.80124e-05; val RMSE 0.001808631; lr 1e-05; 293s
network 7, training 5, epoch 1530: train scaled MSE 7.80445e-05; val RMSE 0.001808724; lr 1e-05; 295s
network 7, training 5, epoch 1540: train scaled MSE 7.78422e-05; val RMSE 0.001808815; lr 1e-05; 297s
network 7, training 5, epoch 1550: train scaled MSE 7.75433e-05; val RMSE 0.001808557; lr 1e-05; 299s
network 7, training 5, epoch 1560: train scaled MSE 7.74389e-05; val RMSE 0.001808169; lr 1e-05; 301s
network 7, training 5, epoch 1570: train scaled MSE 7.72891e-05; val RMSE 0.001808256; lr 1e-05; 303s
network 7, training 5, epoch 1580: train scaled MSE 7.74651e-05; val RMSE 0.001808171; lr 1e-05; 305s
network 7, training 5, epoch 1590: train scaled MSE 7.69131e-05; val RMSE 0.001807949; lr 1e-05; 307s
network 7, training 5, epoch 1600: train scaled MSE 7.76509e-05; val RMSE 0.00180771; lr 1e-05; 309s
network 7, training 5, epoch 1610: train scaled MSE 7.66837e-05; val RMSE 0.001807676; lr 1e-05; 311s
network 7, training 5, epoch 1620: train scaled MSE 7.65143e-05; val RMSE 0.001807318; lr 1e-05; 313s
network 7, training 5, epoch 1630: train scaled MSE 7.6553e-05; val RMSE 0.001807178; lr 1e-05; 315s
network 7, training 5, epoch 1640: train scaled MSE 7.62776e-05; val RMSE 0.001807007; lr 1e-05; 317s
network 7, training 5, epoch 1650: train scaled MSE 7.62861e-05; val RMSE 0.001806976; lr 1e-05; 318s
network 7, training 5, epoch 1660: train scaled MSE 7.60123e-05; val RMSE 0.001806864; lr 1e-05; 320s
network 7, training 5, epoch 1670: train scaled MSE 7.59494e-05; val RMSE 0.001806549; lr 1e-05; 322s
network 7, training 5, epoch 1680: train scaled MSE 7.58438e-05; val RMSE 0.001806592; lr 1e-05; 324s
network 7, training 5, epoch 1690: train scaled MSE 7.56364e-05; val RMSE 0.001806371; lr 1e-05; 326s
network 7, training 5, epoch 1700: train scaled MSE 7.55931e-05; val RMSE 0.001806135; lr 1e-05; 328s
network 7, training 5, epoch 1710: train scaled MSE 7.55358e-05; val RMSE 0.001805988; lr 1e-05; 330s
network 7, training 5, epoch 1720: train scaled MSE 7.53756e-05; val RMSE 0.001805664; lr 1e-05; 332s
network 7, training 5, epoch 1730: train scaled MSE 7.55123e-05; val RMSE 0.001805621; lr 1e-05; 334s
network 7, training 5, epoch 1740: train scaled MSE 7.48451e-05; val RMSE 0.001805176; lr 1e-05; 336s
network 7, training 5, epoch 1750: train scaled MSE 7.62121e-05; val RMSE 0.001805518; lr 1e-05; 338s
network 7, training 5, epoch 1760: train scaled MSE 7.46057e-05; val RMSE 0.001805228; lr 1e-05; 340s
network 7, training 5, epoch 1770: train scaled MSE 8.02621e-05; val RMSE 0.001805351; lr 1e-05; 342s
network 7, training 5, epoch 1780: train scaled MSE 7.56527e-05; val RMSE 0.001805557; lr 1e-05; 344s
network 7, training 5, epoch 1790: train scaled MSE 7.45546e-05; val RMSE 0.001804954; lr 1e-05; 346s
network 7, training 5, epoch 1800: train scaled MSE 7.39874e-05; val RMSE 0.001804932; lr 1e-05; 348s
network 7, training 5, epoch 1810: train scaled MSE 8.60483e-05; val RMSE 0.001806063; lr 1e-05; 350s
network 7, training 5, epoch 1820: train scaled MSE 7.3832e-05; val RMSE 0.001804693; lr 1e-05; 352s
network 7, training 5, epoch 1830: train scaled MSE 7.37976e-05; val RMSE 0.00180469; lr 1e-05; 353s
network 7, training 5, epoch 1840: train scaled MSE 7.45119e-05; val RMSE 0.001804694; lr 1e-05; 355s
network 7, training 5, epoch 1850: train scaled MSE 7.58521e-05; val RMSE 0.00180432; lr 1e-05; 357s
network 7, training 5, epoch 1860: train scaled MSE 7.50316e-05; val RMSE 0.001804466; lr 1e-05; 359s
network 7, training 5, epoch 1870: train scaled MSE 7.40795e-05; val RMSE 0.001803993; lr 1e-05; 361s
network 7, training 5, epoch 1880: train scaled MSE 7.35412e-05; val RMSE 0.00180383; lr 1e-05; 363s
network 7, training 5, epoch 1890: train scaled MSE 7.35587e-05; val RMSE 0.001803744; lr 1e-05; 365s
network 7, training 5, epoch 1900: train scaled MSE 7.36892e-05; val RMSE 0.001803697; lr 1e-05; 367s
network 7, training 5, epoch 1910: train scaled MSE 7.38749e-05; val RMSE 0.001803863; lr 1e-05; 369s
network 7, training 5, epoch 1920: train scaled MSE 7.31816e-05; val RMSE 0.001803795; lr 1e-05; 371s
network 7, training 5, epoch 1930: train scaled MSE 7.55461e-05; val RMSE 0.001803842; lr 1e-05; 373s
network 7, training 5, epoch 1940: train scaled MSE 7.2617e-05; val RMSE 0.001803535; lr 1e-05; 375s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0019,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0019,-1.1467,"[-2.40%, 0.00%]",0.0509,0.0,0.1854
MLP,0.0016,24.2491,"[12.57%, 34.03%]",0.5243,929.9534,0.0320

network 7, training 6, epoch 1: train scaled MSE 0.822256; val RMSE 0.01909814; lr 0.001; 0s
network 7, training 6, epoch 10: train scaled MSE 0.0211585; val RMSE 0.003794605; lr 0.001; 2s
network 7, training 6, epoch 20: train scaled MSE 0.00861689; val RMSE 0.002193287; lr 0.001; 4s
network 7, training 6, epoch 30: train scaled MSE 0.00715375; val RMSE 0.001935787; lr 0.001; 6s
network 7, training 6, epoch 40: train scaled MSE 0.00586724; val RMSE 0.001808018; lr 0.001; 8s
network 7, training 6, epoch 50: train scaled MSE 0.00489653; val RMSE 0.002191341; lr 0.001; 10s
network 7, training 6, epoch 60: train scaled MSE 0.00450165; val RMSE 0.001712636; lr 0.001; 12s
network 7, training 6, epoch 70: train scaled MSE 0.00306037; val RMSE 0.001709648; lr 0.001; 14s
network 7, training 6, epoch 80: train scaled MSE 0.00212659; val RMSE 0.001569467; lr 0.001; 16s
network 7, training 6, epoch 90: train scaled MSE 0.00170003; val RMSE 0.001555959; lr 0.001; 18s
network 7, training 6, epoch 100: train scaled MSE 0.00164349; val RMSE 0.001575849; lr 0.001; 20s
network 7, training 6, epoch 110: train scaled MSE 0.00130097; val RMSE 0.001519209; lr 0.001; 22s
network 7, training 6, epoch 120: train scaled MSE 0.00130811; val RMSE 0.001519162; lr 0.001; 24s
network 7, training 6, epoch 130: train scaled MSE 0.00079825; val RMSE 0.00146156; lr 0.0005; 26s
network 7, training 6, epoch 140: train scaled MSE 0.000730356; val RMSE 0.001449772; lr 0.0005; 28s
network 7, training 6, epoch 150: train scaled MSE 0.00139767; val RMSE 0.001665183; lr 0.0005; 30s
network 7, training 6, epoch 160: train scaled MSE 0.000629922; val RMSE 0.001779548; lr 0.0005; 32s
network 7, training 6, epoch 170: train scaled MSE 0.000535872; val RMSE 0.001436883; lr 0.0005; 34s
network 7, training 6, epoch 180: train scaled MSE 0.000455491; val RMSE 0.001416546; lr 0.00025; 36s
network 7, training 6, epoch 190: train scaled MSE 0.00044239; val RMSE 0.00141643; lr 0.00025; 38s
network 7, training 6, epoch 200: train scaled MSE 0.000415538; val RMSE 0.001413739; lr 0.00025; 40s
network 7, training 6, epoch 210: train scaled MSE 0.000388464; val RMSE 0.001404537; lr 0.00025; 42s
network 7, training 6, epoch 220: train scaled MSE 0.000826823; val RMSE 0.001442846; lr 0.00025; 44s
network 7, training 6, epoch 230: train scaled MSE 0.000343168; val RMSE 0.001392568; lr 0.00025; 46s
network 7, training 6, epoch 240: train scaled MSE 0.000329655; val RMSE 0.001392363; lr 0.00025; 48s
network 7, training 6, epoch 250: train scaled MSE 0.000399656; val RMSE 0.001392108; lr 0.00025; 50s
network 7, training 6, epoch 260: train scaled MSE 0.000358328; val RMSE 0.00139206; lr 0.00025; 51s
network 7, training 6, epoch 270: train scaled MSE 0.000342772; val RMSE 0.001385933; lr 0.00025; 53s
network 7, training 6, epoch 280: train scaled MSE 0.000268802; val RMSE 0.001383186; lr 0.00025; 55s
network 7, training 6, epoch 290: train scaled MSE 0.000265914; val RMSE 0.001379028; lr 0.00025; 57s
network 7, training 6, epoch 300: train scaled MSE 0.000246851; val RMSE 0.001377337; lr 0.00025; 59s
network 7, training 6, epoch 310: train scaled MSE 0.000586538; val RMSE 0.001409035; lr 0.000125; 61s
network 7, training 6, epoch 320: train scaled MSE 0.000216235; val RMSE 0.001368897; lr 0.000125; 63s
network 7, training 6, epoch 330: train scaled MSE 0.000208254; val RMSE 0.001367241; lr 0.000125; 65s
network 7, training 6, epoch 340: train scaled MSE 0.000205492; val RMSE 0.001366485; lr 0.000125; 67s
network 7, training 6, epoch 350: train scaled MSE 0.00019859; val RMSE 0.001365856; lr 0.000125; 69s
network 7, training 6, epoch 360: train scaled MSE 0.000195729; val RMSE 0.001379992; lr 0.000125; 71s
network 7, training 6, epoch 370: train scaled MSE 0.000184485; val RMSE 0.001364322; lr 6.25e-05; 73s
network 7, training 6, epoch 380: train scaled MSE 0.000245962; val RMSE 0.001369304; lr 6.25e-05; 75s
network 7, training 6, epoch 390: train scaled MSE 0.000179127; val RMSE 0.001361847; lr 6.25e-05; 77s
network 7, training 6, epoch 400: train scaled MSE 0.000177365; val RMSE 0.001360812; lr 6.25e-05; 79s
network 7, training 6, epoch 410: train scaled MSE 0.000174293; val RMSE 0.001359723; lr 6.25e-05; 81s
network 7, training 6, epoch 420: train scaled MSE 0.000226616; val RMSE 0.001361386; lr 6.25e-05; 83s
network 7, training 6, epoch 430: train scaled MSE 0.000168715; val RMSE 0.001357265; lr 6.25e-05; 85s
network 7, training 6, epoch 440: train scaled MSE 0.000174303; val RMSE 0.001357321; lr 6.25e-05; 87s
network 7, training 6, epoch 450: train scaled MSE 0.000163277; val RMSE 0.001356765; lr 6.25e-05; 89s
network 7, training 6, epoch 460: train scaled MSE 0.000161751; val RMSE 0.001354244; lr 6.25e-05; 91s
network 7, training 6, epoch 470: train scaled MSE 0.000159205; val RMSE 0.001354013; lr 6.25e-05; 93s
network 7, training 6, epoch 480: train scaled MSE 0.000159243; val RMSE 0.001353176; lr 6.25e-05; 95s
network 7, training 6, epoch 490: train scaled MSE 0.000155422; val RMSE 0.001352482; lr 6.25e-05; 97s
network 7, training 6, epoch 500: train scaled MSE 0.000153302; val RMSE 0.001351727; lr 6.25e-05; 99s
network 7, training 6, epoch 510: train scaled MSE 0.000159891; val RMSE 0.001358866; lr 6.25e-05; 101s
network 7, training 6, epoch 520: train scaled MSE 0.000277179; val RMSE 0.001355691; lr 6.25e-05; 103s
network 7, training 6, epoch 530: train scaled MSE 0.000146204; val RMSE 0.001349501; lr 6.25e-05; 105s
network 7, training 6, epoch 540: train scaled MSE 0.00014382; val RMSE 0.001349048; lr 6.25e-05; 107s
network 7, training 6, epoch 550: train scaled MSE 0.000147062; val RMSE 0.001349623; lr 6.25e-05; 109s
network 7, training 6, epoch 560: train scaled MSE 0.000140038; val RMSE 0.001347931; lr 6.25e-05; 111s
network 7, training 6, epoch 570: train scaled MSE 0.000137028; val RMSE 0.001347078; lr 6.25e-05; 113s
network 7, training 6, epoch 580: train scaled MSE 0.000135643; val RMSE 0.001346448; lr 6.25e-05; 115s
network 7, training 6, epoch 590: train scaled MSE 0.000139184; val RMSE 0.001347134; lr 6.25e-05; 117s
network 7, training 6, epoch 600: train scaled MSE 0.000132716; val RMSE 0.001346304; lr 6.25e-05; 119s
network 7, training 6, epoch 610: train scaled MSE 0.000169847; val RMSE 0.001348986; lr 6.25e-05; 121s
network 7, training 6, epoch 620: train scaled MSE 0.000127086; val RMSE 0.001344939; lr 3.125e-05; 123s
network 7, training 6, epoch 630: train scaled MSE 0.000134717; val RMSE 0.001344805; lr 3.125e-05; 125s
network 7, training 6, epoch 640: train scaled MSE 0.0001257; val RMSE 0.00134429; lr 3.125e-05; 127s
network 7, training 6, epoch 650: train scaled MSE 0.000125673; val RMSE 0.001345535; lr 3.125e-05; 128s
network 7, training 6, epoch 660: train scaled MSE 0.00012669; val RMSE 0.001343949; lr 3.125e-05; 130s
network 7, training 6, epoch 670: train scaled MSE 0.000123848; val RMSE 0.00134338; lr 3.125e-05; 132s
network 7, training 6, epoch 680: train scaled MSE 0.000123091; val RMSE 0.001343071; lr 3.125e-05; 134s
network 7, training 6, epoch 690: train scaled MSE 0.000120473; val RMSE 0.001342871; lr 1.5625e-05; 136s
network 7, training 6, epoch 700: train scaled MSE 0.000120601; val RMSE 0.001342959; lr 1.5625e-05; 138s
network 7, training 6, epoch 710: train scaled MSE 0.000119661; val RMSE 0.001342698; lr 1e-05; 140s
network 7, training 6, epoch 720: train scaled MSE 0.00012121; val RMSE 0.001342659; lr 1e-05; 142s
network 7, training 6, epoch 730: train scaled MSE 0.000120656; val RMSE 0.001342351; lr 1e-05; 144s
network 7, training 6, epoch 740: train scaled MSE 0.000118485; val RMSE 0.001342605; lr 1e-05; 146s
network 7, training 6, epoch 750: train scaled MSE 0.000118347; val RMSE 0.001342468; lr 1e-05; 148s
network 7, training 6, epoch 760: train scaled MSE 0.000118517; val RMSE 0.00134211; lr 1e-05; 150s
network 7, training 6, epoch 770: train scaled MSE 0.000117727; val RMSE 0.00134191; lr 1e-05; 152s
network 7, training 6, epoch 780: train scaled MSE 0.000118989; val RMSE 0.001341851; lr 1e-05; 154s
network 7, training 6, epoch 790: train scaled MSE 0.000117139; val RMSE 0.001341922; lr 1e-05; 156s
network 7, training 6, epoch 800: train scaled MSE 0.000116981; val RMSE 0.0013415; lr 1e-05; 157s
network 7, training 6, epoch 810: train scaled MSE 0.000116612; val RMSE 0.001341615; lr 1e-05; 159s
network 7, training 6, epoch 820: train scaled MSE 0.000116389; val RMSE 0.001341385; lr 1e-05; 161s
network 7, training 6, epoch 830: train scaled MSE 0.000116299; val RMSE 0.001341239; lr 1e-05; 163s
network 7, training 6, epoch 840: train scaled MSE 0.000115943; val RMSE 0.00134125; lr 1e-05; 165s
network 7, training 6, epoch 850: train scaled MSE 0.000116012; val RMSE 0.001341339; lr 1e-05; 167s
network 7, training 6, epoch 860: train scaled MSE 0.000115494; val RMSE 0.001340999; lr 1e-05; 169s
network 7, training 6, epoch 870: train scaled MSE 0.000115088; val RMSE 0.001340925; lr 1e-05; 171s
network 7, training 6, epoch 880: train scaled MSE 0.000119512; val RMSE 0.001341343; lr 1e-05; 173s
network 7, training 6, epoch 890: train scaled MSE 0.000115206; val RMSE 0.001340798; lr 1e-05; 175s
network 7, training 6, epoch 900: train scaled MSE 0.000114251; val RMSE 0.001340702; lr 1e-05; 177s
network 7, training 6, epoch 910: train scaled MSE 0.000114321; val RMSE 0.001340586; lr 1e-05; 179s
network 7, training 6, epoch 920: train scaled MSE 0.000113671; val RMSE 0.001340749; lr 1e-05; 181s
network 7, training 6, epoch 930: train scaled MSE 0.000113357; val RMSE 0.001340615; lr 1e-05; 183s
network 7, training 6, epoch 940: train scaled MSE 0.000113461; val RMSE 0.001340349; lr 1e-05; 185s
network 7, training 6, epoch 950: train scaled MSE 0.00011745; val RMSE 0.001340258; lr 1e-05; 187s
network 7, training 6, epoch 960: train scaled MSE 0.000114489; val RMSE 0.001339993; lr 1e-05; 189s
network 7, training 6, epoch 970: train scaled MSE 0.000112762; val RMSE 0.001340133; lr 1e-05; 191s
network 7, training 6, epoch 980: train scaled MSE 0.000112117; val RMSE 0.001339751; lr 1e-05; 193s
network 7, training 6, epoch 990: train scaled MSE 0.000112029; val RMSE 0.001339782; lr 1e-05; 195s
network 7, training 6, epoch 1000: train scaled MSE 0.000121735; val RMSE 0.001340268; lr 1e-05; 197s
network 7, training 6, epoch 1010: train scaled MSE 0.00011567; val RMSE 0.001340017; lr 1e-05; 199s
network 7, training 6, epoch 1020: train scaled MSE 0.000111638; val RMSE 0.001340468; lr 1e-05; 201s
network 7, training 6, epoch 1030: train scaled MSE 0.000111766; val RMSE 0.001339608; lr 1e-05; 203s
network 7, training 6, epoch 1040: train scaled MSE 0.000110727; val RMSE 0.001339317; lr 1e-05; 205s
network 7, training 6, epoch 1050: train scaled MSE 0.000110654; val RMSE 0.00133965; lr 1e-05; 207s
network 7, training 6, epoch 1060: train scaled MSE 0.000110449; val RMSE 0.001339064; lr 1e-05; 209s
network 7, training 6, epoch 1070: train scaled MSE 0.000110161; val RMSE 0.00133925; lr 1e-05; 211s
network 7, training 6, epoch 1080: train scaled MSE 0.000110042; val RMSE 0.001339102; lr 1e-05; 213s
network 7, training 6, epoch 1090: train scaled MSE 0.000111075; val RMSE 0.001339145; lr 1e-05; 215s
network 7, training 6, epoch 1100: train scaled MSE 0.000110569; val RMSE 0.001339376; lr 1e-05; 217s
network 7, training 6, epoch 1110: train scaled MSE 0.000109189; val RMSE 0.001339013; lr 1e-05; 219s
network 7, training 6, epoch 1120: train scaled MSE 0.000108998; val RMSE 0.001338873; lr 1e-05; 221s
network 7, training 6, epoch 1130: train scaled MSE 0.000109897; val RMSE 0.001338632; lr 1e-05; 222s
network 7, training 6, epoch 1140: train scaled MSE 0.000108738; val RMSE 0.00133845; lr 1e-05; 224s
network 7, training 6, epoch 1150: train scaled MSE 0.000108626; val RMSE 0.001338465; lr 1e-05; 226s
network 7, training 6, epoch 1160: train scaled MSE 0.000108099; val RMSE 0.00133866; lr 1e-05; 228s
network 7, training 6, epoch 1170: train scaled MSE 0.000111197; val RMSE 0.001338527; lr 1e-05; 230s
network 7, training 6, epoch 1180: train scaled MSE 0.00010755; val RMSE 0.001338248; lr 1e-05; 232s
network 7, training 6, epoch 1190: train scaled MSE 0.000108821; val RMSE 0.001338405; lr 1e-05; 234s
network 7, training 6, epoch 1200: train scaled MSE 0.000107117; val RMSE 0.001337969; lr 1e-05; 236s
network 7, training 6, epoch 1210: train scaled MSE 0.000106948; val RMSE 0.001338426; lr 1e-05; 238s
network 7, training 6, epoch 1220: train scaled MSE 0.000106682; val RMSE 0.001337896; lr 1e-05; 240s
network 7, training 6, epoch 1230: train scaled MSE 0.000106592; val RMSE 0.001338208; lr 1e-05; 242s
network 7, training 6, epoch 1240: train scaled MSE 0.000106213; val RMSE 0.001337565; lr 1e-05; 244s
network 7, training 6, epoch 1250: train scaled MSE 0.000106262; val RMSE 0.001338114; lr 1e-05; 246s
network 7, training 6, epoch 1260: train scaled MSE 0.000105758; val RMSE 0.001337587; lr 1e-05; 248s
network 7, training 6, epoch 1270: train scaled MSE 0.000105921; val RMSE 0.001337513; lr 1e-05; 250s
network 7, training 6, epoch 1280: train scaled MSE 0.000105593; val RMSE 0.00133743; lr 1e-05; 252s
network 7, training 6, epoch 1290: train scaled MSE 0.000105814; val RMSE 0.001337363; lr 1e-05; 254s
network 7, training 6, epoch 1300: train scaled MSE 0.000105014; val RMSE 0.00133752; lr 1e-05; 256s
network 7, training 6, epoch 1310: train scaled MSE 0.000105043; val RMSE 0.001337194; lr 1e-05; 258s
network 7, training 6, epoch 1320: train scaled MSE 0.000104735; val RMSE 0.001336989; lr 1e-05; 260s
network 7, training 6, epoch 1330: train scaled MSE 0.000110061; val RMSE 0.001337885; lr 1e-05; 262s
network 7, training 6, epoch 1340: train scaled MSE 0.000106843; val RMSE 0.001337167; lr 1e-05; 264s
network 7, training 6, epoch 1350: train scaled MSE 0.000104601; val RMSE 0.001336837; lr 1e-05; 266s
network 7, training 6, epoch 1360: train scaled MSE 0.000103491; val RMSE 0.001336804; lr 1e-05; 268s
network 7, training 6, epoch 1370: train scaled MSE 0.000109399; val RMSE 0.001337572; lr 1e-05; 270s
network 7, training 6, epoch 1380: train scaled MSE 0.000103269; val RMSE 0.001336954; lr 1e-05; 272s
network 7, training 6, epoch 1390: train scaled MSE 0.000103517; val RMSE 0.001336615; lr 1e-05; 274s
network 7, training 6, epoch 1400: train scaled MSE 0.000102822; val RMSE 0.001336295; lr 1e-05; 276s
network 7, training 6, epoch 1410: train scaled MSE 0.000107482; val RMSE 0.001336799; lr 1e-05; 278s
network 7, training 6, epoch 1420: train scaled MSE 0.000102851; val RMSE 0.00133644; lr 1e-05; 280s
network 7, training 6, epoch 1430: train scaled MSE 0.000102535; val RMSE 0.001336383; lr 1e-05; 282s
network 7, training 6, epoch 1440: train scaled MSE 0.000108526; val RMSE 0.001336859; lr 1e-05; 284s
network 7, training 6, epoch 1450: train scaled MSE 0.000102853; val RMSE 0.001336194; lr 1e-05; 286s
network 7, training 6, epoch 1460: train scaled MSE 0.000101492; val RMSE 0.001336017; lr 1e-05; 288s
network 7, training 6, epoch 1470: train scaled MSE 0.000101443; val RMSE 0.0013359; lr 1e-05; 290s
network 7, training 6, epoch 1480: train scaled MSE 0.00010143; val RMSE 0.001336068; lr 1e-05; 292s
network 7, training 6, epoch 1490: train scaled MSE 0.000101351; val RMSE 0.001335843; lr 1e-05; 294s
network 7, training 6, epoch 1500: train scaled MSE 0.000105366; val RMSE 0.001335999; lr 1e-05; 296s
network 7, training 6, epoch 1510: train scaled MSE 0.000108165; val RMSE 0.001336225; lr 1e-05; 298s
network 7, training 6, epoch 1520: train scaled MSE 0.000101519; val RMSE 0.00133583; lr 1e-05; 300s
network 7, training 6, epoch 1530: train scaled MSE 0.000100163; val RMSE 0.001335551; lr 1e-05; 302s
network 7, training 6, epoch 1540: train scaled MSE 9.99766e-05; val RMSE 0.001335505; lr 1e-05; 304s
network 7, training 6, epoch 1550: train scaled MSE 9.99813e-05; val RMSE 0.001335353; lr 1e-05; 306s
network 7, training 6, epoch 1560: train scaled MSE 9.96965e-05; val RMSE 0.001335122; lr 1e-05; 308s
network 7, training 6, epoch 1570: train scaled MSE 9.97852e-05; val RMSE 0.001335272; lr 1e-05; 310s
network 7, training 6, epoch 1580: train scaled MSE 9.93102e-05; val RMSE 0.001335606; lr 1e-05; 312s
network 7, training 6, epoch 1590: train scaled MSE 9.9126e-05; val RMSE 0.001334913; lr 1e-05; 314s
network 7, training 6, epoch 1600: train scaled MSE 9.89528e-05; val RMSE 0.001335075; lr 1e-05; 316s
network 7, training 6, epoch 1610: train scaled MSE 9.87278e-05; val RMSE 0.001335528; lr 1e-05; 318s
network 7, training 6, epoch 1620: train scaled MSE 9.89667e-05; val RMSE 0.001334955; lr 1e-05; 319s
network 7, training 6, epoch 1630: train scaled MSE 0.000103744; val RMSE 0.001335621; lr 1e-05; 321s
network 7, training 6, epoch 1640: train scaled MSE 9.83357e-05; val RMSE 0.001334759; lr 1e-05; 323s
network 7, training 6, epoch 1650: train scaled MSE 9.79327e-05; val RMSE 0.00133465; lr 1e-05; 325s
network 7, training 6, epoch 1660: train scaled MSE 9.78917e-05; val RMSE 0.001334573; lr 1e-05; 327s
network 7, training 6, epoch 1670: train scaled MSE 9.77299e-05; val RMSE 0.001334419; lr 1e-05; 329s
network 7, training 6, epoch 1680: train scaled MSE 9.7545e-05; val RMSE 0.001334569; lr 1e-05; 331s
network 7, training 6, epoch 1690: train scaled MSE 9.74353e-05; val RMSE 0.00133454; lr 1e-05; 333s
network 7, training 6, epoch 1700: train scaled MSE 9.71352e-05; val RMSE 0.001334363; lr 1e-05; 335s
network 7, training 6, epoch 1710: train scaled MSE 9.69576e-05; val RMSE 0.001334355; lr 1e-05; 336s
network 7, training 6, epoch 1720: train scaled MSE 9.87831e-05; val RMSE 0.001334448; lr 1e-05; 338s
network 7, training 6, epoch 1730: train scaled MSE 9.63987e-05; val RMSE 0.001334685; lr 1e-05; 340s
network 7, training 6, epoch 1740: train scaled MSE 9.63212e-05; val RMSE 0.001333782; lr 1e-05; 342s
network 7, training 6, epoch 1750: train scaled MSE 0.000100609; val RMSE 0.001334229; lr 1e-05; 344s
network 7, training 6, epoch 1760: train scaled MSE 9.69034e-05; val RMSE 0.001334003; lr 1e-05; 346s
network 7, training 6, epoch 1770: train scaled MSE 9.58946e-05; val RMSE 0.00133375; lr 1e-05; 348s
network 7, training 6, epoch 1780: train scaled MSE 9.56688e-05; val RMSE 0.001333871; lr 1e-05; 350s
network 7, training 6, epoch 1790: train scaled MSE 9.50902e-05; val RMSE 0.001333708; lr 1e-05; 351s
network 7, training 6, epoch 1800: train scaled MSE 9.50622e-05; val RMSE 0.001334345; lr 1e-05; 353s
network 7, training 6, epoch 1810: train scaled MSE 9.47388e-05; val RMSE 0.001333424; lr 1e-05; 355s
network 7, training 6, epoch 1820: train scaled MSE 9.50578e-05; val RMSE 0.001333479; lr 1e-05; 357s
network 7, training 6, epoch 1830: train scaled MSE 9.45882e-05; val RMSE 0.001333506; lr 1e-05; 359s
network 7, training 6, epoch 1840: train scaled MSE 9.54775e-05; val RMSE 0.001333665; lr 1e-05; 361s
network 7, training 6, epoch 1850: train scaled MSE 9.46352e-05; val RMSE 0.001333386; lr 1e-05; 363s
network 7, training 6, epoch 1860: train scaled MSE 9.37815e-05; val RMSE 0.001332931; lr 1e-05; 365s
network 7, training 6, epoch 1870: train scaled MSE 9.36915e-05; val RMSE 0.001332885; lr 1e-05; 367s
network 7, training 6, epoch 1880: train scaled MSE 9.38695e-05; val RMSE 0.001332762; lr 1e-05; 369s
network 7, training 6, epoch 1890: train scaled MSE 0.000100207; val RMSE 0.001333551; lr 1e-05; 371s
network 7, training 6, epoch 1900: train scaled MSE 9.59066e-05; val RMSE 0.001333452; lr 1e-05; 373s
network 7, training 6, epoch 1910: train scaled MSE 9.39246e-05; val RMSE 0.001332702; lr 1e-05; 375s
network 7, training 6, epoch 1920: train scaled MSE 9.30955e-05; val RMSE 0.001333158; lr 1e-05; 377s
network 7, training 6, epoch 1930: train scaled MSE 9.26748e-05; val RMSE 0.00133252; lr 1e-05; 379s
network 7, training 6, epoch 1940: train scaled MSE 9.31333e-05; val RMSE 0.001332866; lr 1e-05; 380s
network 7, training 6, epoch 1950: train scaled MSE 9.22478e-05; val RMSE 0.001332644; lr 1e-05; 382s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0018,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0018,-1.0271,"[-2.63%, 0.37%]",0.0644,0.0,0.1681
MLP,0.0016,25.6787,"[14.59%, 35.01%]",0.5277,719.2555,0.3391

network 7, training 7, epoch 1: train scaled MSE 0.831657; val RMSE 0.01909598; lr 0.001; 0s
network 7, training 7, epoch 10: train scaled MSE 0.0290665; val RMSE 0.004327218; lr 0.001; 2s
network 7, training 7, epoch 20: train scaled MSE 0.0104876; val RMSE 0.002461247; lr 0.001; 4s
network 7, training 7, epoch 30: train scaled MSE 0.00661874; val RMSE 0.002212696; lr 0.001; 6s
network 7, training 7, epoch 40: train scaled MSE 0.00550169; val RMSE 0.001920852; lr 0.001; 8s
network 7, training 7, epoch 50: train scaled MSE 0.00541993; val RMSE 0.00206041; lr 0.001; 10s
network 7, training 7, epoch 60: train scaled MSE 0.00383507; val RMSE 0.001816664; lr 0.001; 12s
network 7, training 7, epoch 70: train scaled MSE 0.00330213; val RMSE 0.001811559; lr 0.001; 14s
network 7, training 7, epoch 80: train scaled MSE 0.00410609; val RMSE 0.001808472; lr 0.001; 16s
network 7, training 7, epoch 90: train scaled MSE 0.00264151; val RMSE 0.001793283; lr 0.001; 18s
network 7, training 7, epoch 100: train scaled MSE 0.00151468; val RMSE 0.001903031; lr 0.001; 20s
network 7, training 7, epoch 110: train scaled MSE 0.00119478; val RMSE 0.001732512; lr 0.0005; 22s
network 7, training 7, epoch 120: train scaled MSE 0.00101266; val RMSE 0.001891312; lr 0.0005; 24s
network 7, training 7, epoch 130: train scaled MSE 0.00088984; val RMSE 0.001703191; lr 0.0005; 26s
network 7, training 7, epoch 140: train scaled MSE 0.000800008; val RMSE 0.001685679; lr 0.0005; 27s
network 7, training 7, epoch 150: train scaled MSE 0.00121166; val RMSE 0.001688692; lr 0.0005; 29s
network 7, training 7, epoch 160: train scaled MSE 0.000710791; val RMSE 0.001672395; lr 0.0005; 31s
network 7, training 7, epoch 170: train scaled MSE 0.000546403; val RMSE 0.001648774; lr 0.00025; 33s
network 7, training 7, epoch 180: train scaled MSE 0.000514327; val RMSE 0.001636783; lr 0.00025; 35s
network 7, training 7, epoch 190: train scaled MSE 0.000483235; val RMSE 0.001646625; lr 0.00025; 37s
network 7, training 7, epoch 200: train scaled MSE 0.000498021; val RMSE 0.001621957; lr 0.00025; 39s
network 7, training 7, epoch 210: train scaled MSE 0.000438347; val RMSE 0.001617808; lr 0.00025; 41s
network 7, training 7, epoch 220: train scaled MSE 0.000425896; val RMSE 0.001625894; lr 0.00025; 43s
network 7, training 7, epoch 230: train scaled MSE 0.000379534; val RMSE 0.001607105; lr 0.00025; 45s
network 7, training 7, epoch 240: train scaled MSE 0.000377106; val RMSE 0.001601743; lr 0.00025; 47s
network 7, training 7, epoch 250: train scaled MSE 0.000346621; val RMSE 0.0016024; lr 0.00025; 49s
network 7, training 7, epoch 260: train scaled MSE 0.000852063; val RMSE 0.001669619; lr 0.00025; 51s
network 7, training 7, epoch 270: train scaled MSE 0.000424572; val RMSE 0.001594664; lr 0.000125; 52s
network 7, training 7, epoch 280: train scaled MSE 0.000273604; val RMSE 0.001591219; lr 0.000125; 54s
network 7, training 7, epoch 290: train scaled MSE 0.000269403; val RMSE 0.001587333; lr 0.000125; 56s
network 7, training 7, epoch 300: train scaled MSE 0.000266012; val RMSE 0.00158541; lr 0.000125; 58s
network 7, training 7, epoch 310: train scaled MSE 0.000265056; val RMSE 0.001583483; lr 0.000125; 60s
network 7, training 7, epoch 320: train scaled MSE 0.000252318; val RMSE 0.001580362; lr 0.000125; 62s
network 7, training 7, epoch 330: train scaled MSE 0.000244143; val RMSE 0.001579747; lr 0.000125; 64s
network 7, training 7, epoch 340: train scaled MSE 0.000291869; val RMSE 0.001577571; lr 0.000125; 65s
network 7, training 7, epoch 350: train scaled MSE 0.000236323; val RMSE 0.001586902; lr 0.000125; 67s
network 7, training 7, epoch 360: train scaled MSE 0.000217665; val RMSE 0.001572333; lr 6.25e-05; 69s
network 7, training 7, epoch 370: train scaled MSE 0.000218498; val RMSE 0.00157092; lr 6.25e-05; 71s
network 7, training 7, epoch 380: train scaled MSE 0.000218451; val RMSE 0.001570325; lr 6.25e-05; 73s
network 7, training 7, epoch 390: train scaled MSE 0.000209194; val RMSE 0.001569596; lr 6.25e-05; 75s
network 7, training 7, epoch 400: train scaled MSE 0.000207479; val RMSE 0.001566771; lr 6.25e-05; 77s
network 7, training 7, epoch 410: train scaled MSE 0.000207052; val RMSE 0.001567316; lr 6.25e-05; 79s
network 7, training 7, epoch 420: train scaled MSE 0.000202188; val RMSE 0.00156292; lr 6.25e-05; 81s
network 7, training 7, epoch 430: train scaled MSE 0.000197764; val RMSE 0.001571065; lr 6.25e-05; 83s
network 7, training 7, epoch 440: train scaled MSE 0.000196552; val RMSE 0.00156049; lr 6.25e-05; 85s
network 7, training 7, epoch 450: train scaled MSE 0.000190247; val RMSE 0.00155644; lr 6.25e-05; 87s
network 7, training 7, epoch 460: train scaled MSE 0.000190148; val RMSE 0.001558348; lr 6.25e-05; 89s
network 7, training 7, epoch 470: train scaled MSE 0.000185611; val RMSE 0.001558341; lr 6.25e-05; 91s
network 7, training 7, epoch 480: train scaled MSE 0.000231998; val RMSE 0.001552928; lr 6.25e-05; 93s
network 7, training 7, epoch 490: train scaled MSE 0.000188723; val RMSE 0.001552175; lr 6.25e-05; 94s
network 7, training 7, epoch 500: train scaled MSE 0.000176349; val RMSE 0.001551158; lr 6.25e-05; 96s
network 7, training 7, epoch 510: train scaled MSE 0.000173698; val RMSE 0.001552205; lr 6.25e-05; 98s
network 7, training 7, epoch 520: train scaled MSE 0.00022642; val RMSE 0.001552786; lr 6.25e-05; 100s
network 7, training 7, epoch 530: train scaled MSE 0.000169348; val RMSE 0.001547461; lr 6.25e-05; 102s
network 7, training 7, epoch 540: train scaled MSE 0.000166144; val RMSE 0.001548963; lr 6.25e-05; 104s
network 7, training 7, epoch 550: train scaled MSE 0.000171909; val RMSE 0.00154926; lr 6.25e-05; 106s
network 7, training 7, epoch 560: train scaled MSE 0.000161361; val RMSE 0.001547198; lr 6.25e-05; 108s
network 7, training 7, epoch 570: train scaled MSE 0.000159935; val RMSE 0.001546688; lr 6.25e-05; 110s
network 7, training 7, epoch 580: train scaled MSE 0.000154774; val RMSE 0.001546082; lr 3.125e-05; 112s
network 7, training 7, epoch 590: train scaled MSE 0.000152939; val RMSE 0.001544493; lr 3.125e-05; 114s
network 7, training 7, epoch 600: train scaled MSE 0.000152488; val RMSE 0.001543651; lr 3.125e-05; 115s
network 7, training 7, epoch 610: train scaled MSE 0.000152768; val RMSE 0.001542646; lr 3.125e-05; 117s
network 7, training 7, epoch 620: train scaled MSE 0.000149671; val RMSE 0.001542837; lr 3.125e-05; 119s
network 7, training 7, epoch 630: train scaled MSE 0.000176833; val RMSE 0.00154157; lr 3.125e-05; 121s
network 7, training 7, epoch 640: train scaled MSE 0.00014847; val RMSE 0.001540881; lr 3.125e-05; 123s
network 7, training 7, epoch 650: train scaled MSE 0.000154563; val RMSE 0.001540588; lr 1.5625e-05; 125s
network 7, training 7, epoch 660: train scaled MSE 0.000144582; val RMSE 0.001539953; lr 1.5625e-05; 127s
network 7, training 7, epoch 670: train scaled MSE 0.000145237; val RMSE 0.001539786; lr 1.5625e-05; 129s
network 7, training 7, epoch 680: train scaled MSE 0.000144143; val RMSE 0.001539215; lr 1.5625e-05; 131s
network 7, training 7, epoch 690: train scaled MSE 0.000144136; val RMSE 0.001539129; lr 1.5625e-05; 133s
network 7, training 7, epoch 700: train scaled MSE 0.000142602; val RMSE 0.001538625; lr 1.5625e-05; 135s
network 7, training 7, epoch 710: train scaled MSE 0.000147564; val RMSE 0.001538529; lr 1.5625e-05; 137s
network 7, training 7, epoch 720: train scaled MSE 0.000141798; val RMSE 0.001537938; lr 1.5625e-05; 138s
network 7, training 7, epoch 730: train scaled MSE 0.000146538; val RMSE 0.001538652; lr 1.5625e-05; 140s
network 7, training 7, epoch 740: train scaled MSE 0.000144366; val RMSE 0.001537442; lr 1.5625e-05; 142s
network 7, training 7, epoch 750: train scaled MSE 0.00014239; val RMSE 0.001536675; lr 1.5625e-05; 144s
network 7, training 7, epoch 760: train scaled MSE 0.000139725; val RMSE 0.001536293; lr 1.5625e-05; 146s
network 7, training 7, epoch 770: train scaled MSE 0.000139027; val RMSE 0.001536249; lr 1.5625e-05; 148s
network 7, training 7, epoch 780: train scaled MSE 0.000138943; val RMSE 0.001535882; lr 1.5625e-05; 150s
network 7, training 7, epoch 790: train scaled MSE 0.000138739; val RMSE 0.001535475; lr 1e-05; 152s
network 7, training 7, epoch 800: train scaled MSE 0.000136896; val RMSE 0.0015347; lr 1e-05; 154s
network 7, training 7, epoch 810: train scaled MSE 0.000137742; val RMSE 0.001534897; lr 1e-05; 156s
network 7, training 7, epoch 820: train scaled MSE 0.000135924; val RMSE 0.001534606; lr 1e-05; 157s
network 7, training 7, epoch 830: train scaled MSE 0.000135547; val RMSE 0.001534555; lr 1e-05; 159s
network 7, training 7, epoch 840: train scaled MSE 0.000135335; val RMSE 0.001534415; lr 1e-05; 161s
network 7, training 7, epoch 850: train scaled MSE 0.000134929; val RMSE 0.001533986; lr 1e-05; 163s
network 7, training 7, epoch 860: train scaled MSE 0.000135119; val RMSE 0.001534192; lr 1e-05; 165s
network 7, training 7, epoch 870: train scaled MSE 0.000134176; val RMSE 0.001533827; lr 1e-05; 167s
network 7, training 7, epoch 880: train scaled MSE 0.000134241; val RMSE 0.001533832; lr 1e-05; 169s
network 7, training 7, epoch 890: train scaled MSE 0.000139596; val RMSE 0.001534058; lr 1e-05; 171s
network 7, training 7, epoch 900: train scaled MSE 0.000133426; val RMSE 0.001533606; lr 1e-05; 173s
network 7, training 7, epoch 910: train scaled MSE 0.000133043; val RMSE 0.001534009; lr 1e-05; 175s
network 7, training 7, epoch 920: train scaled MSE 0.000132778; val RMSE 0.001533494; lr 1e-05; 176s
network 7, training 7, epoch 930: train scaled MSE 0.000132979; val RMSE 0.001533436; lr 1e-05; 178s
network 7, training 7, epoch 940: train scaled MSE 0.000132063; val RMSE 0.001532437; lr 1e-05; 180s
network 7, training 7, epoch 950: train scaled MSE 0.00013204; val RMSE 0.001532419; lr 1e-05; 182s
network 7, training 7, epoch 960: train scaled MSE 0.000131452; val RMSE 0.001532126; lr 1e-05; 184s
network 7, training 7, epoch 970: train scaled MSE 0.000133152; val RMSE 0.00153248; lr 1e-05; 186s
network 7, training 7, epoch 980: train scaled MSE 0.000131043; val RMSE 0.001531959; lr 1e-05; 188s
network 7, training 7, epoch 990: train scaled MSE 0.000130463; val RMSE 0.001531589; lr 1e-05; 190s
network 7, training 7, epoch 1000: train scaled MSE 0.000130203; val RMSE 0.001531293; lr 1e-05; 192s
network 7, training 7, epoch 1010: train scaled MSE 0.000129857; val RMSE 0.001531369; lr 1e-05; 194s
network 7, training 7, epoch 1020: train scaled MSE 0.000135316; val RMSE 0.001531579; lr 1e-05; 196s
network 7, training 7, epoch 1030: train scaled MSE 0.000131182; val RMSE 0.001531718; lr 1e-05; 198s
network 7, training 7, epoch 1040: train scaled MSE 0.000129207; val RMSE 0.001531378; lr 1e-05; 199s
network 7, training 7, epoch 1050: train scaled MSE 0.000130161; val RMSE 0.001531326; lr 1e-05; 201s
network 7, training 7, epoch 1060: train scaled MSE 0.000128237; val RMSE 0.001530957; lr 1e-05; 203s
network 7, training 7, epoch 1070: train scaled MSE 0.0001283; val RMSE 0.001532315; lr 1e-05; 205s
network 7, training 7, epoch 1080: train scaled MSE 0.000127667; val RMSE 0.001530467; lr 1e-05; 207s
network 7, training 7, epoch 1090: train scaled MSE 0.000127351; val RMSE 0.001530211; lr 1e-05; 209s
network 7, training 7, epoch 1100: train scaled MSE 0.000127408; val RMSE 0.001530187; lr 1e-05; 211s
network 7, training 7, epoch 1110: train scaled MSE 0.00012727; val RMSE 0.001529513; lr 1e-05; 213s
network 7, training 7, epoch 1120: train scaled MSE 0.000127693; val RMSE 0.00153018; lr 1e-05; 215s
network 7, training 7, epoch 1130: train scaled MSE 0.000126973; val RMSE 0.001529198; lr 1e-05; 217s
network 7, training 7, epoch 1140: train scaled MSE 0.000126987; val RMSE 0.001529493; lr 1e-05; 219s
network 7, training 7, epoch 1150: train scaled MSE 0.000130344; val RMSE 0.001529331; lr 1e-05; 221s
network 7, training 7, epoch 1160: train scaled MSE 0.000125446; val RMSE 0.001528725; lr 1e-05; 222s
network 7, training 7, epoch 1170: train scaled MSE 0.000132429; val RMSE 0.001529161; lr 1e-05; 224s
network 7, training 7, epoch 1180: train scaled MSE 0.00012513; val RMSE 0.001528648; lr 1e-05; 226s
network 7, training 7, epoch 1190: train scaled MSE 0.000124713; val RMSE 0.001528708; lr 1e-05; 228s
network 7, training 7, epoch 1200: train scaled MSE 0.000127898; val RMSE 0.001528962; lr 1e-05; 230s
Standard Linear Baseline Validation RMSE: 0.001920123

Network seed 7, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0019,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0020,-1.1257,"[-2.65%, 0.14%]",0.0537,0.0,0.1368
MLP,0.0017,27.5121,"[18.83%, 35.14%]",0.5333,893.5124,0.3276

network 7, training 8, epoch 1: train scaled MSE 0.816363; val RMSE 0.02006523; lr 0.001; 0s
network 7, training 8, epoch 10: train scaled MSE 0.0217039; val RMSE 0.004437717; lr 0.001; 2s
network 7, training 8, epoch 20: train scaled MSE 0.00842769; val RMSE 0.003381332; lr 0.001; 4s
network 7, training 8, epoch 30: train scaled MSE 0.00680215; val RMSE 0.002626917; lr 0.001; 6s
network 7, training 8, epoch 40: train scaled MSE 0.00845576; val RMSE 0.002543883; lr 0.001; 8s
network 7, training 8, epoch 50: train scaled MSE 0.0039072; val RMSE 0.002386853; lr 0.001; 10s
network 7, training 8, epoch 60: train scaled MSE 0.00304966; val RMSE 0.002381599; lr 0.001; 12s
network 7, training 8, epoch 70: train scaled MSE 0.00233023; val RMSE 0.002282464; lr 0.001; 14s
network 7, training 8, epoch 80: train scaled MSE 0.0019737; val RMSE 0.003293563; lr 0.001; 16s
network 7, training 8, epoch 90: train scaled MSE 0.00189293; val RMSE 0.002235207; lr 0.001; 18s
network 7, training 8, epoch 100: train scaled MSE 0.00140049; val RMSE 0.002133019; lr 0.001; 20s
network 7, training 8, epoch 110: train scaled MSE 0.00133946; val RMSE 0.002153445; lr 0.001; 22s
network 7, training 8, epoch 120: train scaled MSE 0.000782189; val RMSE 0.002088056; lr 0.0005; 24s
network 7, training 8, epoch 130: train scaled MSE 0.000739236; val RMSE 0.002062584; lr 0.0005; 26s
network 7, training 8, epoch 140: train scaled MSE 0.000634818; val RMSE 0.002050908; lr 0.0005; 28s
network 7, training 8, epoch 150: train scaled MSE 0.000602667; val RMSE 0.002045263; lr 0.0005; 30s
network 7, training 8, epoch 160: train scaled MSE 0.000540789; val RMSE 0.002038959; lr 0.0005; 32s
network 7, training 8, epoch 170: train scaled MSE 0.000492211; val RMSE 0.00204671; lr 0.0005; 34s
network 7, training 8, epoch 180: train scaled MSE 0.000487932; val RMSE 0.00203096; lr 0.0005; 36s
network 7, training 8, epoch 190: train scaled MSE 0.000440921; val RMSE 0.002078466; lr 0.0005; 37s
network 7, training 8, epoch 200: train scaled MSE 0.000368969; val RMSE 0.002009023; lr 0.0005; 39s
network 7, training 8, epoch 210: train scaled MSE 0.000363708; val RMSE 0.002009067; lr 0.0005; 41s
network 7, training 8, epoch 220: train scaled MSE 0.000290159; val RMSE 0.001994823; lr 0.00025; 43s
network 7, training 8, epoch 230: train scaled MSE 0.0002963; val RMSE 0.002000459; lr 0.00025; 45s
network 7, training 8, epoch 240: train scaled MSE 0.00024072; val RMSE 0.001987416; lr 0.000125; 47s
network 7, training 8, epoch 250: train scaled MSE 0.000263925; val RMSE 0.001984575; lr 0.000125; 49s
network 7, training 8, epoch 260: train scaled MSE 0.000272574; val RMSE 0.001991543; lr 0.000125; 51s
network 7, training 8, epoch 270: train scaled MSE 0.000221482; val RMSE 0.001973156; lr 0.000125; 53s
network 7, training 8, epoch 280: train scaled MSE 0.000239361; val RMSE 0.001967946; lr 0.000125; 55s
network 7, training 8, epoch 290: train scaled MSE 0.000210785; val RMSE 0.001963516; lr 0.000125; 57s
network 7, training 8, epoch 300: train scaled MSE 0.000202187; val RMSE 0.001960665; lr 0.000125; 59s
network 7, training 8, epoch 310: train scaled MSE 0.000198512; val RMSE 0.001957829; lr 0.000125; 61s
network 7, training 8, epoch 320: train scaled MSE 0.000366917; val RMSE 0.001959191; lr 0.000125; 63s
network 7, training 8, epoch 330: train scaled MSE 0.000186984; val RMSE 0.001952489; lr 0.000125; 65s
network 7, training 8, epoch 340: train scaled MSE 0.000369488; val RMSE 0.00195158; lr 0.000125; 67s
network 7, training 8, epoch 350: train scaled MSE 0.000177956; val RMSE 0.001946891; lr 0.000125; 69s
network 7, training 8, epoch 360: train scaled MSE 0.000183278; val RMSE 0.001947068; lr 0.000125; 71s
network 7, training 8, epoch 370: train scaled MSE 0.000168334; val RMSE 0.00194583; lr 0.000125; 73s
network 7, training 8, epoch 380: train scaled MSE 0.000165627; val RMSE 0.001942099; lr 0.000125; 75s
network 7, training 8, epoch 390: train scaled MSE 0.000160764; val RMSE 0.001939393; lr 0.000125; 77s
network 7, training 8, epoch 400: train scaled MSE 0.000158519; val RMSE 0.001937624; lr 0.000125; 79s
network 7, training 8, epoch 410: train scaled MSE 0.000148413; val RMSE 0.001933066; lr 6.25e-05; 81s
network 7, training 8, epoch 420: train scaled MSE 0.000145382; val RMSE 0.001934248; lr 6.25e-05; 82s
network 7, training 8, epoch 430: train scaled MSE 0.000144156; val RMSE 0.001930804; lr 6.25e-05; 84s
network 7, training 8, epoch 440: train scaled MSE 0.000147124; val RMSE 0.001929285; lr 6.25e-05; 86s
network 7, training 8, epoch 450: train scaled MSE 0.00013941; val RMSE 0.001927615; lr 6.25e-05; 88s
network 7, training 8, epoch 460: train scaled MSE 0.000137367; val RMSE 0.001928437; lr 6.25e-05; 90s
network 7, training 8, epoch 470: train scaled MSE 0.000135166; val RMSE 0.001926195; lr 6.25e-05; 92s
network 7, training 8, epoch 480: train scaled MSE 0.000134018; val RMSE 0.001922331; lr 6.25e-05; 94s
network 7, training 8, epoch 490: train scaled MSE 0.000131898; val RMSE 0.001921907; lr 6.25e-05; 96s
network 7, training 8, epoch 500: train scaled MSE 0.000130775; val RMSE 0.001919191; lr 6.25e-05; 98s
network 7, training 8, epoch 510: train scaled MSE 0.00013224; val RMSE 0.001917617; lr 6.25e-05; 100s
network 7, training 8, epoch 520: train scaled MSE 0.000127137; val RMSE 0.001916779; lr 6.25e-05; 102s
network 7, training 8, epoch 530: train scaled MSE 0.000127415; val RMSE 0.001916876; lr 6.25e-05; 104s
network 7, training 8, epoch 540: train scaled MSE 0.000125404; val RMSE 0.001920197; lr 6.25e-05; 106s
network 7, training 8, epoch 550: train scaled MSE 0.000120948; val RMSE 0.001912127; lr 6.25e-05; 108s
network 7, training 8, epoch 560: train scaled MSE 0.000117058; val RMSE 0.00191164; lr 3.125e-05; 110s
network 7, training 8, epoch 570: train scaled MSE 0.000121628; val RMSE 0.001912963; lr 3.125e-05; 112s
network 7, training 8, epoch 580: train scaled MSE 0.000115444; val RMSE 0.001909643; lr 3.125e-05; 114s
network 7, training 8, epoch 590: train scaled MSE 0.000114816; val RMSE 0.001908888; lr 3.125e-05; 116s
network 7, training 8, epoch 600: train scaled MSE 0.000117999; val RMSE 0.001908438; lr 3.125e-05; 118s
network 7, training 8, epoch 610: train scaled MSE 0.000115211; val RMSE 0.001908081; lr 3.125e-05; 120s
network 7, training 8, epoch 620: train scaled MSE 0.000114307; val RMSE 0.001906894; lr 3.125e-05; 122s
network 7, training 8, epoch 630: train scaled MSE 0.000112123; val RMSE 0.001906119; lr 3.125e-05; 124s
network 7, training 8, epoch 640: train scaled MSE 0.000123088; val RMSE 0.001906908; lr 3.125e-05; 126s
network 7, training 8, epoch 650: train scaled MSE 0.0001152; val RMSE 0.001904627; lr 3.125e-05; 128s
network 7, training 8, epoch 660: train scaled MSE 0.000116013; val RMSE 0.001904377; lr 3.125e-05; 130s
network 7, training 8, epoch 670: train scaled MSE 0.000109135; val RMSE 0.001905086; lr 3.125e-05; 132s
network 7, training 8, epoch 680: train scaled MSE 0.000107815; val RMSE 0.001903163; lr 3.125e-05; 134s
network 7, training 8, epoch 690: train scaled MSE 0.000109871; val RMSE 0.001902171; lr 3.125e-05; 136s
network 7, training 8, epoch 700: train scaled MSE 0.000106846; val RMSE 0.00190145; lr 3.125e-05; 138s
network 7, training 8, epoch 710: train scaled MSE 0.000105238; val RMSE 0.001901512; lr 1.5625e-05; 140s
network 7, training 8, epoch 720: train scaled MSE 0.00010527; val RMSE 0.00190142; lr 1e-05; 142s
network 7, training 8, epoch 730: train scaled MSE 0.000103547; val RMSE 0.001900589; lr 1e-05; 144s
network 7, training 8, epoch 740: train scaled MSE 0.000106694; val RMSE 0.001900994; lr 1e-05; 146s
network 7, training 8, epoch 750: train scaled MSE 0.000105292; val RMSE 0.001900302; lr 1e-05; 148s
network 7, training 8, epoch 760: train scaled MSE 0.000103679; val RMSE 0.001900222; lr 1e-05; 150s
network 7, training 8, epoch 770: train scaled MSE 0.000102725; val RMSE 0.001899489; lr 1e-05; 152s
network 7, training 8, epoch 780: train scaled MSE 0.000103894; val RMSE 0.001899517; lr 1e-05; 154s
network 7, training 8, epoch 790: train scaled MSE 0.000102147; val RMSE 0.001899304; lr 1e-05; 155s
network 7, training 8, epoch 800: train scaled MSE 0.000102075; val RMSE 0.001899242; lr 1e-05; 157s
network 7, training 8, epoch 810: train scaled MSE 0.000101548; val RMSE 0.00189915; lr 1e-05; 159s
network 7, training 8, epoch 820: train scaled MSE 0.000101555; val RMSE 0.001898584; lr 1e-05; 161s
network 7, training 8, epoch 830: train scaled MSE 0.000102256; val RMSE 0.001898551; lr 1e-05; 163s
network 7, training 8, epoch 840: train scaled MSE 0.000101018; val RMSE 0.001897771; lr 1e-05; 165s
network 7, training 8, epoch 850: train scaled MSE 0.000100643; val RMSE 0.001897652; lr 1e-05; 167s
network 7, training 8, epoch 860: train scaled MSE 0.000100261; val RMSE 0.001897742; lr 1e-05; 169s
network 7, training 8, epoch 870: train scaled MSE 0.000100038; val RMSE 0.001897361; lr 1e-05; 171s
network 7, training 8, epoch 880: train scaled MSE 0.000100332; val RMSE 0.001897101; lr 1e-05; 173s
network 7, training 8, epoch 890: train scaled MSE 9.98193e-05; val RMSE 0.001896812; lr 1e-05; 175s
network 7, training 8, epoch 900: train scaled MSE 9.92976e-05; val RMSE 0.001896892; lr 1e-05; 177s
network 7, training 8, epoch 910: train scaled MSE 9.91235e-05; val RMSE 0.001896714; lr 1e-05; 179s
network 7, training 8, epoch 920: train scaled MSE 9.88485e-05; val RMSE 0.001896089; lr 1e-05; 181s
network 7, training 8, epoch 930: train scaled MSE 9.85678e-05; val RMSE 0.00189611; lr 1e-05; 183s
network 7, training 8, epoch 940: train scaled MSE 9.92648e-05; val RMSE 0.001895997; lr 1e-05; 184s
network 7, training 8, epoch 950: train scaled MSE 9.78991e-05; val RMSE 0.001895837; lr 1e-05; 186s
network 7, training 8, epoch 960: train scaled MSE 0.00010037; val RMSE 0.001895751; lr 1e-05; 188s
network 7, training 8, epoch 970: train scaled MSE 9.74521e-05; val RMSE 0.001895237; lr 1e-05; 190s
network 7, training 8, epoch 980: train scaled MSE 9.83955e-05; val RMSE 0.001894995; lr 1e-05; 192s
network 7, training 8, epoch 990: train scaled MSE 9.80703e-05; val RMSE 0.001894627; lr 1e-05; 194s
network 7, training 8, epoch 1000: train scaled MSE 9.86376e-05; val RMSE 0.00189508; lr 1e-05; 196s
network 7, training 8, epoch 1010: train scaled MSE 9.69673e-05; val RMSE 0.001894426; lr 1e-05; 198s
network 7, training 8, epoch 1020: train scaled MSE 9.97066e-05; val RMSE 0.001894295; lr 1e-05; 200s
network 7, training 8, epoch 1030: train scaled MSE 9.67252e-05; val RMSE 0.001894158; lr 1e-05; 202s
network 7, training 8, epoch 1040: train scaled MSE 9.76125e-05; val RMSE 0.001894108; lr 1e-05; 204s
network 7, training 8, epoch 1050: train scaled MSE 9.55883e-05; val RMSE 0.001893529; lr 1e-05; 206s
network 7, training 8, epoch 1060: train scaled MSE 9.53512e-05; val RMSE 0.001893938; lr 1e-05; 209s
network 7, training 8, epoch 1070: train scaled MSE 0.000102199; val RMSE 0.001892589; lr 1e-05; 211s
network 7, training 8, epoch 1080: train scaled MSE 9.48673e-05; val RMSE 0.001893415; lr 1e-05; 213s
network 7, training 8, epoch 1090: train scaled MSE 9.47264e-05; val RMSE 0.001892573; lr 1e-05; 215s
network 7, training 8, epoch 1100: train scaled MSE 9.52213e-05; val RMSE 0.001892859; lr 1e-05; 217s
network 7, training 8, epoch 1110: train scaled MSE 9.53672e-05; val RMSE 0.001892886; lr 1e-05; 219s
network 7, training 8, epoch 1120: train scaled MSE 0.000110318; val RMSE 0.001893278; lr 1e-05; 221s
network 7, training 8, epoch 1130: train scaled MSE 9.35085e-05; val RMSE 0.001892332; lr 1e-05; 223s
network 7, training 8, epoch 1140: train scaled MSE 9.35102e-05; val RMSE 0.001891889; lr 1e-05; 225s
network 7, training 8, epoch 1150: train scaled MSE 9.32488e-05; val RMSE 0.001891763; lr 1e-05; 227s
network 7, training 8, epoch 1160: train scaled MSE 9.36409e-05; val RMSE 0.00189192; lr 1e-05; 229s
network 7, training 8, epoch 1170: train scaled MSE 9.37413e-05; val RMSE 0.00189167; lr 1e-05; 231s
network 7, training 8, epoch 1180: train scaled MSE 9.42295e-05; val RMSE 0.001891533; lr 1e-05; 233s
network 7, training 8, epoch 1190: train scaled MSE 9.35884e-05; val RMSE 0.001891838; lr 1e-05; 235s
network 7, training 8, epoch 1200: train scaled MSE 9.24372e-05; val RMSE 0.001891485; lr 1e-05; 237s
network 7, training 8, epoch 1210: train scaled MSE 9.31378e-05; val RMSE 0.001890907; lr 1e-05; 239s
network 7, training 8, epoch 1220: train scaled MSE 9.42401e-05; val RMSE 0.001890698; lr 1e-05; 241s
network 7, training 8, epoch 1230: train scaled MSE 9.23397e-05; val RMSE 0.001891823; lr 1e-05; 244s
network 7, training 8, epoch 1240: train scaled MSE 9.17031e-05; val RMSE 0.001890293; lr 1e-05; 246s
network 7, training 8, epoch 1250: train scaled MSE 9.12779e-05; val RMSE 0.001890303; lr 1e-05; 248s
network 7, training 8, epoch 1260: train scaled MSE 9.1109e-05; val RMSE 0.001890251; lr 1e-05; 250s
network 7, training 8, epoch 1270: train scaled MSE 9.10235e-05; val RMSE 0.001889724; lr 1e-05; 252s
network 7, training 8, epoch 1280: train scaled MSE 9.06868e-05; val RMSE 0.001890287; lr 1e-05; 254s
network 7, training 8, epoch 1290: train scaled MSE 9.05236e-05; val RMSE 0.001889382; lr 1e-05; 256s
network 7, training 8, epoch 1300: train scaled MSE 9.05172e-05; val RMSE 0.001889436; lr 1e-05; 258s
network 7, training 8, epoch 1310: train scaled MSE 9.41661e-05; val RMSE 0.001889794; lr 1e-05; 260s
network 7, training 8, epoch 1320: train scaled MSE 9.08634e-05; val RMSE 0.001889474; lr 1e-05; 262s
network 7, training 8, epoch 1330: train scaled MSE 8.96571e-05; val RMSE 0.001888914; lr 1e-05; 264s
network 7, training 8, epoch 1340: train scaled MSE 8.92288e-05; val RMSE 0.001888859; lr 1e-05; 266s
network 7, training 8, epoch 1350: train scaled MSE 8.90867e-05; val RMSE 0.001888887; lr 1e-05; 268s
network 7, training 8, epoch 1360: train scaled MSE 8.902e-05; val RMSE 0.001888459; lr 1e-05; 270s
network 7, training 8, epoch 1370: train scaled MSE 8.87145e-05; val RMSE 0.001888083; lr 1e-05; 272s
network 7, training 8, epoch 1380: train scaled MSE 9.24101e-05; val RMSE 0.001888515; lr 1e-05; 274s
network 7, training 8, epoch 1390: train scaled MSE 8.82328e-05; val RMSE 0.001887649; lr 1e-05; 276s
network 7, training 8, epoch 1400: train scaled MSE 8.96298e-05; val RMSE 0.001888036; lr 1e-05; 278s
network 7, training 8, epoch 1410: train scaled MSE 8.76587e-05; val RMSE 0.001887222; lr 1e-05; 280s
network 7, training 8, epoch 1420: train scaled MSE 8.88432e-05; val RMSE 0.001887683; lr 1e-05; 282s
network 7, training 8, epoch 1430: train scaled MSE 8.72792e-05; val RMSE 0.00188742; lr 1e-05; 285s
network 7, training 8, epoch 1440: train scaled MSE 8.81623e-05; val RMSE 0.001887414; lr 1e-05; 287s
network 7, training 8, epoch 1450: train scaled MSE 8.69482e-05; val RMSE 0.001886844; lr 1e-05; 289s
network 7, training 8, epoch 1460: train scaled MSE 8.67695e-05; val RMSE 0.001886746; lr 1e-05; 291s
network 7, training 8, epoch 1470: train scaled MSE 8.6915e-05; val RMSE 0.001886983; lr 1e-05; 293s
network 7, training 8, epoch 1480: train scaled MSE 8.64744e-05; val RMSE 0.001886624; lr 1e-05; 295s
network 7, training 8, epoch 1490: train scaled MSE 8.69539e-05; val RMSE 0.0018866; lr 1e-05; 297s
network 7, training 8, epoch 1500: train scaled MSE 8.60537e-05; val RMSE 0.001887039; lr 1e-05; 299s
network 7, training 8, epoch 1510: train scaled MSE 8.57621e-05; val RMSE 0.001885985; lr 1e-05; 301s
network 7, training 8, epoch 1520: train scaled MSE 8.75279e-05; val RMSE 0.00188681; lr 1e-05; 303s
network 7, training 8, epoch 1530: train scaled MSE 8.52081e-05; val RMSE 0.001885643; lr 1e-05; 305s
network 7, training 8, epoch 1540: train scaled MSE 8.50234e-05; val RMSE 0.001885787; lr 1e-05; 307s
network 7, training 8, epoch 1550: train scaled MSE 8.48476e-05; val RMSE 0.001885137; lr 1e-05; 309s
network 7, training 8, epoch 1560: train scaled MSE 8.47867e-05; val RMSE 0.001885166; lr 1e-05; 311s
network 7, training 8, epoch 1570: train scaled MSE 8.57098e-05; val RMSE 0.001884885; lr 1e-05; 313s
network 7, training 8, epoch 1580: train scaled MSE 8.47652e-05; val RMSE 0.001884795; lr 1e-05; 315s
network 7, training 8, epoch 1590: train scaled MSE 8.59851e-05; val RMSE 0.001885074; lr 1e-05; 318s
network 7, training 8, epoch 1600: train scaled MSE 8.45687e-05; val RMSE 0.001884643; lr 1e-05; 320s
network 7, training 8, epoch 1610: train scaled MSE 8.40061e-05; val RMSE 0.001884407; lr 1e-05; 322s
network 7, training 8, epoch 1620: train scaled MSE 8.36567e-05; val RMSE 0.001884146; lr 1e-05; 324s
network 7, training 8, epoch 1630: train scaled MSE 8.37214e-05; val RMSE 0.001883825; lr 1e-05; 326s
network 7, training 8, epoch 1640: train scaled MSE 8.33522e-05; val RMSE 0.001883841; lr 1e-05; 328s
network 7, training 8, epoch 1650: train scaled MSE 8.29843e-05; val RMSE 0.001883786; lr 1e-05; 330s
network 7, training 8, epoch 1660: train scaled MSE 8.28602e-05; val RMSE 0.001883367; lr 1e-05; 332s
network 7, training 8, epoch 1670: train scaled MSE 8.29171e-05; val RMSE 0.001883335; lr 1e-05; 334s
network 7, training 8, epoch 1680: train scaled MSE 8.24257e-05; val RMSE 0.001883928; lr 1e-05; 336s
network 7, training 8, epoch 1690: train scaled MSE 8.25482e-05; val RMSE 0.001883197; lr 1e-05; 338s
network 7, training 8, epoch 1700: train scaled MSE 8.20863e-05; val RMSE 0.001882797; lr 1e-05; 340s
network 7, training 8, epoch 1710: train scaled MSE 8.20341e-05; val RMSE 0.001882513; lr 1e-05; 342s
network 7, training 8, epoch 1720: train scaled MSE 8.17151e-05; val RMSE 0.001882471; lr 1e-05; 344s
network 7, training 8, epoch 1730: train scaled MSE 8.16623e-05; val RMSE 0.001882417; lr 1e-05; 346s
network 7, training 8, epoch 1740: train scaled MSE 8.13444e-05; val RMSE 0.001882551; lr 1e-05; 348s
network 7, training 8, epoch 1750: train scaled MSE 8.12792e-05; val RMSE 0.001882592; lr 1e-05; 350s
network 7, training 8, epoch 1760: train scaled MSE 8.1256e-05; val RMSE 0.001882164; lr 1e-05; 352s
network 7, training 8, epoch 1770: train scaled MSE 8.14645e-05; val RMSE 0.001881844; lr 1e-05; 354s
network 7, training 8, epoch 1780: train scaled MSE 8.09597e-05; val RMSE 0.001882035; lr 1e-05; 356s
network 7, training 8, epoch 1790: train scaled MSE 8.19423e-05; val RMSE 0.001881527; lr 1e-05; 358s
network 7, training 8, epoch 1800: train scaled MSE 8.0288e-05; val RMSE 0.001881504; lr 1e-05; 360s
network 7, training 8, epoch 1810: train scaled MSE 8.01238e-05; val RMSE 0.001881108; lr 1e-05; 362s
network 7, training 8, epoch 1820: train scaled MSE 7.99498e-05; val RMSE 0.001881383; lr 1e-05; 364s
network 7, training 8, epoch 1830: train scaled MSE 8.01249e-05; val RMSE 0.001880346; lr 1e-05; 366s
network 7, training 8, epoch 1840: train scaled MSE 7.98794e-05; val RMSE 0.001880749; lr 1e-05; 368s
network 7, training 8, epoch 1850: train scaled MSE 7.92735e-05; val RMSE 0.001880591; lr 1e-05; 370s
network 7, training 8, epoch 1860: train scaled MSE 7.91565e-05; val RMSE 0.001881032; lr 1e-05; 372s
network 7, training 8, epoch 1870: train scaled MSE 7.92015e-05; val RMSE 0.001880602; lr 1e-05; 374s
network 7, training 8, epoch 1880: train scaled MSE 8.04581e-05; val RMSE 0.001880611; lr 1e-05; 376s
network 7, training 8, epoch 1890: train scaled MSE 8.0342e-05; val RMSE 0.001880505; lr 1e-05; 378s
network 7, training 8, epoch 1900: train scaled MSE 7.84706e-05; val RMSE 0.001880333; lr 1e-05; 380s
network 7, training 8, epoch 1910: train scaled MSE 7.83978e-05; val RMSE 0.001880082; lr 1e-05; 382s
network 7, training 8, epoch 1920: train scaled MSE 8.01635e-05; val RMSE 0.001880207; lr 1e-05; 384s
network 7, training 8, epoch 1930: train scaled MSE 7.8968e-05; val RMSE 0.001879742; lr 1e-05; 386s
network 7, training 8, epoch 1940: train scaled MSE 7.87468e-05; val RMSE 0.001879751; lr 1e-05; 388s
network 7, training 8, epoch 1950: train scaled MSE 7.8176e-05; val RMSE 0.001879668; lr 1e-05; 390s

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0018,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0018,-1.3070,"[-2.64%, -0.30%]",0.0476,0.0,0.2591
MLP,0.0015,26.3444,"[15.70%, 35.26%]",0.5484,1051.2429,0.3323

network 7, training 9, epoch 1: train scaled MSE 0.80642; val RMSE 0.01936651; lr 0.001; 0s
network 7, training 9, epoch 10: train scaled MSE 0.0204448; val RMSE 0.003319753; lr 0.001; 2s
network 7, training 9, epoch 20: train scaled MSE 0.00800006; val RMSE 0.001838246; lr 0.001; 4s
network 7, training 9, epoch 30: train scaled MSE 0.00752225; val RMSE 0.001806734; lr 0.001; 6s
network 7, training 9, epoch 40: train scaled MSE 0.0067428; val RMSE 0.001895807; lr 0.001; 8s
network 7, training 9, epoch 50: train scaled MSE 0.00402681; val RMSE 0.001316031; lr 0.0005; 10s
network 7, training 9, epoch 60: train scaled MSE 0.00349849; val RMSE 0.001289138; lr 0.0005; 12s
network 7, training 9, epoch 70: train scaled MSE 0.00300866; val RMSE 0.001303843; lr 0.0005; 14s
network 7, training 9, epoch 80: train scaled MSE 0.00229498; val RMSE 0.001248731; lr 0.00025; 16s
network 7, training 9, epoch 90: train scaled MSE 0.00215813; val RMSE 0.001254356; lr 0.00025; 18s
network 7, training 9, epoch 100: train scaled MSE 0.00184665; val RMSE 0.001228499; lr 0.00025; 20s
network 7, training 9, epoch 110: train scaled MSE 0.00167929; val RMSE 0.001229085; lr 0.00025; 22s
network 7, training 9, epoch 120: train scaled MSE 0.00147839; val RMSE 0.001215131; lr 0.00025; 24s
network 7, training 9, epoch 130: train scaled MSE 0.00135038; val RMSE 0.001205254; lr 0.00025; 26s
network 7, training 9, epoch 140: train scaled MSE 0.00121069; val RMSE 0.001203641; lr 0.00025; 28s
network 7, training 9, epoch 150: train scaled MSE 0.00110827; val RMSE 0.001186114; lr 0.00025; 30s
network 7, training 9, epoch 160: train scaled MSE 0.00100132; val RMSE 0.001189482; lr 0.00025; 32s
network 7, training 9, epoch 170: train scaled MSE 0.000889315; val RMSE 0.001177261; lr 0.00025; 34s
network 7, training 9, epoch 180: train scaled MSE 0.000854478; val RMSE 0.001172934; lr 0.00025; 36s
network 7, training 9, epoch 190: train scaled MSE 0.000849663; val RMSE 0.001177961; lr 0.00025; 38s
network 7, training 9, epoch 200: train scaled MSE 0.000686065; val RMSE 0.001156991; lr 0.00025; 40s
network 7, training 9, epoch 210: train scaled MSE 0.000636685; val RMSE 0.001163731; lr 0.00025; 42s
network 7, training 9, epoch 220: train scaled MSE 0.00116985; val RMSE 0.001172643; lr 0.00025; 44s
network 7, training 9, epoch 230: train scaled MSE 0.000591789; val RMSE 0.001158124; lr 0.00025; 46s
network 7, training 9, epoch 240: train scaled MSE 0.000551063; val RMSE 0.001145032; lr 0.00025; 48s
network 7, training 9, epoch 250: train scaled MSE 0.000494978; val RMSE 0.001137372; lr 0.00025; 50s
network 7, training 9, epoch 260: train scaled MSE 0.000441912; val RMSE 0.001134916; lr 0.000125; 52s
network 7, training 9, epoch 270: train scaled MSE 0.000429517; val RMSE 0.001163671; lr 0.000125; 54s
network 7, training 9, epoch 280: train scaled MSE 0.000410311; val RMSE 0.001120032; lr 0.000125; 56s
network 7, training 9, epoch 290: train scaled MSE 0.000399493; val RMSE 0.001119023; lr 0.000125; 58s
network 7, training 9, epoch 300: train scaled MSE 0.000396228; val RMSE 0.001188061; lr 0.000125; 60s
network 7, training 9, epoch 310: train scaled MSE 0.000371897; val RMSE 0.001287854; lr 0.000125; 61s
network 7, training 9, epoch 320: train scaled MSE 0.000447017; val RMSE 0.001116022; lr 6.25e-05; 63s
network 7, training 9, epoch 330: train scaled MSE 0.000342055; val RMSE 0.001109245; lr 6.25e-05; 65s
network 7, training 9, epoch 340: train scaled MSE 0.000345807; val RMSE 0.00111114; lr 6.25e-05; 67s
network 7, training 9, epoch 350: train scaled MSE 0.000326315; val RMSE 0.00110564; lr 3.125e-05; 69s
network 7, training 9, epoch 360: train scaled MSE 0.000323331; val RMSE 0.001104766; lr 3.125e-05; 71s
network 7, training 9, epoch 370: train scaled MSE 0.000319326; val RMSE 0.00110467; lr 1.5625e-05; 73s
network 7, training 9, epoch 380: train scaled MSE 0.000316013; val RMSE 0.001104099; lr 1.5625e-05; 75s
network 7, training 9, epoch 390: train scaled MSE 0.00031489; val RMSE 0.001103383; lr 1.5625e-05; 77s
network 7, training 9, epoch 400: train scaled MSE 0.000313444; val RMSE 0.001103608; lr 1.5625e-05; 79s
network 7, training 9, epoch 410: train scaled MSE 0.000311374; val RMSE 0.001102938; lr 1.5625e-05; 80s
network 7, training 9, epoch 420: train scaled MSE 0.000309595; val RMSE 0.001102573; lr 1.5625e-05; 82s
network 7, training 9, epoch 430: train scaled MSE 0.000305988; val RMSE 0.001101754; lr 1e-05; 84s
network 7, training 9, epoch 440: train scaled MSE 0.000304654; val RMSE 0.001101571; lr 1e-05; 86s
network 7, training 9, epoch 450: train scaled MSE 0.000303692; val RMSE 0.001101284; lr 1e-05; 88s
network 7, training 9, epoch 460: train scaled MSE 0.000305621; val RMSE 0.001102713; lr 1e-05; 90s
network 7, training 9, epoch 470: train scaled MSE 0.00030178; val RMSE 0.001100137; lr 1e-05; 92s
network 7, training 9, epoch 480: train scaled MSE 0.000312553; val RMSE 0.001100986; lr 1e-05; 94s
network 7, training 9, epoch 490: train scaled MSE 0.000298812; val RMSE 0.001100039; lr 1e-05; 96s
network 7, training 9, epoch 500: train scaled MSE 0.000297406; val RMSE 0.001100232; lr 1e-05; 97s
network 7, training 9, epoch 510: train scaled MSE 0.000298429; val RMSE 0.00110202; lr 1e-05; 99s
network 7, training 9, epoch 520: train scaled MSE 0.000296572; val RMSE 0.00110027; lr 1e-05; 101s
network 7, training 9, epoch 530: train scaled MSE 0.000294497; val RMSE 0.001099564; lr 1e-05; 103s
network 7, training 9, epoch 540: train scaled MSE 0.000304132; val RMSE 0.0011013; lr 1e-05; 104s
network 7, training 9, epoch 550: train scaled MSE 0.000294405; val RMSE 0.001099274; lr 1e-05; 106s
network 7, training 9, epoch 560: train scaled MSE 0.000291841; val RMSE 0.001099665; lr 1e-05; 108s
network 7, training 9, epoch 570: train scaled MSE 0.000290688; val RMSE 0.001098648; lr 1e-05; 110s
network 7, training 9, epoch 580: train scaled MSE 0.00028955; val RMSE 0.001098342; lr 1e-05; 112s
network 7, training 9, epoch 590: train scaled MSE 0.000289533; val RMSE 0.001098301; lr 1e-05; 113s
network 7, training 9, epoch 600: train scaled MSE 0.000287289; val RMSE 0.001099022; lr 1e-05; 115s
network 7, training 9, epoch 610: train scaled MSE 0.000286469; val RMSE 0.00109866; lr 1e-05; 117s
network 7, training 9, epoch 620: train scaled MSE 0.000287096; val RMSE 0.00109884; lr 1e-05; 119s
network 7, training 9, epoch 630: train scaled MSE 0.000284494; val RMSE 0.001097581; lr 1e-05; 120s
network 7, training 9, epoch 640: train scaled MSE 0.00028298; val RMSE 0.00109675; lr 1e-05; 122s
network 7, training 9, epoch 650: train scaled MSE 0.000284519; val RMSE 0.001097181; lr 1e-05; 124s
network 7, training 9, epoch 660: train scaled MSE 0.000281591; val RMSE 0.001096952; lr 1e-05; 125s
network 7, training 9, epoch 670: train scaled MSE 0.00028033; val RMSE 0.001096817; lr 1e-05; 127s
network 7, training 9, epoch 680: train scaled MSE 0.000281216; val RMSE 0.001096809; lr 1e-05; 129s
network 7, training 9, epoch 690: train scaled MSE 0.000278773; val RMSE 0.001096804; lr 1e-05; 131s
network 7, training 9, epoch 700: train scaled MSE 0.000277899; val RMSE 0.001096899; lr 1e-05; 133s
network 7, training 9, epoch 710: train scaled MSE 0.000278198; val RMSE 0.001096586; lr 1e-05; 135s
network 7, training 9, epoch 720: train scaled MSE 0.000275641; val RMSE 0.00109539; lr 1e-05; 137s
network 7, training 9, epoch 730: train scaled MSE 0.000278748; val RMSE 0.001096334; lr 1e-05; 139s
network 7, training 9, epoch 740: train scaled MSE 0.000293209; val RMSE 0.001099627; lr 1e-05; 141s
network 7, training 9, epoch 750: train scaled MSE 0.000273186; val RMSE 0.001095892; lr 1e-05; 143s
network 7, training 9, epoch 760: train scaled MSE 0.000272743; val RMSE 0.001096758; lr 1e-05; 145s
network 7, training 9, epoch 770: train scaled MSE 0.000271162; val RMSE 0.001095435; lr 1e-05; 147s
network 7, training 9, epoch 780: train scaled MSE 0.00027017; val RMSE 0.001094808; lr 1e-05; 149s
network 7, training 9, epoch 790: train scaled MSE 0.000272354; val RMSE 0.00109515; lr 1e-05; 151s
network 7, training 9, epoch 800: train scaled MSE 0.000271565; val RMSE 0.001095055; lr 1e-05; 153s
network 7, training 9, epoch 810: train scaled MSE 0.000268266; val RMSE 0.001094284; lr 1e-05; 154s
network 7, training 9, epoch 820: train scaled MSE 0.000266769; val RMSE 0.001094528; lr 1e-05; 156s
network 7, training 9, epoch 830: train scaled MSE 0.000266876; val RMSE 0.001094186; lr 1e-05; 158s
network 7, training 9, epoch 840: train scaled MSE 0.000267243; val RMSE 0.001095307; lr 1e-05; 160s
network 7, training 9, epoch 850: train scaled MSE 0.000264914; val RMSE 0.001093433; lr 1e-05; 162s
network 7, training 9, epoch 860: train scaled MSE 0.000265627; val RMSE 0.001094214; lr 1e-05; 164s
network 7, training 9, epoch 870: train scaled MSE 0.000263701; val RMSE 0.00109337; lr 1e-05; 166s
network 7, training 9, epoch 880: train scaled MSE 0.000263149; val RMSE 0.001093586; lr 1e-05; 168s
network 7, training 9, epoch 890: train scaled MSE 0.000261031; val RMSE 0.001093009; lr 1e-05; 170s
network 7, training 9, epoch 900: train scaled MSE 0.000260694; val RMSE 0.001093695; lr 1e-05; 172s
network 7, training 9, epoch 910: train scaled MSE 0.00025985; val RMSE 0.001093637; lr 1e-05; 174s
network 7, training 9, epoch 920: train scaled MSE 0.000279732; val RMSE 0.001095158; lr 1e-05; 176s
network 7, training 9, epoch 930: train scaled MSE 0.000258919; val RMSE 0.001093207; lr 1e-05; 178s
network 7, training 9, epoch 940: train scaled MSE 0.00025704; val RMSE 0.001092916; lr 1e-05; 179s
network 7, training 9, epoch 950: train scaled MSE 0.000255882; val RMSE 0.001092464; lr 1e-05; 181s
network 7, training 9, epoch 960: train scaled MSE 0.000255769; val RMSE 0.001092887; lr 1e-05; 183s
network 7, training 9, epoch 970: train scaled MSE 0.0002546; val RMSE 0.001092246; lr 1e-05; 185s
network 7, training 9, epoch 980: train scaled MSE 0.00025452; val RMSE 0.001092097; lr 1e-05; 187s
network 7, training 9, epoch 990: train scaled MSE 0.00025324; val RMSE 0.001092189; lr 1e-05; 189s
network 7, training 9, epoch 1000: train scaled MSE 0.000252293; val RMSE 0.001091842; lr 1e-05; 191s
network 7, training 9, epoch 1010: train scaled MSE 0.000251112; val RMSE 0.001091657; lr 1e-05; 193s
network 7, training 9, epoch 1020: train scaled MSE 0.00025044; val RMSE 0.001091345; lr 1e-05; 195s
network 7, training 9, epoch 1030: train scaled MSE 0.000249581; val RMSE 0.001090764; lr 1e-05; 197s
network 7, training 9, epoch 1040: train scaled MSE 0.000254761; val RMSE 0.001090923; lr 1e-05; 199s
network 7, training 9, epoch 1050: train scaled MSE 0.000248075; val RMSE 0.001091475; lr 1e-05; 201s
network 7, training 9, epoch 1060: train scaled MSE 0.000247124; val RMSE 0.001090723; lr 1e-05; 202s
network 7, training 9, epoch 1070: train scaled MSE 0.00024618; val RMSE 0.001090831; lr 1e-05; 204s
network 7, training 9, epoch 1080: train scaled MSE 0.000246413; val RMSE 0.001090852; lr 1e-05; 206s
network 7, training 9, epoch 1090: train scaled MSE 0.00025326; val RMSE 0.001092502; lr 1e-05; 208s
network 7, training 9, epoch 1100: train scaled MSE 0.000244047; val RMSE 0.001091134; lr 1e-05; 210s
Standard Linear Baseline Validation RMSE: 0.001343518

Network seed 7, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0021,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0020,0.0653,"[-0.85%, 0.85%]",0.0684,0.0,0.2759
MLP,0.0018,19.8464,"[5.13%, 33.58%]",0.5001,631.3101,0.1078

Network 8: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   21.7s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   21.8s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   21.9s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   22.0s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   22.1s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   22.3s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   22.4s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   22.6s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   22.8s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   23.0s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   23.1s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   23.4s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   23.5s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   23.7s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   23.9s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   24.1s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   24.3s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   24.4s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   24.8s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   25.0s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   25.1s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   25.4s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   25.7s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   25.9s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   26.2s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   26.5s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   26.8s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   27.1s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   27.4s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   27.6s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   28.3s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   28.5s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   29.0s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   29.3s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   29.7s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   30.0s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   30.4s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   30.8s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   31.2s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   31.6s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   32.0s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   32.3s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   32.8s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   33.2s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   33.6s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   34.0s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   34.4s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   34.9s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   35.3s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   35.8s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   36.2s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   36.7s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   37.2s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   37.7s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   38.2s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   38.7s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   39.2s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   39.7s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   40.3s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   40.8s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   41.4s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   41.9s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   42.5s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   43.1s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   43.6s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   44.2s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   44.8s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   45.4s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   46.0s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   46.6s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   47.3s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   47.9s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   48.6s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   49.2s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   49.9s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   50.5s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   51.2s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   52.0s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   52.7s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   53.6s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   54.3s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   55.0s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   55.6s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:   56.3s
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:   57.1s
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:   57.7s
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:   58.5s
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:   59.2s
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.5min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.5min finished

network 8, training 0, epoch 1: train scaled MSE 0.786657; val RMSE 0.02228062; lr 0.001; 0s
network 8, training 0, epoch 10: train scaled MSE 0.0417749; val RMSE 0.01114822; lr 0.001; 2s
network 8, training 0, epoch 20: train scaled MSE 0.0160366; val RMSE 0.005966978; lr 0.001; 4s
network 8, training 0, epoch 30: train scaled MSE 0.00994371; val RMSE 0.005164845; lr 0.001; 6s
network 8, training 0, epoch 40: train scaled MSE 0.00783033; val RMSE 0.005269539; lr 0.001; 8s
network 8, training 0, epoch 50: train scaled MSE 0.00427678; val RMSE 0.00499653; lr 0.0005; 10s
network 8, training 0, epoch 60: train scaled MSE 0.00367189; val RMSE 0.004975776; lr 0.0005; 12s
network 8, training 0, epoch 70: train scaled MSE 0.00292932; val RMSE 0.004979991; lr 0.00025; 14s
network 8, training 0, epoch 80: train scaled MSE 0.00263129; val RMSE 0.004986964; lr 0.000125; 15s
network 8, training 0, epoch 90: train scaled MSE 0.00246987; val RMSE 0.00499266; lr 6.25e-05; 17s
Standard Linear Baseline Validation RMSE: 0.006982739

Network seed 8, training seed 0

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0053,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0053,1.1931,"[-5.92%, 4.88%]",0.1756,0.0,0.0237
MLP,0.0043,34.0882,"[10.91%, 51.03%]",0.5972,240.0866,0.0094

network 8, training 1, epoch 1: train scaled MSE 0.768817; val RMSE 0.02152624; lr 0.001; 0s
network 8, training 1, epoch 10: train scaled MSE 0.0342377; val RMSE 0.00851277; lr 0.001; 2s
network 8, training 1, epoch 20: train scaled MSE 0.0129351; val RMSE 0.006931782; lr 0.001; 4s
network 8, training 1, epoch 30: train scaled MSE 0.0087861; val RMSE 0.007537385; lr 0.001; 6s
network 8, training 1, epoch 40: train scaled MSE 0.00594259; val RMSE 0.006854127; lr 0.001; 8s
network 8, training 1, epoch 50: train scaled MSE 0.01023; val RMSE 0.006641869; lr 0.0005; 10s
network 8, training 1, epoch 60: train scaled MSE 0.00343598; val RMSE 0.006550505; lr 0.00025; 12s
network 8, training 1, epoch 70: train scaled MSE 0.00299432; val RMSE 0.006632447; lr 0.00025; 14s
network 8, training 1, epoch 80: train scaled MSE 0.00266832; val RMSE 0.006571428; lr 0.000125; 16s
network 8, training 1, epoch 90: train scaled MSE 0.00252866; val RMSE 0.006594463; lr 6.25e-05; 18s
network 8, training 1, epoch 100: train scaled MSE 0.00243174; val RMSE 0.00661647; lr 3.125e-05; 20s
Standard Linear Baseline Validation RMSE: 0.00632203

Network seed 8, training seed 1

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0049,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0049,-3.5427,"[-15.48%, 2.09%]",0.1446,0.0,0.0164
MLP,0.0041,29.3503,"[-13.17%, 53.43%]",0.6006,315.3788,0.0086

network 8, training 2, epoch 1: train scaled MSE 0.766399; val RMSE 0.02218779; lr 0.001; 0s
network 8, training 2, epoch 10: train scaled MSE 0.0316267; val RMSE 0.006622475; lr 0.001; 2s
network 8, training 2, epoch 20: train scaled MSE 0.0102181; val RMSE 0.00615014; lr 0.001; 4s
network 8, training 2, epoch 30: train scaled MSE 0.00606011; val RMSE 0.006017554; lr 0.0005; 7s
network 8, training 2, epoch 40: train scaled MSE 0.00521607; val RMSE 0.005992523; lr 0.0005; 9s
network 8, training 2, epoch 50: train scaled MSE 0.00416738; val RMSE 0.006017689; lr 0.0005; 11s
network 8, training 2, epoch 60: train scaled MSE 0.00357246; val RMSE 0.006164141; lr 0.0005; 13s
network 8, training 2, epoch 70: train scaled MSE 0.00274908; val RMSE 0.005955537; lr 0.00025; 15s
network 8, training 2, epoch 80: train scaled MSE 0.00253252; val RMSE 0.00590891; lr 0.00025; 17s
network 8, training 2, epoch 90: train scaled MSE 0.00231654; val RMSE 0.005815253; lr 0.00025; 19s
network 8, training 2, epoch 100: train scaled MSE 0.00209242; val RMSE 0.005763259; lr 0.00025; 21s
network 8, training 2, epoch 110: train scaled MSE 0.00205237; val RMSE 0.005723536; lr 0.00025; 23s
network 8, training 2, epoch 120: train scaled MSE 0.00180565; val RMSE 0.005677698; lr 0.00025; 25s
network 8, training 2, epoch 130: train scaled MSE 0.00165221; val RMSE 0.005635838; lr 0.00025; 27s
network 8, training 2, epoch 140: train scaled MSE 0.00167937; val RMSE 0.005642797; lr 0.00025; 29s
network 8, training 2, epoch 150: train scaled MSE 0.0021206; val RMSE 0.005623579; lr 0.00025; 31s
network 8, training 2, epoch 160: train scaled MSE 0.00127365; val RMSE 0.005563067; lr 0.00025; 33s
network 8, training 2, epoch 170: train scaled MSE 0.00114156; val RMSE 0.005566688; lr 0.00025; 35s
network 8, training 2, epoch 180: train scaled MSE 0.00103618; val RMSE 0.005523628; lr 0.000125; 37s
network 8, training 2, epoch 190: train scaled MSE 0.000999951; val RMSE 0.005537149; lr 0.000125; 39s
network 8, training 2, epoch 200: train scaled MSE 0.000940763; val RMSE 0.005528469; lr 6.25e-05; 41s
network 8, training 2, epoch 210: train scaled MSE 0.000913202; val RMSE 0.00553063; lr 3.125e-05; 43s
Standard Linear Baseline Validation RMSE: 0.004747626

Network seed 8, training seed 2

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0062,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0060,4.5259,"[1.43%, 6.55%]",0.2127,0.0,0.0176
MLP,0.0060,5.5316,"[-53.38%, 48.32%]",0.4618,117.0587,0.0124

network 8, training 3, epoch 1: train scaled MSE 0.770865; val RMSE 0.02008328; lr 0.001; 0s
network 8, training 3, epoch 10: train scaled MSE 0.0399169; val RMSE 0.008599808; lr 0.001; 2s
network 8, training 3, epoch 20: train scaled MSE 0.0146382; val RMSE 0.006704502; lr 0.001; 4s
network 8, training 3, epoch 30: train scaled MSE 0.00822807; val RMSE 0.005936806; lr 0.001; 6s
network 8, training 3, epoch 40: train scaled MSE 0.00542244; val RMSE 0.005218508; lr 0.001; 8s
network 8, training 3, epoch 50: train scaled MSE 0.00491634; val RMSE 0.005019123; lr 0.001; 10s
network 8, training 3, epoch 60: train scaled MSE 0.00406731; val RMSE 0.004973934; lr 0.001; 12s
network 8, training 3, epoch 70: train scaled MSE 0.00261432; val RMSE 0.004941999; lr 0.001; 13s
network 8, training 3, epoch 80: train scaled MSE 0.00193963; val RMSE 0.004906001; lr 0.001; 15s
network 8, training 3, epoch 90: train scaled MSE 0.0024497; val RMSE 0.004903425; lr 0.001; 17s
network 8, training 3, epoch 100: train scaled MSE 0.00127219; val RMSE 0.004956413; lr 0.0005; 19s
network 8, training 3, epoch 110: train scaled MSE 0.00109527; val RMSE 0.00486212; lr 0.00025; 21s
network 8, training 3, epoch 120: train scaled MSE 0.000987477; val RMSE 0.004830323; lr 0.00025; 23s
network 8, training 3, epoch 130: train scaled MSE 0.000917835; val RMSE 0.004803892; lr 0.00025; 25s
network 8, training 3, epoch 140: train scaled MSE 0.000862716; val RMSE 0.004811788; lr 0.00025; 27s
network 8, training 3, epoch 150: train scaled MSE 0.000800394; val RMSE 0.004776832; lr 0.00025; 29s
network 8, training 3, epoch 160: train scaled MSE 0.000760871; val RMSE 0.004756742; lr 0.00025; 31s
network 8, training 3, epoch 170: train scaled MSE 0.0008355; val RMSE 0.004744877; lr 0.00025; 33s
network 8, training 3, epoch 180: train scaled MSE 0.000683293; val RMSE 0.004755297; lr 0.00025; 35s
network 8, training 3, epoch 190: train scaled MSE 0.000747161; val RMSE 0.004740709; lr 0.00025; 37s
network 8, training 3, epoch 200: train scaled MSE 0.0005438; val RMSE 0.004722741; lr 0.000125; 39s
network 8, training 3, epoch 210: train scaled MSE 0.000607211; val RMSE 0.004728641; lr 0.000125; 41s
network 8, training 3, epoch 220: train scaled MSE 0.000504628; val RMSE 0.00471376; lr 0.000125; 43s
network 8, training 3, epoch 230: train scaled MSE 0.000476796; val RMSE 0.004710246; lr 6.25e-05; 44s
network 8, training 3, epoch 240: train scaled MSE 0.00053587; val RMSE 0.004709313; lr 3.125e-05; 46s
network 8, training 3, epoch 250: train scaled MSE 0.000462092; val RMSE 0.004703488; lr 3.125e-05; 48s
network 8, training 3, epoch 260: train scaled MSE 0.000446641; val RMSE 0.004705134; lr 1.5625e-05; 50s
network 8, training 3, epoch 270: train scaled MSE 0.000443647; val RMSE 0.004705648; lr 1e-05; 52s
Standard Linear Baseline Validation RMSE: 0.006958522

Network seed 8, training seed 3

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0063,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0062,2.8033,"[-0.47%, 4.63%]",0.1701,0.0,0.0297
MLP,0.0047,43.5889,"[34.99%, 51.18%]",0.7052,314.59,0.0142

network 8, training 4, epoch 1: train scaled MSE 0.776521; val RMSE 0.0213095; lr 0.001; 0s
network 8, training 4, epoch 10: train scaled MSE 0.031577; val RMSE 0.006785569; lr 0.001; 2s
network 8, training 4, epoch 20: train scaled MSE 0.0168666; val RMSE 0.004683212; lr 0.001; 4s
network 8, training 4, epoch 30: train scaled MSE 0.0080757; val RMSE 0.004612386; lr 0.001; 6s
network 8, training 4, epoch 40: train scaled MSE 0.00619146; val RMSE 0.003806136; lr 0.001; 8s
network 8, training 4, epoch 50: train scaled MSE 0.00420113; val RMSE 0.003343146; lr 0.001; 10s
network 8, training 4, epoch 60: train scaled MSE 0.0043128; val RMSE 0.003309218; lr 0.001; 12s
network 8, training 4, epoch 70: train scaled MSE 0.00249293; val RMSE 0.003064572; lr 0.001; 14s
network 8, training 4, epoch 80: train scaled MSE 0.00186715; val RMSE 0.003003499; lr 0.001; 16s
network 8, training 4, epoch 90: train scaled MSE 0.00129368; val RMSE 0.002951367; lr 0.0005; 18s
network 8, training 4, epoch 100: train scaled MSE 0.00151401; val RMSE 0.002983082; lr 0.0005; 19s
network 8, training 4, epoch 110: train scaled MSE 0.00099021; val RMSE 0.002887947; lr 0.00025; 21s
network 8, training 4, epoch 120: train scaled MSE 0.000907292; val RMSE 0.002877411; lr 0.00025; 23s
network 8, training 4, epoch 130: train scaled MSE 0.000858573; val RMSE 0.00302966; lr 0.00025; 25s
network 8, training 4, epoch 140: train scaled MSE 0.000780065; val RMSE 0.002877693; lr 0.000125; 27s
network 8, training 4, epoch 150: train scaled MSE 0.000766131; val RMSE 0.002887321; lr 0.000125; 29s
network 8, training 4, epoch 160: train scaled MSE 0.000718673; val RMSE 0.002873342; lr 6.25e-05; 31s
network 8, training 4, epoch 170: train scaled MSE 0.000703492; val RMSE 0.002871113; lr 6.25e-05; 33s
network 8, training 4, epoch 180: train scaled MSE 0.000684701; val RMSE 0.002869025; lr 6.25e-05; 34s
network 8, training 4, epoch 190: train scaled MSE 0.000668783; val RMSE 0.002865369; lr 6.25e-05; 36s
network 8, training 4, epoch 200: train scaled MSE 0.000653607; val RMSE 0.002865986; lr 6.25e-05; 38s
network 8, training 4, epoch 210: train scaled MSE 0.000638323; val RMSE 0.002863721; lr 6.25e-05; 40s
network 8, training 4, epoch 220: train scaled MSE 0.000620508; val RMSE 0.002850299; lr 6.25e-05; 42s
network 8, training 4, epoch 230: train scaled MSE 0.000601793; val RMSE 0.00284794; lr 6.25e-05; 44s
network 8, training 4, epoch 240: train scaled MSE 0.000585259; val RMSE 0.00284637; lr 6.25e-05; 46s
network 8, training 4, epoch 250: train scaled MSE 0.000567042; val RMSE 0.002840757; lr 3.125e-05; 48s
network 8, training 4, epoch 260: train scaled MSE 0.00055906; val RMSE 0.002844424; lr 1.5625e-05; 50s
network 8, training 4, epoch 270: train scaled MSE 0.000548173; val RMSE 0.002842964; lr 1e-05; 52s
Standard Linear Baseline Validation RMSE: 0.005966533

Network seed 8, training seed 4

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0060,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0059,2.7635,"[-3.15%, 5.81%]",0.1841,0.0,0.0327
MLP,0.0043,48.1773,"[32.56%, 60.46%]",0.6972,278.7467,0.0134

network 8, training 5, epoch 1: train scaled MSE 0.776097; val RMSE 0.02160345; lr 0.001; 0s
network 8, training 5, epoch 10: train scaled MSE 0.0379609; val RMSE 0.006806357; lr 0.001; 2s
network 8, training 5, epoch 20: train scaled MSE 0.014207; val RMSE 0.00620343; lr 0.001; 4s
network 8, training 5, epoch 30: train scaled MSE 0.00902099; val RMSE 0.006359476; lr 0.001; 6s
network 8, training 5, epoch 40: train scaled MSE 0.00625778; val RMSE 0.005587067; lr 0.0005; 8s
network 8, training 5, epoch 50: train scaled MSE 0.0051725; val RMSE 0.005481894; lr 0.00025; 10s
network 8, training 5, epoch 60: train scaled MSE 0.00544673; val RMSE 0.00548203; lr 0.00025; 12s
network 8, training 5, epoch 70: train scaled MSE 0.00693468; val RMSE 0.005442895; lr 0.00025; 13s
network 8, training 5, epoch 80: train scaled MSE 0.00435969; val RMSE 0.005342429; lr 0.00025; 15s
network 8, training 5, epoch 90: train scaled MSE 0.00401064; val RMSE 0.005273327; lr 0.00025; 17s
network 8, training 5, epoch 100: train scaled MSE 0.00379269; val RMSE 0.005193406; lr 0.00025; 19s
network 8, training 5, epoch 110: train scaled MSE 0.00316662; val RMSE 0.005117773; lr 0.00025; 21s
network 8, training 5, epoch 120: train scaled MSE 0.00298072; val RMSE 0.005040892; lr 0.00025; 23s
network 8, training 5, epoch 130: train scaled MSE 0.00259197; val RMSE 0.004945771; lr 0.00025; 25s
network 8, training 5, epoch 140: train scaled MSE 0.00249125; val RMSE 0.004894761; lr 0.00025; 27s
network 8, training 5, epoch 150: train scaled MSE 0.00218454; val RMSE 0.004798261; lr 0.00025; 29s
network 8, training 5, epoch 160: train scaled MSE 0.0019311; val RMSE 0.004767532; lr 0.00025; 31s
network 8, training 5, epoch 170: train scaled MSE 0.00175259; val RMSE 0.004722847; lr 0.00025; 33s
network 8, training 5, epoch 180: train scaled MSE 0.00156488; val RMSE 0.004690934; lr 0.00025; 35s
network 8, training 5, epoch 190: train scaled MSE 0.00143733; val RMSE 0.004643096; lr 0.00025; 37s
network 8, training 5, epoch 200: train scaled MSE 0.00128436; val RMSE 0.004613997; lr 0.00025; 39s
network 8, training 5, epoch 210: train scaled MSE 0.00120091; val RMSE 0.004589274; lr 0.00025; 41s
network 8, training 5, epoch 220: train scaled MSE 0.00107503; val RMSE 0.004631488; lr 0.00025; 43s
network 8, training 5, epoch 230: train scaled MSE 0.00109227; val RMSE 0.00452704; lr 0.00025; 45s
network 8, training 5, epoch 240: train scaled MSE 0.000947294; val RMSE 0.004490937; lr 0.00025; 47s
network 8, training 5, epoch 250: train scaled MSE 0.000916908; val RMSE 0.004457242; lr 0.00025; 49s
network 8, training 5, epoch 260: train scaled MSE 0.000843413; val RMSE 0.004441187; lr 0.00025; 50s
network 8, training 5, epoch 270: train scaled MSE 0.000784537; val RMSE 0.004421316; lr 0.00025; 52s
network 8, training 5, epoch 280: train scaled MSE 0.000828446; val RMSE 0.004398497; lr 0.00025; 54s
network 8, training 5, epoch 290: train scaled MSE 0.000702123; val RMSE 0.004402041; lr 0.00025; 56s
network 8, training 5, epoch 300: train scaled MSE 0.00069059; val RMSE 0.004371383; lr 0.00025; 58s
network 8, training 5, epoch 310: train scaled MSE 0.000630851; val RMSE 0.004338649; lr 0.00025; 60s
network 8, training 5, epoch 320: train scaled MSE 0.000625443; val RMSE 0.004343279; lr 0.00025; 62s
network 8, training 5, epoch 330: train scaled MSE 0.000596245; val RMSE 0.004372242; lr 0.00025; 64s
network 8, training 5, epoch 340: train scaled MSE 0.000699876; val RMSE 0.004310563; lr 0.00025; 66s
network 8, training 5, epoch 350: train scaled MSE 0.000519729; val RMSE 0.004304191; lr 0.00025; 68s
network 8, training 5, epoch 360: train scaled MSE 0.000553479; val RMSE 0.004283077; lr 0.00025; 70s
network 8, training 5, epoch 370: train scaled MSE 0.000478568; val RMSE 0.004280424; lr 0.00025; 72s
network 8, training 5, epoch 380: train scaled MSE 0.000497705; val RMSE 0.004247748; lr 0.00025; 74s
network 8, training 5, epoch 390: train scaled MSE 0.000545389; val RMSE 0.004309338; lr 0.00025; 76s
network 8, training 5, epoch 400: train scaled MSE 0.000384038; val RMSE 0.00423006; lr 0.000125; 78s
network 8, training 5, epoch 410: train scaled MSE 0.000350806; val RMSE 0.004221571; lr 0.000125; 80s
network 8, training 5, epoch 420: train scaled MSE 0.00038894; val RMSE 0.004234178; lr 0.000125; 82s
network 8, training 5, epoch 430: train scaled MSE 0.000334998; val RMSE 0.004227595; lr 6.25e-05; 84s
network 8, training 5, epoch 440: train scaled MSE 0.000321733; val RMSE 0.004224589; lr 3.125e-05; 86s
network 8, training 5, epoch 450: train scaled MSE 0.000317203; val RMSE 0.004222991; lr 1.5625e-05; 88s
Standard Linear Baseline Validation RMSE: 0.005922725

Network seed 8, training seed 5

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0054,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0053,1.4009,"[-5.77%, 5.18%]",0.1805,0.0,0.0195
MLP,0.0038,50.9226,"[23.24%, 67.47%]",0.7157,296.4819,0.0142

network 8, training 6, epoch 1: train scaled MSE 0.77094; val RMSE 0.02202279; lr 0.001; 0s
network 8, training 6, epoch 10: train scaled MSE 0.0351918; val RMSE 0.008394249; lr 0.001; 2s
network 8, training 6, epoch 20: train scaled MSE 0.0131383; val RMSE 0.006847725; lr 0.001; 4s
network 8, training 6, epoch 30: train scaled MSE 0.00974615; val RMSE 0.00697837; lr 0.001; 6s
network 8, training 6, epoch 40: train scaled MSE 0.00824748; val RMSE 0.006248077; lr 0.001; 8s
network 8, training 6, epoch 50: train scaled MSE 0.00489937; val RMSE 0.005888064; lr 0.001; 10s
network 8, training 6, epoch 60: train scaled MSE 0.00367034; val RMSE 0.0059431; lr 0.001; 12s
network 8, training 6, epoch 70: train scaled MSE 0.00261831; val RMSE 0.005877814; lr 0.001; 14s
network 8, training 6, epoch 80: train scaled MSE 0.00191592; val RMSE 0.005752413; lr 0.001; 16s
network 8, training 6, epoch 90: train scaled MSE 0.00170151; val RMSE 0.005998665; lr 0.001; 18s
network 8, training 6, epoch 100: train scaled MSE 0.00124277; val RMSE 0.005551075; lr 0.001; 20s
network 8, training 6, epoch 110: train scaled MSE 0.00096025; val RMSE 0.005502281; lr 0.0005; 22s
network 8, training 6, epoch 120: train scaled MSE 0.00090769; val RMSE 0.005503593; lr 0.0005; 24s
network 8, training 6, epoch 130: train scaled MSE 0.000719584; val RMSE 0.005495875; lr 0.00025; 26s
network 8, training 6, epoch 140: train scaled MSE 0.000655592; val RMSE 0.005522344; lr 0.000125; 28s
network 8, training 6, epoch 150: train scaled MSE 0.000622743; val RMSE 0.005547534; lr 0.000125; 30s
Standard Linear Baseline Validation RMSE: 0.0077893

Network seed 8, training seed 6

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0051,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0051,0.3550,"[-6.32%, 3.75%]",0.1593,0.0,0.0194
MLP,0.0037,46.6764,"[31.83%, 59.18%]",0.6842,329.3982,0.0104

network 8, training 7, epoch 1: train scaled MSE 0.764114; val RMSE 0.02105868; lr 0.001; 0s
network 8, training 7, epoch 10: train scaled MSE 0.034624; val RMSE 0.007492099; lr 0.001; 2s
network 8, training 7, epoch 20: train scaled MSE 0.0143134; val RMSE 0.006635933; lr 0.001; 4s
network 8, training 7, epoch 30: train scaled MSE 0.00914454; val RMSE 0.006480329; lr 0.001; 6s
network 8, training 7, epoch 40: train scaled MSE 0.00590876; val RMSE 0.006144631; lr 0.001; 8s
network 8, training 7, epoch 50: train scaled MSE 0.0040667; val RMSE 0.006214285; lr 0.001; 10s
network 8, training 7, epoch 60: train scaled MSE 0.00316073; val RMSE 0.006027483; lr 0.001; 12s
network 8, training 7, epoch 70: train scaled MSE 0.00239301; val RMSE 0.005721523; lr 0.001; 14s
network 8, training 7, epoch 80: train scaled MSE 0.00213568; val RMSE 0.005799852; lr 0.001; 16s
network 8, training 7, epoch 90: train scaled MSE 0.00632748; val RMSE 0.005927121; lr 0.001; 18s
network 8, training 7, epoch 100: train scaled MSE 0.00176542; val RMSE 0.00547854; lr 0.001; 20s
network 8, training 7, epoch 110: train scaled MSE 0.00106414; val RMSE 0.005935597; lr 0.001; 22s
network 8, training 7, epoch 120: train scaled MSE 0.001094; val RMSE 0.005664706; lr 0.001; 24s
network 8, training 7, epoch 130: train scaled MSE 0.00118156; val RMSE 0.005440051; lr 0.001; 26s
network 8, training 7, epoch 140: train scaled MSE 0.000852919; val RMSE 0.005147451; lr 0.001; 28s
network 8, training 7, epoch 150: train scaled MSE 0.0233128; val RMSE 0.005208693; lr 0.001; 30s
network 8, training 7, epoch 160: train scaled MSE 0.00151862; val RMSE 0.004992821; lr 0.001; 32s
network 8, training 7, epoch 170: train scaled MSE 0.000590257; val RMSE 0.004965109; lr 0.001; 34s
network 8, training 7, epoch 180: train scaled MSE 0.000533211; val RMSE 0.00537896; lr 0.001; 36s
network 8, training 7, epoch 190: train scaled MSE 0.000819083; val RMSE 0.004990787; lr 0.001; 38s
network 8, training 7, epoch 200: train scaled MSE 0.00057967; val RMSE 0.00486625; lr 0.001; 40s
network 8, training 7, epoch 210: train scaled MSE 0.000709559; val RMSE 0.004824694; lr 0.001; 42s
network 8, training 7, epoch 220: train scaled MSE 0.00274997; val RMSE 0.005407347; lr 0.001; 44s
network 8, training 7, epoch 230: train scaled MSE 0.000389325; val RMSE 0.004722894; lr 0.001; 46s
network 8, training 7, epoch 240: train scaled MSE 0.00037179; val RMSE 0.004683305; lr 0.0005; 48s
network 8, training 7, epoch 250: train scaled MSE 0.000264955; val RMSE 0.004688139; lr 0.0005; 50s
network 8, training 7, epoch 260: train scaled MSE 0.000394426; val RMSE 0.004708877; lr 0.0005; 52s
network 8, training 7, epoch 270: train scaled MSE 0.000331672; val RMSE 0.004696745; lr 0.00025; 54s
network 8, training 7, epoch 280: train scaled MSE 0.000190995; val RMSE 0.004697617; lr 0.000125; 56s
Standard Linear Baseline Validation RMSE: 0.005578912

Network seed 8, training seed 7

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0049,0.0000,-,0.0000,-,0.0000
Linear Regression,0.0050,-3.2474,"[-15.25%, 2.66%]",0.1533,0.0,0.0148
MLP,0.0033,56.1946,"[29.83%, 71.65%]",0.7526,390.9056,0.0106

network 8, training 8, epoch 1: train scaled MSE 0.760606; val RMSE 0.02094705; lr 0.001; 0s
network 8, training 8, epoch 10: train scaled MSE 0.0324847; val RMSE 0.006483722; lr 0.001; 2s
network 8, training 8, epoch 20: train scaled MSE 0.0119437; val RMSE 0.005524693; lr 0.001; 4s
network 8, training 8, epoch 30: train scaled MSE 0.00772028; val RMSE 0.005597125; lr 0.001; 6s
network 8, training 8, epoch 40: train scaled MSE 0.00549772; val RMSE 0.005463966; lr 0.0005; 8s
network 8, training 8, epoch 50: train scaled MSE 0.00431235; val RMSE 0.005421935; lr 0.00025; 10s
network 8, training 8, epoch 60: train scaled MSE 0.00386485; val RMSE 0.005471171; lr 0.000125; 12s
network 8, training 8, epoch 70: train scaled MSE 0.00353148; val RMSE 0.005447328; lr 0.000125; 13s
Standard Linear Baseline Validation RMSE: 0.004777453

Network seed 8, training seed 8

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0063,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0062,3.4132,"[-0.44%, 5.38%]",0.1882,0.0,0.0196
MLP,0.0050,36.1064,"[11.98%, 53.73%]",0.6025,220.0602,0.0084

network 8, training 9, epoch 1: train scaled MSE 0.771948; val RMSE 0.02175109; lr 0.001; 0s
network 8, training 9, epoch 10: train scaled MSE 0.0492525; val RMSE 0.00667723; lr 0.001; 2s
network 8, training 9, epoch 20: train scaled MSE 0.0168048; val RMSE 0.004573577; lr 0.001; 4s
network 8, training 9, epoch 30: train scaled MSE 0.0103382; val RMSE 0.004134892; lr 0.001; 6s
network 8, training 9, epoch 40: train scaled MSE 0.00923047; val RMSE 0.00384576; lr 0.001; 8s
network 8, training 9, epoch 50: train scaled MSE 0.00540622; val RMSE 0.003582125; lr 0.001; 10s
network 8, training 9, epoch 60: train scaled MSE 0.00368996; val RMSE 0.00343319; lr 0.001; 12s
network 8, training 9, epoch 70: train scaled MSE 0.0029386; val RMSE 0.003301023; lr 0.001; 14s
network 8, training 9, epoch 80: train scaled MSE 0.00248698; val RMSE 0.003234541; lr 0.001; 16s
network 8, training 9, epoch 90: train scaled MSE 0.00200359; val RMSE 0.003247202; lr 0.001; 17s
network 8, training 9, epoch 100: train scaled MSE 0.00155342; val RMSE 0.003152591; lr 0.001; 19s
network 8, training 9, epoch 110: train scaled MSE 0.00129386; val RMSE 0.003312175; lr 0.001; 21s
network 8, training 9, epoch 120: train scaled MSE 0.00095618; val RMSE 0.003153183; lr 0.0005; 23s
network 8, training 9, epoch 130: train scaled MSE 0.00160163; val RMSE 0.003222246; lr 0.0005; 25s
network 8, training 9, epoch 140: train scaled MSE 0.000818137; val RMSE 0.003159302; lr 0.0005; 27s
network 8, training 9, epoch 150: train scaled MSE 0.000693462; val RMSE 0.003122589; lr 0.00025; 29s
network 8, training 9, epoch 160: train scaled MSE 0.000689345; val RMSE 0.003118991; lr 0.000125; 31s
Standard Linear Baseline Validation RMSE: 0.004624887

Network seed 8, training seed 9

,RMSE,MSE Improvement vs Additive (%),MSE Improv. 95% CI,Pearson (Implied vs True Residual),Pearson Improv. vs Linear (%),Fraction Pairs < Additive MSE
Model,,,,,,
Additive Baseline,0.0055,-0.0000,-,0.0000,-,0.0000
Linear Regression,0.0055,0.8785,"[-7.93%, 5.04%]",0.1813,0.0,0.0221
MLP,0.0040,48.1078,"[34.02%, 58.84%]",0.6950,283.2296,0.0119

Network 9: single-gene KOs:   0%|          | 0/256 [00:00<?, ?it/s]

[Parallel(n_jobs=64)]: Using backend LokyBackend with 64 concurrent workers.
[Parallel(n_jobs=64)]: Done   8 tasks      | elapsed:   27.2s
[Parallel(n_jobs=64)]: Done  21 tasks      | elapsed:   27.2s
[Parallel(n_jobs=64)]: Done  34 tasks      | elapsed:   27.4s
[Parallel(n_jobs=64)]: Done  49 tasks      | elapsed:   27.5s
[Parallel(n_jobs=64)]: Done  64 tasks      | elapsed:   27.6s
[Parallel(n_jobs=64)]: Done  81 tasks      | elapsed:   27.9s
[Parallel(n_jobs=64)]: Done  98 tasks      | elapsed:   28.0s
[Parallel(n_jobs=64)]: Done 117 tasks      | elapsed:   28.1s
[Parallel(n_jobs=64)]: Done 136 tasks      | elapsed:   28.2s
[Parallel(n_jobs=64)]: Done 157 tasks      | elapsed:   28.5s
[Parallel(n_jobs=64)]: Done 178 tasks      | elapsed:   28.7s
[Parallel(n_jobs=64)]: Done 201 tasks      | elapsed:   28.8s
[Parallel(n_jobs=64)]: Done 224 tasks      | elapsed:   29.1s
[Parallel(n_jobs=64)]: Done 249 tasks      | elapsed:   29.3s
[Parallel(n_jobs=64)]: Done 274 tasks      | elapsed:   29.4s
[Parallel(n_jobs=64)]: Done 301 tasks      | elapsed:   29.6s
[Parallel(n_jobs=64)]: Done 328 tasks      | elapsed:   29.8s
[Parallel(n_jobs=64)]: Done 357 tasks      | elapsed:   30.1s
[Parallel(n_jobs=64)]: Done 386 tasks      | elapsed:   30.3s
[Parallel(n_jobs=64)]: Done 417 tasks      | elapsed:   30.6s
[Parallel(n_jobs=64)]: Done 448 tasks      | elapsed:   30.8s
[Parallel(n_jobs=64)]: Done 481 tasks      | elapsed:   31.1s
[Parallel(n_jobs=64)]: Done 514 tasks      | elapsed:   31.3s
[Parallel(n_jobs=64)]: Done 549 tasks      | elapsed:   31.6s
[Parallel(n_jobs=64)]: Done 584 tasks      | elapsed:   31.9s
[Parallel(n_jobs=64)]: Done 621 tasks      | elapsed:   32.1s
[Parallel(n_jobs=64)]: Done 658 tasks      | elapsed:   32.4s
[Parallel(n_jobs=64)]: Done 697 tasks      | elapsed:   32.7s
[Parallel(n_jobs=64)]: Done 736 tasks      | elapsed:   33.0s
[Parallel(n_jobs=64)]: Done 777 tasks      | elapsed:   33.3s
[Parallel(n_jobs=64)]: Done 818 tasks      | elapsed:   33.6s
[Parallel(n_jobs=64)]: Done 861 tasks      | elapsed:   33.9s
[Parallel(n_jobs=64)]: Done 904 tasks      | elapsed:   34.2s
[Parallel(n_jobs=64)]: Done 949 tasks      | elapsed:   34.5s
[Parallel(n_jobs=64)]: Done 994 tasks      | elapsed:   34.8s
[Parallel(n_jobs=64)]: Done 1041 tasks      | elapsed:   35.2s
[Parallel(n_jobs=64)]: Done 1088 tasks      | elapsed:   35.5s
[Parallel(n_jobs=64)]: Done 1137 tasks      | elapsed:   35.9s
[Parallel(n_jobs=64)]: Done 1186 tasks      | elapsed:   36.2s
[Parallel(n_jobs=64)]: Done 1237 tasks      | elapsed:   36.5s
[Parallel(n_jobs=64)]: Done 1288 tasks      | elapsed:   37.0s
[Parallel(n_jobs=64)]: Done 1341 tasks      | elapsed:   37.4s
[Parallel(n_jobs=64)]: Done 1394 tasks      | elapsed:   37.7s
[Parallel(n_jobs=64)]: Done 1449 tasks      | elapsed:   38.1s
[Parallel(n_jobs=64)]: Done 1504 tasks      | elapsed:   38.5s
[Parallel(n_jobs=64)]: Done 1561 tasks      | elapsed:   38.9s
[Parallel(n_jobs=64)]: Done 1618 tasks      | elapsed:   39.3s
[Parallel(n_jobs=64)]: Done 1677 tasks      | elapsed:   39.7s
[Parallel(n_jobs=64)]: Done 1736 tasks      | elapsed:   40.1s
[Parallel(n_jobs=64)]: Done 1797 tasks      | elapsed:   40.6s
[Parallel(n_jobs=64)]: Done 1858 tasks      | elapsed:   41.0s
[Parallel(n_jobs=64)]: Done 1921 tasks      | elapsed:   41.5s
[Parallel(n_jobs=64)]: Done 1984 tasks      | elapsed:   42.0s
[Parallel(n_jobs=64)]: Done 2049 tasks      | elapsed:   42.4s
[Parallel(n_jobs=64)]: Done 2114 tasks      | elapsed:   42.9s
[Parallel(n_jobs=64)]: Done 2181 tasks      | elapsed:   43.4s
[Parallel(n_jobs=64)]: Done 2248 tasks      | elapsed:   43.9s
[Parallel(n_jobs=64)]: Done 2317 tasks      | elapsed:   44.4s
[Parallel(n_jobs=64)]: Done 2386 tasks      | elapsed:   44.9s
[Parallel(n_jobs=64)]: Done 2457 tasks      | elapsed:   45.4s
[Parallel(n_jobs=64)]: Done 2528 tasks      | elapsed:   45.9s
[Parallel(n_jobs=64)]: Done 2601 tasks      | elapsed:   46.4s
[Parallel(n_jobs=64)]: Done 2674 tasks      | elapsed:   47.0s
[Parallel(n_jobs=64)]: Done 2749 tasks      | elapsed:   47.6s
[Parallel(n_jobs=64)]: Done 2824 tasks      | elapsed:   48.2s
[Parallel(n_jobs=64)]: Done 2901 tasks      | elapsed:   48.7s
[Parallel(n_jobs=64)]: Done 2978 tasks      | elapsed:   49.3s
[Parallel(n_jobs=64)]: Done 3057 tasks      | elapsed:   49.9s
[Parallel(n_jobs=64)]: Done 3136 tasks      | elapsed:   50.5s
[Parallel(n_jobs=64)]: Done 3217 tasks      | elapsed:   51.0s
[Parallel(n_jobs=64)]: Done 3298 tasks      | elapsed:   51.6s
[Parallel(n_jobs=64)]: Done 3381 tasks      | elapsed:   52.2s
[Parallel(n_jobs=64)]: Done 3464 tasks      | elapsed:   52.8s
[Parallel(n_jobs=64)]: Done 3549 tasks      | elapsed:   53.3s
[Parallel(n_jobs=64)]: Done 3634 tasks      | elapsed:   53.9s
[Parallel(n_jobs=64)]: Done 3721 tasks      | elapsed:   54.5s
[Parallel(n_jobs=64)]: Done 3808 tasks      | elapsed:   55.1s
[Parallel(n_jobs=64)]: Done 3897 tasks      | elapsed:   55.7s
[Parallel(n_jobs=64)]: Done 3986 tasks      | elapsed:   56.3s
[Parallel(n_jobs=64)]: Done 4077 tasks      | elapsed:   57.0s
[Parallel(n_jobs=64)]: Done 4168 tasks      | elapsed:   57.6s
[Parallel(n_jobs=64)]: Done 4261 tasks      | elapsed:   58.3s
[Parallel(n_jobs=64)]: Done 4354 tasks      | elapsed:   59.0s
[Parallel(n_jobs=64)]: Done 4449 tasks      | elapsed:   59.7s
[Parallel(n_jobs=64)]: Done 4544 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4641 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4738 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4837 tasks      | elapsed:  1.0min
[Parallel(n_jobs=64)]: Done 4936 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5037 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5138 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5241 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5344 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5449 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5554 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5661 tasks      | elapsed:  1.1min
[Parallel(n_jobs=64)]: Done 5768 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5877 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 5986 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6097 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6208 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6321 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6434 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6549 tasks      | elapsed:  1.2min
[Parallel(n_jobs=64)]: Done 6664 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6781 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 6898 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7017 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7136 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7257 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7378 tasks      | elapsed:  1.3min
[Parallel(n_jobs=64)]: Done 7501 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7624 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7749 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 7874 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8001 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8128 tasks      | elapsed:  1.4min
[Parallel(n_jobs=64)]: Done 8257 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8386 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8517 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8648 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8781 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 8914 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9049 tasks      | elapsed:  1.5min
[Parallel(n_jobs=64)]: Done 9184 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9321 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9458 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9597 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9736 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 9877 tasks      | elapsed:  1.6min
[Parallel(n_jobs=64)]: Done 10018 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10161 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10304 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10449 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10594 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10741 tasks      | elapsed:  1.7min
[Parallel(n_jobs=64)]: Done 10888 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11037 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11186 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11337 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11488 tasks      | elapsed:  1.8min
[Parallel(n_jobs=64)]: Done 11641 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11794 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 11949 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12104 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12261 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12418 tasks      | elapsed:  1.9min
[Parallel(n_jobs=64)]: Done 12577 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12736 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 12897 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13058 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13221 tasks      | elapsed:  2.0min
[Parallel(n_jobs=64)]: Done 13384 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13549 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13714 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 13881 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14048 tasks      | elapsed:  2.1min
[Parallel(n_jobs=64)]: Done 14217 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14386 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14557 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14728 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 14901 tasks      | elapsed:  2.2min
[Parallel(n_jobs=64)]: Done 15074 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15249 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15424 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15601 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15778 tasks      | elapsed:  2.3min
[Parallel(n_jobs=64)]: Done 15957 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16136 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16317 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16498 tasks      | elapsed:  2.4min
[Parallel(n_jobs=64)]: Done 16681 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 16864 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17049 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17234 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17421 tasks      | elapsed:  2.5min
[Parallel(n_jobs=64)]: Done 17608 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17797 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 17986 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18177 tasks      | elapsed:  2.6min
[Parallel(n_jobs=64)]: Done 18368 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 18561 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 18754 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 18949 tasks      | elapsed:  2.7min
[Parallel(n_jobs=64)]: Done 19144 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19341 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19538 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19737 tasks      | elapsed:  2.8min
[Parallel(n_jobs=64)]: Done 19936 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20137 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20338 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20541 tasks      | elapsed:  2.9min
[Parallel(n_jobs=64)]: Done 20744 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 20949 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21154 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21361 tasks      | elapsed:  3.0min
[Parallel(n_jobs=64)]: Done 21568 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 21777 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 21986 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22197 tasks      | elapsed:  3.1min
[Parallel(n_jobs=64)]: Done 22408 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 22621 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 22834 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23049 tasks      | elapsed:  3.2min
[Parallel(n_jobs=64)]: Done 23264 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23481 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23698 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 23917 tasks      | elapsed:  3.3min
[Parallel(n_jobs=64)]: Done 24136 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24357 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24578 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 24801 tasks      | elapsed:  3.4min
[Parallel(n_jobs=64)]: Done 25024 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25249 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25474 tasks      | elapsed:  3.5min
[Parallel(n_jobs=64)]: Done 25701 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 25928 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26157 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26386 tasks      | elapsed:  3.6min
[Parallel(n_jobs=64)]: Done 26617 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 26848 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27081 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27314 tasks      | elapsed:  3.7min
[Parallel(n_jobs=64)]: Done 27549 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 27784 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28021 tasks      | elapsed:  3.8min
[Parallel(n_jobs=64)]: Done 28258 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28497 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28736 tasks      | elapsed:  3.9min
[Parallel(n_jobs=64)]: Done 28977 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29218 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29461 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29704 tasks      | elapsed:  4.0min
[Parallel(n_jobs=64)]: Done 29949 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30194 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30441 tasks      | elapsed:  4.1min
[Parallel(n_jobs=64)]: Done 30688 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 30937 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31186 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31437 tasks      | elapsed:  4.2min
[Parallel(n_jobs=64)]: Done 31688 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 31941 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 32194 tasks      | elapsed:  4.3min
[Parallel(n_jobs=64)]: Done 32449 tasks      | elapsed:  4.4min
[Parallel(n_jobs=64)]: Done 32640 out of 32640 | elapsed:  4.4min finished

network 9, training 0, epoch 1: train scaled MSE 0.802468; val RMSE 0.01628833; lr 0.001; 0s
network 9, training 0, epoch 10: train scaled MSE 0.028881; val RMSE 0.003269627; lr 0.001; 2s
network 9, training 0, epoch 20: train scaled MSE 0.00981673; val RMSE 0.001846144; lr 0.001; 4s
network 9, training 0, epoch 30: train scaled MSE 0.00887541; val RMSE 0.002136649; lr 0.001; 6s
network 9, training 0, epoch 40: train scaled MSE 0.00487722; val RMSE 0.001933818; lr 0.001; 8s
network 9, training 0, epoch 50: train scaled MSE 0.00389312; val RMSE 0.001472036; lr 0.001; 10s
network 9, training 0, epoch 60: train scaled MSE 0.00319794; val RMSE 0.001471669; lr 0.001; 12s
network 9, training 0, epoch 70: train scaled MSE 0.00220839; val RMSE 0.001456227; lr 0.0005; 14s
network 9, training 0, epoch 80: train scaled MSE 0.00286423; val RMSE 0.001630138; lr 0.0005; 16s
network 9, training 0, epoch 90: train scaled MSE 0.00177864; val RMSE 0.001332413; lr 0.0005; 18s
network 9, training 0, epoch 100: train scaled MSE 0.00159222; val RMSE 0.001312704; lr 0.0005; 20s
network 9, training 0, epoch 110: train scaled MSE 0.00151224; val RMSE 0.001263889; lr 0.00025; 22s
network 9, training 0, epoch 120: train scaled MSE 0.00126756; val RMSE 0.001350513; lr 0.00025; 24s
network 9, training 0, epoch 130: train scaled MSE 0.00114512; val RMSE 0.00123967; lr 0.000125; 26s
network 9, training 0, epoch 140: train scaled MSE 0.00114846; val RMSE 0.001241198; lr 0.000125; 28s
network 9, training 0, epoch 150: train scaled MSE 0.00120204; val RMSE 0.001237043; lr 0.000125; 30s
network 9, training 0, epoch 160: train scaled MSE 0.00113976; val RMSE 0.001236163; lr 0.000125; 32s
network 9, training 0, epoch 170: train scaled MSE 0.00106061; val RMSE 0.001230603; lr 6.25e-05; 34s
network 9, training 0, epoch 180: train scaled MSE 0.000972681; val RMSE 0.001221941; lr 6.25e-05; 36s
network 9, training 0, epoch 190: train scaled MSE 0.000957264; val RMSE 0.001219361; lr 6.25e-05; 38s

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [4]:
mlp_ci_table = (
    all_results_df
    .query("Model == 'MLP'")
    .pivot(
        index="Training Seed",
        columns="Network Seed",
        values="MSE Improv. 95% CI"
    )
)

display(mlp_ci_table)

Network Seed,0,1,2,3,4,5,6,7,8,9
Training Seed,,,,,,,,,,
0,"[-24.85%, 3.28%]","[-43.83%, -9.31%]","[-54.01%, -25.27%]","[-40.89%, -10.22%]","[-6.95%, 23.34%]","[25.58%, 50.16%]","[0.69%, 34.45%]","[-4.86%, 23.09%]","[10.91%, 51.03%]","[16.49%, 55.89%]"
1,"[-23.36%, 23.99%]","[-45.20%, -9.71%]","[-42.76%, -23.48%]","[-56.67%, -6.03%]","[6.20%, 26.03%]","[27.24%, 51.40%]","[12.48%, 32.52%]","[5.13%, 24.23%]","[-13.17%, 53.43%]","[10.08%, 49.75%]"
2,"[-14.63%, 9.26%]","[-14.96%, 4.80%]","[-48.85%, -21.75%]","[-57.96%, -16.20%]","[-6.43%, 15.82%]","[32.55%, 50.12%]","[12.93%, 37.45%]","[20.37%, 38.74%]","[-53.38%, 48.32%]","[21.45%, 48.53%]"
3,"[-84.41%, -27.44%]","[-15.31%, 11.93%]","[-38.47%, -14.23%]","[-64.66%, -24.72%]","[1.25%, 27.20%]","[27.62%, 48.32%]","[-6.06%, 25.25%]","[5.56%, 27.92%]","[34.99%, 51.18%]","[30.74%, 55.55%]"
4,"[-14.36%, 26.40%]","[-29.63%, 3.21%]","[-42.73%, -18.27%]","[-51.91%, -14.74%]","[0.91%, 24.48%]","[36.35%, 57.50%]","[4.57%, 37.25%]","[-4.19%, 24.95%]","[32.56%, 60.46%]","[11.05%, 55.84%]"
5,"[-57.69%, 0.82%]","[-28.90%, 3.57%]","[-42.45%, -16.05%]","[-44.32%, -10.32%]","[-0.49%, 23.94%]","[29.50%, 52.16%]","[8.56%, 28.80%]","[12.57%, 34.03%]","[23.24%, 67.47%]","[30.24%, 56.49%]"
6,"[-22.65%, 0.01%]","[-23.08%, 13.60%]","[-64.65%, -34.68%]","[-54.16%, -17.67%]","[-1.43%, 23.71%]","[24.41%, 47.68%]","[1.42%, 31.80%]","[14.59%, 35.01%]","[31.83%, 59.18%]","[21.74%, 53.11%]"
7,"[-29.59%, 20.40%]","[-15.65%, 28.78%]","[-52.45%, -25.50%]","[-51.47%, -8.72%]","[1.29%, 28.33%]","[28.83%, 46.98%]","[10.94%, 41.30%]","[18.83%, 35.14%]","[29.83%, 71.65%]","[28.69%, 59.16%]"
8,"[-11.19%, 32.98%]","[-11.62%, 23.04%]","[-49.88%, -20.89%]","[-50.64%, -21.71%]","[-12.19%, 17.40%]","[25.55%, 50.71%]","[11.79%, 36.00%]","[15.70%, 35.26%]","[11.98%, 53.73%]","[31.96%, 46.31%]"
9,"[-15.06%, 12.40%]","[-41.85%, -6.04%]","[-44.62%, -17.65%]","[-45.52%, -10.06%]","[-8.31%, 16.10%]","[29.34%, 51.33%]","[2.08%, 29.13%]","[5.13%, 33.58%]","[34.02%, 58.84%]","[8.02%, 52.14%]"

In [5]:
mlp_ci_table = (
    all_results_df
    .query("Model == 'MLP'")
    .pivot(
        index="Training Seed",
        columns="Network Seed",
        values="MSE Improvement vs Additive (%)"
    )
)

display(mlp_ci_table)

Network Seed,0,1,2,3,4,5,6,7,8,9
Training Seed,,,,,,,,,,
0,-8.279761,-25.080205,-37.420500,-22.489317,14.265073,38.916124,20.912626,9.605272,34.088205,39.189121
1,13.467215,-25.743465,-31.585585,-26.609285,17.945392,39.628655,23.783974,15.730771,29.350265,32.828715
2,0.684769,-3.929866,-33.624948,-31.373398,7.047897,41.687451,25.794249,29.816249,5.531624,36.342548
3,-46.188922,-0.214643,-24.129350,-39.461119,17.944355,38.718429,13.427269,17.493844,43.588937,45.185535
4,5.757635,-12.105118,-29.022836,-29.313645,15.620344,47.585345,22.365626,11.777680,48.177324,36.716998
5,-21.548852,-11.153580,-26.189068,-23.366090,15.151538,41.795919,20.311578,24.249073,50.922569,44.913896
6,-8.533990,-4.323529,-46.454928,-32.723388,13.766134,36.624880,19.377537,25.678687,46.676424,40.529287
7,5.629139,7.495240,-37.544963,-25.063104,18.752930,38.616331,27.984417,27.512118,56.194618,45.168782
8,18.908670,6.548808,-33.086014,-33.714648,6.701831,37.909628,25.307224,26.344443,36.106447,39.374934
9,1.763325,-21.274536,-29.490286,-24.156187,7.715919,41.023383,16.794471,19.846366,48.107757,32.880021